### ISSUE TITLE
Cleanup style sheets

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#1004]
- Remove`!important` from css rules
- Remove logic_release.scss and move styles to corresponding stylesheets
- Run scss-lint on all scss files and fix the violations
- Remove custom css and use builtin bootstrap classes wherever possible

- Move inline styles in views to CSS

**Comment by ShubhankarKG** [comment]
I can take up this one @tachyons . I'll get back in a day.

**Comment by mahmodHammad** [comment]
I Want to work on this issue

**Comment by abstrekt** [comment]
Would be very great if it is done

**Comment by Kushagraw12** [comment]
@tachyons  os this done, or can i take it up? 
Thanks!

**Comment by aayush-05** [comment]
@tachyons this can be closed >> Completed with the frontend code refactor
