### ISSUE TITLE
Adding Back button to Edit Profile Page

### ISSUE THREAD

**Issue by darkshredder** [CircuitVerse/CircuitVerse#1009]
**Is your feature request related to a problem? Please describe.**
Its annoying to click on browser back button to go back on Edit profile page

**Describe the solution you'd like**
Add a back button To it

**Are you working on this? (Yes/No)**
Yes

**Comment by darkshredder** [comment]
[https://github.com/CircuitVerse/CircuitVerse/pull/1008](url)

**Comment by darkshredder** [comment]
#1008

**Comment by darkshredder** [comment]
#1008

**Comment by darkshredder** [comment]
[https://github.com/CircuitVerse/CircuitVerse/pull/1008](url)

**Comment by darkshredder** [comment]
#1008

**Comment by PavlosMak** [comment]
Hello! I would like to work on this if it is fine by you.

**Comment by darkshredder** [comment]
Actually I have already opened a PR

**Comment by PavlosMak** [comment]
Oh alright then. Thank you!
