### ISSUE TITLE
Bottom Logo Overlapping with Text on zoom

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1019]
**Describe the bug**
The links in the bottom get overlapped by the Logo image when user zooms in.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Zoom to  '150% or 175%'
3. Scroll down to 'footer'

**Expected behavior**
The Overlapping must be removed.

**Screenshots**
![Issue5](https://user-images.githubusercontent.com/42182955/75904079-8fc6c680-5e68-11ea-8997-8c0b53cd80d3.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Additional context**
I will also be increasing the logo size to make it look more catchy. Let me know your views on this.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shivansh2407** [comment]
@tachyons and @nitin10s review 👍

**Comment by abstrekt** [comment]
what app did you used for the screen record? @Shivansh2407

**Comment by Shivansh2407** [comment]
@abstrekt I use Apowersoft Online screen recorder.

**Comment by tachyons** [comment]
Thanks for reporting the issue

**Comment by Shivansh2407** [comment]
#1020 is a PR ready for this Issue @nitin10s . Please reopen this issue .
