### ISSUE TITLE
Navbar button not working on small screen

### ISSUE THREAD

**Issue by rishipurwar1** [CircuitVerse/CircuitVerse#1022]
When CircuitVerse simulator open in small screen, navbar button not working.

1. Go to simulator page
2. Click on navbar button

Expected behavior
It should show all navbar items when user click on this button.

Are you working on this issue?
 Yes

**Comment by rishipurwar1** [comment]
I am working on this

**Comment by yash15601** [comment]
Mention the browser?? @rishipurwar1

**Comment by rishipurwar1** [comment]
OS-Windows 10 pro 
Gooogle Chrome
