### ISSUE TITLE
No illustration for mobile view in Login & Sign-Up [New UX]

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1026]
**Describe the bug**
In the new_UX,
The mobile view of Login and Sign-Up should not have the illustration that is present in the Desktop View.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Login/Sign-Up on a mobile device

**Expected behaviour**
No illustration to be shown in the mobile view.

**Screenshots**
![login](https://user-images.githubusercontent.com/16988558/76028959-9a14bd80-5f59-11ea-8711-bfdbb4cd0edd.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by rishipurwar1** [comment]
I am working on this

**Comment by rishipurwar1** [comment]
![signup](https://user-images.githubusercontent.com/57035408/76058283-f7ccf800-5fa1-11ea-88a9-f6322ecd47cb.png)
![login](https://user-images.githubusercontent.com/57035408/76059067-ed136280-5fa3-11ea-8e47-766d8a74e928.png)

Please check it
Is it fixed now? @nitin10s

**Comment by Ananthavijay** [comment]
@satu0king @tachyons This issue can be closed
