### ISSUE TITLE
No feedback when on Login Page [New UX]

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1027]
**Describe the bug**
Whenever a user is on pages like Examples, Teachers, About., there is navigation feedback on the navbar [ The selected menu is underlined ]. But when a user is on Login Page, there is no navigational feedback. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Teachers Page
2. Check the Teachers Section is underlined to provide navigational feedback
3. Now click on Login Section
4. No navigational feedback

**Expected behavior**
Navigation feedback for Login Page as well.

**Screenshots**
![loginp](https://user-images.githubusercontent.com/16988558/76029508-a1889680-5f5a-11ea-9f71-3b128d53f63b.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by yash15601** [comment]
Can I work on this @nitin10s ?
