### ISSUE TITLE
Simulator project title is not align properly

### ISSUE THREAD

**Issue by rishipurwar1** [CircuitVerse/CircuitVerse#1028]
When simulator page is open in mobile, the project title doesn't align properly

1. Go to the simulator in the mobile phone and click on navbar button
2. See error
Expected behavior
it should be aligned in the center

Are you working on this issue? 
Yes

**Comment by Shivansh2407** [comment]
@rishipurwar1 If you dont mind, I would Like to work on this issue as I have a completely working solution for this. I just need to open up a PR.

**Comment by Shivansh2407** [comment]
Working on this 👍

**Comment by rishipurwar1** [comment]
> @rishipurwar1 If you dont mind, I would Like to work on this issue as I have a completely working solution for this. I just need to open up a PR.
I close my pull request. You start working on it and make a pr.

**Comment by aayush-05** [comment]
Can you please check it again @rishipurwar1 ? It seems to work fine for me.
![image](https://user-images.githubusercontent.com/47032027/76090642-f0c5da00-5fe1-11ea-83da-74410ac96942.png)

**Comment by Shivansh2407** [comment]
> Can you please check it again @rishipurwar1 ? It seems to work fine for me.
> ![image](https://user-images.githubusercontent.com/47032027/76090642-f0c5da00-5fe1-11ea-83da-74410ac96942.png)

When I opened Gitpod for the same , It showed some problems and overlaps , I will be opening a PR please see that and let me know your views

**Comment by rishipurwar1** [comment]
Are you running locally @aayush-05

**Comment by aayush-05** [comment]
Yes, it is now visible after I pulled from the current master.
![image](https://user-images.githubusercontent.com/47032027/76091351-6aaa9300-5fe3-11ea-9f15-59af376107c2.png)
Go ahead @Shivansh2407
