### ISSUE TITLE
Group Page can look better [new UX]

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1033]
Issues that I found on `/groups/:id`

- Button for removing a user from a group needs some more margin on long usernames
- `Add Member` and `Add new Assignment` should be in same line as their headers, for now, there is wired empty space between header and content of the section
- Margin above group name is bigger than the margin below `Back` button

**Additional context**
![image](https://user-images.githubusercontent.com/23432278/76092099-1988a800-5fbf-11ea-8da2-59175abe2dac.png)

**Are you working on this? (Yes/No)**
No

**Comment by Nitish145** [comment]
I am working on this issue 🙂
