### ISSUE TITLE
White button hover on groups list

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1034]
**Describe the bug**
The button hover is white and its blends with background

**Screenshots**
![image](https://user-images.githubusercontent.com/23432278/76093327-0f67a900-5fc1-11ea-8e0e-9695dd7456b5.png)
![image](https://user-images.githubusercontent.com/23432278/76093340-17274d80-5fc1-11ea-86c7-df4a03dfd639.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by rishipurwar1** [comment]
I want to work on this issue

**Comment by darkshredder** [comment]
@rishipurwar1 If you dont mind can I work on this??

**Comment by rishipurwar1** [comment]
I already working on this. @darkshredder

**Comment by rishipurwar1** [comment]
It's OK @darkshredder
