### ISSUE TITLE
Can't see icons while editing layout.  [new UX]

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#1041]
**Describe the bug**
glyphicons not working in `simulator\embed.html.erb`  and  `simulator\edit.html.erb`. 

**To Reproduce**
1. Go to 'localhost/3000'
2. Try edit layout option or look for this:

![image](https://user-images.githubusercontent.com/32474302/76138207-9f622d00-606b-11ea-9675-b73f3eeb08a6.png)

**Expected behavior**
this is not visible:
![image](https://user-images.githubusercontent.com/32474302/76138192-7a6dba00-606b-11ea-96f5-8d5e5d08290c.png) 
these icons not visible:
![image](https://user-images.githubusercontent.com/32474302/76138197-88233f80-606b-11ea-9e26-08ad3cde9db7.png) 
also the icons used in `embed.html.erb` not visible

**Desktop (please complete the following information):**

**Additional context**
I think importing glyphicons will work. 

**Are you working on this issue? (Yes/No)**
No.

**Comment by Shivansh2407** [comment]
I would like to work on this @shubhankarsharma00 .

**Comment by shubhankarsharma00** [comment]
Ok

**Comment by nitin10s** [comment]
This is because we're using Bootstrap 4 which has dropped the support for Glyphicons. Since we are already using Font-Awesome, we can use it as a replacement.

**Comment by shubhankarsharma00** [comment]
@nitin10s what if we import glyphicons from bootstrap 3 ?

**Comment by Shivansh2407** [comment]
> @nitin10s what if we import glyphicons from bootstrap 3 ?

I have completed fixing the issue with Font Awesome . It is now working and I will open the PR soon.

**Comment by shubhankarsharma00** [comment]
Ok Nice

**Comment by satu0king** [comment]
Fixed in #1082
