### ISSUE TITLE
Learn logic design link should be button

### ISSUE THREAD

**Issue by rishipurwar1** [CircuitVerse/CircuitVerse#1043]
On the homepage, currently learn logic design is a link but I think it should be a button.

1. Go to the homepage
4. See logic learn link
![bug](https://user-images.githubusercontent.com/57035408/76139366-09330480-6075-11ea-95df-806dd5e13792.png)

**Expected behavior**
It should be a button
![budc](https://user-images.githubusercontent.com/57035408/76139373-15b75d00-6075-11ea-9531-7b3950a4ad66.png)

Are you working on this issue? 
Yes, I am working on this.

**Comment by rishipurwar1** [comment]
I am working on this

**Comment by nitin10s** [comment]
"learn logic design" is indeed a button and is made that way to look distinctive on purpose. @tachyons Please close this issue.
