### ISSUE TITLE
Not responsive buttons on index

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1044]
**Describe the bug**
`For Teachers` and `For Contributors` buttons should be centred on mobile version

**Screenshots**
![image](https://user-images.githubusercontent.com/23432278/76140376-18f11f80-605a-11ea-86ce-305861c2d859.png)

**Desktop (please complete the following information):**
 - Chrome Dev Tools iPhone X Emulation

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
Working on this issue 🙂

**Comment by rishipurwar1** [comment]
please tell me where is index.html located?

**Comment by MrBartusek** [comment]
@rishipurwar1 That is `app\views\logix\index.html.erb`
BTW: If you need help any help best place to ask is our [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE)
BTW2: @Nitish145 is already working on that

**Comment by rishipurwar1** [comment]
Thanks @MrBartusek.

**Comment by aayush-05** [comment]
They are explicitly left idented, check the prototype.

**Comment by MrBartusek** [comment]
@aayush-05 I am thinking only about mobile

**Comment by nitin10s** [comment]
Yes, for mobile they would look better centre aligned.

**Comment by yash15601** [comment]
![image](https://user-images.githubusercontent.com/49101492/76192218-4deea500-6207-11ea-8418-b9a86cbbf471.png)
i did this for iphone x but in it look like this will it okk
![image](https://user-images.githubusercontent.com/49101492/76192298-7b3b5300-6207-11ea-89e3-ea34d9cce386.png)
@nitin10s  @MrBartusek  your views please

**Comment by nitin10s** [comment]
Ok.

**Comment by yash15601** [comment]
@nitin10s I think  this is fixed some one was working on this

**Comment by nitin10s** [comment]
Is the PR merged?

**Comment by yash15601** [comment]
@nitin10s  no @mahmodHammad  is facing some issue

**Comment by nitin10s** [comment]
@mahmodHammad link this issue with your PR.

**Comment by MrBartusek** [comment]
Idk what fixed it but, fixed

![image](https://user-images.githubusercontent.com/23432278/80944482-fd9c5980-8de9-11ea-9176-2d927f6c749f.png)
