### ISSUE TITLE
Footer Elements not centered

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1045]
**Describe the bug**
I made this bug report for mobile footer cause it shows more problems than desktop but, some of the problems are desktop too and should be fixed

- The logo is not centred
- Social media icons are too far to the right
- Titles are not aligned to the content (`Circuits`, `Info`, `Sponsors`)

**Screenshots**

![image](https://user-images.githubusercontent.com/23432278/76140472-09260b00-605b-11ea-8cb9-2f1de0bf58a8.png)

**Desktop (please complete the following information):**
- Chrome Dev Tools iPhone X Emulation

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
Would be happy to work , similar to previous one
