### ISSUE TITLE
Educational Institute Typeahead Not Working

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1046]
**Describe the bug**
Typeahead endpoint throws 505

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/users/:id/profile/edit`
2. Type to `Educational institute` and look for network monitor

**Screenshots**

![image](https://user-images.githubusercontent.com/23432278/76140718-9bc7a980-605d-11ea-85d3-de68e73b5ce2.png)

![image](https://user-images.githubusercontent.com/23432278/76140721-a41fe480-605d-11ea-8102-79861e08234b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by aayush-05** [comment]
Are you not able to save the value provided for Educational Institute as well ?

**Comment by MrBartusek** [comment]
@aayush-05 Saving works fine

**Comment by Shivansh2407** [comment]
@MrBartusek Can You please elaborate more about the issue so that I can help in fixing this.

**Comment by MrBartusek** [comment]
@Shivansh2407 i don't know what is causing that

**Comment by Shivansh2407** [comment]
Okay, @aayush-05 do have any clue about this?

**Comment by Ananthavijay** [comment]
Can I work on this issue?

**Comment by Shivansh2407** [comment]
Actually @Ananthavijay I am working on it

**Comment by tachyons** [comment]
> @Shivansh2407 i don't know what is causing that
pluck returns an array and you can't use limit after that
