### ISSUE TITLE
Background of new UX pages blends with page background

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1047]
**Describe the bug**
The content of pages using this layout is inside the grey box which blends with a grey background

**Screenshots**
![image](https://user-images.githubusercontent.com/23432278/76140766-e9dcad00-605d-11ea-90dd-122dc7f26284.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Additional context**
I don't know how to fix it to make it good looking, Ask on Slack

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
I would like to work on this 👍

**Comment by yash15601** [comment]
@MrBartusek  Can you please elaborate  what you are trying  to say

**Comment by yash15601** [comment]
@MrBartusek  I tryed with the grey background  it looks odd

**Comment by Shivansh2407** [comment]
Yes please elaborate the issue @MrBartusek .

**Comment by MrBartusek** [comment]
@yash15601 @Shivansh2407 Moved to [Slack](https://circuitverse-team.slack.com/archives/CQ17325A5/p1583583189203400)

**Comment by aayush-05** [comment]
Not sure if this is what you meant, but if you are saying the border of that div blends in with the background, then it is what meant to be done. The border of that div has been explicitly set to zero. @MrBartusek

**Comment by yash15601** [comment]
@MrBartusek  yes the border is set to Zero , i think this what you are trying to say

**Comment by Shivansh2407** [comment]
So should I just add border to the Div? @MrBartusek @nitin10s

**Comment by yash15601** [comment]
@Shivansh2407 no Dont add border it dosent look good i tryed when  i was desiging this

**Comment by nitin10s** [comment]
Don't do any anything for now.

**Comment by MrBartusek** [comment]
Closing for now, please mention me here if anyone will have an idea how to fix it
