### ISSUE TITLE
"Social" Icons need to be more clickable

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1048]
**Describe the bug**
These icons need to be clickable on the whole surface (not only one point) and need some kind of hover animation

**Screenshots**

`/contribute`
![image](https://user-images.githubusercontent.com/23432278/76141052-11814480-6061-11ea-8891-aee822f7b0a6.png)
![image](https://user-images.githubusercontent.com/23432278/76141062-2362e780-6061-11ea-8e5d-9ed3bb5f6fac.png)

`/about`
![image](https://user-images.githubusercontent.com/23432278/76141058-1d6d0680-6061-11ea-9b6d-40ad869efc04.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
I would like to work on this 👍

**Comment by Ananthavijay** [comment]
This has been fixed in this PR: https://github.com/CircuitVerse/CircuitVerse/pull/1011

**Comment by MrBartusek** [comment]
@Ananthavijay Ok, Can you add hovers to your PR too?
I will appreciate adding `Fixes #1048` to your PR too

**Comment by Ananthavijay** [comment]
yep will do it asap

**Comment by MrBartusek** [comment]
@Ananthavijay these 2 don't have hover yet
![image](https://user-images.githubusercontent.com/23432278/76142770-f3bbdb80-6070-11ea-9b23-df94333fa0be.png)

@tachyons can you re-open?

**Comment by Ananthavijay** [comment]
My bad 🤦‍♀

**Comment by nitin10s** [comment]
@Ananthavijay can you please add hover to those two buttons as well?

**Comment by Ananthavijay** [comment]
will do it asap
