### ISSUE TITLE
Pages and footer left & right margins

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1049]
**Describe the bug**
Margin to centre content of pages to don't spill out to the whole screen are too big

![cv1](https://user-images.githubusercontent.com/23432278/76141343-7b9ae900-6063-11ea-8ffd-6d358bc033a3.png)

The footer should have the same margins as page content _That might create conflicts with #1045_

![c2](https://user-images.githubusercontent.com/23432278/76141357-a2591f80-6063-11ea-9ed1-b892c1f64d85.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
On it, will also take care of conflict..

**Comment by nitin10s** [comment]
I don't understand the issue completely. I see the footer is not centre aligned and I agree with that issue but what else are you trying to say?

**Comment by aayush-05** [comment]
I think he is talking about the increased margin space on the left and right, but it seems to be fine on my screen. 
![image](https://user-images.githubusercontent.com/47032027/76143974-b3288600-60a1-11ea-9d80-b2f684c6d5d6.png)

Can you check on your machine @nitin10s ?

**Comment by MrBartusek** [comment]
@nitin10s I am thinking about 2 issues here, margins on left and right of the page are too big on big screens (like mine) and footer should have the same margins as content in my opion

**Comment by aayush-05** [comment]
We are using bootstrap containers as of now, I think either we can explicitly increase the max-width for larger displays to reduce the margins. 
![image](https://user-images.githubusercontent.com/47032027/76145585-9ba4c980-60b0-11ea-8361-5c14edbabad0.png)
Footer can be made uniform with the rest of the content.

**Comment by nitin10s** [comment]
For the first issue - I agree with what @aayush-05 mentioned
For the second issue - There is no hard and fast rule for that footer. Moreover, since our footers have various elements, I'd say it's ok to keep it that way.

**Comment by Nitish145** [comment]
What changes needs to be done then in footer ? @nitin10s

**Comment by MrBartusek** [comment]
@nitin10s 
@Nitish145 pr was for #1045 can you re-open that
