### ISSUE TITLE
"Hover Effect" on buttons(in About page) make them invisible 

### ISSUE THREAD

**Issue by akansha-singh** [CircuitVerse/CircuitVerse#1050]
**Describe the bug**
"Hover Effect" on these buttons make them invisible and After visiting the buttons it looks like as shown in 2nd pic.
 
**To Reproduce**
1. Go to 'About' page
2. Hover on The buttons 'Terms of Service ' and 'Privacy policy' 
![WhatsApp Image 2020-03-07 at 17 43 10](https://user-images.githubusercontent.com/47236824/76143182-44e0c500-609b-11ea-8943-fd91bb1e5642.jpeg)
3.Click on the button then go back to the previous page  and see bug ![WhatsApp Image 2020-03-07 at 18 13 29](https://user-images.githubusercontent.com/47236824/76143749-013c8a00-60a0-11ea-8666-722c6a3badbd.jpeg)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : chrome, Firefox

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aayush-05** [comment]
It has been updated, pull from the latest master
