### ISSUE TITLE
Recent circuits not being shown in Homepage

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#1058]
**Describe the bug**
Recent circuits not being shown in Homepage

**To Reproduce**
1. Start the server
2. Scroll down 
3. See error

**Expected behavior**
Recent circuits should be shown in Homepage

**Screenshots**
![image](https://user-images.githubusercontent.com/35162705/76147821-1e844f00-60c6-11ea-909b-a110dfe5f8a1.png)

**Desktop (please complete the following information):**
 - Environment: Gitpod
 - Browser: chrome

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
I would like to work on this 👍
