### ISSUE TITLE
Additional in out component ideas

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#106]
Here, have a few more component ideas :P 

- [ ] **Servo Motor**
A servo motor, which will operate using standard servo input, i.e. the angle the servo should rotate too is represented by the length of time it recieves in a pulse. I.E holding a pulse for 9 ticks will make it go to 90°, a pulse for 17 ticks will make it go to 180°, a pulse for 1 tick will make it go to 0°

- [ ] **Square button**
Since we got a square LED, why not a square button? It's essentially the same concept as the square LED but as a button.

- [ ] **Button matrix** 
A matrix of buttons. It's size can be adjusted to suit the users needs. It has H many inputs and W many outputs. When an input is one, it will output the state of each button on the corresponding row.

**Comment by satu0king** [comment]
The idea of a servo motor has in CircuitVerse has been mentioned before by a professor, However I am not sure if it is implementable or practical in the current design of CV. 

Square button, is definitely doable. 

Button matrix - I am not sure I got what this actually is. Is it like there is a matrix of buttons but u can access the values of the buttons only row by row? This seems a very strange use case according to me.
