### ISSUE TITLE
minor style issues at about page  

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1064]
**Describe the bug**
- white space need to be adjusted at  about page 
- our team doesn't look good at md screens 
- terms of Service & privacy needs to be centered

**To Reproduce**
- Go to 'http://localhost:3000/about'

**Expected behavior**
white space should be equal on both sides to look better

**Screenshots**
![before](https://user-images.githubusercontent.com/41790090/76154035-3d8edb00-60de-11ea-968c-9efda4940257.PNG)
our team at md screen 
![image](https://user-images.githubusercontent.com/41790090/76153995-78dcda00-60dd-11ea-87c9-db41538742e1.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome

**Are you working on this issue? (Yes/No)**
YES

**Comment by mahmodHammad** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/1065

**Comment by nitin10s** [comment]
Hey, This "Our Team" section is outdated, so we don't need to make changes on this, we'll be designing a new section in a couple of days.
