### ISSUE TITLE
Component selection size issues

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#107]
There are a number of components in Circuit Verse which have a selection area which extends outside their graphical size, or which has their selection area overlap their pins. These components are often troublesome, to work with, and need to be fixed.

For sake of time, I will refer to the selection area as the "Hit Box"

- [x] Decoder, Multiplexer, Demultiplexer
When the Decoder, Multiplexer or Demultiplexer is given a selection bitwidth of 1, the graphic of the component is smaller than it would be when at a bitwidth of 2 or more. At a larger bitwidth, these components are 4 units wide, and vary in height depending on their settings. However, when there is a bitwidth of 1, these components appear 2 units wide, but still retain the 4 unit wide hit box they had before.

- [x] Power and ground
The power and ground pin's hit box is straight up too big. This should otherwise be an easy fix.

**Comment by fpintos** [comment]
It looks like the issue is not only with the component dimension but also with the rounding on the simulation.mouseX and mouseY; it makes the component think it is being hovered even when the mouse is half-a-square away.
