### ISSUE TITLE
Navbar position should be ' Fixed ' static on the top when Scroll .

### ISSUE THREAD

**Issue by akansha-singh** [CircuitVerse/CircuitVerse#1078]
**Isyour feature request related to a problem? Please describe.**
On scroll .. The position of the Navbar should be fixed on the Top.

**Additional context**
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/47236824/76163167-f817ef80-6169-11ea-91d2-d21e8b6a8349.gif)

**Describe the solution you'd like**

**Desktop (please complete the following information):**
    Environment: Gitpod
    Browser: Chrome

**Are you working on this? (Yes/No)**
Yes

**Comment by rishipurwar1** [comment]
Are you still working on it?
If not, I would like to work on it..

**Comment by akansha-singh** [comment]
> Are you still working on it?
> If not, I would like to work on it.. @akansha-singh

yeah I am working

**Comment by akansha-singh** [comment]
I am just 1 PR away to fix this issue
