### ISSUE TITLE
Footer breaking in Ipad (potrait) & Iphone X/XS (landscape)

### ISSUE THREAD

**Issue by abstrekt** [CircuitVerse/CircuitVerse#1079]
**Describe the bug**
Refer screenshot

**Screenshots**
![footer ipad potrait](https://user-images.githubusercontent.com/42478217/76163718-9c9c3080-616e-11ea-8fc2-46ed6617d650.png)

![footer iphoneX land](https://user-images.githubusercontent.com/42478217/76163719-9efe8a80-616e-11ea-8427-fd9463328354.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
Similar to #1019 . I am working on it to get it fixed soon .

**Comment by aayush-05** [comment]
This can be closed @tachyons
