### ISSUE TITLE
Add Cursor on simulator circuit elements

### ISSUE THREAD

**Issue by darkshredder** [CircuitVerse/CircuitVerse#1088]
**Is your feature request related to a problem? Please describe.**
Add Cursor on simulator circuit elements and canvas 
**Describe the solution you'd like**
Cursor changes to pointer on circuit elements chosen and on canvas while grabing changes to grabing and so on.

**Are you working on this? (Yes/No)**
Yes

**Comment by satu0king** [comment]
Fixed in #966
