### ISSUE TITLE
Demultiplexer Bug

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#109]
https://circuitverse.org/users/2373/projects/7979

**Comment by Amansingla97** [comment]
can you please elaborate on this issue

**Comment by armudgal** [comment]
@Amansingla97 Please go through the link, the description has mentioned the issue, if you have any questions after that please post

**Comment by satu0king** [comment]
This is a tough issue. I wasn't able to diagnose the bug. So the first part of the fixing this issue is finding out why is he not able to save (data is corrupted but what actually is the corruption?). The second part is figuring out how it happened and third part is fixing it.

**Comment by ankur54** [comment]
Is there always a loading diamond going on over the circuit diagram?
