### ISSUE TITLE
Stars to the Project Not working properly

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1090]
**Describe the bug**

- [ ] The Icon of Star is not available so we cannot identify how to star it .
- [ ] On clicking the star the rating decreases to -1, -2, -3 and so on.
- [ ] A user must not give more than one star to the circuit (ideally).

**To Reproduce**
1. Go to 'New UI either through gitpod or clone the repo and on Localhost'
2. Log In => Create a Circuit
3. Go to Any One circuit

**Expected behavior**
The stars must work properly . Icon should be available, the rating must increase, and also the user must give only one star .

**Screenshots**
![Issue7](https://user-images.githubusercontent.com/42182955/76197991-2ac9f280-6213-11ea-9149-89fe8ec5dd13.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shivansh2407** [comment]
I am working on this , @tachyons please let me know your views on this issue.

**Comment by Ananthavijay** [comment]
@shivansh2407 This is in old UI. Please check the new UI. This can be closed

**Comment by yash15601** [comment]
Yes @Shivansh2407  even I was bit confused  about ui update your repo

**Comment by Shivansh2407** [comment]
Oh Sorry , Actually I got a bit confused with the Old and New UI . Thank you for informing @Ananthavijay and @yash15601 👍 . Updated my repo 😅

**Comment by Shivansh2407** [comment]
Closing This issue 👍
