### ISSUE TITLE
Stars Not Working Properly

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1091]
**Describe the bug**
Whenever I star any of my circuit then it gets starred. Now when I get to my circuits page and then from there navigate to that particular circuit again a the glowing star is not shown but it remains in my favourites . 

**To Reproduce**
1. Go to 'New UI (Gitpod or Recent repo clone)'
2. Click on 'My circuits'
3. Star any circuit

**Expected behavior**
Stars must glow when the user returns back to page after starring the project

**Screenshots**
![issue8](https://user-images.githubusercontent.com/42182955/76205257-e09b3e00-621f-11ea-8f24-6d306852f67c.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes I would like to work on this .

**Comment by Shivansh2407** [comment]
I would like to know your views on this @satu0king , @tachyons and @nitin10s 👍

**Comment by Ananthavijay** [comment]
This is fixed in this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/1057)

**Comment by Shivansh2407** [comment]
Is the star now shining too when the user returns back to the same page @Ananthavijay ?

**Comment by Ananthavijay** [comment]
No it doesnt

**Comment by Shivansh2407** [comment]
So I will update the Issue . Thank you for informing @Ananthavijay
