### ISSUE TITLE
Add watermark with link in embed mode when embedded in external tools 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#11]
If bloggers/teachers embed circuits from CircuitVerse in external places like powerpoint/blogs. A watermarks or banner such as "Made with CircuitVerse" or "View on CircuitVerse" needs to be displayed.

**Comment by mohammedsafwat** [comment]
I have added a light grey watermark that's saying "Made with CircuitVerse" at the bottom of any circuit image that will be exported. Kindly inform me if you need it to be adjusted in another way. Thank you!

**Comment by dhyey35** [comment]
@satu0king I had like to work on this issue. Will ask you if I have any doubts

**Comment by Amansingla97** [comment]
@dhyey35  are you still working on it ? I would like to work on this

**Comment by dhyey35** [comment]
@Amansingla97 Go ahead
