### ISSUE TITLE
Make the script part of CircuitVerse a React/TypeScript/WebPack application

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#110]
Just putting these cards on the table...

Making this a TypeScript application will help ensure all parts of the system are properly written, at least from a type perspective. I've noticed, for example, how several components that "numeric" properties but the change functions end up receiving strings. TypeScript would help keep things like that in check and will help us know what references what.

React can deal with the HTML and SVG parts of it.

Finally, we can use WebPack to package and optimize the resulting code.

**Comment by satu0king** [comment]
Yes, this is one of the steps we need to take to increase the stability of the system.
