### ISSUE TITLE
on Hover menu to be highlighted in navbar

### ISSUE THREAD

**Issue by swarali15** [CircuitVerse/CircuitVerse#1102]
**Describe the bug**

**To Reproduce**
1. Go to https://beta.circuitverse.org/
2. Hover on navbar links

**Expected behavior**
On hover the menu or links should get highlighted or underlined

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser chrome
 

**Additional context**
Adding text-decoration:underline
will solve this problem

**Screenshots**
![ONhover](https://user-images.githubusercontent.com/51054329/76284209-a5058000-62c2-11ea-9248-3404a2dd8ca1.gif)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by yash15601** [comment]
@swarali15  are you working on this or should i make pr i have fixed this

**Comment by swarali15** [comment]
> @swarali15 are you working on this or should i make pr i have fixed this

I am working on it

**Comment by yash15601** [comment]
Okay

**Comment by darkshredder** [comment]
btw it should beborder-bottom: 2px solid #42b983; not text-decoration: underline;

**Comment by swarali15** [comment]
okay

**Comment by yash15601** [comment]
@swarali15  hey are you Still working on it or should i make pr i have my pr ready

**Comment by darkshredder** [comment]
mine is ready as well 😂😂

**Comment by swarali15** [comment]
@yash15601  and @darkshredder I think on hover the links should get scaled or changed color of text because active links are already being highlighted using border bottom.

**Comment by yash15601** [comment]
@swarali15  i think you are right @nitin10s  what is your Review can we color text on hover

**Comment by nitin10s** [comment]
Already resolved
