### ISSUE TITLE
Overlapping content on User Projects page

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1106]
**Describe the bug**
The dialog for showing no projects/circuits and the favourites button are overlapping on mobile displays.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/76289257-b48ac600-62ce-11ea-8b68-a39e291589f0.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Nitish145** [comment]
Do you mind if I work on this issue ?

**Comment by aayush-05** [comment]
No problem, go ahead @Nitish145

**Comment by yash15601** [comment]
@aayush-05  @Nitish145  this page have lot of bugs in mobile and ipad view in ipad view the footer is not at the bottom
Screenshot:
![image](https://user-images.githubusercontent.com/49101492/76299564-51eef580-62e1-11ea-91d3-c0c520dc44c0.png)

media queires are  missing for some devices 
 screenshot:
![image](https://user-images.githubusercontent.com/49101492/76299755-a003f900-62e1-11ea-9beb-01f3b42e8fae.png)

![image](https://user-images.githubusercontent.com/49101492/76299798-b1e59c00-62e1-11ea-845e-fe9255af74c1.png)

**Comment by Shivansh2407** [comment]
The Footer is not at Bottom in Many Pages : Profile, Notifications, My Circuits, My Groups, My Favourites in IPad Pro while inspecting the element. If no one is working on this , I would like to give this a try 👍 @aayush-05 .

**Comment by yash15601** [comment]
@Shivansh2407  wait @Nitish145  will fix this in this pr for the page dont make new issue

**Comment by Shivansh2407** [comment]
Ok cool @yash15601 👍

**Comment by Nitish145** [comment]
@yash15601 Sure, will make the page responsive for all screen sizes (reimplement the whole page maybe)

**Comment by Nitish145** [comment]
Hey @yash15601 @Shivansh2407 i am not able to reproduce the footer error on any device or aspect ratio. How do i reproduce the error ?

**Comment by Shivansh2407** [comment]
> Hey @yash15601 @Shivansh2407 i am not able to reproduce the footer error on any device or aspect ratio. How do i reproduce the error ?

Go on https://beta.circuitverse.org
Then Go to any link mentioned : Profile, Notifications, My Circuits, My Groups, My Favourites . Click on inspect element and Change the device to IPad Pro. 
See error.

**Comment by yash15601** [comment]
@Nitish145  as @Shivansh2407  said
