### ISSUE TITLE
CircuitVerse page not responsive

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerse#1110]
**Describe the bug**
The designs on the beta testing site of Circuit Verse are not responsive to screensize at the current moment. The lines clatter on changing the scrren size (Using mobile, etc).

**To Reproduce**
1. Go to 'beta.circuitverse.org'
2. Resize the page.
3. See error

**Expected behaviour**
The page renders elements responsive to device display width and height.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] : Ubuntu 18.04
 - Browser [e.g. chrome, safari] Chrome

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by nitin10s** [comment]
Already working on the responsiveness in sections. Let us know if some section still needs work in particular.
