### ISSUE TITLE
Popups in Simulator not working properly

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1117]
**Describe the bug**
Whenever we click on `Insert Subcircuit` , `Open Offline`, `Combinational Analysis`, `Render Image` in simulator then a Popup Opens . The Popup is both resizable and draggable. Now when the user try to resize the Popup, it resizes weirdly. (See in the GIF Below)

**To Reproduce**
1. Go to 'New UI on Gitpod or beta.circuitverse.org or circuitverse.org'
2. Click on 'Simulator'
3. Open any of the above mentioned links

**Expected behavior**
The Popups must not be resizable though they can be draggable .

**Screenshots**
![issue9](https://user-images.githubusercontent.com/42182955/76326915-53cfad80-630f-11ea-95bd-83d7de85c1c3.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shivansh2407** [comment]
@satu0king , @tachyons , @nitin10s I would like to hear your views on this 👍

**Comment by abstrekt** [comment]
can be closed, @nitin10s

**Comment by abstrekt** [comment]
will be fixed in new UI
