### ISSUE TITLE
Alingment of Feature Section on Homepage

### ISSUE THREAD

**Issue by harshgujrati** [CircuitVerse/CircuitVerse#1118]
**Describe the bug**
Use sub circuits and multi bit buses and components are not alinged on the homepage.

**To Reproduce**
Go to homepage scroll to Features Section

**Expected behavior**

**Screenshots**

![Screenshot (156)](https://user-images.githubusercontent.com/51922630/76328305-284dc280-6311-11ea-8594-97063aa3e4ea.png)
![Screenshot (157)](https://user-images.githubusercontent.com/51922630/76328312-2ab01c80-6311-11ea-999b-a4c8513668a6.png)
![Screenshot (158)](https://user-images.githubusercontent.com/51922630/76328316-2be14980-6311-11ea-931c-d815e6039c35.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome

**Are you working on this issue? (Yes/No)**
Yes

**Comment by mahmodHammad** [comment]
@harshgujrati  What is the updates ? 
are you still working on it or need some help ?

**Comment by harshgujrati** [comment]
@mahmodHammad i will make a pr for it today
