### ISSUE TITLE
Alingment of learn logic design button on homepage

### ISSUE THREAD

**Issue by harshgujrati** [CircuitVerse/CircuitVerse#1120]
**Describe the bug**
Learn Logic Design button should be on next row in all mobile device

**Screenshots**

![Screenshot (161)](https://user-images.githubusercontent.com/51922630/76329592-c8f0b200-6312-11ea-8944-de2383f5f20d.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aayush-05** [comment]
@harshgujrati please fix this asap.

**Comment by harshgujrati** [comment]
#1156
