### ISSUE TITLE
 Pages are not aligned properly  for ipad /ipad pro / iphone 5/SE

### ISSUE THREAD

**Issue by yash15601** [CircuitVerse/CircuitVerse#1137]
**Describe the bug**
Most of the pages are not aligned for ipad pro and other devices as shown below 

**To Reproduce**
1. Go to 'circuitverse.org'
2. See error

**Screenshots**
ipad pro:
![image](https://user-images.githubusercontent.com/49101492/76430582-7b3d7d80-63d6-11ea-9c21-f11bb2939bd9.png)

Iphone 5/SE:
![image](https://user-images.githubusercontent.com/49101492/76430711-a2944a80-63d6-11ea-8e7e-10e71e73ab7e.png)

Teachers page:
ipad pro: footer also have extra space on right hand side
![image](https://user-images.githubusercontent.com/49101492/76431005-01f25a80-63d7-11ea-9f23-95448f41acd4.png)

My circuit page :
ipad pro:  extra space on  right hand side
![image](https://user-images.githubusercontent.com/49101492/76431516-ab395080-63d7-11ea-85b1-e89b81e94916.png)

Favourite page:
ipad: footer not at bottom
![image](https://user-images.githubusercontent.com/49101492/76431714-ff443500-63d7-11ea-8a81-f5eb6fb38882.png)

ipad pro: Extra white space ,footer not at bottom
![image](https://user-images.githubusercontent.com/49101492/76431780-14b95f00-63d8-11ea-85db-67178d192153.png)

Notification Page:
ipad pro: Extra space on right hand side
![image](https://user-images.githubusercontent.com/49101492/76432136-8db8b680-63d8-11ea-8b4f-8742462af89b.png)

Profile page : 
ipad pro : Extra white space
![image](https://user-images.githubusercontent.com/49101492/76432309-ce183480-63d8-11ea-8b85-7d294eacbaee.png)

Edit profile page : 
ipad pro : Extra white space
![image](https://user-images.githubusercontent.com/49101492/76432481-0cadef00-63d9-11ea-8712-7593a02a779f.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by aayush-05** [comment]
Most of the pages work fine on Ipad/Ipad pro. I guess the problem is that you used a really long username, so the website is trying to show it completely and leaves extra space up on the right. What we can do is use "..." for really long names or maybe set a limit to it.
![image](https://user-images.githubusercontent.com/47032027/76435513-16395600-63dd-11ea-9afc-0bf52d02b9e2.png)

**Comment by yash15601** [comment]
ohh i see , except extra space the footer is not at bootom at some pages

**Comment by aayush-05** [comment]
The footer is in works I guess. Can we close this issue and someone make a new one for the name thing.

**Comment by yash15601** [comment]
will close this and making new for name thing @aayush-05
