### ISSUE TITLE
If Username is to long extra White space is produce in ipad pro view 

### ISSUE THREAD

**Issue by ryuk156** [CircuitVerse/CircuitVerse#1138]
**Describe the bug**
If username is to long the white space is produced in ipad pro view

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'login in'
3. See error

**Screenshots**
long username :
![image](https://user-images.githubusercontent.com/49101492/76437982-636af700-63e0-11ea-8b27-4a5f9a3c1d1b.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by GarrySan** [comment]
Hi @yash15601, are you still working on this?

**Comment by yash15601** [comment]
@GarrySan yes I'm still  working

**Comment by aayush-05** [comment]
@nitin10s can be closed, fixed in #1411
