### ISSUE TITLE
Write instructions on groups page

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#114]
- [ ] Users are not clear about the difference between groups and collaborations
- [ ] Students are not understanding that they need to start their assignment on the group page. 
- [ ] Students are not clear about how their assignment will be submitted. 

Some information can be found here https://docs.circuitverse.org/#/groups

**Comment by maykillmore** [comment]
I'd like to take this up . how do i proceed??

**Comment by satu0king** [comment]
Study how groups, assignments, and collaborations work, just try it out. Then document the same both on docs.circuitverse.org and also as a Note somewhere on the groups page. 

**Places to add documentation**
* User Group's page: https://circuitverse.org/users/3/groups - What groups are, what teachers can use the group for
* Specific Group's page: https://circuitverse.org/groups/88 - How teachers can add students to the group, post assignments, instructions for students on how to submit the same. 
* Documentation: Both the above things on https://docs.circuitverse.org/#/

**Comment by maykillmore** [comment]
Sure I'll get right on it.

**Comment by agarwalrounak** [comment]
@maykillmore Are you still on it, cause I would like to work on it.

**Comment by armudgal** [comment]
@agarwalrounak I would wait for @maykillmore to respond. If there is no response within a day, you can take this up :)

**Comment by An0u** [comment]
@maykillmore @agarwalrounak This is something I'd like to work on if it becomes available.

**Comment by agarwalrounak** [comment]
@An0u Since @maykillmore isn't responding, I will take it up.

**Comment by armudgal** [comment]
@agarwalrounak Please take it up.

**Comment by prajapatgautam1999** [comment]
@satu0king Do anyone working on this issue or I can proceed resolving this one.

**Comment by ankitkataria** [comment]
@prajapatgautam1999 @agarwalrounak seems to be on this issue. 
Also, all the issues that labelled `taken` have already been claimed. Try looking for ones that haven't been labelled so. :wink:

**Comment by satu0king** [comment]
This is an easy issue and should be resolved within an hour. Since people have been taking it and not completing it, We will merge the first PR.

**Comment by armudgal** [comment]
As @satu0king mentioned, this issue is now open and we will be merging the first PR that comes and is satisfactory.

**Comment by nrs1729** [comment]
Hi! Just to say I claimed the task on GCI and am working on it :)
