### ISSUE TITLE
Fix alignment of buttons on Homepage

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1140]
**Describe the bug**
Move the second link to bottom for small displays

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/76496565-58a37700-645f-11ea-83c6-4a029e8362f7.png)

**Comment by mahmodHammad** [comment]
@aayush-05  
i can do it now  if you are not working on it

**Comment by mahmodHammad** [comment]
also i would like to indent these button to the left to be aligned with the text above it

**Comment by mahmodHammad** [comment]
#1120 
@aayush-05 
it's duplicated
