### ISSUE TITLE
Fix login/SignUp/Forgot password pages

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1141]
**Describe the bug**
Improve alignment of buttons, text and social media handles for smaller displays. Remove the sketch on forgot password page for smaller displays.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/76496693-92747d80-645f-11ea-8cb4-a2a3990da470.png)
![image](https://user-images.githubusercontent.com/47032027/76496698-96080480-645f-11ea-831b-1053be4caab3.png)
![image](https://user-images.githubusercontent.com/47032027/76496705-986a5e80-645f-11ea-9c76-ce96d9c6adf5.png)

**Comment by rishipurwar1** [comment]
I am working on it

**Comment by Nitish145** [comment]
Hey @rishipurwar1 would you mind if i take up this issue?

**Comment by rishipurwar1** [comment]
I am already start working on it

**Comment by Nitish145** [comment]
Oh cool 🤞

**Comment by rishipurwar1** [comment]
![127 0 0 1_8080_users_sign_in(Galaxy S5) (1)](https://user-images.githubusercontent.com/57035408/76514878-982d8b80-647e-11ea-9a63-ab3002e7eaff.png)

Please check the changes is it OK or not @aayush-05 
I want to know if we change forgot password into link and remove reset your password.
What's your thought?

**Comment by aayush-05** [comment]
@rishipurwar1 please refer to the prototype for now. Further enhancements to be done after the release.
