### ISSUE TITLE
Fix footer alignment

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1142]
**Describe the bug**
Fix footer elements alignment for smaller displays. Make sure it doesn't create any horizontal scroll on the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/76496840-debfbd80-645f-11ea-84a1-0703dfb3e8c3.png)

**Comment by rishipurwar1** [comment]
I am working on it
