### ISSUE TITLE
Fix Edit Profile page

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1143]
**Describe the bug**
Fix the complete alignment for Edit profile page. Also check for the font size (it appears big on smaller displays)

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/76497004-32320b80-6460-11ea-83e6-2d375c255967.png)
![image](https://user-images.githubusercontent.com/47032027/76497011-33fbcf00-6460-11ea-9339-a0c77970c3ff.png)

**Comment by yash15601** [comment]
@aayush-05  i am working on this

**Comment by yash15601** [comment]
![image](https://user-images.githubusercontent.com/49101492/76502010-48909500-6469-11ea-9e69-cb8b62fcc723.png)
@aayush-05  does it look good now

**Comment by ryuk156** [comment]
@satu0king @tachyons  can you reopen this  pr it can be merged
