### ISSUE TITLE
extra white space at top of homePage

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1146]
**Describe the bug**
extra white space existed at phone screens 

**Screenshots**
![home b](https://user-images.githubusercontent.com/41790090/76502780-5a643f00-644d-11ea-80a4-bdb764af2abf.PNG)

**Expected behavior**
It would be better if we reduced that margin top to be like this : 
![home](https://user-images.githubusercontent.com/41790090/76502679-27ba4680-644d-11ea-95d7-b9372b3c8b28.PNG)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Vishruth-S** [comment]
Can I work on this?
