### ISSUE TITLE
Fixing the active navbar item

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1149]
**Describe the bug**
The active navbar-item state looked like a section break in mobile devices

**To Reproduce**
Steps to reproduce the behaviour:
1. Open Navbar Menu in Mobile Devices

**Solution**
Rather than making the active state underlined, we can make the text green without any underline.

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
Would like to take up this issue 🙂

**Comment by arpita-in** [comment]
I would like to work on this issue

**Comment by Nitish145** [comment]
> I would like to work on this issue

already started @arpita-in :slightly_smiling_face:
