### ISSUE TITLE
Subcircuit Layout height automatically increasing by 1 unit. 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#115]
Eventhough, in the edit mode, it has been configured to have this height, The height increases by one unit. 

Configured Height
![image](https://user-images.githubusercontent.com/2092958/53066168-a1a32900-34f4-11e9-81a9-e773e835ad0e.png)

Resultant Height.
![image](https://user-images.githubusercontent.com/2092958/53066146-8c2dff00-34f4-11e9-82a0-ba263b4858e2.png)

**Comment by blane1257** [comment]
Yes, this happens all the time, and is really annoying!

**Comment by satu0king** [comment]
> Yes, this happens all the time, and is really annoying!

Please report such things, even if it is small! I didn't know it till today when I was trying to use the SquareLED

**Comment by SubhajitCode** [comment]
Hi I created a pull req to fix this bug kindly review it and let me know 
https://github.com/CircuitVerse/CircuitVerse/pull/220
