### ISSUE TITLE
Footer not centre aligned

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1157]
**Describe the bug**
Footer content is not centre aligned

**Screenshots**
![FireShot Capture 183 - CircuitVerse - Support the platform - beta circuitverse org](https://user-images.githubusercontent.com/16988558/76547708-a5b13880-64b3-11ea-8ef0-2be98f0f1153.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by kulkarniatharv** [comment]
Can I work on this?

**Comment by kulkarniatharv** [comment]
Footer can be remade by using CSS Grids rather than HTML tables and it fixes the alignment.

**Comment by rishipurwar1** [comment]
I am working on it

**Comment by kulkarniatharv** [comment]
Already started @rishipurwar1 :)

**Comment by kulkarniatharv** [comment]
I already resolved the issue.

**Comment by rishipurwar1** [comment]
Oh, great...
Keep contributing...

**Comment by kulkarniatharv** [comment]
Thanks!
I've made changes using Gitpod.
![resolved](https://user-images.githubusercontent.com/15829308/76599861-d339c880-652b-11ea-9273-caa57d31e47b.jpg)

Can you tell me how to create a Pull request? 
I followed this article: [Pull Request using Gitpod]((https://github.com/CircuitVerse/CircuitVerse/wiki/Pull-Requests-using-Gitpod) but it is giving the following permission error after I execute step 7:
![auth_error](https://user-images.githubusercontent.com/15829308/76599938-ff554980-652b-11ea-95d3-9d6afca01b87.jpg)

**Comment by aayush-05** [comment]
@kulkarniatharv can you fix the footer before we push the new UI to production, it is breaking responsive of pages.

**Comment by kulkarniatharv** [comment]
> @kulkarniatharv can you fix the footer before we push the new UI to production, it is breaking responsive of pages.

What part is not responsive in the footer? The changes I made or some other part? Because they seem to reposition and resize according to change in display size. 
The change I made includes only the logos section. I didn't edit code which was handling other stuff.

**Comment by aayush-05** [comment]
I can't see your pull request. Can you link it here ?

**Comment by kulkarniatharv** [comment]
I can't link the pull request to the issue. I guess I don't have the authorisation. 
But you can check the PR [here:](https://github.com/CircuitVerse/CircuitVerse/pull/1160)

**Comment by kulkarniatharv** [comment]
Link to the PR is [here](https://github.com/CircuitVerse/CircuitVerse/pull/1160)
Idk how is it not linked to this issue even when I followed [this](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)
