### ISSUE TITLE
Reporting Issues related to Simulator in an easy way

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1158]
**Is your feature request related to a problem? Please describe.**
Currently, there isn't any efficient issue reporting system when a normal user encounters any problem/difficulty in using the simulator. Currently, a user, if he/she wants to report an issue would have to email CV or log in to GitHub and open an issue, etc which are time-consuming.

**Describe the solution you'd like**
A favourable solution is a side popup that lets users instantly report any issue whilst using simulator there and then. Just like this: 
![FireShot Capture 181 - Lesson 8 1 - Human-Computer Interaction - HCI - Interaction Design Fo_ - www interaction-design org](https://user-images.githubusercontent.com/16988558/76558161-cc2aa000-64c2-11ea-9400-e06fde1a92dd.png)
![FireShot Capture 179 - Lesson 8 1 - Human-Computer Interaction - HCI - Interaction Design Fo_ - www interaction-design org](https://user-images.githubusercontent.com/16988558/76558165-ce8cfa00-64c2-11ea-87bd-8396cd40979e.png)
![FireShot Capture 180 - Lesson 8 1 - Human-Computer Interaction - HCI - Interaction Design Fo_ - www interaction-design org](https://user-images.githubusercontent.com/16988558/76558164-cdf46380-64c2-11ea-8952-a6cbbce7c941.png)

Instead of FAQs, we can have Documentation, which redirects to the Documentations Page

**Are you working on this? (Yes/No)**
No

**Comment by sal2701** [comment]
Is anyone working on this? I'd like to take this up

**Comment by nitin10s** [comment]
No one is, pls do @sal2701

**Comment by darkshredder** [comment]
@sal2701 are you still working on it. Or can I work on it. Please confirm

**Comment by sal2701** [comment]
Yup. Will surely let you know if I am not @darkshredder

**Comment by nitin10s** [comment]
Yes, it's best to implement this as soon as possible.

**Comment by nitin10s** [comment]
@sal2701 ?

**Comment by sal2701** [comment]
@darkshredder Please proceed, I am working on another issue which is taking more time than expected. Sorry for the delay @nitin10s

**Comment by darkshredder** [comment]
Sure will start from today, will open PR soon

**Comment by darkshredder** [comment]
@tachyons @satu0king @nitin10s Can you tell me how to send mail to CV like I send mails using mailto: but that wont look good i guess... any alternative?

**Comment by satu0king** [comment]
No, we wouldn't want this to be a mail because a mail at least directly as a mail would require authentication. 

For a basic design, a mechanism to submit the feedback is to embed a google form or similar form. This is very ideal as it is super easy to manage, update etc. See https://optinmonster.com/best-ways-to-collect-customer-feedback/ and similar articles for ideas. 

@nitin10s is suggesting that we automatically capture screenshot, the current URL as well for feedback so that we can better process the feedback. I love this. However, This increases the complexity of the task. 

For this as well, a quick search resulted in this service https://www.userback.io/, it is paid but the free plan might work for us. It has all the required features, do check it! 

Do research other alternatives as well and get back. Implementing this from scratch and storing in the backend is the last option as it is actually complicated to develop and maintain 😄.

**Comment by satu0king** [comment]
https://mopinion.com/34-online-feedback-tools-an-overview/

Another very useful article

**Comment by darkshredder** [comment]
@satu0king for now i can redirect it google form, during gsoc period we can make it better that would be best.... so i would like you to create google form and i will open up the PR

**Comment by nitin10s** [comment]
I don't know if I am making sense, I thought of user-submitted issues getting posted in Slack directly, by making use of Incoming Webhooks of Slack Customized App, if anyone will be willing to try this can tell. @satu0king whatsay?

![FireShot Capture 200 - Slack API_ Applications - CircuitVerse Slack - api slack com](https://user-images.githubusercontent.com/16988558/77234433-68942700-6bd4-11ea-97e2-325f4ac26fd1.png)

**Comment by yash15601** [comment]
good idea , we can make channel for #issues and if user post any issues will be send to those issues channel Can i try this @nitin10s  if @satu0king  agree

**Comment by nitin10s** [comment]
Exactly @yash15601, if @darkshredder doesn't mind, you may work on it. Just please try to build this as fast as possible. or maybe you two could coordinate and make it together, @darkshredder could make the frontend part and you could connect it with slack.

**Comment by yash15601** [comment]
@nitin10s will try to finish  asap

**Comment by yash15601** [comment]
@nitin10s this feature should be in home page or in simulator page

**Comment by nitin10s** [comment]
Just in simulator page for now.

**Comment by satu0king** [comment]
Have added basic feedback support. Need to add screenshot capability.

**Comment by Shivansh2407** [comment]
Screenshot capability can be added similar to that present in the simulator currently. We just need to remove various features from it and add a simple screenshot button. Right @satu0king ?

**Comment by yash15601** [comment]
we can have file upload button in that
