### ISSUE TITLE
Show subcircuit type on previewMode 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#116]
When the users clicks/hovers on a subcircuit in preview mode, the subcircuit type should be displayed.

**Comment by jbox144** [comment]
I recently got Visual Studio, I'll try this.

**Comment by ankitkataria** [comment]
@jbox144 Are you still working on this? I wish to work on it.

**Comment by jbox144** [comment]
> @jbox144 Are you still working on this? I wish to work on it.

Unfortunately, I failed to set up the project, go ahead and do this

**Comment by ankitkataria** [comment]
@satu0king Could I get a little more information on the issue? I found out the preview mode. What is meant by the `type` of a subcircuit?

**Comment by akoopraba4** [comment]
Can I work on this issue?

**Comment by ankitkataria** [comment]
Hey @satu0king! I'm already working on it. :smile:

**Comment by satu0king** [comment]
In some circuits, users disable title for SubCircuits. For example: https://circuitverse.org/users/3/projects/8618

Several subcircuits are used but for aesthetic reasons, all titles are disabled. However we need a way to know which subcircuit it is by hovering on them without clicking (Clicking will goto that circuit). 

Maybe a tooltip or a message in a fixed location will work, try out which looks better.
