### ISSUE TITLE
Issues with Group Details Page

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1166]
1. The font of Edit Name is inconsistent.
2. The Back button should be styled like it is everywhere [No bg, green color, underlined]

![FireShot Capture 193 - CircuitVerse - Digital Circuit Simulator_ - 3000-e058e8fd-8e70-42ad-8b01-108ce4f7c3b2 ws-ap01 gitpod io](https://user-images.githubusercontent.com/16988558/76642922-1a4eaa80-657a-11ea-852e-c4637cfe49ee.png)

**Comment by Ananthavijay** [comment]
I am working on this
