### ISSUE TITLE
Checkboxes Not Styled

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1167]
**Problem**
The checkboxes in new UI don't have any styling. Needs to be done at all pages. 

**Are your working on the issue**
No

**Comment by akansha-singh** [comment]
I want to work in this

**Comment by nitin10s** [comment]
Ok.

**Comment by rishipurwar1** [comment]
Can I work on this issue ? @akansha-singh

**Comment by akansha-singh** [comment]
@rishipurwar1 I already started working on this issue ..

**Comment by abstrekt** [comment]
ok I'm working on it, @akansha-singh  left, is it okay @rishipurwar1 ?

**Comment by 1997SHUBHAM** [comment]
I worked on it and solved the check box style problem
