### ISSUE TITLE
User Not Underlined when clicked on Navbar

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1169]
**Problem**
The User is not underlined whenever any link in the User dropdown is clicked .

**Solution**
UserName Must Be Underlined

**Are You Working on this Issue**
Yes. I will be Uploading the Screenshots Soon.

**Comment by nitin10s** [comment]
Didn't Understand the problem, can you please upload the screenshot of the problem

**Comment by Shivansh2407** [comment]
![Issue11](https://user-images.githubusercontent.com/42182955/76647760-6a7e3a80-6583-11ea-959b-e626776704ef.gif)
@nitin10s here Admin is not Underlined when I click on any link present in the drop down.

**Comment by Shivansh2407** [comment]
@nitin10s and @tachyons I would like to hear your views on this :+1:

**Comment by aayush-05** [comment]
I think we will be changing the response for active state to be change in text colour. Further I don't know how valid it is because the last option is a dropdown while the other are direct links.

**Comment by aayush-05** [comment]
We would be changing the underline style to something different on active state, you can close this @Shivansh2407
