### ISSUE TITLE
ROM update

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#117]
My idea is to make the ROM writable. Not necessarily persistent between saves, I mean like have an origin state, but instead of being locked in that state throughout the simulation, add the ability to write new values, and whenever the simulation is saved, the current state of the ROM component becomes the origin. This would make it so computers can much more easily build and run programs, instead of using RAM and potentially a slow program to run RAM programs.

Another feature I would love to see is customizable address bitwidth for the ROM components, but I understand this can cause some issues with the displaying of values on the surface of the ROM, but this could possibly be overcome by a DMA pin much like is described in #113

**Comment by fpintos** [comment]
Sounds like you want an [EPROM](https://en.wikipedia.org/wiki/Eprom).

We can derive from the RAM and just include the memory array in the serializer.

The only issue I can think is that a large array will generate a large JSON; even the memory addresses that were not populated (and thus make the array sparse) will get converted to 'null' in the generated JSON, so maybe EPROMs should be limited in size.

**Comment by blane1257** [comment]
Well, kind of more similar to an EEPROM, but yes. I basically want it to behave lile the RAM, but with an origin state, which can be updated to the current  by saving the simulation

**Comment by blane1257** [comment]
If there's a "reset" pin, should this clear the entire ROM, or revert it to it's origin state?

Or maybe two reset pins, a "full reset" or maybe "format" which clears everything, and a "factory reset" which reverts to the origin state.

**Comment by satu0king** [comment]
> Well, kind of more similar to an EEPROM, but yes. I basically want it to behave lile the RAM, but with an origin state, which can be updated to the current state by saving the simulation

Yes, what you need is a RAM which starts which an origin state which we can do by using a DMA module which can put data into the RAM.

**Comment by blane1257** [comment]
well, i would also like the ability to update the origin state when the simulation is saved

**Comment by blane1257** [comment]
really, the reason is, programming a 65KB ROM by hand sounds absolutely horrible to me. what i'd love to be able to do is build small programs to help me program the computer faster (like IDE's, interpreters, and other programs) so I can much more quickly fill the ROM with programs and files, then just save the end product and be done.

**Comment by fpintos** [comment]
I'll write the EPROM this weekend.

**Comment by blane1257** [comment]
Awesome!
