### ISSUE TITLE
Cards broken in Contribute page

### ISSUE THREAD

**Issue by Nitish145** [CircuitVerse/CircuitVerse#1172]
**Describe the bug**
The email, slack, and github cards background overlap with content.

**To Reproduce**
1. Go to https://beta.circuitverse.org/contribute
2. See error

**Expected behavior**
The card's background should not overlap and all the cards must be consistent in terms of layout.

**Screenshots**
![Screenshot from 2020-03-13 21-35-07](https://user-images.githubusercontent.com/45434030/76673145-72ac9900-65c8-11ea-8255-2c94959351c1.png)
![Screenshot from 2020-03-13 21-34-43](https://user-images.githubusercontent.com/45434030/76673148-76d8b680-65c8-11ea-8b9a-6aa263c8bfc3.png)
![Screenshot from 2020-03-13 21-34-23](https://user-images.githubusercontent.com/45434030/76673149-7809e380-65c8-11ea-91de-f876880a9209.png)
![Screenshot from 2020-03-13 21-34-04](https://user-images.githubusercontent.com/45434030/76673151-793b1080-65c8-11ea-803d-c6f9aec685fc.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aayush-05** [comment]
Can you check once again, it seems to work fine for me.
![image](https://user-images.githubusercontent.com/47032027/76674293-b658d000-65d3-11ea-81ce-88ee928b4adf.png)
![image](https://user-images.githubusercontent.com/47032027/76674298-cc669080-65d3-11ea-893d-cc6f7a467d4b.png)

**Comment by Shivansh2407** [comment]
Same @aayush-05 . It works for me as well .

**Comment by Nitish145** [comment]
![Screenshot from 2020-03-14 09-14-21](https://user-images.githubusercontent.com/45434030/76674325-3d0dad00-65d4-11ea-8ad1-4774e313c28a.png)

**Comment by Nitish145** [comment]
@nitin10s Please check.. Should i proceed with this issue ??

**Comment by aayush-05** [comment]
Let us wait for now and see how it goes on production.

**Comment by aayush-05** [comment]
Works fine for me, @tachyons @nitin10s can you confirm and close this ?

**Comment by Nitish145** [comment]
Works fine for me too.. the issue aroused when i changed the default browser font size @aayush-05
