### ISSUE TITLE
home page contents not aligned properly

### ISSUE THREAD

**Issue by Nitish145** [CircuitVerse/CircuitVerse#1173]
**Describe the bug**
- *Launch Simulator* and *For Teachers* buttons not aligned properly
- The *new_homepage_sketch* image is not aligned with corresponding content.

**To Reproduce**
1. Go to beta.circuitverse.org
2. See error

**Expected behavior**
The forementioned buttons must be aligned properly and the image must be aligned with it's contents.

**Screenshots**
![Screenshot from 2020-03-14 10-26-51](https://user-images.githubusercontent.com/45434030/76675388-cf1ab300-65de-11ea-8878-f558a8f9d118.png)

![Screenshot from 2020-03-14 11-17-42](https://user-images.githubusercontent.com/45434030/76676105-207a7080-65e6-11ea-8a5b-f07968b43e99.png)

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Vishruth-S** [comment]
Can I work on this?

**Comment by Nitish145** [comment]
@Vishruth-S PR already linked
