### ISSUE TITLE
Group page not aligned properly

### ISSUE THREAD

**Issue by rishipurwar1** [CircuitVerse/CircuitVerse#1174]
**Describe the bug**
After creating a group, when you visit a newly created group page. Button and text are not properly aligned

**To Reproduce**
1. Create a group
2. Click on view in mobile view
3. See error

**Expected behavior**
Buttons and  text should be aligned properly

**Screenshots**
![beta circuitverse org_groups_14](https://user-images.githubusercontent.com/57035408/76675647-7d275c80-65e1-11ea-90d7-9e11ce3b7b5e.png)

**Are you working on this issue? **
Yes

**Comment by rishipurwar1** [comment]
Can I start working on it? @nitin10s

**Comment by Nitish145** [comment]
@rishipurwar1 this page has been completely redone. You can check here #1062

**Comment by rishipurwar1** [comment]
Ok @Nitish145
