### ISSUE TITLE
Outline not working properly in favorites page

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#1178]
**Describe the bug**
Outline on the favorites page is not rounded (but it should) and have wired white strip

**Screenshots**
![Screenshot (50)](https://user-images.githubusercontent.com/35162705/76681334-f346b600-6617-11ea-9d32-0c7e804d1432.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
@Ananthavijay i think there was a pr related to that #1066 ..

**Comment by Ananthavijay** [comment]
Yep, but this issue is on favorites page

**Comment by Nitish145** [comment]
Working on it :)

**Comment by Nitish145** [comment]
@Ananthavijay i think the borders shouldn't be rounded as reflected in the discussions of #1066 .
Please update the issue..

**Comment by Shivansh2407** [comment]
Yes the Borders Must be straight instead of rounded as in #1066
