### ISSUE TITLE
Remove button on teacher's page for Members isn't completely visible.

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerse#1185]
**Describe the bug**
Remove button on teacher's page for Members isn't completely visible.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'Teachers', then click to view your Groups.
3. See error

**Expected behavior**
Button completely visible as in other window sizes.

**Screenshots**
![Screenshot from 2020-03-15 08-57-48](https://user-images.githubusercontent.com/50791000/76694621-1bc3c400-669b-11ea-8680-a87fc27a69cc.png)
![Screenshot from 2020-03-15 08-57-11](https://user-images.githubusercontent.com/50791000/76694622-1e261e00-669b-11ea-83b3-cd4a2efa77a8.png)
![Screenshot from 2020-03-15 08-58-42](https://user-images.githubusercontent.com/50791000/76694630-31d18480-669b-11ea-85b0-6ec26ad47863.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : Chrome

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Nitish145** [comment]
@ShubhankarKG i think @darkshredder is working on this very issue.. 
@darkshredder please confirm..

**Comment by darkshredder** [comment]
@ShubhankarKG @Nitish145 I m working on this
