### ISSUE TITLE
A little extra whitespace

### ISSUE THREAD

**Issue by Vishruth-S** [CircuitVerse/CircuitVerse#1187]
**Describe the bug**
I feel that this whitespace in the homepage is a bit extra

**To Reproduce**
Check the Homepage bottom

**Expected behavior**
Decrease whitespace

**Screenshots**
![circuit](https://user-images.githubusercontent.com/55310756/76700294-1175ea00-66dc-11ea-9882-2ecac05d05d7.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
Yes, I am self-assigning this issue

**Comment by Nitish145** [comment]
@Vishruth-S this is intentional i guess @Ananthavijay please confirm..

**Comment by Vishruth-S** [comment]
Ohh okay...Thanks
Is there any other issue which I can work on?

**Comment by Ananthavijay** [comment]
Yes I think this is intentional, this issue can be closed
