### ISSUE TITLE
Invert colors

### ISSUE THREAD

**Issue by akshathkaushal** [CircuitVerse/CircuitVerse#1188]
**Is your feature request related to a problem? Please describe.**
It is not related to any problem. But I have seen many such projects have an option of inverting colors.
So it would be nice if such a feature is integrated in the simulator.

**Describe the solution you'd like**
I am thinking of adding a button that inverts all the colors in the simulator. 

**Are you working on this? (Yes/No)**
Yes, I am working on this.

**Comment by abstrekt** [comment]
can be closed, themer under process.
@nitin10s
