### ISSUE TITLE
Navbar bug

### ISSUE THREAD

**Issue by Vishruth-S** [CircuitVerse/CircuitVerse#1190]
**Describe the bug**
The "untitled" is out of place in tablet & mobile screen size

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Reduce screen width so that navbar collapses
3. Open the navbar

**Expected behavior**
The "Untitled" should be centered

**Screenshots**
![circuit6](https://user-images.githubusercontent.com/55310756/76704720-f7023780-6700-11ea-8675-d3dd8f32c647.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shivansh2407** [comment]
Similar to #1028 . #1035 Fixes this Issue .

**Comment by nitin10s** [comment]
Duplicate
