### ISSUE TITLE
Mentor should not be able to add himself as a member of the same group

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#1191]
**Describe the bug**
The mentor should not be able to add himself as a student of the same group

**To Reproduce**
1. Go to circuitverse.org
2. Create a Group
3. Click Add members
4. Add the email with which you have created the group

**Screenshots**
![Screenshot (54)_LI](https://user-images.githubusercontent.com/35162705/76705216-5f064d00-6704-11ea-8ce9-d01eec9e9aa0.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
Would like to take up this issue :)
