### ISSUE TITLE
Test button in Notifications page is not working

### ISSUE THREAD

**Issue by pranavmodx** [CircuitVerse/CircuitVerse#1193]
**Describe the bug**
The Test button in Notifications page is not working. 

**To Reproduce**
1. Go to Notifications page
2. Enable browser notifications if not already enabled.
3. Click Test button

**Expected behavior**
Not sure what the test button is actually there for.

**Screenshots**
![Screenshot 2020-03-15 at 9 39 27 PM](https://user-images.githubusercontent.com/42793024/76705352-7d207d00-6705-11ea-872c-5ef403d6c775.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] - Mac OSX Mojave
 - Browser [e.g. chrome, safari] - Firefox
 - Version [e.g. 22] - 74.0 (64-bit)

**Additional context**

**Are you working on this issue? (Yes/No)**
Maybe. Depending upon validity of issue

**Comment by Nitish145** [comment]
@pranavmodx I think Notifications page was discussed to be disabled @satu0king Please confirm.

**Comment by ALWISH007** [comment]
@pranavmodx  did you find any solution for this.

**Comment by pranavmodx** [comment]
No, I didn't work on it since there was no follow up.
