### ISSUE TITLE
Fix missing icons in simulator

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#12]
Add images with type svg in the images folder. 
Missing images. You can send the icons in separate PRs 

- [x] Tunnel
- [ ] TestBench Input
- [ ] TestBench Output
- [x] ForceGate

**Comment by johneckert** [comment]
added Tunnel.svg and ForceGate.svg in the above pull request

**Comment by Amansingla97** [comment]
<img width="242" alt="screenshot 2019-03-03 at 6 38 57 pm" src="https://user-images.githubusercontent.com/20012612/53695606-a795e580-3de3-11e9-82fc-926f10ea354d.png">

It appears that icons for TB input and output are still missing.Can you suggest how can I find the relevant svg's?

**Comment by armudgal** [comment]
Hi @Amansingla97, there aren't any pre-existing SVG's for the same and you need to design them.

**Comment by satu0king** [comment]
Generally, generateSvg() in data.js is used to generate the SVG but this may not work with this element.
