### ISSUE TITLE
Same content for developer and student in contribute page

### ISSUE THREAD

**Issue by Vishruth-S** [CircuitVerse/CircuitVerse#1216]
**Describe the bug**
The content for "developer" and "student" is the same in contribute page. I think this can be improved by modifying it as shown in the images below

**To Reproduce**
1. Go to https://circuitverse.org/contribute

**Expected behavior**
I Think it would be better to improve the developer's content as shown below,,,just an opinion

**Screenshots**
Before
![circuit11](https://user-images.githubusercontent.com/55310756/76862343-fba32900-6883-11ea-98d8-8127ec0726c9.png)
After
![circuit12](https://user-images.githubusercontent.com/55310756/76862368-0493fa80-6884-11ea-8f6c-967ea2eef1c5.png)

**Are you working on this issue? (Yes/No)**
I would like to,..if the same is relevant

**Comment by nileshdas** [comment]
Can I work on this?

**Comment by Vishruth-S** [comment]
@nileshdas ...I already took up this issue and submitted a PR.

**Comment by aayush-05** [comment]
@tachyons @nitin10s issue can be closed, related PR had been merged
