### ISSUE TITLE
Function of toggle button not obvious

### ISSUE THREAD

**Issue by Vishruth-S** [CircuitVerse/CircuitVerse#1217]
**Describe the bug**
The toggle button in "Documentation" page has no description of what it does unless clicked. At first sight, looks as if it allows "Edit on Github" since it's next to it

**To Reproduce**

1. Go to https://docs.circuitverse.org/#/
2. See error

**Expected behavior**
Adding "Dark mode" next to the button improves appearance and user experience
**Screenshots**
Before
![circuit15](https://user-images.githubusercontent.com/55310756/76864823-c0a2f480-6887-11ea-9fb7-57afb90845fc.png)
Possible suggestion
![circuit16](https://user-images.githubusercontent.com/55310756/76864853-c8fb2f80-6887-11ea-8fe4-fb28d5087457.png)

**Are you working on this issue? (Yes/No)**
Yes i would like to, if approved to do it.

**Comment by Ananthavijay** [comment]
Create the issue here: https://github.com/CircuitVerse/CircuitVerseDocs/issues

**Comment by Vishruth-S** [comment]
Okay, Thanks
