### ISSUE TITLE
No horizontal margins for icons in simulator

### ISSUE THREAD

**Issue by angad-k** [CircuitVerse/CircuitVerse#1218]
**Is your feature request related to a problem? Please describe.**
Yes. It's a minor UI thing but results in the overall design not looking good.
![HorizontalMarginsForButtons](https://user-images.githubusercontent.com/54415525/76865763-32c80900-6889-11ea-89c1-5c8bb572bdba.png)
So, as it can be seen in the screenshot, the buttons don't have a margin in the horizontal direction which disturbs the overall aesthetics

**Describe the solution you'd like**
A simple addition of margin-left to icon class would solve this problem.

**Are you working on this? (Yes/No)**
Yes, if you think this is important enough.

**Comment by nitin10s** [comment]
Looks good.
