### ISSUE TITLE
Styling fix for "Delete Circuit" and "Edit Layout" buttons in Simulator 

### ISSUE THREAD

**Issue by angad-k** [CircuitVerse/CircuitVerse#1219]
**Is your feature request related to a problem? Please describe.**
Yes, another minor UI issue. So, the "delete circuit" and "edit layout" don't look pretty when we minimize the left panel enough to get them stacked on each other as shown in the screenshot.
![DeleteCircuitAndEditLayout](https://user-images.githubusercontent.com/54415525/76867735-f21dbf00-688b-11ea-8101-bd55d5f72923.png)
They don't have a vertical margin between them and they are also of different sizes.

**Describe the solution you'd like**
If we add a margin-bottom to the class "btn" and also fix both of their widths, it would look much more aesthetically pleasing.

**Are you working on this? (Yes/No)**
Yes, if you consider this relevant enough.

**Comment by nitin10s** [comment]
Looks good.
