### ISSUE TITLE
Holding backspace and dragging corrupts simulator

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#122]
This is a strange one.

Holding down backspace and dragging your mouse will corrupt the simulator. I have absolutely no diagnosis nor explanation as to how or why, I just know it does happen. Pretty consistently too.

**Comment by Amansingla97** [comment]
Can you please give me more details on this issue?.I am not able to reproduce this issue.

**Comment by satu0king** [comment]
@armudgal, what is triage?

**Comment by armudgal** [comment]
@satu0king issues under `triage` needs to be looked upon once again after reproducing and confirming the issue, to figure out the difficulty in resolving it.
