### ISSUE TITLE
Assignments page is broken

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#1220]
**Describe the bug**
- Preview modal doesn't appear when the name of the member is clicked.
- UI should be updated, Text area for entering Grade is missing 

**To Reproduce**
1. Go to circuitverse.org
2. Create a group and assignment
3. Login with another account as a member and submit your work
4. Login with mentor account and see the assignment

**Screenshots**
- When assignments cannot be graded
![CircuitVerse - Digital Circuit Simulator (1)](https://user-images.githubusercontent.com/35162705/76870172-5c842e80-688f-11ea-9519-d49c04f8d588.gif)

- When assignments can be graded
![CircuitVerse - Digital Circuit Simulator](https://user-images.githubusercontent.com/35162705/76870146-51c99980-688f-11ea-8f75-81e04b0e07f6.gif)

**Additional context**
- To fix the issue with preview modal, add this class ````list-group-item-action```` to line no: 62 (app/views/assignments/show.html.erb) because this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/1063
) removed it which caused the issue.
- Regarding the UI make it look like this one https://xd.adobe.com/view/4ae4522f-c144-48b3-48c1-3a23fbfb0aee-3cd5/screen/81629f3c-b1a6-47f3-84c8-ddccd44c08f4/Assignment-Details-Ungraded

**Are you working on this issue? (Yes/No)**
No, Need an urgent fix

**Comment by yash15601** [comment]
@Ananthavijay  I'm working on this

**Comment by yash15601** [comment]
Will make pr soon
