### ISSUE TITLE
Left panel in simulator isn't fully visible when any of the circuit elements is expanded

### ISSUE THREAD

**Issue by angad-k** [CircuitVerse/CircuitVerse#1224]
**Is your feature request related to a problem? Please describe.**
Yes. Though this issue doesn't lead to any loss of information, the border of the properties tab on the left panel gets obscured from below when any of the circuit elements tab is expanded. 
![Screenshot from 2020-03-18 01-07-57](https://user-images.githubusercontent.com/54415525/76895046-44270a80-68b5-11ea-94cf-c7264b4db7ec.png)
As it can be seen in the screenshot, the below portion of the border isn't visible as I cant scroll further below leading to a feeling that the complete left panel isn't visible.

**Describe the solution you'd like**
Adding a margin-bottom of 20px to "#moduleProperty-inner" will solve this problem

**Are you working on this? (Yes/No)**
Yes, once someone reviews this.

**Comment by ALWISH007** [comment]
@angad-k still working on this?

**Comment by abstrekt** [comment]
can be closed, revamp  under process.
@nitin10s

**Comment by nitin10s** [comment]
Let's leave this UI bugs until we are in the process of building the new UI

**Comment by abstrekt** [comment]
sure

**Comment by satu0king** [comment]
Fixed in new UI
