### ISSUE TITLE
Footer alignment issues along with copyright text being slashed

### ISSUE THREAD

**Issue by kulkarniatharv** [CircuitVerse/CircuitVerse#1234]
**Describe the bug**
Alignment issues were observed during testing the footer in different screen sizes along with some text in the copyright section not to be displayed.

![alignment](https://user-images.githubusercontent.com/15829308/76976625-37a8bd80-695a-11ea-802f-fa233fe46bcf.jpg)

**To Reproduce**
Steps to reproduce the behaviour:
Check the footer on a mobile view using Chrome/Firefox DevTools.

**Expected behaviour**
Solving this issue will create a reliable layout for footer along with solving alignment issues.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome.
 - Version 80

**Additional context**
The current footer is made using _HTML Tables_ and styled using _Bootstrap_.
HTML Tables make it very difficult and increase the complexity to properly align everything at every screen size. 

**_CSS Grids_** is the new way of creating layouts on the web and this layout system is **natively** available in the browser which means that it _boosts performance_. CSS Grids make it easier to maintain and understand the code. 
You can read [this awesome article](https://hackernoon.com/how-css-grid-beats-bootstrap-85d5881cf163) by _Per Harald Borgen(Co-founder of Scrimba)_ to know the benefits we get if we use CSS Grids for creating layouts instead of framework like Bootstrap.

The current footer is very complex and difficult to understand. The aim is to make the code less complex and easier to understand along with fixing the alignment issues.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by akansha-singh** [comment]
@kulkarniatharv https://github.com/CircuitVerse/CircuitVerse/pull/1232 this pr already resolved this issue

**Comment by kulkarniatharv** [comment]
@akansha-singh Your PR used **HTML Tables** and **bootstrap** which creates complex code and a heavyweight abstraction(Bootstrap) for layouts. I've used a new and browser native solution **CSS Grids** which will improve performance and also create a simple code which is easy to understand for any future developer. I request you to go through the issue and my PR one more time. Also, take a look at the article mentioned in the issue.

**Comment by kulkarniatharv** [comment]
@aayush-05 Please review the PR.

**Comment by thedarkdivinity** [comment]
I would like to fix this issue but I cannot find the neccessary folder location.Could someone just guide me please.

**Comment by aayush-05** [comment]
Duplicate issue, already opened at #1142 
@nitin10s can be closed

**Comment by nitin10s** [comment]
Duplicate #1142
