### ISSUE TITLE
An illustration on the 'favourites page', If there are no favourite projects of the user

### ISSUE THREAD

**Issue by akansha-singh** [CircuitVerse/CircuitVerse#1237]
**Is your feature request related to a problem? Please describe.**
If there are no favourites added by a user, show an illustration rather than just showing a message

**Additional context**

![WhatsApp Image 2020-03-18 at 18 45 02](https://user-images.githubusercontent.com/47236824/76980131-d59e8700-695e-11ea-9c34-81d67b5f4dc8.jpeg)

**Describe the solution you'd like**
An illustration like this
![undraw_empty_xct9](https://user-images.githubusercontent.com/47236824/76980849-b8b68380-695f-11ea-87d6-e095809bad06.png)

**Are you working on this? (Yes/No)**
yes

**Comment by yash15601** [comment]
@akansha-singh  Can i make a pr  for this
