### ISSUE TITLE
Large empty space(left side), if Description of the project is too large

### ISSUE THREAD

**Issue by akansha-singh** [CircuitVerse/CircuitVerse#1238]
**Describe the bug**

If the circuit description is too large, then the page has lots of white space (Desktop View) below the circuit. 

**To Reproduce**
1. Go to 'https://circuitverse.org/users/3464/projects/16521' (Desktop View)
2. Scroll down
3. See Large empty space on left side (Desktop View)

**Expected behavior**

**Screenshots**

**Are you working on this issue? (Yes/No)**
No

**Comment by Vishruth-S** [comment]
I would like to take up this issue.
I would suggest a fix as shown below by increasing the area of the canvas and also correcting the top-alignment of the main circuit.

Before
![bandicam-2020-03-19-00-02-57-862](https://user-images.githubusercontent.com/55310756/76995213-89ab0c80-6975-11ea-94da-83aa269712fb.gif)

After
![circuit25](https://user-images.githubusercontent.com/55310756/76995587-13f37080-6976-11ea-88e5-0dd3efc0c48c.gif)

It would be great if someone can approve this before i do a PR

**Comment by satu0king** [comment]
A better fix would be to limit the size of the property div and make it scrollable imo. @nitin10s ?

**Comment by nitin10s** [comment]
I agree with @satu0king . That would be the best fix.

**Comment by UltimateGamer07** [comment]
I'd like to implement this issue in the wat that @satu0king said, if you can assign this issue to me ill have a PR within a short while
