### ISSUE TITLE
Mobile sign in page CSS Issue

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#124]
![image](https://user-images.githubusercontent.com/2092958/53416195-f49b4580-39f8-11e9-808e-b834039b6299.png)

The sign in page on mobile is not very aesthetically good looking.

**Comment by Yugandhartripathi** [comment]
I am on it

**Comment by Yugandhartripathi** [comment]
@satu0king I have spotted following associated CSS issues after setting up the project both on mobile and Desktop viewports.<br>
## Like Forgot Password screen here: 
![image](https://user-images.githubusercontent.com/32102845/53435764-959cf700-3a1f-11e9-8ddc-f5482a43adc3.png) <br>
## Signup page on mobile needs same rework as sign in page:
![image](https://user-images.githubusercontent.com/32102845/53435882-dd238300-3a1f-11e9-8864-138574c6c3f0.png)
<br>
I would like to claim responsibility for fixing these.

**Comment by fylux** [comment]
I have an small initial proposal. There is a lot of room for improvement, but probably this is a good example of the way to go: using placeholders, centering the form, use link instead of button to Sign Up, etc. Any suggestion?

[![screen](https://user-images.githubusercontent.com/1207962/53447381-45b93280-3a15-11e9-825d-c040d53ba37f.png)](url)

**Comment by satu0king** [comment]
> I have an small initial proposal. There is a lot of room for improvement, but probably this is a good example of the way to go: using placeholders, centering the form, use link instead of button to Sign Up, etc. Any suggestion?
> 
> [![screen](https://user-images.githubusercontent.com/1207962/53447381-45b93280-3a15-11e9-825d-c040d53ba37f.png)](url)

This looks good, go ahead.

**Comment by satu0king** [comment]
> @satu0king I have spotted following associated CSS issues after setting up the project both on mobile and Desktop viewports.
> 
> ## Forgot Password screen:
> ![image](https://user-images.githubusercontent.com/32102845/53435764-959cf700-3a1f-11e9-8ddc-f5482a43adc3.png) 
> 
> ## Signup page on mobile needs same rework as sign in page:
> ![image](https://user-images.githubusercontent.com/32102845/53435882-dd238300-3a1f-11e9-8864-138574c6c3f0.png)
> 
> 
> I would like to claim responsibility for fixing these.

Please send a PR with the fixes.

**Comment by agarwalrounak** [comment]
@armudgal I guess the `taken` label can be added here.

**Comment by Parikshit-Hooda** [comment]
Please confirm who is finally working on this issue.

**Comment by agarwalrounak** [comment]
I think the PR #156 is for this issue

**Comment by armudgal** [comment]
@agarwalrounak Thanks mate :)

@Parikshit-Hooda Since there is already a PR done, we can mark this as `taken`. @satu0king is reviewing the PR, if I get to squeeze a little more time I will do it. Thoughts?
