### ISSUE TITLE
Small Names of The Circuit Elements

### ISSUE THREAD

**Issue by RohitKumarGit** [CircuitVerse/CircuitVerse#1240]
**Is your feature request related to a problem? Please describe.**
The name of the gates are really annoyingly small

**Describe the solution you'd like**
I want that some kind of tooltip should appear on right where name , and a link should be there , from where the user can know about that gate

**Are you working on this? (Yes/No)**
Yes , I have already designed the cool "tooltip" and thought of the logic of making it appear on hover. I will surely create a basic tooltip and create a PR showing my capability to do it.

**Comment by Shivansh2407** [comment]
Similar to #590

**Comment by RohitKumarGit** [comment]
It hasn't been fixed yet though

**Comment by sgpritam** [comment]
@RohitKumarGit Please provide the ss

**Comment by abstrekt** [comment]
can be closed @nitin10s , it will be addressed on the revamp

**Comment by abstrekt** [comment]
can be assigned to me.

**Comment by satu0king** [comment]
Fixed in new UI
