### ISSUE TITLE
Zooming error in project

### ISSUE THREAD

**Issue by Vishruth-S** [CircuitVerse/CircuitVerse#1241]
**Describe the bug**
By default, circuit is zoomed out. But once zoomed in, it is not possible to bring back to original state

**To Reproduce**
1. Go to https://circuitverse.org/users/3464/projects/16521
2. "Zoom in" the circuit
3. Zoom out

**Are you working on this issue? (Yes/No)**
No

**Comment by yash15601** [comment]
@Vishruth-S it is working fine

**Comment by Shivansh2407** [comment]
Please Check Again or explain the issue elaborately . This is working fine for me as well @Vishruth-S.

**Comment by Vishruth-S** [comment]
Okay...must be some internal error in my browser ig...nevermind

**Comment by Shivansh2407** [comment]
Please Mention the Environment and the browser you are using @Vishruth-S .

**Comment by Vishruth-S** [comment]
My browser is chrome

And this is what i meant by the error
![bandicam-2020-03-19-17-40-11-237](https://user-images.githubusercontent.com/55310756/77066465-36829980-6a09-11ea-9218-b515f3e26287.gif)

**Comment by Vishruth-S** [comment]
I am not able to fully zoom out once zoomed in...

**Comment by yash15601** [comment]
Are you Talking About Mouse scroll or zoom in zoom out button

**Comment by Vishruth-S** [comment]
Both of them give the same issue

**Comment by yash15601** [comment]
@Vishruth-S  both are working fine

**Comment by Vishruth-S** [comment]
Okay...Closing this issue..
