### ISSUE TITLE
UI Enhancement - Color scheme of the Naviagation Bar

### ISSUE THREAD

**Issue by RohitKumarGit** [CircuitVerse/CircuitVerse#1247]
**Is your feature request related to a problem? Please describe.**
The colors of the navigation bar is not , in harmony and completely not par with current modern design trend and scheme

**Describe the solution you'd like**
As the modern design is completely based on flat design and placement , I want that only the logo should be on left , when we hover an item , the background and the color of font should change , moreover the dropdown color scheme is not at all matching the simulator's scheme

**Are you working on this? (Yes/No)**
Yes , I would Like to complete it in Summer .

**Comment by abstrekt** [comment]
can be closed, ui revamp under process
 @nitin10s
