### ISSUE TITLE
UI Enhancement - Color scheme and  look of the Circuit Element Selector

### ISSUE THREAD

**Issue by RohitKumarGit** [CircuitVerse/CircuitVerse#1248]
**Is your feature request related to a problem? Please describe.**
The Design of the sidebar from where we are selecting elements looks "historic" , out of date

**Describe the solution you'd like**

 I want the dropdown to look like bootstrap's accordians. I want some adequate padding and margin between the input elements there. I want buttons to be of  "Ghost style " , all of these will improve the vibe of the website.

**Are you working on this? (Yes/No)**
Yes , I will create a PR with some adjustments but I want to complete this in summer as it's quite time taking

**Comment by abstrekt** [comment]
can be closed @nitin10s
