### ISSUE TITLE
UI Enhancement - Look and placement of buttons in sidebar

### ISSUE THREAD

**Issue by RohitKumarGit** [CircuitVerse/CircuitVerse#1249]
**Is your feature request related to a problem? Please describe.**
There is literally no proper padding and margin between the form elements , especially the two buttons and the input field . Moreover the "Delete circuit button " is of red color , which is not anywhere in the website , Design looks obsolete.

**Describe the solution you'd like**
I want horizontally aligned , same color , "ghost style" button . I want the input not to be of Material style ( sort of ) , instead I want it to look like boostrap's or  bulma's input field . I prefer 'Teal' as the proper color base of the input field.

**Are you working on this? (Yes/No)**
Yes , and I would surely create a PR with buttons improved , but I would like to do all the further adjustments during summer . I would surely show my final idea as a picture in my Proposal :)

**Comment by 1997SHUBHAM** [comment]
Solved this issue

**Comment by abstrekt** [comment]
can be closed @nitin10s

**Comment by abstrekt** [comment]
revamp under process
