### ISSUE TITLE
CircuitVerse Favicon Logo 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#125]
We have a decent CircuitVerse logo but we do not have a good square logo which can be used as favicon or for places we need a shorter form of the logo. 

Not sure what is needed. I am thinking similar to the current Favicon logo would do.

**Comment by blane1257** [comment]
Is there a file type preference?

**Comment by nehavatsyan** [comment]
Is this issue resolved ?

**Comment by satu0king** [comment]
@shubhankarsharma00 I checked the svg image in your PR. Though you have designed as asked, something seems to be missing. Maybe the shorter logo should not be "CV" and instead be a circuit design type logo similar to the current logo.

**Comment by shubhankarsharma00** [comment]
@satu0king I completely agree with the point that there seems to be something missing in the short logo that I designed. If you're thinking of designing a circuit design type logo I'll be happy to assist.

**Comment by Parikshit-Hooda** [comment]
https://circuitverse.org/img/favicon.ico like this.

**Comment by sarthak77** [comment]
Hey, is the issue still open.
I would like to take this up

**Comment by Parikshit-Hooda** [comment]
Hi @sarthak77 Please make a new favicon for CIrcuitVerse somewhat like the current one and then we will see. As of yet, this issue is still under discussion and no one has claimed it..so, I believe that you can.

**Comment by sarthak77** [comment]
Ok I'll be on it

**Comment by pradnyasd** [comment]
@satu0king @Parikshit-Hooda is the issue still open? I have a few ideas. Can I work on this issue?

**Comment by armudgal** [comment]
Hi @pradnyasd , @sarthak77 is working on it and is coming up with a design. If you have any designs in mind please feel free to post them here.

**Comment by sarthak77** [comment]
jbj

**Comment by pradnyasd** [comment]
@armudgal I have made 2 designs. Kindly review it and let me know about the changes if any. 
![screenshot from 2019-03-07 11-41-03](https://user-images.githubusercontent.com/46742046/53935970-4a917c80-40ce-11e9-98b5-9d2a67791251.png)

![screenshot from 2019-03-07 11-41-22](https://user-images.githubusercontent.com/46742046/53935977-50875d80-40ce-11e9-8c69-29fd85d17b54.png)

**Comment by blane1257** [comment]
I like the second design, but I'm not sure how well it will scale..

**Comment by sanctophagus** [comment]
![circuitversefavicon](https://user-images.githubusercontent.com/31550423/53960500-7fbcbf80-410c-11e9-8240-b80727426cda.jpg)
This is one of my own design.
@satu0king @blane1257  @armudgal Please review it.

**Comment by pradnyasd** [comment]
@satu0king @Parikshit-Hooda @armudgal I have made one more favicon logo
![screenshot from 2019-03-08 11-09-09](https://user-images.githubusercontent.com/46742046/54009918-bdfcc200-4192-11e9-9d97-e7e58c6d4945.png)

**Comment by armudgal** [comment]
I really like the second logo. If we can make it more simple and remove the background it will look really good. @satu0king and @tachyons comments?

**Comment by pradnyasd** [comment]
@armudgal I will make the changes and send it to you.

**Comment by pradnyasd** [comment]
@armudgal How is this. Is this as per your expectation?
![screenshot from 2019-03-08 12-14-22](https://user-images.githubusercontent.com/46742046/54012385-e5a45800-419b-11e9-9bea-6928baa8f6dd.png)

**Comment by Parikshit-Hooda** [comment]
An advice : use all the above candidates as favicons in your own browser and compare them with some well known ones like FB, GitHub. My personal favorite is this so far : 
![image](https://user-images.githubusercontent.com/25405707/54078786-6aa28500-42f4-11e9-8616-dbdddde646c8.png)

**Comment by Parikshit-Hooda** [comment]
What is the update on this issue?

**Comment by pradnyasd** [comment]
@satu0king @blane1257  @shubhankarsharma00 @armudgal @tachyons  Any update on this issue??

**Comment by satu0king** [comment]
Please keep the logos simple, Logos like this have too much detail which will be lost when made into a favicon 

![image](https://user-images.githubusercontent.com/2092958/54422009-90d08680-4733-11e9-93e6-213f97ac4b1f.png)

**Comment by satu0king** [comment]
> I like the second design, but I'm not sure how well it will scale..

I agree, we should give it a try.

**Comment by satu0king** [comment]
@blane1257, I am not able to find the logo, you designed, could you share it again here?

**Comment by satu0king** [comment]
> @armudgal @Parikshit-Hooda I have made 2 designs. Kindly review it and let me know about the changes if any.
> ![screenshot from 2019-03-07 11-41-03](https://user-images.githubusercontent.com/46742046/53935970-4a917c80-40ce-11e9-98b5-9d2a67791251.png)
> ![screenshot from 2019-03-07 12-23-59](https://user-images.githubusercontent.com/46742046/53937733-f8ebf080-40d3-11e9-9c14-607211746948.png)
> ![screenshot from 2019-03-07 17-44-45](https://user-images.githubusercontent.com/46742046/53956131-ce645c80-4100-11e9-96f1-4a13e9550ac0.png)
> ![screenshot from 2019-03-07 17-44-00](https://user-images.githubusercontent.com/46742046/53956139-d15f4d00-4100-11e9-9bce-ca00692afebf.png)
> 
> These are the rough designs just to showcase the ideas.
> I have tried to include "C" and "V" in both of them.

Thanks for these designs! 
The second and fourth look good. Can you try making them simpler. Remember, the size of the image will be scaled down to this size, and things will not be visible then. 
![image](https://user-images.githubusercontent.com/2092958/54422430-7ea31800-4734-11e9-97e0-626cf646fd71.png)

**Comment by satu0king** [comment]
> @armudgal How are these? Are these as per your expectations?
> ![screenshot from 2019-03-08 12-14-22](https://user-images.githubusercontent.com/46742046/54012385-e5a45800-419b-11e9-9bea-6928baa8f6dd.png)
> ![screenshot from 2019-03-08 12-16-44](https://user-images.githubusercontent.com/46742046/54012443-12586f80-419c-11e9-934b-c745f61434fd.png)

Hello, these look nice for analog design circuits, not so much for CV

**Comment by satu0king** [comment]
> ![screenshot from 2019-03-08 12-02-46](https://user-images.githubusercontent.com/46742046/54011886-24d1a980-419a-11e9-81de-e275b56ef2ac.png)

This one looks good.

**Comment by Parikshit-Hooda** [comment]
> > @armudgal How are these? Are these as per your expectations?
> > ![screenshot from 2019-03-08 12-14-22](https://user-images.githubusercontent.com/46742046/54012385-e5a45800-419b-11e9-9bea-6928baa8f6dd.png)
> > ![screenshot from 2019-03-08 12-16-44](https://user-images.githubusercontent.com/46742046/54012443-12586f80-419c-11e9-934b-c745f61434fd.png)
> 
> Hello, these look nice for analog design circuits, not so much for CV

The second one in this looks good.

**Comment by satu0king** [comment]
![image](https://user-images.githubusercontent.com/2092958/54425423-52d76080-473b-11e9-8c9f-7009956d75e6.png)

This is the logo by @blane1257. It is my favourite so far. Not very circuity but elegant and recognizable like the GitHub logo. What do you say @armudgal ?

**Comment by pradnyasd** [comment]
@Parikshit-Hooda @satu0king 
Kindly finalize a logo and in case if you need any help do let me know. :blush:

**Comment by Ayannnn** [comment]
I made these Favicon Logo.

![logo](https://user-images.githubusercontent.com/46364732/54457247-e3875e00-4786-11e9-8482-6c67c4b518ed.jpg)
![logo2](https://user-images.githubusercontent.com/46364732/54457248-e3875e00-4786-11e9-9f7d-21af74e6ddb5.png)

**Comment by satu0king** [comment]
Sorry for the delay, we have shortlisted these two logo. 

@blane1257's logo
![image](https://user-images.githubusercontent.com/2092958/54935041-88ebc000-4f45-11e9-9539-f34476d55f4b.png)

@pradnyasd's logo
![image](https://user-images.githubusercontent.com/2092958/54935074-99039f80-4f45-11e9-83df-2971219dd328.png)
Please fine tune your logos. @pradnyasd a black and white logo would be good.

**Comment by Parikshit-Hooda** [comment]
@pradnyasd  please make the whole logo(the one that looks like a voltmeter) in black and white. We will make a final decision based on how that looks.

**Comment by pradnyasd** [comment]
@Parikshit-Hooda @satu0king 
I have made 2 black and white logos. Kindly review it. 
![Screenshot from 2019-03-29 10-20-16](https://user-images.githubusercontent.com/46742046/55210247-7f47ae00-520c-11e9-9d1e-59112ed58f75.png)

**Comment by satu0king** [comment]
@pradnyasd looks good! Will you be able to generate SVGs of the same?

**Comment by swpradnyad** [comment]
@satu0king How should I send you the SVGs? 
This doesn't support SVG format.

**Comment by armudgal** [comment]
Send a PR with the SVG logos. Or else post the code of the SVG here(not recommended).

**Comment by pradnyasd** [comment]
@armudgal  @satu0king 
I have created a PR. Kindly review it and merge it.
