### ISSUE TITLE
Signup and LogIn should happen in the simulator itself.

### ISSUE THREAD

**Issue by RohitKumarGit** [CircuitVerse/CircuitVerse#1250]
**Is your feature request related to a problem? Please describe.**
Consider me a new user , I opened the website and just started playing without noticing the "Sign in" button . Suddenly when I will want to save the project , I will click the button and it will take me out of the page , believe me it's frustating and not okay.

**Describe the solution you'd like**
I want that there should be a cool "modal" , bootsrap's modal is pretty fine . In the modal there should be all sort of login methods , and when the user is signed in , the modal should just go away , updating the simulator without refreshing the page at all.

**Are you working on this? (Yes/No)**
Yes , I have deignned the look of the modal . As understanding the login flow of CircuitVerse will take time , I can't finish it completely as PR , But I will surely show the mentors how I want it to look in proposal with a picture . I will create a basic modal with dummy inputs and a create a PR for sure.

**Comment by abstrekt** [comment]
#1421 shall address this I guess @nitin10s

**Comment by nitin10s** [comment]
Wow, someone noticed this before, didn't know, Closing this #1421 explains the bug better along with the new design
