### ISSUE TITLE
In the mobile mode the menu items shift to right.

### ISSUE THREAD

**Issue by RohitKumarGit** [CircuitVerse/CircuitVerse#1264]
**Describe the bug**
Abnormal position of the menu items.

**To Reproduce**
1. Go to '.simulator'
2. decrease width of browser
**Expected behavior**
The menu items should be properly placed and vericatlly centred.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/59276987/77221389-4d430080-6b6f-11ea-8059-f782b03e3d62.PNG)

**Desktop ( windows 10):**

 - Browser [chrome]

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Nitish145** [comment]
@RohitKumarGit simulator will be disabled on mobile.

Please close this issue..
