### ISSUE TITLE
Adding Comments Section under Projects.

### ISSUE THREAD

**Issue by Sj1218305** [CircuitVerse/CircuitVerse#1265]
**Describe the solution you'd like**
Adding "See Responses" at the end of Project. Here users can see other's comments and can also add if they want. This will help in providing more specified description of the project.

![4HefbVP](https://user-images.githubusercontent.com/46301590/77227625-ad559900-6ba7-11ea-9ff3-6264ed669a6a.png)

**Are you working on this? (Yes/No)**
YES

**Comment by Shivansh2407** [comment]
Please Post the screenshots. Similar to #1073

**Comment by Sj1218305** [comment]
I have not started working on this issue yet. When the mentors will review it and if they permit me, then I will post the required screenshots in a PR

**Comment by aayush-05** [comment]
Is this issue about adding a comment section to the website @Sj1218305 ?

**Comment by aayush-05** [comment]
@nitin10s can be closed. Fixed by Aboobacker already
