### ISSUE TITLE
Invert Colors

### ISSUE THREAD

**Issue by akshathkaushal** [CircuitVerse/CircuitVerse#1274]
**Is your feature request related to a problem? Please describe.**
I have seen a feature of inverting colors in some projects. So I want to add the same feature in the simulator at least.

**Describe the solution you'd like**
I am thinking of adding a toggle button which can help in switching between inverted and original mode.

**Are you working on this? (Yes/No)**
yes

**Comment by abstrekt** [comment]
Can be closed, themer under process. @nitin10s

**Comment by nitin10s** [comment]
Revamping the simulator so closing this
