### ISSUE TITLE
Make Cards Clickable

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1277]
### make Example cards clickable

![image](https://user-images.githubusercontent.com/41790090/77235019-2f9b8880-6bbb-11ea-827e-eba8feb97f5b.png)

###Are you working on it (NO)

**Comment by Cinderace** [comment]
Hey, can I work on this?

**Comment by Vishruth-S** [comment]
I would like to commit a change as shown below
![bandicam-2020-03-22-18-43-51-708](https://user-images.githubusercontent.com/55310756/77250360-90839900-6c6d-11ea-8d6a-1d5ff95c2d67.gif)

@mahmodHammad  Please suggest if any further modification is required

**Comment by mahmodHammad** [comment]
@Vishruth-S 
this hover effect is good 
but it would be great if you could add this line 
transition: all 0.3s ease;

![ani](https://user-images.githubusercontent.com/41790090/77261471-59c27880-6c97-11ea-87d0-0ea617de1fce.gif)

**Comment by Vishruth-S** [comment]
@mahmodHammad 
Is this alright?
![bandicam-2020-03-23-08-56-00-995](https://user-images.githubusercontent.com/55310756/77278146-99638180-6ce4-11ea-98cd-8f04539fe6c4.gif)

**Comment by mahmodHammad** [comment]
@nitin10s  
Please take a look at this

**Comment by nitin10s** [comment]
Reduce the size of the circuit box when hovered, like in the picture @mahmodHammad sent.

**Comment by nitin10s** [comment]
@Cinderace should work on this issue if available.

**Comment by Cinderace** [comment]
@nitin10s Okay! I'm on it!

**Comment by Vishruth-S** [comment]
@Cinderace Really sorry I didn't notice your earlier comment. I am no longer working on this, You can take it up :)

**Comment by Cinderace** [comment]
@chaudharirohit2810 I am currently working on it. Please find another issue. Thank you.

**Comment by chaudharirohit2810** [comment]
Okay

**Comment by mahmodHammad** [comment]
@Cinderace  any updates?

**Comment by Kushagraw12** [comment]
Is this issue closed, or can i take it up? 
Thanks!

**Comment by nitin10s** [comment]
We won't be having this page after completing the revamp, @aayush-05 is handling the new UI, he can bring you up with any sort of contribution required in this area 😄

**Comment by Kushagraw12** [comment]
> We won't be having this page after completing the revamp, @aayush-05 is handling the new UI, he can bring you up with any sort of contribution required in this area 😄  

Okay. I want to make contributions, i am new to this org. Please let me know from where I can start! Thanks! :)
