### ISSUE TITLE
Seperate Tab for Element and Properties menu

### ISSUE THREAD

**Issue by Sudhir-Pawar** [CircuitVerse/CircuitVerse#1280]
Circuit Element and properties can be separated  

![sep](https://user-images.githubusercontent.com/54767646/77246773-738c9d00-6c50-11ea-9e87-8998318566a2.png)

I have prepared sample mock up how menu might look like.It allow faster access of properties a user can select a element which is being placed in simulator and dive into its properties faster through it.

**Comment by yash15601** [comment]
???? @Sudhir-Pawar  description  please

**Comment by abstrekt** [comment]
can be closed @nitin10s

**Comment by nitin10s** [comment]
Revamping the simulator so closing this
