### ISSUE TITLE
collapsing simulator on adding new circuit

### ISSUE THREAD

**Issue by krishanu-2001** [CircuitVerse/CircuitVerse#1287]
**Describe the bug**

 ### The new circuit fails when input name is large for the screen size.
![issue2](https://user-images.githubusercontent.com/56930593/77223262-e3335700-6b80-11ea-968c-c7dbe148d765.png)

**To Reproduce**
1. Go to 'simulator'
2. Click on 'circuit'
3. Scroll down to 'new circuit +'
4. type a name larger than first row*

**Expected behavior**
the simulator collapses, only way out is to delete circuit.

**Screenshots**

As above 
 

**Desktop (please complete the following information):**
 - OS: windows 10, ubuntu 18.0.4
 - Browser : chrome
 - Version 80.0.3987.149 (Official Build) (64-bit)

**Additional context**
-This is my first issue.
-I would really appreciate your feedback and support

**Are you working on this issue? (Yes/No)**
yes, please

**Comment by Shivansh2407** [comment]
I appreciate your work but this is similar to #617 . This has been fixed in #897 .

**Comment by krishanu-2001** [comment]
sure, great work there!. 
Here i wanted to try something different, I allow any input size but hide the display of whole name. The name can be viewed by hovering. This has been described in figures:
agian if this is a problem, i can tag it as Ui improvement or something...

images:
1.
![hut1](https://user-images.githubusercontent.com/56930593/77310829-05fe7080-6d25-11ea-9ede-3571bd245238.png)
 2.
![hut2](https://user-images.githubusercontent.com/56930593/77310842-0b5bbb00-6d25-11ea-9bbf-d9091e1b5628.png)

**Comment by Shivansh2407** [comment]
Sure go ahead . But keep in mind whether it will work for longer inputs or not.

**Comment by krishanu-2001** [comment]
That i will.
should i change title of issue. if it causes issue!

**Comment by nitin10s** [comment]
Duplicate #617
