### ISSUE TITLE
Add code linter

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#129]
As the code base grows large, a code linter like rubocop - https://github.com/rubocop-hq/rubocop will make it very easy to keep a hold of overall code quality by imposing strict checks. 

Once added, the entire code-base will have to linted. Most of errors will get fixed by `rubocop -a`

**Comment by ankitkataria** [comment]
I would like to self assign the issue! :smile:

**Comment by tachyons** [comment]
Also eslint or prettier  for js code

**Comment by ankitkataria** [comment]
Also, a .editorconfig can have to be added for uniform formatting.

**Comment by tachyons** [comment]
I am not fan of linting whole code together as it will change git history without any functional change. But since this project is in early stage, it may be fine. @satu0king your thoughts please

**Comment by ankitkataria** [comment]
If we don't want to lint the whole code-base at once, we can look into running rubocop only on those files that are being changed before every commit - 
`git ls-files -m | xargs ls -1 2>/dev/null | grep '\.rb$' | xargs rubocop`
We can add this as a pre-commit hook.

**Comment by tachyons** [comment]
@Ankitanvesh https://github.com/brigade/overcommit does this

**Comment by ankitkataria** [comment]
Thanks :+1: , I'll look into them once.

**Comment by armudgal** [comment]
@tachyons looks like you tagged the wrong Ankit :D

**Comment by tachyons** [comment]
Oops, sorry

**Comment by satu0king** [comment]
> I am not fan of linting whole code together as it will change git history without any functional change. But since this project is in early stage, it may be fine. @satu0king your thoughts please

True, it will change git history without any functional change but it has to happen sometime! We can do it along with the refactor of #199. I would not want to do it now as it will raise unnecessary conflicts with everyone's PRs.

**Comment by ankitkataria** [comment]
> True, it will change git history without any functional change but it has to happen sometime! We can do it along with the refactor of #199. I would not want to do it now as it will raise unnecessary conflicts with everyone's PRs

Maybe we can explore of the option of still setting up codeclimate where we can view all the new offences and try fix most of them in each pr. This way add the new additions will be free of lint errors.
