### ISSUE TITLE
Alignment Issue of Title in Mobile View

### ISSUE THREAD

**Issue by Sj1218305** [CircuitVerse/CircuitVerse#1291]
**Describe the bug**
alignment issue in magin of Title of Project in mobile view.

**To Reproduce**
1. Go to 'Simuator in Mobile view'
2. Click on 'Hamburger button'
3. See error

**Screenshots**
![RvsyS6O - Imgur](https://user-images.githubusercontent.com/46301590/77392115-4232df00-6dc0-11ea-94db-6bfe0738aa51.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser - Chrome

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aayush-05** [comment]
@tachyons can be closed. Issue already raised under #1028

**Comment by aayush-05** [comment]
@nitin10s @tachyons this can be closed

**Comment by nitin10s** [comment]
Duplicate #1028
