### ISSUE TITLE
featured_circuits Still on the old UI

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1293]
**Describe the solution you'd like**
I Think https://circuitverse.org/featured_circuits Should look like  https://circuitverse.org/examples

![image](https://user-images.githubusercontent.com/41790090/77410479-93909d80-6dc3-11ea-86ef-1769f839328e.png)

**Are you working on this? (Yes/No)**
NO

**Comment by abstrekt** [comment]
can you confirm @nitin10s I can work on it!

**Comment by nitin10s** [comment]
The thing is there is a confusion with the search bar, featured circuits, examples, Editor Picks. We plan to resolve this during the GSoC Period.

**Comment by kromate** [comment]
Can i also work on this @nitin10s ?

**Comment by nitin10s** [comment]
Part of a GSoC project
