### ISSUE TITLE
Log In link in Footer does nothing if user is logged in

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1294]
**Describe the bug**
The login link in footer redirects to nowhere if the user is logged in.

**To Reproduce**
1. Log in to CircuitVerse
2. Click Login in the Footer

**Expected behavior**
Clicking on it should redirect to the My Circuits Page

**Are you working on this issue? (Yes/No)**
No

**Comment by yash15601** [comment]
@nitin10s  will try to fix this asap

**Comment by yash15601** [comment]
@nitin10s  we should remove that link if the user is logged in their no use of that link

**Comment by Ananthavijay** [comment]
I think it would be better if `Login `changes to `My Circuits` if the user is logged in.

**Comment by yash15601** [comment]
@Ananthavijay  let see what @nitin10s  says

**Comment by nitin10s** [comment]
I agree with @Ananthavijay

**Comment by yash15601** [comment]
@nitin10s  okay will do that

**Comment by nitin10s** [comment]
Please see to it that you resolve your previously opened PRs before taking up new issues.

**Comment by yash15601** [comment]
yes @nitin10s  I'm working on that issues  just facing some little problems will fix that pr soon
