### ISSUE TITLE
Circuit Preview not Available

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1297]
**Describe the bug**
Some of the circuit previews can't be seen

**To Reproduce**
As far as I know, the circuits that you yourself make have the preview.
The circuits that you fork from someone else don't have the preview.

**Expected behavior**
A preview should be visible

**Screenshots**
![FireShot Capture 210 - Nitin Singhal - Favourite Circuits - circuitverse org](https://user-images.githubusercontent.com/16988558/77537700-814a5880-6ec4-11ea-844b-beafd299ce41.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
Can I fix this @nitin10s ?

**Comment by nitin10s** [comment]
No, please fix your already opened PRs before taking up new issues.

**Comment by ShubhankarKG** [comment]
What files handle these ? I'm unable to locate one. Any help @Shivansh2407 ?

**Comment by yash15601** [comment]
CircuitVerse/app/views/users/logix

**Comment by Nitish145** [comment]
@ShubhankarKG you working on this ??

**Comment by Shivansh2407** [comment]
@ShubhankarKG as @yash15601 said. I guess this might be an issue due to image_tag or the image URL. 👍

**Comment by ShubhankarKG** [comment]
Yeah, I'm working on this @Nitish145 . I might finish it by day after tomorrow at earliest. Thanks @Shivansh2407 @yash15601

**Comment by aayush-05** [comment]
@ShubhankarKG you still working on this ?

**Comment by ShubhankarKG** [comment]
Couldn't find a valid fault in the image tags. Not working.

**Comment by aayush-05** [comment]
@tachyons can you help ?

**Comment by satu0king** [comment]
@Nitish145 Can you fix this? Basically you need to create a copy of the image when forking.

**Comment by Nitish145** [comment]
AFAIK we remove the circuit preview while forking, removing that would suffice i guess..

Will give it a shot.. @satu0king

**Comment by aayush-05** [comment]
Was their any specific reason for [this](https://github.com/CircuitVerse/CircuitVerse/blob/59410933500a51a868e4224e25ee4c7b30669a0c/app/controllers/projects_controller.rb#L71) though?

**Comment by Nitish145** [comment]
> Was their any specific reason for [this](https://github.com/CircuitVerse/CircuitVerse/blob/59410933500a51a868e4224e25ee4c7b30669a0c/app/controllers/projects_controller.rb#L71) though?

Since `image_previews` are not copied directly, it's was once better to just remove them.. @aayush-05
