### ISSUE TITLE
Starring the Circuit has problems

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1298]
**Describe the bug**
On opening any of the favourite circuits, the icon displays it the opposite, although the working is completely fine.

**To Reproduce**
1. Go to your favourite projects
2. Open one of the circuits and observe the icon should be filled.

**Expected behavior**
The icon should appear filled if the circuit has been already starred.

**Screenshots**
![Untitled_ Mar 25, 2020 6_27 PM](https://user-images.githubusercontent.com/16988558/77539339-34b44c80-6ec7-11ea-90ab-57a92832a2c4.gif)

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
Working on it @nitin10s

**Comment by nitin10s** [comment]
Ok, but see to it, that you've resolved your already opened PRs as well.

**Comment by aayush-05** [comment]
@nitin10s this can be closed >> fixed with new UI
