### ISSUE TITLE
Top Users

### ISSUE THREAD

**Issue by kromate** [CircuitVerse/CircuitVerse#1304]
**feature request**
Noticed the coming soon feature of Top User request in the examples page and would love to work on it

**Describe the solution you'd like**
create a table with the users their projects and time spend on the site ( Depending on what is used to grade the top users ). planning on building the table using bootstrap and making it dynamic but adding a JavaScript function to update the table automatic after checking for users and screening the top users among all users depending on set criteria

**Are you working on this? (Yes/No)**

Yes

**Comment by aayush-05** [comment]
Maybe you can discuss the approach you are planning on Slack @kromate
