### ISSUE TITLE
Search 

### ISSUE THREAD

**Issue by kromate** [CircuitVerse/CircuitVerse#1305]
**feature request.**
Noticed that the Search bar in the Examples page doesn't have a search button and would require the user to click the enter button on their keyboard before it search, this might be inconvenient for mobile users and users with faulty keyboard

**Describe the solution you'd like**
I would just be adding a search button beside the search bar, to make things easier and this button would probably be a bootstrap button   

**Are you working on this? (Yes/No)**
YES @nitin10s

**Comment by nitin10s** [comment]
Yep, thats needed. Cool

**Comment by kromate** [comment]
The page were the search bar is located can be found under which sub repo

**Comment by harshgujrati** [comment]
CircuitVerse\app\views\logix\examples.html.erb

**Comment by nitin10s** [comment]
Being worked upon under a GSoC Project
