### ISSUE TITLE
Empty group member list gives success message

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#131]
Adding group members without any emails shows the success message that a groups member has been added. It should show an error message regarding the empty email field. 
Similar issue occurs while adding collaborators.

**Comment by ankitkataria** [comment]
I would like to self assign this issue. :slightly_smiling_face:

**Comment by satu0king** [comment]
I would like the message to show the following details. 

- [ ] Number of emails newly invited 
- [ ] Number of emails already invited
- [ ] Number of emails failed (email is not actually an email)

For checking if the email given is an email, right now, the system doesn't parse the email strings to check if the string is actually an email. You will need to implement this.

**Comment by ankitkataria** [comment]
We can use `validates :email, format: { with: URI::MailTo::EMAIL_REGEXP  }` in the required models to check the emails. I also wanted to propose the use of [strong params](https://edgeguides.rubyonrails.org/action_controller_overview.html#strong-parameters) as it a good security practice.

**Comment by satu0king** [comment]
> We can use `validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }` in the required models to check the emails.

This is good, but we might not want to create a PendingInvitation record in the first place if the email ID is incorrect.
