### ISSUE TITLE
Copy Component copying it Literally ! 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1311]
**Describe the bug**
when user copy a component he copies it as text so if he pasted in other places he would past  the component's details as a big object

![copy](https://user-images.githubusercontent.com/41790090/77840338-a4a42a80-7186-11ea-9c9a-c2b0b6af80f7.gif)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome

**Are you working on this issue? (Yes/No)**
YES

**Comment by satu0king** [comment]
Why is this approach wrong?

**Comment by mahmodHammad** [comment]
@satu0king 
i think because users shouldn't see any side effects from our code, like this long object when he past at somewhere else

**Comment by abstrekt** [comment]
though it is necessary to copy the object as text so that it can be pasted & render, I'm not sure we can avoid pasting the object somewhere else, a solution would be to have windows clipboard to be personal to the simulator,
@satu0king, please review

**Comment by mahmodHammad** [comment]
@abstrekt  
WE can use local storage 
i have done that before , and it's perfectly working

**Comment by mahmodHammad** [comment]
it's an  unnoticeable issue 
but we will not be able to make a custom shortcut with the current implementation 
so what would you say @satu0king
