### ISSUE TITLE
copy cut past with a keydown! 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1312]
**Is your feature request related to a problem? Please describe.**
I want to assign a key like c to copy directly, x to cut, v to past .without having to press CTRL

**Additional context**
this would make it possible to customize keys for Copy, Cut, and Past later!
**Are you working on this? (Yes/No)**
YES

**Comment by abstrekt** [comment]
It is listed in assignment task for a project , **custom shortcuts**, most of the applicants have already implemented it in their private repo,

**Comment by mahmodHammad** [comment]
> It is listed in assignment task for a project , **custom shortcuts**, as well as it is a project task too, most of the applicants have already implemented it in their private repo,

This is not the project task

**Comment by aayush-05** [comment]
@tachyons @nitin10s shall we close this one

**Comment by mahmodHammad** [comment]
> @tachyons @nitin10s shall we close this one

Why?

**Comment by aayush-05** [comment]
Because as far as I know, GSoC tasks would eventually be converted to Issues during the community bonding period.

**Comment by tachyons** [comment]
No need to close this issue

**Comment by aayush-05** [comment]
@tachyons @nitin10s please can anyone of you reopen this issue then

**Comment by aayush-05** [comment]
@nitin10s this can be added in the new Key Shortcuts feature @abstrekt is developing
