### ISSUE TITLE
Deselecting elements in Simulator

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1316]
**Describe the bug**
Currently, to deselect the selected elements on the simulator, we have to double click on a clear space.

**To Reproduce**
1. Go to Simulator
2. Select one or more elements
3. Double click somewhere else to deselect

**Expected behaviour**
As used in Windows and everywhere as far as I remember, a single click should deselect the element.

**Screenshots**
![FireShot Capture 216 - CircuitVerse - Digital Circuit Simulator online - circuitverse org](https://user-images.githubusercontent.com/16988558/77852044-1ec1c700-71fa-11ea-8adf-e1f7bd312c5d.png)

**Comment by mahmodHammad** [comment]
can i work on it ?

**Comment by nitin10s** [comment]
Work on your proposal, please. Take up issues after 31st.

**Comment by mahmodHammad** [comment]
@nitin10s 
DONE ! 🙂
![selet](https://user-images.githubusercontent.com/41790090/77852271-0643b380-71de-11ea-9973-a635b2a744d1.gif)
