### ISSUE TITLE
CircuitVerse Help Doesn't work for some elements.

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1317]
**Describe the bug**
The Help feature doesn't work for most of the elements. E.g NAND Gate

**Screenshots**
![download](https://user-images.githubusercontent.com/16988558/77852884-9b56a480-71fe-11ea-97eb-992d021939cb.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Ananthavijay** [comment]
Can I work on this?

**Comment by Potential17** [comment]
Would like to work on this
