### ISSUE TITLE
Keep the Properties Menu fixed and scroll just the elements menu in the simulator

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1318]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the element menu expands and the property menu goes below the screen and I have to scroll for it.

**Describe the solution you'd like**
Keep the Property Menu fixed at the bottom left and just make the element list scroll-able. At the same time, bring the expanded element list into focus, scrolling can be minimized

**Screenshot**
![propertymenu](https://user-images.githubusercontent.com/42511766/77862652-8dbf1000-723a-11ea-8d03-413d75c12d44.png)
The Property Menu can't be accessed without scrolling

**Are you working on this? (Yes/No)**
No

**Comment by mahmodHammad** [comment]
thank you for reporting that.
actually this sidebar is going to be redesigned as a part of project 4, **as soon as possible :)**

**Comment by Potential17** [comment]
Would like to work on this issue

**Comment by aayush-05** [comment]
@Potential17 you want to work on this issue ?

**Comment by abstrekt** [comment]
Can be closed, UI Revamp in progress.
