### ISSUE TITLE
Misleading Icon in Simulator

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1320]
**Describe the bug**
The delete icon on the right toolbar is a cross that is misleading. It should instead be a "bin"

**Screenshots**
![FireShot Capture 218 - CircuitVerse - Digital Circuit Simulator online - circuitverse org](https://user-images.githubusercontent.com/16988558/77942063-bd245a00-72d8-11ea-8f93-5f71255b7e35.png)

**Comment by nitin10s** [comment]
@satu0king whatsay?

**Comment by yash15601** [comment]
@nitin  I think yes it should be change

**Comment by Ananthavijay** [comment]
And also the undo icon should be other way, right now it looks like rotate icon

**Comment by nitin10s** [comment]
Yep

**Comment by Ananthavijay** [comment]
Can I work on this?

**Comment by yash15601** [comment]
@Ananthavijay yes u can
