### ISSUE TITLE
Featured Examples cards 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1323]
**Describe the bug**
Featured Examples cards are broken at Medium screens (starting from 768px to 1200px )
**To Reproduce**
1. Go to 'https://circuitverse.org/'
3. Scroll down to 'featured examples'
4. reduce screen width

**Expected behavior**
cards should have the same width and the same height.
**Screenshots**
![image](https://user-images.githubusercontent.com/41790090/77982709-3d64b280-730d-11ea-8add-d2dc4c6c512f.png)

**Are you working on this issue? (Yes/No)**
NO

**Comment by Shivansh2407** [comment]
In #532 we have discussed this issue, https://github.com/CircuitVerse/CircuitVerse/issues/532#issuecomment-596220506 points to how this can be fixed. I would like to know the views of @nitin10s and @tachyons on this.

**Comment by harshgujrati** [comment]
Can we implement the cards as in examples page @Shivansh2407 @mahmodHammad

**Comment by aayush-05** [comment]
@nitin10s this can be closed. Similar to #532
