### ISSUE TITLE
Direction of undo button

### ISSUE THREAD

**Issue by bolubee101** [CircuitVerse/CircuitVerse#1325]
While minute, the direction of the undo button is in the clockwise direction. This goes against intuition. I propose that it be turned in the other anti-clockwise direction.
![Screenshot (102)](https://user-images.githubusercontent.com/32003376/77995941-98ee6a80-7324-11ea-9f37-321a4c3b2159.png)

**Comment by Shivansh2407** [comment]
Similar to #1320 . Fixed in #1321 .

**Comment by bolubee101** [comment]
Oh, OK. Thanks

**Comment by Ananthavijay** [comment]
This issue can be closed.
