### ISSUE TITLE
Bug with Report Bug 

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1326]
![report](https://user-images.githubusercontent.com/41790090/78023614-3ebacd00-7357-11ea-9900-8fd946a60356.gif)
**Describe the bug**
if the user accidentally pressed on a custom shortcut, it would be executed.

also **copy , past , cut doesnt' work**
**Are you working on this issue? (Yes/No)**
YES, I Already have Done this fix on my machine a will make a PR with the solution soon

**Comment by yash15601** [comment]
Please elaborate  the bug @mahmodHammad

**Comment by Shivansh2407** [comment]
Actually @yash15601 , @mahmodHammad wants to say that the keyboard functions that are enabled in the simulation area,upon executing them accidentally in the text area of the report bug feature also works. That means CTRL + S will save the project in the background.

**Comment by mahmodHammad** [comment]
> Please elaborate the bug @mahmodHammad
while entering the issue message the simulator still listen to the input , if user entered 
CTRL + z  for example it will undo changes on the simulator 
the worse this would be when he was selecting an element then report issue , and clicked backspace , the component would be deleted

**Comment by yash15601** [comment]
Okay @mahmodHammad  got it😇

**Comment by Shivansh2407** [comment]
Also Select all, Copy Paste feature also does not works, They all keep on working in the simulation area in the background.

**Comment by mahmodHammad** [comment]
@Shivansh2407  
i will update the issue with that

**Comment by Shivansh2407** [comment]
Sure @mahmodHammad 👍
