### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#133]
Refer: https://thoughtbot.com/blog/circleci-2-rails

**Comment by ankitkataria** [comment]
@tachyons 
I was going to suggest this while I was working on a few issues yesterday. This will make reviewing and testing the PR very easy. If possible I was hoping to work on setting up the CI/CD pipeline. :smile:

**Comment by tachyons** [comment]
Fixed in #186
