### ISSUE TITLE
Delay in Arrow, Rectangle and Text to be removed

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1331]
**Describe the bug**
Delay in Arrow, Rectangle and Text field should be removed.
@satu0king can tell better on the other elements that don't require this.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/16988558/78048621-99741900-7397-11ea-9b2a-15fdaf750733.jpg)

**Comment by Shivansh2407** [comment]
@nitin10s can I work on it? @satu0king please let me know which elements do not require these labels.
