### ISSUE TITLE
Splitter cannot split 32-bit line

### ISSUE THREAD

**Issue by jaideepheer** [CircuitVerse/CircuitVerse#1332]
#### I am submitting a -
* [] **Feature Request**
* [-] **Bug Report**

#### Describe your bug/feature -
When a splitter is attached to a 32-bit line, it causes a connection error if the line has the 32nd bit(MSB) as 1.
#### Expected behavior -
The splitter should be able to split without errors.
#### Screenshots (if relevant) -
![image](https://user-images.githubusercontent.com/15523937/69902975-aa952500-13b9-11ea-954d-3c267984590b.png)

#### Are you working on this issue? (Yes/No)
No

**Comment by YashKumarVerma** [comment]
Looks like this is a fundamental issue.

https://stackoverflow.com/questions/25828450/javascript-bitwsie-operation-0-2147483648-yields-2147483648

**Comment by satu0king** [comment]
@gr455 check this please?

**Comment by gr455** [comment]
I think this is happening because the value is becoming signed somewhere in the middle of splitter resolution
