### ISSUE TITLE
Stretched images in example page

### ISSUE THREAD

**Issue by harshgujrati** [CircuitVerse/CircuitVerse#1336]
**Is your feature request related to a problem? Please describe.**
Images on example page are stretched
**Describe the solution you'd like**
Edit the image such that it looks normal and changing the background of all image to white to maintain uniformity

**Additional context**

**Are you working on this? (Yes/No)**
  Yes

**Comment by MayankVir** [comment]
I would like to work on this feature update

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed >> Examples page revamped
