### ISSUE TITLE
Unit tests for all models

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#134]
Refer: https://github.com/rspec/rspec-rails

**Comment by ankitkataria** [comment]
Currently tests are written using `ActiveSupport::TestCase`. `RSpec` is the most widely used testing framework for ruby. 
Are you proposing to add this as a new dependency? If so, will we have to re-write all the existing specs?

**Comment by tachyons** [comment]
All of those tests are just empty files. So we will have to start fresh anyway. So better use Rspec

**Comment by ankitkataria** [comment]
Then tests will also be required for various controllers, helpers, and mailers. Only after the tests are complete a CI/CD pipeline can be set up. I'll open up issues for them.

**Comment by vik-y** [comment]
Rspec + Factorybot 

We'll start first with model level tests - that's high priority.

**Comment by ankitkataria** [comment]
Great! I'll start working on this. :man_technologist:
