### ISSUE TITLE
Configure codeclimate for code style review

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#135]
Related to #129

**Comment by rishi-s8** [comment]
I would like to work on this. Can you give me some pointers?

**Comment by armudgal** [comment]
Hi @rishi-s8, you can read about ESlint and how to configure it with CodeClimate, you might need our access to add the repository and setup the configuration but we would really like if you could setup everything and ping us back.

Would you be up for this issue then?

**Comment by tachyons** [comment]
He can do in the forked project where he have full access

**Comment by ankitkataria** [comment]
Looks cool! @rishi-s8 let me know if you need help on this one. :tada:

**Comment by rishi-s8** [comment]
Yes. I am on it. :)

**Comment by armudgal** [comment]
@tachyons I think that even if he does it on the forked project, codeclimate will only do the checks for the forked project. we need to link CircuitVerse/CircuitVerse to codeclimate to link this project.

**Comment by rishi-s8** [comment]
@armudgal, I read about ESLint and CodeClimate and was able to add my forked repository to CodeClimate. 
Here's the screenshot of the issues page.
![screenshot 2019-03-04 at 3 10 00 pm](https://user-images.githubusercontent.com/33762894/53724373-bafe8a80-3e8f-11e9-9870-af866856a6a7.png)
Can you help me with what I have to do next?
Also, I read about ESLint, and that is for JavaScript Apps I guess. Though I found other gems for Ruby on Rails apps.

**Comment by tachyons** [comment]
Looks good, but need to fix #129 before this

**Comment by rishi-s8** [comment]
I can try #129 too. :)

**Comment by ankitkataria** [comment]
@rishi-s8 I've mentioned in the issue about rubocop, you can look into it. You'll need to add a `.rubocop.yml` file in the project with the rules. Similarly for js you'll have to add an `eslintrc` file.
Once added, there will be a lot of linting violations in the codebase which will have to be fixed. I'm not sure if we're supposed to go ahead and make all the linting changes at once. 
I'm been looking in a rubocop file for the project already. If you wish to you can help out with eslint. :slightly_smiling_face:

**Comment by ankitkataria** [comment]
You can work on top of #188 to add eslint.
