### ISSUE TITLE
Change the Login System to Pop-up

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1355]
**Is your feature request related to a problem? Please describe.**
Currently, the login page is used from two different places - 
1. Simulator
2. CircuitVerse Platform

The users accessing the login from the simulator have to redirect to a completely different screen that proves to create friction in users' journey. 

**Describe the solution you'd like**
I wanted to propose a **Pop-up Login and Signup system** so it gets easy for simulator users to log in and signup

**Comment by yash15601** [comment]
Can I work on this @nitin10s

**Comment by nitin10s** [comment]
Let's just first discuss on this.

**Comment by yash15601** [comment]
Sure

**Comment by tachyons** [comment]
Even if we rely on popup login, we still have to reload the page to apply the changes.

**Comment by yash15601** [comment]
@tachyons  is right after  pressing  login the page will surely reload to check if user exist in db if then will get access this will reload the page

**Comment by Shivansh2407** [comment]
@tachyons @nitin10s a login modal can be displayed on load of the page in top right corner in the main page just below the sign in ( which can be closed if not needed or will not be shown if the user is signed in ) .

**Comment by nitin10s** [comment]
Is it possible we reload just the popup rather than the whole page?

**Comment by yash15601** [comment]
@nitin10s  its is possible  to reload  only modal but we have also change username in simulator  at right corner that requires  page reload

**Comment by nitin10s** [comment]
I get it and that reload is okay. The current basically disconnects the user from the simulator canvas to redirect to a completely different place. That's the problem.
.

**Comment by yash15601** [comment]
Yes @nitin10s  I think we can change  it  by redirecting it simulator  rather than  redirecting  it to home page

**Comment by aayush-05** [comment]
What if we save the current circuit in browser storage when the login button is pressed. The user_id to which the circuit is to be saved can be taken from the login credentials, and then after login redirect the user back to that saved circuit.

**Comment by nitin10s** [comment]
The user needs a feedback when he presses the login button, the feedback that the top right Sign in changes to his name.

**Comment by yash15601** [comment]
Yess and that require page reload to change state

**Comment by mahmodHammad** [comment]
I am with not to redirect the user to a separate page to login.
the popup will be perfect

**Comment by mahmodHammad** [comment]
@tachyons  
Can use promises to apply the changes. , instead of reloading the whole page?
It could be something like this section at _data.js [line 503]_
![image](https://user-images.githubusercontent.com/41790090/78524567-9da79880-77d4-11ea-877c-99a0a6b91fe0.png)

if success->display a message to indicate he successfully logged in then close the popup form and update (username, id,...etc)
if failure ->  display a message to try again

**Comment by aayush-05** [comment]
> Yess and that require page reload to change state

I understand, that is why I am saying we can first save the current circuit in the browser storage, so the current progress isn't lost and then after reloading, we can open up the same circuit.
Although one thing I am not sure is whether we can get the user_id from the database concurrently as the user is getting logged in.
