### ISSUE TITLE
Problem in Edit Assignment page

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1356]
**Describe the bug**
Currently, there are two buttons Show and Back.
The Show button is basically a back button, the Back button redirects to the My Circuits Page
![FireShot Capture 236 - CircuitVerse - Digital Circuit Simulator - circuitverse org](https://user-images.githubusercontent.com/16988558/78506535-c2c9e600-7797-11ea-828d-3b6c3908b8d6.png)

**Expected behavior**
The Show button should be renamed as Back and be styled as all the other back buttons and placed in the right of Update Project button.

The other back button should be removed.

**Comment by Nitish145** [comment]
Can i work on this issue?

**Comment by nitin10s** [comment]
Sure.
