### ISSUE TITLE
Self inviting for collaborators

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1357]
**Describe the bug**
Currently, I can invite myself through Add a collaborator for any project. This should not happen and an error should be displayed - You can't invite yourself.

**Comment by harshgujrati** [comment]
can i work on this @nitin10s

**Comment by harshgujrati** [comment]
can i work on this @nitin10s

**Comment by Nitish145** [comment]
@harshgujrati you working on this issue ? or shall i take up this one..
