### ISSUE TITLE
Documentaion for setting up this project on Windows using WSL

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#136]
Refer: https://richonrails.com/articles/rails-on-windows-10-via-wsl

**Comment by souravpd** [comment]
Currently Working on it

**Comment by vik-y** [comment]
This project currently supports docker. 

We would strongly encourage using docker on windows and Linux both.

**Comment by vik-y** [comment]
@satu0king Do you have any inputs on this?

**Comment by satu0king** [comment]
I agree with @vik-y that the use of docker is encouraged. @tachyons, is there any reason to not use the docker for the development environment.

**Comment by tachyons** [comment]
I am not against docker, intact it provides a consistant environment. This is just a low priority task for those who want native environment in windows. Feel free to close this issue if you think this isn't worth

**Comment by vik-y** [comment]
Even after following the write up you sent - it will take a while to set things up on Windows. 

It'll be much easier to avoid all the struggle and just do `docker compose build && docker compose up` 

Though I am not against it but I'd prefer people avoiding the pain of setting things up natively in Windows. And then again we won't have the consistent environment thing, if people develop it using docker then we can be sure that it will work in our environment as well.

**Comment by souravpd** [comment]
Totally agree with your point

I was facing issues setting this project up on my local machine and as I
was new to docker I preferred to do it the native way
So I thought this would be of some help..

**Comment by vik-y** [comment]
@souravpd I completely understand. But as I said using a consistent dockerized environment makes deployment easier. 

Let's not argue over this anyway, we can just merge it and move on.

**Comment by souravpd** [comment]
Ya sure
Thank you for your time
