### ISSUE TITLE
Bug in circuits page of other user

### ISSUE THREAD

**Issue by harshgujrati** [CircuitVerse/CircuitVerse#1364]
**Describe the bug**
When you visit my circuit page of other user and if that user don't have any project then it shows "You don't have any projects. Create one here". First issue is that instead of you the name of user must be displayed and second issue is, as create one here directs to simulator it is of no use here it must be only visible to the user if he is visiting his own my circuit page not to others.

**To Reproduce**
1. Go to 'My circuits page of other user' 
2. Click on 'Create one here'
3. See error

**Screenshots**
![Screenshot (255)](https://user-images.githubusercontent.com/51922630/78539049-93ef5680-780f-11ea-884a-565f70a78a91.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Nitish145** [comment]
Can i work on this issue ?

**Comment by harshgujrati** [comment]
Yes @Nitish145
