### ISSUE TITLE
Unused Project Setup in Github

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/CircuitVerse#1369]
**Describe the bug**
**not exactly a bug**
The project made under github projects is not being used and is there since 2019, so could we remove it all together ?

**To Reproduce**
1. Go to https://github.com/CircuitVerse/CircuitVerse/projects

**Expected behavior**
A blank project which is not being used should not exist.

**Screenshots**
Not Applicable.

**Are you working on this issue? (Yes/No)**
Can't. Admins Please.

**Comment by YashKumarVerma** [comment]
@ankitkataria 
sir kindly take this into consideration.

**Comment by aayush-05** [comment]
Can be closed @YashKumarVerma @nitin10s
