### ISSUE TITLE
Implementing tests for controllers and mailers using rspec

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#137]
Tests will have to written using RSpec for controller and mailers. They will prove to be necessary while setting up a CI/CD pipeline. 
Refer - https://github.com/rspec/rspec-rails

**Comment by vik-y** [comment]
This is something we have been looking for a long time. 

We prefer using factorybot and rspec for it. 


I am managing this, in case if you want are interested in working on it, let me know.

**Comment by ankitkataria** [comment]
Yeah! I'd like to work on it. I've worked with factory_bot and rspec before. :slightly_smiling_face:

**Comment by sushantahujaa** [comment]
I've worked with rspec and factory bot before. It would be great if we can work on it and also we can add simplecov to it, to get the maximum coverage

**Comment by ankitkataria** [comment]
Hey @sushantahujaa!
I've started working on adding the basics of the test-suite in PR #148. I've added coveralls for code-coverage in the same PR. It is approved and should be merged soon. We'll start working on it and divide work once that is done. :smile:

**Comment by sushantahujaa** [comment]
Yeah cool @ankitkataria let me know

**Comment by ankitkataria** [comment]
I'll be working on this issue from now on. I'll be updating the PR with the tests.
