### ISSUE TITLE
Issue Reporting sidebar covers the scroll bar of Timing diagram

### ISSUE THREAD

**Issue by ryuk156** [CircuitVerse/CircuitVerse#1372]
**Describe the bug**
Their is Issue Reporting sidebar the right corner in the simulator when we place Timing diagram in the simulator the issue Reporting sidebar cover the scroll bar  of Timing daigram 

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'simulator'
3. Add  'Timing Diagram'

**Screenshots**
![image](https://user-images.githubusercontent.com/49101492/78639084-f9544d80-78ca-11ea-903b-bd9a239c9d94.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by abstrekt** [comment]
The report button would be moved to a new place, so this can be closed?
@nitin10s @satu0king

**Comment by nitin10s** [comment]
Which place would it be moved to?

**Comment by abstrekt** [comment]
> 
> 
> Which place would it be moved to?

Should we have it right where it is, or inside a dropdown?

**Comment by ryuk156** [comment]
If  we want to place in dropdown then why I made the sliding  mechanism  this mechanism  looks attractive  as nitin  said    before creating  it,  ask all community  to where to place it  😅 that's  the last option  I can say

**Comment by nitin10s** [comment]
I was wanting it to be placed right where it is with some z-index properties so it hides behind the timing diagram.

**Comment by nitin10s** [comment]
This is made to stand out basically so as to make it more discoverable

**Comment by abstrekt** [comment]
Okay :)

**Comment by satu0king** [comment]
Fixed in new UI
