### ISSUE TITLE
Inputs can be assigned bit-widths more than 32 manually

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/CircuitVerse#1375]
**Describe the bug**
If we use the tiny arrows to increase the bit-width of an input element, it stops at 32 as the upper limit.
![image](https://user-images.githubusercontent.com/14032427/78646816-43433080-78d7-11ea-8e91-7298cac0348f.png)
But when you manually type any arbitrary number greater than 32, it accepts and increases the length of the input element.
![image](https://user-images.githubusercontent.com/14032427/78646904-64a41c80-78d7-11ea-9b4c-7da5d656b661.png)
Also, clicking on the bits of an oversize input changes the bits at starting and not the ones which are clicked. **not exactly a bug, but outcome of a bug**

**To Reproduce**
1. Open Simulator
2. Create an input element
3. Scroll down to properties
4. Increase Bit-width using arrow button
5. Observe as it stops at 32
6. Manually type any number greater than 32
7. Observe as input becomes bigger
8. Try switching on bits towards left. The bits towards right would change.

**Expected behavior**
The input should not accept any integer greater than 32.

**Screenshots**
[Attached]

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser 80.0.3987.162 (Official Build) (64-bit)
 - Version 80

**Additional context**
None

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shivansh2407** [comment]
Similar to #910.

**Comment by YashKumarVerma** [comment]
Closing in favour of #910
