### ISSUE TITLE
IRC channel

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#138]
is there any irc channel or slack or discord sever if not, are there any plans on creating one?

**Comment by ankitkataria** [comment]
No @shubhankarsharma00, there isn't any slack or IRC channel as of yet.

**Comment by vik-y** [comment]
We are planning to create a slack channel soon. I don't think we'll have an IRC channel though.

**Comment by satu0king** [comment]
https://gitter.im/CircuitVerse/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link
Join on gitter.
