### ISSUE TITLE
Acknowledge not logged in user trying to star a Project/Circuit

### ISSUE THREAD

**Issue by Nitish145** [CircuitVerse/CircuitVerse#1380]
**Describe the bug**
If the user is `not logged` in currently the user's tap on star project button is not acknowledged.

**To Reproduce**
1. Go to circuitverse.org
2. Scroll down to examples
3. Click on `Explore More`.
4. Click on any project.
5. Try to 🌟 the project
6. See error

**Expected behavior**
User must be redirected to login page or can be shown a flash message that shows Unauthorized status.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by aayush-05** [comment]
@Nitish145 working on this ?

**Comment by Nitish145** [comment]
Will work but depends on the login popup modal hence waiting for the same as we'll be required to redirect to login modal.. @aayush-05

**Comment by aayush-05** [comment]
@Nitish145 I guess this can be closed. Star icon isn't visible for non-logged users with the new UI

**Comment by Nitish145** [comment]
Yeah, Closing this issue..
