### ISSUE TITLE
Help for components

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1390]
**Is your feature request related to a problem? Please describe.**
I want to make f1 key open the documentation of the selected components
for example:
- if the user selected a 7-segment displayer component and clicked on the f1 key, we will open [seven-segment-display](https://docs.circuitverse.org/#/outputs?id=seven-segment-display) section at the **documentation** on a **separate tab**, to give him many details about that component.

**Are you working on this? (Yes/No)**
YES

**Comment by mahmodHammad** [comment]
@nitin10s  @aayush-05  @satu0king  @tachyons 
could someone approve this feature,
i will start working on it after 9 hours form now of anyone approved it

**Comment by yash15601** [comment]
Great  idea it sounds good😃

**Comment by nitin10s** [comment]
Sounds like a good idea.
