### ISSUE TITLE
Timing diagram

### ISSUE THREAD

**Issue by mahmodHammad** [CircuitVerse/CircuitVerse#1394]
**Describe the bug**
after putting a flag and remove it later we will get a plank white bar at the bottom which reduces the simulator height

**Expected behavior**
this div should be hidden if there are no flags 
![image](https://user-images.githubusercontent.com/41790090/79052657-5ab44d80-7c38-11ea-9d70-9cba534f29ed.png)

**Screenshots**
![timing](https://user-images.githubusercontent.com/41790090/79052578-d4980700-7c37-11ea-898f-c8b5c433f08b.gif)

**Are you working on this issue? (Yes/No)**
NO
I will work on it. if no one claimed this issue for the next 3 day

**Comment by Ananthavijay** [comment]
I guess this will be done during GSOC.

**Comment by yash15601** [comment]
It is part of project 1  fixing ui of timing  diagram  and other issues will be solved I think so

**Comment by yash15601** [comment]
let me work on this

**Comment by yash15601** [comment]
@mahmodHammad  i am working on this

**Comment by abstrekt** [comment]
@ryuk156 do you have the PR ready?

**Comment by ryuk156** [comment]
No my system  is not working fine if you have then you can make pr@abstrekt
