### ISSUE TITLE
Fix github labels

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#1397]
I was speaking with some of the contributors during GCI about our issue labels but there wasn't any elaboration so here, is it!

## Naming Scheme

Some of the labels use `naming-scheme-with-dashes`, some of them are `with spaces` some of them are `Uppercased` some of them are `lowercased` there aren't any standard.

**FIX**
use lowercased labels with spaces `like that`

## Colours
![image](https://user-images.githubusercontent.com/23432278/79079057-ee574e00-7d0c-11ea-9e06-e6f5ca62c209.png)
very intense and dark
![image](https://user-images.githubusercontent.com/23432278/79079081-23fc3700-7d0d-11ea-8227-4994bdd0e76f.png)
pastel

**FIX**
Use one of the colour plates, flat Dutch palette is cool https://flatuicolors.com/palette/nl

## Not using them at all
we are basically not using labels cause that mess

![image](https://user-images.githubusercontent.com/23432278/79079182-d8965880-7d0d-11ea-8a87-e7341c37582b.png)

**How labels should be set?** There is a couple of things to discuss, there is one setup:
https://github.com/azu/github-label-setup
Also, that would be cool to add more templates that assign labels that themselves
![IMAGE](https://user-images.githubusercontent.com/23432278/79079272-6a05ca80-7d0e-11ea-948e-acd28ae5fc01.png)

**Are you working on this issue? (Yes/No)**
Only people with write access can add labels so that is issue prepared for them!

**Comment by ShubhankarKG** [comment]
This is resolved here it seems. New labels have been added. I think this can be closed @tachyons .

**Comment by MrBartusek** [comment]
> This is resolved here it seems. New labels have been added. I think this can be closed @tachyons .

still, a lot of mess only done point from this issue is currently
> Also, that would be cool to add more templates that assign labels that themselves
