### ISSUE TITLE
Multiplexers and Demultiplexers not working properly

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1402]
**Describe the bug**
Multiplexers and Demultiplexers have a property of `Control Signal Size` which on increasing does not works properly. 

**To Reproduce**
1. Go to 'circuitverse.org/simulator'
2. Click on 'Decoders and Plexers'
3. Select Multiplexer or Demultiplexer => Increase Control Signal Size

**Expected behavior**
I suggest that we should limit the Control Signal Size to 10 or 12 because over 12 the simulator tends to lag. Also when the Control Size is 10 then too the minimap looks weird like this :
![10CSMinimap](https://user-images.githubusercontent.com/42182955/79537434-daf70a80-809f-11ea-9bf9-671960433f89.PNG)

**Screenshots**
Control Signal Size 32:
![32ControlSize](https://user-images.githubusercontent.com/42182955/79537094-2fe65100-809f-11ea-9d52-50bd8ffaace5.PNG)

Control Signal Size 31:
![31ControlSize](https://user-images.githubusercontent.com/42182955/79537123-42f92100-809f-11ea-8be5-ff83a7ce9365.PNG)

Control Signal Size 10 but the numbers are overlapping:
![Overlapping](https://user-images.githubusercontent.com/42182955/79537157-4f7d7980-809f-11ea-82fb-846078a694b4.PNG)

Control Signal Size 15 => Unresponsive Page:
![Unresponsive](https://user-images.githubusercontent.com/42182955/79537168-55735a80-809f-11ea-9906-73771053a4f7.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes I Can work on this issue.

**Comment by Shivansh2407** [comment]
Please let me know your views on this issue @satu0king @tachyons @nitin10s so that I can start working on it 👍 .

**Comment by nitin10s** [comment]
@satu0king

**Comment by satu0king** [comment]
@Shivansh2407 go ahead! Sorry for the super late response

**Comment by Prerna-0202** [comment]
I would like to work on this issue..
