### ISSUE TITLE
Broken Navbar for middle-sized screens

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1406]
**Describe the bug**
The navbar broke at middle screens and the drop down isn't reachable then.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Resize the window width to ~1000px
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/79591766-9fd3f600-80f6-11ea-964f-c6c29ddd5385.png)

**Are you working on this issue? (Yes/No)**
Not right now, more to be discussed. It can be done in two ways :
- Either truncate the user name to a specified length
- Decrease the padding and margin between the navbar tabs

**Comment by yash15601** [comment]
@aayush-05  I tryed  using truncate in username  but that dropdown toggle is creating  problem

**Comment by aayush-05** [comment]
Oh, okay. I will try once and get back to you on this

**Comment by harshgujrati** [comment]
We also need to add a search bar for which i think that we have to redesign navbar @nitin10s @aayush-05

**Comment by yash15601** [comment]
@aayush-05 did you find any solution for truncating the user name i was working on it but still the dropdown toggle is creating  problem

**Comment by aayush-05** [comment]
![image](https://user-images.githubusercontent.com/47032027/79788588-833df500-8366-11ea-9636-96829774263b.png)
It worked, however it just shifted the dropdown toggle a little below; but I don't think that is an issue. Whatsay @nitin10s

**Comment by yash15601** [comment]
@aayush-05  that's  the main thing its should not be shifted  if create div and then  after we add toggle it is still shifting  @nitin10s  can you suggest something

**Comment by aayush-05** [comment]
![image](https://user-images.githubusercontent.com/47032027/79826937-a5f9f900-83ba-11ea-957b-1e163ef5b056.png)
@yash15601 overriding the bootstrap toggle class will do. I guess this one looks fine now ?

**Comment by yash15601** [comment]
Yes LGTM
