### ISSUE TITLE
Redis::TimeoutError

### ISSUE THREAD

**Issue by abstrekt** [CircuitVerse/CircuitVerse#1407]
Bug while running development environment from latest master branch, 
Probably caused by PR #1346  ,
![Firefox_Screenshot_2020-04-17T17-50-37 300Z](https://user-images.githubusercontent.com/42478217/79598731-0f9bae00-8102-11ea-8732-7f93c18440d9.png)

@ciphereck can you please verify

**Comment by yash15601** [comment]
Yes this the big problem  I think I'm still not able to run my repo @tachyons  can you take a look please

**Comment by abstrekt** [comment]
Til it gets fixed, can that PR be unmerged? @tachyons

**Comment by Shivansh2407** [comment]
This issue is there in Gitpod too. We need to update the gitpod files also.

**Comment by Ananthavijay** [comment]
@abstrekt @Shivansh2407 Try starting the Redis server manually in a new terminal by running `redis-server`.

**Comment by Shivansh2407** [comment]
@Ananthavijay it is working on localhost for me. Gitpod needs an update or some changes.

**Comment by Ananthavijay** [comment]
In gitpod try `bundle exec redis-server`

**Comment by yash15601** [comment]
In normal  when I execute  the redis-server in new terminal another issue is created something  kill

**Comment by ciphereck** [comment]
Maybe try running redis-server on your system.
If you are using gitpod, you need to run redis-server on it too.
Please let me know if the problem persists.
It's working fine on my system based on latest master commits @abstrekt

**Comment by yash15601** [comment]
We tryed  it's not working

**Comment by abstrekt** [comment]
> 
> 
> Maybe try running redis-server on your system.
> If you are using gitpod, you need to run redis-server on it too.
> Please let me know if the problem persists.
> It's working fine on my system based on latest master commits @abstrekt

![image](https://user-images.githubusercontent.com/42478217/79693952-32a59980-828b-11ea-9552-45f0b3fe14b1.png)

**Comment by abstrekt** [comment]
> 
> 
> Maybe try running redis-server on your system.
> If you are using gitpod, you need to run redis-server on it too.
> Please let me know if the problem persists.
> It's working fine on my system based on latest master commits @abstrekt

![image](https://user-images.githubusercontent.com/42478217/79693969-40f3b580-828b-11ea-8c15-168f8184e8ba.png)

**Comment by ciphereck** [comment]
@yash15601 let's wait for @tachyons to check the issue then.
@abstrekt Do you have Redis installed? Probably not. Maybe try checking this.
https://stackoverflow.com/questions/6476945/how-do-i-run-redis-on-windows/10525215

**Comment by yash15601** [comment]
Okay

**Comment by Shivansh2407** [comment]
It is working fine for me too on localhost based on the latest master branch👍. Please check out redis.io for help too.

**Comment by abstrekt** [comment]
@yash15601 install from https://github.com/microsoftarchive/redis/releases
