### ISSUE TITLE
Improper orientation of links on Homepage

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1408]
**Describe the bug**
'Learn Logic Design' button was moved to the next line to due to insufficient space for smaller mobile displays. But it stays there for devices (ex, Iphone X) where it can be easily displayed on the same line. Putting it on the next line makes the page looks a little dis-oriented.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/79602035-68217a00-8107-11ea-8d9c-b0762bf72f93.png)

**Are you working on this issue? (Yes/No)**
Not right now, requires validation from @nitin10s

**Comment by nitin10s** [comment]
Sure, this can be done
