### ISSUE TITLE
SHOWING-"This page isn’t working"

### ISSUE THREAD

**Issue by akoopraba4** [CircuitVerse/CircuitVerse#141]
I am not sure if this is correct or not.If we press the back button in new groups without entering the group name it shows 
This page isn’t working 
If the problem continues, contact the site owner.
HTTP ERROR 406
https://circuitverse.org/groups/new
Please check this out

**Comment by satu0king** [comment]
Yes it is a bug.

**Comment by akoopraba4** [comment]
I would like to work on this issue.However @satu0king  can you provide some information on how to go about it?
