### ISSUE TITLE
Error Connecting to Redis On Gitpod

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1410]
**Describe the bug**
Whenever we try to open Gitpod (for PRs made after merging #1346) it displays error as in the screenshot below by default.
![RedisNotWorking2](https://user-images.githubusercontent.com/42182955/79820216-5c54e280-83a9-11ea-85e0-fdbdc6a798b3.PNG)

On Executing `bundle exec redis-server` it displays : 
![3000NotServed](https://user-images.githubusercontent.com/42182955/79820530-18161200-83aa-11ea-840a-c2ae8429979e.PNG)

**To Reproduce**
1. Go to gitpod.com for any PR
2. See Error

**Expected behavior**
The gitpod files need to be updated .

**Screenshots**
Before Merging of the above mentioned PR : 
![RedisWorking](https://user-images.githubusercontent.com/42182955/79820342-a3db6e80-83a9-11ea-959b-96aac9c520d8.PNG)

After Merging of the above mentioned PR : 
![RedisNotWorking](https://user-images.githubusercontent.com/42182955/79820348-a6d65f00-83a9-11ea-9274-39f150ae6dc8.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

**Comment by ciphereck** [comment]
@Shivansh2407 the 6379 port is for Redis.
I see it open before the PR, but not served after PR?

**Comment by ciphereck** [comment]
@Shivansh2407 I checked the latest repo from the master in Gitpod. It's working for me just fine.
Maybe you can just try either forking the repo again or restarting the workplace of Gitpod from scratch. I checked it by navigating to multiple pages. Also, port 6379 was open. I checked it on Ubuntu and Chrome browser.

@tachyons @satu0king 
Maybe we can proceed towards closing this issue.

**Comment by Shivansh2407** [comment]
Yes @ciphereck it is now working on gitpod too. 👍
