### ISSUE TITLE
Timing and delays in simulation.

### ISSUE THREAD

**Issue by Mazurel** [CircuitVerse/CircuitVerse#1412]
### Overview of the problem
**Delay**
CircutVerse gives a user an ability to use a setting called **_delay_** which is definitely not working like delay should work (it doesn't affect the time).  Although the delay in some cases may seem like a "slowing factor" of an element, in reality it is not. Currently, the delay is used in a queue as a priority of an element, which is good for a lot of cases (not all of them) but is not really accurate. 
**Tick counter/Timer**
I feel like current implementation is missing a timer or a tick counter that would synchronize everything that is being simulated. There are currently elements such as clock, flag, and simulation steps that are strictly time-related. What may be surprising is that they are (from what I understood from the source code) completely unsynchronized with each other, ie they all use different timing methods. Of course, they shouldn't all fire at the same time, but they should all be part of one mechanism.
### My solution
What I propose is to create a system that would,  create ticks one after another with timeouts between each, which would affect all the time-related elements on the page. Such solution would create a possibility for future more advanced simulation manipulations (such as speed manipulation or stoping). Sadly I don't think Javascripts custom event system can be used here, as there is no way to check if all event handlers have done their job. That is why I think that implementation would need an object with an array that would contain promises. The controlling class would call all the functions, wait for them, wait after that and make a loop. Such solution wouldn't really affect whole code, other than changing current queue and current time-related elements as well as delay values, as they should in my opinion contain information after how many ticks they would propagate (maybe even time in ms or ns).
### Conclusion
I have not started doing such change as I am not sure if it will be approved, but I am pretty sure it would be possible to make it. Also I think that time based simulation may eliminate simulation limit problems when the circuts are invalid.

**Comment by satu0king** [comment]
@Mazurel , sorry for lack of activity, We have incorporated some of your suggestions in #1929
