### ISSUE TITLE
Organizing the profile section

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1419]
**Is your feature request related to a problem? Please describe.**
Currently, the user section on the website is very unfavourable while it comes to navigation.
For instance, you cannot visit the Profile section from My Circuits section.
You can navigate to favourites section from My Circuits section but no the other way around [You cannot navigate anywhere the Favourites Section]

**Describe the solution you'd like**
We can supposedly have something like [dribble](https://dribbble.com/nitin10s)
![image](https://user-images.githubusercontent.com/16988558/81391425-af18f300-913a-11ea-9489-a1a384fbea0e.png)

So that all the Profile, My Circuit and Favourite Circuits sections are accessible at one place.

**Comment by aayush-05** [comment]
Fixed by #1629
