### ISSUE TITLE
Migrate tooltips

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#142]
Currently, tooltips information are stored at UX.js, migrate the same to individual circuit elements. Check out how Power and Ground implement Tooltips.

**Comment by rkpattnaik780** [comment]
I would like to work on this issue.

**Comment by armudgal** [comment]
Hi @rkpattnaik780, can you please if you are working on this issue

**Comment by sarthak77** [comment]
Hi I would like to take up this issue if not taken

**Comment by sanctophagus** [comment]
Hey @satu0king !
If no one is working on this issue, than I am willing to work on it!

**Comment by armudgal** [comment]
@sarthak77 Would you be taking up this issue?

**Comment by sarthak77** [comment]
ok i'll be working on it

**Comment by armudgal** [comment]
Hi @satu0king, the issues are based on first come first serve, so sorry for that, please look through other issues. Cheers

**Comment by agarwalrounak** [comment]
@armudgal I think you tagged the wrong person :sweat_smile:

**Comment by sarthak77** [comment]
Yeah I'm working on it

**Comment by sarthak77** [comment]
> Currently, tooltips information are stored at UX.js, migrate the same to individual circuit elements. Check out how Power and Ground implement Tooltips.

Hey I could not relate to what do you mean by Power and Ground
Can you elaborate?

**Comment by satu0king** [comment]
> > Currently, tooltips information are stored at UX.js, migrate the same to individual circuit elements. Check out how Power and Ground implement Tooltips.
> 
> Hey I could not relate to what do you mean by Power and Ground
> Can you elaborate?

Look for this line in modules.js: 
`Power.prototype.tooltipText = "Power: All bits are High(1).";`

This is how we want all modules to implement tooltips now.

**Comment by satu0king** [comment]
@sarthak77 since we haven't heard from you, I am releasing this issue. Please feel free to claim the issue again if you are still working on this.

**Comment by sarthak77** [comment]
I was having trouble in setting up the system and had exams in between so was out for a while

**Comment by mohamedar97** [comment]
i want to give this issue a try, can i take it?

**Comment by prajapatgautam1999** [comment]
@satu0king @armudgal Is anyone working on this issue as it is not marked "taken" but there are few who seem to be working for the same.

**Comment by satu0king** [comment]
This is a very easy issue, therefore the first PR will be merged.

**Comment by armudgal** [comment]
@prajapatgautam1999 You can go ahead since we didn't receive any PR till now

**Comment by mohamedar97** [comment]
migration done under pull request #283

**Comment by prajapatgautam1999** [comment]
@armudgal Alright then I am now working on this issue.

**Comment by prajapatgautam1999** [comment]
@mohamedar97

**Comment by mohamedar97** [comment]
@prajapatgautam1999 no need to do so i already fixed the issue

**Comment by mohamedar97** [comment]
Pr #286

**Comment by prajapatgautam1999** [comment]
@satu0king @armudgal @mohamedar97 So as far till now no, PR are made to fix the issue successfully.
I am working on this issue for now, and will update accordingly.
