### ISSUE TITLE
Links in Contribute section should open in next tab

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1420]
**Describe the bug**
The Email, Slack and Github Links in the [Contribute section](https://circuitverse.org/contribute) should open in next tab.

**Comment by Shivansh2407** [comment]
Can I work on it?

**Comment by bankebihariagrawal** [comment]
can I work on this?

**Comment by nitin10s** [comment]
@aayush-05

**Comment by aayush-05** [comment]
Issue already fixed in updated master. This can be closed @nitin10s
