### ISSUE TITLE
Examples section issues - no styling (& search doesn't work)

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/CircuitVerse#1444]
**Describe the bug**
The examples section on the website is not styled properly - the fonts do not fit the theme.

Also, the search needs to be fixed. The magnifying glass icon is not linked itself so you must click the white background to the white of it, which brings up an empty dropdown. The enter key can be used which brings the user to a completely new page. (I think this is already been worked on though)

**Screenshots**
<img width="1114" alt="2020-05-21_14-06 _129" src="https://user-images.githubusercontent.com/34946235/82562055-631f7280-9b6c-11ea-86dd-be6e354f9448.png">

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed >> Examples page has been revamped
