### ISSUE TITLE
GitHub authentication button on sign-up reads "Authorise satu0king" instead of "Authorise CircuitVerse"

### ISSUE THREAD

**Issue by schezfaz** [CircuitVerse/CircuitVerse#1445]
**Description:** 
When logging in to CircuitVerse via GitHub, the authentication message reads "Authorise satu0king". It should ideally read "Authorise CircuitVerse".

**Steps to Reproduce the behaviour:**
1. Go to https://circuitverse.org/ 
2. Click on "Sign In" in the top right corner
3. Click on the GitHub icon next to "Log in with"
4. You will get redirected to the authorisation page that will read "Authorise satu0king"

**Expected behavior**
The authorisation button should read "Authorise CircuitVerse"

**Screenshots**
![image](https://user-images.githubusercontent.com/28871211/82590369-3777a900-9bbb-11ea-9cb0-b604f69be4de.png)

**Device Information:**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Version: 81.0.4044.138 (Official Build) (64-bit)

Not working on this issue currently.

**Comment by imrishabh18** [comment]
@schezfaz Hey, I will like to take up this issue.

**Comment by pavanjoshi914** [comment]
@schezfaz 
I checked other standard websites who integrates github api for user authentication.It is github default api setting that ,account which register an application on GitHub will get authorize so probably there is no way to change unless account holder changes its username as circuitverse .So issue must be closed

**Comment by schezfaz** [comment]
Oh right yes, I did not account for the fact that it could be a default api setting. Good catch! @pavanjoshi914
