### ISSUE TITLE
Refactoring simulator codebase

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#1446]
**Is your feature request related to a problem? Please describe.**
As a part of GSoC project, I will be working on refactoring the simulator codebase. Updating it to ES6 and making some changes in the implementation of how a couple of things work.

**Are you working on this? (Yes/No)**
Yes

**Comment by satu0king** [comment]
@shubhankarsharma00  closing this issue xD
