### ISSUE TITLE
No feedback for Start Plot

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#1449]
**Describe the bug**
In the Simulator, the Start Plot ( Tools > Start Plot ) works only when we have a flag in the circuit. Otherwise, it gives no feedback which is confusing for the user

**Expected behaviour**
When there isn't any flag on the canvas and the user clicks on Start Plot. An alert stating "You need to add a flag to use the Start Plot option"

**Comment by Roshan13046** [comment]
Anyone working on the issue.
I am interested to work on it.
Please suggest ways to gets started.

**Comment by satu0king** [comment]
Fixed in new UI
