### ISSUE TITLE
add CODE OF CONDUCT

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerse#145]
add Code of Conduct section in the README.md for visitors and contributors for GSSoC.

**Comment by Parikshit-Hooda** [comment]
I am attaching some links below that could be consulted for the above mentioned task.
GitHub Help on Code of Conduct - [https://help.github.com/en/articles/adding-a-code-of-conduct-to-your-project](url)
Docker Code of Conduct - [https://github.com/docker/code-of-conduct/blob/master/code-of-conduct-EN.md](url)

**Comment by sanctophagus** [comment]
Hey @Parikshit-Hooda !
I would like to work on this issue, if anyone else is not working on it presently.

**Comment by Parikshit-Hooda** [comment]
Sure @sanctophagus . Go ahead.. get in touch if any help is needed.

**Comment by Parikshit-Hooda** [comment]
Revision : Please make a new file with an appropriate name for Code of Conduct(.md) and provide a link to it in README.md
