### ISSUE TITLE
add Contribution Guidelines - CONTRIBUTING.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerse#146]
add Contribution Guidelines section in README.md for GSSoC participants and other contributors.

**Comment by ankitkataria** [comment]
Setup instructions are already present in the README. Probably, a template for opening issues and making a pull request can be added. Also, commit guidelines can be added. 

Reference: 
- https://help.github.com/en/articles/about-issue-and-pull-request-templates
- https://github.com/devspace/awesome-github-templates

**Comment by la2798** [comment]
Hi I would like to contribute to this issue

**Comment by armudgal** [comment]
Hi @la2798, there seems to be an overlap here with #161, please look through other issues until we sort this out. Thanks :)

**Comment by la2798** [comment]
I was about to make a PR 😅 , I ll look through other issues then

**Comment by Parikshit-Hooda** [comment]
Hi @la2798 . 
Revision : Put contribution guidelines in the CONTRIBUTING.md and put a link to it in README.md.

**Comment by Parikshit-Hooda** [comment]
Also, please note that 
**before submitting any PR, please talk about the bug fix/feature/enhancement by opening an issue. PR's without referencing any issue becomes hard to keep a track of.** 

@armudgal , I have quoted you here.

**Comment by la2798** [comment]
So i need to raise an issue here and then do a PR ??

**Comment by armudgal** [comment]
Hi @la2798, the previous message was to mention some points that needs to be added in the `CONTRIBUTING` file. This issue is already being worked upon by @Ankitanvesh.
