### ISSUE TITLE
The close tab fa-icon always deletes the current circuit.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#1464]
**Describe the bug**
When you are in main and make a new circuit and want to close main when you are currently working in main2. It will actually delete main2. 
**To Reproduce**
1. Go to '/simulator'
2. Click on 'Circuit -> New Circuit'
3. with new circuit in focus try to close Main.
4. See the prompt as it asks to delete the current circuit.

**Expected behavior**

**Screenshots**

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes, Will fix with refactoring PR

**Comment by satu0king** [comment]
@shubhankarsharma00 can this be closed?

**Comment by shubhankarsharma00** [comment]
Yes, This is fixed
