### ISSUE TITLE
Implement Authorization layer

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#150]
In the current code authorization is handled in the controller layer. It is always better to extract it into separate layer.

Use https://github.com/varvet/pundit (Preferred), Or https://github.com/CanCanCommunity/cancancan

**Comment by ankitkataria** [comment]
Can I start looking into this?

**Comment by tachyons** [comment]
Sure, go ahead

**Comment by Sadat97** [comment]
Is anyone one working on this issue?

**Comment by ankitkataria** [comment]
Hey @Sadat97, I've opened a PR for it.

**Comment by Parikshit-Hooda** [comment]
@ankitkataria  if this has been done, please refer the PR here. Then, this issue can be closed after the merge.

**Comment by ankitkataria** [comment]
@Parikshit-Hooda PR #184  is yet to be merged. I've referenced the issue in the PR already. I'll ensure that the issue gets closed once it is merged! :sweat_smile:
