### ISSUE TITLE
Delay Property Not working as expected. 

### ISSUE THREAD

**Issue by YashKumarVerma** [CircuitVerse/CircuitVerse#1502]
Problem:
The delay is not documented, and I've tried using it with
- Input element
- Clock
- Gate

and none of the data streams are being delayed. Can someone help.

Context:
I actually need some help here. It seems the delay property isn't working across any input element. It would be pretty difficult to document it if it's not working @YashKumarVerma @Shivansh2407 @mahmodHammad

_Originally posted by @CapTen101 in https://github.com/CircuitVerse/CircuitVerseDocs/issues/218#issuecomment-645419076_

**Comment by mahmodHammad** [comment]
This issue is complicated, i think it's hard to do that on the current code base so I 'd recommend to disable this feature until the refactoring is done.

**Comment by satu0king** [comment]
Yes this feature needs to be docoumented,  will be doing this
