### ISSUE TITLE
The links to the slack, email Us, github should open in another tab. Rather, it opens up in the same tab. This needs a fix.

### ISSUE THREAD

**Issue by lopeselio** [CircuitVerse/CircuitVerse#1515]
**Describe the bug**
In the contribute section, when I try to open the three links mentioning email Us, slack and github, they open up in the same tab. It would have been better if this issue is fixed.

**To Reproduce**
1. Go to 'https://circuitverse.org/contribute'
2. Click on any of the three links to contribute.
3. They Open up in the same tab

**Expected behavior**
It would provide a much better user experience if the links open up in a new window.

**Screenshots**

**Device Information [optional]:**
 - OS: Windows 10
 - Browser Chrome
 - Version 83.0.4103.116

**Additional context**

**Are you working on this issue? (Yes/No)**
Currently not
![issue1](https://user-images.githubusercontent.com/43913734/86008807-ecad4480-ba36-11ea-9582-b621357087ae.PNG)
![issue2](https://user-images.githubusercontent.com/43913734/86008815-f2a32580-ba36-11ea-9b86-719f738569f2.PNG)

**Comment by himanshujaidka** [comment]
Is anybody working on this? @lopeselio

**Comment by lopeselio** [comment]
> Is anybody working on this? @lopeselio

I can try!

**Comment by animesh-007** [comment]
If it's okay Can I work on this? And the same issue is with About page I guess it will be good to implement the same over there too.

**Comment by animesh-007** [comment]
#1443 This PR solves this issue.

**Comment by animesh-007** [comment]
@YashKumarVerma Can you close this issue as it is already resolved?

**Comment by aayush-05** [comment]
@nitin10s please close this one
