### ISSUE TITLE
Copy-pasting circuits doesn't preserve layout

### ISSUE THREAD

**Issue by medakk** [CircuitVerse/CircuitVerse#1516]
**Is your feature request related to a problem? Please describe.**
I sometimes copy paste an existing circuit to build off of(when it doesn't make sense to just build off that as a black box). When I do this, the circuit components are correctly populated, but the layout is messed up

**Describe the solution you'd like**
The layout gets copied when I copy "entire" circuits

**Describe alternatives you've considered**
Nothing, I just manually fix the layout.

**Comment by satu0king** [comment]
@medakk I was not able to reproduce this. Can you show exact steps with images preferably?

**Comment by medakk** [comment]
I'm not able to reproduce it anymore, not sure what I was doing different back then. Feel free to close!
