### ISSUE TITLE
Typo/Grammatical error in contributing.md

### ISSUE THREAD

**Issue by Himanshunitrr** [CircuitVerse/CircuitVerse#1521]
**Describe the bug**
In contributing.md there is some typo or grammatical error.
To be precise :
Under the heading of how to contribute, there is a sentence "When you are ready to start work on a issue" 
I think it must be "When you are ready to start to work on an issue" or "When you are ready to start, work on an issue" 
**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by Himanshunitrr** [comment]
Should I fork, fix the problem and create a PR.

**Comment by Ankit27Agg** [comment]
i want to work on this issue.
