### ISSUE TITLE
Delete sometimes initiated when I click on a tab to the left of the X

### ISSUE THREAD

**Issue by ellenspertus** [CircuitVerse/CircuitVerse#1532]
**Describe the bug**
Sometimes when I click on a tab, I receive the message "The following circuits are depending on ...Delete subcircuits of ... before trying to delete ...". See [video](https://360.articulate.com/review/content/2c91b570-992b-4dc7-87a1-ee9dd7949034/review).

**Expected behavior**

I expected to switch to the tab I clicked on.

**Device Information [optional]:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 77.0.1

**Additional context**

While I don't think it's project-specific, the video is of [this project](https://circuitverse.org/users/28963/projects/117768).

**Are you working on this issue? (Yes/No)**

No

**Comment by nc79188** [comment]
the close button hover css property has been given a left padding of 1em in UI.css and that is the reason for this closing
as it is only given in the :hover property and not in the the class it is observed after hovering on it

this issue can be solved by changing the padding-left to margin-left

i will make those changes
