### ISSUE TITLE
circuit preview doesn't load when flags are used

### ISSUE THREAD

**Issue by I-mikan-I** [CircuitVerse/CircuitVerse#1586]
## Describe the bug
When using flags in a circuit, and saving said circuit online, the interactive preview will be stuck in a loading loop.

## To Reproduce
1. Create a Circuit with flags.
2. Save the project online.
3. Open the project page.
4. The preview window doesn't load the circuit.

## Expected behavior
The preview should load (ideally with flags)

## Screenshots/GIFs
see: https://circuitverse.org/users/31101/projects/bug_flag_preview-ccb5e4b9-da0f-47e9-aaa3-b42b4fbff173

## Device Information [optional]:
 - Browser:
   tested on both chrome and firefox

**Comment by satu0king** [comment]
Fixed in new UI
