### ISSUE TITLE
Add the gitter channel

### ISSUE THREAD

**Issue by creyente1897** [CircuitVerse/CircuitVerse#159]
Adding gitter channel link to the contribute page of circuit verse

**Comment by parammittal16** [comment]
Want to work on this issue. I am a GSSoC participant.

**Comment by parammittal16** [comment]
@creyente1897 plz review my PR.

**Comment by creyente1897** [comment]
@creyente1897 I am sorry that i did not added that i am working on it and created the pr 10 hours ago.
I will keep that in mind next time :smile: .

**Comment by armudgal** [comment]
Hi @parammittal16  @creyente1897, looks like there was a confusion. We would keep that in mind that it doesn't happen next time.
