### ISSUE TITLE
Signup form improvements 

### ISSUE THREAD

**Issue by pavanjoshi914** [CircuitVerse/CircuitVerse#1640]
**Is your feature request related to a problem? Please describe.**

Circuit verse signup forms has many validation problems 

problem1:no proper validation set up to username field

    as there is only one field in signup form it can used as username  as well as full name for user 
   so only possible validation can be applied is it cant be left blank  (Closes #1503 )
    (  no server side validation will be applicable as it will create conflicts with existing users)
                

problem2:  no proper validation set up in email field

                  *required type validation preexists on email field but it do not check the correctness
                    of the form of the email (except @ postion in email)

                  *you can put email without domain name of email  
 

**Describe the solution you'd like**
   I will apply each possible validations on email and username as follows:

    for username:
     * currently only validation applied is it cant be left blank
 
     for email:
     *we will check email in the form of

    1> local section of email
     2>@ symbol present
     3> domain name present (which takes only characters as a input)  (Closes #1633  )
   
    any of the part not present in email will consider email as invalid

**Are you working on this? (Yes/No)**
Yes.

**Comment by Tushardeepak** [comment]
I would like to work on it..

**Comment by Palaksharma23** [comment]
is anyone working on this issue , i would like to work on this issue .

**Comment by pavanjoshi914** [comment]
Already fixed and merged ! closing this
