### ISSUE TITLE
Fix Sidebar scroll for Assignment Submissions

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1656]
**Describe the bug**
The Sidebar's height for the Assignment submissions must not exceed a certain length, rather it should scroll to expose rest entries. 

**Expected behavior**
Add a limit to the height (preferrably default height on page load for each display size) and enable scroll.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/93382469-c8b40f00-f87f-11ea-8b82-072d5231a31e.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by manasivaraiya** [comment]
can i work on this? i haven't contributed to open source before!

**Comment by aayush-05** [comment]
Sure! Go ahead

**Comment by HADES-01** [comment]
Is anyone still working on this issue, if not then I would like to fix this bug. @aayush-05

**Comment by aayush-05** [comment]
Hey!
Closing this, because Satvik fixed it himself here >> #1691
