### ISSUE TITLE
Add a default font for the platform

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1657]
**Describe the bug**
Currently we are not defining a font to be used on the platform so the browser resorts to using the browser-default font. This creates inconsistency when using the platform on different browsers.

**Expected behavior**
Add a font to the platform (personally prefer "Inter", finalise with @nitin10s) using a OTF/TTF file via the Asset Pipeline

**Are you working on this issue? (Yes/No)**
No

**Comment by pavanjoshi914** [comment]
I would like to work on this

**Comment by aayush-05** [comment]
Great! Go ahead

**Comment by pavanjoshi914** [comment]
@nitin10s and @aayush-05 plz review the pull request if any further changes needed you're welcome
