### ISSUE TITLE
Add LinkedIn Icon in Footer

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#1659]
Add LinkedIn icon similar to Facebook and Twitter icon in the Footer.
![image](https://user-images.githubusercontent.com/47032027/93570283-660e6080-f9b0-11ea-8ef4-98a543ab9eb3.png)

**Are you working on this? (Yes/No)**
No

**Comment by animesh-007** [comment]
Can I work on this?

**Comment by aayush-05** [comment]
Sure, Go ahead!

**Comment by hdck007** [comment]
Can I work on this if @animesh-007 isn't doing it.

**Comment by hdck007** [comment]
Can I go for this if @animesh-007 isn't doing it?

**Comment by animesh-007** [comment]
@hdck007 Sure😀
