### ISSUE TITLE
drag out of bound 

### ISSUE THREAD

**Issue by abstrekt** [CircuitVerse/CircuitVerse#1661]
Dragging of elements should not go out of bound in PR #1585, may take panels to a point of no return.

![image](https://user-images.githubusercontent.com/42478217/93591112-60734380-f9cd-11ea-9666-b163f3259eaf.png)

*Creating this issue to keep track of the bug*

**Comment by satu0king** [comment]
Interesting, in the older UI it is not happening, maybe that will give a clue on how to fix this?

**Comment by satu0king** [comment]
https://forum.jquery.com/topic/prevent-draggable-to-go-outside-screen

I think this will solve the problem

**Comment by abstrekt** [comment]
> 
> 
> https://forum.jquery.com/topic/prevent-draggable-to-go-outside-screen
> 
> I think this will solve the problem

exactly what was needed!
