### ISSUE TITLE
Indicate that "circuit" and "info" in footer are not link

### ISSUE THREAD

**Issue by DarthCucumber** [CircuitVerse/CircuitVerse#1664]
**Describe the bug**
 "_**circuit**_" and "**_info_**" in footer are not link which is not indicated

**Expected behavior**
May be underlining the text _**circuit**_ and _**info**_
plus adding suitable color to the text so that visitors can differentiate.
Changing color would be ideal because links already get underlined on hovering cursor.

**Screenshots**
![bug](https://user-images.githubusercontent.com/64456160/93663382-354c2b00-fa85-11ea-8a3e-458e18819f8e.png)

**Are you working on this issue? (Yes/No)**
yes

**Comment by sanskar-p** [comment]
Hi @DarthCucumber. Can I work on this issue?
