### ISSUE TITLE
After search results of user the category of search should still remain 'Users' and not projects

### ISSUE THREAD

**Issue by pavanjoshi914** [CircuitVerse/CircuitVerse#1667]
**Describe the bug**
when a user is searched it shows result of  all registered users but category of search automatically changes to projects  

**To Reproduce**
1. Go to 'www.circuitverse.org'
2. Click on 'search tab and search for user'
3. after search of user the  category shows projects as category and not users

**Expected behavior**
  If a user is searched, after search results category of search should remain users only and not projects
 and if projects are searched then category of search should still remain projects

**Screenshots**

as shown in screenshot we have results of user search  but category of search gets changed to projects automatically 

![Screenshot from 2020-09-19 17-25-28](https://user-images.githubusercontent.com/55848322/93666984-232bb600-faa0-11ea-8751-7a9a874e5e24.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by DarthCucumber** [comment]
can I work on this?

**Comment by pavanjoshi914** [comment]
yes ... Go ahead
