### ISSUE TITLE
Boolean function -> Circuit Generation

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1706]
Currently, we have Combinational Analysis to generate circuits.
We also have ways to generate boolean logic table given a boolean function. See [here](https://learn.circuitverse.org/docs/bool2.html)

We should easily be able to integrate the 2. Given a boolean function like `X = AB' + C`, we should get a minimized circuit for the same. 

Please send PRs to `new_UI` branch. 

**Are you working on this? (Yes/No)**
No

**Comment by rohan2734** [comment]
@satu0king  hi i would like to work on this issue if no one has taken it.

**Comment by satu0king** [comment]
Go Ahead @rohan2734

**Comment by rohan2734** [comment]
- @satu0king does ```combinational analysis``` mean this one [here](https://learn.circuitverse.org/docs/combinational) ?
- > We should easily be able to integrate the 2. Given a boolean function like X = AB' + C, we should get a minimized circuit for the same.

can you give some hints , i dont know with what language or skills ,we can do them, thats why.

**Comment by satu0king** [comment]
Check tools-> combinational analysis. 
@rohan2734 I recommend going through the product for a while and try different things. This will give you a good picture on everything. Good luck!

**Comment by rohan2734** [comment]
- @satu0king  ya i have understood now, I even tried to give inputs A,B 
- and output as X=A.B, the boolean table is not working?, for ```AND``` gate.
![image](https://user-images.githubusercontent.com/58523134/94906324-e73f1a80-04bb-11eb-90f3-afe84a84ca99.png)

- the output is not correct right? according to and gate between A and B, the output should be
![image](https://user-images.githubusercontent.com/58523134/94906372-fcb44480-04bb-11eb-8b16-4f5cdf01f073.png)

-so first issue, here is the output is not generate right, 
-then we can look into the circuit, like if X=AB, then the circuit must be ```A and B``` right?

**Comment by satu0king** [comment]
@sal2701 can you help out here. Thanks!

**Comment by rohan2734** [comment]
- @sal2701  i think here the first task is to correct the logic in boolean table right?.
- please provide the filenames with complete path,
- i will work on first correcting the loigc in boolean talbe, then creating a circuit.

**Comment by rohan2734** [comment]
@satu0king  i think @sal2701 is not responding, can you assign it to others ?

**Comment by pavanjoshi914** [comment]
@satu0king I would like to work on this.....
