### ISSUE TITLE
Update Simulator Issue reporting

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1707]
**Describe the bug**
Report Issue window in `new_UI` branch is outdated from `master` branch

`new_UI` branch:
![image](https://user-images.githubusercontent.com/2092958/94338595-41019980-0011-11eb-9b17-d27105390b25.png)

`Master` branch:
![image](https://user-images.githubusercontent.com/2092958/94338592-39da8b80-0011-11eb-800d-6b22da3531b0.png)

Please send a PR fixing this issue. 
Code for the html can be found in `app/views/simulator/edit.html.erb`
Code for JS in `new_UI` branch can be found in `public/src`
code for JS in `master` branch can be found in `public/js`

**Are you working on this issue? (Yes/No)**
No

**Comment by arjungarg07** [comment]
Hey @satu0king , I am willing to work on this as my first issue. Can you assign this to me?

**Comment by satu0king** [comment]
Go ahead! @arjungarg07

**Comment by arjungarg07** [comment]
Hey @satu0king , I have opened a pull request for the same , kindly review https://github.com/CircuitVerse/CircuitVerse/pull/1717
