### ISSUE TITLE
Zoom in and Zoom out buttons

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1708]
The Zoom slider in the new UI at [beta.circuitverse.org](beta.circuitverse.org) works but the + and - symbols are not buttons. It would be nice if they act as buttons for zooming in and zooming out respectively. 

Branch: new_UI
JS: public/src
HTML: app/views/simulator/edit.html.erb

The class name for the zoom slider is `zoom-slider`

**Are you working on this? (Yes/No)**
No

![image](https://user-images.githubusercontent.com/2092958/94338795-a86c1900-0012-11eb-895e-8eab57103b14.png)

**Comment by arjungarg07** [comment]
Hey @satu0king Can i work upon this feature?

**Comment by satu0king** [comment]
@arjungarg07 go ahead

**Comment by rohan2734** [comment]
@satu0king  if @arjungarg07 couldnt do it, then assign me otherwise i will look on other issue.

**Comment by satu0king** [comment]
@arjungarg07 working on this?

**Comment by arjungarg07** [comment]
Yeah! , @rohan2734  can work on it, I am solving other issues.Thanks!

**Comment by rohan2734** [comment]
@satu0king @arjungarg07 ok i am working on this.

**Comment by rohan2734** [comment]
```
<script type="text/javascript">
  function zoomIn() {
      console.log("clicked zoom in");
      var canvasLayout = document.getElementById("backgroundArea");
      var currLeft = canvasLayout.style.left;
      var currTop = canvasLayout.style.top;
      canvasLayout.style.left = (currLeft - 10)+"px";
      canvasLayout.style.top = (currTop - 10)+"px";
  }
  function zoomOut() {
      console.log("clicked zoom out");
      var canvasLayout = document.getElementById("backgroundArea");
      var currLeft = canvasLayout.style.left;
      var currTop = canvasLayout.style.top;
      canvasLayout.style.left = (canvasLayout -20)+"px";
      canvasLayout.style.top = (canvasLayout -20)+"px";
  }
</script>
```

```
<canvas
      id="backgroundArea"
      style="
        position: absolute;
        left: 0;
        top: 0;
        z-index: 0;
        width: 100%;
        height: 100%;
      "
    ></canvas>
```

```
<div class="zoom-slider">
            <button type="button" onclick="zoomOut()">
                 <i class="fa fa-minus" aria-hidden="true" ></i>
            </button>
            <input type="range" class="custom-range" min="0" max="45" step="1"  id="customRange1">
            <span id='slider_value'></span>
            <button type="button" onclick="zoomIn()">
                <i class="fa fa-plus" aria-hidden="true" ></i>
            </button>
        </div>
```
guys here, ```console.log ``` is working , but the ```top``` and``` left``` values of the ```style``` in ```canvas``` are not changing, do you guys have any idea?.

**Comment by pavanjoshi914** [comment]
@satu0king if not done by anyone, would like to work on it....

**Comment by satu0king** [comment]
> @satu0king if not done by anyone, would like to work on it....

Go ahead

**Comment by pavanjoshi914** [comment]
@satu0king created a PR for this have a check on pr
