### ISSUE TITLE
Night Sky Theme Not working Properly

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1709]
**Describe the bug**
The Night Sky Theme in the Tools section on selecting works well, but on refresh it fades all the options on the Navbar.

**To Reproduce**
1. Go to 'beta.circuitverse.org'
2. Click on 'simulator'
3. Apply Night Sky theme and refresh

**Expected behavior**
The Navbar options should remain as it is like in the other themes.

**Screenshots**
Default Theme
![image](https://user-images.githubusercontent.com/42182955/94339067-bae75200-0014-11eb-9e7a-a9ec74a8d22e.png)

Night Sky Theme
![image](https://user-images.githubusercontent.com/42182955/94339076-d3576c80-0014-11eb-9701-200371c312bc.png)

On refreshing the Page
![image](https://user-images.githubusercontent.com/42182955/94339097-f84bdf80-0014-11eb-9eed-95b090e76ea0.png)

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

**Comment by satu0king** [comment]
I think the issue will be here `public/src/themer/themes.js`, some colors might be missing for some themes.

**Comment by AkashChetia** [comment]
Hi, @Shivansh2407. Can I work on this Issue? 
I'm new to opensource and hope will get some values by contributing to it.

**Comment by satu0king** [comment]
> Hi, @Shivansh2407. Can I work on this Issue?
> I'm new to opensource and hope will get some values by contributing to it.

Go ahead, this is an easy one. Good luck!

**Comment by Shivansh2407** [comment]
@satu0king, Is the the fix for this issue deployed on Beta Site? Because I am able to reproduce the bug currently in the Beta Site. Please check and Update.
