### ISSUE TITLE
Feature: Starburst Announcements [High Priority] 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1712]
We need to be able to make announcements of new features easily. Ideally we don't want to update the View code to make these kind of announcements. 

Gem: https://github.com/starburstgem/starburst#scheduling-announcements

**Describe the solution you'd like**
- [ ] Integrate the gem with our platform
- [ ] Confirm that announcements can support basic text as well as custom HTML with basic styling
- [ ] Check that announcements are shown to both logged in and logged out users
- [ ] Hide the close button (via CSS)
- [ ] The gem does not have an admin panel to create a new announcement. Create a simple admin view to create new announcements. Similar to https://circuitverse.org/custom_mails/new

It is possible to create this feature from scratch without using gems. If that is easier, we can consider that as well. @tachyons  can advise on the same. 
**This is a high priority feature request**

**Are you working on this? (Yes/No)**
No

**Comment by pavanjoshi914** [comment]
I would like to implement It if it is not taken by anyone

**Comment by satu0king** [comment]
> @satu0king I would like to implement It if it is not taken by anyone

Go ahead!

**Comment by rohan2734** [comment]
@satu0king  if @pavanjoshi914  has not yet done, i would like to work on this issue.

**Comment by satu0king** [comment]
@pavanjoshi914 working on this?

**Comment by pavanjoshi914** [comment]
> @pavanjoshi914 working on this?

@satu0king  work in progress....

**Comment by pavanjoshi914** [comment]
> @satu0king if @pavanjoshi914 has not yet done, i would like to work on this issue.

HII @rohan2734  
even a single line you contribute to circuit verse ,it is a great contribution

If you  are new to circuitverse plzz have a look on them

https://github.com/CircuitVerse/CircuitVerse/issues/1740
https://github.com/CircuitVerse/CircuitVerse/issues/1711

also visit https://beta.circuitverse.org/simulator and file some good issues that you will enouter 
Thanks!

**Comment by rohan2734** [comment]
- @pavanjoshi914  sure pavan, but no one has responded to #1655 issue, who have commented there. please someone check it.
- #1740 , do you have any idea , how to manage that problem?
- #1711 , i have commented my idea, there, if it could be assigned to me , i can work and solve it.

**Comment by pavanjoshi914** [comment]
> * @pavanjoshi914  sure pavan, but no one has responded to #1655 issue, who have commented there. please someone check it.
> * #1740 , do you have any idea , how to manage that problem?
> * #1711 , i have commented my idea, there, if it could be assigned to me , i can work and solve it.

respective authors will respond soon on them 
1740 needs more test results from different browsers and os after that only browser specific changes can be done

**Comment by rohan2734** [comment]
> respective authors will respond soon on them
> 1740 needs more test results from different browsers and os after that only browser specific changes can be done

ok

**Comment by satu0king** [comment]
Anyone send a PR for this issue. It is urgent as we need to announce the beta website so that we can get more testers.

**Comment by pavanjoshi914** [comment]
@satu0king 
 https://circuitverse.org/custom_mails/new
not authorised to view this plzz share screenshot for the same...

**Comment by pavanjoshi914** [comment]
@satu0king  @tachyons 
I was working on feature announcement implementation and created it from scratch before generating a PR for the same it is worthy to ask modifications

1>basically announcement is displayed for both logged in and logged out users on hompage only (suggest if want to display site wide)
2>It represents new created (latest record)  single line announcement in between start and end date
3>for creating announcements controller to perform CRUD operations on announcements (suggest if want to be limited to specific operations)

more modifications I want to apply:
A>as displaying latest record we can create other announcement only after end date of previous announcement if we do it before it,then it  will overide it as we are displaying latest record only

   I am thinking of creating any or limited number of announcements at any time and displaying them according to their dates

  solution 1> fetching all announcements and  displaying announcements  depending on startdate and enddate ( can create any number of announcementt at once and schedule them ,if we had many announcements I think this will not be feasible)


   solution 2> fetching latest 5 announcements and presenting them according to startdate and enddate (hence can create 5 announcements and schedule them at once)

B> not just single line announcements of features, but also  having relevant data which expressing feature in detail

   solution>I was thinking of creating announcement with relative  images paragraphs in separate view (show view) for expressing  announcements
  in detail (announcement model with  fields body ,start_date,end_date_,images,text_area )
   (suggest if only  announcement ,with start and end date needed)

C>having show and index view for announcements
  a separate announcement view where we can show all recent announcements and show view to see full details of announcements
 (on announcement banner we will have know more button redirecting users to show and index pages)
(suggest if only admin view is sufficient for create delete and update them)

 plzz suggest if above mentioned any modifications are currently  in need

also some screenshot of admin view of custom mail and suggestion for announcement banner design to have them in sync with current ui

**Comment by tachyons** [comment]
We can think about more flexible announcements feature later, we are looking for an immediate solution for now, we are already delayed for this

**Comment by pavanjoshi914** [comment]
> We can think about more flexible announcements feature later, we are looking for an immediate solution for now, we are already delayed for this

Ohk sure sir, so I will generate pr to display announcements with basic operations on it....

Also I have finished my work on modifications that i've suggested if any want plzz suggest freely ...

Thanks for the review!!
