### ISSUE TITLE
Delete Selected option Not working on the Quick Access Panel

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1713]
**Describe the bug**
When selecting a Particular element, for, example : input element, and then clicking on Delete Selected on the Quick Access Panel, The Input is not getting deleted.

**To Reproduce**
1. Go to 'beta.circuitverse.org'
2. Go to Simulator
3. Insert any element and click delete selected on the Quick Access Panel

**Expected behavior**
It should work in the same way, as the Delete option in the context menu.

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

**Comment by 1337w0rm** [comment]
Has this issue been fixed ? I can't seem to reproduce it.

**Comment by Shivansh2407** [comment]
Closing this issue, as it has been Fixed in this [commit](https://github.com/CircuitVerse/CircuitVerse/commit/c8ee110f371620117b8c2f3ada104363f115be89)
