### ISSUE TITLE
Delay in Text to be removed

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1716]
**Describe the bug**
Delay Property from Text Element should not be there.

**To Reproduce**
1. Go to 'beta.circuitverse.org'
2. Select 'Text' Element
3. See error

**Expected behavior**
The Delay property should be removed from Text.

**Screenshots**
![image](https://user-images.githubusercontent.com/42182955/94363710-c9e80600-00e1-11eb-9af8-168b858951a7.png)

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Additional context**
Contributors can Take reference from [this](https://github.com/CircuitVerse/CircuitVerse/pull/1335) PR.

**Are you working on this issue? (Yes/No)**
No

**Comment by Yashs911** [comment]
Hi, @Shivansh2407 Can I work on this Issue. I am new to open source so, can guide me what all changes are necessary.

**Comment by satu0king** [comment]
@Yashs911, just add `Text.prototype.propagationDelayFixed = true;` to `public/src/modules/Text.js`

**Comment by Yashs911** [comment]
@satu0king okay. I will create a PR on 1st Oct.

**Comment by Yashs911** [comment]
@satu0king I think there is some typo in the file path because I cannot find src folder in public

**Comment by satu0king** [comment]
> @satu0king I think there is some typo in the file path because I cannot find src folder in public

Check new_UI branch

**Comment by Yashs911** [comment]
@satu0king, can you, please provide the link for that file where I need to add Text.prototype.propagationDelayFixed = true; Sorry If I caused any inconvenience.

**Comment by satu0king** [comment]
Fixed
