### ISSUE TITLE
Some contents not escaped

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#1720]
**Describe the bug**
The contents of the 'Open offline project' menu are not escaped. The title can contain malicious javascript. Since this only happens locally, it is not a security threat but escaping is always better

**To Reproduce**
1. Go to 'beta.circuitverse.org/simulator'
2. Click on 'Project > Save offline'
3. Change the value of 'projectList' key in the local storage to <script>alert(1)</script>
4. Click 'Project > Open offline'
5. See error

**Expected behavior**
The contents of the project title should be escaped, you should see "<script>alert(1)</script>" as the title instead of the script getting executed

**Screenshots**
![Screenshot from 2020-09-28 15-09-29](https://user-images.githubusercontent.com/53974118/94417461-b9956100-019d-11eb-9b6f-f0475df589a7.png)
![Screenshot from 2020-09-28 15-09-37](https://user-images.githubusercontent.com/53974118/94417465-bbf7bb00-019d-11eb-97b2-7fa2f4e7eb2e.png)

**Device Information [optional]:**
Chrome 84.0.4147.105
Ubuntu 20.04 LTS

**Similar issue in Combinational analysis**

**To Reproduce**
1. Go to 'beta.circuitverse.org/simulator'
2. Click on 'Tools > Combinational analysis'
3. Type in <script>alert(1)</script> in either of the fields and click Next

**Are you working on this issue? (Yes/No)**
No

**Comment by 1337w0rm** [comment]
I don't think this is a relevant issue or bug. It is a self XSS and no sensitive information is being stored in the localstorage.

**Comment by gr455** [comment]
> I don't think this is a relevant issue or bug. It is a self XSS and no sensitive information is being stored in the localstorage.

Yes this is true. I mentioned that this is not a security issue. Just for UI sake. But to be fair, this is really not an important issue because people will most likely not alter local storage contents

**Comment by gr455** [comment]
A similar bug is in the combinational analysis popup, but there you can just type in unescaped HTML/JS which is better issue.(again not a security issue, just UI)

**Comment by 1337w0rm** [comment]
In the `Save Offline` feature the contents are being sanitized. The XSS in triggered only when you manipulate the local storage

**Comment by gr455** [comment]
> In the `Save Offline` feature the contents are being sanitized. The XSS in triggered only when you manipulate the local storage

You're right. I think it's best to only focus on the combinational analysis one.

**Comment by 1337w0rm** [comment]
I tried to fix the Combinationa Analysis bug. Can you please verify if the fix is working correctly or not. [Combinational Analysis XSS Fix](https://3000-c1ec5981-a3ba-49ed-a382-f576c2ad6632.ws-us02.gitpod.io/simulator)

**Comment by gr455** [comment]
> I tried to fix the Combinationa Analysis bug. Can you please verify if the fix is working correctly or not. [Combinational Analysis XSS Fix](https://3000-c1ec5981-a3ba-49ed-a382-f576c2ad6632.ws-us02.gitpod.io/simulator)

Can you base your changes over the new_UI branch?

**Comment by 1337w0rm** [comment]
By "Base your changes over the new_UI branch" you meant to make a PR ? 

I made a PR, tell me if I did it right. I'm fairly new to these stuff.

**Comment by gr455** [comment]
> By "Base your changes over the new_UI branch" you meant to make a PR ? 
> 
> I made a PR, tell me if I did it right. I'm fairly new to these stuff.

I meant use the new_UI branch and make changes in that and PR to the new_UI branch.
If you have CircuitVerse in your git remote(as circuitverse), then you can use

`git checkout circuitverse/new_UI`
Then you can make a new branch(say you call it xssfix) by
`git checkout -b xssfix`
This will create(and switch to) a branch 'xssfix' which will be based on the new_UI branch.
Now any commits that you make on this branch will be on top of the commits from the 'new_UI' branch.

You can make changes on this branch and push to **your fork** of this repository

`git push origin xssfix`

This will create a new branch 'xssfix' on your GitHub fork of this repository.
Then make a PR and select base branch as new_UI on GitHub.

All this is because the code will soon be migrated to the new_UI branch

**Comment by 1337w0rm** [comment]
Thanks for the help. 

Did a Pull Request to new_UI branch can you please check it out.

**Comment by vijay938** [comment]
I want to work on this issue

**Comment by gr455** [comment]
I think this issue is already fixed
