### ISSUE TITLE
Change logo for Google OAuth

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerse#1721]
**Describe the solution you'd like**
I'd like that we update our auth logo for Google to something along the lines of https://developers.google.com/identity/branding-guidelines

**Additional context**
Currently, we use this.

![Screenshot from 2020-09-28 20-27-12](https://user-images.githubusercontent.com/50791000/94449249-849f0380-01c9-11eb-940b-83aa2260a07d.png)

It's a small fix, but I feel we should update content :man_shrugging: 

**Are you working on this? (Yes/No)**
I'd love to, but I'd like to know the reactions first.

**Comment by nishd8** [comment]
Yes I am working on this even put a pull request

**Comment by ShubhankarKG** [comment]
Closing this since the issue has been resolved.
