### ISSUE TITLE
Project properties display object on 'Launch'

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#1724]
**Describe the bug**
Project properties section displays a span object instead of the project name when launching a saved circuit 

**To Reproduce**
Steps to reproduce the behavior
1. Go to 'beta.circuitverse.org'
2. Make a new project ( if you don't have an existing project)
3. Go to Dashboard, click 'Launch' on the project

**Expected behavior**
Should display the project name in place of the object

**Screenshots**
![Screenshot from 2020-09-29 12-49-29](https://user-images.githubusercontent.com/53974118/94525996-7d700800-0252-11eb-9cdc-44d95d08bec9.png)

**Device Information [optional]:**
Chrome 84.0.4147.105
Ubuntu 20.04 LTS

**Are you working on this issue? (Yes/No)**
No

**Comment by satu0king** [comment]
@gr455, I pushed some new changes today. Can you check if it is still happening?

**Comment by gr455** [comment]
> @gr455, I pushed some new changes today. Can you check if it is still happening?

Fixed now thanks!
