### ISSUE TITLE
Hex-Bin-Dec-converter not working

### ISSUE THREAD

**Issue by ryuk156** [CircuitVerse/CircuitVerse#1731]
**Describe the bug**
No prompt appearing when we click on  Hex-Bin-Dec-converter inside Tools 

**To Reproduce**
1. Go to 'Simulator
2. Click on 'tools'
3. Then Click to 'Hex-Bin-Dec-converter'

**Expected behavior**

Old UI:
![image](https://user-images.githubusercontent.com/49101492/94650412-46fac180-0314-11eb-8115-b92f5d86929a.png)

**Screenshots**
New UI:
![image](https://user-images.githubusercontent.com/49101492/94650464-642f9000-0314-11eb-8e10-55d0564b7cb8.png)

**Device Information [optional]:**
 - OS: [e.g. Windows 10]
 - Browser [e.g. chrome]

**Are you working on this issue? (Yes/No)**
No

**Comment by Rajat-S-Patel** [comment]
it's working in my case

**Comment by ryuk156** [comment]
@Rajat-S-Patel  its not working on beta   https://beta.circuitverse.org/simulator can you  try this URL

**Comment by Rajat-S-Patel** [comment]
yes, It's not working on beta

**Comment by ryuk156** [comment]
@satu0king  can you take a look please

**Comment by satu0king** [comment]
> @satu0king can you take a look please

Yes it has not been migrated, we just need to migrate the code.

**Comment by satu0king** [comment]
Fixed
