### ISSUE TITLE
Tutorial Guide is not working properly under certain conditions in beta version

### ISSUE THREAD

**Issue by Rajat-S-Patel** [CircuitVerse/CircuitVerse#1733]
**Descption**
Tutorial Guide is not working after deleting an element
**To Reproduce**
1. Go to 'beta.circuitverse.org/simulator'
2. Select circuit element, and then delete that element.
3. Now click on Help
4. Try to open tutorial guide
5. It will work for circuit element, but when you click next, it will hang.

**Expected behavior**
It should continue to display guide for all the panels.

**Screenshots**
<img width="908" alt="Annotation 2020-09-30 125354" src="https://user-images.githubusercontent.com/53576511/94655640-8e854b80-031c-11eb-9c6a-e26223a4eef3.png">
<img width="903" alt="Annotation 2020-09-30 125420" src="https://user-images.githubusercontent.com/53576511/94655647-9218d280-031c-11eb-8fe8-cbd0e99765ec.png">
Now it's not showing the tutorial guide

**Comment by satu0king** [comment]
Nice catch @Rajat-S-Patel, This is happening because the property menu is not active. Also noticed that if the menu's are collapsed, it won't work properly. 

@abstrekt any inputs here?

![image](https://user-images.githubusercontent.com/2092958/94965712-9827d280-0519-11eb-8308-df8f3345af92.png)

**Comment by abstrekt** [comment]
> 
> 
> Nice catch @Rajat-S-Patel, This is happening because the property menu is not active. Also noticed that if the menu's are collapsed, it won't work properly.
> 
> @abstrekt any inputs here?
> 
> ![image](https://user-images.githubusercontent.com/2092958/94965712-9827d280-0519-11eb-8308-df8f3345af92.png)

The tutorial pop-ups are attached to the elements but the offsets are static & fixed, it doesn't actually hang, but as the properties panel is currently hidden so is the popup..  though as a consequence the next previous buttons get hidden but the tutorial also operates with the arrow keys and the tour continues when pressing ```right or left``` arrow key..

As a consequence of draggable components and static offset, I also noticed something like this:

![image](https://user-images.githubusercontent.com/42478217/95015723-2dd37700-066c-11eb-9070-bb9f9791f6dd.png)
as the offset for this panel set to the right of the element.

A solution could be to expand the panels if minimized or show if hidden upon re-initiating the tutorial, 
but the offset problem with draggable panels is a bit tricky..
