### ISSUE TITLE
Navigation link 

### ISSUE THREAD

**Issue by reshma-avvaru** [CircuitVerse/CircuitVerse#1742]
The navigation button of current page in navigation bar  is not disabled. 
view get reloaded on clicking the button leading to same view again
![bug1](https://user-images.githubusercontent.com/69675204/94774883-5a715f80-03dc-11eb-96c6-f92d13e9c826.png)

Are you working on this issue? (Yes/No)
Yes

**Comment by pavanjoshi914** [comment]
@reshma-avvaru always use screeshots to describe the bug ,Thanks!

**Comment by alishahzil** [comment]
I would like to work on this issue.

**Comment by pulkit-30** [comment]
Is there anyone working on this issue?
If not, may you please assign me this issue and please help me out with some code pointers/references.

**Comment by tachyons** [comment]
This is not a bug, You can see similar behaviour in Github as well
