### ISSUE TITLE
Inconsistent color scheme in the Combinational Analysis Tool

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1748]
**Describe the bug**
The Combinational Analysis Truth Table has a green and white color scheme which isn't consistent with the theme of the simulator.

**To Reproduce**
1. Go to [Simulator Beta Version](https://beta.circuitverse.org/simulator)
2. Click on ```Tools - > Combinational Analysis```
3. Enter the variables to see the table.

**Expected behavior**
A color scheme more consistent with the simulator theme

**Screenshots**
![image](https://user-images.githubusercontent.com/42511766/94833802-30945900-042d-11eb-9a9e-803a2275276b.png)

**Are you working on this issue? (Yes/No)**
No, open for triage

**Comment by satu0king** [comment]
@nitin10s @abstrekt is this intended?

**Comment by abstrekt** [comment]
> @nitin10s @abstrekt is this intended?

definitely not, missed this element

**Comment by nitin10s** [comment]
As far as I remember, this was designed in a way to look different from all other elements deliberately? And it should ideally change as we change the theme.
But I strongly believe this can be improved and incase someone has a design in mind, pls do suggest.

**Comment by pavanjoshi914** [comment]
> As far as I remember, this was designed in a way to look different from all other elements deliberately? And it should ideally change as we change the theme.
> But I strongly believe this can be improved and incase someone has a design in mind, pls do suggest.

@nitin10s 
![color](https://user-images.githubusercontent.com/55848322/94987775-96482880-0586-11eb-8dcf-7fa7ba30e143.png)
have a look  on this combination...

**Comment by abstrekt** [comment]
The only color-changing per theme is the 1st row

**Comment by Palaksharma23** [comment]
hey is anyone working on this issue ? 
i would love to work on this issue .

**Comment by Prerna-0202** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/89515816/142739281-11669efd-fa47-4d2c-b21a-8bc310a6d7e5.png)
 
@abstrekt @nitin10s @sal2701,  please have a look at this one.. is this ok?

**Comment by gr455** [comment]
> ![Screenshot (4)](https://user-images.githubusercontent.com/89515816/142739281-11669efd-fa47-4d2c-b21a-8bc310a6d7e5.png)
> 
> @abstrekt @nitin10s @sal2701 @gr455, please have a look at this one.. is this ok?

Looks good to me

**Comment by nitin10s** [comment]
Looks good to me as well

**Comment by Prerna-0202** [comment]
@gr455 @nitin10s, So, can I make a pull request for this change?
