### ISSUE TITLE
"Draggable" indicator vanishes on minimizing Property Menu

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1749]
**Describe the bug**
The Property Menu has a "-" to indicate that it can be dragged around in the simulator. On minimizing, this indicator vanishes.

**To Reproduce**
1. Go to [Simulator Beta](https://beta.circuitverse.org/simulator)
2. Click on the Property Menu Title to minimize it.
3. The bar vanishes

**Expected behavior**
The bar should be present in the minimized state as well.

**Screenshots**
Maximized
![image](https://user-images.githubusercontent.com/42511766/94844675-3ba2b580-043c-11eb-8f59-8ce0f47207f7.png)

Minimized
![image](https://user-images.githubusercontent.com/42511766/94844721-4c532b80-043c-11eb-867c-95393170d0e1.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by GAUTAMSAHARAN** [comment]
I like to work on this issue.

**Comment by GAUTAMSAHARAN** [comment]
I solve this issue and also did for the Circuit Element menu and I made the  Pr request Please review it and let me know any changes needed.

**Comment by GAUTAMSAHARAN** [comment]
and I more think @sal2701 this pr also have the code to resolve the issue #1751, do I need to exclude the changes for that issue from this pr.

**Comment by GAUTAMSAHARAN** [comment]
Well just do me a favor @sal2701, first please review my first PR request #1764, and if that get's merged and we will see if this Pr #1773  gets any conflict then I start work on how to solve them.

**Comment by GAUTAMSAHARAN** [comment]
made a new pr request with different branch
![Screenshot from 2020-10-04 18-13-16](https://user-images.githubusercontent.com/54721472/95016206-1b0e7180-066f-11eb-8325-005525eaab47.png)
