### ISSUE TITLE
Button to create "New Circuit" in "Insert Subcircuit" Dialogue

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1751]
**Is your feature request related to a problem? Please describe.**
If there is only 1 circuit and we press ```Insert SubCircuit``` we get a dialogue box. Adding a button to ```Create a New Circuit``` can be helpful.

**Describe the solution you'd like**
A simply button or anchor tag to create a new circuit.

**Additional context**
Screenshot
![image](https://user-images.githubusercontent.com/42511766/94851544-377b9580-0446-11eb-88b1-bad9dc06a832.png)

**Are you working on this? (Yes/No)**
No.

**Comment by GAUTAMSAHARAN** [comment]
I wanted to work on this.

**Comment by GAUTAMSAHARAN** [comment]
a simple button I think works and it's great because we wanted to minimize the work of user so it's good d

**Comment by sal2701** [comment]
That's great @GAUTAMSAHARAN. Go ahead. Let me know if you face any issues.

**Comment by GAUTAMSAHARAN** [comment]
Thanks, @sal2701,  I am having an issue which is when i try to make changes in public/src directory js files and restart the server i am not getting it's those changes in my browser, is there some way to rebuild the js file??

**Comment by sal2701** [comment]
Yeah @GAUTAMSAHARAN. CircuitVerse uses Webpack to handle the javascript modules and assets. So the files are generated and are served from the ```public/packs/``` directory. This bundling process takes place once at the beginning, which works great for production, but for local development we need it to reload aka. Hot Reload on our changes. So you need to run ```bin/webpack-dev-server``` to enable this Hot Reload.

Thanks for bringing this to our notice, we weren't aware this wasn't documented.

**Comment by GAUTAMSAHARAN** [comment]
Thanx for your help about webpack and i add a button in dialog box to create new circuit directly and made a Pr. Please review it.

**Comment by GAUTAMSAHARAN** [comment]
so here we go, I made a new pull request with different branch 
![Screenshot from 2020-10-04 17-48-46](https://user-images.githubusercontent.com/54721472/95015538-0e881a00-066b-11eb-8c14-52e0ba3d4a62.png)

**Comment by Prerna-0202** [comment]
Hii,
I am interested in this issue
Is anyone working on this issue?
Please assign me this issue...

**Comment by gr455** [comment]
> Hii, I am interested in this issue Is anyone working on this issue? Please assign me this issue...

No need to be assigned, you can work on this
