### ISSUE TITLE
Add instructions to enable Webpack Hot Reload to SETUP.md

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1757]
**Describe the bug**
Information about Webpack is not present in ```SETUP.md```. It needs to be updated.

The new_UI uses webpack to bundle the javascript module and assets. So to see any changes made to the simulator code aka. Hot Reload, on the local server, we need to start the ```webpack-dev-server```.

This can be done by running the command ```bin/webpack-dev-server``` .

This instruction needs to be added to the ```SETUP.md``` file.

**Are you working on this issue? (Yes/No)**
No

**Comment by arjungarg07** [comment]
Hey @sal2701 ,Can I work on this?

**Comment by sal2701** [comment]
Sure @arjungarg07, go ahead.

**Comment by arjungarg07** [comment]
I have made the changes as requested, Please review @sal2701. Thanks
