### ISSUE TITLE
Login Button overlaps with ReCaptcha on hovering

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1762]
**Describe the bug**
ReCaptcha was recently added, but it is not styled properly. It needs to be fixed.

**To Reproduce**
1. Go to [CircuitVerse Login Page](https://circuitverse.org/users/sign_in).
2. Hover over the login button.

**Expected behavior**
Proper styling around the ReCaptcha Element.

**Screenshots**
![image](https://user-images.githubusercontent.com/42511766/94938104-09519080-04ee-11eb-9102-d7c87051a156.png)

**Are you working on this issue? (Yes/No)**
No.

**Comment by zhanghailing** [comment]
can I work on this issue?

**Comment by DhairyaBahl** [comment]
I would like to work on the issue if its still available 

Thanks :)

**Comment by SakshiSarna** [comment]
would love to work on this issue

**Comment by manwindersingh1712** [comment]
Can I work on this issue !! I would love to do it .

**Comment by jayantchaudhary002** [comment]
I would like to work on this issue

**Comment by shivamparashar165** [comment]
I would like to work on this issue.

**Comment by Ddevendra** [comment]
[resolved recaptcha-button overlap #1854](https://github.com/CircuitVerse/CircuitVerse/pull/1854)
