### ISSUE TITLE
Complete div behaves as checkbox rather than just the checkbox on Login Page

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#1763]
**Describe the bug**
Clicking the whole div selects/deselects the checkbox.

**To Reproduce**
1. Go to [CircuitVerse Login Page](https://circuitverse.org/users/sign_in)
2. Click on and around the 'Remember Me' Checkbox
3. It selects/deselects the Remember Me Checkbox

**Expected behavior**
Only clicking the checkbox should select/deselect it.

**Screenshots**
![image](https://user-images.githubusercontent.com/42511766/94939490-dc05e200-04ef-11eb-9433-2ec1e76febe4.png)

**Are you working on this issue? (Yes/No)**
Nope.

**Comment by sal2701** [comment]
@nitin10s Is this a bug or was it intended?

**Comment by Shivansh187** [comment]
I would like to work on this issue

**Comment by nitin10s** [comment]
Not intended, it's a bug

**Comment by sal2701** [comment]
Great @Shivansh187 go ahead!

Thanks @nitin10s

**Comment by pavanjoshi914** [comment]
@sal2701  If not done yet shall I generate a PR?

**Comment by Shivansh187** [comment]
@sal2701 I'm new to open source and facing some issues. If @pavanjoshi914 has solved, you can reassign it to him. Sorry for the inconvenience

**Comment by yuktibagrodia** [comment]
Can I give it try? if it's not done?

**Comment by yuktibagrodia** [comment]
Can I give it a try? If it's not done?

**Comment by aayush-05** [comment]
@nitin10s @satu0king do we want it to accessible by the text too or just the box?

**Comment by rishabhgit0608** [comment]
is this issue fixed ? i was seeing to work on it .
