### ISSUE TITLE
Assignment Close Immediately

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1766]
Currently assignments close at a deadline. However, it will be a nice for the professor to have the ability to close the assignment immediately. This will be helpful in a test like environment, where the official time is 1 hour, but the professor has set deadline as 1.5 hours (for margin). But once he is convinced everyone is done, he can close it manually himself. 

I would like a button which says "Close now"

**Are you working on this? (Yes/No)**
No

**Comment by jayantchaudhary002** [comment]
I would like to work on this issue

**Comment by satu0king** [comment]
Go ahead @jayantchaudhary002

**Comment by dipanshparmar** [comment]
Working on it @satu0king

**Comment by shagun25** [comment]
Is this issue still open, I would like to work on it.

**Comment by ineffable23** [comment]
@satu0king Do let me know if this issue is still open. I'm highly interested to work on this issue.

**Comment by CoderMayhem** [comment]
Has there been any developement regarding this issue? If not I would like to take it up @satu0king . Kindly let me know.

**Comment by ShreyaPrasad1209** [comment]
@satu0king @tachyons can we add this under good first issues?

**Comment by pulkit-30** [comment]
Hey @satu0king @ShreyaPrasad1209 , 
Is anyone working on this?
If not Please assign me this issue and please help me out with some code pointers/references from where I can start digging into it.
