### ISSUE TITLE
Export Link is not very visible

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1768]
**Describe the bug**

![image](https://user-images.githubusercontent.com/2092958/94962632-606a5c00-0514-11eb-8c04-c328a6ba306c.png)

I think the export link in the assignment page can be made into button to increase visibility. Also rename to export grades instead of export results. 
@aayush-05 is that good? 

**Are you working on this issue? (Yes/No)**
No

**Comment by aayush-05** [comment]
Yeah! This looks a good improvement

**Comment by arjungarg07** [comment]
@satu0king, I would like to work on this, please.
