### ISSUE TITLE
User name dropdown menu css issue .

### ISSUE THREAD

**Issue by Amansingla97** [CircuitVerse/CircuitVerse#177]
There seems to be a positioning issue with the dropdown menu which is dependent on the size of username. 

I would like to self assign this issue

<img width="412" alt="screenshot 2019-03-03 at 3 17 29 pm" src="https://user-images.githubusercontent.com/20012612/53696496-686c9200-3ded-11e9-8483-ff4e864c4e2a.png">

**Comment by sarthak77** [comment]
I would like to take up this issue
