### ISSUE TITLE
Fork Own Circuit Bug

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#1774]
**Describe the bug**
While saving the circuit, we get to see the Project Description, along with the Launch Simulator, Fork and Star Button, But Fork must only be implemented for other users forking our project or vice-versa. Currently Fork button is shown for my very own project in the Project description page and the View Modal in the Dashboard. 

**To Reproduce**
1. Go to 'circuitverse.org or beta.circuitverse.org'
2. Create a Circuit -> Save It
3. Go to Project Description

**Expected behavior**
Fork button should be renamed as "Create Copy" for own circuits both in the project description and the view modal.

**Screenshots**
![image](https://user-images.githubusercontent.com/42182955/94988299-ce9d3600-0589-11eb-8924-8485a1a78b75.png)
![image](https://user-images.githubusercontent.com/42182955/94988294-c3e2a100-0589-11eb-8169-0e58e5b49c20.png)

**Device Information [optional]:**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

**Comment by sal2701** [comment]
Instead of removing the 'Fork' option we could have a 'Create Copy' option for our own circuits, it might be useful to users creating circuits which involve lot of common stuff.

@Shivansh2407 @satu0king Thoughts?

**Comment by satu0king** [comment]
Yes, the fork your own circuit feature is very important. If you want to rename it to Create Copy instead of Fork, go ahead!

**Comment by Shivansh2407** [comment]
Create Copy would be a Better option 👍

**Comment by sal2701** [comment]
@Shivansh2407 can you edit the issue to reflect that? Thanks

**Comment by 1337w0rm** [comment]
Do you want to keep the fork icon ? @satu0king @Shivansh2407

**Comment by arjungarg07** [comment]
ok

**Comment by DevanshD3** [comment]
Hey I am new to open source and would love to contribute to Circuitverse! Could you please explain me how to proceed ? Is anyone working on this issue ?

**Comment by vkassingh** [comment]
I am also looking to make quality contributions in UI, UX and documentation for circuit verse. Please guide me a bit.
Thanks

**Comment by satu0king** [comment]
@1337w0rm and others, note that this issue is not simply rename fork -> copy. It is rename fork -> copy only for the authors. Also I don't think just renaming makes sense, because the database and view will show the circuit as forked later.

**Comment by aayush-05** [comment]
It would be better if someone can first list all the instances where we mention a project as a fork (or forked from). Then we can add on a conditional to all of them once

**Comment by apoorvdwi** [comment]
Is the issue still open ?
I would like to work on it .

**Comment by sarthakkundra** [comment]
@Shivansh2407 I would like to work on this for SWoC. Can you assign it to me?

**Comment by Shivansh2407** [comment]
@sarthakkundra you can go ahead and start working on the issue. Make sure to keep in mind, the suggestions in the comments mentioned above, and work accordingly 👍

**Comment by surbhigoel191** [comment]
@sarthakkundra Are you still working on the issue? If not I would like to take it @Shivansh2407

**Comment by sarthakkundra** [comment]
@surbhigoel191 please go ahead. I have my hands full right now.

**Comment by nitin10s** [comment]
> @1337w0rm and others, note that this issue is not simply rename fork -> copy. It is rename fork -> copy only for the authors. Also I don't think just renaming makes sense, because the database and view will show the circuit as forked later.

If this is the case, I don't think changing name would be wise. Whatsay @Shivansh2407 ?

**Comment by Shivansh2407** [comment]
Yeah @nitin10s, As mentioned earlier, renaming fork -> copy only for authors will show forked in the database so we need to update that entirely to show up create copy in database instead of forked only for the authors, because just renaming it is meaningless here at this point, as we cannot identify which is forked and copied from database point of view.
Let me know your views on this @satu0king @tachyons

**Comment by satu0king** [comment]
The database can maintain it as forked, that shouldn't be a big deal. The key point is it should show copy only if the circuit is owned by the current user. Otherwise it should be fork.
