### ISSUE TITLE
Google Login not working on beta.circuitverse.org

### ISSUE THREAD

**Issue by 1337w0rm** [CircuitVerse/CircuitVerse#1782]
**Describe the bug**
Google Login doesn't work on beta.circuitverse.org

**To Reproduce**
1. Go to 'beta.circuitverse.orh'
2. Click on 'Login'
3. Scroll down to 'Google Login Button' and click it.

**Expected behavior**
Clicking on google login button should've let the user to login or choose their google account to login.

**Screenshots**
![Screenshot_2020-10-04-06-50-39-527_org bromite bromite](https://user-images.githubusercontent.com/41179329/95004853-5c226980-060e-11eb-8d73-f6a2539c8687.jpg)

**Are you working on this issue? (Yes/No)**
No

**Comment by gr455** [comment]
I think this is only because Google Oauth is not configured for beta since beta is not really for end usage, @satu0king can confirm?

**Comment by tachyons** [comment]
Yes, it is just a matter of configuration issue

**Comment by satu0king** [comment]
It is working now.
