### ISSUE TITLE
Add a search bar in the user's dashboard

### ISSUE THREAD

**Issue by rajat2502** [CircuitVerse/CircuitVerse#1806]
**Is your feature request related to a problem? Please describe.**
Right now, the user's dashboard doesn't have any option to search for a particular project (circuits).

**Describe the solution you'd like**
A search bar will improve the user's experience as they will be able to search for the required project easily.

**Comment by paultech4u** [comment]
@rajat2502 can I work on this issue.

**Comment by yuktibagrodia** [comment]
can I do?

**Comment by vkassingh** [comment]
I would like to work on this issue. So @satu0king can you please guide me through this?

**Comment by harshitaaaaaa** [comment]
![Screenshot from 2020-11-05 22-40-53](https://user-images.githubusercontent.com/66556662/98273354-292a1780-1fb8-11eb-91ad-3bf145d4edcd.png)

A search bar is already available in user dashboard.

**Comment by satu0king** [comment]
Yes this is a much needed feature. The search bar that you are referring to @harshitaaaaaa searches across all projects and users. 

What a user would need is a search for just his/her projects. Implement this in client side. It will be very easy to do so using basic JQuery and JS.

**Comment by Shubhamverma2796** [comment]
Can I work on this issue?

**Comment by pavanjoshi914** [comment]
@satu0king ,If not done yet, I would like to work on this....

**Comment by dipanshparmar** [comment]
> @satu0king ,If not done yet, I would like to work on this....

Hello @pavanjoshi914 , I'm really sorry that I forgot to claim this issue. Actually I have already started working on this and it'll be completed soon. So, can I continue my work on this? or do you want to work on this?

**Comment by dipanshparmar** [comment]
> @satu0king ,If not done yet, I would like to work on this...

Hello @pavanjoshi914 , I'm really sorry that I forgot to claim this issue. Actually I have already started working on this and it'll be completed soon. So, can I continue my work on this?

**Comment by pavanjoshi914** [comment]
> > @satu0king ,If not done yet, I would like to work on this...
> 
> Hello @pavanjoshi914 , I'm really sorry that I forgot to claim this issue. Actually I have already started working on this and it'll be completed soon. So, can I continue my work on this?

@dipanshparmar no  problem please continue work on this!! I will work on something else

**Comment by dipanshparmar** [comment]
.
