### ISSUE TITLE
On click of search button the heading "Dive into the world of Logic" gets hidden!!!

### ISSUE THREAD

**Issue by khanjasir90** [CircuitVerse/CircuitVerse#1817]
**Describe the bug**
When you click on the search button on the home page the search bar hides the heading "Dive into the world of Logic"

**To Reproduce**
1.Go to the home page of circuitverse.org
2.Click on search button icon
3.on the click of the button the search bar hides the line of user interface "Dive into the world of Logic".
4.See error

**Expected behavior**
The line "Dive into the world of Logic" should not get hide else it should be visible to the user..

**Screenshots**
Before : 
![before](https://user-images.githubusercontent.com/53305380/96358963-b3562d00-112a-11eb-91fb-5fd68f8494fe.PNG)
After : 
![after](https://user-images.githubusercontent.com/53305380/96358969-bd782b80-112a-11eb-8205-e6e376b5b1fe.PNG)

**Are you working on this issue? (Yes/No)**
Yes!!!

**Comment by khanjasir90** [comment]
Please assign this to me !!! I would like to work on this!

**Comment by pavanjoshi914** [comment]
This was tried earlier too.. plzz refer 
https://github.com/CircuitVerse/CircuitVerse/pull/1789
As it is not required you can close issue...
thanks!!!

**Comment by khanjasir90** [comment]
okay @pavanjoshi914
