### ISSUE TITLE
Subcircuit's dimensions increase non uniformly

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#1823]
**Describe the bug**
Subcircuit's dimensions' alteration and movement of the label happens at a varying rate when multiple circuits are created

**To Reproduce**
1. Go to 'beta.circuitverse.org/simulator'
2. Make 4 to 5 circuits
3. For each circuit, go into layout mode and increase the height/width or move the label
4. Notice that for each subsequent circuit, the increases happen at increased rate

**Expected behavior**
The change in dimensions and movement label should happen at a constant rate

**Device Information [optional]:**
 - OS: Ubuntu 20.04
 - Browser: Chrome 84

**Are you working on this issue? (Yes/No)**
No

**Comment by satu0king** [comment]
Fixed
