### ISSUE TITLE
Inconsistent use of the microcopy "Log in"

### ISSUE THREAD

**Issue by iprithvitharun** [CircuitVerse/CircuitVerse#1827]
**Describe the bug**
Three different words (Log in, Login, and Log In) used on the Log in page to denote the same action.  

'Login' is the noun/adjective form referring to the form, page, or actual credentials. 'Log In' is the verb form referring to the action.

**To Reproduce**

Visit the [Log in page](https://circuitverse.org/users/sign_in) 

**Expected behavior**
All three instances should use the same microcopy to improve the users' experience.

**Screenshots**
![circuit-verse](https://user-images.githubusercontent.com/58725708/96817852-d3912f00-143d-11eb-878b-2fc5847d7cf7.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by satu0king** [comment]
Interesting, according to you, we should rename it to which of the 3? Also is `Sign In` better?

**Comment by iprithvitharun** [comment]
@satu0king 

We should rename all three to **Log in**.

The reason I didn't use Sign in is that users can easily mistake Sign in for Sign up and vice-versa as both the labels look almost identical. 

From a consistency perspective, you'd expect to use Sign in since we are using Sign up. But users are easily prone to making mistakes. I did analytics on the users' behaviour in my organization regarding this and Log in and Sign up worked better. The number of errors reduced drastically.
