### ISSUE TITLE
CircuitVerse Discord

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#183]
#### Describe your bug/feature -

I want to startup an unnofficial CircuitVerse Fan Discord Server, as an alternative means of community connections. I wanted to first request permission to do this, to avoid any conflicts with other plans.

#### Current behaviour -

There is no discord.

#### Expected behaviour -

There is a discord.

#### Are you working on this issue? (Yes/No)

Yes

**Comment by satu0king** [comment]
Sounds like a great idea. I am not very familiar with discourse however, can you brief me on how it works? I would like to know if we need to host this separately as well, do we need to pay for this and on which domain will the discord be accessible. 

Also so we are using gitter for developer discussions, discourse for user's question forum and discord for fan discussions?

**Comment by satu0king** [comment]
@fpintos any comments?

**Comment by jbox144** [comment]
@satu0king

Discord is a free service, and they host the servers themselves. "server" is just a word for a group of chats operated by the same people. otherwise, discord can be likened to an IRC, but with a lot of extra features.

**Comment by satu0king** [comment]
Great, go ahead then

**Comment by agarwalrounak** [comment]
What about Slack? I see a lot of Open Source Projects nowadays using Slack. I too have been using it for the past few months and it's really good.

**Comment by Parikshit-Hooda** [comment]
I will setup a Slack workspace. Mentors and participants - opinions? There is nothing actually distinguishable with discord..its just pretty slick in the sense of themes, animations, welcome messages as far as i have noticed.

**Comment by Parikshit-Hooda** [comment]
Also, I like the above template of issue which leads to submitting a PR. I think we can put it in CONTRIBUTING.md . Opinions?

**Comment by fpintos** [comment]
> @fpintos any comments?

I suppose the only comment I have on this right now is that if we end up with multiple community fragments it gets harder to keep track of them and people won't know where to go for answers.

It might also be interesting to setup expectations about these services: one might be more community-driven and community-oriented for people that just want to use the product, while another might be more appropriate for people interested in contributing to the code.

As long as we have pointers to them in the home page and people know what to expect from each, it should be fine.

**Comment by ahmedkrmn** [comment]
An IRC channel would be a viable solution as well.

**Comment by HypheX** [comment]
I do think a discord would be nice! I use discord a lot actually. I can only see it contributing positively.

**Comment by satu0king** [comment]
No I do not prefer slack. Either way @jbox144 wanted a fanbase forum for fun discussions. For any developer discussions, Gitter will do well. Adding to what @fpintos said, I would like the following to be the expectations 

- Discourse - Question And Answer Forum for normal users - questions related to CV and Digital Logic Design
- Gitter - Developer only discussions 
- Discord - Fan discussions - people can reach out to other fans here and collaborate on interesting projects, discuss tricks and hacks etc.

**Comment by jbox144** [comment]
Yay! I made the unofficial CircuitVerse fan discord server!

https://discord.gg/95x8H7b

**Comment by Parikshit-Hooda** [comment]
CircuitVerse Slack url [circuitverse.slack.com](url)

**Comment by Parikshit-Hooda** [comment]
@jbox144  open a PR.
