### ISSUE TITLE
Announcement Feature improvements

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1832]
Small improvements for the announcement feature
- [ ] Text Wrapping is not correct?
![image](https://user-images.githubusercontent.com/2092958/97009211-72627c00-1561-11eb-9265-d9e09c988357.png)

- [ ] Button Text should be customizable. I think here the button text should be "Try It" instead of "Read More" 
![image](https://user-images.githubusercontent.com/2092958/97009241-7bebe400-1561-11eb-8c8f-3e122770d271.png)

- [ ] Link to open in new tab
- [ ] Wysiwyg text editor as it is HTML content. 

@pavanjoshi914

**Comment by pavanjoshi914** [comment]
@satu0king working on it!! :+1:

**Comment by satu0king** [comment]
> @satu0king working on it!! 👍

Awesome. I added a couple of additional improvements in the issue, please check.

**Comment by pavanjoshi914** [comment]
https://github.com/froala/wysiwyg-rails

this gem is to be integrated for 4th checkpoint?

**Comment by satu0king** [comment]
> https://github.com/froala/wysiwyg-rails
> 
> this gem is to be integrated for 4th checkpoint?

This looks amazing! However we are already using a text editor for project page description and assignment page description. Probably just use that for now.

@aayush-05 @nitin10s does this froala text editor look better?

**Comment by satu0king** [comment]
https://summernote.org/
@pavanjoshi914 can u research on other text editors 
https://awesomeopensource.com/projects/wysiwyg-editor

**Comment by pavanjoshi914** [comment]
> > https://github.com/froala/wysiwyg-rails
> > this gem is to be integrated for 4th checkpoint?
> 
> This looks amazing! However we are already using a text editor for project page description and assignment page description. Probably just use that for now.
> 
> @aayush-05 @nitin10s does this froala text editor look better?
> 
> Update: Froala is not free, so not an option for us.

ohk i was not aware  of text editor already present got it in editor folder will use that !!!

**Comment by pavanjoshi914** [comment]
> https://summernote.org/
> @pavanjoshi914 can u research on other text editors
> https://awesomeopensource.com/projects/wysiwyg-editor

on it!!

**Comment by aayush-05** [comment]
We are currently using this: https://alex-d.github.io/Trumbowyg/
It's not the most feature-rich, but very small ~20kB (comparison: SummerNote is ~100kB). I would recommend the current one since our usage isn't much in terms of fancy text styling. 
If we go by the current one, it has already been abstracted as a rails partial, and would require one-line change to incorporate for this feature. 
cc: @satu0king

**Comment by pavanjoshi914** [comment]
poked around the list of the editors except simiditor and summernote  some lacks ui some lacks features 
found current one always better than them...
 as compared with size i agree with @aayush-05

**Comment by pavanjoshi914** [comment]
if we put url in the link without protocol like "www.circuitverse.com" it opens localhost:3000/www.google.......
url must have https or http
is this needs to be corrected?

**Comment by satu0king** [comment]
> if we put url in the link without protocol like "www.circuitverse.com" it opens localhost:3000/www.google.......
> url must have https or http
> is this needs to be corrected?

Current Behavior seams fine.
