### ISSUE TITLE
WYSIWYG Text Editor - Improvements

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1837]
**Is your feature request related to a problem? Please describe.**

Current Editor
![image](https://user-images.githubusercontent.com/2092958/97068776-3de5d300-15e8-11eb-9e5b-2133a7df8665.png)

We are using https://alex-d.github.io/Trumbowyg/

However, the editor in the main website is having more features 
![image](https://user-images.githubusercontent.com/2092958/97068819-a339c400-15e8-11eb-8bee-1d1959d26560.png)

Specific features I would like to see
* HTML Code Preview
* More Text Size options
* Super Script and SubScript
* Full Screen View

Plugins also have more features which we can consider
1. Embed Video
2. Upload Image -> IMGUR
3. Color Text
![image](https://user-images.githubusercontent.com/2092958/97068983-290a3f00-15ea-11eb-9331-53d4e5871360.png)

Maybe we are using an older version of the text editor or we have to enable the features, not sure. 

**Are you working on this? (Yes/No)**
No

**Comment by satu0king** [comment]
cc @pavanjoshi914 @aayush-05

**Comment by pavanjoshi914** [comment]
I would like to work on this...

**Comment by DevanshD3** [comment]
@satu0king I would like to work on this issue
