### ISSUE TITLE
Search elements are not draggable onto the main canvas in the beta simulator

### ISSUE THREAD

**Issue by aaryandewan** [CircuitVerse/CircuitVerse#1846]
Describe the bug
After searching for an element (say Multiplexer) from the newly introduced search box in the beta simulator, you cannot drag the element into the canvas. To add that element, you must click on it and then move your mouse to the canvas. This bug is not present in the working (main/non-beta) version.

To Reproduce
1. Go to https://beta.circuitverse.org/simulator
2. In the search box, type NOR.
3. Try dragging the NOR gate into the canvas. It won't move.

Expected behavior
The searched elements should be draggable onto the canvas

Are you working on this issue?
No

**Comment by shivamparashar165** [comment]
Love to work on this issue. 

Assign me this issue @satu0king

**Comment by satu0king** [comment]
Go ahead @shivamparashar165

**Comment by DevanshD3** [comment]
Can I work on this issue please ?

**Comment by shivamparashar165** [comment]
> Go ahead @shivamparashar165

Thanks, I am working on it.

**Comment by shivamparashar165** [comment]
Hey ! Everyone 

Sorry from my side, As a new developer I was not able to fix the issue. 

For, this issue I think that it is not made-up for me. I am trying for last 2 days but not able to solve that issue.
I am with community and like to do small contributions now.

Hope in future, I will also able to solve these complex issue.

**Comment by satu0king** [comment]
@shivamparashar165, Hey it is alright. This was a slightly hard fix. But don't give up! 

Check the fix here: https://github.com/CircuitVerse/CircuitVerse/commit/085a374c021f0e4dd48753ecc77582f0a1a66dd6
