### ISSUE TITLE
Sign In and Navbar Toggler Button overlap in Beta Simulator when browser window is resized

### ISSUE THREAD

**Issue by KKVANONYMOUS** [CircuitVerse/CircuitVerse#1853]
**Describe the bug**
After resizing the browser window of **Beta Simulator** you can see that the **Sign In** and **Navbar Toggler Button** overlap each other which makes it difficult to distinguish between the two.

**To Reproduce**
1. Go to https://beta.circuitverse.org/simulator
2. Resize the browser window, Sign In and Navbar toggler button will overlap

**Expected behavior**
The Sign In option should be included inside the Navbar Toggler when browser window is resized

**Screenshots**
![Screenshot (18)](https://user-images.githubusercontent.com/58628586/97526071-5c741180-19ce-11eb-911e-0e5bf5068af1.png)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser: Chrome

**Are you working on this issue?**
No

**Comment by pavanjoshi914** [comment]
resolved in #1725 , #1745 but yet to be merged...

**Comment by KKVANONYMOUS** [comment]
ohhk, I will close this issue, Thank You for notifying me
