### ISSUE TITLE
Heading and Icon are overlapping with each other

### ISSUE THREAD

**Issue by dipanshparmar** [CircuitVerse/CircuitVerse#1874]
**Describe the bug**
Heading and icon of the 'circuit elements' tab are overlapping with each other.

**Expected behavior**
There were supposed to be some spacing between the heading and the icon.

**Screenshots**
![image](https://user-images.githubusercontent.com/49204837/98205993-24854500-1f5f-11eb-8eb9-e8dcb5c5fcd0.png)

**Device Information [optional]:**
 - OS: Ubuntu 20.04
 - Browser: firefox

**Are you working on this issue? (Yes/No)**
Yes

**Comment by satu0king** [comment]
@dipanshparmar reference issues

**Comment by dipanshparmar** [comment]
@satu0king I actually did so, but somehow the issue was not showing up there.
