### ISSUE TITLE
Group Page - Privacy Violations

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1893]
**Describe the bug**
The group page lists all email ids of all members of the group. Only group admin should be able to see the email ids as this is a possible Privacy violation.

**To Reproduce**
1. Create a group
2. Add 2 members to group
3. Login to member 1 account
4. Member 1 user can see member 2's email id (privacy violation)

**Expected behavior**
Only group admin should be able to see all email ids

**Are you working on this issue? (Yes/No)**
No

**Comment by arjungarg07** [comment]
I would like to work on this.

**Comment by arjungarg07** [comment]
I have opened a pull request. Kindly review https://github.com/CircuitVerse/CircuitVerse/pull/1896 
Thanks.
