### ISSUE TITLE
Can't erase project name

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#1895]
**Describe the bug**
Project properties menu dissapears on pressing backspace/delete

**To Reproduce**
1. Go to 'beta.circuitverse.org/simulator'
2. Try to erase the project name from the properties menu on the right side

**Expected behavior**
Must be able to erase the project name

**Are you working on this issue? (Yes/No)**
No

**Comment by satu0king** [comment]
Fixed
