### ISSUE TITLE
backdrop appears at top in report issue popup

### ISSUE THREAD

**Issue by abstrekt** [CircuitVerse/CircuitVerse#1899]
**Describe the bug**
the backdrop for the 'Report an Issue' popup is appearing on top on everything, making the popup inaccesible.
**To Reproduce**
Just click report an issue

**Expected behavior**
1. Backdrop should be in proper z-index,  
2. as well as also clicking on backdrop should close the Report Issue dialog/popup
3. The close 'X' & the dialog title should have proper formatting/alligned (all seems to be wrapped centric, include the close 'X' )

**Screenshots**
![image](https://user-images.githubusercontent.com/42478217/98459083-25b3ad80-21bd-11eb-8fc2-936e32ea5a88.png)

**Device Information [optional]:**
 - fireox/chrome

**Additional context**
Found this is on beta

**Are you working on this issue? (Yes/No)**
No

**Comment by dipanshparmar** [comment]
@abstrekt can I work on this?

**Comment by abstrekt** [comment]
> @abstrekt can I work on this?

okay.

**Comment by satu0king** [comment]
Hey @dipanshparmar, I pushed a fix as I knew exactly what causes this problem. Thanks!

**Comment by dipanshparmar** [comment]
> Hey @dipanshparmar, I pushed a fix as I knew exactly what causes this problem. Thanks!

Oh! okay :slightly_smiling_face:
