### ISSUE TITLE
Improving search bar

### ISSUE THREAD

**Issue by pratyush6717** [CircuitVerse/CircuitVerse#1900]
**Is your feature request related to a problem? Please describe.**
Right now, there is no query suggestion and recent searches in search bar,

**Describe the solution you'd like**
Adding query suggestion and recent searches  will improve user experience.

**Comment by DevanshD3** [comment]
Are you working on this issue ?

**Comment by pratyush6717** [comment]
No,I am not working in it.

**Comment by harshitaaaaaa** [comment]
Can I work on this?

**Comment by iemprashant** [comment]
I would like to work on this.

**Comment by Palaksharma23** [comment]
I would love to work on this issue , is anybody working on this issue , can you please assign it to me ?

**Comment by pratyush6717** [comment]
Obsolete
