### ISSUE TITLE
Input box should not reload when it is empty

### ISSUE THREAD

**Issue by dipanshparmar** [CircuitVerse/CircuitVerse#1909]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/49204837/98624425-d04ddc80-2333-11eb-8155-96ccb8e59394.png)
If we don't add anything in the input box and click on <b>add collaborators</b> button then the page reloads and give this error:
![image](https://user-images.githubusercontent.com/49204837/98624553-160aa500-2334-11eb-954e-725aea77b405.png)

**Describe the solution you'd like**
We can enhance the user experience by providing a client side verification of the input box. If there is no value in the input box then we can prevent the reload and add border of red, so that the user knows that it is invalid.

**Are you working on this? (Yes/No)**
Yes

**Comment by satu0king** [comment]
The issue presented is not a big deal. But there is something better you can work on. Instead of getting the details from the server, why don't you do it in client side only. 

Something like this: This will give confidence to the user that it is working. 

![image](https://user-images.githubusercontent.com/2092958/99786378-6cea5880-2b44-11eb-9312-82f4aa1229f0.png)

**Comment by satu0king** [comment]
Or even better something liek this

https://codepen.io/gehadz/pen/PrMNba

**Comment by satu0king** [comment]
@Shivansh2407 any inputs here?

**Comment by Shivansh2407** [comment]
I was thinking like when there is no text present in the Text box, till that time we can disable the button to Add Collaborators. Next, On adding an email ID, for sure we should go with tagging the inputs. Then As we get one or more tag, we can enable the Button and add the Collaborator, this way it solves the empty field issue and also will improve the user experience. Please let me know your views on this @satu0king

**Comment by satu0king** [comment]
Yes just disabling the button is a great idea. Yes https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/ is a good alternative as well.

**Comment by satu0king** [comment]
Note most of these options do not seem to allow the emails to be separated by "space" or "new line" or "tab", this is important because our users might just copy/paste from excel or other sources and the emails may not be separated by comma.

**Comment by dipanshparmar** [comment]
@satu0king and @Shivansh2407, so the final concept is that:-
1. Emails input should be in the format of the tags.
2. Button should be enabled only when there are one or more email tags present.
3. Input box should have the ability to differentiate the emails when 'space', 'new line', or 'tab' is encountered.

Please let me know if this is what you guys wanted.

**Note:** There can be a delay for this PR as my final exams are coming in December. But I'll make the PR as soon as possible.

**Comment by satu0king** [comment]
> @satu0king and @Shivansh2407, so the final concept is that:-
> 
> 1. Emails input should be in the format of the tags.
> 2. Button should be enabled only when there are one or more email tags present.
> 3. Input box should have the ability to differentiate the emails when 'space', 'new line', or 'tab' is encountered.
> 
> Please let me know if this is what you guys wanted.
> 
> **Note:** There can be a delay for this PR as my final exams are coming in December. But I'll make the PR as soon as possible.

Did u do this in the PR? the PR seems to disable the button?

**Comment by dipanshparmar** [comment]
yeah @satu0king I am working on this but I also feel like that I should close this PR and create a new one as there are no major changes done on that PR yet and I also want to do a fresh start. So I'm closing this PR now and will make a new one ASAP with the mentioned features. Sorry for the delay.

**Comment by dipanshparmar** [comment]
@satu0king, @aayush-05, @Shivansh2407 
Updates:
1. This is how the tags input will look like:
![image](https://user-images.githubusercontent.com/49204837/100847119-64c7dc80-34a5-11eb-906a-57225f291ef6.png)

**Now I'm trying to figure out how to do the 3rd step when pasting**
