### ISSUE TITLE
New UI Tab Bar issues

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1911]
Old UI: 

![image](https://user-images.githubusercontent.com/2092958/98796037-f1482780-2430-11eb-877b-2bd569e78a2b.png)

New UI:

![image](https://user-images.githubusercontent.com/2092958/98796075-fe651680-2430-11eb-9456-b252dabeeacb.png)
![image](https://user-images.githubusercontent.com/2092958/98796100-045af780-2431-11eb-8367-3ba3637556ce.png)

Issues:
1. Old UI tabs look more modern, brighter, rounded corners, better colors
1. Old UI selected tab is very clear. Here there is confusion as to which tab is selected
1. Old UI tab increases as required. New UI tab size is fixed and overflow goes down (not desired)
1. Old UI allowed lots of circuits, tabs overflowed to next line if required. New UI doesn't allow circuits beyond tab bar length.

**Comment by satu0king** [comment]
@abstrekt please check this. Thanks!

**Comment by dipanshparmar** [comment]
@satu0king if this issue is open for everyone then I would like to work on this.

**Comment by Just-A-Pixel** [comment]
satu0king Is it possible that I can contribute to this issue too?

**Comment by satu0king** [comment]
@dipanshparmar , @Just-A-Pixel , check new_UI branch, @abstrekt has fixed it. However, you can try and make it Better.

**Comment by dipanshparmar** [comment]
@satu0king yeah! Sure 🙂
