### ISSUE TITLE
combinational analysis needs few improvements

### ISSUE THREAD

**Issue by pavanjoshi914** [CircuitVerse/CircuitVerse#1915]
position should be correct when circuit gets generated
![2020-11-13_10-45](https://user-images.githubusercontent.com/55848322/99031685-b283b000-259d-11eb-9f03-5defad62b6bc.png)
small ui improvement will make it correct
![2020-11-13_10-40](https://user-images.githubusercontent.com/55848322/99031692-b6173700-259d-11eb-974d-5c68bdef19b2.png)
tooltip
![Screenshot from 2020-11-13 10-53-45](https://user-images.githubusercontent.com/55848322/99032126-bcf27980-259e-11eb-9786-ad3958651934.png)

**Comment by satu0king** [comment]
There is no exact position actually because the property menu and other things can be moved

**Comment by satu0king** [comment]
Call autofocus in the end, that should work. @pavanjoshi914

**Comment by pavanjoshi914** [comment]
got it!! I was unaware of that option

**Comment by satu0king** [comment]
> got it!! I was unaware of that option

No, I mean we should call autofocus in the code to fix this issue. `globalScope.centerFocus();` I added that now.

**Comment by pavanjoshi914** [comment]
ohh i thought you were talking about right click and center focus to centralize thinks...

**Comment by satu0king** [comment]
> ohh i thought you were talking about right click and center focus to centralize thinks...

Yes that calls the above function
