### ISSUE TITLE
Group Invite by Link

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1922]
It is difficult to invite users in large groups in some cases as teachers don't have list of email ids. 

**Describe the solution you'd like**
We can have group invite link similar to the one used in whatsapp. 

Url can be of the form `groups/id/invite/<secret token>`

I think there is a rails API to create tokens easily, something along the lines `has_secure_token :auth_token` @tachyons any inputs here? I think this resource might help: https://blog.bigbinary.com/2016/03/23/has-secure-token-to-generate-unique-random-token-in-rails-5.html

- [ ] Add Token to groups Table
- [ ] Existing groups are assigned a token in the previous migration
- [ ] New groups get a token when created
- [ ] Button in group page to copy invite link
- [ ] Button in group page to reset invite link (should we have this option?) 
- [ ] Add method to groups_controller to add current user to the group if the secret token matches

We can also consider deprecating the way we do currently, i.e. using `pending invitations` for email invite. Instead we can send a mail invite with the link. This will also give a way for users to accept group invite rather than forcibly be put into a group (privacy reasons). Another advantage is if user for some reason signs up on personal account instead of college account, it still works. 

**Are you working on this? (Yes/No)**
No

**Comment by pavanjoshi914** [comment]
@satu0king i would like to work on this..

**Comment by satu0king** [comment]
> @satu0king i would like to work on this..

Go ahead

**Comment by satu0king** [comment]
> * Invitation link should be optional, no need to have invitation link for all groups
> * token must be expirable to avoid misuse

Yeah agreed, @pavanjoshi914 keep this in mind? This actually might make things easier. We can set an automatic invitation link expiry of 2 weeks.

**Comment by satu0king** [comment]
Thank you @pavanjoshi914 !
