### ISSUE TITLE
Not being copied to clipboard

### ISSUE THREAD

**Issue by DevanshD3** [CircuitVerse/CircuitVerse#1924]
**Describe the bug**
While we try to Embed the iframe links on the main website , when we click on "Embed" we see the <iframe> code and below that it says "copied to clipboard" but it hasn't been copied to clipboard. This is a problem in all the 3 ie Featured Examples , Editor picks and Recent Circuits.

**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to Featured Examples/Editor picks or Recent Circuits.
3. Click on "view" on any circuit that is present there and then click on "Embed"
4. You will see the message "copied to clipboard" but it doesn't copy the code.

**Expected behavior**
it should either already copy the code to the clipboard or ask the user to copy.

**Screenshots**

![Screenshot (225)](https://user-images.githubusercontent.com/64734319/99412686-033b3600-291b-11eb-8f56-f6346c2f36d5.png)

**Device Information [optional]:**
 - OS: Windows
 - Browser : Chrome
 

**Are you working on this issue? (Yes/No)**
Yes

**Comment by satu0king** [comment]
@DevanshD3 also mention on what platforms it is working and on what it is not

**Comment by harshitaaaaaa** [comment]
![Screenshot from 2020-11-19 23-33-46](https://user-images.githubusercontent.com/66556662/99705528-d96f4400-2abf-11eb-866e-18eaa684f9d4.png)

In mozilla, there is no Embed feature whereas in Chrome it is there.

**Comment by harshitaaaaaa** [comment]
@DevanshD3 @satu0king Actually the error is just that after clicking on Embed we have to manually copy the code by selecting it but the message shows copied to clipboard. I think we should either code it in a way that it directly copies the link or it should not show the copied to clipboard message, instead it should say,'select and copy'.

**Comment by satu0king** [comment]
@harshitaaaaaa no we actually copy to clipboard also but it is not working for some browsers - https://github.com/CircuitVerse/CircuitVerse/blob/master/app/views/projects/show.html.erb#L205-L224

**Comment by abhinav-TB** [comment]
I can't copy the circuit into my clipboard as text now, can anyone help

**Comment by pavanjoshi914** [comment]
@satu0king i am not able to reproduce bug... it is working fine 
is this still a problem?

**Comment by DevanshD3** [comment]
@pavanjoshi914 it still is a problem for my browser( Chrome 87 on Windows 10), it says "copied to clipboard" but it doesn't copy on its own.

**Comment by pavanjoshi914** [comment]
yup fixed it !!
