### ISSUE TITLE
Difficulty in clicking help link in Navbar

### ISSUE THREAD

**Issue by aldrinjenson** [CircuitVerse/CircuitVerse#1927]
**Describe the bug**
- No hand-pointer  in the Navbar for the help link (only present when the mouse is hovered only to the extreme left)
- In order to access the help link from the simulator, unlike other links in the nav, most part of the help link seems to be disabled

**To Reproduce**
1. Open the simulator
2. Try to open help section by clicking on the help link in the nav
3. It will be disabled.
4. Nov hover mouse to extreme left of the help text, now a hand-pointer will appear and the link becomes active

**Expected behavior**
The link should be active when the mouse is hovered anywhere on the help text

**Screenshots**
![image](https://user-images.githubusercontent.com/53407417/99488780-10453d00-298e-11eb-8b58-b00cc21f5964.png)

**Device Information [optional]:**
 - OS: Ubunutu 20.04
 - Browser: Firefox

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by SingingApple** [comment]
@aldrinjenson Can I work on this issue?

**Comment by shivamkushwah0** [comment]
works pretty fine with my system.......no such problem i m facing

**Comment by SingingApple** [comment]
@shivamkushwah0 another div is overlapping ***help*** in navbar which creates a difficulty in clicking on it.

**Comment by aldrinjenson** [comment]
@SingingApple , I am not currently working on this. If you have found the fix, then ig you can make a pr

**Comment by aldrinjenson** [comment]
@shivamkushwah0 ,  here is a gif showing the difficulty. Apparently, the help nav link becomes active only when the cursor is hovered to the far left.
![problem](https://user-images.githubusercontent.com/53407417/99699105-98733180-2ab7-11eb-9cf8-45f7412925e2.gif)

**Comment by harshitaaaaaa** [comment]
@aldrinjenson It's working pretty fine on my system as well.

**Comment by shivamkushwah0** [comment]
![16058093634113671940698184909701](https://user-images.githubusercontent.com/66745614/99706016-7f22b300-2ac0-11eb-9735-e2e5ed33d8f7.jpg)

See......this isn't the same as urs!! I'm using windows and chrome browser

**Comment by satu0king** [comment]
Please check if this issue is there in https://beta.circuitverse.org/simulator, otherwise close this issue.

**Comment by SingingApple** [comment]
@satu0king @aldrinjenson it is working fine in the above link. Kindly, close this issue.

**Comment by aldrinjenson** [comment]
@satu0king , it is working fine in https://beta.circuitverse.org/simulator 

But the issue still persists in Firefox for https://circuitverse.org/simulator 
However, it does not seem to be there for Chrome browser

**Comment by sanchit36** [comment]
@aldrinjenson It is working on my system ( windows 10 and ubuntu 20.04 on firefox).

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/66944705/101207010-fb5af000-3695-11eb-9f82-bc6e4887f6a6.gif)
