### ISSUE TITLE
positioning of the "Untitled" text in Simulator 

### ISSUE THREAD

**Issue by shivamkushwah0** [CircuitVerse/CircuitVerse#1934]
**Describe the bug**
the positioning of "Untitled" text after opening of the simulator is not justified in some screen size

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'Simulator'
3. Reduce the screen size to less than 991px
4. See the Blue colored "Untitled" after toggling on the navbar, the text is hidden from the left side to some extent 

**Expected behavior**
The text "Untitled" should have been directly below the other navbar options 

**Screenshots**
The original behaviour
![download](https://user-images.githubusercontent.com/66745614/99671702-6b635680-2a98-11eb-8174-5c6322241108.jpg)

The expected behaviour
![download (1)](https://user-images.githubusercontent.com/66745614/99671801-9057c980-2a98-11eb-8967-badafe6f8506.jpg)

**Device Information [optional]:**
 - OS: Windows 10 (using WSL2)
 - Browser : Chrome
  

**Are you working on this issue? (Yes/No)**
Yes, I want to work on the issue

**Comment by shivamkushwah0** [comment]
I would like to work on this issue, please assign it to me

**Comment by harshitaaaaaa** [comment]
Yes, I want to work on this issue.

**Comment by shivamkushwah0** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/1935#issue-524508858

**Comment by Shivansh2407** [comment]
@shivamkushwah0 Please have a look at the new Simulator at https://beta.circuitverse.org/simulator

**Comment by shivamkushwah0** [comment]
@Shivansh2407 is the new simulator in new_UI branch of the codebase......i was looking at the old simulator.....where is the codebase for the new simulator??

**Comment by satu0king** [comment]
> @Shivansh2407 is the new simulator in new_UI branch of the codebase......i was looking at the old simulator.....where is the codebase for the new simulator??

check new_UI branch public/src folder
