### ISSUE TITLE
Improve Embed Feature. 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1938]
Currently the embed feature is basic, it just embeds under some default settings. Would like something as follows:

1. Click Embed
2. Dialog Opens
3. Dialog has following options

- iFrame Size
- Color Theme
- Optional Project Title Display
- Landing Circuit Tab (Circuit that is displayed be default)  
- Some Styling options like border etc
- Optionally Disable stuff like Clock Enable/Clock Time Interval/Zoom/FullScreen options 
- Some more stuff like this 

Referencing https://github.com/CircuitVerse/CircuitVerse/issues/1555

Current Sample iFrame Code
```
<iframe width="600px" height="400px" 
src="https://circuitverse.org/simulator/embed/sap-1-computer-5a0acd53-6e0c-434d-b19d-4073d9a6dc58" 
id="projectPreview" scrolling="no" 
webkitAllowFullScreen mozAllowFullScreen allowFullScreen></iframe>
```

I think we can encode the options like this 

`https://circuitverse.org/simulator/embed/<project id>?color-theme="default"&landing-circuit-id="21323"&display-title="true"`

@danielluehr would like your inputs here. 
@sal2701 @Shivansh2407 @nitin10s

**Comment by pavanjoshi914** [comment]
@satu0king any updates here... I would like to complete this feature for you.

**Comment by vmk8826** [comment]
assign it to m please

**Comment by pavanjoshi914** [comment]
I was busy in my semesters for a while.. @vmk8826 if you want to complete it please proceed

**Comment by vmk8826** [comment]
okay @pavanjoshi914  can you tell me about the progress you have made until now

**Comment by Kartikay304** [comment]
I would like to work on this feature.

**Comment by vedant-jain03** [comment]
@Kartikay304 Are you working on this, if not I want to work on this issue.

**Comment by vedant-jain03** [comment]
@Kartikay304 I want to work on this issue if you are not working?

**Comment by Kartikay304** [comment]
@vedant-jain03 You can work on this issue. Currently. I am not working on this issue.

**Comment by Kartikay304** [comment]
@vedant-jain03 I want to work on this issue, if you are not working on it?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 I want to work on this issue, if you are not working on it?

Go ahead, I am working on #1892 currently.
