### ISSUE TITLE
Unusual working of Tutorial Guide

### ISSUE THREAD

**Issue by jaggu21** [CircuitVerse/CircuitVerse#1952]
**Describe the bug**
Tutorial guide sometimes vanishes the Navbar . This can create issues for the user to save his/her current progress. 

Navbar vanishes in 3 cases:
1. When **Properties panel** is placed to extreme left.
2. When **Quick Access Panel**  is placed at the bottom.
3. When **Timing Diagram Panel** is placed at the bottom.

In some cases it creates an additional white space which never goes away. This is happening only when **Circuit Access Panel** is placed to extreme right.   

**To Reproduce**
1. Place the panel/s as per the position described in the **describe the bug** section. 
2. Go to **Help** .
3. Choose **Tutorial Guide** .

**Expected behavior**
1) Navbar should not get hidden due to actions of Tutorial Guide.
2) No extra spaces should be created.

**Screenshots**
**Navbar Issue**
![a3](https://user-images.githubusercontent.com/56889104/99885654-a9a97300-2c5c-11eb-8d83-77827de5ce06.png)
![a4](https://user-images.githubusercontent.com/56889104/99885660-af9f5400-2c5c-11eb-9235-cd6f815e02d6.png)

**White Space Issue**
![a1](https://user-images.githubusercontent.com/56889104/99885662-bf1e9d00-2c5c-11eb-8b08-c64575980bc5.png)
![a2](https://user-images.githubusercontent.com/56889104/99885665-c80f6e80-2c5c-11eb-9cd6-a5598a3039f9.png)

**Device Information [optional]:**
 - Browser : **Google Chrome**
 - Version  :  **83.0.4103.97**

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
There is another Unusual Behaviour, When we click on the Empty Circuit Canvas and Press Delete, The Property Panel gets removed. Then On Opening the Tutorial Guide, It shows black faded screen after one step (Because it cannot generate the removed property panel). @abstrekt @satu0king Please Check this.

**Comment by 2019UCP1350** [comment]
I think I can solve this issue, but this is my first time contributing to an organization. So, Could you please guide me?

**Comment by 2019UCP1350** [comment]
Can I work on this issue?

**Comment by abstrekt** [comment]
> Can I work on this issue?

certainly go ahead, let us know if you face any issues.

**Comment by 2019UCP1350** [comment]
Could u please help me in setting up the workspace on gitpod. 
It is showing some error like the creation of a new role failed: ERROR:  role "postgres" already exists.

**Comment by 2019UCP1350** [comment]
Please help I had tried many times to set up a workspace on git pod but it is still showing the same error.

**Comment by vedant-jain03** [comment]
fixed in #2360
