### ISSUE TITLE
Theme Creator 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#1964]
Create a theme creator window where I can select the colors for different theme elements. It should reflect changes realtime. This is a mostly a UI task of creating a window for the same. Allow the theme to be downloaded/loaded as a JSON. 

**Are you working on this? (Yes/No)**
No

@abstrekt any inputs here?

**Comment by saumyasrivastava08** [comment]
can i work?

**Comment by satu0king** [comment]
> can i work?

Yes @abstrekt any inputs here?

**Comment by abstrekt** [comment]
Yes, this is can be done & would be great allowing users to customize their simulator UI as per their taste, most useful for colorblindness, currently, when a theme is changed the function `updateThemeForStyle` is called to preview it in real-time, but it does so for all the elements, meaning it updates all the varibales. If in this feature we want each component to update in real-time for every particular element instantly making use of `updateThemeForStyle` would be very expensive, we should have a separate function to update only the current variable, after that, we can allow them to store it in their browser storage or in the db.

The menu of this customization would be a list of variables names with the current color, a color picker to update.

We can also consider separating customization into two sections, one section affecting only the simulator, & the rest for the rest.

we can also consider having a JSON editor open up on a browser window where we can edit the JSON, preview, save download without the need to have an external editor, something like this:

*  ![image](https://user-images.githubusercontent.com/42478217/100542087-0a910680-326e-11eb-9343-63a6d105e4c3.png)

**Comment by satu0king** [comment]
> Yes, this is can be done & would be great allowing users to customize their simulator UI as per their taste, most useful for colorblindness, currently, when a theme is changed the function `updateThemeForStyle` is called to preview it in real-time, but it does so for all the elements, meaning it updates all the varibales. If in this feature we want each component to update in real-time for every particular element instantly making use of `updateThemeForStyle` would be very expensive, we should have a separate function to update only the current variable, after that, we can allow them to store it in their browser storage or in the db.
> 
> The menu of this customization would be a list of variables names with the current color, a color picker to update.
> 
> We can also consider separating customization into two sections, one section affecting only the simulator, & the rest for the rest.
> 
> we can also consider having a JSON editor open up on a browser window where we can edit the JSON, preview, save download without the need to have an external editor, something like this:
> 
> * ![image](https://user-images.githubusercontent.com/42478217/100542087-0a910680-326e-11eb-9343-63a6d105e4c3.png)

JSoN Editor is an easy way out. I was thinking of having a nice UI where u can color pick colors.

**Comment by satu0king** [comment]
@saumyashrm2802 create something basic now. Themes is going to be a long task.

**Comment by Ayushdubey86** [comment]
I would like to work on this?

**Comment by pulkit-30** [comment]
Hey @satu0king @tachyons  @abstrekt ,
Is Anyone working on this?
If not, Can I come up with an idea, how to implement this and Can I start working on this Issue?

**Comment by pulkit-30** [comment]
What I understand so far is that 
We need a custom theme generator that takes the input as JSON and the User can Set his own custom theme colors.

https://user-images.githubusercontent.com/76155456/146489661-1914d464-59cc-4b6d-99fa-771e0e07f7be.mov

keypoints:
1. Reflect changes in realtime
2. Theme can be downloaded (export)
3. Theme can be loaded (import) as a JSON file

@satu0king @abstrekt @tachyons  any add-on or any suggestion or any point I just missed out, please mention.

**Comment by pulkit-30** [comment]
I just work on the loading/downloading of custom theme file 

https://user-images.githubusercontent.com/76155456/146518779-85f00361-18c2-4c4f-b0e9-405146701fe6.mov

Users can export the Custom theme JSON file for the future and also import the file and set the custom theme.

**Comment by abstrekt** [comment]
We haven't yet brainstormed on this particular feature. Will need to do some research on this for how the experience should be for end users.

at-least we know that exposing the css variables directly to the UI won't make much sense & will complicate stuff for the users.  
There needs to be a layer of abstraction here which should solve for:
* ease of use
* reduce number of input from users
* better meaning to each options that we expose for customisation

**Comment by tachyons** [comment]
I don't think we need custom themes for CV, having custom themes doesn't add much value. WDYT @nitin10s ?

**Comment by nitin10s** [comment]
I agree with abstrekt with the introduction of a level of abstraction for ease of use. @tachyons this is a "good to have" feature.
