### ISSUE TITLE
Clock Component independency

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#198]
#### I am submitting a -
* [] **Feature Request**

#### Describe your feature -
As of now, every clock is set to the same value, set within the simulation. There are times, however, when you may want two different clocks operating at different independent speeds.
#### Current behaviour -
All clocks operate at the same frequency.
#### Expected behaviour -
Each clock has an independent "speed" setting. 
#### Are you working on this issue? (Yes/No)
No.

Additionally, the maximum clock speed currently is 50ms, or 20Hz. If this could be made faster, that would be great, however I'm unsure of the limitations of the simulator or browser..

**Comment by fpintos** [comment]
My understanding is that the entire simulator works by recalculating stuff on each clock tick, so having two wildly independent clocks might not be as simple as it sounds.

In the meantime, one can always use a ripple counter to effectively create separate clocks, although in this case the clocks are always multiple of each other.

As for the minimum speed, I never tested lower values; it would have to be a value that would give enough time for the simulator to compute and redraw the circuit on every tick. It would be interesting to see how low it can get.

**Comment by blane1257** [comment]
When I first found this simulator, the fastest clock speed was as fast as 1ms, or 1KHz, though I'm unsure if such clock speeds made the simulator  unstable, or if the actual simulated clock speed was actually that fast

**Comment by satu0king** [comment]
> My understanding is that the entire simulator works by recalculating stuff on each clock tick, so having two wildly independent clocks might not be as simple as it sounds.
> 
> In the meantime, one can always use a ripple counter to effectively create separate clocks, although in this case the clocks are always multiple of each other.
> 
> As for the minimum speed, I never tested lower values; it would have to be a value that would give enough time for the simulator to compute and redraw the circuit on every tick. It would be interesting to see how low it can get.

You are right, all calculations happen when a user makes an interaction or when the clock ticks. So having multiple clocks will make this complicated and inefficient. The rendering doesn't happen on every clock tick at lower frequency. Whenever the clock ticks, it requests a canvas update, however, the canvas will actually update only after a certain time (before which several clock ticks can happen) allowing the clock frequency to be higher than the canvas update frequency.

**Comment by blane1257** [comment]
@satu0king did the 1ms clocks work properly, and why can you no longer set a value so low?

**Comment by satu0king** [comment]
> @satu0king did the 1ms clocks work properly, and why can you no longer set a value so low?

Well, our engine is not very optimized for such frequencies, to keep things stable, we have set the max frequency to 20 Hz. Of course, we need to improve this moving forward.

**Comment by blane1257** [comment]
Yes, I think the low clock frequency is very limiting.

Though on second thought, this might not be such a bad thing, as it has caused me to think much more intently about optimization of systems...
