### ISSUE TITLE
Refactor classes into separate files

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#199]
We should refactor the code to make it easier for people to get started with the code base.
Ideally, each class should have its own file and each standalone function should be on its own file as well.

In the long term we can pack them together for a single file download with webpack (as mentioned in #110)

Example of issues:
_Originally posted by @abdullah-mohamed in https://github.com/CircuitVerse/CircuitVerse/issues/190#issuecomment-469754219_

**Comment by ankitkataria** [comment]
This will be great! We can use React to declare the entire UI as various components. The life cycles methods will make it easier to define the routines that will be running the circuit.

**Comment by agarwalrounak** [comment]
This is a great idea! I can get started with it. 
Just for the purpose of knowing that I am on the right path, I will first start with the refactoring of [modules.js](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/js/modules.js) Based on the reviews I get, I will continue further.

@fpintos Can I take up this issue?

**Comment by satu0king** [comment]
This will be a major refactor and will break everything that others are working on. I would want to this after GSSoC is over and after GSoC selections are over.

**Comment by satu0king** [comment]
> This will be great! We can use React to declare the entire UI as various components. The life cycles methods will make it easier to define the routines that will be running the circuit. Then we can also explore the option of moving away from the current monolith repo to two separate repos, one for react front end and one for rails backend.

I don't think there will not be any major changes in the core circuit logic. I think the canvas is best handled by regular javascript and not react. Yes all the UI elements can move to react.

**Comment by tachyons** [comment]
https://github.com/rails/webpacker is the best way to accomplish this within rails app

**Comment by AniMysore74** [comment]
This library abstracts canvas implementations as react components. I think it's a good idea to use this for the React refactor.
https://github.com/Flipboard/react-canvas

**Comment by tachyons** [comment]
Part of refactoring task
