### ISSUE TITLE
Ability to 'load' an EPROM from a CSV file

### ISSUE THREAD

**Issue by richardpawson** [CircuitVerse/CircuitVerse#1990]
I designed my own, simple, 'EPROM burner' in CircuitVerse - it just advances the address counter (or you can set it) and you enter the data value and click next. Works nicely but very tedious for anything but a tiny data set.

I'd like to be able to generate the data set just a sequential set of values, in CSV format, say, then be able to load (preferably via a File dialog, but will accept a cut-and-paste of the data) any file into the EPROM. It's state should be preserved when the project is saved (as it is now for a hand-burned  'burned' EPROM)

So CSV file might be:

180,207,3,41 etc.

decimal numbers representing successive data values from address 0 onwards. N.B. The user should take responsibilities that all data values are within the integer range for the data bit-width, and that the total number of values does not exceed the address space of the EPROM,

**Comment by satu0king** [comment]
@shubhankarsharma00 check #1457 and #1014

**Comment by satu0king** [comment]
I think we need to consider multiple formats. 
1. Entire Data String like "0 0x12 0x2f 0". We have to assume its binary its decimal if no 0x. Assume its octal if starting with a zero. Data can be separated by space, tab, comma, newline. 
2. JSON format like { "addr1": "value1", "addr2":value2" }
3. CSV format with 2 columns - Address | Value. 

The first option is most straightforward but if entire memory is not used, it will be too big to manage.
Second and Third options is good in the other 2 cases.

**Comment by richardpawson** [comment]
I wouldn't over-complicate it. In Excel you can easily do the conversion between binary, hex, decimal. (Even for oldies like me, I doubt Octal has much use), and then output as a CSV.

 I'm also not sure that it is necessary to specify the address and the value. I think I would prefer just a sequence of data values and assume it starts from address zero.  I don't really care whether hex, decimal, or binary is the requirement -  if I had to state a preference it would be for decimal (easiest to check visually).

I don't really see the value (for this specific case) of using JSON (or XML) format - especially if not specifying the address - its harder to read or generate. For simple, linear lists or tables, CSV is a universal form.
