### ISSUE TITLE
Export to svg not working

### ISSUE THREAD

**Issue by humble-barnacle001** [CircuitVerse/CircuitVerse#1998]
**Describe the bug**
Downloading the circuit as svg is not working

**To Reproduce**
1. Go to simulator
2. Click on download as an image
3. Click on svg option
4. Nothing happens and the circuit is shifted towards bottom right

**Expected behavior**
The circuit should be downloaded as svg file

**Screenshots**
Output on console
![image](https://user-images.githubusercontent.com/58736240/100973350-660a0f80-3560-11eb-8cb3-d00e2a2c569e.png)

**Device Information [optional]:**
 - OS: Windows 10 20H2
 - Browser Chrome
 - Version 87.0.4280.66

**Additional context**
Probably an error in variable name or a missing variable or function

**Are you working on this issue? (Yes/No)**
No

**Comment by dipanshparmar** [comment]
@satu0king any inputs here? I can't reproduce this behavior in localhost.
