### ISSUE TITLE
Replace logix with circuitVerse

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#20]
The project was initially named logix but was later renamed to CircuitVerse. The name has been changed in most places but there are still some places where it hasn't been changed. 

1. Do a global search for term "logix" or "Logix" and replace with "circuitVerse" and "CircuitVerse" respectively
2. Make sure whatever you replace is data and database independent otherwise old project will no longer work and database integrity will be effected.

**Comment by agarwalrounak** [comment]
I will work on it

**Comment by armudgal** [comment]
@agarwalrounak sure, waiting for the PR :)

**Comment by agarwalrounak** [comment]
Need a little help on this!

Do we have to replace "logix" with "circuitVerse" wherever the project is named as "logix" or everywhere(including the filenames). I suppose @satu0king meant where the project is still named as ''logix'' or "Logix".

**Comment by armudgal** [comment]
Please move forward with the places where the project is named as variants of 'Logix', updating the filenames right now will lead to a lot of conflict and I would wait for proper tests to setup before changing the files so that we know what we break (if we break).

**Comment by satu0king** [comment]
@armudgal is right. 

I do not think many files have logix in the name. However many messages/constants/strings have them. Over time a lot of it has changed but some parts remain. @agarwalrounak you could probably help us by identifying the places that need to be changed simply by doing a global search for "logix" and "Logix"

**Comment by agarwalrounak** [comment]
Here you can find the files that have to be modified: https://hastebin.com/osawakonos.cpp
Let me know what are the changes that can be done now.

**Comment by armudgal** [comment]
Please go forward with replacing the names of the images for now.
