### ISSUE TITLE
Add the ability to bind keyboard buttons to buttons

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#200]
#### I am submitting a -
* [] **Feature Request**

#### Describe your bug/feature -
Currently, the only way to use your keyboard to control circuits is by using the ASCII keyboard input, which is great, but somewhat limiting, as it only works with ASCII text. Anything that isn't text cannot be used. Binding keyboard buttons to buttons in CircuitVerse would allow us to use non-text keys, such as ctrl, enter, or the arrow keys.

#### Are you working on this issue? (Yes/No)
No.

**Comment by satu0king** [comment]
Interesting idea. I will give some thought and formulate how this can be achieved and update this issue.

**Comment by mehtabhazra1998** [comment]
Hey i want to take up this issue and work on it.
could you please brief me on the problem in a bit more detail. since this is my first time conrtibuting to your org

**Comment by mehtabhazra1998** [comment]
okay @armudgal 
. i want this issue to be assigned to me

**Comment by armudgal** [comment]
@mehtabhazra1998 Sure, once the mappings with the keys are finalised as to what keys will be used for what purposes we can analyze whether we want to go forward with only one issue or break the issue into more than one for different functionalities. Based on that this issue can be assigned to you. Since this might take couple of days, please look into other issues.

**Comment by blane1257** [comment]
armudgal, I think you misunderstood. I wan't to give the user the ability to assign whatever keys they like to buttons, so that the buttons can be pressed using the keyboard as well as the mouse.

**Comment by armudgal** [comment]
@blane1257 Aah, I see. I am sorry I just gave a cursory read to the issue. Thanks for the clarification.

**Comment by mohamedar97** [comment]
so here is how i see this, in the button configuration the user should get an option to assign a keyboard key to activate that button instead of just using the mouse.
if i understood things correctly please let me work on this issue

**Comment by blane1257** [comment]
that is correct!

**Comment by mohamedar97** [comment]
Okay can i work on the issue?

**Comment by blane1257** [comment]
Absolutely!

**Comment by mohamedar97** [comment]
@blane1257  i need your help with something. now i see a lot of variables and objects used but i cant find their definition anywhere, for example 'simulationArea' object is used a lot but i cant find where is it defined

**Comment by blane1257** [comment]
Sorry, I don't know the language. Maybe @fpintos can help.

**Comment by mohamedar97** [comment]
okay thanks @blane1257

**Comment by mohamedar97** [comment]
@armudgal so i'm done with adding this feature but there a problem i'm having that is a little bit awkward.
so i have added a property to the button class "activationKey" which is set to the key that activates this button.
then i added two event listeners to the window "keyup" and "keydown", in keydown i check if 'e.key' matches the activationKey property of any button defined in the globalScope and when it finds it, it changes the wasClicked property to true and then invokes resolve( ),  key up does the opposite to deactivate the key

**Comment by mohamedar97** [comment]
here is the problem i'm having, when either of the events occur all the code in them runs fine except for the "resolve" method, however if i attach the event to the window from the browser console everything works perfectly.
`window.addEventListener('keydown', function (e) {

        // If mouse is focusing on input element, then override any action
        // if($(':focus').length){
        //     return;
        // }
        if (globalScope.Button.length > 0) {
            var i = 0;
            globalScope.Button.forEach(button => {
                if (e.key == button.activationKey) {
                    console.log(button.activationKey)
                    button.wasClicked = true
                    button.resolve()
                    console.log(`activated button ${i + 1}`)
                }
                i = i + 1;
            });


        }`
i have added all these 'console.log' for debugging to make sure everything is fine

**Comment by mohamedar97** [comment]
here is the problem i'm having, when either of the events occur all the code in them runs fine except for the "resolve" method, however if i attach the event to the window from the browser console everything works perfectly.
`window.addEventListener('keydown', function (e) {

        if (globalScope.Button.length > 0) {
            globalScope.Button.forEach((button,index) => {
                if (e.key == button.activationKey) {
                    console.log(button.activationKey)
                    button.wasClicked = true
                    button.resolve()
                    console.log(`activated button ${index + 1}`)
                }
               
            });


        }`
i have added  these 'console.log' for debugging to make sure everything is fine and everything runs fine except the resolve method

**Comment by fpintos** [comment]
I'll venture a guess that you might need to add the button to the simulation queue instead of calling resolve directly.
I can give it a try tomorrow and see if I spot anything else.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mohamedar97** [comment]
i think upon creating an element the is added automatically to the simulation queue, right?
the code runs perfectly when i add the event from the browser console but only the resolve method doesn't work if i add the event in my code editor.
does anyone have an explanation for this?
