### ISSUE TITLE
Incorrect project name while saving the project for offline

### ISSUE THREAD

**Issue by humble-barnacle001** [CircuitVerse/CircuitVerse#2000]
**Describe the bug**
Incorrect project name while saving the project for offline.
> It shows `[object HTMLSpanElement]` instead of project name

**To Reproduce**
1. Go to Simulator
2. Click on save for offline
3. See error

**Expected behavior**
It should show the project name instead of `[object HTMLSpanElement]`

**Screenshots**
![image](https://user-images.githubusercontent.com/58736240/100976826-14fd1a00-3566-11eb-9963-f42362e4b3e6.png)

**Device Information [optional]:**
 - OS: Windows 10 20H2
 - Browser Chrome
 - Version 86

**Additional context**
Probably error in parsing HTML element to text

**Are you working on this issue? (Yes/No)**
No

**Comment by RahulSingh212** [comment]
@humble-barnacle001 I am new to open source and If the issue is still unresolved, I would like to work on it.

**Comment by humble-barnacle001** [comment]
@RahulSingh212 I think this has been resolved in #2026
