### ISSUE TITLE
Dashboard : Blank Space when the User Has all private circuits

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#2001]
**Describe the bug**
When the user has no circuits, there is an indication shown by image that the user does not have any circuits. But if the user creates a new Circuit and Keeps the Project Acces type to be private, Then in that case ( if the user has all the circuits as private ) there is no image shown and the space remains blank.

**To Reproduce**
1. See this Profile https://circuitverse.org/users/59394 . It has only one circuit that too with Private access. If we add more private access projects then the blank space remains.

**Expected behavior**
The same Image with No Circuits Indication Can be displayed.

**Screenshots**
No Circuits : 

![image](https://user-images.githubusercontent.com/42182955/100995390-b8a5f480-357d-11eb-83e3-6462294b648c.png)

All Circuits with Private Access : 
 
From Main User Dashboard :
![image](https://user-images.githubusercontent.com/42182955/100995576-facf3600-357d-11eb-9c7a-cbb91196d6c9.png)

From Other User's End : 

![image](https://user-images.githubusercontent.com/42182955/100995662-18040480-357e-11eb-9566-375aa0a7cda8.png)

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
@satu0king @nitin10s Please have a look at this

**Comment by sarthakm21** [comment]
I want to work on this. The image of the circuit is intended to be displayed for the private circuits as well right? Instead of showing blank space.

**Comment by Palaksharma23** [comment]
is anyone working on this issue ?
i would love to work on this issue .

**Comment by nitin10s** [comment]
I've left a comment on the previous PR. Let's wait for some time for @sarthakm21. If he's unavailable, you may take the issue.

**Comment by pulkit-30** [comment]
Hey @Palaksharma23,
Are you working on this?
