### ISSUE TITLE
Enhance about page

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#2004]
Enhance about page with following details 

Mentors
Core team members 
Alumni
Contributers (as it is)

For inspiration

https://www.rust-lang.org/governance/teams/core
https://rubyonrails.org/community/

**Comment by AkashChetia** [comment]
@tachyons i would like to work on it.

**Comment by satu0king** [comment]
> @tachyons i would like to work on it.
> Edited: I am not sure about the Alumni and Mentors.

@AkashChetia Please go ahead! Check how we hardcore featured page section in the codebase. Please make a similar hardcoding comprising of name, image and link. Create the PR with placeholder names and images. We can later populate the details once the PR is ready :D 

Assume that mentors have 4-5 people.
Core team has 8-10 people. 
Alumni has 4-5 people. 

Hardcoded Featured Examples Page: https://circuitverse.org/examples

**Comment by joshibhaumik** [comment]
@tachyons I would like to work on it. Can you grant me permission to work on this issue?

**Comment by AkashChetia** [comment]
@joshibhaumik  Hi! I am working on it....will shortly generate a PR for it. 🙂

**Comment by devanshmarwaha** [comment]
I would like to work on this. Can you give me permission to work on this issue?

**Comment by Grumpyyash** [comment]
@satu0king I would like to work on this issue if it is still open?

**Comment by anmolkohli13** [comment]
@tachyons I would like to work on this issue if it is still open.
