### ISSUE TITLE
Option to share the circuit designed by the respective user

### ISSUE THREAD

**Issue by iCoder-007** [CircuitVerse/CircuitVerse#2007]
When anyone save the circuit he/she must have an option to share the circuit with read permission only.

I would like to work on the above mentioned project .

**Comment by satu0king** [comment]
@iCoder-007, unless someone is a collaborator, he or she cannot edit the circuit.

**Comment by iCoder-007** [comment]
But let say , i am the owner of the circuit and to share someone the circuit with read only permission

**Comment by satu0king** [comment]
@iCoder-007 we can have a share button but I am not sure what exactly it will do. Right now unless the project is private, you can just share the URL of the project with your friend

**Comment by iCoder-007** [comment]
Ya we can a share option were the user can share the circuit as image or something like that

**Comment by satu0king** [comment]
@iCoder-007 if u just want to share the circuit as an image, just download it and share? Tools -> Download Image

**Comment by iCoder-007** [comment]
ok ,sorry i didn't saw that option
