### ISSUE TITLE
Rotate circuit element with keyboard shortcut

### ISSUE THREAD

**Issue by Kartik1397** [CircuitVerse/CircuitVerse#2018]
**Describe the solution you'd like**
Select element from CIRCUIT ELEMENT panel
Press R to change the direction of the element by 90deg clockwise.

**Are you working on this? (Yes/No)**
Discussion required.

**Comment by legendsovermyths** [comment]
Hey can I work on this?

**Comment by satu0king** [comment]
@Kartik1397 u can set whatever shortcut u want in Tools->Custom Shortcut

**Comment by Kartik1397** [comment]
Sorry, my bad
