### ISSUE TITLE
Offline save not working as desired.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#2026]
**Describe the bug**
Successfully saving the project gives a message showing which is a hint to where this probably is going wrong.
when you save the project to your local object it is saved with key "undefined" as compared to earlier when it was saved with projectId as key.

![img](https://files.slack.com/files-pri/TJTJJ6R1A-F01HE4ZK5AL/image.png)

**To Reproduce**
1. Go to 'circuitverse.org/simulator'
2. Make something
3. Try to save offline
4. See error as weird success message and in local storage > ProjectList > data with key as "undefined".

**Expected behavior**

**Screenshots**

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by dipanshparmar** [comment]
Working!

**Comment by satu0king** [comment]
@dipanshparmar, this issue is not the same one you fixed. Please check this issue carefully.

**Comment by dipanshparmar** [comment]
Sure @satu0king

**Comment by dipanshparmar** [comment]
@satu0king I'm no longer working on this issue because my industrial training is starting from today up to 31 Jan. So I'm busy between this time span. I'm sorry for the inconvenience. If anyone wants to take this issue then please go ahead and if no one takes this issue till 31st of Jan then I'll make a PR for this after 31 Jan. Thanks

**Comment by raffayatiq** [comment]
Hello. I would like to work on this issue. However, I am not sure what code is handling the Save Offline functionality. This is the HTML for the Save Offline button inside the canvas: 
![image](https://user-images.githubusercontent.com/58357644/103442317-e5315700-4c76-11eb-91b6-85b4e83d17ef.png)
And this is HTML for the Save Offline link when you click on "Projects" top-left on the File menu:
![image](https://user-images.githubusercontent.com/58357644/103442334-1873e600-4c77-11eb-88c5-ff18e726f070.png)
Can anyone guide me on what code is being linked to these two elements and how is it being linked? Is it through the id="saveOffline"? Is the save to the local storage being handled by a Rails Controller or through JavaScript? If so, what file is handling it? I am searching for it in the source code but I am somewhat lost. Any guidance would be appreciated!

**Comment by dipanshparmar** [comment]
Hey @raffayatiq,
The save offline functionality is implemented using javaScript (Local Storage). These are the code sections that are probably handling this functionality:

**File Location**: public/js/**data.js**
![image](https://user-images.githubusercontent.com/49204837/103450464-d7162180-4cdc-11eb-8415-e3239a59f1a0.png)

**File Location**: public/src/data/**project.js**
![image](https://user-images.githubusercontent.com/49204837/103450470-fad96780-4cdc-11eb-8e84-a16154ba14f8.png)

**Comment by shubhankarsharma00** [comment]
yes the first snippet is the latest code and the second one is the legacy code. We want the save to work in the new simulator same as it did before and I'm not sure what the issue is.

**Comment by raffayatiq** [comment]
It seems like the second snippet is the one being used. I am trying to edit the public/src/data/project.js file, but the changes are not being reflected in the browser. This is what I edited:
![image](https://user-images.githubusercontent.com/58357644/103467900-89012c80-4d75-11eb-9d80-e1604ca99838.png)
And this is what's being loaded by the browser:
![image](https://user-images.githubusercontent.com/58357644/103467911-9a4a3900-4d75-11eb-8fdf-9a2e3f9d8bea.png)
What can I do to make the changes reflect?

**Comment by ZadeAbhishek** [comment]
Hey @satu0king @shubhankarsharma00 I have fixed this bug i guess this was the desired result tell if 
![Screenshot from 2021-01-08 02-03-31](https://user-images.githubusercontent.com/66520848/103984778-c0951d80-5155-11eb-963f-5a525d9cfcc8.png)

**Comment by dipanshparmar** [comment]
@ZadeAbhishek this issue is already solved at #2008. The issue here is the project is saving with the undefined key in the local storage instead of the project id.

**Screenshot**
![image](https://user-images.githubusercontent.com/49204837/104082577-5ff10800-525d-11eb-9b5a-1b60b902706c.png)

**Comment by ZadeAbhishek** [comment]
okay got it

**Comment by raffayatiq** [comment]
Sorry for creating two pull requests. I made a mistake in the first one. The issue seems to be fixed now. @satu0king @shubhankarsharma00, please let me know if I have overlooked anything. Thank you!
