### ISSUE TITLE
ROM size increase

### ISSUE THREAD

**Issue by seinos** [CircuitVerse/CircuitVerse#2033]
**Is your feature request related to a problem? Please describe.**
I would like to use the ROM but i need an input of 5 and an output of 9 Bit.

**Describe the solution you'd like**
I would like to be able to set the ROM input and output size using the properties panel.

**Describe alternatives you've considered**
I could use a multiplexer to increase the input but I have no idea how to increase the output.

**Additional context**
-

**Are you working on this? (Yes/No)**
No

**Comment by satu0king** [comment]
@seinos can you use EEPROM for this?

**Comment by seinos** [comment]
@satu0king Thanks looks promising. If not I think I could try to use the multiplexer implementation of the control I want to realize. By the way I took a look in the docs and I think the example of the EEPROM in the docs is broken (Bit width error 8 and 7) and RAM as well.
Thanks for the quick answer and for the free open source tool which all in all is simple to use and a lot of fun to play with.

**Comment by satu0king** [comment]
@seinos, thanks for reporting, I fixed the documentatin circuits.

**Comment by seinos** [comment]
Thanks and thank you for the fast reply.
