### ISSUE TITLE
Circuits invisible on Gitpod

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#2040]
**Describe the bug**
On setting up CircuitVerse through Gitpod, I saw that circuits on home page under Editor's Pick and Recent Circuits were not visible.

**To Reproduce**
1. Go to SETUP.md
2. Follow Gitpod instructions to set up CircuitVerse
3. On successful setup, open the preview in browser
4. Scroll down to see error on homepage

**Expected behavior**
Circuits should be visible as this might cause confusion to young users who are getting started with the platform

**Screenshots**
![image](https://user-images.githubusercontent.com/43600306/102176508-8a061300-3ec7-11eb-9ec1-375e42024bea.png)

**Device Information [optional]:**
 - OS: Windows
 - Browser: Microsoft Edge

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by shubhankarsharma00** [comment]
I think this is because `rails db:seed` is not run and so there are no circuits available ?

**Comment by ghoshdipan** [comment]
What is the issue? Can anyone explain?

**Comment by shadowoflight** [comment]
I am using Gitpod as well, the recent circuits are being shown in the preview. 
Browser: Chrome
OS: Mac OS

**Comment by DevanshD3** [comment]
I think it's because some circuits are hardcoded (in the featured section) by the team and if you want to see your recent circuits, you need to make your own, and then it will be shown there. @tachyons could you please confirm ?

**Comment by tachyons** [comment]
Gitpod creates a fresh setup, so there won't be any circuits in the recent circuits section, you create new circuits to get items in recent circuits section, also there is an option to set a circuit as featured
