### ISSUE TITLE
Zoom In Zoom Out not working in Circuit Preview

### ISSUE THREAD

**Issue by MegaMind77-coder** [CircuitVerse/CircuitVerse#2042]
**Describe the bug**
Zoom In Zoom Out Buttons not working after Selecting preview Circuit option

**To Reproduce**
1. Go to any circuit from your dashboard
2. Click on Preview Circuit option from the Projects dropdown.
3. Try to zoom in or zoom out from the Timing diagram control panel provided. 
4. It is not functional

**Expected behavior**
Zoom In Zoom out should work in Full circuit preview.

**Screenshots**
![Screenshot from 2020-12-16 12-06-56](https://user-images.githubusercontent.com/42925218/102313766-3d8a0880-3f97-11eb-904e-fe96a314d58d.png)

**Device Information [optional]:**
 - OS: [Ubuntu 18.04]
 - Browser [Chrome]
 - Version [26+]

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
The Zoom in and Zoom out button in the Timing Diagram Panel is used to control the Timing Digram specifically and not the circuit. To zoom in and out the circuit, the user can make use of Scroll up and down in the Preview Mode. While in the Embed Mode we have respecrive buttons to perform the same action .

**Comment by MegaMind77-coder** [comment]
@Shivansh2407 could you share how the Timing Diagram is controlled by the zoom-in and out buttons? 

Scroll Works Perfectly fine.

**Comment by Shivansh2407** [comment]
You can fork this circuit and try out various functions. Also you can ask related questions on the CV forum or slack channel, we will be happy to answer them as soon as possible.
Circuit Link : https://circuitverse.org/users/3/projects/timing-diagram-test

Closing this issue 👍
