### ISSUE TITLE
Showing date/time of creation and last modification of a circuit

### ISSUE THREAD

**Issue by r-arvind** [CircuitVerse/CircuitVerse#2047]
**Is your feature request related to a problem? Please describe.**
When I look at a circuit, it would be really helpful to see when the circuit was created and when it was last modified.

**Describe the solution you'd like**
Display `Date created` and `Date Modified` below the circuit description

**Describe alternatives you've considered**
The best estimate of date-time I could make was by using the timestamps of the comments. But it's not always helpful.

**Are you working on this? (Yes/No)**
No

**Comment by shubhankarsharma00** [comment]
hmm should be an easy feature to add. Created_at and Updated_at is already a part of schema. 
https://github.com/CircuitVerse/CircuitVerse/blob/129182c0f422c9482abe149f730e03292ec1a7ef/db/schema.rb#L281-L282

**Comment by Cronus1007** [comment]
@ShubhankarKG Let me implement this one then.

**Comment by shubhankarsharma00** [comment]
@Cronus1007 you tagged the wrong guy I guess, but yeah go ahead.

**Comment by silentC1C4D4** [comment]
Is this issue still open? @Shivansh2407
