### ISSUE TITLE
Link to Code of Conduct is not working

### ISSUE THREAD

**Issue by sanctophagus** [CircuitVerse/CircuitVerse#205]
Commit: fc55b0ac2a844c1bb5b3e8d2047545860c4c1cb9 changed the name of file `CODE OF CONDUCT.md` to `code-of-conduct.md` which broke the link between `README.md` and `code of conduct`.

**Comment by agarwalrounak** [comment]
Nice catch!

**Comment by armudgal** [comment]
Thanks for this, the cause of the bug would be me :P
