### ISSUE TITLE
Assigning Roles to Members of a group

### ISSUE THREAD

**Issue by r-arvind** [CircuitVerse/CircuitVerse#2050]
**Is your feature request related to a problem? Please describe.**
In Circuitverse for Teachers, only the user who created the group can make new assignments and grade them. This is a problem when working in teams. For example, when a faculty/teacher creates an assignment, the grading is done by a team of TAs (Teaching Assistants). Therefore, the teacher should be able to add other members who have the ability to create and grade the assignments.  

**Describe the solution you'd like**
In a group, the members should have different roles like `owner`, `moderator` or `member` and these roles should have different levels of permission. The owner can do anything with the group (rename it, edit it, delete it). Moderators should only be able to create assignments and grade them. The members can only see the assignments and submit them.

**Are you working on this? (Yes/No)**
No

**Comment by gr455** [comment]
@satu0king @tachyons, this will require the the roles to be added in the `group_member` model. So for existing groups it will be required to set the 'owner / mentor' in `group_member` instead of `group`. How do we handle that? Do we write a rake task for that?

**Comment by tachyons** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/1682 related

**Comment by gr455** [comment]
> #1682 related

I will try to build on those PRs
