### ISSUE TITLE
Export Circuits as GIFs

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#2065]
**Is your feature request related to a problem? Please describe.**
At the moment, we have the option to download the circuits as images ( PNGs, JPEGs, etc ). Some users prefer to have the option to share their circuits as GIFs. This requires an external tool.

**Describe the solution you'd like**
To help with this we can have an inbuilt GIF exporter making it easy for users to share their circuits with others.

**TODO**
- We already have a menu for Downloading Images in ```Tools > Download Image```. There is also a GIF button which currently downloads PNG.
- We have to add the feature to create a GIF.
- Add the option to start and stop the recording for the GIF
- Add option to Download GIF

**Are you working on this? (Yes/No)**
No

**Comment by ishandeveloper** [comment]
I might be able to work on this. Can you explain a bit more about "Add the option to start and stop the recording for the GIF" ?

What do we want to animate in the gif, should there be a seek bar or something else, etc?

**Comment by arnab15** [comment]
hello,
I have knowledge of javascript ,nodejs,reactjs,expressjs, Mongodb but I haven't contributed to any open-source project so I'm a beginner.I would like to contribute to this project.
how should I start can anyone suggest to me the way should I start contributing.

**Comment by ZadeAbhishek** [comment]
@sal2701 
my idea is if any body wants to save the circuit as GIF the animated part would be the input vs output.
so for external tools to save as GIF we can use "gifshot" library. 
https://yahoo.github.io/gifshot/ 
can i help you with this feature ?

**Comment by sal2701** [comment]
Since the circuit outputs change based on the inputs & the clock cycle, users might want to record it for multiple cycles or even for given seconds. So I feel what we need is a proper way to facilitate this. Yeah a seek bar might make it easier.

@ishandeveloper interested in this issue?

Hey @arnab15 good you want to contribute here. I suggest that you first setup CircuitVerse and use the simulator, it will give you a better idea of the platform & issues as well.

@ZadeAbhishek I will let you know if no one else is working on this issue. Feel free to try out other issues

**Comment by ZadeAbhishek** [comment]
yes sure

**Comment by ishandeveloper** [comment]
Thanks @sal2701 . Thanks for offering me the chance to work on this, however something came up and I might be busy for next few weeks. You can move forward and assign this to @ZadeAbhishek , meanwhile I'll be keeping an eye out for other issues, once I'm free : )

**Comment by sal2701** [comment]
@ishandeveloper no issues. @ZadeAbhishek you can take this up. gifshot sounds good. Let me know if you've any doubts.

**Comment by ZadeAbhishek** [comment]
yes

**Comment by syedobaid45git** [comment]
Hey would you please guide me to setup circuitverses

**Comment by syedobaid45git** [comment]
I want this issue to be fixed but unable to setup the circuitverses

**Comment by syedobaid45git** [comment]
> Hey would you please guide me to setup circuitverses

**Comment by ZadeAbhishek** [comment]
> Hey would you please guide me to setup circuitverses

read setup.md will help you to setup

**Comment by ZadeAbhishek** [comment]
https://user-images.githubusercontent.com/66520848/104838764-06cf4700-58e3-11eb-962c-ee9480185f01.mp4

hey @sal2701 gifshot is intergrated as shown in above video now we can save image as GIF in chrome and firefox i have not tested for all but in gifshot docs its is given that it supports all brouser.But problem is as  said  earlier we need seek bar implementation but not able to do  can you give any suggestion i am also finding.

**Comment by syedobaid45git** [comment]
Hey @ZadeAbhishek could I get your mail Id please.i have some doubts and question that I want to get cleared by you

**Comment by syedobaid45git** [comment]
> 
> 
> 
> https://user-images.githubusercontent.com/66520848/104838764-06cf4700-58e3-11eb-962c-ee9480185f01.mp4
> 
> hey @sal2701 gifshot is intergrated as shown in above video now we can save image as GIF in chrome and firefox i have not tested for all but in gifshot docs its is given that it supports all brouser.But problem is as  said  earlier we need seek bar implementation but not able to do  can you give any suggestion i am also finding.

    Hey, I need some source to contact with you . Just needed help for open source, would you please give your email id

**Comment by ZadeAbhishek** [comment]
> > GIFSHOT.INTRI.mp4
> >     
> >   
> > 
> >   
> > 
> >   
> > 
> > 
> > hey @sal2701 gifshot is intergrated as shown in above video now we can save image as GIF in chrome and firefox i have not tested for all but in gifshot docs its is given that it supports all brouser.But problem is as  said  earlier we need seek bar implementation but not able to do  can you give any suggestion i am also finding.
> 
> ```
> Hey, I need some source to contact with you . Just needed help for open source, would you please give your email id
> ```

zabhidoc@gmail.com

**Comment by syedobaid45git** [comment]
> > > GIFSHOT.INTRI.mp4
> > >     
> > >   
> > > 
> > >   
> > > 
> > >   
> > > 
> > > 
> > > hey @sal2701 gifshot is intergrated as shown in above video now we can save image as GIF in chrome and firefox i have not tested for all but in gifshot docs its is given that it supports all brouser.But problem is as  said  earlier we need seek bar implementation but not able to do  can you give any suggestion i am also finding.
> > 
> > ```
> > Hey, I need some source to contact with you . Just needed help for open source, would you please give your email id
> > ```
> 
> zabhidoc@gmail.com 

Hi @ZadeAbhishek I have sent you so many emails with my mail I'd syedobaidali453@gmail.com . Please respond to my mail please

**Comment by syedobaid45git** [comment]
> > > > GIFSHOT.INTRI.mp4
> > > >     
> > > >   
> > > > 
> > > >   
> > > > 
> > > >   
> > > > 
> > > > 
> > > > hey @sal2701 gifshot is intergrated as shown in above video now we can save image as GIF in chrome and firefox i have not tested for all but in gifshot docs its is given that it supports all brouser.But problem is as  said  earlier we need seek bar implementation but not able to do  can you give any suggestion i am also finding.
> > > 
> > > ```
> > > Hey, I need some source to contact with you . Just needed help for open source, would you please give your email id
> > > ```
> > 
> > zabhidoc@gmail.com 
> 
> Hi @ZadeAbhishek I have sent you so many emails with my mail I'd syedobaidali453@gmail.com . Please respond to my mail please 

Bro I read your mails, thanks for your advice. I wanted to know which js framework should I start learning to start contributing in circuitverses. Pls

**Comment by ZadeAbhishek** [comment]
@sal2701  hey i success fully add GIF feature here is the video  please check what to do next ?

https://user-images.githubusercontent.com/66520848/106264963-6109c980-624c-11eb-8943-a19cd0c7d3e4.mp4

**Comment by ZadeAbhishek** [comment]
> > > > > GIFSHOT.INTRI.mp4
> > > > > hey @sal2701 gifshot is intergrated as shown in above video now we can save image as GIF in chrome and firefox i have not tested for all but in gifshot docs its is given that it supports all brouser.But problem is as  said  earlier we need seek bar implementation but not able to do  can you give any suggestion i am also finding.
> > > > 
> > > > 
> > > > ```
> > > > Hey, I need some source to contact with you . Just needed help for open source, would you please give your email id
> > > > ```
> > > 
> > > 
> > > [zabhidoc@gmail.com](mailto:zabhidoc@gmail.com)
> > 
> > 
> > Hi @ZadeAbhishek I have sent you so many emails with my mail I'd [syedobaidali453@gmail.com](mailto:syedobaidali453@gmail.com) . Please respond to my mail please
> 
> Bro I read your mails, thanks for your advice. I wanted to know which js framework should I start learning to start contributing in circuitverses. Pls

as such i don't know much about javascript  i am not pro but start j query library is will help you to ease work

**Comment by ZadeAbhishek** [comment]
@sal2701 can you help me i have created pull request know what to do can you help me

**Comment by ShreyaPrasad1209** [comment]
This issue has been resolved so I'm closing it.
