### ISSUE TITLE
Search filtering/ordering

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#208]
In response to the search engine improvements, I have a few suggestions to add.

- [ ] **Search filtering**
Filtering results by tags, users, number of views, or submissions over a certain period of time (this day, week, month, e.t.c)

- [ ] **Search ordering**
Ordering search results by number of stars, views or comments.

- [ ] **Searching without keywords**
The ability to make search queries without having to use keywords (for finding top viewed circuits, most commented circuits, circuits submitted this week, e.t.c)

**Comment by agarwalrounak** [comment]
If this is to be worked upon now, then I would like to work on Search ordering.

**Comment by ankitkataria** [comment]
Related to #21, @agarwalrounak I feel filters can be worked on once the actual search is ready.  Since the original issue is tagged with 'Future' and this also happens to be a GSoC project. I have a feeling we are supposed to present our proposals now and eventually work on them during the summers.

**Comment by ciphereck** [comment]
@tachyons we can close this issue since #319 fixed the issue #21 
And this issue is the same as #21
