### ISSUE TITLE
Circuit not loading

### ISSUE THREAD

**Issue by jvilaplana** [CircuitVerse/CircuitVerse#2084]
**Describe the bug**
When opening an assignment submission, the circuit is stuck at the loading spinner and several errors keep popping in the debug console.

**To Reproduce**
No clear steps to reproduce it. This error is showing in one of the submissions to one of my assignments. The author of the circuit experiences the same issue when trying to open it in their simulator.

**Expected behavior**
To be able to open and interact with the circuit.

**Screenshots**
![Screenshot 2021-01-20 at 21 14 27](https://user-images.githubusercontent.com/732164/105229603-7ef86f80-5b64-11eb-9d77-38c775a79ada.png)

**Device Information [optional]:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 87

**Additional context**
-

**Are you working on this issue? (Yes/No)**
No.

**Comment by shubhankarsharma00** [comment]
@jvilaplana This seems like a project-specific bug. Can you share the link of the project so I can have a look at why this bug originated.

**Comment by jvilaplana** [comment]
@shubhankarsharma00 it's a private project, the link is:

https://circuitverse.org/simulator/edit/practica-2-4c823a80-81ca-41e4-bda3-b9e6086ad6be

**Comment by shubhankarsharma00** [comment]
Oh, I wouldn't be able to help you if it's private. This may be a bug that happens sometimes when some input or output was deleted from one of the subcircuits but that change wasn't saved properly and is not reflected in the circuits that the subcircuit was included in. Maybe try changing included subcircuits.

**Comment by jvilaplana** [comment]
@shubhankarsharma00 I've forked the original project from the student and changed it to public, this should work for you now:

https://circuitverse.org/simulator/edit/practica-2-5bb094a5-74ba-4361-8669-e55790ad7872

I can't navigate through the different circuits to try to check your solution. Thank you!

**Comment by shubhankarsharma00** [comment]
@jvilaplana can u share the project link? You can get it from the projects page. It'll be like this: https://circuitverse.org/users/64636/projects/7-segment-082ca31a-2003-4013-b9d8-106acc9ab108

**Comment by jvilaplana** [comment]
@shubhankarsharma00 Sure, it should be this one: https://circuitverse.org/users/42748/projects/practica-2-5bb094a5-74ba-4361-8669-e55790ad7872

**Comment by shubhankarsharma00** [comment]
https://circuitverse.org/users/3642/projects/practica-2-d0688787-d216-4534-9e90-714b3e64ad33 check this out @jvilaplana . I am not sure if I have recovered the complete project but it is probably some state of it I hope. You can Fork this and continue working.

**Comment by jvilaplana** [comment]
Perfect, thank you @shubhankarsharma00 ! 😄
