### ISSUE TITLE
Issue while setting up the project using docker-compose up

### ISSUE THREAD

**Issue by pushpendrahpx** [CircuitVerse/CircuitVerse#2090]
**Describe the bug**
The docker images named "circuitverse_web" and "circuitverse_webpacker" are not runnning as expected, they are throwing error 
1. Error From "circuitverse_web" image in docker is like this given below
``` web_1        | standard_init_linux.go:219: exec user process caused: no such file or directory```
```  circuitverse_web_1 exited with code 1 ```
2. Error From "circuitverse_webpacker: image in docker is like this given below
``` webpacker_1  | /usr/bin/env: 'ruby\r': No such file or directory ```
```  circuitverse_webpacker_1 exited with code 127 ```

So, am I the only one facing the issue or other people as well ? 

Please Help me regarding this! 

Thank You

**Comment by gr455** [comment]
Hey, are you using Windows to build? Also which branch are you trying to build?

**Comment by Pushpendrahpx** [comment]
> Hey, are you using Windows to build? Also which branch are you trying to build?

Yes I am using windows I think this issue is due this only

**Comment by Pushpendrahpx** [comment]
> Hey, are you using Windows to build? Also which branch are you trying to build?

It seems it is the issue in windows due to some due to '\r' return character in cmd. It is working fine in Linux.

**Comment by Gieted** [comment]
Why have you closed this issue? The problem still persists, the main branch cannot be build on Windows.

**Comment by gr455** [comment]
> Why have you closed this issue? The problem still persists, the main branch cannot be build on Windows.

You can fix it by changing the end of line(EOL) from `\r\n` (CRLF) to `\n` (LF) in `bin/docker_run` and `bin/docker_webpacker_run`

refer: https://stackoverflow.com/a/52665687

Sorry for this, we'll try to figure out a way to fix this. Until then you can fix it like above

**Comment by Gieted** [comment]
Couldn't you just use `.gitattributes` file as described [here](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings)?

**Comment by gr455** [comment]
> Couldn't you just use `.gitattributes` file as described [here](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings)?

Yes we'll do that. Thanks!

**Comment by gr455** [comment]
@Gieted Sorry for being late. Can you try out [this](https://github.com/gr455/CircuitVerse/tree/crlf-fix-docker) branch. I am not sure if I have done this right

Thanks

**Comment by Gieted** [comment]
Nope, it's not working. Dot is probably not supported by git patterns, just do it like this instead:
```
# All files in bin/ should use LF
bin/** text eol=lf
```

**Comment by gr455** [comment]
> Nope, it's not working. Dot is probably not supported by git patterns, just do it like this instead:
> ```
> # All files in bin/ should use LF
> bin/** text eol=lf
> ```

Will try this. Thanks a lot!

**Comment by gr455** [comment]
> Nope, it's not working. Dot is probably not supported by git patterns, just do it like this instead:
> 
> ```
> # All files in bin/ should use LF
> bin/** text eol=lf
> ```

I have updated the [branch](https://github.com/gr455/CircuitVerse/tree/crlf-fix-docker) with this change. Can you please confirm if it works?

**Comment by Gieted** [comment]
Yes, now it works 👍.

**Comment by gr455** [comment]
> Yes, now it works 👍.

Great! Thank you for helping with this
