### ISSUE TITLE
Making Changes to Dashboard Page of User

### ISSUE THREAD

**Issue by pushpendrahpx** [CircuitVerse/CircuitVerse#2091]
**Is your feature request related to a problem? Please describe.**
No, this is not the problem, but when we click on Dashboard it actually takes us to user profile page, so it seems like there is no dashboard page there.

**Describe the solution you'd like**
Designing and Implementation of Dashboard will give user's a better user experience, and people can see there recent Circuits and many more features can be implemented there so that users can have a feel of better user experience at CircuitVerse.

**Describe alternatives you've considered**
Currently as of now when we click on Dashboard it takes us to 
``` https://circuitverse.org/users/<user-id> ``` this profile page, but profile page and dashboard should remain seperate

**Additional context**
So I would Like to work on this, new Dashboard Page Development, so is it possible ?
 
**Are you working on this? (Yes/No)**
Yes I would like to work on this.

So Should I start with this *new feature* ?

**Comment by satu0king** [comment]
CC: @aayush-05 @nitin10s 

We actually had it separate initially and then we integrated it.

**Comment by Grumpyyash** [comment]
No, I have not added any circuits as such but what I have done is that I have seperated the user page for just information regarding them and made dashboard for circuits and other stuff as mentioned in the issue

**Comment by nitin10s** [comment]
Yes, we integrated it essentially so that users can have a holistic view of people's profiles when they visited them. Info about people + their circuits, fav circuits, etc. That is a sort of a dashboard itself.

**Comment by Grumpyyash** [comment]
Yes, it definitely makes sense, I just tried implementing it when I saw an issue regarding this.

**Comment by satu0king** [comment]
Closing this issue for now
