### ISSUE TITLE
Renaming "Resume Timing Diagram" and "Pause Timing Diagram" button tooltips in the TIMING DIAGRAM panel as they are misleading

### ISSUE THREAD

**Issue by arjunagarwal899** [CircuitVerse/CircuitVerse#2095]
**Describe the bug**
The "Resume Timing Diagram" and "Pause Timing Diagram" button tooltips are confusing as they do not actually pause the timing diagram from recording the values but just pause the autoscrolling. The code itself indicates that it is only for controlling the autoscrolling of the diagram.

**To Reproduce**
1. Open any circuit with a Flag component
2. Click on 'Timing Diagram'
3. Hover over the last two buttons, click on them once the diagram starts to scroll on it's own
4. Observe the tooltips, they do not match the functionality provided by the buttons

**Screenshots**
![image](https://user-images.githubusercontent.com/31124126/106142996-2e05fe00-6198-11eb-883e-1640f27789cb.png)
![image](https://user-images.githubusercontent.com/31124126/106143049-4413be80-6198-11eb-95bb-0bda4314db5a.png)

**Additional context**
Solution: Rename the tooltips to "Resume auto-scroll" and "Pause auto-scroll" respectively.

**Are you working on this issue? (Yes/No)**
Yes, I would like to

Please let me know if I can work on this issue. I think it is a good first issue to become a contributor. (This is my first foray into open-source contribution)

**Comment by beverleyokogwu** [comment]
May I take this issue?

**Comment by dineshkumar12004** [comment]
hey can i work on this ?

**Comment by Prerna-0202** [comment]
I would like to work on this issue.
Is anyone working on this issue?
