### ISSUE TITLE
Search Engine

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#21]
Currently we are using google custom search which doesn't do a very good job. The search should search over project names and descriptions.

**Comment by garry329** [comment]
I would like to work on this issue.

**Comment by armudgal** [comment]
@garry329, please go forward with this.

**Comment by armudgal** [comment]
@garry329, please go forward with this.

**Comment by satu0king** [comment]
@garry329 do check various options and revert back to us.

**Comment by ankitkataria** [comment]
There are multiple options we have here, one is implementing a normal query-based search along with proper indexing. If we are going that way we can use [EXPLAIN](https://robots.thoughtbot.com/reading-an-explain-analyze-query-plan) queries to analyse and tweak the index. I've seen such searches doing very well previously. 
I'm guessing there will be considerable experimentation required for this, and this also happens to be a GSoC task. :stuck_out_tongue:

**Comment by shubhankarsharma00** [comment]
@ankitkataria we can also use elasticsearch-ruby (as specified in wiki page/projetcs) or [Chewy gem](https://github.com/toptal/chewy). Elastic-search has inbuild Explain API.

**Comment by ankitkataria** [comment]
Yes, that is also one way to go. But I'm not a personal fan of adding
dependencies if it's possible to replicate one from scratch. We can
probably try both and weigh the differences.

**Comment by garry329** [comment]
@satu0king i have looked into this and i also saw that we are using postgres db in production so i think postgres's full text search is a very good option for us.it has:
-search rankings(getting more relevant results)
-support for searching entire phrases(which is an important usecase for us)
-fuzzy search(searching through misspellings)
It is much lighter than something like elasticsearch or SOLR.
And also there is a gem for it called pg_search. Does this sound ok?

**Comment by jbox144** [comment]
Could I also get a tool to order by views and stars, or stars over a certain period of time?

**Comment by armudgal** [comment]
@jbox144 Sure you can, waiting for a feature request in seperate Issue :)

**Comment by armudgal** [comment]
@tachyons Can you go through this once. Thanks :)

**Comment by tachyons** [comment]
I believe postgres full text search is enough for our use case in our scale. If a dedicated search engine is necessary then ES is the way to go I recommend https://github.com/ankane/searchkick. It is easy to work with and have good integration with rails

**Comment by garry329** [comment]
Ok, thanks @tachyons .So i'll go ahead with posgres full text search.

**Comment by garry329** [comment]
![screenshot 2019-03-06 at 11 38 50 pm](https://user-images.githubusercontent.com/20072704/53903237-38c9be00-4069-11e9-90a0-c4a275970bca.png)
@satu0king , can you please give me feedback on this single project search result?

**Comment by garry329** [comment]
So i have implemented a basic search functionality(full text search using pg_search).What should i do next?
@satu0king @armudgal @tachyons 
![search](https://user-images.githubusercontent.com/20072704/53936217-25e9d480-40cf-11e9-88ca-63f1d31bf49f.gif)

**Comment by armudgal** [comment]
Can you please send a PR so that we can test it and review it. Thanks

**Comment by garry329** [comment]
@armudgal Done.

**Comment by satu0king** [comment]
> ![screenshot 2019-03-06 at 11 38 50 pm](https://user-images.githubusercontent.com/20072704/53903237-38c9be00-4069-11e9-90a0-c4a275970bca.png)
> @satu0king , can you please give me feedback on this single project search result?

Looks great! It would be good if you can also show number of stars and views. If not we can do that in a later issue.

**Comment by jbox144** [comment]
> Looks great! It would be good if you can also show number of stars and views. If not we can do that in a later issue.

I agree, showing the number of stars and views would be handy
