### ISSUE TITLE
Bug: Counter component resets when wires are added/removed

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#211]
Whenever wires connected to the counter component are added, removed or updated, the counter component reset's it's value. This is a bit of a nuisance.

**Comment by Oghenebrume50** [comment]
Hi, @jbox144 could you please be more descriptive with this issue, I would like to work on it, but I understand it clearly.

**Comment by ankur54** [comment]
@jbox144 Please post the link to the circuit diagram you are facing problem in. That would help a lot.

**Comment by fpintos** [comment]
This is an odd one...I see the value of the counter reset to zero but I don't see the lines that do that being called...maybe calling the field "value" is causing conflict with something else I might have missed?

**Comment by fpintos** [comment]
I spoke too soon...bug is in this line in Counter.prototype.resolve:
```js
var outputValue = this.output.value || 0;
```

It should be simply:
```js
var outputValue = this.value;
```

**Comment by fpintos** [comment]
I'll send a fix for this.
