### ISSUE TITLE
navbar 

### ISSUE THREAD

**Issue by srishty-07** [CircuitVerse/CircuitVerse#2117]
Last semester due to the pandemic we were making circuits on  circuit verse , it was really very helpful .In pc's when we do work on circuit work it is very easy to work with ,but sometimes some people who want to do it on phones or smaller devices it becomes very difficult for them many of my classmates also find that issue. 
![image](https://user-images.githubusercontent.com/70388131/108344453-28ce2900-7203-11eb-9397-fceed844c09b.png)
As shown in above image the navbar is very easy to use at
but in phone the navbar is hiding the content and also the content is not visible as shown below.
![cv](https://user-images.githubusercontent.com/70388131/108344010-a0e81f00-7202-11eb-9f5c-d05fc43463ca.jpg)
So if the mentors find this issue feasible I will be really grateful if you assign me with the styling of navbar and other divs also.

**Comment by SaDevat** [comment]
I think this is already being addressed in issue #2108 https://github.com/CircuitVerse/CircuitVerse/issues/2108

**Comment by ashutosh264** [comment]
Is this issue still open?

**Comment by ShreyaPrasad1209** [comment]
This issue is being worked on as part of our GSoC project - Compatibility with Touch Devices. I will close this issue.
