### ISSUE TITLE
RAM should save it's values

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#212]
RAM components are really handy for storing a lot of data, which is why I think they should also be able to save it's values with the project. Hopefully this isn't a big ask.

**Comment by blane1257** [comment]
This is exactly what I've been asking for with my writable ROM #117 

A writable ROM, or a RAM which saves its contents.

**Comment by satu0king** [comment]
> RAM components are really handy for storing a lot of data, which is why I think they should also be able to save it's values with the project. Hopefully this isn't a big ask.

It is not actually difficult but as @fpintos pointed out it is functionally wrong for a RAM to persist values. Once the DMA is implemented we can achieve this functionality by saving data into some other module, maybe disk? and then loading of from the said module back into RAM during startup.

**Comment by fpintos** [comment]
I'll write the EPROM this weekend.

**Comment by ankur54** [comment]
Hi everyone. I am new here. I have a fair amount of knowledge about C++, Java and some experience in python. If this issue is open can I start working on it?

**Comment by blane1257** [comment]
I believe fpintos is working on this.

**Comment by armudgal** [comment]
@fpintos Hi there, can you confirm whether you are working on it. We can block this issue then.

**Comment by fpintos** [comment]
Yeah, I'll work on it.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
