### ISSUE TITLE
Minor UI Enhancements in Simulator

### ISSUE THREAD

**Issue by manjotsidhu** [CircuitVerse/CircuitVerse#2125]
**Describe the bug**
There are some minor UI/UX enhancements that can be done while while using simulator.

1. There is a 1-2 px gap between the arrows of the expandable section in circuit elements.
![image](https://user-images.githubusercontent.com/22657113/109112260-56195a80-7760-11eb-975b-2fd12f0b1eee.png)

2. "Report an Issue" icon is off-centered.
![image](https://user-images.githubusercontent.com/22657113/109112298-6a5d5780-7760-11eb-891a-44c8dbc8fba0.png)

3. When panels are expanded, the maximize button cursor on hover changes to move from pointer.

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator'

**Device Information [optional]:**
 - OS: Windows x64 20H2 (WSL v2)
 - Browser: Google Chrome
 - Version: 88

**Are you working on this issue? (Yes/No)**
Yes

**Comment by dhiru9599** [comment]
I want to work on this, can I?
