### ISSUE TITLE
Improve Webpacker Configuration

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#2128]
1. Remove duplicate jquery import
1. Move jquery ui to webpacker
1. Add canvas2svg to the bundle
1. Add webpack analyser plugin
1. Move webpack dir to simulator

Reference PR: https://github.com/CircuitVerse/CircuitVerse/pull/1601
Note: Reference PR was closed as it became stale and was difficult to use it directly

**Comment by vmk8826** [comment]
assign it to me please

**Comment by vmk8826** [comment]
assign it to me please
