### ISSUE TITLE
Wrong use of bootstrap class in Delete CIrcuit

### ISSUE THREAD

**Issue by armudgal** [CircuitVerse/CircuitVerse#213]
We are currently using the wrong class of bootstrap alert to give the warning when there are less than 2 circuits.

![image](https://user-images.githubusercontent.com/19341613/54054612-af54f000-4210-11e9-9966-37c515510476.png)

**Solution**: Use `alert-warning` or any other class if you think it would make more sense. Look into `showError` and `showMessage`

**Comment by sanctophagus** [comment]
Hey @armudgal ! I am working on it.

**Comment by armudgal** [comment]
Nice response. Waiting for the PR 🍔
