### ISSUE TITLE
Close icon not being displayed in ui-dialog

### ISSUE THREAD

**Issue by armudgal** [CircuitVerse/CircuitVerse#214]
Hi,

![image](https://user-images.githubusercontent.com/19341613/54056806-2e4d2700-4217-11e9-935a-09289dea0139.png)

As you can see the close icon can not be displayed. (Circuit -> Insert Subcircuit)

**Solution**: We haven't included the jquery-ui class `ui-dialog-titlebar-close` in `UX.css`. Also the code mentioned below is redundant and can be removed.
https://github.com/CircuitVerse/CircuitVerse/blame/master/public/css/UX.css#L306-L308

**Comment by sanctophagus** [comment]
Hey @armudgal ! I am working on it.

**Comment by armudgal** [comment]
@sanctophagus Hey, send a PR for #213 and then you can take this one. We don't want to block issues if they can't be worked upon :)
