### ISSUE TITLE
Improper Positioning of the Context Menu

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/CircuitVerse#2145]
Its observed that on the simulation Page on Right-clicking and opening the context menu, it always open below the point of click which sometimes results in it being hidden.

1. Simulation Page
2. Right mouse click on the bottom part of the page
3. The some part context menu is hidden

The context menu should be displayed at the top or bottom depending upon the position of the click on the page

![Screenshot (677)](https://user-images.githubusercontent.com/61665451/110473859-03975100-8105-11eb-97cb-663a9794797f.png)

Please suggest any other feature or design you want me to include for the context menu.

I want to go ahead and work on this issue.

**Comment by devartstar** [comment]
I am working on this issue.

**Comment by Dnouv** [comment]
@devartstar, sorry for the interruption, but are you still working on this issue?

**Comment by devartstar** [comment]
yeah, I am working on this ... will generate a PR soon!

**Comment by Prerna-0202** [comment]
solved in pr #2589
