### ISSUE TITLE
Move the space around by two finger on mousepad.

### ISSUE THREAD

**Issue by vmk8826** [CircuitVerse/CircuitVerse#2147]
**Describe the bug**
When we keep our two fingers on the mousepad and try to move the space around, the application instead zooms the wok area

**Expected behavior**
When two fingers are kept on the mousepad and they are moved, the work area should move instead of it zooming.

**Screenshots**
![mousepad](https://user-images.githubusercontent.com/68069180/110889238-ca80fb80-8313-11eb-8e40-36dafe572858.jpg)

**Additional context**
Generally two fingers on mousepad are used to move the workspace around.

**Are you working on this issue? (Yes/No)**
Yes, Please assign it to me.

**Comment by vmk8826** [comment]
please assign it too me, I wish to work on it.

**Comment by ShreyaPrasad1209** [comment]
@vmk8826 you can start working on it

**Comment by vmk8826** [comment]
can please point me to the file where I should start from. It will be very helpful.

**Comment by ShreyaPrasad1209** [comment]
@vmk8826 you can see that yourself using Dev Tools

**Comment by vmk8826** [comment]
Can you assign it to me please. I am new to this code base, I don't completely understand what you mean by dev tool, are you talking about VStudio and Gitpod.

**Comment by ShreyaPrasad1209** [comment]
@vmk8826 you can start working on this issue, it doesn't need to be explicitly assigned. For understanding the codebase, you need to have prior knowledge of Ruby on Rails (RoR). You can find the resources to learn in #random channel on Slack. To access Dev Tools, right click on the page that you want to work on and select inspect element. 
You can learn all these things yourself by Googling and YouTube.

**Comment by vmk8826** [comment]
sure thanks.

**Comment by ShreyaPrasad1209** [comment]
@vmk8826 I checked and looks like this is not a bug but an expected behaviour so this issue can be closed

**Comment by vmk8826** [comment]
okay
