### ISSUE TITLE
Add hover effect to social icons

### ISSUE THREAD

**Issue by Aayush-hub** [CircuitVerse/CircuitVerse#2149]
**Is your feature request related to a problem? Please describe.**
Add hover effect to social icons in footer section.

**Are you working on this? (Yes/No)**
Yes

**Comment by Aayush-hub** [comment]
I am working on this , can it be assigned to me?

**Comment by ashutosh264** [comment]
Can I work on this?

**Comment by ShreyaPrasad1209** [comment]
@Aayush-hub what's the status on this issue?

**Comment by Aayush-hub** [comment]
@ShreyaPrasad1209 Can be assigned to @ashutosh264

**Comment by ShreyaPrasad1209** [comment]
@ashutosh264 you can work on it

**Comment by Aayush-hub** [comment]
@ashutosh264 Good luck. Happy Coding :)

**Comment by ashutosh264** [comment]
Added hover effect to social icons. Improvised a bit & made changes according to theme. Please suggest if any more modifications needed.
@ShreyaPrasad1209 @Aayush-hub 
Sorry for delayed response.

**Comment by deepaahuja92** [comment]
I want to work on this issue.Please assign this issue to me.

**Comment by deepaahuja92** [comment]
Working on this issue

**Comment by deepaahuja92** [comment]
#2286 Kindly review my PR. I have added the hover effect to social icons.

**Comment by Palaksharma23** [comment]
I want to work on this issue . Can you please assign it to me

**Comment by Palaksharma23** [comment]
Currently working on it ........

**Comment by gr455** [comment]
@Palaksharma23 seems like https://github.com/CircuitVerse/CircuitVerse/pull/2462 has aleady addressed this issue

**Comment by Palaksharma23** [comment]
Okay sir @gr455
