### ISSUE TITLE
Using Bootstrap CDN instead of hosting on our server

### ISSUE THREAD

**Issue by armudgal** [CircuitVerse/CircuitVerse#215]
Hi,

So the issue title is pretty self-explanatory. It would be wise to use the static bootstrap files using CDN so that the loading time is faster.
Bonus: Cleans our code a little bit. (~22% reduction in our repo size)

**Comment by sanctophagus** [comment]
Hey @armudgal ! I am working on it.

**Comment by armudgal** [comment]
@sanctophagus Hey, send a PR for the previous issue and then you can take this one. We don't want to block issues if they can't be worked upon :)

**Comment by sanctophagus** [comment]
@armudgal  Should I delete all the files of `public/bootstrap-3.3.7`

**Comment by armudgal** [comment]
@sanctophagus After making sure that everything works locally (UI and front-end JS part) you can. Once you make the PR, I will test as well.
