### ISSUE TITLE
Mention discord and gitter link in the readme explicitly

### ISSUE THREAD

**Issue by agarwalrounak** [CircuitVerse/CircuitVerse#216]
Update the discord and gitter link in the readme explicitly, perhaps under the section of 'talk to us at' or 'circuitverse community'.

I am working on it.

**Comment by creyente1897** [comment]
@agarwalrounak This was an issue related to #183 and has been resolved in the pr #221

**Comment by creyente1897** [comment]
You can add the discord link in the about page if you want
