### ISSUE TITLE
Better documentation for Docker

### ISSUE THREAD

**Issue by Blakelist7** [CircuitVerse/CircuitVerse#2164]
**Is your feature request related to a problem? Please describe.**
I think some might be facing trouble while setting up CircuitVerse through docker, (to be honest I faced a lot as new to docker)

**Describe the solution you'd like**
A simple and brief docker installation docs would do the job.

**Are you working on this? (Yes/No)**
yes

**Comment by ayan-biswas0412** [comment]
@Blakelist7 can you explain what kind of problem you faced ? like I have also setup the codebase using docker but I have not got any problem .

**Comment by Blakelist7** [comment]
@ayan-biswas0412  see for someone like me who isn't familiar with docker may face trouble installing docker since as far as I am aware there are different aspects to docker so I want to make a documentation that you can use and directly setup docker. I have requested a PR also.You can look into it for more info.
https://github.com/CircuitVerse/CircuitVerse/pull/2165
