### ISSUE TITLE
Graph of time (Scope)

### ISSUE THREAD

**Issue by danieltak** [CircuitVerse/CircuitVerse#2166]
**Is your feature request related to a problem? Please describe.**

Falstad has a graph for each element or you can input a Scope to plot a time diagram of the circuit.
I think it is really helpfull and educational.

**Describe the solution you'd like**

As in Falstad (https://www.falstad.com/circuit/circuitjs.html) or Github (https://github.com/pfalstad/circuitjs1/commits/master), you could add or stack graphs for each element or on some nodes, so it is more doable to understand what happens on some circuits.

**Describe alternatives you've considered**

Since those are logical circuits, maybe instead of the Voltage, it could display value x time. Where value could be Binary, Hex or Dec.

**Additional context**

A Ripple Counter (D Flip Flop) can be an example:

![image](https://user-images.githubusercontent.com/28607555/111195086-a4b95800-859a-11eb-8843-363f587ddf13.png)

**Are you working on this? (Yes/No)**

No

**Comment by shubhankarsharma00** [comment]
In the misc submenu we have an element called "Flag" it does something similar and plots timing graphs. You can visualize these graphs by opening timing graph menu as in the photo.
![image](https://user-images.githubusercontent.com/32474302/111873477-68c92d00-89b6-11eb-918c-ce3880723ab4.png)
Is this your feature request
