### ISSUE TITLE
logo is not loading in wiki/GSoC'21-Project-List

### ISSUE THREAD

**Issue by two-ticks** [CircuitVerse/CircuitVerse#2188]
**Describe the bug**
The circuitverse logo is not loading in wiki/GSoC'21-Project-List page and all other wiki pages

**To Reproduce**
1. Go to https://github.com/CircuitVerse/CircuitVerse/wiki
3. Scroll down to 'About'

**Expected behavior**
Logo of CircuitVerse logo should be loaded

**Screenshots**
<img src="https://user-images.githubusercontent.com/68433541/112295281-c365d000-8cb9-11eb-9e73-6c3da717bbe9.png" height="250"/>

**Are you working on this issue? (Yes/No)**
I would like to work on this

**Comment by pranay-simejia** [comment]
go ahead and send a PR.

**Comment by ayan-biswas0412** [comment]
@Shivansh2407 @satu0king please take a note of this the wiki really looks bad for this 
<img width="934" alt="image" src="https://user-images.githubusercontent.com/52851184/112644697-b4268400-8e6b-11eb-9662-ed8955746ec7.png">

**Comment by satu0king** [comment]
Thanks for reporting this. I have resolved it temporarily now.
