### ISSUE TITLE
property panel disappears. 

### ISSUE THREAD

**Issue by pranay-simejia** [CircuitVerse/CircuitVerse#2191]
**Describe the bug**
Properties panel vanishes on selecting and pressing delete key and then re-appears. 

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator.'
2. Shift + drag on property table and keep the cursor on the table itself.
4. See the table vanish and re-appear.

**Expected behavior**
The circuit below the table should be selected. 

**Gif**
![bug prop panel](https://user-images.githubusercontent.com/70064696/112717467-ec34d200-8f12-11eb-8997-bc9eb3ffbe27.gif)

**Are you working on this issue? (Yes/No)**
No, as this doesn't seem to be a priority.

**Comment by anmolkohli13** [comment]
@pranay-simejia I tried to reproduce the behavior but the property table didn't disappear .

**Comment by ShreyaPrasad1209** [comment]
@pranay-simejia should I close this issue?

**Comment by pranay-simejia** [comment]
Yes, closing it. @ShreyaPrasad1209
