### ISSUE TITLE
Make error message user friendly.

### ISSUE THREAD

**Issue by pranay-simejia** [CircuitVerse/CircuitVerse#2198]
**Describe the bug**
on setting ConstVal to except 1/0, the Contention error of NaN and NaN at ConstVal shows up.

**To Reproduce**
1. Go to '[simulator](https://circuitverse.org/simulator)'
2. Click on 'select a ConstVal input.
3. Double click the Const Val input and set value except 1/0. 
4. See an error.

**Expected behavior**
A user-friendly error message like, "ConstVal set to Non-binary value."

**Screenshots**

![image](https://user-images.githubusercontent.com/70064696/113132822-97f45f80-923c-11eb-9e72-4e8c8758cab5.png)

**Are you working on this issue? (Yes/No)**
No.

**Comment by Whitroy** [comment]
Can I work on it?

**Comment by pranay-simejia** [comment]
sure, go ahead. @Whitroy

**Comment by Whitroy** [comment]
@pranay-simejia  Hey, I have searched some of the simulators' code but I didn't find the error handling file. Could you help me out?

**Comment by pranay-simejia** [comment]
Error is fired from /simulator/src/node.js line 390. You can find the showError function in /simulator/src/utils.js line 47. All the best,. @Whitroy

**Comment by Whitroy** [comment]
@pranay-simejia thanks for the above help. One more question, What are the other possibilities to get contention error?

**Comment by pranay-simejia** [comment]
you can read about it here. [error messages](https://github.com/pranay-simejia/CircuitVerseDocs/blob/GSoD2020/docs/chapter8/3cverrormessages.md) @Whitroy

**Comment by ShreyaPrasad1209** [comment]
I've added good first issue for a special project and is currently not open for contributors.

**Comment by vvijayalakshmi21** [comment]
HI,
This needs just changing the error message to the specified text. Is that right?
https://github.com/CircuitVerse/CircuitVerse/blob/master/simulator/src/node.js#L390
