### ISSUE TITLE
Fix css and bootstrap for mobile

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#22]
There are small css and bootstrap issues. For example, this is the sign in page on mobile below. 

![image](https://user-images.githubusercontent.com/2092958/47259407-de1f3380-d4c6-11e8-97e8-620af989b290.png)

**Comment by Amansingla97** [comment]
I would like to work on this issue

**Comment by tachyons** [comment]
Fixes in https://github.com/CircuitVerse/CircuitVerse/pull/156
