### ISSUE TITLE
Text and Icon not aligned on issue reporting tool

### ISSUE THREAD

**Issue by ryuk156** [CircuitVerse/CircuitVerse#2202]
**Describe the bug**

![image](https://user-images.githubusercontent.com/49101492/113289539-f9383380-930d-11eb-80be-991172c92a4b.png)

 

**Expected behavior**
![image](https://user-images.githubusercontent.com/49101492/113289667-21279700-930e-11eb-9e61-33326a069064.png)

**Device Information [optional]:**
 - OS: Ubuntu 18.04
 - Browser: Firefox 

**Are you working on this issue? (Yes/No)**
NO

**Comment by Sukriti-sood** [comment]
@ryuk156 Can i work on this issue

**Comment by abhishek-iiit** [comment]
While file check at PR, I encountered one error "AppVeyor build failed ".
Could you please help me out with solving this issue. I still can't get why the check failed.
Thanks in advance

**Comment by ryuk156** [comment]
@abhishek-iiit did you check "AppVeyor build failed" details?

**Comment by abhishek-iiit** [comment]
Actually, I didn't know why did it fail.
Here's the screenshot of the error ,I did face 
![Screenshot from 2021-04-09 00-55-25](https://user-images.githubusercontent.com/69477761/114085116-8fe88f80-98ce-11eb-9c06-188e09f5395a.png)

**Comment by Ansh7899** [comment]
Can I take this issue for OSD?

**Comment by ryuk156** [comment]
@ShreyaPrasad1209 I think this one is fixed,  @Ansh7899 just check in the simulator before working

**Comment by Palaksharma23** [comment]
yes this one is already fixed

**Comment by harshalkaigaonkar** [comment]
open?

**Comment by Kunal0220** [comment]
Is the issue still open , I would be happy to try it !

**Comment by rinkydevi** [comment]
i can contribute in this issue, how can i proceed?

**Comment by Subhraneel77** [comment]
Can I give it a Try ?

**Comment by Shofiya2003** [comment]
The issue is already fixed I believe. The text and icon seems to be aligned.

**Comment by Prerna-0202** [comment]
Fixed
