### ISSUE TITLE
clashing inputs on generating 2 combinational circuits

### ISSUE THREAD

**Issue by pranay-simejia** [CircuitVerse/CircuitVerse#2203]
**Describe the bug**
Simulator overwrites the first input element when generating 2nd combinational circuit with different boolean variables.

**To Reproduce**
1. Go to '[simulator](https://circuitverse.org/simulator)'
2. Click on 'tools>combinational analysis.'
4. Create a combinational circuit with boolean variables A, B, C ... and generate a circuit.
5. Repeat steps 1 to 4 with unused boolean variables. 
**Expected behavior**
A new circuit should be generated away from the existing circuit.

**Screenshots**
![image](https://user-images.githubusercontent.com/70064696/113412638-66170080-93d6-11eb-8010-b4e08d4426c1.png)

**Are you working on this issue? (Yes/No)**
No.

**Comment by ZadeAbhishek** [comment]
Hey @pranay-simejia  can i work on this issue

**Comment by pranay-simejia** [comment]
Sure, go-ahead. @ZadeAbhishek

**Comment by pulkit-30** [comment]
Hey @tachyons @ZadeAbhishek, 
This issue still exists 

<img width="1045" alt="Screenshot 2022-01-03 at 6 55 33 PM" src="https://user-images.githubusercontent.com/76155456/147935702-d653217e-c76f-41f1-be97-cd2acdd215e8.png">

Is anyone working on this?
If not, may you please assign me this Issue?

**Comment by ZadeAbhishek** [comment]
@pulkit-30  have you tried this branch #2205

**Comment by pulkit-30** [comment]
Yes, @ZadeAbhishek, I tried this and the changes are looking good.
but the changes need to be optimized, too many changes for a small bug.
and it would be great if we can implement the requested feature by reviewers @pranay-simejia.
>could we add circuits to the next row if the x coordinate reaches a certain limit? With the current functionality, the circuits get pretty small if they are added in a single row.
