### ISSUE TITLE
Combinational Analysis Tool: Circuits generated over existing circuits

### ISSUE THREAD

**Issue by felixschlegel** [CircuitVerse/CircuitVerse#2215]
**Describe the bug**
In the Combinational Analysis tool, I realised that there is the following issue:

When generating a circuit from a truth table, no respect is paid to existing elements already placed inside of the editor. Therefore the generated circuit is drawn over existing circuits, which is often unpleasant for the user.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to the https://circuitverse.org/simulator
2. Click on Tools -> Combinational Analysis 
3. Type _(AB)_ inside of the text field "Enter Boolean Function"
4. Click "Next" and then "Generate Circuit"
5. Repeat step 2
6. Type _(D+E)_ inside of the text field "Enter Boolean Function"
7. Click "Next" and then "Generate Circuit"
8. See that the second circuit is drawn above the first circuit

**Expected Behavoir**
A possible solution could be checking for empty space next to existing circuits before generating the new circuit, though I am open to any other ideas.

**Screenshots**
<img width="1437" alt="Screenshot 2021-04-13 at 10 38 11" src="https://user-images.githubusercontent.com/26013286/114523179-5d2ef600-9c44-11eb-970c-a9a6153298ce.png">

**Additional context**

**Are you working on this issue? (Yes/No)**
Not yet, would love to discuss possible solutions first.

**Comment by ZadeAbhishek** [comment]
this issue already exist #2203

**Comment by felixschlegel** [comment]
Sorry for the duplicate
