### ISSUE TITLE
Bump omniauth version

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#2218]
Omniauth need to be upgraded to 2.x to fix a vulnerability. But this requires some code changes. Refer #2207

**Comment by anmolkohli13** [comment]
@tachyons can you tell if we have to make the same changes as the bot or update it manually?

**Comment by tachyons** [comment]
Simply updating gem version is not enough as the omniauth 2.0 is not backward compatiable. See the failing specs from the linked PR

**Comment by pavanjoshi914** [comment]
I can't see any specs failing in appveyor logs.
similar error  ```Gem::Ext::BuildError: ERROR: Failed to build gem native extension.```  was encountered on my local machine when working with jekyll gem which was solved after installing g++ compiler.
any further ideas how to proceed for it?

**Comment by tachyons** [comment]
Check circleci logs

**Comment by Sarthakaga15** [comment]
@tachyons Hi, I am new to open source ? Is this issue still open ,I would like to work on it if possible. Thanks.

**Comment by vedant-jain03** [comment]
#3071 Resolved
