### ISSUE TITLE
Add search icon in search file - User dashboard

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#2227]
**Describe the bug**
The search field lacks a search icon which could help users easily identify it as a search field

**To Reproduce**
![image](https://user-images.githubusercontent.com/16988558/116386081-1392fd80-a837-11eb-8814-2d4844a39021.png)

**Are you working on this issue? (Yes/No)**
No, a good first issue

**Comment by jokerJun00** [comment]
@nitin10s Can I work on this issue?

**Comment by shubhankarsharma00** [comment]
@jokerJun00 I think you should go ahead and start working on this 😄

**Comment by nitin10s** [comment]
Yes please, sorry for the late reply!

**Comment by jokerJun00** [comment]
Alright, I make a pull request but I am not sure why I cannot pass AppVeyor

**Comment by pavanjoshi914** [comment]
> Alright, I make a pull request but I am not sure why I cannot pass AppVeyor

pull requests must be linked with the respective issue  for easy to refer and automated closure of issue after merge

**Comment by deepaahuja92** [comment]
I want to work on this issue.please assign this issue to me.

**Comment by nitin10s** [comment]
@jokerJun00 are you still working on this issue? Otherwise @deepaahuja92 can take this up

**Comment by deepaahuja92** [comment]
Thank you very much

**Comment by Anshnrag02** [comment]
Can I work upon it?

**Comment by nitin10s** [comment]
@deepaahuja92 is taking this up @Anshnrag02

**Comment by ankit80570** [comment]
I'm working on this for OSD.

**Comment by ankit80570** [comment]
![image](https://user-images.githubusercontent.com/52366781/125833679-79202b70-c8df-4dfc-8808-1c5bedb09bd0.png)
Will this work for pr?

**Comment by ShreyaPrasad1209** [comment]
@ankit80570 yes

**Comment by ankit80570** [comment]
I have made a pull request, can you check it?

**Comment by Nonna-source** [comment]
Hey @ShreyaPrasad1209 I am a participant at GHC OSD and I would like to try working on this issue. I am not sure if I will be able to fix this issue. I will need some mentoring assistance.

**Comment by gr455** [comment]
@Nonna-source Looks like this was already worked on in https://github.com/CircuitVerse/CircuitVerse/pull/2464

**Comment by nitin10s** [comment]
Closing via #2337
