### ISSUE TITLE
Handling schema.rb in version control  

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#224]
It is generally recommended to commit `schema.rb` file along with other file systems as mentioned [here]( https://stackoverflow.com/questions/6450263/what-is-the-right-approach-to-deal-with-rails-db-schema-rb-file-in-git)
Will it be a good idea to remove it from `.gitignore` and commit it for our project too?

**Comment by armudgal** [comment]
I suppose it wasn't done in the past to stay away from merge conflicts but that is not the way we should go forward. I agree of having `schema.rb` in our version control. 
@tachyons would be the best person here to respond to this. 

Thanks for the suggestion.

**Comment by tachyons** [comment]
Yes, it is the recommended practice, but it is impossible to have schema.rb in version control since we support two databases at the moment. We can add them once we drop mysql support

**Comment by ankitkataria** [comment]
I agree, the extension mentioned in the file would differ. Are we planning to drop mysql support anytime soon?

**Comment by armudgal** [comment]
@ankitkataria We are.

**Comment by ankitkataria** [comment]
I'll add the schema.rb once Issue #234 is done.
