### ISSUE TITLE
deleteOfflineProject not a function.

### ISSUE THREAD

**Issue by pranay-simejia** [CircuitVerse/CircuitVerse#2242]
**Describe the bug**
When deleting an offline project in the openOfflineProject prompt, the browser console throws an uncaught ReferenceError. 

**To Reproduce**
1. Go to the simulator
2. Create multiple projects and save them offline. 
3. Click on projects > Open Offline button.
4. Click the delete button and see an error in the browser console. 

**Expected behavior**
The selected project must be deleted. 

**Screenshots**
![image](https://user-images.githubusercontent.com/70064696/117441528-21413500-af53-11eb-8a7c-96696e624a96.png)

**Are you working on this issue? (Yes/No)**
No. @tachyons, if you could label this issue as "good first issue."

**Comment by deepaahuja92** [comment]
I want to work on this issue.Please assign this issue to me.

**Comment by pranay-simejia** [comment]
@deepaahuja92 go ahead, atb!

**Comment by deepaahuja92** [comment]
Thank you for assigning this issue to me.

**Comment by deepaahuja92** [comment]
@pranay-simejia sir I am having problem in opening this website in gitpod please can you help me with it..when I am trying to access it,it is just showing the folders and not the actual website.

**Comment by pranay-simejia** [comment]
Could you try running the repo locally? https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md

**Comment by Kartikay304** [comment]
I would like to work on this issue.
