### ISSUE TITLE
Navbar disappears during Tutorial Guide

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/CircuitVerse#2251]
**Describe the bug**
Navbar disappears during Tutorial Guide after clicking next for the Time Diagram Panel

**To Reproduce**
1. Click on Help on Navbar
2. Chick on Tutorial Guide
3. Click Next, Next for the guide
4. After clicking next for the Time Panel the Navbar disappears suddenly.

**Expected behavior**
The Navbar should have remained in its place.

**Screenshots**
![BugTutorialGuide](https://user-images.githubusercontent.com/61665451/118279711-135a5980-b4e9-11eb-943d-484536dafd1f.gif)

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
Yes...I am working to solve this bug

**Comment by deepaahuja92** [comment]
I am interested in this project.Please assign this issue to me.

**Comment by devartstar** [comment]
Hi @deepaahuja92 , I have already created a pull request for this issue...waiting for a review of mentors.

**Comment by pulkit-30** [comment]
Hii,
Is anyone working on this issue?
Please assign me this issue and please help me out with some code pointers/references from where I can start digging into it.

**Comment by Prerna-0202** [comment]
Solved in  pr #2360
