### ISSUE TITLE
Fixing Features section

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#2264]
The features section has very big icons and large padding. Fixing these would make the section appear better. We can aim for something like 50% icon width and removing the Y-padding from the card-body

![image](https://user-images.githubusercontent.com/16988558/119691279-10a42080-be68-11eb-956d-b443fe583950.png)

**Comment by Anshnrag02** [comment]
Kindly assign

**Comment by deo002** [comment]
> Kindly assign
Are you still working on this issue?

**Comment by Anshnrag02** [comment]
@deo002 I am really sorry I was unable to inform but I am stuck up in some emergency and wont be able to work on it for the time being. Once again really sorry

**Comment by deo002** [comment]
Ok. I'll work on it then. @Anshnrag02

**Comment by ShreyaPrasad1209** [comment]
@nitin10s do you want to merge the PR and close this issue? Else I will reserve it for open source day.
