### ISSUE TITLE
Can we have a link of Blog in nav and footer

### ISSUE THREAD

**Issue by ayan-biswas0412** [CircuitVerse/CircuitVerse#2268]
**Is your feature request related to a problem? Please describe.**
There is no direct link of CircuitVerse blog site available in the navbar as well as footer in the main website of CircuitVerse

**Describe the solution you'd like**
Like to add Blog in the nav and footer which will redirect users to https://blog.circuitverse.org

**Are you working on this? (Yes/No)**
No , but looking for inputs

**Comment by ayan-biswas0412** [comment]
@ShreyaPrasad1209 @Shivansh2407 @satu0king can you give your suggestions ?

**Comment by prashantpandey9** [comment]
@ayan-biswas0412  I can add these links to Navbar and footer.  Can I work on this?

**Comment by ayan-biswas0412** [comment]
> @ayan-biswas0412 I can add these links to Navbar and footer. Can I work on this?

ofc you can work on, but this issue is awaiting approval from official maintainers, your work will be merged if and only if this issue is approved

**Comment by prashantpandey9** [comment]
@ayan-biswas0412 Okay I can wait till then. After approval, I will work on this issue.

**Comment by ShreyaPrasad1209** [comment]
We can do this. I've added good first issue for a special project and is currently not open for contributors.

**Comment by astelrastogi** [comment]
I want to work on this issue

**Comment by vedant-jain03** [comment]
I want to work on this issue.

**Comment by Shivansh2407** [comment]
Go ahead @vedant-jain03 :+1:

**Comment by astelrastogi** [comment]
@Shivansh2407 im working on this issue too

**Comment by astelrastogi** [comment]
can you tell which file is the homepage for this site in the repo? https://circuitverse.org/

**Comment by Shivansh2407** [comment]
The thing I'll suggest you to go with is browsing the file structure. You can also have a look at the Viscose search, wherein you can find the file easily with keyword search. Thanks

**Comment by astelrastogi** [comment]
@Shivansh2407 @ShreyaPrasad1209 i'm not able to find the homepage file in the repository for adding the link on navbar  and footer. is this the correct repository im looking: https://github.com/CircuitVerse/CircuitVerse ?

**Comment by astelrastogi** [comment]
Completed the issue, sending in a PR
<img width="682" alt="Screenshot 2021-07-16 at 12 33 56 AM" src="https://user-images.githubusercontent.com/54110949/125843394-b5d9af59-852a-4f5d-aab7-51ee775c4b0e.png">

<img width="676" alt="Screenshot 2021-07-16 at 12 32 30 AM" src="https://user-images.githubusercontent.com/54110949/125843386-f91c5319-9abf-4cf9-9101-528fdae3882c.png">
