### ISSUE TITLE
Seperate Circuit Elements tab and Properties tab

### ISSUE THREAD

**Issue by YizhePKU** [CircuitVerse/CircuitVerse#227]
Put Properties on the right of the screen. This will make editing properties simplier(by not having to scroll down to see the properties when an element tab is open)

**Comment by saumyashrm2802** [comment]
@armudgal I would like to work on this issue. Please assign me this.

**Comment by ankur54** [comment]
I'll do it. Is that okay?

**Comment by satu0king** [comment]
Go ahead, try different options and we will review.
