### ISSUE TITLE
Fix: password input on login and signup pages

### ISSUE THREAD

**Issue by ritika99** [CircuitVerse/CircuitVerse#2278]
**Describe the bug**
The input element in div form-input for the password in login and signup is overflowing. This hides the bottom border of form-input. 
#
**Expected behavior**
The border is visible properly and the height of the input element should fit inside the div form-input.

**Screenshots**
<img width="1017" alt="login" src="https://user-images.githubusercontent.com/35415933/121490504-b6bc6280-c9f2-11eb-8266-6e93e321c10b.png">

**Device Information [optional]:**
 - OS: macOS
 - Browser: Chrome
 - Version: 90

**Are you working on this issue? (Yes/No)**
Yes!

**Comment by dineshkumar12004** [comment]
can i work on this issue? I'm on windows I can see the same bug too.
![image](https://user-images.githubusercontent.com/67814205/122514474-a70fd000-d029-11eb-8b34-4722263fe94e.png)

**Comment by AshuKV** [comment]
I want to work on this issue. Please assign this issue to me.

**Comment by sonali-dudekula** [comment]
@ritika99 Can I please work on this issue?

**Comment by ritika99** [comment]
> @ritika99 Can I please work on this issue?

> I want to work on this issue. Please assign this issue to me.

Hey @sonali-dudekula and @AshuKV
Thank you for showing interest. However, I have resolved the issue and waiting for the PR to be merged.
