### ISSUE TITLE
Clicking on links present under MENTORS and EXTENDED TEAM heading results opening of Linked in page of Mr. Vaibhav Aggarwal.

### ISSUE THREAD

**Issue by saumyashrm2802** [CircuitVerse/CircuitVerse#228]
![image](https://user-images.githubusercontent.com/40107298/54102647-55f6e780-43ef-11e9-946b-618d50b6ea51.png)

Whenver links under MENTORS heading and EXTENDED TEAM heading are clicked, linked in profile of Mr. Vaibhav Aggarwal gets opened. 
I would like to fix this issue.
I require links to linked in profiles of the mentors and extended team members so I that I can attach the link with their names .

**Comment by saumyashrm2802** [comment]
@armudgal @satu0king please assign me this issue.

**Comment by armudgal** [comment]
@saumyashrm2802 Please go forward with this. Also fix the width of the whole div which will be solved if you remove the hyperlink. 

For now, remove the links, we will provide you with the list of links to add later on.

**Comment by armudgal** [comment]
Also add screenshots in the PR after the change.

**Comment by saumyashrm2802** [comment]
Yes sir..i will surely do it.

**Comment by armudgal** [comment]
Closed by #244
