### ISSUE TITLE
Broken checkboxes in firefox

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#2290]
**Describe the bug**

Checkboxes are broken in Firefox browser.

**To Reproduce**
1. Go to [Login Page](https://circuitverse.org/users/sign_in)
2. Scroll to see "Remember Me" option
3. See error

**Expected behavior**

![image](https://user-images.githubusercontent.com/43600306/122352525-d3b1e200-cf6c-11eb-8bc8-9cfe46d09a70.png)

**Screenshots**

<img width="963" alt="Screenshot 2021-06-17 at 11 17 43 AM" src="https://user-images.githubusercontent.com/43600306/122351834-2939bf00-cf6c-11eb-884d-b7fd8b520bf9.png">

**Device Information [optional]:**
 - Browser - Mozilla Firefox
 

**Are you working on this issue? (Yes/No)**

No this is reserved for Open Source Day contributors.

**Comment by dineshkumar12004** [comment]
can i work on this issue ?

**Comment by ShreyaPrasad1209** [comment]
Hi @dineshkumar12004, as mentioned above this issue is reserved for a special project and is not open for contributions at the moment. You can check out other issues and contribute 😊

**Comment by dineshkumar12004** [comment]
> Hi @dineshkumar12004, as mentioned above this issue is reserved for a special project and is not open for contributions at the moment. You can check out other issues and contribute 😊

okay cool :)

**Comment by AbhipsaGuru1012** [comment]
@ShreyaPrasad1209 can I work on this issue? I am a contributor in Open Source Day
