### ISSUE TITLE
CI continuous-integration/appveyor/pr failing every time

### ISSUE THREAD

**Issue by ayan-biswas0412** [CircuitVerse/CircuitVerse#2296]
**Describe the bug**
One of the CI is failing for every PR

**To Reproduce**
make a simple PR and see the error of the ```continuous-integration/appveyor/pr```

**Screenshots**
here is a  failed log for one of my PR
<img width="966" alt="image" src="https://user-images.githubusercontent.com/52851184/122674672-da05bf80-d1f3-11eb-80ec-afd0af2ed7a2.png">

**Additional context**
N/A

**Are you working on this issue? (Yes/No)**
No

**Comment by ShreyaPrasad1209** [comment]
@ayan-biswas0412 yes I have noticed this. Even with minor changes this CI fails. @tachyons what's the purpose of this CI and do we really need this? Or can we make do with some alternative solution?

**Comment by tachyons** [comment]
Appveyor is to ensure that circuitverse is working fine in windows environment. It started failing since the mimemagic update which made configuration on Windows difficult.
