### ISSUE TITLE
Navbar disappears after the tutorial guide is launched

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#2299]
**Describe the bug**
When the Tutorial guide is Launched, and it reaches the report system step, the navbar automatically disappears and does not show up until I refresh the page. Refer to the screenshots for more information.

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator'
2. Click on 'Help' -> 'Tutorial Guide'
3. Click on next until you reach report system step.

**Expected behavior**
The Navbar should remain as it is, like in the previous steps of this tutorial guide.

**Screenshots**

The Navbar is there when the tutorial guide is launched.

![Screenshot from 2021-06-21 18-27-18](https://user-images.githubusercontent.com/42182955/122765716-68467800-d2be-11eb-83f0-7a4bc11397cf.png)

The Navbar Disappears when we reach report system step.

![Screenshot from 2021-06-21 18-10-57](https://user-images.githubusercontent.com/42182955/122765349-0ab22b80-d2be-11eb-9fcf-8ca8f8920f66.png)

![Screenshot from 2021-06-21 18-11-02](https://user-images.githubusercontent.com/42182955/122765333-084fd180-d2be-11eb-8f37-46b1c5f7b1c2.png)

![Screenshot from 2021-06-21 18-11-14](https://user-images.githubusercontent.com/42182955/122765342-0a199500-d2be-11eb-9398-13ebf4090d32.png)

**Device Information [optional]:**
 - OS: [Ubuntu 20.04.2 LTS]
 - Browser [Firefox Web Browser]

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
@satu0king @abstrekt please have a look at this.

**Comment by devartstar** [comment]
I had already created this issue - [Issue - 2251](https://github.com/CircuitVerse/CircuitVerse/issues/2251)
And also made a pull request solving it - [PR - 2253](https://github.com/CircuitVerse/CircuitVerse/pull/2253)

**Comment by Shivansh2407** [comment]
> I had already created this issue - [Issue - 2251](https://github.com/CircuitVerse/CircuitVerse/issues/2251)
> And also made a pull request solving it - [PR - 2253](https://github.com/CircuitVerse/CircuitVerse/pull/2253)

Thank you @devartstar for the clarification and your contribution. Closing this issue. Please see #2251
