### ISSUE TITLE
Mobile compatibility for Simulator

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#23]
I think it will be difficult to maintain both Desktop and mobile in one HTML file, so one approach is to use a separate html file for mobiles. 

- [ ] Setup mobile HTML5 layout
- [ ] Add touchscreen listeners

**Comment by blane1257** [comment]
This is a good idea. I was looking at circuitverse on my phone recently and was disappointed with the lack of formatting on mobile. but being able to edit and view circuits on mobile sounds awesome!

**Comment by mahmodHammad** [comment]
What is the updates on this issue?

**Comment by TheShubhendra** [comment]
Any updates? So that simulator can be used in phone browser's also.
