### ISSUE TITLE
Resize width of search filter according to content 

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#2304]
**Describe the bug**

Currently we have two search filters in CircuitVerse - Users and Projects. On selecting Projects, some of the letters get hidden. 

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on the search icon 
3. On the left side, you'll see a filter. Choose Projects.
4. See that "s" hidden partially.

**Expected behavior**

The box should resize according to the content present inside the filter.

**Screenshots**

![image](https://user-images.githubusercontent.com/43600306/123425477-d3a28980-d5df-11eb-8912-3fc03a49ce5b.png)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser [Edge]

**Are you working on this issue? (Yes/No)**

This issue is reserved for Open Source Day contributors.

**Comment by lonwabo-mnyaiza** [comment]
@ShreyaPrasad1209 can I work on this if no one has picked it up already?

**Comment by Mbiakop1** [comment]
Hello, recently worked on this. I made a pull request but I don't know why its not being accepted

**Comment by sonali-dudekula** [comment]
@ShreyaPrasad1209 Can I please work on this issue?

**Comment by itsij** [comment]
I am an Open Source Day contributor. Plz assign this issue to me. I would like to resolve it on Open Source Day.

**Comment by mgjain9871** [comment]
I would like to work on this issue on Open Source Day as an Open Source Day Contributor.
@ShreyaPrasad1209

**Comment by AbhipsaGuru1012** [comment]
@ShreyaPrasad1209 can I work on this issue? I am an Open Source Day contributor

**Comment by itsij** [comment]
Working on it
