### ISSUE TITLE
Improve docs added more information in README about the project

### ISSUE THREAD

**Issue by Ayush7614** [CircuitVerse/CircuitVerse#2309]
* In README there is very less information regrading project i think we have to improve that one

**Comment by ShreyaPrasad1209** [comment]
@Ayush7614 what exactly do you think we are missing?

**Comment by Ayush7614** [comment]
Hey @ShreyaPrasad1209, maam thanku for replying I read the documentation and had the following observations

**Comment by Ayush7614** [comment]
![image](https://user-images.githubusercontent.com/67006255/124373031-ad9a7a80-dcac-11eb-994c-552fb4bdd23f.png)

**Comment by Ayush7614** [comment]
![image](https://user-images.githubusercontent.com/67006255/124373047-d3c01a80-dcac-11eb-9499-f17da4bd7528.png)

**Comment by Ayush7614** [comment]
Like after the define of circuit verse we have added some bullet points with dots or stars like what we have cover 
* Introduction
* Getting started this type this all things i have add and improved and added some more new features

**Comment by Ayush7614** [comment]
If you assign me this issue then i will work on it surely it looks very good

**Comment by ShreyaPrasad1209** [comment]
@Ayush7614 feel free to get started.
