### ISSUE TITLE
Resposive Navbar/Homepage Problem

### ISSUE THREAD

**Issue by kunalvishnoi** [CircuitVerse/CircuitVerse#231]

**Comment by kunalvishnoi** [comment]
Submitting a Bug Report and would like to work on the same
Current Behaviour:
![Screenshot_2019-03-11-23-29-31-012_com android chrome](https://user-images.githubusercontent.com/24695316/54146647-71e1a400-4456-11e9-886b-5af8982d99ed.png)

Expected Behaviour:
![Capture](https://user-images.githubusercontent.com/24695316/54146819-d270e100-4456-11e9-9496-354421dc58d4.JPG)

Images are self-explanatory with the bug in the mobile view, and I have to solve the issue
@armudgal Please look at the issue.
Thanks

**Comment by armudgal** [comment]
The issue is with the paging, Since the paging (numbers) is moving out of the screen, it's causing the screen to have a blank space on the right.
Please go forward.

**Comment by armudgal** [comment]
Duplicate of #192
