### ISSUE TITLE
Refractor the css in group.scss

### ISSUE THREAD

**Issue by ayan-biswas0412** [CircuitVerse/CircuitVerse#2317]
Firstly checkout to the ```lms-lti``` branch 
see the file ```app/assets/stylesheets/groups.scss``` where the class named ```groups-lmsmodal-link-text``` need to be refractored.

the class name is too long refractor it as something like this
```
.groups-lms-model {
  .link-text {
     // styles here
   }
}
```

**Comment by crudybagger** [comment]
I'll work on this

**Comment by Vivekk07** [comment]
Is the scope of refactoring only limited to `groups-lmsmodal-link-text` class?
There are a few other long class names as well (in `app/assets/stylesheets/groups.scss`) which can be refactored in the same way.

**Comment by ayan-biswas0412** [comment]
> Is the scope of refactoring only limited to `groups-lmsmodal-link-text` class?
> There are a few other long class names as well (in `app/assets/stylesheets/groups.scss`) which can be refactored in the same way.

can you provide some inputs @tachyons

**Comment by tachyons** [comment]
> Is the scope of refactoring only limited to groups-lmsmodal-link-text class?
No, you can fix other issues as well

**Comment by tachyons** [comment]
@LinaJohnson Yes, Idea is to refactor styles without changing the existing user interface

**Comment by Vasuvj24** [comment]
hello i am looking to contribute and i am a newbie, Is this issue still open?

**Comment by mayank171** [comment]
Can I work on this issue? I will refractor the group.scss as much as possible.

**Comment by soham4abc** [comment]
I am working on this issue will provide a PR soon

**Comment by UTKARSHSHARMA718** [comment]
Sir can I work on this please, I am new to open source and love to contribute to your organization, it would be better for me to try a good first issue first.

**Comment by harshalkaigaonkar** [comment]
is it open?
