### ISSUE TITLE
Cursor:Pointer property to search button in Home Page.

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2336]
**Describe the bug**
I thought it will be classy if the search button on the home page has pointer property.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Hover on the 'search bar button'
3. See error

**Expected behavior**
Pointer hover effect on Search Button.

**Screenshots**

![Screenshot (36)](https://user-images.githubusercontent.com/76901313/125885032-d82fc534-5bcd-42b2-a4da-5c4dd2a63071.png)

**Device Information [optional]:**
 - OS: Windows
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
Yes

**Comment by AsherThomasBabu** [comment]
I've created a one liner PR to fix this issue at #2342 
Please review.

P.S: This is my first, and I'm excited to start contributing to CircuitVerse!

**Comment by the-halfbloodprince** [comment]
In case the issue isn't closed, I would like to fix this, please assign me this issue if it's not closed.
