### ISSUE TITLE
Drop Mysql support

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#234]
**Describe the bug**
Supporting two databases causes unnecessary hurdles in development. We decided to drop Mysql support and just use PostgreSQL in all environments

**Are you working on this issue? (Yes/No)**
No

**Comment by Amansingla97** [comment]
i would like to work on this issue

**Comment by tachyons** [comment]
Go ahead

**Comment by danllin** [comment]
Drop Mysql support #234
