### ISSUE TITLE
Slack link is no longer active

### ISSUE THREAD

**Issue by praveeno** [CircuitVerse/CircuitVerse#2343]
I'm interested to join slack workspace, but slack link shared in issues template is not working
I want to discuss if there is any near future plan to add course similar to https://www.nand2tetris.org/, as Circuitverse have everything needed to build a computer itself I believe, correct me if I'm wrong

**Comment by ayan-biswas0412** [comment]
@praveeno Slack link is now active ? can I close the issue ?

**Comment by praveeno** [comment]
Hello @ayan-biswas0412 , slack link mention on here https://github.com/CircuitVerse/CircuitVerse/issues/new/choose, still not working

**Comment by ayan-biswas0412** [comment]
> Hello @ayan-biswas0412 , slack link mention on here https://github.com/CircuitVerse/CircuitVerse/issues/new/choose, still not working

@ShreyaPrasad1209 can you please update this, in the issue section the slack link is outdated
