### ISSUE TITLE
Bug - Simulator Navbar disappears at the end of tutorials guide

### ISSUE THREAD

**Issue by pavanjoshi914** [CircuitVerse/CircuitVerse#2348]
**Describe the bug**
The end msg of the tutorials guide goes out of the screen and makes the navbar disappear. reloading is required to restore everything in a normal state

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'circuitverse.org/simulator'
2. Click on 'help-->tutorials guide'
3. click next till the last msg appear

**Expected behavior**
msg must not go out of screen and navbar shall not disappear

**Screenshots**
![image](https://user-images.githubusercontent.com/55848322/126259080-458cfbe2-4fc8-4818-b664-cff83c78273c.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by vedant-jain03** [comment]
I want to work on this issue

**Comment by pavanjoshi914** [comment]
Go ahead!!

**Comment by vedant-jain03** [comment]
> Go ahead!!

Sure
