### ISSUE TITLE
Content Hide in Mobile View

### ISSUE THREAD

**Issue by kunalvishnoi** [CircuitVerse/CircuitVerse#235]
**Problem**
Main heading content of the page teacher, feature, contribute and about page is hiding due to large text in mobile view.

**Expected behavior**
The content should be clearly visible 

**Screenshots**

![Screenshot_2019-03-12-22-35-33-977_com android chrome](https://user-images.githubusercontent.com/24695316/54220781-2a235100-4518-11e9-8855-9df7bfbe7a8c.png)

**I am working on the issue please allow me to make a PR**
@armudgal please have a look

**Comment by armudgal** [comment]
Please go forward

**Comment by kunalvishnoi** [comment]
Sure
