### ISSUE TITLE
Grade scaling fix to 1-100 for LTI Assignments 

### ISSUE THREAD

**Issue by ayan-biswas0412** [CircuitVerse/CircuitVerse#2361]
First checkout to the `lms-lti` branch and run CircuitVerse locally

1. Login to your account
2. Go to the Group page by clicking on `My-Groups`
3. Click on any existing group (if you haven't any create one)
4. Click on the `+Add Assignment`
After Clicking you will see the screen shown below
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52851184/127228742-060114bc-d194-4ae3-906c-3b3eff6ab2f1.png">

### Expected Feature
If the checkbox shown above is clicked then the grading scale should be automatically be fixed at `1-100` scale and the field should be disabled. Add corresponding checks in the controller if necessary.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/52851184/127228897-83dd0b80-ebb5-4b41-8111-518a3b1ea3be.png">

### Reference Code
https://github.com/CircuitVerse/CircuitVerse/blob/261533d00b386dc7721636561c5f91d42384543a/app/views/assignments/_form.html.erb#L15

### Note
1. Please make PR against `lms-lti` branch
2. Please comment below if you are starting work on this issue

**Comment by akshatvirmani** [comment]
I would like to work on this issue. Kindly assign this to me.

**Comment by ayan-biswas0412** [comment]
> I would like to work on this issue. Kindly assign this to me.

Yah go ahead,  you can start working

**Comment by ayan-biswas0412** [comment]
@akshatvirmani hi are you still working on the issue ?

**Comment by akshatvirmani** [comment]
Yes Sir, But I don't know how to setup the project locally on VS Code. I read the README.md file but was still not able to set it up. I messaged you yesterday regarding the same on discord as I did not have permission to join the Slack channel.

**Comment by ayan-biswas0412** [comment]
> Yes Sir, But I don't know how to setup the project locally on VS Code. I read the README.md file but was still not able to set it up. I messaged you yesterday regarding the same on discord as I did not have permission to join the Slack channel.

You can join slack from here https://circuitverse.org/contribute, and also you can use Gitpod environment if you are facing difficulties In stepping locally , look here for Gitpod working https://github.com/CircuitVerse/CircuitVerse/wiki/Development-on-Gitpod

**Comment by ayan-biswas0412** [comment]
Closing via #2375
