### ISSUE TITLE
Update UI in open in CircuitVerse page for LTI assignments

### ISSUE THREAD

**Issue by ayan-biswas0412** [CircuitVerse/CircuitVerse#2363]
First checkout to the `lms-lti` branch and run CircuitVerse locally and check `app/views/lti/open_incv.html.erb`

#### currently the view look like below
<img width="1079" alt="image" src="https://user-images.githubusercontent.com/52851184/127271026-dce0c0b6-97f5-4c95-bce6-549550e80fc2.png">

### Expected Feature
You need to update the view according the below
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/52851184/127271217-03562248-f227-44f8-91a8-d3cfbe77aea1.png">
The page should automatically redirect to the group link in 2-3 seconds 

### Reference Code
https://github.com/CircuitVerse/CircuitVerse/blob/261533d00b386dc7721636561c5f91d42384543a/app/views/lti/open_incv.html.erb#L1

### Note
1. Please make PR against `lms-lti` branch
2. Please comment below if you are starting work on this issue

**Comment by vedant-jain03** [comment]
I want to work on this issue.!

**Comment by ayan-biswas0412** [comment]
> I want to work on this issue.!

yah go ahead 🎉

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by ayan-biswas0412** [comment]
> Can I work on this issue?

I think @vedant-jain03 is working? Please ask him once before starting

**Comment by aadityasinha-dotcom** [comment]
Ok

**Comment by aadityasinha-dotcom** [comment]
@vedant-jain03 are you working on this right now?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 are you working on this right now?

Yes I am working on it!

**Comment by ayan-biswas0412** [comment]
Closing via #2373
