### ISSUE TITLE
Centralise of About Page UI

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2376]
**Describe the bug**
The components of about page UI looks good when centered

**To Reproduce**
1. Go to 'https://circuitverse.org/about'

**Screenshots**
* Before
![Screenshot (92)](https://user-images.githubusercontent.com/76901313/128455508-289a9313-c7cf-4ce0-87fa-aff24d6b65c5.png)

* After
![Screenshot (94)](https://user-images.githubusercontent.com/76901313/128455442-f26acb4d-48f5-41a6-9be1-57dd4242101f.png)

**Are you working on this issue? (Yes/No)**
yes

**Comment by vedant-jain03** [comment]
@nitin10s

**Comment by Ayush7614** [comment]
@vedant-jain03 are you working on the issue ?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 are you working on the issue ?

Yes
