### ISSUE TITLE
Adding rel="noopener" to footer external links to enhance the security.

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2380]
**Describe the bug**
Links to cross-origin destinations are unsafe according to lighthouse report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=http%3A%2F%2Fcircuitverse.org#accessibility > Best Practice > Links to cross-origin destinations are unsafe

**Expected behavior**
The noopener is needed to enhance the security of website and prevent other websites from gaining access to page (through the browser session). The noreferrer is used to protect referral information from being passed to the target website and this also hides referral traffic in Google analytics.

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
yes

**Comment by vedant-jain03** [comment]
@tachyons Should I go for it?

**Comment by tachyons** [comment]
Sure
