### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by zidingz** [CircuitVerse/CircuitVerse#2389]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by AsherThomasBabu** [comment]
@zidingz I suppose you can reach out to the team on [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/zt-p6bgler9-~8vWvsKmL9lZeYg4pP9hwQ)

**Comment by zidingz** [comment]
Thank you, machane! We would need to verify their maintainer status here on GitHub. If you can bring their awareness to this issue, perhaps they'll provide a contact method?

**Comment by AsherThomasBabu** [comment]
@zidingz I'm just getting started with contributing to this project and hence don't have any contacts. 
@tachyons could help give more info probably.

**Comment by tachyons** [comment]
@AsherThomasBabu Thanks for bring this to my attention. 

We will add security.md file as soon as possible. Meanwhile you can reach me at aboobackervyd  AT gmail DOT com. You can confirm my identity here in github.

**Comment by zidingz** [comment]
As far as I can tell, @tachyons has been one of the most responsive maintainers on huntr and has dealt with security issues swiftly, and was quick to sign up. Communication channels are already in place, so no rush on the `SECURITY.md`. 

If you want to encourage security researchers to responsibly disclose security issues in CircuitVerse in future, feel free to link us in your `SECURITY.md`: [![huntr](https://cdn.huntr.dev/huntr_security_badge_mono.svg)](https://huntr.dev)

Thank you for taking open source security seriously.

**Comment by tachyons** [comment]
We have already linked huntr here https://github.com/CircuitVerse/CircuitVerse/blob/master/SECURITY.md

**Comment by zidingz** [comment]
Thank you! Much appreciated.
