### ISSUE TITLE
Broken Image on Homepage

### ISSUE THREAD

**Issue by AnirudhPanda** [CircuitVerse/CircuitVerse#2392]
**Describe the bug**
Broken Image on Homepage

**To Reproduce**
1. Go to [this link](https://circuitverse.org/)
2. Scroll down to Recent Circuits
3. See error

**Expected behavior**
The Image should appear instead of the alt text

**Screenshots**
![Capture](https://user-images.githubusercontent.com/66218496/129765563-85756cc5-c641-4b49-a78c-145e64efbba8.PNG)

**Are you working on this issue? (Yes/No)**
Not yet but I would if this issue is applicable

**Comment by AsherThomasBabu** [comment]
This issue was not reproducible on Firefox Version 91.0. or Chrome Version 92.

**Comment by ShreyaPrasad1209** [comment]
I'm closing this issue as it was not reproducible.
