### ISSUE TITLE
No access check for show method in AssignmentsController

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#240]
**Describe the bug**
Currently, there is no access check for show method in assignments controller, which means any user who is signed in can view assignment of any group provided the url is available, even if the user is not a part of the group. 
Is this expected behavior? 

**To Reproduce**
1. Create a group 
2. Create an assignment of a group without adding any member. 
3. Login in as a different user and go to URL. 
4. The assignment will be available. 

**Expected behavior**
The assignment of a specific group should be viewable only by the members of the group. 

**Desktop (please complete the following information):**
Issue on all OS and browsers.

**Are you working on this issue? (Yes/No)**
If this is not expected behaviour, I'd like to self assign the issue. I've implemented auth layer in PR #184 A rule can be added along with the PR or after merging it.

**Comment by satu0king** [comment]
This is not expected behavior.

**Comment by ankitkataria** [comment]
@satu0king Should I add this along with #184 ? Or after that PR has been reviewed and merged?

**Comment by satu0king** [comment]
As per your convenience.
