### ISSUE TITLE
Notification for users.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#243]
**Is your feature request related to a problem? Please describe.**
with commontator subscriptions, mentions, upvote, downvote, and groups it's important to make a system to notify the user about these inside the website.  

**Describe the solution you'd like**
 A notification system similar to GitHub would just be a perfect solution but we can start with just a basic notification option in navbar which can show us our notifications from notification table in which we can push whenever any group invite is sent or any comment mention is made.

**Describe alternatives you've considered**
I looked into [notifications](https://github.com/rails-engine/notifications) gem which seems a decent enough option I am looking for a better alternative though.
 
**Are you working on this? (Yes/No)**
If you guys think this is the right time to implement this feature I can start working on this.

**Comment by satu0king** [comment]
@arkokoley can you give your input here.

**Comment by shubhankarsharma00** [comment]
@satu0king @tachyons @arkokoley  I also think that if we have a notification feature we can easily keep a follow user option and send latest updates to followers with the help of notifications (like GitHub and codeforces do). I think a perfect notification feature can take some time as a lot of experimentation will be required for it. This can also be a GSoC project.

**Comment by vik-y** [comment]
Agreed. This looks like a good gsoc project. Building a good notification
system willl take time.

**Comment by arkokoley** [comment]
Agreed. Building a robust notification system which is free of N+1 queries is a non trivial problem, suitable for GSoC. There are a few pluggable notification systems like 

[Notifications](https://github.com/rails-engine/notifications)
[Activity Notification](https://github.com/simukappu/activity_notification)

[Public Activity](https://github.com/chaps-io/public_activity)

Public Activity is for creating feeds but can be repurposed into a notifications module.

**Comment by tachyons** [comment]
For more advanced implementation https://blog.chaps.io/2016/05/18/creating-activity-feeds-in-postgresql.html

**Comment by ankitkataria** [comment]
If it hasn't already been mentioned, once the notification system is set up, we can also look into setting web push notifications. 
Reference - https://rossta.net/blog/web-push-notifications-from-rails.html

**Comment by shubhankarsharma00** [comment]
@satu0king @vik-y @arkokoley @tachyons can someone spare some time and review my draft proposal on this issue?

**Comment by satu0king** [comment]
> Hey @satu0king @vik-y @arkokoley @tachyons, can someone spare some time and review my draft proposal on this issue?

Please send proposals in private and not on the public forum.

**Comment by tachyons** [comment]
Oops, I closed the issue by mistake

**Comment by shubhankarsharma00** [comment]
Okay @satu0king :grimacing:
