### ISSUE TITLE
Number of views for a circuit increases upon page reload

### ISSUE THREAD

**Issue by animysore** [CircuitVerse/CircuitVerse#246]
**Describe the bug**
Everytime a signed in user who is *not* the creator refreshes the page, the view count increases.

**To Reproduce**
1. Sign in to CircuitVerse. 
2. Go to any project. eg. https://circuitverse.org/users/3/projects/247
3. Keep refreshing the page
4. Views keep increasing

**Expected behavior**
Views should not change upon refresh.

**Screenshots**
![rec](https://user-images.githubusercontent.com/6796491/54365945-cc1c7800-4695-11e9-8b12-d7750e6b5781.gif)

**Desktop**
 - OS: any
 - Browser: any
 - Version any

**Additional context**
@satu0king We can store a list of userids who have viewed the project and increment view only if the current user is not in that list. Let me know if this seems like a decent approach. We can periodically flush the list of viewers for each project to save space.

**Are you working on this issue? (Yes/No)**
Yes,

**Comment by satu0king** [comment]
No, I think storing user-project views is a lot of data. Also, we would want to count multiple views by the same users as separate. I am not sure how websites like youtube implement views. 

Given that, I do not think every refresh should be a new view. Instead, every page visit, that lasts longer than 15 seconds or so can be counted as a view. 

@vik-y @tachyons @arkokoley can you give your input here.

**Comment by tachyons** [comment]
There is a gem that does this https://github.com/ankane/ahoy

**Comment by satu0king** [comment]
> Basically those views are calculated using cookies. There is a gem that does this https://github.com/ankane/ahoy for rails

@AniMysore74 this looks like a solid gem, go ahead with this.

**Comment by vik-y** [comment]
I can take ownership of this task. Whoever wants to work on this, please contact me.

**Comment by AniMysore74** [comment]
@vik-y I have started integration.
