### ISSUE TITLE
Broken checkboxes 

### ISSUE THREAD

**Issue by Kartikay304** [CircuitVerse/CircuitVerse#2466]
**Describe the bug**
Checkboxes are greyed in the browser

**To Reproduce**
1. Go to "My Groups"
2. Create a "New Group"
3. Add an "Assignment"
4. Scroll down  and check on 'Enable elements restriction'
5. See error

**Expected behavior**
![login (1)](https://user-images.githubusercontent.com/40604582/132085609-fcce27a6-26a7-47d2-a8bb-dc62b1979ad4.png)

**Screenshots**
![error](https://user-images.githubusercontent.com/40604582/132085663-65e491b0-d5e8-40fb-941b-ed785300d471.PNG)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser Chrome
 - Version  92.0.4515.159 

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Wimukti** [comment]
Is this bug fixed? If not please assigned this to me so that I can resolve it

**Comment by Kartikay304** [comment]
> Is this bug fixed? If not please assigned this to me so that I can resolve it

Hello,yeah.this bug is already fixed.
