### ISSUE TITLE
Broken Button in collaborated Circuits page

### ISSUE THREAD

**Issue by Kartikay304** [CircuitVerse/CircuitVerse#2488]
**Describe the bug**
In view after popup screen shows up, on clicking More button, it is re-directing to wrong page.

**To Reproduce**
1. Go to  'Collaborated Circuits'
2. Click on 'View'
3. Click on  'More'

**Expected behavior**
It should re-direct to respective project  page.

**Screenshots**

https://user-images.githubusercontent.com/40604582/132992068-a6909495-d921-42fa-990a-316e7fcf23a5.mp4

**Device Information [optional]:**
 - OS: Windows 11
 - Browser Edge
 - Version 93.0.961.44 (Official build) (64-bit)

**Are you working on this issue? (Yes/No)**
No

**Comment by Palaksharma23** [comment]
Are you still working on this issue
Can I take up this issue ?

**Comment by Kartikay304** [comment]
@Palaksharma23 Currently I am not working on this issue, you can go ahead and take up this issue.👍

**Comment by Palaksharma23** [comment]
Okay @Kartikay304  Working on it now 👍

**Comment by Palaksharma23** [comment]
@Vasuvj24 I am trying but I am getting an error if you want you can take this up

**Comment by Vasuvj24** [comment]
its client side is also made in ruby?

**Comment by Kartikay304** [comment]
> sure i will take this issue up

Yeah go ahead
