### ISSUE TITLE
Watermark not clickable 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#249]
**Describe the bug**
![image](https://user-images.githubusercontent.com/2092958/54427777-7a312c00-4741-11e9-8076-f5d2e400a3cd.png)

Check #11 for more details regarding watermark.

URLS via embed, for example, https://circuitverse.org/simulator/embed/704 should show water-mark. The same watermarks should redirect to the project page of the circuit. Currently, they are not redirecting to the project page. 

**Are you working on this issue? (Yes/No)**
No

**Comment by Amansingla97** [comment]
I would like to work on it

**Comment by Amansingla97** [comment]
I would like to work on it

**Comment by armudgal** [comment]
@Amansingla97 Please take on the issue.
