### ISSUE TITLE
ActionView Gem update

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#250]
Update ActionView Gem

![image](https://user-images.githubusercontent.com/2092958/54429538-d34f8e80-4746-11e9-8373-8fd525394117.png)

**Are you working on this issue? (Yes/No)**
No

**Comment by Sadat97** [comment]
i would to work on this

**Comment by shubhankarsharma00** [comment]
@Sadat97 are you still working on this?

**Comment by Sadat97** [comment]
yes am working on it

**Comment by ankitkataria** [comment]
Will get resolved on solving #372
