### ISSUE TITLE
Include more information with simulator bug reporting

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#2501]
Right now, simulator has a `report bug` option which sends the circuit screenshot along with the issue to the slack channel. It will be helpful to include
a) the circuit data and
b) javascript console logs 
along with this so that issues could be looked better into.

**Comment by ayan-biswas0412** [comment]
Yah it will be great i think @gr455

**Comment by Vasuvj24** [comment]
can i work on this issue i am new it will be great if you please elaborate the issue

**Comment by divyesh-rathod** [comment]
Is the issue still open ? May I work on it
@gr455

**Comment by gr455** [comment]
@divyesh-rathod Yes. The issue actually boils down to finding some pastebin site which works with just Client ID (like imgur does) so we don't have to trouble the backend with the paste creation. If you have such a pastebin site in mind, you can tell.
