### ISSUE TITLE
Back to top button

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2507]
**Is your feature request related to a problem? Please describe.**
We can implement back to top button for the user to navigate to top of the page.

**Describe the solution you'd like**
Making a button absolute for the screen.

**Are you working on this? (Yes/No)**
Yes

**Comment by vedant-jain03** [comment]
@tachyons @nitin10s Should I go ahead?

**Comment by nitin10s** [comment]
The homepage is not really longer than 4-5 screens and a back to the top button would be overkill so I don't think it's really required. What do you think?

**Comment by vedant-jain03** [comment]
> The homepage is not really longer than 4-5 screens and a back to the top button would be overkill so I don't think it's really required. What do you think?

I completely agree, Just asking as now some of the websites have this functionality, but totally agreed with your point. 👍🏼
