### ISSUE TITLE
Translation of "Open assignment" using i18n

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2509]
https://github.com/CircuitVerse/CircuitVerse/blob/59bf87ccb3f9cc19443e72af9084077c6334566f/app/views/lti/open_incv.html.erb#L17

**Comment by vedant-jain03** [comment]
@ayan-biswas0412 @pavanjoshi914 I will make new key in en.yml file for making it translatable.

**Comment by vedant-jain03** [comment]
so I go ahead?

**Comment by ayan-biswas0412** [comment]
> should I go ahead?

yah sure you can do that

**Comment by pavanjoshi914** [comment]
not translatable?  gives different meaning use proper context in issue title

Please go ahead
