### ISSUE TITLE
Make Invite Link text area uneditable

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#2510]
**Describe the bug**
The text area where the group invite link is displayed is editabe, although it's not required to be

**To Reproduce**
1. Create a group
2. Go to `Add Members`
3. Click on `Group Invite Link`

**Expected behavior**
Text area should be uneditable

Related code [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/app/views/groups/_add_member_modal.html.erb#L39)

**Comment by csaa2019** [comment]
Hello, can I work on this as part of OSD?

**Comment by gr455** [comment]
> Hello, can I work on this as part of OSD?

Yes go ahead!

**Comment by gr455** [comment]
Closed by https://github.com/CircuitVerse/CircuitVerse/pull/2515
