### ISSUE TITLE
Add 'hi' translations using i18n

### ISSUE THREAD

**Issue by Kartikay304** [CircuitVerse/CircuitVerse#2519]
Adding 'hi' translations in following pages:

**1. In groups page ,for flash mesage**
![groups](https://user-images.githubusercontent.com/40604582/135802678-ae810bff-9756-41dc-9221-828b1889547d.png)

**2. In new assignment page ,for the form elements**
![new assignment](https://user-images.githubusercontent.com/40604582/135802932-9d8f0d36-0be8-4716-9632-0ec686ed8da0.png)

**3. In notification page**
![notification](https://user-images.githubusercontent.com/40604582/135803066-33159ae7-d3d2-4a37-b941-194faa4a02a8.png)

**4. Adding 'hi' translations for navbar and footer.**
![header+footer](https://user-images.githubusercontent.com/40604582/135803145-d5f416cb-1967-4292-9636-f0b78b9ea282.png)

**5. Add translations for Active circuit main and sub heading**
![active circuits](https://user-images.githubusercontent.com/40604582/135803412-1e46faba-8575-4c64-83aa-a073733e387f.png)

 
**6. Add translations for form elements in edit assignment page**

![edit_assignmmn](https://user-images.githubusercontent.com/40604582/135853108-d188b060-ed67-4c18-8395-eeb73013ffe7.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by pavanjoshi914** [comment]
You can close this. We already translated different modules just little late in merging

Keep contributing !
