### ISSUE TITLE
No background for the typeahead drop-down for Educational Institute

### ISSUE THREAD

**Issue by somesh202** [CircuitVerse/CircuitVerse#2523]
**Describe the bug**
The suggestions drop-down for educational institutions in the Edit Profile section appears transparent which looks weird.

**To Reproduce**
1. Go to `Dashboard`
2. Click on `Edit Details`
3. Try entering something in **`Educational institute`** input
4. See error in suggestions

**Expected behavior**
There should be some background for the drop-down(preferably white)
**Screenshots**
![Screenshot 2021-10-06 173033](https://user-images.githubusercontent.com/77766761/136214852-7132f742-2cec-4f0f-9e67-4743ca7cb67b.png)

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [chrome, Edge]

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by Vasuvj24** [comment]
hello @gr455 i am newbie , can i work on the issue if @rushikeshadhav you are ok with it

**Comment by rushikeshadhav** [comment]
Yes, I am working on it

**Comment by rushikeshadhav** [comment]
Hey! @somesh202 can you tell me where can I find the file.
Actually I am new to this project and I am unable to find the index.html file where I can make changes.
Thanks

**Comment by gr455** [comment]
@rushikeshadhav I think [this](https://github.com/CircuitVerse/CircuitVerse/blob/master/app/views/users/logix/edit.html.erb#L32) is the file that you're looking for, it's an html.erb file which is a ruby view file. It's very much like HTML but it supports some ruby logic in between

**Comment by rushikeshadhav** [comment]
Thanks for helping :-)

**Comment by Palaksharma23** [comment]
I am new to ope source if there is any mistakes in the pr please tell me i will solve them @gr455 @ShreyaPrasad1209

**Comment by Palaksharma23** [comment]
@gr455  i have just added style i line 730 and it is working fine 
This time i have attached the screenshots as well 

i tried to look for the class related to the dropdown menu but i am unable to find it in any css file other than (vendor/bundle/ruby/2.6.0/gems/bootstrap-typeahead-rails-0.10.5.1/vendor/assets/javascripts/bootstrap-typeahead-rails/bootstrap-typeahead.js)

**Comment by Palaksharma23** [comment]
Yes @somesh202  Thank you so much , now it is working fine 
@gr455 please once review this pr

**Comment by rushikeshadhav** [comment]
@somesh202 Do I have to add  class  tt-dropdown-menu in the users.scss with background-color: white

**Comment by somesh202** [comment]
@rushikeshadhav Yes

**Comment by Palaksharma23** [comment]
@gr455 i have added the box-shadow effect

**Comment by rushikeshadhav** [comment]
Actually I was working on this issue before @Palaksharma23 
I had asked doubts also 
So, I should make PR right

**Comment by Palaksharma23** [comment]
Yes you have commented first , but I was solving it much before and what was taking time for me was to figure out how should I set my database in educational institution box 

I have asked @gr455 him on LinkedIn to figure out the setup for the same as well . I didn't comment because I thought whenever I will do it I will make the pr 

Because in one issue I have commented but i didn't make the pr someone else makes the pr and it got merged and it was fine .

So I was also working on it and also you haven't made any PR yet 
So I guess the one who has already make the pr should get the priority please because I have already make the pr and have invested a lot of time in this and yet you have to make the pr solve the issue you can utilise this time in any other good - first issue there are lot many 
Thank you

**Comment by Palaksharma23** [comment]
Sorry for wasting your time as you are newbie , i am also newbie but if you need any kind of help or want to ask anything in future you can get my LinkedIn id in my readme you can ask me anytime . I would love to help you ☺
Thank you so much

**Comment by rushikeshadhav** [comment]
That's great. Thank you so much 
Yeah I will ask you if I need any help
As far as now I just need one help 
How do I close my PR:blush: so that yours will get merged

**Comment by Palaksharma23** [comment]
Try this link - 
https://www.linkedin.com/in/palak-sharma-57256a200 
Yes sure you can ask 👍

**Comment by harshalkaigaonkar** [comment]
Is it open still?

**Comment by tachyons** [comment]
Fixed in #2534
