### ISSUE TITLE
Remove all ocuurances of logix from codebase

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#2528]
Circuitverse was originally named as logix, but we still have references to it in the codebase and that is ambiguous to the new contributors. Replace the occurrences of logix with Circuitverse without changing any changes to the end user experience

**Comment by rushikeshadhav** [comment]
Can you assign ?

**Comment by Kartikay304** [comment]
> Under app/views we have two folders named logix
> 
> 1. logix
> 2. logix_assets
> 
> We have to change in both files?

Yes, we have to change them all... and all the routes and controllers associate with them. Currently I am working with logix folder you can start working with logix_assets. @vedant-jain03 whatsay?

**Comment by rushikeshadhav** [comment]
Hey! @Kartikay304 @vedant-jain03 can I also work with you.

**Comment by vedant-jain03** [comment]
@rushikeshadhav @Kartikay304 Lets meet in slack and divide the task, what do you think?

**Comment by rushikeshadhav** [comment]
This is my member id U024U3PF4SU
