### ISSUE TITLE
Improper thumbnail

### ISSUE THREAD

**Issue by monsij** [CircuitVerse/CircuitVerse#253]
**Describe the bug**
A proper thumbnail for test benches is not set.

**Expected behavior**
A more appropriate thumbnail must be shown, probably a default image for such objects may also seem fine. But a broken image looks odd.

**Screenshots**
![Circuit](https://user-images.githubusercontent.com/23289387/54438874-a195f200-475d-11e9-86a1-2272993b2589.JPG)

**Desktop :**
 - OS: Windows
 - Browser :chrome,
 -  Version : 73.0.3683.75

**Are you working on this issue? Yes**

**Comment by satu0king** [comment]
Yes, please have a default image.
