### ISSUE TITLE
SignUp and LogIn page icon issue

### ISSUE THREAD

**Issue by Ayannnn** [CircuitVerse/CircuitVerse#254]
Two Pages:-
https://circuitverse.org/users/sign_up
https://circuitverse.org/users/sign_in

![gsoc_LI](https://user-images.githubusercontent.com/46364732/54442758-3cde9580-4765-11e9-9518-2a6fc373bf53.jpg)
![gsoc is_LI](https://user-images.githubusercontent.com/46364732/54442762-3d772c00-4765-11e9-8226-7bac7160ec5f.jpg)

In LogIn page
1--"Sign up with Google" will be "Continue with Google"
2-- There will be a facebook icon attached with "Continue with Facebook"

In SignUp page
1--"Log in with Facebook" will be "Continue with Facebook"
2-- And also a facebook icon 

Instead of writing those things i have some suggestions.Check the Following pic.

![Screenshot (10)](https://user-images.githubusercontent.com/46364732/54443264-49172280-4766-11e9-88c6-9a3261b8970c.png)

Are you working on this issue? 
Yes

**Comment by tabishshakeel** [comment]
I will solve this issue.

**Comment by armudgal** [comment]
@tabishshakeel hi there, I think @Ayannnn is already working on it. 

@Ayannnn: I would like to change the behaviour of the solution. Mentioning 'Signing up' for both google and facebook doesn't make sense therefore it should be `Continue with Google` and `Continue with Facebook` on both Sign up and Sign-in page. 
Please do the necessary edits in the issue description.

**Comment by tabishshakeel** [comment]
Oh! I didn't know he was working on that issue so I solved this issue and already submitted a pull request.
I mentioned you there @armudgal .

**Comment by Parikshit-Hooda** [comment]
whats the progress?

**Comment by mahmodHammad** [comment]
can i work on this issue?

**Comment by Parikshit-Hooda** [comment]
@mahmodHammad I think the PR for this issue has already been opened. I intend to check the status of that so that this issue can be closed or expedited. @armudgal @satu0king

**Comment by tabishshakeel** [comment]
> whats the progress?

@Parikshit-Hooda this issue is already solved and merged. You can see the changes on the site.

**Comment by Parikshit-Hooda** [comment]
In that case, I shall go forward and close this issue.
