### ISSUE TITLE
Github Auth is not working.

### ISSUE THREAD

**Issue by somesh202** [CircuitVerse/CircuitVerse#2555]
**Describe the bug**
The functionality of user log in using github account is not working currently.

**To Reproduce**
1. Go to 'Login'
2. Click on 'Login with Github'
3. Redirects you to **`/users/sign_up`**

**Expected behavior**
Clicking on Login with Github should redirect us to github login api.

**Screenshots**

https://user-images.githubusercontent.com/77766761/137456614-2f54db48-2595-4212-ba8c-3822abd8d506.mp4

**Device Information [optional]:**
 - OS: [Linux, Windows]
 - Browser [e.g. chrome, firefox]

**Additional context**

**Are you working on this issue? (Yes/No)**
YES

**Comment by tachyons** [comment]
Unable to reproduce, I could sign in using Github

**Comment by gr455** [comment]
> Unable to reproduce, I could sign in using Github

I was not able to sign in as well
