### ISSUE TITLE
Enable LTI integrations to all users

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#2571]

**Comment by ayan-biswas0412** [comment]
Hi @tachyons when can we get the newer version of the CircuitVerse docs in deployment ,
because LMS integration depends on it.

**Comment by ayan-biswas0412** [comment]
@tachyons now as the new docs are in production, that means we are ready to launch the LMS integration.
Please take the necessary steps regarding that.
Tasks 
- [ ] Enable the feature from the Flipper admin panel 

cc @tachyons

**Comment by tachyons** [comment]
Done
