### ISSUE TITLE
Show proper name of element 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2580]
**Describe the bug**
Now when we hover on any element in stimulator section it is not showing proper name of the element, it must show proper name when hovered 

**Screenshots**

<img width="960" alt="element" src="https://user-images.githubusercontent.com/87171452/140074896-098b2e45-d89b-4dc9-9f63-c0a3f3217d26.png">

**Are you currently working on this issue**
Yes i am Currently working on this issue .

**Comment by Palaksharma23** [comment]
@gr455 @nitin10s @satu0king  can you please tell me do you need this change , as i have solved the issue but it requires some changes in names of svg files , if you say i will make the pull request.

**Comment by nitin10s** [comment]
I didn't exactly get you. Can you briefly describe it?

**Comment by Palaksharma23** [comment]
sir @nitin10s  when we hover on any item in circuit elements to pick that up , the title shows its class name not the proper name and when we search as well it doesn't get searched with proper name , it get search by the class name

**Comment by Palaksharma23** [comment]
Focus on constant Value element in these pictures 
![image](https://user-images.githubusercontent.com/87171452/142763409-13318d7d-7424-4abf-9ff8-c28c02a9450b.png)

on searching 
![image](https://user-images.githubusercontent.com/87171452/142763421-0f6cdeef-7161-4a8c-a473-ad52cc52a183.png)

![image](https://user-images.githubusercontent.com/87171452/142763424-fa3670f7-13d3-4afa-bc93-6bdb3c144d94.png)

**Comment by Palaksharma23** [comment]
@nitin10s

**Comment by nitin10s** [comment]
Oh I see now, yeah I think that's a problem. You may go ahead and open a PR

cc @gr455

**Comment by Palaksharma23** [comment]
Thank you @nitin10s , i will raise a pr soon

**Comment by gr455** [comment]
> Oh I see now, yeah I think that's a problem. You may go ahead and open a PR
> 
> cc @gr455

Yeah seems like a reasonable change

**Comment by Palaksharma23** [comment]
@gr455 @nitin10s , i have tried a lot but i am getting some error , can you please provide me a little reference in solving this issue .

**Comment by nitin10s** [comment]
you can ask for help on #coding channel in Slack specifying what errors you are getting.

**Comment by pavanjoshi914** [comment]
![image](https://user-images.githubusercontent.com/55848322/144435906-93c212e2-0cd7-401d-a007-6291037db944.png)
since you just type ```constant``` we can get the element displayed. not every user will go till ```constant value``` 


if it doesn't increase code complication or requires fewer changes in existing code then I think it can be done else not necessary

@Palaksharma23  here is the part of the code that renders search results

https://github.com/CircuitVerse/CircuitVerse/blob/master/simulator/src/listeners.js#L424

also if you are thinking of changing the element name from ```constantval to constant val ``` this will require much refactoring instead you can improve pattern matching accuracy of search bar

**Comment by Palaksharma23** [comment]
yes @pavanjoshi914 i agree with you , user will type only few letters , i will once try to change for search accuracy .☺

**Comment by Palaksharma23** [comment]
@pavanjoshi914 @nitin10s @gr455 i have corrcted the proper name of elements on hovering , can you please once review it .

**Comment by Palaksharma23** [comment]
Now i will work on improving the search accuracy as well

**Comment by Palaksharma23** [comment]
I have added the search accuracy in as well in second commit in my pull request #2673 :)
