### ISSUE TITLE
Correct position of box when user click on right side or bottom of the simulator page 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2588]
**Describe the bug**

https://user-images.githubusercontent.com/87171452/140457549-879e6a6c-b9ad-4472-80e0-3d5756706f8c.mp4

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'Stimulator'
3. Right Click on right or bottom of the page 

**Expected behavior**

https://user-images.githubusercontent.com/87171452/140457713-0b4ac734-bbb6-4d77-af39-b359439a79c1.mp4

**Are you working on this issue? (Yes/No)**
Yes i am working on this issue .

**Comment by vedant-jain03** [comment]
@Palaksharma23 change stimulator to simulator in issue title.

**Comment by Palaksharma23** [comment]
sorry, by mistake @vedant-jain03 :)
