### ISSUE TITLE
fix: Border in footer social media links look odd.

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2590]
**Describe the bug**
Border in social media links look odd.

**To Reproduce**
1. Go to 'circuitverse.org'
3. Scroll down to 'Footer'

**Expected behavior**
Remove the border

**Screenshots**
![bandicam 2021-11-05 16-13-42-250](https://user-images.githubusercontent.com/76901313/140498856-f7dfc8d8-726a-4dfd-b107-7c959fb161ba.jpg)

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by dhruvsol** [comment]
i am working on it

**Comment by tachyons** [comment]
Can you get this approved on #ux channel first

**Comment by dhruvsol** [comment]
@tachyons  where is this channel??

**Comment by tachyons** [comment]
https://circuitverse.org/slack

**Comment by nitin10s** [comment]
A hover effect was added on purpose. Please confirm if the issue is valid by a maintainer before sending PRs. Closing this.
