### ISSUE TITLE
Replace content of prompt box while closing a new circuit 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2600]
As a discussion in this pr https://github.com/CircuitVerse/CircuitVerse/pull/2586

**Describe the bug**
Whenever we click on x button in side of name of a project, we see that it is written are you sure you want to delete this circuit.
It should be Are you sure you want to close this circuit.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'simulator'
3. Make a new project by clicking on + icon next to main
4. Now click on x next to the name of the project
5. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/87171452/141826678-a9e63dc5-bf6d-4716-8fd8-4198b3c3cc7f.png)
![image](https://user-images.githubusercontent.com/87171452/141826698-edd53d5f-a17b-4882-aa64-53be646930bb.png)

**Are you working on this issue? (Yes/No)**
Yes i am currently working on this issue.

**Comment by tachyons** [comment]
>  It should be Are you sure you want to close this circuit.

Can you add your reasoning why the 'close' is better here ?

**Comment by Palaksharma23** [comment]
@tachyons yes sir in discussion of my pull request https://github.com/CircuitVerse/CircuitVerse/pull/2586 , it was concluded to replace delete keyword with close .
