### ISSUE TITLE
Misalignment of text inside a card in features section 

### ISSUE THREAD

**Issue by sakkshm26** [CircuitVerse/CircuitVerse#2607]
**Describe the bug**
The text inside the card with title "Multi Bit Buses and components" in the features section of home page is not aligned properly with the left card.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Scroll down to the Features section
3. See error

**Expected behavior**
The text should be properly aligned with the left card.

**Screenshots**
![Screenshot (410)](https://user-images.githubusercontent.com/87091886/142190684-e51d32ac-15f3-4175-90b6-9bc61126c84b.png)

**Are you working on this issue? (Yes/No)**
Yes, I have fixed this issue, let me know if I should open a PR.

**Comment by Azhrdev** [comment]
I'm currently working on this issue

**Comment by Palaksharma23** [comment]
yes @sakkshm26 i you have already fixed the issue , you can open a pr linking this issue .
