### ISSUE TITLE
Go to top button must be there at each page 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2617]
**Description.**

A back to top button must be there at each page and it shoul come only on scroll not before than that just like interactive book has one .

![image](https://user-images.githubusercontent.com/87171452/142661580-64da590f-f65e-4b05-a8a9-978cc859e8bd.png)

**Are you working on this? (Yes/No)**
Yes i have fixed the issue , will raise a pull request soon.

**Comment by ajaybhaskar-h** [comment]
I'm new to open source and I'm really interested in working on this issue.
Is it still open?

**Comment by Palaksharma23** [comment]
@ajaybhaskar-h i am currently working on this issue . 
please try on different one

**Comment by ajaybhaskar-h** [comment]
@Palaksharma23 Ok cheers
