### ISSUE TITLE
Colour difference in hover and click 

### ISSUE THREAD

**Issue by harshagrawal523** [CircuitVerse/CircuitVerse#2618]
**Describe the bug**
On the home page of website in the navbar , when I hover on "Getting Started" the color is different than when I click it. 

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'Getting Started'
3. See colour difference in hover and click

**Expected behavior**
The colour should be same as it looks more professional that way and all other navlinks have same colour in hover and click.

**Screenshots**
Hover image

<img width="1333" alt="hover" src="https://user-images.githubusercontent.com/77069304/142676077-abf3c795-3b16-42cd-a1aa-bfe05fd34105.png">

Click Image

<img width="1333" alt="Screenshot 2021-11-20 at 00 10 40" src="https://user-images.githubusercontent.com/77069304/142676169-7448acf7-7574-4a3c-8b2b-6efe68f93afa.png">

**Device Information [optional]:**
 - macOS
 - Browser [Chrome]
 

**Are you working on this issue? (Yes/No)**
Yes I am working on this issue and will provide the PR soon.

**Comment by reejuBhattacharya** [comment]
Hi, anyone still working on this issue, or can I work on it?

**Comment by harshagrawal523** [comment]
Hi @reejuBhattacharya , Yes I am working on it and will provide a PR soon!

**Comment by reejuBhattacharya** [comment]
Ok cheers!

**Comment by Creatoon** [comment]
I have solved the issue, can i make a pr? as the issue has not been resolved since 22 days.

**Comment by harshagrawal523** [comment]
> @harshagrawal523 This is the expected behavior for dropdown nav links similar to user dropdown. @nitin10s

Okay sir , I will close the issue.

**Comment by Creatoon** [comment]
@vedant-jain03 Thanks for confirming.
