### ISSUE TITLE
feat: add custom scroll theme for circuitverse

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#2619]
**Is your feature request related to a problem? Please describe.**
Every modern website nowadays has its custom scrolling theme. 

**Describe the solution you'd like**
Using webkit.

**Are you working on this? (Yes/No)**
Yes.

**Comment by tachyons** [comment]
Closing as I don't see any value addition by doing this

>  Every modern website nowadays has its custom scrolling theme.

This is not accurate.
