### ISSUE TITLE
Add Some Label Fonts  in the Properties Dialog Box

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#2626]
**Describe the solution you'd like**
Add Some Label Fonts in the Properties Dialog Box 

**Additional context**
<img width="949" alt="2021-11-21 (9)" src="https://user-images.githubusercontent.com/89515816/142766247-d2e5584c-0854-4f52-a048-6fbc156542f9.png">
<img width="956" alt="2021-11-21 (8)" src="https://user-images.githubusercontent.com/89515816/142766481-7f3a3426-04a6-4575-8cd5-e5678b8eca2a.png">

**Are you working on this? (Yes/No)**
Yes, I am working on this issue...

**Comment by ajaybhaskar-h** [comment]
I would like to work on it.
Is it open?

**Comment by Prerna-0202** [comment]
@ajaybhaskar-h , Currently I am working on this issue. Please try on different one :)

**Comment by ajaybhaskar-h** [comment]
@Prerna-0202 Ok

**Comment by Prerna-0202** [comment]
@gr455 @tachyons Can you Please tell me that, Is this feature request is valid/right? Should I make a pr for this issue?

**Comment by Palaksharma23** [comment]
Can i take this up @Prerna-0202

**Comment by tachyons** [comment]
This will make things complex as system fonts will vary with devices and embedding fonts with circuits are expensive. 

cc @satu0king @nitin10s

**Comment by gr455** [comment]
> This will make things complex as system fonts will vary with devices and embedding fonts with circuits are expensive. 
> 
> cc @satu0king @nitin10s 

I also don't see much value in custom fonts (maybe dyslexia friendly fonts for accessibility). It's unnecessary complexity.

**Comment by gr455** [comment]
> @gr455 @tachyons Can you Please tell me that, Is this feature request is valid/right? Should I make a pr for this issue? 

I'm so sorry for the late response this slipped under my notifications 😓
