### ISSUE TITLE
Fork circuit action should be POST request, not GET request

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#2628]
Currently, forking project is done via http GET request, which need to converted into POST request to enable bultin CSRF protection in rails

**Comment by Kartikay304** [comment]
I want to work on this issue

**Comment by vedant-jain03** [comment]
@tachyons There is a typo error in the title of the issue.

**Comment by divyesh-rathod** [comment]
Is the issue still open? May I work on it?
@tachyons

**Comment by tachyons** [comment]
This is work in progress
