### ISSUE TITLE
Understanding code problem

### ISSUE THREAD

**Issue by mohamedar97** [CircuitVerse/CircuitVerse#263]
I was trying to grasp how the CircuitVerse app is implemented, like understanding the code and so, and I’m facing a few problems.
First I see objects being used but I can’t see where they are defined example is the ‘simulationArea’  (public/js/) used In many files,
Same goes for some functions and variables like for example ‘errorDetected’, ‘updateCanvas’ ,’updateSimulation’ , etc. (public/js/listeners.js)
Second is that I see functions defined but never see them being used like ‘add’ , ‘swap’, ‘pop’ ,. Etc. (public/js/eventQueue.js) 

I know these are a lot of questions so I would appreciate if anyone can answer them or at least direct me to the correct path to finding out by myself

**Comment by shubhankarsharma00** [comment]
A shortcut to learning all this by yourself would be to get a good IDE like vs code and look for definitions and search for use of class methods. simulationArea is id of the canvas on which the circuit is drawn.

**Comment by mohamedar97** [comment]
I do have vscode installed but whenever i click 'go to definition' it says not found.
Also I'm not talking about the simulationArea id , I'm talking about the object

**Comment by mohamedar97** [comment]
i managed to find at last in the logix.js but there were too many references of it so i missed it

**Comment by satu0king** [comment]
Please reach out to us on gitter with specific questions, we will be happy to help you out.
