### ISSUE TITLE
Understanding code problem

### ISSUE THREAD

**Issue by mohamedar97** [CircuitVerse/CircuitVerse#264]
I was trying to grasp how the CircuitVerse app is implemented, like understanding the code and so, and I’m facing a few problems.
First I see objects being used but I can’t see where they are defined example is the ‘simulationArea’  (public/js/) used In many files,
Same goes for some functions and variables like for example ‘errorDetected’, ‘updateCanvas’ ,’updateSimulation’, 'update()' , etc. (public/js/listeners.js)
Second is that I see functions defined but never see them being used like ‘add’ , ‘swap’, ‘pop’ ,. Etc. (public/js/eventQueue.js) 

I know these are a lot of questions so I would appreciate if anyone can answer them or at least direct me to the correct path to finding out by myself

**Comment by tachyons** [comment]
You can ask the specific questions in gittter channel. Also it will be great if you can help us by documenting them in the project wiki

**Comment by mohamedar97** [comment]
I would be more than happy to help with this, but i'm not so familiar with github so can you elaborate a little bit more how do you want me to help with the docs?

**Comment by tachyons** [comment]
You can add code related documentations here https://github.com/CircuitVerse/CircuitVerse/wiki

**Comment by mohamedar97** [comment]
so  i should add a page called ' source code explanation' and add code related stuff to it. right?
