### ISSUE TITLE
Cannot render console from 172.19.0.1! Allowed networks: 127.0.0.0/127.255.255.255, ::1

### ISSUE THREAD

**Issue by Sarfraz-droid** [CircuitVerse/CircuitVerse#2643]
I was trying to run the environment in Docker but Images/Icons are not loading in localhost:3000/simulator.
I did sent it on slack but got no reply

1. Run docker-compose up
2. open localhost:3000 
3. Go to localhost:3000/simulator
4.  Circuit elements not loading

**Expected behavior**
It should show the circuit elements

**Screenshots**
![image](https://user-images.githubusercontent.com/73013838/143025486-e89ec1fd-4f4d-4f15-8523-b1440c3ed26b.png)
![image](https://user-images.githubusercontent.com/73013838/143025515-f98e7ad2-53aa-4ad6-b3ae-ffdce755d223.png)
![image](https://user-images.githubusercontent.com/73013838/143025536-b929a29c-7b5d-4b76-8079-22315a38ddf4.png)

**Device Information [optional]:**
 - OS: Win 11
 - Browser Edge

**Are you working on this issue? No**

**Comment by Rick-mad-lab** [comment]
Hey It might a problem of image source file

**Comment by Sarfraz-droid** [comment]
How can I fix it?🤔

**Comment by Rick-mad-lab** [comment]
Find the resources folder

**Comment by Sarfraz-droid** [comment]
then?

**Comment by Rick-mad-lab** [comment]
hey just remove old docker container and then make a new container and clone it again  and deploy it again.

**Comment by Sarfraz-droid** [comment]
till getting errors :/

**Comment by Rick-mad-lab** [comment]
Hmm 🤔 wait let me try

**Comment by Sarfraz-droid** [comment]
still not solved yet :/
