### ISSUE TITLE
Hover effect on social media icons 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2655]
When we hover on social media icons there should be some hover effects 

![image](https://user-images.githubusercontent.com/87171452/143731616-9561aa63-315d-431d-9ff4-4d642796a468.png)

**Are you working on this issue? (Yes/No)**
Yes , i am working on this issue , and will raise a pull request soon.

**Comment by FaizAlam** [comment]
Internet Archive is a different organization.

**Comment by Palaksharma23** [comment]
@FaizAlam by mistake
