### ISSUE TITLE
Circuit elements not displaying information when hovered over.

### ISSUE THREAD

**Issue by divyesh-rathod** [CircuitVerse/CircuitVerse#2656]
**Describe the bug**
If the circuit elements are searched in the search box then hovered over they would not display information about them

**To Reproduce**
1. Go to 'Circuit Elements'
2. Click on 'Search box'
3. Type any circuit element name or letter  'eg~b'
4. Hover over the circuit element
5. See the error

**Expected behavior**
While circuit elements being hovered over,First by searching them from search box they would display the information about them. 

**Screenshots**
![Screenshot 2021-11-28 175218 (2)_LI](https://user-images.githubusercontent.com/70877143/143768562-c75e3965-ce4e-448c-a3a0-64da074375c2.jpg)
The Button element is not displaying information about itself.

![Screenshot 2021-11-28 175112 (2)](https://user-images.githubusercontent.com/70877143/143768597-162db49a-00ea-4ab4-b24d-724d6180798e.png)
Normally the Button would display the information about itself. 

**Device Information 
 - OS: Windows 10
 - Browser Chrome

**Are you working on this issue? (Yes/No)**
YES i am working on this issue. Will Create a PR soon.

**Comment by Palaksharma23** [comment]
@divyesh-rathod it is the copy of #2580 and I am working on it :)

**Comment by divyesh-rathod** [comment]
@Palaksharma23 it NOT the copy of #2580 I went through it. #2580 deals with not displaying proper names and #2656 is all about displaying information about the circuit element.
