### ISSUE TITLE
Using button instead of link on "Learn Logic Design" link for a consistent UX design.

### ISSUE THREAD

**Issue by h2o-Noob** [CircuitVerse/CircuitVerse#2666]
**Is your feature request related to a problem? Please describe.**
Not a problem, but an enhancement suggestion on using a button instead of a link for a consistent UX design
![linkimg](https://user-images.githubusercontent.com/85777684/144718406-2bb7d999-5703-4a46-a502-4fbeefb22fd1.png)

**Describe the solution you'd like**
Instead of using a link, a button with similar functionality as the link would look better in my opinion.
![buttonimg](https://user-images.githubusercontent.com/85777684/144718563-bfe72407-94ce-4fc4-ae8a-5b971b64b759.png)

**Describe alternatives you've considered**
None yet.
**Additional context**
Nothing
**Are you working on this? (Yes/No)**
Yes I am

**Comment by h2o-Noob** [comment]
#2667

**Comment by sulogna2001** [comment]
Can I work on this feature?

**Comment by tachyons** [comment]
It is an intentional design to give more importance to simulator button

**Comment by h2o-Noob** [comment]
> It is an intentional design to give more importance to simulator button 

Alright 👍🏻
