### ISSUE TITLE
Use enums to handle model status'

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#267]
**Is your feature request related to a problem? Please describe.**
It is often difficult to figure out the exhaustive set of values that a key should get in a model. 
For example: `project_access_type` can have only three values - `Private, Public, Limited access`, though `Public` and `Private` are pretty evident,  `Limited access` isn't. 

**Describe the solution you'd like**
We can use enums in our model for this. 
[Reference](http://vaidehijoshi.github.io/blog/2015/02/03/when-enough-is-enough-how-to-know-when-to-use-enums/)

**Describe alternatives you've considered**
An alternative is using boolean values for each status, but this won't be feasible when the number of status increases as a separate column will have to be added for each one of them. 

**Additional context**
Enums can also be used for creating roles for users(Currently we have a boolean coloum of admin in the users model for this). It might be useful if we choose to add more roles in the future. 
It can also be used for the status of assignments. 

**Are you working on this? (Yes/No)**
This will require migrations that will have to be absolutely correct. Measures will have to be taken to ensure data can be restored if anything goes wrong. In the light of all the work that is going on right now, I think this should not be worked on right now, but later.

**Comment by tachyons** [comment]
Also solution should contain proper data migration. Existing statuses should not be lost
