### ISSUE TITLE
You haven't add 8x1 multiplexer in circuit verse why ..?😤😤 .I have to do my task tomorrow is my last date of assignment submission.


### ISSUE THREAD

**Issue by Maddiprog** [CircuitVerse/CircuitVerse#2674]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by h2o-Noob** [comment]
@Maddiprog I don't think it's a bug, It's more like a feature request.

**Comment by tachyons** [comment]
Feature requests should be tagged accordingly, also we can't commit timeframe for the features as the development is handled by the volunteers
