### ISSUE TITLE
Find a replacement for bootstrap-tagsinput

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#2683]
bootstrap-tagsinput is no longer maintained and having a security issue, this package need to be replaced with a library which is being maintained

**Comment by Kartikay304** [comment]
We can use [Select2](https://github.com/select2/select2)  or [selectize js ](https://github.com/selectize/selectize.js) for bootstap-tagsinput replacement.

**Comment by h2o-Noob** [comment]
@tachyons @Kartikay304 can I work on this one?

**Comment by Palaksharma23** [comment]
i would love to take up this issue , if no one is working on it .

**Comment by tachyons** [comment]
@Kartikay304 Both seems being developed actively, Can you check for 
- Size of the library (smaller the better)
- UI consistency with existing CV theme

**Comment by Kartikay304** [comment]
> @Kartikay304 Both seems being developed actively, Can you check for 
> - Size of the library (smaller the better)
> - UI consistency with existing CV theme

Sure

**Comment by Kartikay304** [comment]
> @Kartikay304 Both seems being developed actively, Can you check for
> 
> * Size of the library (smaller the better)
> * UI consistency with existing CV theme

[selective js](https://github.com/select2/select2)  is smaller and have UI similar to Cv theme

**Comment by tachyons** [comment]
select2 looks good, feel free to proceed

**Comment by kushalShukla-web** [comment]
Guys is this issue still open

**Comment by tachyons** [comment]
@kushalShukla-web Yes

**Comment by Prerna-0202** [comment]
I would like to work on this issue @tachyons.

**Comment by tachyons** [comment]
Go ahead
