### ISSUE TITLE
Adding scroll-top button in homepage

### ISSUE THREAD

**Issue by Sayan-Maity** [CircuitVerse/CircuitVerse#2701]
**Is your feature request related to a problem? Please describe.**
Yes
This will help user easily to go to the top portion of the page without scrolling by mouse

**Describe the solution you'd like**
I will make a simple button 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Are you working on this? (Yes/No)**
Yes, and I will soon make a PR

**Comment by vedant-jain03** [comment]
@Sayan-Maity 
This is not needed in CV, kindly check what maintainer say about this in this thread: https://github.com/CircuitVerse/CircuitVerse/pull/2660#issuecomment-986515311
Kindly close this issue.

**Comment by Sayan-Maity** [comment]
> @vedant-jain03 , are you sure
