### ISSUE TITLE
Centering the social icons in the footer

### ISSUE THREAD

**Issue by rucha0702** [CircuitVerse/CircuitVerse#2712]
**Describe the bug**
Misalignment of icons: There is a non-uniform margin and padding on the icons.

**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to 'footer'
4. See the icons

**Screenshots**

Before: 
![original](https://user-images.githubusercontent.com/77936051/146054938-957d456f-b3a8-48a3-9ac6-4b4b4bae06fb.png)
After: 
![edited](https://user-images.githubusercontent.com/77936051/146055072-c493edcb-742f-4fa7-92d0-5c5b4039791f.png)

**Are you working on this issue? (Yes/No)**
 Yes, I will create a PR if the issue is appproved.

**Comment by NerdyLucifer** [comment]
May I work on this issue?

**Comment by denver-39** [comment]
@rucha0702  I've fixed this issue should I make PR 
![Screenshot 2021-12-28 114145](https://user-images.githubusercontent.com/88855792/147534687-081108bb-4bd1-4baf-a491-637f23b8bf51.png)
?

**Comment by gr455** [comment]
Adding more to this, currently the borders for the icons is also visible. It would be great if those are hidden

**Comment by PrakritiShetty** [comment]
Hi I'm working on this issue. Goals: 1. Remove the bounding box for the twitter icon 2. Make the bounding box for LinkedIn a square rather than a circle. 3. Work on incorporating a GitHub icon if possible

**Comment by legendarykamal** [comment]
hey @vedant-jain03 the PR's that was proposed i found that it has conflicts, so should I work on this?
https://github.com/CircuitVerse/CircuitVerse/pull/2922

**Comment by me-aashish** [comment]
@rucha0702 can I work on this issue if it is still open ?

**Comment by joannasjohnraj** [comment]
Is this issue still open? I would like to work on it.

**Comment by sambhavgupta0705** [comment]
Hey @vedant-jain03 is this issue still open? I want to work on this

**Comment by MrNewbie-KH** [comment]
hi, can I work on this issue?

**Comment by rishuraj1** [comment]
Is this issue still open? I really want to contribute and I might have a fix for this.

**Comment by harshsindhu0408** [comment]
Hey @rucha0702 could I work on this issue I have a fix for this one.

**Comment by Sandeep77942** [comment]
Is this still open? I want to fix it

**Comment by theslowdeveloper** [comment]
can i get assigned on this ? @vedant-jain03, I thought this issue was idle for a long time so I made a PR.
