### ISSUE TITLE
Localeapp::MissingApiKey in CircuitverseController

### ISSUE THREAD

**Issue by camperjett** [CircuitVerse/CircuitVerse#2713]
**Describe the bug**
Critical error which seems to have come after last few commits. The project doesn't functions properly. Error Localeapp::MissingApiKey is thrown.

**To Reproduce**
1. Open gitpod environment (or pull latest changes in your local repository)
2. Run ```docker-compose up```
3. open localhost:3000 in browser

**Expected behavior**
A red page shows up with error Localeapp::MissingApiKey.

**Screenshots**
![image](https://user-images.githubusercontent.com/84286404/146136516-10492142-a11a-4c92-baf9-ee12698ffc29.png)

**Device Information [optional]:**
 - OS: Ubuntu
 - Browser Chrome

**Possible Solution:**
1. Revert back to last stable commit.

**Comment by camperjett** [comment]
I checked out the previous commit (59e52d6f8efeac73723e8dfc6d5b5fdf1f1ff897) "Cleanup outdated instrcutions" which seems stable. @tachyons

**Comment by tachyons** [comment]
Fixed in 0bb5b872665b6439ce640cf238f3cf88e9b21235
