### ISSUE TITLE
Changes to layout height gets reverted after switching to another circuits

### ISSUE THREAD

**Issue by SunYiZheXinKe** [CircuitVerse/CircuitVerse#272]
Changes to layout height gets reverted after switching to another circuits.

To Reproduce:
1. Create a circuit
2. Click "Edit layout", add a bunch of height, and save the change
3. Click "Edit layout" again, and confirm that the change is saved
4. Switch to another circuit, then switch back again
5. Click "Edit layout", and notice that the change of height is reverted. However, it shouldn't.

This bug only affects the height of a layout.

I'm not working on this issue.

**Comment by NavonilDas** [comment]
I am Working on it.
