### ISSUE TITLE
Signout link in Simulator Header is sending GET call instead of POST

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#2746]
**Describe the bug**
Signing Out from the simulator throws an error!

**To Reproduce**
1. Go to https://circuitverse.org/
2. sign in to your Account
3. Go to https://circuitverse.org/simulator
4. click on your name (right top in navbar)
5. try to signOut from there
6. throws an error 
(you were redirected to https://circuitverse.org/users/sign_out with the message, 404 OOPS, THE PAGE YOU ARE LOOKING FOR CAN'T BE FOUND! )

**Expected behavior**
User must be Sign Out normally without any error.

**Screenshots**

https://user-images.githubusercontent.com/76155456/147589287-4d9f57e1-a4df-4500-8dca-45d84080509b.mov

**Device Information [optional]:**
 - OS: macOS
 - Browser Chrome

**Comment by tachyons** [comment]
Issue is that signout link is sending GET call instead of DELETE

**Comment by ankanbag101** [comment]
Anyone working on this issue?

**Comment by pulkit-30** [comment]
> Anyone working on this issue?

Yes 👍🏽

**Comment by pulkit-30** [comment]
> > Anyone working on this issue?
> 
> No, You can Go ahead 👍🏽

**Comment by raghavluthra20** [comment]
Does this issue still need work? I'd be happy to contribute

**Comment by pariksh1th** [comment]
I like to work on this, it may become my first contribution.
Even I am facing this issue.
-  OS: MacOs
- Browser: Safari

**Comment by vedant-jain03** [comment]
@pariksh1th thankyou for your interest but the PR for this issue is under review.

**Comment by SethiVanshika** [comment]
Is this closed !

**Comment by Subhraneel77** [comment]
Can I give it a try?

**Comment by vedant-jain03** [comment]
@khareyash05 are you working on this issue?

**Comment by me-aashish** [comment]
@vedant-jain03 can you please assign it to me if this issue is still open and others are not working on this ?

**Comment by rakshitgondwal** [comment]
@vedant-jain03 I guess no one has been solving this issue lately, so can I try to solve this issue?

**Comment by Prerna-0202** [comment]
Hey @tachyons, In this issue, if we change the `anchor tag` to `button_to`, then it is working.
So Can we do that to solve this issue?
