### ISSUE TITLE
 Decimal to BCD and vice versa

### ISSUE THREAD

**Issue by Kunal0220** [CircuitVerse/CircuitVerse#2749]
**Is your feature request related to a problem? Please describe.**
This feature will be a tool to convert Decimal to BCD and Vice-Versa.

**Describe the solution you'd like**
I want the user to enter a Decimal/BCD code , according to their choice and in return the get the appropriate result.

**Describe alternatives you've considered**

**Additional context**
You can have a look on google about how to conversion works and work on the same concept

**Are you working on this? (Yes/No)**
Yes

**Comment by Prerna-0202** [comment]
This issue has been solved in pr #2719.
You can try on other open issues...

**Comment by Kunal0220** [comment]
Ok cool , I think i'll find some other issue then.
Thank You.
