### ISSUE TITLE
Bug in the dashboard section

### ISSUE THREAD

**Issue by Snehagupta1907** [CircuitVerse/CircuitVerse#2752]
**Describe the bug**
-hovering style of choose file button is not working
**Expected behavior**
before

https://user-images.githubusercontent.com/96808735/147912221-7753136b-b762-47b2-8939-eda08930b9ee.mp4

after

https://user-images.githubusercontent.com/96808735/147912245-3e134f85-73bf-4a01-a801-6ce837b70654.mp4

**Device Information [optional]:**
 - OS: windows
  - Browser -chrome
**Are you working on this issue? 
Yes

**Comment by Kunal0220** [comment]
Hey @Snehagupta1907  , I think I can resolve this issue , Do you need some help ?

**Comment by Snehagupta1907** [comment]
> Hey @Snehagupta1907, I think I can resolve this issue, Do you need some help?

I have already made a PR for this issue
