### ISSUE TITLE
Adding new components for fluid circuits

### ISSUE THREAD

**Issue by deek121477** [CircuitVerse/CircuitVerse#2756]
**Is your feature request related to a problem? Please describe.**
 To add new components to the simulator. This component can be useful for fluid and hydraulic systems diagrams.

**Describe the solution you'd like**
By adding new features in  simulator can also help for designing various control system designs.

**Are you working on this? (Yes/No)**
Yes

**Comment by tachyons** [comment]
Hi @deek121477, Circuitverse is a digital circuit simulation platform. Adding control system simulation is out of the scope of this project
