### ISSUE TITLE
Cannot sign-out from simulator

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#2760]
**Describe the bug**
Clicking sign-out from `/simulator` produces a 404 Not found.

**To Reproduce**
1. Go to `/simulator`
2. Click on your profile on the top right
3. Click sign-out

**Expected behavior**
Must sign out similar to how it happens on other pages

**Are you working on this issue? (Yes/No)**
No

**Comment by ankanbag101** [comment]
Can I work on this issue?

**Comment by csking101** [comment]
Can I work on this as my first issue?

**Comment by pulkit-30** [comment]
Hey @gr455, I think we just open the same issue 😅 #2746

**Comment by gr455** [comment]
> Hey @gr455, I think we just open the same issue sweat_smile #2746

Whoops, I'll close this one. Moved to #2746
