### ISSUE TITLE
feat: Filter functionality in dashboard section for circuits

### ISSUE THREAD

**Issue by shukapurv** [CircuitVerse/CircuitVerse#2764]
**Is your feature request related to a problem? Please describe.**
If there are lots of projects its hard to find only private or public projects so- a filter button in each section(My circuits, Favorite Circuits, Collaborated Circuits) for projects to filter for specific access types.

**Describe the solution you'd like**

- creating an option to select for access type in each section
- Filtering the locals according to the selected filter option.

**Are you working on this? (Yes/No)**
Yes

**Comment by rachit3006** [comment]
Can I also help with working over this issue?

**Comment by uraj323** [comment]
can I work on this issue
