### ISSUE TITLE
safe html for description on tags page

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#277]
**Describe the bug**
when the html is not plain the whole html of project description is rendered

**To Reproduce**
1. Go [here](https://circuitverse.org/projects/tags/test)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by satu0king** [comment]
Actually, it is already html_safe, that is why you are seeing the HTML as text in the browser. @tachyons is that right?

**Comment by tachyons** [comment]
By default rails consider text as unsafe because it is a potential xss target. Do we really want to allow HTML in the description ?

**Comment by tachyons** [comment]
Calling html_safe will mark the text as safe, but since it is user entered field, we should not trust it. So html_safe is dangerous here

**Comment by tachyons** [comment]
See https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html

**Comment by shubhankarsharma00** [comment]
@satu0king here is what I see right now
![image](https://user-images.githubusercontent.com/32474302/54655017-414cda80-4ae6-11e9-8aa2-401a20795e29.png)

**Comment by shubhankarsharma00** [comment]
@tachyons my PR now uses sanitize but the description in show_project uses html_safe should I change that too?

**Comment by satu0king** [comment]
Yes use santize, Actually, we were using sanitize previously, I don't recollect why we changed to this.
