### ISSUE TITLE
Simulator tutorial message box displayed improperly 

### ISSUE THREAD

**Issue by Traitor000** [CircuitVerse/CircuitVerse#2776]
**Describe the bug**
On opening the simulator of circuit verse for the first time(or on incognito mode) , the last tutorial message box is not displayed properly.

**To Reproduce**
1. Open a new incognito window / Private Window.
2. Go to https://circuitverse.org/simulator .
3. Click on Next until the last tutorial message box .
4. See error (Message box hangs at the top) .

**Expected behavior**
The last message box of the tutorial should be displayed properly inside the window like previous boxes.

**Screenshots**
![image](https://user-images.githubusercontent.com/75945709/149001666-08156b41-6b77-4fa0-a475-643e750fdd01.png)

Uploading CircuitVerse - Digital Circuit Simulator online - Personal - Microsoft​ Edge 2022-01-12 00-21-28.mp4…

**Device Information [optional]:**
 - Windows 11 
 - chrome Version 97.0.4692.71 (Official Build) (64-bit) &
 - brave V1.34.80
 - Edge 96.0.1054.62
 

**Are you working on this issue? (Yes/No)**
Yes

**Comment by vedant-jain03** [comment]
Hey @Traitor000 This is already begin raised #2348 and PR is also being raised and waiting for merge #2360

**Comment by Traitor000** [comment]
Sure ! So I am closing this issue @vedant-jain03 . Let me know if you have some issues in mind that I can work on or any other way I can contribute.
