### ISSUE TITLE
Random password suggestions 

### ISSUE THREAD

**Issue by Palaksharma23** [CircuitVerse/CircuitVerse#2781]
We should add a feature to suggest random and strong password to the user like other sites do 

Whenever a user click on password while signing up on the circuitverse, we can show up an option saying "Use Suggested password"

and then if a user click on that option we can generate a strong password 

![image](https://user-images.githubusercontent.com/87171452/149268421-9cdf35b8-5211-477d-b9cc-ad45c1ac7c49.png)

**Are you working on this? (Yes/No)**
yes

**Comment by tachyons** [comment]
Circuitverse signup page works well with existing password managers, they provide password generation and password autofill functionalities. Doing that ourselves is not secure and an overkill
