### ISSUE TITLE
Copyright is not changed to 2022

### ISSUE THREAD

**Issue by ZaidKhan2002** [CircuitVerse/CircuitVerse#2789]
**Describe the bug**
It's not bug, It's just on learn page at footer copyright year is 2021.

**To Reproduce**
1. Go to <a href="https://learn.circuitverse.org/">Learn</a> 
2. At bottom in footer Copyright year is not changed
3. See error

**Expected behavior**
 It should be 2022 I suppose.

**Screenshots**
<img width="690" alt="Screenshot 2022-01-16 at 4 02 54 PM" src="https://user-images.githubusercontent.com/71960989/149656908-04f51f31-fd12-4f49-804b-4740a71eb200.png">

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by ZaidKhan2002** [comment]
It should be 2021 only or it should be 2022. Like on official mainpage and other pages it's 2022.

**Comment by St80ene** [comment]
Hi, @ZaidKhan2002 I would love to work on this issue. Thanks

**Comment by St80ene** [comment]
I would love to be assigned to handle this issue @ZaidKhan2002

**Comment by pulkit-30** [comment]
Related to [Interactive-Book](https://github.com/CircuitVerse/Interactive-Book)

**Comment by ZaidKhan2002** [comment]
Should I close this issue here ?

**Comment by pulkit-30** [comment]
Yes, 
Please open same at Interactive-Book

**Comment by ZaidKhan2002** [comment]
Sure.
