### ISSUE TITLE
Unsuitable width of form fields with error 

### ISSUE THREAD

**Issue by shukapurv** [CircuitVerse/CircuitVerse#2790]
**Describe the bug**
Unsuitable width of fields with error in sign-up page.

**To Reproduce**
1. Go to 'Sign up page'
2. Sign up with all fields blank.

**Expected behavior**
Width of the fields should be fixed.

**Screenshots**
![Screenshot from 2022-01-17 04-10-44](https://user-images.githubusercontent.com/73848723/149681134-0d21ed59-6ac0-4136-80c0-6d2f04ba95fe.png)

**Device Information [optional]:**
 - OS: Ubuntu
 - Browser: Chrome

**Are you working on this issue? Yes**

**Comment by Prerna-0202** [comment]
Duplicate of #2603

**Comment by shukapurv** [comment]
@Prerna-0202 sorry for the Duplicate issue but I think #2603 is only related to the password field's positioning and this issue is related to width of all the fields.

**Comment by KhanFiza896** [comment]
Is this issue still open?
