### ISSUE TITLE
Navbar toggler not working on groups page

### ISSUE THREAD

**Issue by shukapurv** [CircuitVerse/CircuitVerse#2795]
**Describe the bug**
Navbar toggler not expanding on the groups page.

**To Reproduce**
1. Go to any of your groups view page.
2. Click on any navbar toggler.

**Expected behavior**
Togglers should expand on click.

**Screenshots**
https://user-images.githubusercontent.com/73848723/149690122-85d52159-ec16-4d42-b990-bbbf75452463.mp4

**Device Information [optional]:**
 - OS: Ubuntu
 - Browser: Chrome

**Are you working on this issue? Yes**

**Comment by vedant-jain03** [comment]
Duplicate #2739
