### ISSUE TITLE
Selection in simulator window.

### ISSUE THREAD

**Issue by Harshil-Jani** [CircuitVerse/CircuitVerse#2796]
**Is your feature request related to a problem? Please describe.**

Suppose you are designing some circuit. Then you made one section of circuit incorrect. Now you want to delete that section. Currently you have to select individual elements and delete them. Instead, It would be more good for a user to select some elements together and delete them in bulk. 

**Describe the solution you'd like**
By clicking `Ctrl` key and selecting on the screen, Multiple elements must be selected and then on clicking delete, They must be deleted in bulk.

**Additional context**
A similar feature can be encountered in LT Spice Simulator. Where you can just select few elements and delete them all together. Similarly We can implement this to the web version of CircuitVerse Simulator.

**Are you working on this? (Yes/No)**
Yes (I am willing to work on this after approval from maintainers)

**Comment by SethiVanshika** [comment]
Can I work on this issue.

**Comment by Tanmoy741127** [comment]
@vedant-jain03 @tachyons  can you assign this feature-request to me ?
