### ISSUE TITLE
Ability to hide components other than output

### ISSUE THREAD

**Issue by MechaFinch** [CircuitVerse/CircuitVerse#282]
**Is your feature request related to a problem? Please describe.**
I'd like to have the ability to hide wiring and only see outputs such as LEDs and TTY text, as when wiring output such as LEDs to be like screens, the wires get in the way.

**Describe the solution you'd like**
Some option or button that toggles the visibility of wires and/or non-output components.

**Describe alternatives you've considered**
There isn't much else that could be done, except for making larger LED displays (the primary case)

**Additional context**
[Messy example](https://circuitverse.org/users/4002/projects/11772)
As can be seen in the example, the splitters used to get data to the LEDs block a good portion of the display

**Are you working on this? (Yes/No)**
No

**Comment by satu0king** [comment]
The way I understand is you want to have a way to hide the circuitry for testing. So both Inputs and Outputs should be visible but not other circuits elements. 

If we were to implement the feature we could mark certain elements as IO and dim/reduce the brightness of others either completely as you mentioned or partially.

**Comment by fpintos** [comment]
Hi @MechaFinch 

One way to hide circuitry is to create a sub-circuit.

In your example, you can create sub-circuits that will hold the wires internally and expose the pins where you connect the leds in the main circuit. Obviously it requires a little more work, but it is doable.

Here's an example: https://circuitverse.org/users/1935/projects/5524
In the "16-pixel" row circuit I have the "wires" and "pins" for the LEDs.
Then the main circuit connects the LEDs to them and it all looks nice and clean.

That being said, we also made the SquareRGB led with the ability to have long pins, so the circuitry can be out of the way. Satvik built a nice example with it. See #104
