### ISSUE TITLE
pg gem duplication in Gem file 

### ISSUE THREAD

**Issue by Sadat97** [CircuitVerse/CircuitVerse#284]
While I was setting up the environment I noticed a warning,
![Screenshot from 2019-03-20 22-05-32](https://user-images.githubusercontent.com/26658549/54715551-654b0300-4b5c-11e9-8a1d-3d919c94dcd3.png)

Are you working on this issue? (Yes/No)
Yes

**Comment by tachyons** [comment]
Fixed in #285
