### ISSUE TITLE
Adding dark mode 

### ISSUE THREAD

**Issue by PaarthAgarwal** [CircuitVerse/CircuitVerse#2854]
While exploring the website I found the dark mode feature in learn tab so I'd like to add a dark mode like the one present in the interactive book to make the UI more consistent, user friendly and attractive.
Like this

![Screenshot 2022-01-28 151027](https://user-images.githubusercontent.com/86092410/151524086-41706c4e-ee7d-494a-af55-e7eb7b7fc4e1.png)

**Are you working on this? (Yes)**

I want to work on this issue. Please assign it to me

**Comment by vedant-jain03** [comment]
@PaarthAgarwal This is already being raised #2823
