### ISSUE TITLE
While creating a new group if i enter a blank space it is accepting blank space as group name

### ISSUE THREAD

**Issue by mudassir1231** [CircuitVerse/CircuitVerse#2855]
**Describe the bug**
While creating a new group if i enter a blank space it is accepting blank space as group name

**To Reproduce**
1. Go to 'Create group'
2. Enter blank space as group name 
3. Click on save

**Expected behavior**
it should show alert when blank space is entered

**Screenshots**

![Screenshot (139)](https://user-images.githubusercontent.com/88880988/151566580-3180d966-b59f-4a47-b28d-8a7a93739bd9.png)

![Screenshot (140)](https://user-images.githubusercontent.com/88880988/151566990-e0c0882b-ffbc-49e8-8014-eb1f7706e7a8.png)

![Screenshot (138)](https://user-images.githubusercontent.com/88880988/151567081-b3280f61-8707-481d-9c2e-c9b9531fde23.png)

**Are you working on this issue? (Yes)**

**Comment by prakhar3062** [comment]
assign it to me i will work on it

**Comment by mudassir1231** [comment]
I am already working on it I am waiting for the approval

**Comment by prakhar3062** [comment]
okay

**Comment by riteshsonawane1372** [comment]
????

**Comment by Subhadiptech** [comment]
Is this still an issue or has been solved ?

**Comment by vedant-jain03** [comment]
@mudassir1231 are you working on the issue?

**Comment by prakhar3062** [comment]
you may add required in input tag then it may work

**Comment by mudassir1231** [comment]
@vedant-jain03  yes I am working

**Comment by mudassir1231** [comment]
@prakhar3062  actually I tried to add "required" but it didn't work

**Comment by prakhar3062** [comment]
> @prakhar3062 actually I tried to add "required" but it didn't work

then we have dom as another option

**Comment by Kissh12** [comment]
if it is still open, can I work on this?

**Comment by me-aashish** [comment]
Hey @vedant-jain03 ! Can you please assign this to me if it is still open ?

**Comment by vedant-jain03** [comment]
> Hey @vedant-jain03 ! Can you please assign this to me if it is still open ?

Go ahead @me-aashish

**Comment by ABHISHEK-PANDEY2** [comment]
We can just accept the name with the space at the beginning and then trim the value of the input field ? .. i can work on this if the issue is not being solved yet

**Comment by ABHISHEK-PANDEY2** [comment]
@vedant-jain03 I can work on this , is the issue open ?

**Comment by vedant-jain03** [comment]
@ABHISHEK-PANDEY2 Sure, go ahead!

**Comment by Sarthaknegigit** [comment]
Is this issue still open ?

**Comment by vedant-jain03** [comment]
> Is this issue still open ?

Sure, you can take this after successful merge of your ongoing PR!

**Comment by Sarthaknegigit** [comment]
@vedant-jain03 Can I start working on this one now?

**Comment by joannasjohnraj** [comment]
Is this issue still open? i would like to work on it

**Comment by Prerna-0202** [comment]
Solved already.
