### ISSUE TITLE
Circuit-Cards on Example page are not responsive

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#2857]
**Describe the bug**
CircuitCards on [examples](https://circuitverse.org/examples) page are not responsive between 992/843 and 1199/843

**To Reproduce**
1. Go to 'https://circuitverse.org/examples'
2. resize window between 992 - 1199
3. see error

**Expected behavior**
Card Design should be responsive

**Screenshots**
<img width="995" alt="Screenshot 2022-01-29 at 2 20 47 AM" src="https://user-images.githubusercontent.com/76155456/151620059-2d4ad7cc-6863-49c8-a9ed-fefea1cfd9f0.png">

**Device Information [optional]:**
 - OS: MacOS
 - Browser Chrome

**Are you working on this issue? (Yes/No)**
NO

**Comment by romasinha** [comment]
Can I work on this issue?

**Comment by vedant-jain03** [comment]
@romasinha Go Ahead

**Comment by Arch0125** [comment]
@vedant-jain03 I was not able to replicate the bug. Maybe it happens on some specific devices/browsers ?
Here are some screenshots, the cards seem to be responsive
![Screenshot from 2022-01-30 20-17-13 ](https://user-images.githubusercontent.com/72722967/151704681-18af9311-64b2-4a25-a69a-d0c509d1784a.png)
![Screenshot from 2022-01-30 20-16-54](https://user-images.githubusercontent.com/72722967/151704682-7549a138-fd72-495f-8bf8-a8b816dec0e3.png)

**Device Information**
- OS: Ubuntu 21.10
- Browser: Chrome

**Comment by pulkit-30** [comment]
Resize your window to 1040 X 852 
By opening dev tools on chrome

**Comment by Prakhargarg-2010196** [comment]
Is this issue still open can I work on it ?

**Comment by anugoyal998** [comment]
can I work on the issue?

**Comment by PrerakMathur20** [comment]
If this issue is still open, I would like to take up. And will fix this in no time.

**Comment by theshivanshvasu** [comment]
Can I work on this issue?

**Comment by theshivanshvasu** [comment]
@vedant-jain03 @pulkit-30 @anugoyal998  Please have a look on my PR!

**Comment by pulkit-30** [comment]
Thanks, @theshivanshvasu , There are already two pr waiting for review
