### ISSUE TITLE
Tooltip in the footer for social icons 

### ISSUE THREAD

**Issue by aashimawadhwa** [CircuitVerse/CircuitVerse#2860]
**Describe the bug**
In the footer when we hover on the social icons the tool-tip is not present there .

**To Reproduce**

1. Scroll down to footer
2. hover on the social icons'
3. See error

**Expected behavior**
To display tool-tips

**Screenshots**

![Screenshot from 2022-01-30 01-20-04](https://user-images.githubusercontent.com/73706697/151675625-5cb4f8c4-4f82-423d-8aa1-72afdc60e263.png)

**Are you working on this issue? (Yes/No)**
yes

**Comment by prakhar3062** [comment]
Please assign me this issue, i will resolve it.

**Comment by vedant-jain03** [comment]
@aashimawadhwa can you please ellaborate the use case. Why it is needed?

**Comment by aashimawadhwa** [comment]
> @aashimawadhwa can you please ellaborate the use case. Why it is needed?

Providing tooltips will enhance it and will provide a clear description of  the social icons.

**Comment by Prerna-0202** [comment]
@gr455 @tachyons

**Comment by prakhar3062** [comment]
Yeah it might be possible that some of the users can't get the idea of social media platform icon. So tooltip will also work nice. Just put the name of social media platform in span tag. And make it's opacity zero and change to one on hover

**Comment by bhutani2002** [comment]
Hey @aashimawadhwa please assign this issue to me. As I saw that no one is assigned this issue yet and there's no pull request too, for this. I have started on the tooltip formation and will get back to you as soon as possible, when it's ready.
Thank You.

**Comment by aashimawadhwa** [comment]
> Hey @aashimawadhwa please assign this issue to me. As I saw that no one is assigned this issue yet and there's no pull request too, for this. I have started on the tooltip formation and will get back to you as soon as possible, when it's ready. Thank You.

I am already working on it and its already mentioned on the issue itself.
