### ISSUE TITLE
Browser Notification button not enabling notifications

### ISSUE THREAD

**Issue by Arch0125** [CircuitVerse/CircuitVerse#2862]
**Describe the bug**
When Enable button is clicks the browser does not asks to enable browser notifications

**To Reproduce**
1. Go to 'Circuitverse.org>Profile>Notifications'
2. Click on 'Enable button'
3. See error

**Expected behavior**
A Browser pop-up should appears asking for notification permissions

**Screenshots**

https://user-images.githubusercontent.com/72722967/151705781-6f75ef46-ff62-4631-9600-835fd5eb95b0.mp4

**Device Information :**
 - OS: Ubuntu 21.10
 - Browser: Chrome

When site notifications enables manually from chrome site settings, the change is reflected however the Test button does not work
![image](https://user-images.githubusercontent.com/72722967/151705861-3c30059f-9f13-4762-a515-275b27e94a5d.png)

**Comment by mudassir1231** [comment]
Can i work on this issue

**Comment by Arch0125** [comment]
@mudassir1231  Sure

**Comment by Prerna-0202** [comment]
Solved  in #3243
