### ISSUE TITLE
Dropdown menu is not working on this page

### ISSUE THREAD

**Issue by mudassir1231** [CircuitVerse/CircuitVerse#2864]
**Describe the bug**
dropdown menu is not working on this page
https://circuitverse.org/groups/4023

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'groups'
2. Click on 'profile'
3. See error

**Screenshots**

https://user-images.githubusercontent.com/88880988/151709363-e1299a59-e145-4c6f-8829-2511651a159d.mp4

**Expected behaviour**

![bug1](https://user-images.githubusercontent.com/88880988/151709342-275778aa-5091-4cd8-8ae5-8cefec419c10.png)

**Device Information [optional]:**
 - OS: [windows]
 - Browser [chrome]
 

**Are you working on this issue? (Yes)**

**Comment by Arunesh-Tiwari** [comment]
**I want to work on this issue, pls asign it to me**.

**Comment by Arunesh-Tiwari** [comment]
the link which you provided https://circuitverse.org/groups/4023 is unable to acces it shows:
"You are not authorized to do the requested operation"

**Comment by mudassir1231** [comment]
I am working on it bro

**Comment by mudassir1231** [comment]
@Arunesh-Tiwari   you can't access it
Log in to your account and create grups and the see error

**Comment by mudassir1231** [comment]
@vedant-jain03  can you please assign this issue to me

**Comment by Trupti0406** [comment]
@mudassir1231 I'd like to work on this issue. Can you please direct me to the file/folder where changes can be made!

**Comment by pulkit-30** [comment]
solved #2739
