### ISSUE TITLE
Unable to sign in with Facebook

### ISSUE THREAD

**Issue by mudassir1231** [CircuitVerse/CircuitVerse#2865]
**Describe the bug**
Unable to sign in with Facebook

**To Reproduce**
1. Go to 'sign-in page'
2. Click on 'sign-in with Facebook'
3. See error

**Screenshots**

![Screenshot (143)](https://user-images.githubusercontent.com/88880988/151709767-df1623da-9ae3-4be3-8107-27f18c1cd830.png)

![Screenshot (142)](https://user-images.githubusercontent.com/88880988/151709773-561f1350-09c3-45da-9c4c-2cf8c556cfae.png)

**Device Information [optional]:**
 - OS: [Windows]
 - Browser [chrome]

**Are you working on this issue? (Yes)**

**Comment by prakhar3062** [comment]
Assign it to me, i will resolve it through firebase.I have did it previously also.

**Comment by mudassir1231** [comment]
I don't think they are using firebase at the back end 🤔
And I actually am working on this issue

**Comment by mudassir1231** [comment]
I this this issue can only be solved by the admine so it is better to close this issue
