### ISSUE TITLE
Open up wiki so other people can collaborate

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#287]
@satu0king ,

The CircuitVerse wiki in GitHub seems to be read-only right now.
It would make sense to open it up so other people can edit as well; there's an option in the project settings for that.

Optionally, add people that are interested in contributing to the wiki to the list of collaborators.

**Comment by satu0king** [comment]
> Optionally, add people that are interested in contributing to the wiki to the list of collaborators.

I will go with this option. Have added you as collaborator.

**Comment by vik-y** [comment]
@satu0king but we have a separate place for storing docs right?

**Comment by satu0king** [comment]
@vik-y the other repo is for documentation on how to use CircuitVerse not with respect to the code.
