### ISSUE TITLE
Adding a custom context menu.

### ISSUE THREAD

**Issue by NavonilDas** [CircuitVerse/CircuitVerse#288]
**Describe your feature.**
Adding a custom context menu for the simulation area.

The context menu will contain the following options in the same order as well:
- [ ] Copy
- [ ] Cut
- [ ] Paste
- [ ] Delete  (it deletes the selected circuit element)
- [ ] Undo
- [ ] New Circuit
- [ ] Insert Subcircuit
- [ ] Center Focus

This is the default context menu provided by Chrome.
![screenshot](https://user-images.githubusercontent.com/29132316/54744856-1188fa00-4bee-11e9-923e-07c3c0ac4f8b.jpg)

**Are you working on this? (Yes/No)**
Yes

**Comment by satu0king** [comment]
Good idea. I have updated the issue to be more appropriate.
