### ISSUE TITLE
Redundant icon file

### ISSUE THREAD

**Issue by monsij** [CircuitVerse/CircuitVerse#289]
**Describe the bug**
Currently there are two files named `favicon.ico` and `favicon.ICO`.  Both of these serve the same purpose.

**Screenshots**
![Duplicate](https://user-images.githubusercontent.com/23289387/54765552-bd970900-4c1f-11e9-9321-224392cca911.PNG)

**Are you working on this issue? (Yes)**

**Comment by satu0king** [comment]
Yes the one with ICO is redundant.

**Comment by monsij** [comment]
I'm interested to take this up.

**Comment by satu0king** [comment]
go ahead
