### ISSUE TITLE
Space issue around image button

### ISSUE THREAD

**Issue by Ankur-Agrawal-ece20** [CircuitVerse/CircuitVerse#2890]
**Describe the bug**
Very little space on the left and right sides of the `Render Circuit Image` button.

**To Reproduce**
1. Go to Simulator
2. Click on the download as image button
3. Observe the `Render Circuit Image` button
4. See an error

**Expected behavior**
The space should be more so that button looks neater.

**Screenshots**
Before:
![Screenshot from 2022-02-03 22-49-07](https://user-images.githubusercontent.com/78701055/152396164-5864bb6b-02ba-48d0-9176-744c18e48a48.png)
After:
![Screenshot from 2022-02-03 22-49-01](https://user-images.githubusercontent.com/78701055/152396215-b9fff773-66f6-4767-8b1f-737577b89209.png)

**Device Information [optional]:**
 - OS: Linux
 - Browser: Firefox

**Are you working on this issue? (Yes/No)**
Yes, I'm working on this issue.

**Comment by soustab10** [comment]
Can I work on this issue?

**Comment by Ankur-Agrawal-ece20** [comment]
> Can I work on this issue?

I am working on it bro.

**Comment by Ankur-Agrawal-ece20** [comment]
@Kartikay304 should I work on this issue?

**Comment by Prerna-0202** [comment]
Solved already
![Screenshot (686)](https://user-images.githubusercontent.com/89515816/190873891-1309eb89-1e55-4b94-826f-fe5c1b16e58a.png)
