### ISSUE TITLE
Unexpected behaviour : deleting an Offline Project

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#2894]
**Describe the bug**

Unexpected behaviour after deleting an offline project. 
We cannot choose a project to open (Radio button disappear)

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator'
2. Click on 'project>open Offline '
3. Delete a project
4. See an error

**Expected behavior**

It should remain the same ( radio button and the delete icon should not disappear ) 

**Screenshots**

https://user-images.githubusercontent.com/76155456/152520518-b15b7780-06cc-44d6-b9c4-0f90f89f7267.mov

**Device Information [optional]:**
 - OS: MacOs
 - Browser Chrome

**Additional context**
Also, update dialog box style for better UI

**Comment by Ankur-Agrawal-ece20** [comment]
@pulkit-30 I would like to work upon this issue. Can you please assign it to me?

**Comment by PrerakMathur20** [comment]
@pulkit-30
I think I have figured out the bug here, and can fix this issue up in no time. So I'd like to work on this issue.

**Comment by Ankur-Agrawal-ece20** [comment]
> @pulkit-30 I think I have figured out the bug here, and can fix this issue up in no time. So I'd like to work on this issue.

Nice to see that you are eager to contribute but I think that's the incorrect way of doing so. I have asked @pulkit-30 first and he reacted to me with thumbs up so I have also sorted the issue. But you should have asked first if anyone is working upon the issue before creating a PR. 
Thank you.

**Comment by Prerna-0202** [comment]
> @pulkit-30 I think I have figured out the bug here, and can fix this issue up in no time. So I'd like to work on this issue.

Hey @PrerakMathur20, If someone has already commented on an issue, then it's not right to do it like this. Everyone has their own potential. It's great that you solved this issue in no time. But if someone wants to try. Let them try first...You can work on other open issues ...

**Comment by Manan17** [comment]
Hi, can I work on this issue?

**Comment by aadubey01** [comment]
I would like to contribute in this issue, is this  issue open.

**Comment by fillingtothemomo** [comment]
hello , is this issue still open, i would like to contribute to it,can u please assign me.

**Comment by nisha-laur** [comment]
@pulkit-30 I want to resolve this issue ,please assign it to me .

**Comment by Prerna-0202** [comment]
> hello , @pulkit-30 is this issue still open, i would like to contribute to it,can u please assign me.

@fillingtothemomo, Go ahead

**Comment by fillingtothemomo** [comment]
@Prerna-0202 I made some changes and fixed the issue. Please review my PR.

**Comment by fillingtothemomo** [comment]
@Prerna-0202 can you kindly review my PR and merge it if there are no further modification to be done
