### ISSUE TITLE
Unwanted border around social icons in footer.

### ISSUE THREAD

**Issue by arpandesai0** [CircuitVerse/CircuitVerse#2896]
**Describe the bug**
There is an added border around the social icons which makes the UI look broken.

**Expected behavior**
Either border must not be there or icons must be aligned in center. ( I prefer it should be without border)

**Screenshots**
![image](https://user-images.githubusercontent.com/71290351/152534466-21645adc-4d1f-4134-ba32-7b32474ac59c.png)

**Are you working on this issue? (Yes/No) Yes**

**Comment by Trupti0406** [comment]
@arpandesai0 I figured out the solution for this. Please assign this to me.

**Comment by arpandesai0** [comment]
@Trupti0406 I am already on it and have made pull request for the same.

**Comment by arpandesai0** [comment]
#2898

**Comment by arpandesai0** [comment]
#2898
