### ISSUE TITLE
The copyright text should be at the center.

### ISSUE THREAD

**Issue by Trupti0406** [CircuitVerse/CircuitVerse#2899]
**Describe the bug**
In the footer, the copyright text is aligned at the left-most side instead of at the center.

**Expected behavior**
The copyright text i.e. ("Copyright © 2022 CircuitVerse, All rights reserved.") should be at the center of the footer instead of the left side.

**Screenshots**
Current behaviour:
![current](https://user-images.githubusercontent.com/92917582/152572012-7c339b7b-5b2a-4ce0-992c-d6de38a9bcae.PNG)

Expected behaviour:
![expected](https://user-images.githubusercontent.com/92917582/152572116-3a8f0029-31c0-445c-868c-887108f897b4.PNG)

**Are you working on this issue? (Yes/No)**
Yes, I'm working on this issue.

**Comment by vishwassrivastava** [comment]
Yes I am working on this issue

**Comment by Trupti0406** [comment]
I've already fixed the issue and put up a pull request. It'd better to not
waste time and work on something else. Thank you and all the best.

**Comment by vishwassrivastava** [comment]
@wallento @mohammedsafwat @revathskumar please look into my pr

**Comment by vedant-jain03** [comment]
@Trupti0406 Do not raise a PR for an self made issue before reviewing.

**Comment by vedant-jain03** [comment]
@Trupti0406 Thank you for your contribution but do review your issue by community members before raising a PR for betterment.

From my perspective of this issue, it is not the expected behavior.
