### ISSUE TITLE
Fixing Social Icons on About US Page

### ISSUE THREAD

**Issue by Harshil-Jani** [CircuitVerse/CircuitVerse#2901]
**Describe the bug**
The social icons on About us page as not looking as expected. Styling was supposed to be improved over there.

**To Reproduce**
1. Go to [About ](https://circuitverse.org/about) Section of CircuitVerse
2. Scroll down to [Social Links](https://circuitverse.org/about#:~:text=Email%20us%20at,Slack%20Channel)

**Expected behavior**
 The Social Icons and Texts must be in proper styling.
**Screenshots**
![image](https://user-images.githubusercontent.com/79367883/152595893-98fa47c5-68bb-4fbe-9ef4-b0d143298732.png)

**Device Information [optional]:**
 - OS: Ubuntu 20.04
 - Browser : Chrome
 - Version : 97.0.4692.99 (Official Build) (64-bit)

**Additional context**

**Are you working on this issue? (Yes/No)**
YES , I AM WORKING ON THIS.

**Comment by vishwassrivastava** [comment]
Is this issue open?

**Comment by vedant-jain03** [comment]
@Harshil-Jani I am not able to reproduce the bug.
Thank you for raising a PR but before raising a PR do review your issue by community members for betterment.

**Comment by gr455** [comment]
I am too, not able to reproduce the bug. Can you tell me the resolution of your display or some way to reproduce this?

**Comment by Harshil-Jani** [comment]
https://user-images.githubusercontent.com/79367883/153223495-3a0a4691-2d6a-48ac-bb24-0f8192c0b246.mp4

**Comment by MashTerro** [comment]
Hi @Harshil-Jani  I want to fix this issue can fix it?

**Comment by kushalShukla-web** [comment]
Can I work on this issue

**Comment by gr455** [comment]
> Can I work on this issue

Are you able to reproduce this issue?
