### ISSUE TITLE
Documentation for groups is not working

### ISSUE THREAD

**Issue by ZaidKhan2002** [CircuitVerse/CircuitVerse#2905]
**Describe the bug**
Documentation regarding the groups is giving 404 error.

**To Reproduce**
1. Login to your account 
2. View my groups on your profile dropdown
3. Click on make group
4. Click here for documentation
5. See error

**Expected behavior**
A documentation should be properly linked and if documentation is not there than it should be made.

**Screenshots**
<img width="1440" alt="Screenshot 2022-02-07 at 11 52 09 AM" src="https://user-images.githubusercontent.com/71960989/152735971-0834f7b4-7fdc-452f-9cf3-373a00bccfd6.png">

**Are you working on this issue? (Yes)**

**Comment by Prerna-0202** [comment]
@ZaidKhan2002, This is an issue of Circuitverse docs, So Please open this issue in the "CircuitVerseDocs" repo..

**Comment by Kartikay304** [comment]
I tried, but I am not able to replicate this issue. Instead, the drop-down menu didn't appear when clicking on getting started in the group view page. @vedant-jain03  @pulkit-30 are you able to replicate this issue ?

https://user-images.githubusercontent.com/40604582/152806825-8ce4364b-de68-4367-9361-7fdd5ca45eb2.mp4

**Comment by pulkit-30** [comment]
No, the mentioned issue didn't exist and the issue with the drop-down menu has been fixed #2739.

**Comment by vedant-jain03** [comment]
@pulkit-30 @Kartikay304 Can we close this issue?

**Comment by Kartikay304** [comment]
> @pulkit-30 @Kartikay304 Can we close this issue?

Sure
