### ISSUE TITLE
Produce a Card-box-shadow effect

### ISSUE THREAD

**Issue by bhutani2002** [CircuitVerse/CircuitVerse#2906]
Describe the problem
In the "How to Support?" section of the "Contribute" Webpage, all the three cards of Student, Teacher and Developer doesn't look distinguished from each other and is being visible as a single block.

To Reproduce

1. Go to [https://circuitverse.org/contribute]
2. Scroll down to the "How to Support Section"
3. See error

Expected behavior
To produce a card box-shadow effect to distinguish the cards from each other.

Screenshots
Before:
![CircuitVerse-How to support(OLD)](https://user-images.githubusercontent.com/84590758/152926596-1aff8727-b918-445a-a6fe-23f215d940fd.png)

After:
![CircuitVerse-How to support(NEW)](https://user-images.githubusercontent.com/84590758/152926634-d1c0ecea-2226-4f63-a278-9d1f29560dcf.png)

Are you working on this issue? (Yes/No)
Yes

**Comment by bhutani2002** [comment]
Hi @gr455 @shubhankarsharma00, please try to review it once and provide me a feedback so that I can complete the task and generate a pull request.

**Comment by bhutani2002** [comment]
![image](https://user-images.githubusercontent.com/84590758/152935816-087a512c-324d-44e6-a862-2ee329e1a3af.png)

V.S.

![image](https://user-images.githubusercontent.com/84590758/152935854-32fb210a-d26e-4338-a911-ee63ac80ef37.png)

**Comment by adarrssh** [comment]
hey @bhutani2002, Can you assign me this issue I would like to work on this?

**Comment by gr455** [comment]
Sounds good, you can go ahead with this.
