### ISSUE TITLE
Extra columns in Combinational Analysis due to an extra space in input

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#291]
**Description of the bug**
In the Combinational Analysis, while entering the input number of columns vary because of a space at the end of the input.

**Steps to reproduce the behavior:**
1. Go to Simulator.
2. Click on Combinational Analysis and Enter "a b c "
3. The generated table has 4 columns instead of the expected 3 columns.

**Expected behavior**
4 columns

**Screenshots**

![Circuitverse_Error](https://user-images.githubusercontent.com/42511766/54779231-af0b1a80-4c3c-11e9-81bf-fb32eb3c5fd8.png)

4th column is the error.

Yes, I am working on this issue

**Comment by Amansingla97** [comment]
This happens when we enter a space after last input.https://github.com/CircuitVerse/CircuitVerse/blob/c9e365ba3e9095628f312781c3106754a926e43f/public/js/combinationalAnalysis.js#L22 when .split(' ') detetcts a space it forms a empty input. let me know if you need any help

**Comment by sal2701** [comment]
Thanks! I am planning on using ```.match(/\S+/g)``` instead of ```.split(' ')```. This will give me everything except the whitespace and solves the above problem as well. I don't think this should cause any other problems. Do suggest me anything or any problems this might cause :)
