### ISSUE TITLE
Password validator only validates for length of password

### ISSUE THREAD

**Issue by aashimawadhwa** [CircuitVerse/CircuitVerse#2916]
**Describe the bug**
Password validator only validates for the length of password i.e. more than 6 , but it should check for a special character , number , uppercase alphabet , lowercase alphabet .

**To Reproduce**
1. Go to signup
2.  enter more than 6 alphabets 
3. click on signup 

**Expected behavior**
It should check for a special character , number , uppercase alphabet , lowercase alphabet  along with length .

**Are you working on this issue? (Yes/No)**
**yes**

**Comment by aashimawadhwa** [comment]
> Can I give it a try?

I'm already working on it and it's mentioned in the issue itself.

**Comment by aashimawadhwa** [comment]
@gr455 @vedant-jain03 , please review this issue once .

**Comment by gr455** [comment]
Do we really need that strong of a password for CircuitVerse? cc @tachyons

**Comment by tachyons** [comment]
I don't think so
