### ISSUE TITLE
Project Breaking Problem/Bug Caused by Splitter Element

### ISSUE THREAD

**Issue by Zhongy1** [CircuitVerse/CircuitVerse#2920]
**Describe the bug**
Clicking cancel in splitter prompt window causes an error to occur. This ends up breaking the project, and if saved, the project will never be able to load.

**To Reproduce**
1. Launch a project
2. Click on Circuit Elements > Misc > Splitter
3. Click cancel through the two prompt windows
4. See errors in dev tools' console
5. Try to save project online
6. Unable to save; if you are, project becomes corrupted

**Expected behavior**
In the simulator, there's no immediate indicator that error occurred. However, moving and placing elements become very troublesome to do. Expected behavior should be that it properly cancels the creation of the splitter and causes no problems.

**Screenshots**
![bug](https://user-images.githubusercontent.com/34720343/153514956-3b9c9fd4-8c79-498e-95cf-9b1b1267c9a5.gif)

**Device Information [optional]:**
 Tried the steps on Chrome, Safari, and Firefox and all show similar errors in the console.

**Additional context**
Problem needs to be fixed or else users' projects may get corrupted without them knowing; resulting in so much hours of work lost.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by teyim** [comment]
can i work on this?

**Comment by vedant-jain03** [comment]
@teyim Actually the PR is already being created and it is under review.
You can check out other issues, Thankyou 😃

**Comment by kushalShukla-web** [comment]
this issue is still open ?
