### ISSUE TITLE
Slack link

### ISSUE THREAD

**Issue by auyfadaiaiedfviyab** [CircuitVerse/CircuitVerse#2928]
The link to the slack channel for GSoC 22 doesnt work.
@satu0king

**Comment by vedant-jain03** [comment]
Actually I guess GSoC 2022 for contributors not begin officially yet as mentoring org. List awaits by 7th march. Will try to update the slack link after that for sure I G.
@tachyons

**Comment by ayan-biswas0412** [comment]
> Actually I guess GSoC 2022 for contributors not begin officially yet as mentoring org. List awaits by 7th march. Will try to update the slack link after that for sure I G. @ayan-biswas0412

I think we can update the link now, because there will be many of interested future GSoCers who may want to interact with us from now

**Comment by soustab10** [comment]
Yes would be very helpful.

**Comment by ayan-biswas0412** [comment]
> Yes would be very helpful.

yes it is updated now.
