### ISSUE TITLE
Option to attach image in "Report an issue" feature.

### ISSUE THREAD

**Issue by aroradhruv2308** [CircuitVerse/CircuitVerse#2930]
**Is your feature request related to a problem? Please describe.**
This feature will allow users to attach images or videos while reporting an issue.

**Describe the solution you'd like**
Currently to report an issue user can only describe the issue in textual format. We can add a button to allow users to attach images or videos to describe the issue.
![Selection_085](https://user-images.githubusercontent.com/67088080/153751001-c6a1013f-559b-42d8-b689-78c41f8592d9.png)

**Describe alternatives you've considered**
None

**Additional context**
None

**Are you working on this? (Yes/No)**
Yes

**Comment by rachit3006** [comment]
@aroradhruv2308 actually I am working on this feature. You can check issue #2912 it involves using GitHub API and mostly it will involve the option to attach images.

**Comment by aroradhruv2308** [comment]
@rachit3006  Ok! no problem ☺️. So should I close this one?
