### ISSUE TITLE
Drop Down doesn't appear on clicking profile name.

### ISSUE THREAD

**Issue by Subhadiptech** [CircuitVerse/CircuitVerse#2941]
**Describe the bug**
After creating a group, on the group page when we click on our profile to get the drop down for dashboard, my groups, notifications and sign out options, it actually don't appear and is actually not clickable. I think this makes the user experience bad because it may happen that the user creates a new group and want to sign out. In that case, user have to suffer for this. Things are more cleared on the screenshot.

**To Reproduce**
1. [Click Here](https://circuitverse.org/users/121288/groups)
2. Click on 'Make new Group'
3. Click on  'Profile name drop down icon'

**Expected behavior**

**Screenshots**
![Screenshot 2022-02-17 030718](https://user-images.githubusercontent.com/89024718/154361344-944946f8-0287-4ebe-8a14-8d9199e83f98.jpg)

**Device Information [optional]:**
 - OS: [windows]
 - Browser [chrome]

**Are you working on this issue? (Yes/No)**

**Comment by vedant-jain03** [comment]
@tachyons

**Comment by Subhadiptech** [comment]
Hey @vedant-jain03 I want to resolve this issue, I am just finalizing project setup on local machine.

**Comment by vedant-jain03** [comment]
> Hey @vedant-jain03 I want to resolve this issue, I am just finalizing project setup on local machine.

You can setup your CV env. 
Let's wait for @CircuitVerse/circuitverse-core-team review for this issue.

**Comment by tachyons** [comment]
Are you getting this issue in local, this issue was fixed, not deployed yet

**Comment by Subhadiptech** [comment]
Yes I was getting this issue on the official release in Chrome

**Comment by vedant-jain03** [comment]
@Subhadiptech the bug is already solved in development mode and not deployed.
