### ISSUE TITLE
Enabling drag select of objects

### ISSUE THREAD

**Issue by ahmedibrahim404** [CircuitVerse/CircuitVerse#2958]
**Is your feature request related to a problem? Please describe.**

I was building some big logic circuit, and then I wanted to select part of the circuit (sub-circuit) and delete it
I wan't able to select only the gates I needed to delete, Either select one (by clicking shift + click over it) or select all (ctrl+a)
I thought I'd be better if I was able to select the needed sub-circuit only by dragging over it

**Describe the solution you'd like**

I suggest that there can be a button to disable dragging and enable selecting some part of the panel to do operations on

**Describe alternatives you've considered**
I deleted the gates one by one by keeping shift button clicked

**Are you working on this? (Yes/No)**
Yes

I need to know if I can start working on this feature?
Thanks

**Comment by xUser5000** [comment]
I faced this problem before and it was painful for me to delete so many gates one by one.

**Comment by vedant-jain03** [comment]
@tachyons @gr455

**Comment by ahmedibrahim404** [comment]
Sorry, I didn't see that the feature is already there 
By clicking `Shift`, then selecting the needed part

I am closing the issue
