### ISSUE TITLE
ESC button to deattach objects - Closing fullscreen

### ISSUE THREAD

**Issue by ahmedibrahim404** [CircuitVerse/CircuitVerse#2959]
**Is your feature request related to a problem? Please describe.**

1. When selecting any object(gate, ...etc) from the side panel, and then wanting to delete it (before placing over the panel) then ESC may does this for us

2. Exiting fullscreen mode using ESC button (sometimes it easier than clicking over `Exit Full Preview`)

**Describe the solution you'd like**
Make ESC button responsible for deattaching objects and closing fullscreen mode

**Are you working on this? (Yes/No)**
Yes

The first idea was proposed before in https://github.com/CircuitVerse/CircuitVerse/issues/1476

**Comment by ahmedibrahim404** [comment]
@tachyons @gr455

Let me know If I can work on this
Thanks in advance

**Comment by ayan-biswas0412** [comment]
yah i think it's a good one 
cc @nitin10s what you think ?

**Comment by ahmedibrahim404** [comment]
@kushalShukla-web 
It's done and merged now
Thanks
