### ISSUE TITLE
Notifications is not working

### ISSUE THREAD

**Issue by ahmedibrahim404** [CircuitVerse/CircuitVerse#2962]
**Describe the bug**
Notification system is not working as described below in the GIF

In the GIF, I enabled the Notifications manually, to test 'Test' button also

**To Reproduce**
1. Select your username (top right of screen)
2. Click on 'Notifications'
3. Try 'Enable' is disabled, or 'Test' is enabled
4. Nothing happens 

**Expected behavior**
Should give a prompt to ask if user wants to allow notifications or test if it's running

**Screenshots**
![notification](https://user-images.githubusercontent.com/34144004/155892224-a3054aa5-f3b5-498f-8396-5b1365e83888.gif)

**Device Information:**
 - Google Chrome Browser

**Additional context**
I tried to investigate the issue, and it turned out that the `service worker` is not ready yet

**Are you working on this issue? (Yes/No)**
Yes (if applicable)

**Comment by ahmedibrahim404** [comment]
@ayan-biswas0412 
Can you check this, please?

**Comment by vedant-jain03** [comment]
@ahmedibrahim404 I guess this is one of the parts of the GSoC project as we are expecting to replace the gem, so I think this issue should get resolved on it.
WDYT @tachyons

**Comment by ayan-biswas0412** [comment]
> @ahmedibrahim404 I guess this is one of the parts of the GSoC project as we are expecting to replace the gem, so I think this issue should get resolved on it. WDYT @tachyons

yes that's true

**Comment by ayan-biswas0412** [comment]
See this  [Project 2](https://github.com/CircuitVerse/CircuitVerse/wiki/GSoC%2722-Project-List#project-2---circuitverse-platform-improvements)
