### ISSUE TITLE
Unresponsive length of Navbar

### ISSUE THREAD

**Issue by Dnouv** [CircuitVerse/CircuitVerse#2964]
**Describe the bug**
On the simulator page on `md` size devices, when the navbar is opened it flexes to around the half-length of the page and then returns to the expected length.

**To Reproduce**
1. Go to the simulator page on medium-screen size devices.
2. Open the Navbar.
3. Drag and keep the quick tools outside the navbar area.
4. Now close the navbar again and then open it again.
5. See error.

**Expected behavior**
The navbar opens without flexing to an extra length. 

**Screenshots**

https://user-images.githubusercontent.com/61188295/155983944-ec90bf15-3d0a-4c6c-9328-3660f13dfda5.mp4

**Device Information [optional]:**
 - OS: Windows
 - Browser Chrome

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes, once approved by community members

**Comment by vedant-jain03** [comment]
@Dnouv As far as I know the new responsive design for the simulator is solved in GSoC mobile touch compatibility.
@CircuitVerse/circuitverse-core-team

**Comment by Dnouv** [comment]
Thanks for the info, ok, so this would be completed under the GSoC project, then shall I close this issue? Please let me know.

**Comment by vedant-jain03** [comment]
> Thanks for the info, ok, so this would be completed under the GSoC project, then shall I close this issue? Please let me know.

Let's wait for the reviews from other core-team.

**Comment by Dnouv** [comment]
Hey @vedant-jain03 from whom shall we get this issue reviewed please let me know.
Thank you!

**Comment by vedant-jain03** [comment]
@Dnouv actually I have tagged core-team, so expecting one from the behalf of core-team.
