### ISSUE TITLE
Add keyboard shortcuts docs

### ISSUE THREAD

**Issue by ahmedibrahim404** [CircuitVerse/CircuitVerse#2981]
**Is your feature request related to a problem? Please describe.**

I have been using the application for 4 days, and since then I am always discovering new keyboard shortcuts to make the design process faster, and that's an amazing thing.

I tried to search for keyboard shortcuts catalog where I can know all the available shortcuts but didn't find any unfortunately

That's why I suggest adding shortcuts catalog to the [docs](https://docs.circuitverse.org/#/) where new users can know all the shortcuts available, to make their experience better!

It may look something like that
![image](https://user-images.githubusercontent.com/34144004/156229760-6af0ccd9-a82b-4cda-9d3e-b83eb9fa525a.png)

**Are you working on this? (Yes/No)**
Yes, if applicable

**Comment by ahmedibrahim404** [comment]
What do you think? 
@ayan-biswas0412 @nitin10s @gr455

**Comment by ayan-biswas0412** [comment]
> What do you think? @ayan-biswas0412 @nitin10s @gr455

yah sure go ahead

**Comment by ahmedibrahim404** [comment]
Thanks @ayan-biswas0412 
Here is the [PR](https://github.com/CircuitVerse/CircuitVerseDocs/pull/325)
It was really fun going through the codebase and discovering new keys shortcuts!
