### ISSUE TITLE
Zoom in/out bug

### ISSUE THREAD

**Issue by ahmedibrahim404** [CircuitVerse/CircuitVerse#2982]
**Describe the bug**
Whenever I zoom in/out using `Ctrl + (+/-)`, it works properly but the top bar percent doesn't change (as described in the gif below)
The leads to unexpected behaviors when using both

**To Reproduce**
1. Go to Simulator
2. Click on `Ctrl + '+'`
3. See it's zooming in, but the top zoom bar doesn't change

**Expected behavior**
The top zoom bar should change while zooming in/out with `Ctrl + (+/-)`

**Screenshots**

![a](https://user-images.githubusercontent.com/34144004/156253169-e0d1abf7-f3f1-4b18-adca-6a9437471651.gif)

**Are you working on this issue? (Yes/No)**
Yes, I can work on it

**Comment by ahmedibrahim404** [comment]
Can I work on this? Thanks!
@ayan-biswas0412

**Comment by vedant-jain03** [comment]
@gr455

**Comment by gr455** [comment]
Yep, Good find
