### ISSUE TITLE
Checkbox is overlapping in edit details page

### ISSUE THREAD

**Issue by aashimawadhwa** [CircuitVerse/CircuitVerse#2990]
**Describe the bug**
the checkbox is overlapping the subscribe to mail

**To Reproduce**
1. Go to dashboard
2. Click on  edit details
3. Scroll down 

**Expected behavior**
checkbox should not overlap 

**Screenshots**
![Screenshot from 2022-03-02 14-30-15](https://user-images.githubusercontent.com/73706697/156330309-53688203-1997-43f3-844e-086581fcfde7.png)

**Are you working on this issue? (Yes/No)**
**yes**

**Comment by kushalShukla-web** [comment]
Can I pls..

**Comment by vedant-jain03** [comment]
@aashimawadhwa is this behavior in firefox?
