### ISSUE TITLE
Deletion of Flag makes the timing diagram blank

### ISSUE THREAD

**Issue by tintin9999** [CircuitVerse/CircuitVerse#3001]
**Describe the bug**
Bugs related to the timing diagrams and flags.
1. Deletion of every flag causes the timing diagram panel to have an empty box.
2. Creation of flag after the previous deletion doesn't show a timing graph.

**To Reproduce**
Steps to reproduce bug 1.:
1. Go to Simulator
2. Open Timing Diagram
3. Add and Delete a flag
4. See Bug 1.

Steps to reproduce bug 2.:
1. Follow the steps given for Bug 1.
2. Add a Flag
3. See Bug 2.

**Expected behavior**
1. Deletion of every Flag should hide the timing diagram plotArea
2. Creation of any Flags after the deletion should result in the timing graph to be shown.

**Screenshots**
Bug 1:

https://user-images.githubusercontent.com/56310902/156811469-2ddb5766-4259-4e51-8f61-715d03d92fa2.mp4

Bug 2:

https://user-images.githubusercontent.com/56310902/156811584-746f3948-bd6f-4373-a891-5a79325d6a2c.mp4

**Device Information [optional]:**
 - OS: Ubuntu
 - Browser: Brave & Chrome

**Additional context**
None.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by vedant-jain03** [comment]
@gr455

**Comment by gr455** [comment]
Yep this needs to be fixed. @tintin9999 If you could work on this, it would be a great help

**Comment by tintin9999** [comment]
Sure thing! I have a fix ready, I'll make a PR soon. @gr455
