### ISSUE TITLE
Update mailer copyright text

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3008]
**Describe the bug**
Currently, the mailer copyright text in locales is `Copyright © 2021 CircuitVerse. All rights reserved. For any issues, reach out to us support@circuitverse.org` which should be updated like [this](https://github.com/CircuitVerse/CircuitVerse/blob/80b1a0ba56231b1b43d4d1355cf033ee36fe4025/config/locales/views/layouts/en.yml#L22)

**Are you working on this issue? (Yes/No)**
No

**Comment by ahmedibrahim404** [comment]
I think I can do this, if applicable

**Comment by vedant-jain03** [comment]
@pavanjoshi914 
Is this valid, Then we can assign the issue.

**Comment by pavanjoshi914** [comment]
> @pavanjoshi914 Is this valid, Then we can assign the issue.

applicable

**Comment by vedant-jain03** [comment]
@ahmedibrahim404 
Go ahead 👍

**Comment by harshlancer** [comment]
I would be happy to help if needed @ahmedibrahim404 ...

**Comment by me-aashish** [comment]
Hey @vedant-jain03! Can you please review my PR #3216 for this particular issue #3008

**Comment by codewithnadeem14502** [comment]
I think I can do this, if applicable

**Comment by siddhi-244** [comment]
Can I try it ?

**Comment by vedant-jain03** [comment]
> Can I try it ?

Thanks but the PR for the issue is under review, you can check out other open issues!

**Comment by joannasjohnraj** [comment]
Is this issue still open? I would like to work on it.

**Comment by palashb01** [comment]
i think i can resolve this issue, @vedant-jain03  could you please assign this issue to me.

**Comment by vedant-jain03** [comment]
> i think i can resolve this issue, @vedant-jain03 could you please assign this issue to me.

@palashb01 PR for the issue is already raised and is under review. You can checkout another open issue!
