### ISSUE TITLE
Open with Simulator Button for featured examples from CircuitVerse homepage

### ISSUE THREAD

**Issue by SiddheshKukade** [CircuitVerse/CircuitVerse#3027]
**Is your feature request related to a problem? Please describe.**
Request for an **Open With Simulator Button** on featured examples 

**Describe the solution you'd like**
## Issue Description : 
- Go to homepage :  [circuitverse.org](circuitverse.org)
- scroll down to featured examples
![Screenshot_2022-03-10-17-25-05-472_com.android.chrome.jpg](https://user-images.githubusercontent.com/65951872/157657165-76100e55-0773-49fc-be07-6a73b44f9e88.jpg)

- Open any example  : 

![Screenshot_2022-03-10-17-19-43-952_com.android.chrome.jpg](https://user-images.githubusercontent.com/65951872/157656807-d7e4d1e5-c0c7-4380-bcb5-8db2d02d3e29.jpg)

Here you can see that we can only read about the circuit and observe it 

## feature description

On featured circuits examples there should be a  button like **pen with simulator** which will take the user To The Simulator page with a readymade circuit same as that of the previously featured example circuit was.

It should look something like this  : 
![IMG_20220310_173447.jpg](https://user-images.githubusercontent.com/65951872/157658249-bee23c57-e75b-4468-b838-ca7fed368781.jpg)

**Additional context**

### benefits to the user
- can directly see the circuit in action and how it works in real life with the real inputs rather than just reading the information

- will be able to modify the circuit according to his needs and see the results with different inputs provided

- will be able to enhance the circuit as well

**Are you working on this? (Yes/No)**
No

**Comment by pulkit-30** [comment]
Hey, @SiddheshKukade Welcome to circuitverse,

talking about this issue, We have a full-screen button that preview circuits and sub-circuits, Any user can test these projects... and for making some changes and enhancing the project, we have a fork button( user must be signed in ), Simply user can fork the project and launch the simulator and made his changes to that project...
Directly making changes to someone's project that's not a good idea.

https://user-images.githubusercontent.com/76155456/157673066-faa608b5-b492-4e69-9e27-19fabd93f5e3.mov

WDYT @ayan-biswas0412

**Comment by ayan-biswas0412** [comment]
> Hey, @SiddheshKukade Welcome to circuitverse,
> 
> talking about this issue, We have a full-screen button that preview circuits and sub-circuits, Any user can test these projects... and for making some changes and enhancing the project, we have a fork button( user must be signed in ), Simply user can fork the project and launch the simulator and made his changes to that project... Directly making changes to someone's project that's not a good idea.
> 
>  Screen.Recording.2022-03-10.at.6.57.11.PM.mov 
> WDYT @ayan-biswas0412

I don't think fork directly changes the main project, rather it creates a copy in the profile who have forked and all changes made to the copied one.

**Comment by pulkit-30** [comment]
> I don't think fork directly changes the main project, rather it creates a copy in the profile who have forked and all changes made to the copied one.

Yep!
