### ISSUE TITLE
Discussion Forum Showing Error

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#3033]
**Describe the bug**
When we click on the discussion forum, It is showing 500 server error.

**To Reproduce**
1. Go to 'Simulator'
2. Click on 'Help'
3. Scroll down to 'Discussion Forum'

**Expected behavior**
It should redirect to the Forum Page

**Screenshots**
![Screenshot (295)](https://user-images.githubusercontent.com/89515816/158196071-5aad0762-c804-4f9c-a0b6-8964edafe5a6.png)

**Device Information [optional]:**
 - OS: Windows
 - Browser : Chrome
 - Version :-

**Additional context**

**Comment by legendarykamal** [comment]
Hi I would like to work on this  @tachyons @gr455  : )

**Comment by tachyons** [comment]
Fixed
