### ISSUE TITLE
Responsive Simulator is not Working 

### ISSUE THREAD

**Issue by Subhraneel77** [CircuitVerse/CircuitVerse#3045]
Describe the bug
When You reduce the size of your displaying screen, then all the components present in simulator gets distorted.

To Reproduce
1. Go to 'Simulator'
2. Click on 'Minimise Button'
3. See error 

Expected behavior
All the components should reduce their respective sizes in order to fit in the screen.

Screenshots
<img width="570" alt="Screenshot 2022-03-18 at 10 02 03 PM" src="https://user-images.githubusercontent.com/75981967/159058934-c9b46075-bfc0-4df0-bf7d-2b83d2d5f71c.png">
<img width="572" alt="Screenshot 2022-03-18 at 10 01 40 PM" src="https://user-images.githubusercontent.com/75981967/159058965-ecebfb5e-73ff-4a99-a480-cdcf13fa1298.png">

Device Information [optional]:
 - OS:  iOS
 - Browser safari
 - Version : a1

Additional context
Mainly the responsive nature of the simulator gets disrupted.

**Comment by vedant-jain03** [comment]
@Subhraneel77 I guess the PR for this issue is under review as this was under the last year's GSoC project.
@CircuitVerse/circuitverse-core-team Any lead on this one?

**Comment by Prerna-0202** [comment]
Solved in #3236
