### ISSUE TITLE
Navbar Overlap with Panels

### ISSUE THREAD

**Issue by ahmedibrahim404** [CircuitVerse/CircuitVerse#3047]
**Describe the bug**
When opening the navbar of the simulator for small devices, it overlaps with the panels as shown below

**Expected behavior**
The navbar should appear on top of these panels

**Screenshots**
![CVL](https://user-images.githubusercontent.com/34144004/159402215-ff536c37-902e-4c8d-bcdf-1fc616186ca6.gif)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by kumarsanu2002** [comment]
if it is open then i can fix it. Let me know and provide code base.
Thanks.

**Comment by Prerna-0202** [comment]
Hey @kumarsanu2002, The pr for this issue has been already made under the Gsoc task(#3236). You can try other open issues.

**Comment by Prerna-0202** [comment]
Solved in #3236
