### ISSUE TITLE
Simulator is not Working Properly in Mobile Website

### ISSUE THREAD

**Issue by Subhraneel77** [CircuitVerse/CircuitVerse#3058]
**Describe the bug**
Simulator is not Working properly in Mobile Website Page. We cannot change the positions of Timing Diagram, Circuit Elements and Properties.

**To Reproduce**
1. Go to 'https://circuitverse.org/ in Mobile'
2. Click on 'Launch Simulator'
3. Try to Change the positions of Timing Diagram, Circuit Elements , Properties etc.

**Expected behavior**
Properly should have worked as in Desktop or Laptop.

**Screenshots**
![6c78ad12-55bb-4526-bc62-7a1a3399e408](https://user-images.githubusercontent.com/75981967/160274916-8c0e3b33-e607-4b8d-b0b2-d27086bd9ab9.jpg)
![61c636a6-d819-4741-b37d-32808f659e3d](https://user-images.githubusercontent.com/75981967/160274923-160dfae1-8ffd-47fa-8aca-b015cfa3593a.jpg)

**Device Information [optional]:**
 - OS:  iOS
 - Browser : safari
 - Version : M1

**Are you working on this issue? (Yes/No)**
Yes

**Comment by devartstar** [comment]
Hi @Subhraneel77,
A lot of work has already been done for UI and working of Simulator in mobile in the [PR # 2362](https://github.com/CircuitVerse/CircuitVerse/pull/2362)
