### ISSUE TITLE
CircuitVerse Discord Circuit Embed

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#308]
**Is your feature request related to a problem? Please describe.**
When we embed a youtube link in Discord, you can see the video inline in chat. Similarly I would like to see the circuit preview image or better still circuit preview itself inline. 

**Describe the solution you'd like**
I have no idea if this is possible. Would like someone to survey on the same. I found something that might help: https://discord.js.org/#/docs/main/stable/class/MessageEmbed

**Additional context**
Reach out to @jbox144 if you need any information, permissions etc

**Are you working on this? (Yes/No)**
No

**Comment by jbox144** [comment]
Message embeds are generated by bots normally.

That being said, we *could* certainly add a bot to the CircuitVerse Discord that embeds a CircuitVerse simulator when a link is posted, similar to the BlueprintBot commonly used on Factorio discord servers. I know that is an option, although it would not make CircuitVerse embeds native to discord, but would make it possible to preview circuits via Discord. I'll look into this more.

**Comment by jbox144** [comment]
For reference, here's an example of jbot1 using customly generated embeds. Only bots can use such embeds, but we could easily use a bot to post CircuitVerse embeds whenever a user posts a CircuitVerse link.
![image](https://user-images.githubusercontent.com/40789662/54886423-ee0acb80-4edb-11e9-8c8b-b4b2e8aafb5c.png)

**Comment by satu0king** [comment]
Yes, a bot will do, is it easy to add a bot?

**Comment by blane1257** [comment]
It's fairly easy to make a bot, though I'm not sure if the embed feature would allow for the circuitverse preview. It could certainly show an image of the circuit, but I'm not sure if it would be able to use iframes...

**Comment by jbox144** [comment]
> Yes, a bot will do, is it easy to write and add a bot?

Using python like I did, it's dead easy to make a bot. You can easily create a bot account directly from Discord, and the scripting is childs play from my experience.

**Comment by satu0king** [comment]
Yes atleast image is good

**Comment by Parikshit-Hooda** [comment]
What is the progress on this issue @jbox144  ?
