### ISSUE TITLE
Timing Diagram Visualization

### ISSUE THREAD

**Issue by theredcap** [CircuitVerse/CircuitVerse#311]
**Is your feature request related to a problem? Please describe.**
What are your thoughts on making a timing diagram visualization. It would be easier to look at how the different signals are acting at certain instant of time.

**Describe the solution you'd like**
To build a tool that would help us to visualize the timing diagram. Probably something like this.
![timing](https://user-images.githubusercontent.com/42991063/54883078-7dd35a00-4e89-11e9-85a0-6d10cfc0722a.gif)

 **Are you working on this? (Yes/No)**
No

**Comment by MechaFinch** [comment]
Try placing a Flag from the Misc section and connect a wire to it. It does this.

![waveform visualizer](https://user-images.githubusercontent.com/33042726/54927476-9de63600-4ee8-11e9-98c1-19b85a8d3679.png)

**Comment by satu0king** [comment]
Yes the feature is already present but in a prototype stage. Check #252
