### ISSUE TITLE
Preset not working in Sequential elements.

### ISSUE THREAD

**Issue by theredcap** [CircuitVerse/CircuitVerse#312]
**Describe the bug**
https://circuitverse.org/users/4399/projects/12251
The Preset input does not seem to have any reaction to the sequential system. I have tried it on SR Flip Flop and D Flip Flop but it doesn't seem to bring any change in the output of the Flip Flops

![pre1](https://user-images.githubusercontent.com/42991063/54883491-326f7a80-4e8e-11e9-908f-814f60c106a2.png)

![preset](https://user-images.githubusercontent.com/42991063/54883470-0eac3480-4e8e-11e9-9e9f-3e44f9cf4551.png)

Though the preset is enabled but the output remains the same.
**To Reproduce**
https://circuitverse.org/users/4399/projects/12251
Here is a demo test. Try changing the input value given to preset. 

**Expected behavior**
Whenever the preset signal it enabled the output Q of the Flip Flop should have a value of 1 whatever the value of input and clock signal may be. 

**Desktop (please complete the following information):**
 - OS: Ubuntu 18
 - Browser: Chrome

**Are you working on this issue? (Yes/No)**
No

**Comment by NavonilDas** [comment]
I am working on it.

**Comment by satu0king** [comment]
I think you misunderstood the purpose of preset. Preset is the value you want to reset to. So when reset is triggered by default it resets to 0 but if there is a preset value it presets to that value.

I am not sure if regular flipflops have these things but this is the purpose we use preset for so far. @fpintos might have some inputs on this. Nevertheless we cannot change this now as many circuits might already be using this feature,

**Comment by DoctorPCOD** [comment]
Has this been corrected? The preset function on most FF chips is an asynchronous SET, and is an extremely useful pin. The preset pin does not do anything on any of the sequential elements in Circuitverse, even 5 years after this issue was initially brought up.
