### ISSUE TITLE
Fix discord link

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#313]
The discord link found in the readme file does not work.

The link is: https://discordapp.com/channels/552660710232948749

Discord requires that users be "invited" to a server to have access to it. This is as simple as a single invite link. (set to never expire)

A discord invite should look like "https://discord.gg/######"
(in place of "######" should be a random 6 letter unique identifier)

**Comment by blane1257** [comment]
@jbox144 I believe you can get an invite easily.

**Comment by jbox144** [comment]
@blane1257 Ah yes, here it is! 
https://discord.gg/95x8H7b

**Comment by Parikshit-Hooda** [comment]
Fix this issue by opening a PR @blane1257 . Reference this issue. The current link works fine for me, by the way.

**Comment by blane1257** [comment]
I believe the posted link will only work for users who have already joined the server (i.e. clicked on an invite link and accepted it)

I've never opened a PR before, so im not entirely sure how to, but I'll see what I can do.

**Comment by blane1257** [comment]
I'm sorry, I really have no clue how to do this..

**Comment by monsij** [comment]
I am interested to take up this issue as @blane1257 would not be able to do it. @Parikshit-Hooda

**Comment by Parikshit-Hooda** [comment]
@monsij  go ahead.

**Comment by monsij** [comment]
@Parikshit-Hooda  : This issue has been addressed via #331 . You may close this now.

**Comment by Parikshit-Hooda** [comment]
closed. please make sure your points are updated for gssoc.

**Comment by monsij** [comment]
sorry but I am not participating for gssoc but surely for GSoC 😄

**Comment by Parikshit-Hooda** [comment]
noted. For future instances, please refrain from taking up issues that are specifically marked as gssoc(which is undergoing) just like this issue. Good work. Godspeed.
