### ISSUE TITLE
Reduce the size of production docker image

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3142]
Our current docker image takes around 600MB, we might be able to reduce this by using small base images like alpine.

**Comment by gr455** [comment]
Our build image takes about 2.6 GB I think. Updating to alpine only makes it 2GB
We might have to use a multi-stage build but that might be tricky considering we have multiple services using the same image

**Comment by tachyons** [comment]
Sorry for not making the issue clear enough, this issue is about the production docker file which is already using multi stage build. And it's current size is about 600 MB

**Comment by tachyons** [comment]
https://github.com/CircuitVerse/CircuitVerse/pkgs/container/circuitverse production images are currently built here

**Comment by Prerna-0202** [comment]
I am working on this issue.

**Comment by tachyons** [comment]
Closing this issue as moving to different base image like alpine cause issues in compilation duo to different libc implementation.
