### ISSUE TITLE
[Simulator/Themes] Cannot apply the same theme file twice

### ISSUE THREAD

**Issue by gr455** [CircuitVerse/CircuitVerse#3153]
**Describe the bug**
Cannot apply the same theme file twice even after chagning the colors.

**To Reproduce**
1. Go to the simulator
2. Click on 'Themes'
3. Click on 'Custom Theme'
4. Import a theme file
5. Change some color
6. Apply theme
7. Go back to 'Custom Theme'
8. Import the same theme file again
9. See that the theme does not change this time

**Expected behavior**
The theme should change as described in the imported theme file

**Additional context**

**Comment by Prerna-0202** [comment]
I would like to work on this issue.
@gr455
