### ISSUE TITLE
Speed up docker builds

### ISSUE THREAD

**Issue by vik-y** [CircuitVerse/CircuitVerse#320]
**Is your feature request related to a problem? Please describe.**
Docker builds are too slow. I understand the first build will be slow because it has to download tons of things but if someone makes any change to Gemfile then it again takes forever to fetch in all those gems and rebuild the thing. 

**Describe the solution you'd like**
The basic thing which can be done is to cache the downloaded gems in a docker volume or use a proxy gemserver which caches the gems required and speeds up the builds. 

For caching based approach following might be helpful:
You basically have to setup a gem server using https://github.com/bundler/gemstash and modify `source` in your Gemfile such that it's used only when reachable. 
https://stackoverflow.com/questions/39386806/ignore-gemfile-source-if-source-not-accessible

For caching the downloads in a separate volume: 
https://blog.bigbinary.com/2018/07/25/speeding-up-docker-image-build-process-of-a-rails-application.html

**Additional context**
This is a good starting issue and if anyone is interested in working on this please let me know. 

**Are you working on this? (Yes/No)**
Currently I am mentoring this.

**Comment by gautam-prajapat** [comment]
@vik-y I want to work on this issue. Can you please elaborate more about the issue ?

**Comment by Amansingla97** [comment]
@gautam-prajapat Try setting up the docker.
Now lets take an eg:
Suppose we change the gemfile and compose the docker again.It would take a lot of time to compose it again. Instead of that, @vik-y is suggesting to setup a cache and remote server Gemstash.Gemstash server will fetch the gems from https://rubygems.org and cached them for you! To prove this, you can disable your Internet connection and try again. Gem files (*.gem) are cached indefinitely. Gem dependencies metadata are cached for 30 minutes, so if you bundle again before that, you can successfully bundle without an Internet connection.It speeds up the process.

**Comment by tachyons** [comment]
For development environment or for deployment environments ?

**Comment by Amansingla97** [comment]
We are using docker env for development. In production we are not using it.

**Comment by gautam-prajapat** [comment]
@Amansingla97 Alright, I am working on this issue.

**Comment by tachyons** [comment]
Configuring gemstash for caching in development seems an overkill. If changing something in Gemfile causes downloading whole gems again, then that is bug in our current Docker setup

**Comment by vik-y** [comment]
@tachyons 
Well I guess I'm too late but i think I have to respond to this. The bug is not with our docker setup - it's the problem of Docker philosophy that even though we write an efficient Dockerfile - it turns out to be inefficient. 

Consider  a Dockerfile which does this: 
1. take base ruby image  
2. Copy Gemfile 
3. bundle install 
4. Copy rails code 

Image generated after 3 will have all gems installed. Now until any changes are made to Gemfile - builds will be very fast. 

If any changes are made to Gemfile - we essentially loose the layer with all gems installed and have to start again from 2 - and hence we re download everything again. Unfortunately this is an efficient and recommended way for writing Dockerfiles though it does not fit well with Rails case. Many people have this problem. 

Now another alternative to this would be (apart from the alternatives mentioned above):
make a basic Gemfile which contains gems like Rails 5 , sidekiq , devise , and maybe other gems which will always be there (hopefully) let's call it static-Gemfile 


```Dockerfile
# This is just sample - might be incorrect 
FROM ruby:2.5 
WORKDIR /app
COPY static-Gemfile /app/Gemfile
RUN bundle install 
# Till here the build can be cached because static-Gemfile will never change unless some major upgrade happens. 

# Since most of the things are already installed - this part will be quick 
COPY Gemfile /app/Gemfile 
RUN bundle install
COPY . /app 
# Do whatever else you wish to 
```
