### ISSUE TITLE
Fix pundit deprecation message

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3208]
Pundit gem  is showing the following deprecation message 
```
DEPRECATION WARNING: 'include Pundit' is deprecated. Please use 'include Pundit::Authorization' instead.
```

**Comment by me-aashish** [comment]
Hey @tachyons I would love to work on this issue. Can you please assign it to me if it is still open?

**Comment by tachyons** [comment]
Yes, you can work on this

**Comment by me-aashish** [comment]
Thanks!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by vedant-jain03** [comment]
@me-aashish Any progress?

**Comment by me-aashish** [comment]
@vedant-jain03 sorry for the late reply. Been bit busy with my end sem exams. Actually I tried to fix this issue but I couldn't. Sorry. It will be better if you could assign it to some other better people. Thank you!

**Comment by Nishchay1571999** [comment]
Hey @tachyons is this issue  still open? I would like to work on it if it is

**Comment by vedant-jain03** [comment]
@Nishchay1571999 Thanks, go ahead!

**Comment by Nishchay1571999** [comment]
@vedant-jain03 Hey Can you help and could tell me where to start?

**Comment by vedant-jain03** [comment]
> @vedant-jain03 Hey Can you help and could tell me where to start?

Sure, here:
1. Setup CircuitVerse([ref](https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md))
2. You will see this error in the console while running the server.
3. Debug it.

**Comment by vedant-jain03** [comment]
@Nishchay1571999 Any updates?

**Comment by Pankaj-SinghR** [comment]
Hey, @vedant-jain03 would you please assign me this issue. I would like to give it a shot

**Comment by Pankaj-SinghR** [comment]
hey, @Nishchay1571999 you still working in this bug or need some help

**Comment by vedant-jain03** [comment]
> hey, @Nishchay1571999 you still working in this bug or need some help

Go ahead, @Pankaj-SinghR.

**Comment by Pankaj-SinghR** [comment]
Thanks

**Comment by Pankaj-SinghR** [comment]
Hey, @vedant-jain03 I'm getting no error in console btw I'm using docker container. Do I need to setup Manually to replicate this issue

**Comment by vedant-jain03** [comment]
> Hey, @vedant-jain03 I'm getting no error in console btw I'm using docker container. Do I need to setup Manually to replicate this issue

I will prefer that but the simplest way to do that is just to find the `include Pundit` and replace it!
The description says everything!

**Comment by Pankaj-SinghR** [comment]
> > Hey, @vedant-jain03 I'm getting no error in console btw I'm using docker container. Do I need to setup Manually to replicate this issue
> 
> I will prefer that but the simplest way to do is that to just find the `include Pundit` and replace it! The description says everything!

If I replace `include Pundit` with `include Pundit::Authorization` how would I know it worked cuz my terminal not showing any error

**Comment by vedant-jain03** [comment]
> > > Hey, @vedant-jain03 I'm getting no error in console btw I'm using docker container. Do I need to setup Manually to replicate this issue
> > 
> > 
> > I will prefer that but the simplest way to do is that to just find the `include Pundit` and replace it! The description says everything!
> 
> If I replace `include Pundit` with `include Pundit::Authorization` how would I know it worked cuz my terminal not showing any error

hmm, for that I will prefer the manual setup
@pulkit-30 any way we can see rails deprecation errors in docker?

**Comment by Pankaj-SinghR** [comment]
> > > > Hey, @vedant-jain03 I'm getting no error in console btw I'm using docker container. Do I need to setup Manually to replicate this issue
> > > 
> > > 
> > > I will prefer that but the simplest way to do is that to just find the `include Pundit` and replace it! The description says everything!
> > 
> > 
> > If I replace `include Pundit` with `include Pundit::Authorization` how would I know it worked cuz my terminal not showing any error
> 
> hmm, for that I will prefer the manual setup @pulkit-30 any way we can see rails deprecation errors in docker?

Thanks it's showing now. I'll show update with the progress
