### ISSUE TITLE
Help links in Properties Panel broken

### ISSUE THREAD

**Issue by devartstar** [CircuitVerse/CircuitVerse#3213]
**Describe the bug**
Help links for the circuit elements in the properties panel are not working.
This is because of the change in the file structure of the CircuitVerseDocs repository.

**To Reproduce**
1. Go to `simulator`
2. Click on any circuit element on canvas
3. Click Help button in Properties Panel

**Expected behavior**
Fix them with the proper links.

**Screenshots**

https://user-images.githubusercontent.com/61665451/175778181-02286392-3f3a-4a98-b311-7669843bee1b.mp4

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**

**Comment by Prerna-0202** [comment]
I would like to work on this issue
@tachyons

**Comment by tachyons** [comment]
Go ahead
