### ISSUE TITLE
Backspace not working in Combinational Analysis inputs

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#322]
**Describe the bug**
While entering data in the combinatinalAnalysis inputs, backspace doesn't work. It just stops the input as well. Same goes for delete as well.

**Expected behavior**
Backspace should work as normal

**GIF**

![backspace](https://user-images.githubusercontent.com/42511766/55027622-b874f800-502b-11e9-920b-9aeca9e38f38.gif)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Mozilla Firefox Quantum
 - Version 66.0.1

**Are you working on this issue? (Yes/No)**
No

**Comment by NavonilDas** [comment]
I am Working on it :)

**Comment by Amansingla97** [comment]
https://stackoverflow.com/questions/49263039/backspace-not-working-in-firefox-in-input-field

**Comment by NavonilDas** [comment]
@Amansingla97 it's not specific to Firefox. it was happening in chrome also.
