### ISSUE TITLE
feat: Add transition effect to the Sidebar

### ISSUE THREAD

**Issue by adarrssh** [CircuitVerse/CircuitVerse#3225]
**Is your feature request related to a problem? Please describe.**
I would like to add some transition effects to the sidebar. The sidebar doesn't have any transition effect when it slides from left to right, it just pops out suddenly.

 **Current Sidebar sliding from left to right (without transition)**

https://user-images.githubusercontent.com/85433137/176629746-d0624367-48fd-47b5-96af-c9a9b8d86906.mp4

**Describe the solution you'd like**
I would like to add transition effects to the sidebar ( watch the below video for transition reference only)

https://user-images.githubusercontent.com/85433137/176632289-43ab651e-32a5-4d77-a5cf-a36faa6b9fd2.mp4

**Are you working on this? (Yes/No)**
yes

**Comment by vedant-jain03** [comment]
@adarrssh Open this issue in [this](https://github.com/CircuitVerse/Interactive-Book) repo

**Comment by adarrssh** [comment]
okay @vedant-jain03

**Comment by adarrssh** [comment]
I have open the this issue in different repo @vedant-jain03
