### ISSUE TITLE
Adding a column with Decimal value for binary value in combinationalAnalysis table

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#323]
**Is your feature request related to a problem? Please describe.**
While dealing with tables with large number of rows in the combinationalAnalysis tool a lot of confusion arises, so an extra column with decimal value of corresponding binary values will be very helpful.

**Describe the solution you'd like**
An extra column with decimal value of corresponding binary values

**Describe alternatives you've considered**
This is the best and simple solution according to me.

**Are you working on this? (Yes/No)**
Yes

**Comment by Amansingla97** [comment]
In combinational Analysis the inputs are not always combined and read as decimal values.
eg input =0100( A,B,C,D )
It is not necessary read as input is 4 .Rather it will be read as, the input is 0100 when the B is positive and A,C,D are negative.
I means to say that  always giving a decimal representation gives a false idea that input A,B,C,D are related.
Best Solution according to me would be giving a toggle to have that extra column(only if it is not creating any confusion)

**Comment by sal2701** [comment]
@Amansingla97 I agree with you, I have included a checkbox below the inputs. I will pr it asap

**Comment by Amansingla97** [comment]
@sal2701 that's gr8. Let me know if you need any help.
