### ISSUE TITLE
Update documentation for Simulator Testing

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#3235]
Update documentation

- [ ] update setup.md (instructions to run tests before opening PR)

**Comment by Pankaj-SinghR** [comment]
Hey, @pulkit-30 would you please assign me this issue I would like to work on it

**Comment by pulkit-30** [comment]
Sorry, This issue is under the GSoC'22 project [simulator Improvement](https://github.com/CircuitVerse/CircuitVerse/wiki/GSoC%2722-Project-List#project-4---circuitverse-simulator-improvements)
I am working on it.
