### ISSUE TITLE
Misalign Checkbox in Login 

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3252]
**Describe the bug**
Misaligned Checkbox in Login 
![Screenshot from 2022-08-03 10-03-36](https://user-images.githubusercontent.com/76901313/182524790-ab3e3784-893f-4f47-a544-8f4c80014caa.png)

**To Reproduce**
1. Go to https://circuitverse.org/users/sign_in
2. See an error

**Expected behavior**
The checkbox should be aligned properly

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
No

**Comment by Sarthaknegigit** [comment]
Hey @vedant-jain03 , I would like to work on this issue if you could assign it to me.

**Comment by vedant-jain03** [comment]
> Hey @vedant-jain03 , I would like to work on this issue if you could assign it to me.

Sure, go ahead!

**Comment by codewithnadeem14502** [comment]
hello sir/madam , I am complete new to this , I want to try to fix sir , if you can assign me this , i try my best to solve it , thank you

**Comment by vedant-jain03** [comment]
> hello sir/madam , I am complete new to this , I want to try to fix sir , if you can assign me this , i try my best to solve it , thank you

Hey @codewithnadeem14502, @Sarthaknegigit is working on it 
You can check out other open unassigned issues!

Welcome to the Community!

**Comment by Sarthaknegigit** [comment]
@vedant-jain03 Resolved this issue in PR #3254. Please review.

**Comment by debrajrout** [comment]
Hi I would  like to resolve the issue if u assign it to me

**Comment by Sarthaknegigit** [comment]
@debrajrout Hey Debraj, I am already working on this issue with an ongoing PR. 
You can check other issues with `good first issue` label if you are new.

**Comment by debrajrout** [comment]
@Sarthaknegigit Sure sure.
And thank you.

**Comment by itsAastha** [comment]
The misalignment still exists, please check again

**Comment by Sarthaknegigit** [comment]
> The misalignment still exists, please check again

Hey Astha, there is some problem with appveyor while pushing the build, that' why the approved PR hasn't been pushed yet.

**Comment by siddhi-244** [comment]
Can I try this? Hello myself Siddhi Bhanushali and I am planning to apply for gsoc next year and would really love to work with this organization

**Comment by Sarthaknegigit** [comment]
> Can I try this? Hello myself Siddhi Bhanushali and I am planning to apply for gsoc next year and would really love to work with this organization 

Hey Siddhi, this issue has already been resolved and approved. You can try to solve other issues with `good first issue` tag if you are a beginner.
Welcome to Circuitverse Community.

**Comment by natzmonteiro** [comment]
#3292  @vedant-jain03 Is this issue still open? I would like to work on it.

**Comment by joannasjohnraj** [comment]
@vedant-jain03 Is this issue still open? I would like to work on it.

**Comment by vedant-jain03** [comment]
> @vedant-jain03 Is this issue still open? I would like to work on it.

Hey @joannasjohnraj the PR for the issue is already been raised and under review, you can checkout other open issues!

**Comment by Prerna-0202** [comment]
completed via https://github.com/CircuitVerse/CircuitVerse/pull/3360
