### ISSUE TITLE
Merge two if conditions into one

### ISSUE THREAD

**Issue by Rounak-28** [CircuitVerse/CircuitVerse#3283]
In `public/js/listeners.js` there are some if conditions inside another condition like this: -

` if ( // something ) {
     if ( // something ) {
        // the code
        }
     } `

Those two ` if ` can be merged together.

**Comment by vedant-jain03** [comment]
cc @pulkit-30

**Comment by pulkit-30** [comment]
hey @Rounak-28,
Welcome to CircuitVerse 🎉 
[pubic/](https://github.com/CircuitVerse/CircuitVerse/tree/master/public) dir code is for old simulator version.
You can find current version code in the [simulator/](https://github.com/CircuitVerse/CircuitVerse/tree/master/simulator) dir.

**Comment by tachyons** [comment]
We are no longer accepting contributions for old simulator
