### ISSUE TITLE
[style]: importing and exporting circuit-files dialog box 

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#3286]
**Describe the bug**

Need to improve import and export circuit-files dialog box styles.

<img width="489" alt="Screenshot 2022-09-11 at 12 56 21 PM" src="https://user-images.githubusercontent.com/76155456/189516810-5e8e75d5-82c4-4e43-bcd7-78e8202edc23.png">

<img width="470" alt="Screenshot 2022-09-11 at 12 56 35 PM" src="https://user-images.githubusercontent.com/76155456/189516818-53ace361-0ab1-48aa-afe0-3f2074e889ad.png">

**Expected behavior**

<img width="640" alt="Screenshot 2022-09-11 at 12 57 01 PM" src="https://user-images.githubusercontent.com/76155456/189516837-30b1cd24-601d-4e7d-ab4f-31959402f817.png">

<img width="634" alt="Screenshot 2022-09-11 at 12 57 15 PM" src="https://user-images.githubusercontent.com/76155456/189516851-7dd00a9c-ac3a-44ba-a308-99e0e6444722.png">

**Comment by Devraj5032** [comment]
I would like to work on it.

**Comment by Devraj5032** [comment]
I would like to work on it.

**Comment by vedant-jain03** [comment]
@Devraj5032 this issue is under `GSoC2022`!
Thanks for your interest, you can check out another open issue!
