### ISSUE TITLE
Check box and "Remember Me" not alinged on log in page.

### ISSUE THREAD

**Issue by omsurase** [CircuitVerse/CircuitVerse#3292]
**Describe the bug**
On Log In page, "Remember Me" and its corresponding text box is not aligned properly.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'Log In'
3. Scroll down to 'Forgot Password

**Expected behavior**
"Remember me" and its checkbox should be properly aligned. They should also be responsive to screen size changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/98473361/190497425-e547bce3-f7b7-4454-a8fd-008012c142ba.png)

**Device Information [optional]:**
 - OS: Windows
 - Browser: Chrome
 - Version: 105.0.5195.102

**Additional context**

**Are you working on this issue?  Yes**

**Comment by vedant-jain03** [comment]
#3252
