### ISSUE TITLE
feat: notify group members for the new assignment in the group

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3294]
**Is your feature request related to a problem? Please describe.**
- All group members of a group should get notify regarding the new assignment in the group.

**Describe the solution you'd like**
- Create a new notification in `app/notifications`(we are using the `noticed` gem, [documentation](https://github.com/excid3/noticed))
- When group mentors click the submit button in the form for a new assignment, the notifications should be delivered to all group members as recipients.

**Are you working on this? (Yes/No)**
No

**Comment by omsurase** [comment]
@vedant-jain03  i would like to work on this.

**Comment by vedant-jain03** [comment]
@omsurase Sure go ahead!

**Comment by omsurase** [comment]
@vedant-jain03 could you please tell me what type of notification is expected?
Currently, group members are getting notifications in emails regarding new assignments.

**Comment by vedant-jain03** [comment]
> @vedant-jain03 could you please tell me what type of notification is expected? Currently, group members are getting notifications in emails regarding new assignments.

@omsurase we are expecting the web platform notification.
Currently, we have two notification events
- when someone stars a project, notify the author
- when someone forks a project, notify the author

We want to notify all the group members for new assignment published by group mentor!

**Comment by VaibhavUpreti** [comment]
Hi , is anybody currently working on this issue? If not ... I would like to contribute.

**Comment by omsurase** [comment]
hey @VaibhavUpreti I'm still working on it, feel free to come over to slack and we can work on this together

**Comment by VaibhavUpreti** [comment]
Oops I missed checking slack... well thanks for the heads up 👍

**Comment by omsurase** [comment]
@vedant-jain03 unassigning myself because i cant seem to fix this issue.

**Comment by vedant-jain03** [comment]
@VaibhavUpreti are you interested to work on this issue?

**Comment by VaibhavUpreti** [comment]
Yes ... I think I can make it work. Kindly assign me the issue.

**Comment by bijoysijo** [comment]
Hi @vedant-jain03, @VaibhavUpreti I'd also like to work on this. 

@VaibhavUpreti  Can we work together?
