### ISSUE TITLE
fix: not to show mark all as read button for no unread notifications.

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3299]
**Describe the bug**
not to show mark all as read button for no unread notifications.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'notification icon'
3. Scroll down to 'see all'

**Expected behavior**
The button for `mark all as read` should be visible when there are unread notifications.

**Screenshots**
![Screenshot from 2022-09-28 08-36-14](https://user-images.githubusercontent.com/76901313/192678348-29b48930-f992-47ee-8b93-7f791fc2058f.png)

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
No

**Comment by r3yc0n1c** [comment]
Hi @vedant-jain03! I want to work on this issue

**Comment by vedant-jain03** [comment]
> Hi @vedant-jain03! I want to work on this issue

Sure, go ahead!
