### ISSUE TITLE
Login loop after clicking 'Save Online'

### ISSUE THREAD

**Issue by manuelcarrizo** [CircuitVerse/CircuitVerse#33]
Steps to reproduce

- Edit a project and add some components
- Click `Save Online` and name the project
- The side redirects to `/users/sign_in`
- Don't log in, click the CircuitVerse logo

The site redirects to the home, then to the simulator and you see the message `You have to login to save the project, you will be redirected to the login page.` that redirects again to `/users/sign_in`

**Comment by satu0king** [comment]
It is interesting that no one mentioned this before.

**Comment by satu0king** [comment]
Resolved
