### ISSUE TITLE
feat: Include mark as read button in the drop down menu of notifications

### ISSUE THREAD

**Issue by VaibhavUpreti** [CircuitVerse/CircuitVerse#3313]
**Is your feature request related to a problem? Please describe.**
I think it will be much more user friendly if users had an option to mark all notifications as read from the drop down itself ... rather than going to the notification page every time. 

**Describe the solution you'd like**
To include 
- mark as read button in the drop down menu of notifications

I propose a solution like the one mentioned below ...
**Describe alternatives you've considered**

**Additional context**

BEFORE 
![before read](https://user-images.githubusercontent.com/85568177/195151613-bda5c4dd-6847-4626-a657-22f86f92138f.png)

AFTER (no more notifications)
![after read](https://user-images.githubusercontent.com/85568177/195151682-d1359843-33b3-4c33-bc68-a2220fc1fe17.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by VaibhavUpreti** [comment]
Also there seems to be some issue with overlapping of text and the green unread circle when a notification is long( occupies 2 lines )

![beforefix](https://user-images.githubusercontent.com/85568177/195164732-d162947d-9db1-4d05-8f17-c5ceb3c8e164.png)

**Comment by tachyons** [comment]
@nitin10s Could you check if this is needed ? Close button now looks odd with mark as read button

**Comment by vedant-jain03** [comment]
> @nitin10s Could you check if this is needed ? Close button now looks odd with mark as read button

Can we have `mark as read` button in footer, I mean on lets not touch header, we have space in footer we can place `mark as read` on left and `see all` on right.

WDYT?

**Comment by VaibhavUpreti** [comment]
Or maybe we can have the cross(X) svg when there are no unread notifications and replace it with 'mark as read' when we have unread notifications . Something like in this image
![image](https://user-images.githubusercontent.com/85568177/195516823-1798c307-8618-4ccb-935b-cf00fbc1ef99.png)

**Comment by vedant-jain03** [comment]
> Or maybe we can have the cross(X) svg when there are no unread notifications and replace it with 'mark as read' when we have unread notifications . Something like in this image ![image](https://user-images.githubusercontent.com/85568177/195516823-1798c307-8618-4ccb-935b-cf00fbc1ef99.png)

What if user have unread notifications and do not want to mark them as read?
The close button and mark as read have different context, I think we should make them separately.

WDYT?

**Comment by VaibhavUpreti** [comment]
> > Or maybe we can have the cross(X) svg when there are no unread notifications and replace it with 'mark as read' when we have unread notifications . Something like in this image ![image](https://user-images.githubusercontent.com/85568177/195516823-1798c307-8618-4ccb-935b-cf00fbc1ef99.png)
> 
> What if user have unread notifications and do not want to mark them as read? The close button and mark as read have different context, I think we should make them separately.
> 
> WDYT?

Yes I think this makes much more sense.
