### ISSUE TITLE
Duplication of tags is not handled 

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#332]
**Describe the bug**
If in the project update page, if the input for tags is `tag tag tag tag`, then this duplication is not removed and 4 taggins are created, while there should only be 1. 

**To Reproduce**
1. Go to project edit page
2. Input `tag tag tag tag` in tags input
2. Click `Update Project`
3. Go to project preview page

**Expected behavior**
Duplicate tags should be removed

**Screenshots**
`project_preview_page`
![image](https://user-images.githubusercontent.com/22021150/55201116-81e3dc80-51e7-11e9-8458-53cd02840b8e.png)

`projects/tags/tag`
![image](https://user-images.githubusercontent.com/22021150/55201129-958f4300-51e7-11e9-93eb-7c1dfae8c6b7.png)

**Desktop (please complete the following information):**
Platform agnostic

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes. @shubhankarsharma00 added tags in PR #185 and might have some points to add. We can work on it together.

**Comment by shubhankarsharma00** [comment]
Yeah, I think this can be solved in 2 ways. One is checking out the tags when the tag list is converted to tags array and remove duplicates. But Another can be to validate uniqueness in Active record in taggings.rb models using validate_uniqueness_of [like this](https://stackoverflow.com/questions/923796/how-do-you-validate-uniqueness-of-a-pair-of-ids-in-ruby-on-rails)

**Comment by shubhankarsharma00** [comment]
@ankitkataria does this look okay now?

**Comment by ankitkataria** [comment]
Fixed via #422
