### ISSUE TITLE
Remember me button is not rendering properly 

### ISSUE THREAD

**Issue by aashimawadhwa** [CircuitVerse/CircuitVerse#3331]
**Describe the bug**
remember me button on the signup page is rendering in an unaligned manner with the checkbox on Chrome and Firefox.

**Screenshots**
![Screenshot from 2022-10-30 22-36-11](https://user-images.githubusercontent.com/73706697/198891969-16c9176c-8f89-44dc-9a1e-47480bbeaa9f.png)
![Screenshot from 2022-10-30 22-45-21](https://user-images.githubusercontent.com/73706697/198892024-ded7365d-3cc9-476c-847f-5792da0c4bad.png)

**Are you working on this issue? (Yes/No)**
**yes I would like to take this issue**

**Comment by vedant-jain03** [comment]
@aashimawadhwa this issue is already raised https://github.com/CircuitVerse/CircuitVerse/issues/3252 and the PR for this is under review!
