### ISSUE TITLE
Overlapping Notification and unread notification green circle

### ISSUE THREAD

**Issue by VaibhavUpreti** [CircuitVerse/CircuitVerse#3333]
**Describe the bug**
Overlapping Notification and unread notification green circle

**To Reproduce**
1. Go to 'Notifications modal'

**Expected behavior**
The text should not overlap with the unread notification circle.

**Screenshots**
![Screenshot 2022-11-01 at 5 51 39 PM](https://user-images.githubusercontent.com/85568177/199231217-e0bcfcb1-50b5-4e62-9a57-cfcc2be0447b.png)

**Device Information [optional]:**
 - Browser [e.g. chrome, safari] : All web browsers ... css issue

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by sulogna2001** [comment]
Hey @VaibhavUpreti  can I work on this issue?
