### ISSUE TITLE
Search failing on large search

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#334]
Goto: https://circuitverse.org/search?utf8=%E2%9C%93&q=test

Error: ` ActionView::Template::Error (uninitialized constant SearchPaginateRenderer::ELLIPSIS)`

**Are you working on this issue? (Yes/No)**
No

**Comment by Amansingla97** [comment]
As the database grows we ultimately have to shift to elastic search.pgsearch would be too slow to process all the text data.Postgres full-text search is pretty solid for straightforward use cases, but there are a number of reasons why Lucene (and thus Solr and ElasticSearch) is superior both in terms of performance and functionality.

**Advantages to ElasticSearch**

->Scale your indexing and search load separately from your regular database load.
->More flexible term analysis for things like accent normalizing, linguistic stemming, N-grams, markup removal… Other cool features like spellcheck, "rich content" (e.g., PDF and Word) extraction…
->Lucene can do everything on the Postgres full-text search can do.
->Much better and faster term relevancy ranking, efficiently customizable at search time.
->Probably faster search performance for common terms or complicated queries.
->Probably more efficient indexing performance than Postgres.
->Better tolerance for change in your data model by decoupling indexing from your primary data store
