### ISSUE TITLE
Search results not rendered correctly

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#335]
https://circuitverse.org/search?page=1&q=LED&utf8=%E2%9C%93

![image](https://user-images.githubusercontent.com/2092958/55230942-4da00880-5247-11e9-9144-e2f8ce453f26.png)

The HTML content is getting rendered as text instead of HTML

**Are you working on this issue? (Yes/No)**
No

**Comment by tabishshakeel** [comment]
Okay! I am working on this issue.

**Comment by shubhankarsharma00** [comment]
@tabishshakeel change this line to load sanitized html https://github.com/CircuitVerse/CircuitVerse/blob/5863caf21cbce9d5cd17cc306a4ea6099d947aea/app/views/logix/search.html.erb#L13
using 
 https://edgeapi.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html
