### ISSUE TITLE
Aligment of the remember me option in login page

### ISSUE THREAD

**Issue by omthakare16** [CircuitVerse/CircuitVerse#3354]
**Describe the bug**
"Remember me" text not align with the check box in login page

**To Reproduce**
1. Go to https://circuitverse.org/users/sign_in
2. See the error below the email and password input section. 

**Expected behavior**
It should be perfectly aligned with the checkbox given for it.

**Screenshots**
![Screenshot from 2022-11-17 16-31-13](https://user-images.githubusercontent.com/83799380/202431293-605880c3-a359-47c2-aa77-a4e698dc9c4a.png)

**Device Information [optional]:**
for all devices this issue is visible.

**Are you working on this issue? (Yes/No)**
No, but I would like to work if assigned to me.

**Comment by vedant-z** [comment]
@omthakare16 May I work on this please?

**Comment by omthakare16** [comment]
@vedant-z I myself want to work on this issue but I don't have right to assign anyone, @vedant-jain03  can you assign me.

**Comment by akashshukla7458** [comment]
@vedant-jain03  @omthakare16  can i work on this issue???

**Comment by vedant-jain03** [comment]
This issue is duplicate
https://github.com/CircuitVerse/CircuitVerse/issues/3252
