### ISSUE TITLE
bug: UI / Remember me button not positioned correctly in user sign in page

### ISSUE THREAD

**Issue by danger-ahead** [CircuitVerse/CircuitVerse#3359]
**Expected behavior**
The remember me text should be properly aligned with the checkbox.

**Screenshots**
![image](https://user-images.githubusercontent.com/55531939/202887396-c8389793-cca4-4075-8d2e-9d38d4036c0d.png)
![image](https://user-images.githubusercontent.com/55531939/202887676-73fa756d-2dcc-4be8-b78e-5868bc95e92a.png)

**Device Information [optional]:**
 - OS: [e.g. iOS] Fedora 37
 - Browser [e.g. chrome, safari] Firefox
 - Tested on other browsers: Yes, mobile browsers, Google Chrome

**Are you working on this issue? (Yes/No)** Yes

**Comment by Shruti799** [comment]
I would like to work on this issue and fix it.
