### ISSUE TITLE
feat: infinite scroll feature in recent circuits section instead of pagination.

### ISSUE THREAD

**Issue by Waishnav** [CircuitVerse/CircuitVerse#3365]
**Is your feature request related to a problem? Please describe.**
Yes, there is a User-experience flaw on the home page **Recent Circuit** section.

**Describe the solution you'd like**
Instead of pagination, we can have an infinite scroll feature for a better user experience.
So that users don't need to click on the Nth page again n again.

**Describe alternatives you've considered**
Or we can have some circuits in the recent section and one new route where all the circuits made by users will be dumped there and people can explore the circuits on that page
And an infinite scroll feature will be there for better usability and interaction.

**Additional context**
Infinite scroll feature like youtube feed.

**Are you working on this? (Yes/No)**
Yes. I do want to work on this issue.

**Comment by Sekhar-Kumar-Dash** [comment]
hello Waishnav  can you please assign me this issue and also i am new to open source can you please guide me through

**Comment by Sekhar-Kumar-Dash** [comment]
hello tachyons please assign me this issue

**Comment by GarvitSinghal47** [comment]
@tachyons i would love to work on this issue after product review , can you plz assign me after product review .

**Comment by vedant-jain03** [comment]
@Waishnav There are more than 50k+ circuits on CircuitVerse. This feature will not be compatible for long case.

**Comment by Waishnav** [comment]
@vedant-jain03 Same goes for pagination WDYT?
Users would like to scroll instead of clicking on the page number to get there. 
I might be wrong, but that way user feel not lost as well as it feels easy to scroll down for more content.

Considering 50K circuits we can have implementation of mix (pagination + infinite scroll).

**Comment by salmoneatenbybear** [comment]
@Waishnav is this still in progress or can be closed

**Comment by ChandrakantaMandal** [comment]
Hi maintainers 👋
I’m interested in working on this issue and would love to contribute. If the issue is still open, please assign it to me.

**Comment by Asrani-Aman** [comment]
In GsoC 25 we dicided to keep this as pagination
