### ISSUE TITLE
feat: add a default message for empty group fields

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3380]
**Is your feature request related to a problem? Please describe.**
For empty group members, mentors and assignments, the group page needs to have some default message:
- Mentors: `There are no mentors in the group, click "+ Add Mentors" button to add mentors.`
- Members: `There are no members in the group, click "+ Add Member" button to add members.`
- Assignments: `There are no assignments in the group, click "+ Add Assignments" button to start an assignment.`

![Screenshot from 2022-12-07 22-46-51](https://user-images.githubusercontent.com/76901313/206247566-b80cc7e8-31ac-4bed-bd09-fceb54245aaf.png)

**Additional context**
The assignment section should not show the table for empty data.

**Are you working on this? (Yes/No)**
No

**Comment by VaibhavUpreti** [comment]
How about an approach like this?
Before-
![Uploading Screenshot 2022-12-08 at 1.31.19 AM.png…]()

After-
![Screenshot 2022-12-08 at 1 32 17 AM](https://user-images.githubusercontent.com/85568177/206283720-34200f52-ebea-45b6-b6e7-b15f36573f76.png)

Also I think removing the table might be a bad idea(when no assignments) , cause it gives a brief description of how the assignments will be once the user creates them.

**Comment by thejaysharma** [comment]
Hey @VaibhavUpreti , If this issue is still open I want to work on this, can you assign it to me.

**Comment by vedant-jain03** [comment]
@thejaysharma the PR for the issue is under review, kindly checkout other open and unassigned issues, thanks!

**Comment by Malavi1** [comment]
is the issue still under the review?
