### ISSUE TITLE
 Forum UI update

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/CircuitVerse#3381]
**Is your feature request related to a problem? Please describe.**
 Forum UI update. It's an ndividual issue regarding this issue #3316 

**Describe the solution you'd like**
I will first of all create an updated UI in Figma as an prototype and then will customize the Forum UI

**Are you working on this? (Yes/No)**
Yes

**Tasks**

- [x] Design Prototype [Click to open design](https://www.figma.com/file/I6qAJbSV4W69NNWZbNdcr7/Circuitverse-Forum-UI?node-id=0%3A1&t=H0tSjwun90CBL96d-1)
- [x] Fix all the broken links and errors
- [x] Update UI

**Comment by Waishnav** [comment]
The design Looks good. But we can have some improvements in the comment box.
If there is gonna be markdown support then we can take github's comment box for inspiration WDYT?

**Comment by Tanmoy741127** [comment]
@Waishnav 
Yes the design of Github Editor is simple. I sm thinking the same. That does not included in the design because, currently I am working on the main design of the forum and resolving some bugs that are already there in the forum.
