### ISSUE TITLE
feat: add core team members name in about us page

### ISSUE THREAD

**Issue by VaibhavUpreti** [CircuitVerse/CircuitVerse#3390]
**Is your feature request related to a problem? Please describe.**
Issue for First Time Contributors to Circuitverse.

Add names of Aman, Vedant, Pulkit and Devjit (GSoC'22 Participants) in the about page of [circuitverse](https://circuitverse.org/), in the core team section.

**Describe the solution you'd like**
You have to add the following data in [about_controller.rb](https://github.com/CircuitVerse/CircuitVerse/blob/d4c0c2e1b37aaf64f4e470b81eb16e494177e86f/app/controllers/about_controller.rb#L34) file.

**STEPS TO FOLLOW**
1. Go to [about_controller.rb](https://github.com/CircuitVerse/CircuitVerse/blob/d4c0c2e1b37aaf64f4e470b81eb16e494177e86f/app/controllers/about_controller.rb#L34))

2. Add the following code
```
               { name: "Vedant Jain",
                img: "https://avatars.githubusercontent.com/u/76901313?v=4", link: "https://github.com/vedant-jain03" },
              { name: "Aman Singh",
                img: "https://avatars.githubusercontent.com/u/77198905?v=4", link: "https://github.com/aman-singh7" },
              { name: "Devjit Choudhury",
                img: "https://avatars.githubusercontent.com/u/61665451?v=4", link: "https://github.com/devartstar" },
              { name: "Pulkit Gupta",
                img: "https://avatars.githubusercontent.com/u/76155456?v=4", link: "https://github.com/pulkit-30" }

```
It should look something like this
![names](https://user-images.githubusercontent.com/85568177/206830691-014b1336-9f34-4570-a799-74b728640f15.jpg)

3. Raise a pull request for the same.

**Additional context**
Issue Meant for first time contributors.

**Are you working on this? (Yes/No)**
No

**Comment by apschauhan03** [comment]
I am interested
