### ISSUE TITLE
CircuitVerse Forum `AllThreads` link broken

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/CircuitVerse#3392]
**Describe the bug**
The link on `All Threads` button has been broken.

**To Reproduce**
1. Go to 'https://circuitverse.org/forum/threads/category/feedback'
2. Click on 'All Threads' under 'Filter Section'
3. See error

**Expected behavior**
That page should  show all the threads available in that forum

**Screenshots**
![image](https://user-images.githubusercontent.com/57363826/206862676-1b931284-5ea0-49a2-b46c-eb0768f3f3e6.png)

**Device Information [optional]:**
 - Browser [Google Chrome]

**Additional context**

**Are you working on this issue? (Yes/No)**
Currently No
[If anyone doesn't take the issue, will work on the issue after few weeks]

**Comment by GarvitSinghal47** [comment]
i would like to work on this issue , can you assign me this issue

**Comment by Tanmoy741127** [comment]
@vedant-jain03 can you asiign this to @GarvitSinghal47

**Comment by vedant-jain03** [comment]
@GarvitSinghal47 I have assigned you the issue #3393 , check that out!
