### ISSUE TITLE
CircuitVerse Forum `All under By Category`  link broken

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/CircuitVerse#3393]
**Describe the bug**
The link on `All Threads` button has been broken.

**To Reproduce**
1. Go to 'https://circuitverse.org/forum/threads/category/feedback'
2. Click on 'All' under 'By Category'
3. See error

**Expected behavior**
That page should  show all the threads of any category available in that forum

**Screenshots**
![image](https://user-images.githubusercontent.com/57363826/206862846-cc8ac743-e9e3-49b2-8aa6-a7a9553e3ada.png)

**Device Information [optional]:**
 - Browser [Google Chrome]

**Are you working on this issue? (Yes/No)**
Currently No
[If anyone doesn't take the issue, will work on the issue after few weeks]

**Comment by GarvitSinghal47** [comment]
i would like to work on this issue , can you assign me this issue

**Comment by Tanmoy741127** [comment]
@vedant-jain03 can you asiign this to @GarvitSinghal47

**Comment by Ujjwal55** [comment]
If this issue is still open, I would like to work on this @vedant-jain03

**Comment by GarvitSinghal47** [comment]
> If this issue is still open, I would like to work on this @vedant-jain03

 currently, I am working on this issue, you can look for any other open issues to work on.

**Comment by Ujjwal55** [comment]
> > If this issue is still open, I would like to work on this @vedant-jain03
> 
> currently, I am working on this issue, you can look for any other open issues to work on.

sure

**Comment by GarvitSinghal47** [comment]
@vedant-jain03 I think this issue is resolved already as there is no error now, I think you can close this issue.

**Comment by Tanmoy741127** [comment]
Ok👍
