### ISSUE TITLE
CircuitVerse Forum : add message regarding "login is mandatory  to comment" under thread page

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/CircuitVerse#3394]
**Is your feature request related to a problem? Please describe.**
Currently, in Circuitverse Forum, when you navigate to any specific thread, you will not see any comment box or message. Without login, any user is not permitted to comment on any question until the user is logged in. But while the user is not logged in, no message is shown to him under the thread.

Just an example:
![image](https://user-images.githubusercontent.com/57363826/206863989-680f33b5-1e80-4466-b09a-073b1ee9e243.png)

**Describe the solution you'd like**
 There should be a message or bar like "Login or Register yourself to join the conversion". 
As an example:
![image](https://user-images.githubusercontent.com/57363826/206863805-116816f1-4bdf-4154-94f0-133b10ad80a8.png)

**Are you working on this? (Yes/No)**
Currently Yes

**Comment by Tanmoy741127** [comment]
@vedant-jain03 can you assign to me ?

**Comment by diivi** [comment]
are you still working on this @Tanmoy741127 ?

**Comment by Tanmoy741127** [comment]
Yes . I am working on the UI update. So doing this one issue also with that.

**Comment by Tanmoy741127** [comment]
It's fixe d in an internal PR https://github.com/CircuitVerse/simple_discussion/pull/1 . So closing this issue
