### ISSUE TITLE
feat: Add command to copy database template in readme setup

### ISSUE THREAD

**Issue by VaibhavUpreti** [CircuitVerse/CircuitVerse#3397]
**Is your feature request related to a problem? Please describe.**
A lot of new contributors (especially one's new to rails) find the 4th step of the Setup.md readme file difficult to understand.

We can add the command directly they can use to copy the postgres credentials in the database.yml file

**Describe the solution you'd like**
add this command in readme

```bash
cp config/database.example.yml config/database.yml
```

**Describe alternatives you've considered**

**Additional context**
BEFORE
![before](https://user-images.githubusercontent.com/85568177/207076310-5fbab2e2-5844-4e01-90e1-c3bd2e285d01.jpg)
AFTER
![after](https://user-images.githubusercontent.com/85568177/207076291-072de432-008c-4dcb-bacd-6f07113f213e.jpg)

**Are you working on this? (Yes/No)**
Yes

**Comment by Adityasaini10012001** [comment]
@VaibhavUpreti assign this to me
