### ISSUE TITLE
Alignmemt issue in login page

### ISSUE THREAD

**Issue by VenomFate-619** [CircuitVerse/CircuitVerse#3402]
**Describe the bug**
Remember Me and checkbox are not alinged 

**To Reproduce**
1. Go to the login page

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/67755128/207247927-adbbbef4-6f2b-4d8b-8129-6003786a3712.png)

![image](https://user-images.githubusercontent.com/67755128/207248170-03e97c50-debd-4f67-a4a9-b31c0f3c5643.png)

**Device Information [optional]:**
 - OS: popOS
 - Browser brave
 - Version 1.45.127 Chromium: 107.0.5304.110 (Official Build) (64-bit) 

**Are you working on this issue? (Yes/No)**
Yes i would  like work on it

**Comment by Prerna-0202** [comment]
hey @VenomFate-619 , this issue has been already solved in [0e3c000](https://github.com/CircuitVerse/CircuitVerse/commit/0e3c000393c40daba2a1f9f2edba0b69582a478a).
You can check out other good first issues.
