### ISSUE TITLE
Add markdown support in the forum

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3427]
Markdown support can be added to cirucuitverse form by using https://github.com/vmg/redcarpet and overriding [formated_content helper](https://github.com/excid3/simple_discussion/blob/9a4a9b553b785c5918fed236ab78a58ffdb84287/app/helpers/simple_discussion/forum_posts_helper.rb#L13)

**Comment by VaibhavUpreti** [comment]
I would like to work on this, If this issue is not taken.

**Comment by vedant-jain03** [comment]
Go ahead @VaibhavUpreti

**Comment by Tanmoy741127** [comment]
@VaibhavUpreti are you working currently?

**Comment by Tanmoy741127** [comment]
@tachyons 
Can you take a look at this [https://github.com/nhn/tui.editor](https://github.com/nhn/tui.editor)
We can have this type of interface for markdown editor for the forum . I found this Js library popular and well maintained for markdown and WYSIWYG editor.
