### ISSUE TITLE
Follow and Unfollow ( Users) #2

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#3428]
#2  

Is your feature request related to a problem? Please describe.
Add a new feature of follow other users on the platform.

Further Suggestion->
After adding a feature of follow users we can attach notification  such that whenever any user which we are following will make any new project , the user will get notification for that.

Additional context

Are you working on this? (Yes)

**Comment by Aadarshprajapati777** [comment]
I want to work on this feature

**Comment by Prerna-0202** [comment]
Hey @Aadarshprajapati777, Actually I have already started working on this issue. So you can checkout other open issues to work.

**Comment by Aadarshprajapati777** [comment]
Can you please suggest me some beginner friendly issues, I am new in open source contributions.
