### ISSUE TITLE
Add  web push notification.

### ISSUE THREAD

**Issue by Tanmoy741127** [CircuitVerse/CircuitVerse#3439]
Individual issue of #3316 

**Is your feature request related to a problem? Please describe.**
Add web push notifications for users.

**Describe the solution you'd like**
I like to use firebase push notifications.

**Are you working on this? (Yes/No)**
Yes

**Comment by Tanmoy741127** [comment]
@vedant-jain03 can you please assign this ?

**Comment by VaibhavUpreti** [comment]
This one's a part of GSOC'22 project, [pull](https://github.com/CircuitVerse/CircuitVerse/pull/3273)

**Comment by Tanmoy741127** [comment]
Ohh 👀
