### ISSUE TITLE
login page remember me button issue

### ISSUE THREAD

**Issue by GarvitSinghal47** [CircuitVerse/CircuitVerse#3445]
**Describe the bug**
There was a misalignment in the remember me button and also it is working kind of wrong on clicking.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'login '
3. See the error

**Expected behavior**

**Screenshots**
before:
[CircuitVerse---Digital-Circuit-Simulator.webm](https://user-images.githubusercontent.com/82756460/209983348-3c1ca5b8-7077-428d-83a4-42674a70e1a2.webm)

after:
https://user-images.githubusercontent.com/82756460/209983379-a4564083-cce8-4b64-9a8b-95a77db6eeb6.mp4

**Device Information [optional]:**
 - OS: window
 - Browser: Chrome, brave 

**Are you working on this issue? **
Yes.

**Comment by GarvitSinghal47** [comment]
@vedant-jain03 can you assign me this issue so that I can create a pull request.

**Comment by danger-ahead** [comment]
I believe this has been fixed through this PR: https://github.com/CircuitVerse/CircuitVerse/pull/3360

**Comment by GarvitSinghal47** [comment]
I don't think so as there was h6 remember me text in login page which was  creating this issue not the checkbox. 

This issue is particular related to the text which was causing the boz to behave weird. I have attached a video for the same as well. 

You are saying right the issue is related to the previous pr but the previous pr is related to the error in checkbox but this issue is specifically related to the misalignment of both the data of login page specifically.

**Comment by GarvitSinghal47** [comment]
yup, you are right, closing this issue, seen this issue while using the website but came to know your pr already resolved it.

> I believe this has been fixed through this PR: #3360
