### ISSUE TITLE
BUG in embeded Mode

### ISSUE THREAD

**Issue by SubhajitCode** [CircuitVerse/CircuitVerse#345]
**Describe the bug**
The Bug appears when We embed the iframe generated in to another website .CircuitVerse Does not take any user input ,mouse click on the button is also broken
**To Reproduce**
1. open a project project window
2. Click on 'Embed' to generate embed iframe tag 
3. paste in your personal Website
4. Some interactivity is lost and circuit verse does not take any mouse input to change the state of button or any other input for that matter.
5.Javascript error

**Expected behavior**
It should take mouse input keyboard input properly
**Screenshots**
![Screenshot_20190402_181303](https://user-images.githubusercontent.com/41638148/55403234-03829400-5573-11e9-9bf4-67e869c36cb7.png)

**Reason**
Violation Of Cross-Origin Policy of Browsers
in the bellow commit https://github.com/CircuitVerse/CircuitVerse/commit/9d117395e369486feb7d8680819777549a8719b7#diff-eb48d01219533c6484ace1ac12e464bf the change had been made .
iframe is trying to access parent windows  keyboard  inputs that violets browsers  cross-origin policy. It can open door to attacks like XSS . So Browser (Checked on Chrome) blocks it.
 

**Additional context**
Reverting the commit will bring back issue https://github.com/CircuitVerse/CircuitVerse/issues/307

**Are you working on this issue? (Yes/No)** Yes

**Comment by satu0king** [comment]
@ankitkataria , I think you worked on this, maybe you have some inputs.
