### ISSUE TITLE
Remember me not properly aligned

### ISSUE THREAD

**Issue by anasaijaz** [CircuitVerse/CircuitVerse#3462]
**Describe the bug**
On the login page the remember me checkbox and label is not properly aligned

![image](https://user-images.githubusercontent.com/27632474/210388493-01a502a9-e26d-4ad4-a75a-d36ca3dfb323.png)

**Comment by MauryanKansara** [comment]
hey I would like to fix this issue. Can you please assign it to me?

**Comment by MauryanKansara** [comment]
![CircuitVerse - Digital Circuit Simulator - Brave 1_3_2023 10_40_16 PM](https://user-images.githubusercontent.com/86093112/210406386-9c1b1d29-50c1-4a88-9215-ca8d8a511376.png)


Does this look good to you?

**Comment by anasaijaz** [comment]
Hi @MauryanKansara I am not the maintainer of this repo

please reach out to
@vedant-jain03 @Prerna-0202

**Comment by MauryanKansara** [comment]
@Prerna-0202 @vedant-jain03 can I work on this issue?

**Comment by aashimawadhwa** [comment]
@MauryanKansara  this issue is already raised #3252  and the PR for this is under review!

**Comment by thejaysharma** [comment]
hey @aashimawadhwa, If this issue is still open , can you assign it to me?

**Comment by Prerna-0202** [comment]
[completed](https://github.com/CircuitVerse/CircuitVerse/pull/3360)
