### ISSUE TITLE
Pagination is not in the center of the page

### ISSUE THREAD

**Issue by MauryanKansara** [CircuitVerse/CircuitVerse#3469]
pagination section should be in middle of the page instead being in the left side. 

1. Go to the [circuitverse](https://circuitverse.org/)
2. Search for a project or user
3. Scroll down to the end of the page
4. The pagination section is in the left side.
![CircuitVerse - Digital Circuit Simulator - Brave 1_4_2023 9_35_23 PM](https://user-images.githubusercontent.com/86093112/210600194-bf1544e4-6e00-4c12-942c-6a9424ef78c3.png)

**Expected behavior**
The pagination section should be in the middle something like this:-
![CircuitVerse - Digital Circuit Simulator - Brave 1_4_2023 9_35_12 PM](https://user-images.githubusercontent.com/86093112/210600221-d32f0309-8235-44e6-809f-2c7f2c16a42d.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by cherish2003** [comment]
@vedant-jain03  Can assign me this issue i would love to work on it

**Comment by GavinDmello97** [comment]
@vedant-jain03 Can this issue be assigned to me? I believe I have identified the issue origin and can write a patch for it on a new pull request as soon as this issue is assigned to me.

**Comment by shauryag2002** [comment]
Hi @tanmoysrt @vedant-jain03 @Prerna-0202 , Can i work on this issue?

**Comment by Prerna-0202** [comment]
> Hi @tanmoysrt @vedant-jain03 @Prerna-0202 , Can i work on this issue?

Go ahead @shauryag2002

**Comment by shauryag2002** [comment]
> > Hi @tanmoysrt @vedant-jain03 @Prerna-0202 , Can i work on this issue?
> 
> Go ahead @shauryag2002

Could you please assign this issue so that I can access it directly in my issues tab?
