### ISSUE TITLE
search item is not in a line with respect to each other

### ISSUE THREAD

**Issue by weberankit** [CircuitVerse/CircuitVerse#3479]
**Describe the bug**
search item is not in a line with respect to each other.

**To Reproduce**
1. Go to the https://circuitverse.org/
2. Click on the search icon and type project
![chrome_aWeiemRsMQ](https://user-images.githubusercontent.com/94105514/211288469-4961d9cc-0160-4450-8e8d-7c03a3880301.png)
3. you will see an error
![bug-1](https://user-images.githubusercontent.com/94105514/211288933-dec28cba-9698-4413-ac1a-c166c9518214.png)

**Expected behavior**
it should be in perfect line with respect to each other
![bug-fixed](https://user-images.githubusercontent.com/94105514/211288766-f619eab3-9e8d-43dc-b19c-42932ebf86de.png)

**Are you working on this issue? (Yes/No)**
yes

**Comment by weberankit** [comment]
I'm working on this issue

**Comment by weberankit** [comment]
Plz check PR #3480, review the code and merge it

**Comment by Simer13** [comment]
were you able to fix this issue ? If not, ping me. I can help.

**Comment by weberankit** [comment]
Sorry plz assign to other My end sem exam is going on

**Comment by weberankit** [comment]
Thanks

**Comment by Simer13** [comment]
No, u misunderstood. I too want to fix this issue.

**Comment by vishwassrivastava** [comment]
hey i wanted to work on it?
@vedant-jain03

**Comment by weberankit** [comment]
I think this issue is solved 
![image](https://user-images.githubusercontent.com/94105514/216799908-85f65414-c31d-4dce-9369-681371fab16a.png)

**Comment by chiggshiggs** [comment]
I was working on this issue, but i am unable to fetch any search results in my local setup. Pls help.
