### ISSUE TITLE
Make the sidebar responsive for new fold phones

### ISSUE THREAD

**Issue by AFZL210** [CircuitVerse/CircuitVerse#3485]
**Is your feature request related to a problem? Please describe.**
the sidebar is not responsive and visible on fold phones

![](https://res.cloudinary.com/primeflix/image/upload/v1673443714/ezgif.com-gif-maker_npy4yz.gif)

**Describe the solution you'd like**
decrease the font size of sidebar a little.

**Describe alternatives you've considered**

**Additional context**

**Are you working on this? (Yes/No)**
YES

**Comment by ksba2004** [comment]
As the sidebar is not responsive on fold phones, I would make the make the Sidebar responsive using JavaScript State Manager.
Or I could make use of media query too to make the sidebar responsive.
Yes, I would like to work on this issue.
Please assign this to me.

**Comment by AshirMehmood** [comment]
The sidebar is not responsive and not visible on fold phones?
I will try to use media queries to make the sidebar responsive on fold screens, and if that will not work, I will try a new feature of CSS called containers which work better than media queries and work relative to element's behavior present in document.
Yes, I want to work on this small yet interesting challenge.

**Comment by AFZL210** [comment]
hey! the code of CircuitVerse docs is present in seperate repo you can try this -
https://github.com/CircuitVerse/CircuitVerseDocs

**Comment by ksba2004** [comment]
Thanks for the link @AFZL210, can I work on this?

**Comment by AFZL210** [comment]
im also working on this, i fail i will ping you

**Comment by ksba2004** [comment]
Sure

**Comment by AFZL210** [comment]
@ksba2004 i tried but i cannot trigger the nested list you can try i have opened the issue in docs repo

**Comment by ksba2004** [comment]
Yes, I have commented on docs repo,
Do I have to wait for until I get assigned?

**Comment by AFZL210** [comment]
@ksba2004 I'm also new, I think you should create a new branch with the issue number and try creating a PR if everything works fine

**Comment by AshirMehmood** [comment]
Kindly assign me

**Comment by Prerna-0202** [comment]
Hey @AFZL210, This issue belongs to the CircuitVerseDocs repo. You can open it [here](https://github.com/CircuitVerse/CircuitVerseDocs).
