### ISSUE TITLE
Output Disconnects on changing the Width of subCircuit.

### ISSUE THREAD

**Issue by NavonilDas** [CircuitVerse/CircuitVerse#349]
**Describe the bug**
When we change the width of the subCircuit from layout mode and switch back to the circuit the output nodes are disconnected.

**To Reproduce**

![demo](https://user-images.githubusercontent.com/29132316/55524571-7000ae80-56ab-11e9-8482-7c4b787fb10f.gif)

**Expected behavior**
Output Should remain connected.

**Are you working on this issue? (Yes/No)**
Yes

**Comment by satu0king** [comment]
This is actually intended behavior. Users are not supposed to change the width often. And if they do, there is no well-defined way to handle it, so the simple solution is to break the circuit and let the user redraw the wires again. Interested to see your approach.
