### ISSUE TITLE
[ui] : fix alignment of elements in a comment

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3493]
**Describe the bug**
When the user comment on a project, a container elements look un-aligned. 

![Screenshot from 2023-01-18 19-53-46](https://user-images.githubusercontent.com/76901313/213196480-1d544e8e-a29f-4e48-bf4b-df976c6e3607.png)

**Expected behavior**
The elements should be aligned properly!
Elements includes:
- edit button
- delete button
- upvote/downvote button

These elements should be shifted rightmost to the container.

**Device Information [optional]:**

**Are you working on this issue? (Yes/No)**
No

**Comment by disha1202** [comment]
Hi, I would like to work on this

**Comment by vedant-jain03** [comment]
Sure, @disha1202 Go ahead!

**Comment by MohdSaad** [comment]
hey I would like to work on this ..

**Comment by azr-arch** [comment]
i would like to work on this

**Comment by vishwassrivastava** [comment]
Hey I would like to work on it?
