### ISSUE TITLE
[ui] : revamp comment input

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3494]
**Describe the bug**
- Comment input box is small to type more than one line comment.
- We need to make the input standardise with circuitverse inputs, refer `search` input.

![Screenshot from 2023-01-18 20-04-47](https://user-images.githubusercontent.com/76901313/213199742-8a8afaf5-aa1b-40a1-9a1b-301133eb2a83.png)

**Expected behavior**
Better experience to user while writing comment!

**Device Information [optional]:**
 - Browser [chrome, safari, mozilla]

**Additional context**
- If you are tweaking the UI, share the UI in the `UX` channel of our slack before raising a PR.

**Are you working on this issue? (Yes/No)**
No

**Comment by Sauvic016** [comment]
Hi I would like to work on it, could you please assign it to me.

**Comment by Sauvic016** [comment]
Hi just want to know is this good 
![image](https://user-images.githubusercontent.com/72251657/213245584-8e1ee1a0-c2a4-45ca-87d3-1d2826358f44.png)

**Comment by anushayerram2025** [comment]
I would like to work on this. Can you please assign it to me.

**Comment by gaurav5154** [comment]
Hi I would also like to work on it, could you please assign it to me.

**Comment by Malavi1** [comment]
I really interested work on this could you please assign me? I have a great idea on giving good user search experience 
Thankyou !!

**Comment by vishwassrivastava** [comment]
Is anyone working on it?If not @vedant-jain03 please assign it to me

**Comment by Malavi1** [comment]
If someone not working  I really want to do this!! Could you please assign me!

**Comment by Sauvic016** [comment]
Hi , There is a pull request associated with this issue. you can checkout other issues.. @Malavi1

**Comment by Malavi1** [comment]
OK I will

**Comment by Rajat2213** [comment]
Hi I would like to work on it. If nobody is working on it. @vedant-jain03 Can you assign me this. I have send demo to the slack #ux channel. Kindly check it
