### ISSUE TITLE
Multiple access for projects

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#35]
Should CircuitVerse provide a way for multiple people to edit the same circuit?

If yes, how should we implement it. Real time editing like google docs is not feasible. One way is to allow users to independently open the circuits and independently save. That is the responsibility of saving correctly and avoiding clashes is on the users.

**Comment by blane1257** [comment]
Yes, there should be. Maybe a way to "request edit" or use a randomly generated key

**Comment by HypheX** [comment]
Yes, and it would be awesome if we could get near-live feedback (if possible)

**Comment by satu0king** [comment]
@blane1257 @HypheX could you check if this is as per expectations.
