### ISSUE TITLE
Update CircuitVerse Github org logo

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerse#350]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The latest favicon suggestions or the circuitverse logo can be used. Letting them remain the default way is not too exciting to look at.

**Describe alternatives you've considered**
No alternative.

**Additional context**
Null.

**Are you working on this? (Yes/No)**
No

**Comment by yashjaiswal1** [comment]
Hi! I'd like to help. Does this image meet the requirements?
![Circuit_verse](https://user-images.githubusercontent.com/46043241/59166990-85cb9d80-8b4c-11e9-8a50-249c7c7e9f66.png)
