### ISSUE TITLE
yarn tests for simulator are failing

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#3507]
**Describe the bug**
yarn tests are failing due to canvas node modules

**To Reproduce**
1. Go to Terminal.'
2. Run 'yarn run test'
3.  See the error

**Expected behavior**
The Canvas node module needs to update for passing all the tests.

**Screenshots**
![Screenshot (1031)](https://user-images.githubusercontent.com/89515816/213903129-864368d9-f4e5-495f-93f5-a7189b4974b2.png)

**Device Information [optional]:**
 - OS: Windows 10
 - Browser: Brave, Chrome

**Additional context**

**Are you working on this issue? 
  (Yes)

**Comment by Prerna-0202** [comment]
cc:- @pulkit-30 @gr455

**Comment by pulkit-30** [comment]
Tests are passing on my system, may be problem on windows,
also, we need to upgrade some dependencies.

**Comment by tachyons** [comment]
What is the nodejs version you are using?

**Comment by Prerna-0202** [comment]
> What is the nodejs version you are using?

v16.13.0.


On Local Setup:-
`yarn`
![Screenshot (1037)](https://user-images.githubusercontent.com/89515816/214074997-0a8ae644-d603-4aa9-bb02-38f47b9e72e5.png)

On gitpod:-
`yarn run test`
![Screenshot (1031)](https://user-images.githubusercontent.com/89515816/213903129-864368d9-f4e5-495f-93f5-a7189b4974b2.png)
