### ISSUE TITLE
Navigation bar Covering lot of space

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#3509]
**Describe the bug**

The Navigation bar is a bit large vertically for the content of the web page

![pre](https://user-images.githubusercontent.com/91966855/213905762-0d0df608-d40a-4c88-87c0-6166e0197eb1.png)

**To Reproduce**
1. Go to 'circuitverse.org'
2. Scroll to check the vertical space of the navigation bar
3. See a large area is being covered by the navigation bar

**Expected behavior**
Less Area is occupied by the navigation bar which will be resulting in the content being more visible

**Screenshots**

![im](https://user-images.githubusercontent.com/91966855/213905724-968adb94-d8cb-485d-b9d9-d75378f84309.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shinchan3102** [comment]
if it is not done can i work on it?

**Comment by vedant-jain03** [comment]
@niladrix719 Thanks for the issue.
Navbar UI revamp is under progress and is covering this point as well. Have a look at https://github.com/CircuitVerse/CircuitVerse/pull/3425
