### ISSUE TITLE
login page social icons are too much close

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#3514]
**Describe the bug**

The social icons on the Login page are way too close to each other

![Screenshot from 2023-01-22 21-58-02](https://user-images.githubusercontent.com/91966855/213927342-8fb6c29c-5b91-4691-a46d-3f1beabb45ee.png)

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'login on the navigation bar'
3. Scroll down to 'login with social section below the form'
4. the social icons are too close

**Expected behavior**
there should be some distance between the icons

**Screenshots**

![Screenshot from 2023-01-22 22-01-25](https://user-images.githubusercontent.com/91966855/213927622-a02aef80-fd54-4594-a937-410c3da37b2b.png)

**Are you working on this issue? (Yes/No)**
yes

**Comment by Shinchan3102** [comment]
can i work on this issue?

**Comment by vedant-jain03** [comment]
@niladrix719 Thanks for the issue, 
But the initial design is more suitable!

Some good practice:
- Kindly have an approval or descussion in `#community` in slack before opening an issue and PR.

**Comment by niladrix719** [comment]
@vedant-jain03 yeah sure
