### ISSUE TITLE
[ui] : revamp the announcement form UI.

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3524]
**Is your feature request related to a problem? Please describe.**
We need to improve the UI for announcement page. 
| ![Screenshot from 2023-01-25 16-52-08](https://user-images.githubusercontent.com/76901313/214550843-db8c763e-99d7-4449-bcd7-ba415f58a9b2.png) |
|-|
|Announcement Page|

**Describe the solution you'd like**
Suggest a design and before raising a PR, kindly post the UI in `#ux` channel in slack so that we can provide feedback. 

**Additional context**
The annoucement page requires `admin` access, if you want to reproduce the bug you can remove [this](https://github.com/CircuitVerse/CircuitVerse/blob/32b382f1b0caf2a214d8a573078d19502d1a8ead/app/controllers/announcements_controller.rb#L5) line. Remember to not to add this in commit.

**Are you working on this? (Yes/No)**
No

**Comment by niladrix719** [comment]
@vedant-jain03 can i work on this?

**Comment by niladrix719** [comment]
@vedant-jain03 can i work on this?

**Comment by himeshparashar** [comment]
Hi I would like to work on this, could you please assign it to me.

**Comment by vedant-jain03** [comment]
@niladrix719 Go Ahead!

**Comment by Sheikh-JamirAlam** [comment]
@vedant-jain03 Can you tell me how to setup this repo on my local machine?

**Comment by vishwassrivastava** [comment]
Hi I would like to work on it. Is @niladrix719 working on it? @vedant-jain03

**Comment by niladrix719** [comment]
@vishwassrivastava yes

**Comment by niladrix719** [comment]
@vedant-jain03 i have posted some updates on the issue in slack #ux channel

**Comment by vedant-jain03** [comment]
> @vedant-jain03 I have posted some updates on the issue in the slack #ux channel

Will look into it and let you know!

**Comment by Malavi1** [comment]
Hey @Sheikh-JamirAlam DO try this run command -->`docker-compose up` on the terminal that your curser  is pooping right now
Hope this helpful

**Comment by Gauravjadhav22** [comment]
Hi I would like to work on this, could you please assign it to me.

**Comment by sakshii2000** [comment]
Hi is anyone assigned to this issue and is working on it? I tried adding a new announcement to see how it works. 

![image](https://user-images.githubusercontent.com/88350866/218389021-ae4cad41-883c-4f91-8846-2d2f7f7367f4.png)

Can i work on it?

**Comment by niladrix719** [comment]
> Hi is anyone assigned to this issue and is working on it? I tried adding a new announcement to see how it works.
> 
> ![image](https://user-images.githubusercontent.com/88350866/218389021-ae4cad41-883c-4f91-8846-2d2f7f7367f4.png)
> 
> Can i work on it?

it's already done

**Comment by pavanjoshi914** [comment]
@niladrix719 can you link the pr here so that i can check

**Comment by niladrix719** [comment]
@pavanjoshi914 linked the pr , please check

**Comment by niladrix719** [comment]
@pavanjoshi914 all set please have a look
