### ISSUE TITLE
Change the color of Circuit Verse logo in navbar of simulator to match the theme

### ISSUE THREAD

**Issue by vedant-z** [CircuitVerse/CircuitVerse#3528]
**Is your feature request related to a problem? Please describe.**
It would be better if we update the color of CircuitVerse logo to other color like Green to match the theme.

**Describe the solution you'd like**
Change the color to green

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/93431609/214944049-e4e9dd79-0112-4e85-9576-9dd787b0d51b.png)

**Are you working on this? (Yes/No)**

I am willing to work on this if confirmed

**Comment by vedant-jain03** [comment]
@vedant-z the white logo is used intentionally to make the UI standardize, if you see every text in the navbar/toolbar is of color white!

Thanks for suggesting!
