### ISSUE TITLE
Integrate story-book for previewing componets

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3537]
We have a few [view components](https://viewcomponent.org/) defined in our application. But we don't have any place to preview those components. We can use https://jonspalmer.github.io/view_component-storybook/ to achieve this.

**Comment by disha1202** [comment]
Hi, I would like to work on this.

**Comment by niladrix719** [comment]
can i work on this?

**Comment by bsarthak16** [comment]
hi i would like to work on this

**Comment by ShivangMishra** [comment]
I'm working on it... @tachyons

**Comment by tachyons** [comment]
This issue is already taken by @disha1202

**Comment by ShivangMishra** [comment]
If I'm not wrong the error is related to incorrect stories path in main.js. 
  You have added **stories: ["../test/components/**/*.stories.json"],**   but there's no such folder. I think it should be app/component instead of test/components because that's the only similar folder I can see. @tachyons any other folder where we should configure storybook to search for stories ?

**Comment by disha1202** [comment]
> If I'm not wrong the error is related to incorrect stories path in main.js. You have added **stories: ["../test/components/**/*.stories.json"],** but there's no such folder. I think it should be app/component instead of test/components because that's the only similar folder I can see. @tachyons any other folder where we should configure storybook to search for stories ?

As per the documentation [https://jonspalmer.github.io/view_component-storybook/](https://jonspalmer.github.io/view_component-storybook/)
I have created a test/components folder.

**Comment by ShivangMishra** [comment]
@disha1202 but still there are no stories in that folder, so two options - change the path as I said earlier, or add stories in the folder you created. The first option would be preferred imo, but you should discuss that with an active contributor or maintainer here.

**Comment by disha1202** [comment]
> @disha1202 but still there are no stories in that folder, so two options - change the path as I said earlier, or add stories in the folder you created. The first option would be preferred imo, but you should discuss that with an active contributor or maintainer here.

There is a story inside test/components https://github.com/CircuitVerse/CircuitVerse/pull/3575/files#diff-3633b80c57d565a95b498dfac42b17c68be34c3902ad1f206b3dbe46adc51bf2R1

**Comment by tachyons** [comment]
@ShivangMishra I suggest you to pair with @disha1202 to resolve the issue

**Comment by B1TSH3LL** [comment]
i would like to wor on this issue please assign this to me.

**Comment by Aryan-Mishra24** [comment]
i'd love to work on this issue or help and collaborate with whoever is working on it

**Comment by shubham-shinde-442** [comment]
I would like to work on this issue, Could you assign me?

**Comment by fillingtothemomo** [comment]
i would like to work on this issue, can u please assign to me

**Comment by nisha-laur** [comment]
Hi @tachyons , I want to resolve this issue ,please assign it to me .
