### ISSUE TITLE
The title area in testbench page needs to be redesigned.

### ISSUE THREAD

**Issue by MauryanKansara** [CircuitVerse/CircuitVerse#3539]
**Describe the bug**
Currently the title area of  [testbench](https://circuitverse.org/testbench?scopeID=5869640273&popUp=true) page looks something like this:-

![Screenshot (18)](https://user-images.githubusercontent.com/86093112/216813344-1dff5c6e-7507-4e8f-b5b6-3c4df872f508.png)

This design is default and not so user friendly. 
I have come up with a good design which looks something like this:-

![Screenshot (22)](https://user-images.githubusercontent.com/86093112/216813393-71de022e-6ce6-45aa-8211-88d2cba51308.png)

This will also improve the user experience.

Are you working on this issue? (Yes/No)
Yes.

**Comment by vedant-jain03** [comment]
@MauryanKansara thanks for suggetion, we high appreciate if you share your designs ideas in `#ux` in slack, so that only after final designs you can work on it!

GitHub issue discussion is not the way we appreciate for design discussion!

**Comment by MauryanKansara** [comment]
@vedant-jain03 I already have sent message in #UX channel and have tagged you. Can you please check that out?
