### ISSUE TITLE
navbar links alignment

### ISSUE THREAD

**Issue by weberankit** [CircuitVerse/CircuitVerse#3540]
**Describe the bug**
On small devices, navbar links should be in middle aligned 

**To Reproduce**
1. Go to https://circuitverse.org/
2. go to the developer tools and click on inspect(adjust on small size device ex-599px)
3. click on the navbar icon 
4. you will see all nav links are not in the middle of the page

**Expected behavior**
it should be in the middle of the page

**Screenshots**

issue---

![image](https://user-images.githubusercontent.com/94105514/216828393-d3cb94d5-62a2-447c-9983-22062e5cdeca.png)

**Device Information [optional]:**

**Additional context**

**Are you working on this issue? (Yes/No)**

**Comment by weberankit** [comment]
I'm working on this issue could you plz assign it to me

**Comment by weberankit** [comment]
gitpod.io/#https://circuitvers-circuitvers-5ouvcrsyy3l.ws-us85.gitpod.io/?workspace=file%3A%2F%2F%2FCircuitVerse.code-workspace

**Comment by Shantanusharnagat** [comment]
DO you want to align getting started, teachers , blogs in the middle?

**Comment by weberankit** [comment]
yes, I think it will look best

**Comment by vedant-jain03** [comment]
@weberankit thanks for opening the issue but making the elements center will not be appropriate designs, as you can see the text length of elements are different and not standard, a standard way is to align it and that is why we have kept it aligned to left. If you do have a design, feel free to share the designs in `#ux` channel in slack. 

Closing this....

**Comment by weberankit** [comment]
Okay 
Thanks
