### ISSUE TITLE
Convert issue template to issue form

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3542]
Our current issue template is not efficient enough. Using an issue form will make the process a little better. 
Ref: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms

**Comment by niladrix719** [comment]
can i work on this?

**Comment by vedant-jain03** [comment]
@niladrix719 Go Ahead

**Comment by tachyons** [comment]
Sorry for not stating in advance, good-first-issue 's are for first contributors only.

**Comment by chiggshiggs** [comment]
Is this issue still open?

**Comment by Mayank1170** [comment]
Hey!! 
Can you please assign this issue to me i wanna work on it...
