### ISSUE TITLE
[ui] : align text in contribute page

### ISSUE THREAD

**Issue by vedant-jain03** [CircuitVerse/CircuitVerse#3551]
### Describe the bug

| ![Screenshot from 2023-02-10 09-54-09](https://user-images.githubusercontent.com/76901313/218001839-dc39a26d-d1a0-4e64-955d-dc029a6b6dc4.png) | ![Screenshot from 2023-02-10 10-08-47](https://user-images.githubusercontent.com/76901313/218002085-4e9eb8a4-cf59-481b-aec1-012659088ce7.png) |
|-|-|
|Before|After|

Reference: https://circuitverse.org/about

### Steps To Reproduce

1. Go to https://circuitverse.org/contribute
2. see the error

### Additional context

This issue is for first-time contributor

### Are you working on this issue?

No

**Comment by aryanvarma7272** [comment]
Hey @vedant-jain03 , I have solved this issue and sent the PR . 
Kindly Approve my PR .
Thank you.

**Comment by Rajat2213** [comment]
@aryanvarma7272 dude i already solved this issue and you did same copy of mine. This is not correct.

**Comment by aryanvarma7272** [comment]
@Rajat2213 , I overlooked it , was not knowing that you have solved the issue. kindly mind your language, there is no such thing of copying from you , single line of code even class 4th std student would solve it 
Happy & Peace Contributing : )

**Comment by Rajat2213** [comment]
@aryanvarma7272 I'm just asking it's not like that. ok so the issue is resolve. Most Important thing

**Comment by Rajat2213** [comment]
@aryanvarma7272 I have already solved this issue before. Thanks for contributing. You can take your pr back otherwise there will be merge conflict

**Comment by vedant-jain03** [comment]
@aryanvarma7272 @Rajat2213 There is nothing to argue about. 
According to [guidelines](https://github.com/CircuitVerse/CircuitVerse/blob/master/CONTRIBUTING.md) you must get the issue assigned or approved by core-team and then only your PRs or contributions would be entertained.

We are here to build and grow, I understand you want to show your capabilities by your contributions!

As the log says you both created the PR before getting assigned. Holding this issue as of now....

Keep building and thanks for your interest in this issue!

**Comment by Rajat2213** [comment]
@vedant-jain03  Ohk I didn't know about that first to get assigned before contributing. Thanks for guiding me in right path.
