### ISSUE TITLE
alert text not correctly aligned

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

alert text is not correctly aligned and has uneven padding.

### Steps To Reproduce

steps to reproduce:
1. go to circuitverse.org and signup or login 
2. on successful signup or login a alert text pops up with the success 
3. check the text 

alternatively:
1. try making a new group or editing existing one
2. alert text pops up check it.

### Expected Behavior

expected:
the items in the alert should be aligned correctly
![Screenshot_20230211_123420](https://user-images.githubusercontent.com/96580571/218245471-e82ff191-68ca-422d-8b68-c8ad93bbe42f.png)
or,
![Screenshot_20230211_123359](https://user-images.githubusercontent.com/96580571/218245479-dac69556-ba3a-405c-8646-3a1ddb55c084.png)

### Screenshots

what is shown:
![Screenshot_20230209_095954](https://user-images.githubusercontent.com/96580571/218245411-1e02d1e7-193c-41a9-9d80-61b211c638a8.png)
or,
![Screenshot_20230209_100634](https://user-images.githubusercontent.com/96580571/218245371-175bb180-db11-4356-8413-45e452947536.png)

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser: Chrome, Firefox both
- version: web
```

### Are you working on this issue?

Yes

**Comment by vedant-jain03** [comment]
cc @nitin10s

**Comment by cherish2003** [comment]
@Arnabdaz  can you assign me this issue i would love to work on it

**Comment by cherish2003** [comment]
@vedant-jain03  is this issue still open if it is open can you please assign me

**Comment by Arnabdaz** [comment]
> @Arnabdaz can you assign me this issue i would love to work on it

sorry friend I have fixed the issue and opened a pr already ... please feel free to try any other issue
