### ISSUE TITLE
🐞 Comment text is not spaced correctly 

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3558]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Multi-line comment is having too much line spacing.

### Steps To Reproduce

1. Go to any circuit details page 
2. in the comment section add new comment with each line broken with a enter 
3. submit the comment and check

### Expected Behavior

![image](https://user-images.githubusercontent.com/96580571/218314539-47e66819-f023-43dd-9ef4-efe0d80f6477.png)

### but what actually is happening:

![image](https://user-images.githubusercontent.com/96580571/218314565-acb318ea-aed8-4d92-af66-ddb5ec537881.png)

### Device Information [optional]

```markdown
- OS: windows 
- Browser: chrome , firefox
- version: web
```

### Are you working on this issue?

Yes

**Comment by Inkster6868** [comment]
hey is the issue resolved? if not, please assign it to me. this shouldn't take more than a day to solve! Thanks.
