### ISSUE TITLE
🐞 Error Message's text isn't aligned properly in Sign Up page 

### ISSUE THREAD

**Issue by MauryanKansara** [CircuitVerse/CircuitVerse#3560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The error message text in Sign Up page is not aligned in center vertically.

![Screenshot (30)](https://user-images.githubusercontent.com/86093112/218316957-9e6a627f-e0e3-4cb7-849c-c8a810c60c74.png)

### Steps To Reproduce

1. Go to the Sign Up Page.
2. Enter any invalid information like wrong/blank email, short/blank password, blank username, etc.
3. Click on Sign Up button.
4. An error message will be displayed with red text and pinkish background.

### Expected Behavior

Error Message's text should be aligned properly. Just like shown in SS:-

![Screenshot (31)](https://user-images.githubusercontent.com/86093112/218317162-d01ee311-9593-40b2-a504-0af9e91840f9.png)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by cherish2003** [comment]
@vedant-jain03  can you assign me this issue i would  love to work on this

**Comment by shauryag2002** [comment]
Hi @tanmoysrt @vedant-jain03 @Prerna-0202 , Can i work on this ?
### Screenshot of Bug :
![CV-issue-error-message-ul-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/dd304136-11eb-499d-b8c2-5f627f70e964)


### Screenshot of Solution :

![CV-issue-error-message-ul-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/a88d677b-32ec-445c-ad1b-3a19d8a4d93e)
