### ISSUE TITLE
Allow to import/export circuits

### ISSUE THREAD

**Issue by creack** [CircuitVerse/CircuitVerse#357]
**Is your feature request related to a problem? Please describe.**

To use the tool in a serious context, we can't just trust that the website & sponsor will be there forever. In order to consider the tool, we need to be able to export the work.
- Trust
- Outages
- Discontinuation of the project / sponsors
- Moving the circuit between local instance for dev and live one.
- Work around limitations of the tools by exporting / editing / re-importing. (i.e. preprogramming eeprom)

**Describe the solution you'd like**

A button in the menu to export the circuit in any format (text format like json / yaml would be nice, but could be anything) as well as a button to import.

**Describe alternatives you've considered**

The alternative is to use Logisim, but it is not ideal.

**Are you working on this? (Yes/No)**

No.

**Comment by fpintos** [comment]
+1 on this.

In the meantime, a workaround for this is to select and copy the circuit.
This puts the corresponding JSON data in the clipboard, which one can then save anywhere.
Then one can paste that data back into CircuitVerse to regenerate the circuit.

**Comment by creack** [comment]
I didn't realize we could copy/paste outside as JSON :). That do the trick for now, but a "full blown" import/export would still be nice.

In the same topic, having some kind of version control would be great. Maybe even a sync with github with the raw json file in a repo.

**Comment by Kartikay304** [comment]
I would like to work on this issue.
