### ISSUE TITLE
Missing a colon in the timezone

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#3571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the details of assignment we mentioned dead line in that we also stated the time of the in the form of IST which is GMT+0530 (India Standard Time)
because of missing of colon there is some in convenience while reading.

![time edit](https://user-images.githubusercontent.com/112646623/219065018-adda4864-6d33-4309-84e5-194a479a442d.png)

### Steps To Reproduce

 First create a group on your own, design an assignment
Go to ->My Groups
Click on ->The project you create, and click on the view option
scroll down -> Click on the view option of assignments
see error
 

### Expected Behavior

I want to add the colon in the time zone of IST GMT+05:30 (India Standard Time) like this

### Device Information [optional]

```markdown
- OS: windows 11
- Browser: fire fox
- version:109.0.1
```

### Are you working on this issue?

Yes

**Comment by cherish2003** [comment]
@Malavi1 can you assign me this issue i would to work on this

**Comment by Malavi1** [comment]
So sorry, I am looking to start working on this after approval from the maintainers !

**Comment by Pramod-Aswani1012** [comment]
I would like to work on this issue can you assign me ?

**Comment by The-MysticOp** [comment]
Sir , i would love to work on this good first issue , can i get the task

**Comment by sivangbagri** [comment]
@Malavi1 I want to work on this issue, please assign me this issue

**Comment by Malavi1** [comment]
Thank you for your interest but this issue was not approved by the maintainers!!

**Comment by DhairyaMajmudar** [comment]
@Malavi1 shall I take this up if @tanmoysrt approves this issue?

**Comment by Malavi1** [comment]
Hi, @DhairyaMajmudar that is not at all a bug, that's the default time zone format we can't edit that. Initially I too thought it as a bug.
