### ISSUE TITLE
Update esbuild to latest version

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3573]
The latest version of esbuild changed the configuration format and that broke the [dependabot PR](https://github.com/CircuitVerse/CircuitVerse/pull/3565). This can be fixed by changing the esbuild.config.js file

**Comment by turingAlan** [comment]
Hi, I will work on it.

**Comment by rohithreddy009** [comment]
Hi, I could fix this. Can you assign this issue
