### ISSUE TITLE
Enlarge comment text-area on enter

### ISSUE THREAD

**Issue by Waishnav** [CircuitVerse/CircuitVerse#3578]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

When attempting to submit a new comment in the comments section, pressing the enter key causes a new line to be created instead of posting the comment. If this is the intended user experience, it may be helpful to enlarge the `textarea` box of that comment so that the user can easily distinguish between creating a new line and submitting a comment.

### Steps To Reproduce

1. Go to any simulator page. For example go [here](https://circuitverse.org/users/151831/projects/tic-tac-toe-simulator-aa4c2a28-661a-4b4a-8927-2ac5dae20fb0)
2. Write a comment.
3. Hit `Enter key`

### Expected Behavior

On hitting `Enter key`, size of textarea should increase. so that user can see all the new lines with previous lines.

### Screenshots

You can play the following video to understand the issue.
Video can be found [here](https://cdn.discordapp.com/attachments/846673043329777666/1076112898948083732/Screencast_2023-02-17_120746.mp4)

### Are you working on this issue?

No

**Comment by Sheikh-JamirAlam** [comment]
Can I work on this issue if no one is working on this?

**Comment by Waishnav** [comment]
Hey @Sheikh-JamirAlam. Welcome to the CircuitVerse community. you can start working on this issue. If you need any help ping me.

**Comment by Arnabdaz** [comment]
@Waishnav I belive this issue is already taken care on #3521

**Comment by Waishnav** [comment]
> @Waishnav I belive this issue is already taken care on #3521

thanks for letting me know. I was not aware about this PR.

**Comment by Waishnav** [comment]
@Arnabdaz We were thinking about custom size of comment box on adding new line by hitting enter. (basically adding event listner to the textarea and increasing the row number)

**Comment by Waishnav** [comment]
@Arnabdaz We were thinking about custom size of comment box on adding new line by hitting enter. (basically adding event listner to the textarea and increasing the row number)

**Comment by Waishnav** [comment]
@tachyons WDYT?

**Comment by Arnabdaz** [comment]
@Waishnav well for that I already added that feature while trying to fix the issue i mentioned earlier but as it was assigned to someone I didn't make a pr .. I asked about the feature and the updates  I made in #ux channel on slack but no one replied ... so yah if you would like I can discuss about it.

**Comment by shauryag2002** [comment]
Can I work on this issue if no one is working on this?
