### ISSUE TITLE
Fix saas deprecation

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3579]
Running node `esbuild.config.js` displays of couple of deprecation warnings, we need to fix them 
Eg:
```
DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
```

**Comment by Arnabdaz** [comment]
@tachyons can you assign me this issue ?

**Comment by tachyons** [comment]
@Arnabdaz This is a good first issue, ideally to be taken by someone who is yet to make their first contribution to circuit verse.

**Comment by cherish2003** [comment]
@tachyons can you assign me this issue i would love to work on it

**Comment by jatinsahijwani** [comment]
i am a beginner and would love to start contributing to circuit verse. Can i work on this issue?

**Comment by Inkster6868** [comment]
hello @tachyons, I haven't contributed yet to any of the issues in the circuit verse. Please can you assign me this issue?

**Comment by Bharadwajshivam28** [comment]
@tachyons Hello I am a newcomer can you assign it to me

**Comment by Prerna-0202** [comment]
@cherish2003 are you still working on this issue?

**Comment by harshsharma-11** [comment]
@tachyons @Prerna-0202 how to produce this error i want to work on it

**Comment by Deveshch2712** [comment]
@tachyons  Where can I find the code related to this issue? I'd like to contribute. Thanks!

**Comment by Nikuunj** [comment]
I have some experience in programming languages like html , css , js , react . I am passionate about open-source and have recently participated in Hacktoberfest 2023. I am now seeking mentorship to improve my skills in open-source development. I am keen to contribute to your projects and would appreciate your guidance on how to get started.

**Comment by Nikuunj** [comment]
Hi @tachyons 

I hope this message finds you well. I'm Nikunj Makwana, and I'm reaching out because I'm interested in contributing to CircuitVerse.
Being new to the world of contributions, I'm eager to learn and would greatly appreciate your guidance on how I can get started? I have some background in HTML, css , react, js, and I'm keen to align my efforts with the current needs of the project.

**Comment by fillingtothemomo** [comment]
@Prerna-0202 I am new to open source and would like to contribute to CircuitVerse, can you please assign me this issue.

**Comment by DhairyaMajmudar** [comment]
@tachyons  there are several warnings also while running and building the vue simulator which is being removed by below PR
 
https://github.com/CircuitVerse/cv-frontend-vue/pull/214 

![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/f0a2cab5-0f06-4391-ad5b-028b3e90386d)
