### ISSUE TITLE
fix check-box tick to fit and correctly align in its container box

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

All the checkbox tick mark in the site are not correctly aligned and also get hidden some part due to overflow

![image](https://user-images.githubusercontent.com/96580571/219880996-ca8a958f-bce0-4647-b504-0c067e424ace.png)

### Steps To Reproduce

1. go to any place and find a checkbox 
2. you can find one in account details section 

### Expected Behavior

![image](https://user-images.githubusercontent.com/96580571/219880987-ba1e18e1-951e-4760-8ceb-1b771d647327.png)

### Device Information [optional]

```markdown
- OS: any
- Browser: any
- version: web
```

### Are you working on this issue?

Yes

**Comment by avezqureshi14** [comment]
Hey can i work on this issue
