### ISSUE TITLE
SubCircuit Surface LED's

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#36]
When customizing the layout of a SubCircuit, any LED's that have been placed should appear on the SubCircuit similar to inputs or outputs, but on the surface. A similar idea I just had is to do the same with buttons, allowing for a SubCircuit button panel. 
Here's a graphical representation of what I mean about the surface LED's:
![screenshot 2](https://user-images.githubusercontent.com/34515731/47725495-0c231700-dc2f-11e8-8e6b-83bc4a07a706.png)

**Comment by satu0king** [comment]
That is a great idea! The LEDs can be done right away, however, the buttons may be a tad bit trickier.

**Comment by blane1257** [comment]
Awesome! Also, the image is just a rough demonstration, I definitely would want it to look a little better than that.. particularly the non-lit LED's and the borders between them stick out way too much.

**Comment by satu0king** [comment]
Should the LEDs be circular or square?, should there be a border around the LEDs?

**Comment by blane1257** [comment]
They should be square and "pixel-like." There should be a border, but a fainter one than in the image.

**Comment by SubhajitCode** [comment]
hi I implemented this feature and creating a pull request to check them out .. please notify me if you find any bugs....
I really need some  one who knows inside out of this project as mentor 
ps.. those  leds are circular now but will change them to rectangular later ...

**Comment by blane1257** [comment]
Hey @SubhajitCode, this issue is a bit outdated, it's reiterated in #48, go there instead. I'll close this issue, actually.

**Comment by SubhajitCode** [comment]
here is the pull req 
https://github.com/CircuitVerse/CircuitVerse/pull/210
