### ISSUE TITLE
CCS not loading

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#360]
**Describe the bug**
Going onto the CircuitVerse home page displays a broken web page, with no CSS loading. I originally thought this was a once off, but for the past week the same bug has occurred repeatedly. I have also tried a hard refresh, but that did not fix the issue.

![image](https://user-images.githubusercontent.com/40789662/55780474-54ead000-5aeb-11e9-890f-89f060013c6b.png)

**To Reproduce**
1. Go to https://circuitverse.org/

**Expected behavior**
The page should be properly formatted, with a visually pleasing aesthetic.

**Desktop (please complete the following information):**
 - OS: Windows 10 `1803`
 - Browser: Google Chrome `Version 73.0.3683.86 (Official Build) (64-bit)`

**Are you working on this issue? (Yes/No)**
No

**Comment by jbox144** [comment]
Further revalations: Originally this would only affect the front page, now it affects all parts of the site. Even the simulator (much sadness)

![image](https://user-images.githubusercontent.com/40789662/55781137-d0994c80-5aec-11e9-9ada-840ceff2565b.png)

**Comment by jbox144** [comment]
Further information: My developer console states the following errors when loading any pages:
```
maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css:1 Failed to load resource: net::ERR_CONNECTION_RESET
bootstrap.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
sign_in:109 Uncaught TypeError: Cannot read property 'hide' of null at sign_in:109
```

**Comment by iamNamanKhare** [comment]
@jbox144 I tested it on the following configs many times and it worked fine every time : 

- **OS** : Ubuntu Gnome 16.04 LTS  **Browser** : Firefox Quantum 67.0b5 (64-bit)

![Screenshot from 2019-04-09 19-27-55](https://user-images.githubusercontent.com/32154933/55806632-4528b700-5afe-11e9-8b68-25dac8c4bda3.png)


- **OS** : Ubuntu Gnome 16.04 LTS  **Browser** : Chromium Version 73.0.3683.75

![Screenshot from 2019-04-09 19-27-50](https://user-images.githubusercontent.com/32154933/55806645-4c4fc500-5afe-11e9-9674-6f8bcbe98c0f.png)

**Comment by puskuruk** [comment]
It must be solved. But there is still problems in JS.

![Screenshot from 2019-04-09 19-45-35](https://user-images.githubusercontent.com/22892227/55818772-157aae80-5b00-11e9-97aa-a09076c988b2.png)

**Comment by satu0king** [comment]
> maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css:1 Failed to load resource: net::ERR_CONNECTION_RESET
bootstrap.min.js:1 Failed to load resource: net::ERR_CONNECTION_RESET
sign_in:109 Uncaught TypeError: Cannot read property 'hide' of null at sign_in:109

This is exactly why previously the CSS files were in the public folder instead of serving over CDN because sometimes CDN fails!

**Comment by tachyons** [comment]
Probably your ISP is blocking CDN!!. Try different connection and retry

**Comment by satu0king** [comment]
@tachyons, This was an issue long back as well, I resolved it simply by copying all the CSS/JS files into our own public folder. Anyway cloudflare caches things for us, so it shouldn't be much slower. I understand that this is not the ideal solution but what do you say?

**Comment by tachyons** [comment]
@jbox144 Seems like you are using one adblock extension, Can you try after disabling the extension

**Comment by jbox144** [comment]
Sorry for the late reply. As it turns out, it was just my adblock blocking the CSS (don't know why, it's been pretty good so far). Whitelisting circuitverse.org and hard reloading the page (shift+reload) fixed the issue, and I can now view CircuitVerse in all it's stylesheeted glory.

Thanks @tachyons for the fix!

**Comment by mosip-guest** [comment]
@tachyons @jbox144 that is a good diagnosis but I think we cannot expect users to realize this and disable their adblock. We can leave it at this for now.
