### ISSUE TITLE
Spelling mistake in GSoC'23 Project List wiki

### ISSUE THREAD

**Issue by R4d104ct1v1ty** [CircuitVerse/CircuitVerse#3608]
There is a spelling mistake in the title of Project 4: Improve the development experiance. It should be changed to  Improve the development **experience**.

**Comment by ShatilKhan** [comment]
Hi, can you tell me where exactly this is?
@R4d104ct1v1ty

**Comment by alffy007** [comment]
I think it has been rectified.

**Comment by vedant-jain03** [comment]
@R4d104ct1v1ty Thanks for raising the issue, it has been rectified.
