### ISSUE TITLE
🐞 Bug -Alignment & Adjusting size of a Components

### ISSUE THREAD

**Issue by alffy007** [CircuitVerse/CircuitVerse#3609]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Describe the bug
when the size of the device is smaller than 320px  the alignment and size of the buttons are mismatched and needed to style the UI component for small devices.

### Steps To Reproduce

1. Go to the website.
2. Set width to below 320px
3. see the front page

### Expected Behavior

![Screenshot_20230224_134539](https://user-images.githubusercontent.com/98375473/221335263-e38f3a04-919a-4960-8eb4-dc3ba092e77c.png)

### Screenshots

as in the screenshot below:
![Screenshot_2023-02-24-13-30-38-75_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/98375473/221335040-a5c5cbfd-728b-4883-b6f0-4ea6c287d664.jpg)

### Device Information [optional]

```markdown
- OS:android
- Browser:chrome
- version:12
```

### Are you working on this issue?

Yes

**Comment by Pramod-Aswani1012** [comment]
@alffy007 I would like to work on this issue ??? can you assign it to me ??

**Comment by alffy007** [comment]
@Pramod-Aswani1012  But I already Finished this and ready for PR

**Comment by Pramod-Aswani1012** [comment]
> @Pramod-Aswani1012 But I already Finished this and ready for PR

Ohh Okay

**Comment by Rai-Nishhant** [comment]
@vedant-jain03 , Is this issue still open? Please assign this to me, I would like to work on this.

**Comment by lavi20** [comment]
I want to work on this issue please assign this to me
