### ISSUE TITLE
[ui]: replace svg with user avatar

### ISSUE THREAD

**Issue by VaibhavUpreti** [CircuitVerse/CircuitVerse#3622]
### Is your feature request related to a problem? Please describe

This feature is meant to increase the usage of the profile picture by users.

### Describe the solution you'd like

Task is to replace the svg in group and mentors list with avatar of user.

For the view for mentors and group members

![Untitled](https://user-images.githubusercontent.com/85568177/221559691-269fd319-41ea-400d-b439-5d52c42a6016.jpg)

### Describe alternatives you've considered

For discussing ui implementation or any doubts reach out via #ux channel of [slack](https://circuitverse.org/slack)

### Additional context

This feature is under the fosshack, you need to register [here](https://fossunited.org/login#login). You can join #fosshack-students channel in slack for any doubts and support

### Are you working on this?

No

**Comment by Arnabdaz** [comment]
can I work on this?

**Comment by kiransatdive** [comment]
I want to work on this issue, can assign me issue?

**Comment by krish-op151** [comment]
I would like to contribute in this, i request you to assign this issue to me @vedant-jain03
