### ISSUE TITLE
Add the helplinks for Clock and Two's Complement

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#3623]
Is your feature request related to a problem? 
The docs for Clock and Two's complement are present in the circuitVerse docs but their helplinks are not available in the simulator.

Describe the solution you'd like

Like other  Elements, we need to add the helplink for the Clock and Two's complement.
The docs for the clock and two's complement is already present in CircuitVerse docs.

Additional context
This feature is under the fosshack, you need to register [here](https://fossunited.org/login#login). You can join #fosshack-students channel in slack for any doubts and support

Are you working on this?
No

**Comment by kiransatdive** [comment]
I want to work on this issue, can assign me issue?

**Comment by vedant-jain03** [comment]
> I want to work on this issue, can assign me issue?

@kiransatdive I have assigned you issue already, you can take another issue once you have solved the initial one!

**Comment by Malavi1** [comment]
I would like to work on this issue could you please assign me!

**Comment by vedant-jain03** [comment]
@Malavi1 You can work on this!

**Comment by Malavi1** [comment]
In the registration they are asking to link the GitHub link should I need to link the URL of this issue?

**Comment by vedant-jain03** [comment]
> In the registration they are asking to link the GitHub link should I need to tie-up the URL of this issue?

No, you need to add link to your github url!

**Comment by Malavi1** [comment]
Thank you!!

**Comment by neerajbachani** [comment]
Hi there,
Not only clock and 2's compliment but also ImageAnnotation, ControlledInventor, ForceGate don't have help links and RgbledMatrix have toggle grid instead of help link.
please assign this issue to me i will work on clock and 2's compliment first and if you give permission for other these issue then only i will start:)

**Comment by vedant-jain03** [comment]
> Hi @vedant-jain03, Not only clock and 2's compliment but also ImageAnnotation, ControlledInventor, ForceGate don't have help links and RgbledMatrix have toggle grid instead of help link. please assign this issue to me i will work on clock and 2's compliment first and if you give permission for other these issue then only i will start:)

cc @Prerna-0202

**Comment by Prerna-0202** [comment]
> Hi @vedant-jain03, Not only clock and 2's compliment but also ImageAnnotation, ControlledInventor, ForceGate don't have help links and RgbledMatrix have toggle grid instead of help link. please assign this issue to me i will work on clock and 2's compliment first and if you give permission for other these issue then only i will start:)


There is no currently available documentation for ControlledInventor, ForceGate and RgbledMatrix in our Cv-docs. That's why I have opened the issues in [this](https://github.com/CircuitVerse/CircuitVerseDocs) repo. Once the documentation will be done then only we can add helplinks for these elements.
I think, Currently @Malavi1 is working on this issue.  If she is not working then you can proceed. 
@Malavi1 any updates?

**Comment by Malavi1** [comment]
I am working on this issue Prerna. I am finding where the particular code is located to append these 2 elements' hyperlinks to the rest!! Can you give me any suggestions related to this @Prerna-0202!?

**Comment by Prerna-0202** [comment]
> I am working on this issue Prerna. I am finding where the particular code is located to append these 2 elements' hyperlinks to the rest!! Can you give me any suggestions related to this @Prerna-0202!?

In,
https://github.com/CircuitVerse/CircuitVerse/blob/master/simulator/src/modules/TwoComplement.js and
https://github.com/CircuitVerse/CircuitVerse/blob/master/simulator/src/sequential/Clock.js
Also, add helplink for Image Annotation in:-
https://github.com/CircuitVerse/CircuitVerse/blob/master/simulator/src/modules/ImageAnnotation.js

**Comment by Malavi1** [comment]
![Screenshot (251)](https://user-images.githubusercontent.com/112646623/222609016-cb5122be-abee-4db6-9073-4d4d2cf40139.png)

 This means should I need to add the hyperlink to this element!?

**Comment by neerajbachani** [comment]
Two's Compliment added #8f7566d1308da901d9ec98f9ecb0cc6e7b817eea

**Comment by neerajbachani** [comment]
Two's Compliment added #3641
neerajbachani:tsc

**Comment by Malavi1** [comment]
I added the two'scomplement hyperlink also. But I made a spelling mistake @neerajbachani
