### ISSUE TITLE
ui: login page revamp

### ISSUE THREAD

**Issue by Waishnav** [CircuitVerse/CircuitVerse#3634]
### Is your feature request related to a problem? Please describe

This feature is meant to increase the visibility of other log in options. Like using Google, GitHub, Facebook, etc
And improve the hirarchy structure of ui elements in login-page.

### Describe the solution you'd like

|                                          before                                          |                                         after                                          |
| :-------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| ![](https://user-images.githubusercontent.com/86405648/222409444-4c9dacec-716d-49f4-a926-5bc95010f467.png) | ![](https://user-images.githubusercontent.com/86405648/222409320-036bbe5f-0569-411d-b826-73f2f4139736.png) ![](https://user-images.githubusercontent.com/86405648/222415632-71d67013-dd47-4f6c-8993-af3b06404148.png) |

For more details visit this figma file [here](https://www.figma.com/file/btjwmO8Jq1Q4L0NcraOuT7/circuitverse-ui-updates?node-id=307%3A32&t=COylgeNXKj0GM5y9-1), And go to `login/sign-up revamp` page shown in left sidebar.

### Additional context

This feature is under the fosshack, you need to register [here](https://fossunited.org/login#login). You can join #fosshack-students channel in slack for any doubts and support

### Are you working on this?

No

**Comment by krish-op151** [comment]
can i work on this? @Waishnav

**Comment by ankit-0369** [comment]
hey @Waishnav can I work on this issue? As I am new to open source community so I think I can start contributing with this issue.

**Comment by Animesh239** [comment]
I want to work on this issue can you pls assign this to me

**Comment by ShivamKaushik316** [comment]
is this issue still open ? If yes then i would like to contribute to this issue

**Comment by Waishnav** [comment]
@neerajbachani Go ahead. You can start working on this issue.

**Comment by Waishnav** [comment]
@neerajbachani any updates?

**Comment by neerajbachani** [comment]
@Waishnav i almost update the login page as you described in figma but i don't have idea to run my code can you please tell me that how can i see my results so i can make pull request

**Comment by Waishnav** [comment]
have you not gone through the CircuitVerse [setup](https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md)?

> @Waishnav i almost update the login page as you described in figma but i don't have idea to run my code can you please tell me that how can i see my results so i can make pull request

**Comment by neerajbachani** [comment]
thnx @Waishnav soon gonna make a pull request

**Comment by SimardeepSingh1450** [comment]
@Waishnav Can I work on this issue as well ? If so please assign me this issue .

**Comment by vedant-jain03** [comment]
@neerajbachani Any updates?

**Comment by SimardeepSingh1450** [comment]
@vedant-jain03 if possible assign me this issue.

**Comment by Waishnav** [comment]
@SimardeepSingh1450 Do you want to take this issue?

**Comment by SimardeepSingh1450** [comment]
@Waishnav yes i would like to work on this

**Comment by Waishnav** [comment]
@SimardeepSingh1450 Go ahead. If need any help ping me.

**Comment by SimardeepSingh1450** [comment]
@Waishnav can you please tell me the working directory files related to this page ? I tried but unable to do so

**Comment by Waishnav** [comment]
you need to do changes in this file `/app/views/users/sessions/new.html.erb` mostly and also you can found respective scss file to add new style in the following directory `/app/assets/stylesheets`

> @Waishnav can you please tell me the working directory files related to this page ? I tried searching but I am having some problems.

**Comment by Aryan-Mishra24** [comment]
i'd love to work on this issue or help and collaborate with whoever is working on it

**Comment by SimardeepSingh1450** [comment]
![circuitverse-doubt-1](https://user-images.githubusercontent.com/92221517/233745224-fe605580-ba11-4e77-b3c6-04e1ffc07cd3.png)

@Waishnav can you please tell if there are any outer-classes to forgot-password and remember-me ? because i am having some problem writing scss for both.

**Comment by vs-mark-graham-smith** [comment]
@Waishnav @vedant-jain03 Can I work on this?

**Comment by neerajbachani** [comment]
Hi @vedant-jain03 @Waishnav I was the first one assigned to this issue, but at the time, I was busy creating my GSoC23 proposal, and all my attention was focused on that. Yesterday, I noticed that the issue was still open, so I decided to take the initiative and code it myself. I have made the changes as specified in the Figma file for the first page.

![CV_ui_revamp](https://user-images.githubusercontent.com/124370566/233914563-4badaaa4-542d-4e4f-8047-8b0b3a63304b.jpeg)

Could you assign this issue back to me? If nobody else is working on it or having trouble solving it.

**Comment by Waishnav** [comment]
@SimardeepSingh1450 are you done with the issue please let me know.

**Comment by SimardeepSingh1450** [comment]
@Waishnav currently working on frame-3 of login in figma file, will soon share a preview with you.

**Comment by SimardeepSingh1450** [comment]
![doubt-circuitverse](https://user-images.githubusercontent.com/92221517/235325431-60e620ee-0c46-4f36-9c74-acb4b7f2f848.png)
@Waishnav I am done with the first part , working on the red marked below , can you please tell how to conditionally render the red-part below ? (how to toggle show between upper email-password login and below red login links div.)

**Comment by SimardeepSingh1450** [comment]
@vedant-jain03 @Waishnav I am done with the issue, here is the pr -> https://github.com/CircuitVerse/CircuitVerse/pull/3746

**Comment by harshsharma-11** [comment]
@Waishnav is this issue still open ,if yes i am happy to work on it???????

**Comment by Karan-Palan** [comment]
I'd like to work on this issue!

**Comment by souravgope** [comment]
i want to work on this issue please assign me

**Comment by DhairyaMajmudar** [comment]
@tachyons @nitin10s If this issue is open Shall I start working on this?

**Comment by nitin10s** [comment]
The design has a lot of issues, we won't be proceeding ahead with it for the moment guys
