### ISSUE TITLE
ui: dashboard revamp 

### ISSUE THREAD

**Issue by Waishnav** [CircuitVerse/CircuitVerse#3645]
### Is your feature request related to a problem? Please describe

Right now. The UI of the dashboard is not well organized as well as we have not utilized the screen space very well.
This issue will fix by implementing the approved design by me in slack. for the figma file click [here](https://www.figma.com/file/btjwmO8Jq1Q4L0NcraOuT7/circuitverse-ui-updates?node-id=0%3A1&t=3ehFkBT06XUUByO2-1)Figma

### Describe the solution you'd like

|                                          before                                          |                                         after                                          |
| :-------------------------------------------------------------------------------------------: | :-------------------------------------------------------------------------------------------: |
| ![](https://user-images.githubusercontent.com/86405648/222878775-2c4a8aa6-e604-44ec-90af-6b20fa1a7f61.png) | ![](https://user-images.githubusercontent.com/86405648/222878770-32a5a3f3-57fb-4996-a554-0771f64e59f7.png) |

### Are you working on this?

Yes

**Comment by krish-op151** [comment]
can i work on this @Waishnav ?

**Comment by Waishnav** [comment]
> can i work on this @Waishnav ?

Hey I'm already working on this issue.
And almost done with the changes.

**Comment by krish-op151** [comment]
okay @Waishnav

**Comment by nisha-laur** [comment]
@Waishnav if this issue is still open , Can you please assign it to me ?
