### ISSUE TITLE
🐞 Bug responsiveness of simulation navbar

### ISSUE THREAD

**Issue by iks1** [CircuitVerse/CircuitVerse#3654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the behavior of the simulator when screen gets small, some parts of the navbar coincide 

![image](https://user-images.githubusercontent.com/94672267/223660469-4aebb70d-b15a-4d5c-8b97-6a2d7a755bf7.png)

### Steps To Reproduce

open simulator then make your screen small , by clicking the given menu you can see the issue

![image](https://user-images.githubusercontent.com/94672267/223661488-dec2b783-ce82-48e9-bc19-42e9d9844a6d.png)

### Expected Behavior

instead of coinciding they should be aligned properly

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by abhijain2003** [comment]
it says to switch to landscape mode in a small screen size.

and below 997 px it get convert into toggle hamburger button on navbar
is this issue already solved i think
or you want to remove that swtich to landscape alert and make it accessible for small screen users as well

**Comment by abhijain2003** [comment]
hey do you have any update on this?

**Comment by pulkit-30** [comment]
Simulator is now compatible with small screen, you can open the simulator on your smartphone and enjoy simulating circuits 😄.

I think these type of issues doesn't make any sense, no user going to open circuitVerse on browser and inspect it and change screen size to mobile(below 900px), and then going to use it.

**Comment by iks1** [comment]
@pulkit-30 ++ 🙂
