### ISSUE TITLE
Weird UI of 'change password' page 

### ISSUE THREAD

**Issue by harsha-iiiv** [CircuitVerse/CircuitVerse#367]
**Describe the bug**
UI of change password page is not matching with other layouts.

**To Reproduce**
1. Go to https://circuitverse.org/users/password/new
2. Request to change the password.
3. Open the reset link received.
 
**Screenshots**
![screenshot-circuitverse org-2019 04 14-10-15-40](https://user-images.githubusercontent.com/31560965/56088587-9c81ab00-5ea1-11e9-9aae-a6dc2a74c049.png)

**Expected**
![screenshot-circuitverse org-2019 04 14-11-30-04](https://user-images.githubusercontent.com/31560965/56088978-f46fe000-5ea8-11e9-99c3-723422761270.png)

 **Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chrome
 

 

**Are you working on this issue? (Yes/No)**
  No

**Comment by harsha-iiiv** [comment]
@satu0king

**Comment by terabo090** [comment]
Can i work on this issue?

**Comment by harsha-iiiv** [comment]
Sure, proceed @terabo090👍

**Comment by terabo090** [comment]
Thank you for your response

**Comment by Blizzard57** [comment]
Can I work on this issue?

**Comment by harsha-iiiv** [comment]
Okay @Blizzard57

**Comment by ankitkataria** [comment]
Sure, go ahead @Blizzard57 :grin:

**Comment by Blizzard57** [comment]
Thanks for the response

**Comment by Ananthavijay** [comment]
@tachyons This can be closed, Old UI
