### ISSUE TITLE
Comment input box should be in the top of comments

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3678]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when there are multiple comments in a project to add a new comment you need to navigate to the bottom of the page and post new comment by clicking the add comment test... but when there are too many comments in the comment section it is inconvinient to go to bottom to add a comment which also makes it hard for new users to navigate to the comment and add comment

### Steps To Reproduce

1. in a project go to the comment section
2. add new comment and watch 
3. the add comment box goes below the oldest comment and it keeps going down with each new comment

### Expected Behavior

the Add new comment button and comment input box should appear in the top of old comments

### Screenshots

![image](https://user-images.githubusercontent.com/96580571/225717573-43e3677e-2cf5-4559-99da-b2a81bcfbc8f.png)

### Device Information [optional]

```markdown
- OS: any
- Browser: any
- version: web
```

### Are you working on this issue?

No

**Comment by shauryag2002** [comment]
I would like to work on this issue could you please assign me!

**Comment by abhijain2003** [comment]
can I work on this

**Comment by vikaskumar2703** [comment]
can i help or get assigned on this issue. Its a simple fix

**Comment by Arnabdaz** [comment]
yah sure @vikaskumar2703 go ahead

**Comment by Arnabdaz** [comment]
@vedant-jain03 can @vikaskumar2703 be assigned the issue ?

**Comment by vikaskumar2703** [comment]
i m having issues setting up locally using docker please assign this to other interested folks

**Comment by 92Mohammad** [comment]
Hey! Could you assign me this issue.

**Comment by 92Mohammad** [comment]
thanks vedant-jain03

**Comment by 92Mohammad** [comment]
I installed latest ruby version and when I ran the command (bundle install) it is showing me that   and Gemfile depends on pg ~> 1.5.3,
  Ruby (no versions) is required.
So, because current Ruby version is = 3.2.2,

can you please help me to setup locally

**Comment by Aryan20022003** [comment]
Greeting,  
As I have already finished my part of work of previous issue #4048 , can I work on this , I guess I could solve this 
.

**Comment by Kaarti22** [comment]
Can I solve this issue plz, I want to start my open source contributions...

**Comment by Ayush-865** [comment]
I want to work on this issue. I'm a beginner contibutor in CircuitVerse but can surely solve this issue. Please assign me this issue

**Comment by connectnitesh** [comment]
Hey @Arnabdaz & @vedant-jain03  , I would like to work on this issue , can u please assign it to me?

**Comment by HarshithaPerumalla** [comment]
Hey @Arnabdaz. I have already completed setting up CircuitVerse locally. and I am new to contributing to CorcuitVerse I want to start by doing some good first issue. and this task is also suitable for begginer. Can you assign me the task.

**Comment by HarshithaPerumalla** [comment]
Hey @vedant-jain03 , Can you assign me this task

**Comment by uraj323** [comment]
Hi @vedant-jain03 , I can fix this issue can you please assign this to me

**Comment by 92Mohammad** [comment]
Hey, can we not fixes any issue without assignment

**Comment by theslowdeveloper** [comment]
@vedant-jain03 @Arnabdaz can i work on this issue, it has been idle for quite a while, here is my solution
![image](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/21707172-e5b3-44cb-9bfe-2d6bcea6dcdc)
I also have a doubt about the rendering of reply partial

**Comment by unnat-gupta** [comment]
Hi!
Can I work on this issue? I want to start my open source journey and this seems to be a perfect issue to start with.
It would be really helpful if you assign this to me.
Thanks

**Comment by jsndz** [comment]
Assign this issue to me 
This is my first issue 
I want to try it

**Comment by shauryag2002** [comment]
Hi @Arnabdaz @tanmoysrt @vedant-jain03 , Can i work on this issue ?
### Solution:
![CV-issue-add-comment-on-top](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/df96b5ba-89fe-48cf-b9de-29028eb435af)

**Comment by pratik2172003** [comment]
@Arnabdaz    can you please assign me this i will work on it .

**Comment by shrutii-pandey** [comment]
Hi @Arnabdaz and @vedant-jain03 
Will you kindly assign me this issue.
I understand that the issue needs the add new comment button and comment input box to appear above the old comments.
I am confident that I can resolve this issue.

**Comment by fillingtothemomo** [comment]
hello, @vedant-jain03 , I would like to take up this issue.

**Comment by Sahil-K123** [comment]
hii @vedant-jain03 , please assign this issue to me.
