### ISSUE TITLE
Footer Having Square Blocks In Social handles.

### ISSUE THREAD

**Issue by B1TSH3LL** [CircuitVerse/CircuitVerse#3689]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The footer area's social icon section has a solid black square border, which has a negative user interface (UI) impact. not looking good while lingering on it, either.

### Steps To Reproduce

1. Go To Footer Section.
2. Hover On Social Media Icons.

### Expected Behavior

There shouldn't be any square borders to enhance the user interface because they provide users a poor experience. no square while hovering over it as well.

### Screenshots

![image](https://user-images.githubusercontent.com/85166079/226698203-0a23e731-cae4-452f-9588-7fb09c3c8e6b.png)

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Chrome 
- version: 111.0.5563.65
```

### Are you working on this issue?

Yes

**Comment by vedant-jain03** [comment]
This issue is duplicate, and the PR for that is already under review!
