### ISSUE TITLE
Adding features for Test Bench

### ISSUE THREAD

**Issue by igaurab** [CircuitVerse/CircuitVerse#369]
**Is your feature request related to a problem? Please describe.**
There is no feature for deleting particular input or output columns in [testbench](https://circuitverse.org/testbench)`This becomes a matter of issue when we accidentally click on add inputs or add outputs. If one have written a significant amount of test cases, in such case currently there is no option but to refresh the entire page and start fresh.
**Describe the solution you'd like**
I would like to add a button "Delete Column". The user first selects the column they want to delete and click on delete column to delete the column. Or may be other way around(Please suggest)
**Additional context**
I will also work on to improve the design of the page. 

**Are you working on this? (Yes/No)**
Yes

**Comment by nrs1729** [comment]
Would it be okay to have a "-" button on each column that deletes it instead of one button at the top?
