### ISSUE TITLE
🐞 Bug: Unexpected behaviour when dragging components on Simulator

### ISSUE THREAD

**Issue by pulkit-30** [CircuitVerse/CircuitVerse#3697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Drag and Drop components on Simulator turns screen to dark. (on Safari browser)

### Steps To Reproduce

1. Open CircuitVerse/simulator on safari browser.
2. drag any element from side panel
3. see bug

### Expected Behavior

work as fine.

### Screenshots

https://user-images.githubusercontent.com/76155456/227503033-cd74258e-f025-4ce3-b2bb-23e606061f19.mov

### Device Information [optional]

```markdown
- OS: MacOs
- Browser: Safari
```

### Are you working on this issue?

No

**Comment by vinayakgoyal2022** [comment]
can i work on this issue

**Comment by Arnabdaz** [comment]
> can i work on this issue

if you have a mac or device with access to safari browser you can work on this issue

**Comment by niladrix719** [comment]
can I work on this? @Arnabdaz @Prerna-0202

**Comment by Prerna-0202** [comment]
Yes

> can I work on this? @Arnabdaz @Prerna-0202
