### ISSUE TITLE
Fork/duplicate your own project

### ISSUE THREAD

**Issue by bmwalters** [CircuitVerse/CircuitVerse#37]
## What
It would be nice if as a logged in user you could "clone" or duplicate your own project. You can currently do this with another user's project, but not your own. [simulator.io](
https://simulator.io) has this feature.

## Why
A use case for this would be keeping a base version of a circuit, such as an ALU, then cloning it before adding features.

## How
Since there's already support for forking another user's project, perhaps it wouldn't be hard to reuse that code.

An alternative solution could be having version control for projects and having a branching model

**Comment by satu0king** [comment]
Yes, this is a definite requirement. Having a version control would be overkill and confusing to most users. Branching would be similar to forking itself. However, merging like on GitHub would be extremely difficult if not impossible. 

As of now, if you need this feature immediately, simply select all the circuit elements from the main circuit and copy paste it into a new circuit, even the subcircuits get copied correctly. I use this to duplicate/backup project work.

**Comment by satu0king** [comment]
For now, duplicate can be implemented as fork itself by simply relaxing the constraint to fork oneself's circuit. 
Would this work out @bmwalters

**Comment by satu0king** [comment]
@bmwalters I have relaxed the fork feature. Could you check if it works as expected.

**Comment by bmwalters** [comment]
Great! Thanks
