### ISSUE TITLE
🐞 Bug Navbar is not aligned properly

### ISSUE THREAD

**Issue by himanshu1221** [CircuitVerse/CircuitVerse#3702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

as we scroll down navbar is not aligned to the top which it has to

### Steps To Reproduce

home screen
scroll down 
observe the nvbar navbar

### Expected Behavior

it should stick to the top

### Screenshots

![Screenshot from 2023-03-25 22-13-07](https://user-images.githubusercontent.com/32031706/227730463-837a02e0-e505-4b93-9dc0-b36001d0016d.png)
![Screenshot from 2023-03-25 22-13-02](https://user-images.githubusercontent.com/32031706/227730467-4601de55-dbe8-487a-b697-9df136cc84b3.png)

### Device Information [optional]

```markdown
- OS:UBUNTU
- Browser:CHROME
- version:111.0.5563.110
```

### Additional context

if mentainer found this issue valid i would love to work on this issue

### Are you working on this issue?

Yes

**Comment by SuyashOP-2** [comment]
I will work on this issue !!

**Comment by himanshu1221** [comment]
> I will work on this issue !!

hey @SuyashOP-2 I am willing to work on this issue waiting for a maintainer for a review if they find it well ill start working on this issue you can find other issue there are many :smile:
