### ISSUE TITLE
Setup database_consistency checker

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#3703]
https://github.com/djezzzl/database_consistency is a gem which allows static checking of potential mismatch in database schema and database models.

**Comment by SimardeepSingh1450** [comment]
@tachyons I have gone through the readme of **database_consistency checker** and was able to set it up on local-setup, please assign me this issue, so that i can make a pull request.

**Comment by tachyons** [comment]
@SimardeepSingh1450 Sure

**Comment by SimardeepSingh1450** [comment]
@tachyons created a pr at #3785 , also to run this checker there is a command which is needed to execute, can you tell me where to place that instruction ?
