### ISSUE TITLE
Navbar unwanted spacing from top

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the navbar should be sticked to the top of the site but there seems to be a unwanted space in the navbar from the top

![image](https://user-images.githubusercontent.com/96580571/227757113-61edd935-c879-4c36-85ae-d65f300192bf.png)

### Steps To Reproduce

1. open circuitverse.org
2. scroll down a bit and see the navbar issue

### Expected Behavior

there should be no gap at the top of the navbar

![image](https://user-images.githubusercontent.com/96580571/227757132-3da3dca5-637d-4ccf-a2ef-b5210f296704.png)

### Device Information [optional]

```markdown
- OS: Any
- Browser: Any
- version: web
```

### Are you working on this issue?

No

**Comment by Kartik-Maheshwari** [comment]
I have worked on this issue and created Pull Ruquest

**Comment by himanshu1221** [comment]
hey @Kartik-Maheshwari @Arnabdaz I have already stated this issue at #3702 please dont replicate the issue please check that if the issue exists or not as it creates chaos

**Comment by Arnabdaz** [comment]
@himanshu1221 sorry didn't notice it as the issue was due to a pr merge I asked tachyons in slack about the issue he asked me to open a issue and I opened one asap hope you don't mind as it was not a issue to be contributed to.

closing as fixed
