### ISSUE TITLE
Migrate from PaperClip to Active Storage

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#371]
**Is your feature request related to a problem? Please describe.**
Paperclip is [deprecated](https://thoughtbot.com/blog/closing-the-trombone)

**Describe the solution you'd like**
Follow this migration [guide](https://github.com/thoughtbot/paperclip/blob/master/MIGRATING.md)

**Are you working on this? (Yes/No)**

No

**Comment by ankitkataria** [comment]
Active storage was released with rails 5.2. Will this task also entail upgrading to rails 5.2(we currently use 5.1.6)?

**Comment by tachyons** [comment]
Made it separate issue #372

**Comment by Shivansh2407** [comment]
Can I work on this @tachyons ?

**Comment by tachyons** [comment]
No, it is already done. We are postponing the merge as it requires some manual work for deployment
