### ISSUE TITLE
404 error on clicking View previous UI under project drop down in simulator

### ISSUE THREAD

**Issue by whogurdevil** [CircuitVerse/CircuitVerse#3714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Gives 404 error when clicked on "View Previous UI" in simulator under Project drop down of navbar

### Steps To Reproduce

1. Go To 
```
https://circuitverse.org/simulator
```
2. Click on Project drop down in navbar
3.  Click on "View Previous UI"
4.  It says 
5. 404
OOPS,THE PAGE YOU ARE LOOKING FOR CAN'T BE FOUND!

### Expected Behavior

Previous UI should load when this option is choosen

### Screenshots

![Screenshot_20230403_094709](https://user-images.githubusercontent.com/106698199/229569091-b28bac53-8a57-4c2d-b573-19b88baac28d.png)
![Screenshot_20230403_065547](https://user-images.githubusercontent.com/106698199/229569178-8fe74b17-344c-41d1-ba02-42180b151bb4.png)

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser: Chrome
- version(chrome): 111.0.5563.147 (Official Build) (64-bit)
```

### Are you working on this issue?

No

**Comment by abhirajn** [comment]
can I work on this?
