### ISSUE TITLE
Missing asset error on CircuitVerse local server

### ISSUE THREAD

**Issue by 20014119-002** [CircuitVerse/CircuitVerse#3726]
I start the local server with 'rails server' command
the application starts on port:3000, the home page renders all right 
but upon launching the Simulator, it generates error that two of the assets in the asset pipeline are not present.
1. simulator.js
2. simluator.css

![Screenshot_1](https://user-images.githubusercontent.com/119746507/231796224-2ec0f6ef-d0cb-47a6-853e-5306ba17e4c5.png)

Similarly, upon opening the testbench i.e., http://localhost:3000/testbench, the same missing assets error occurs.
1. testbench.js
2. simluator.css
3. testbench.css

![image](https://user-images.githubusercontent.com/119746507/231800630-4e2047be-9edc-4d58-9f8b-457fb0696cd0.png)

**Comment by VaibhavUpreti** [comment]
Hi @20014119-002, for running the server in local development it is advised to use `bin/dev`, which will run a worker that will compile these assets regularly.

If you prefer to run the `rails server` instead, you'll need to precompile the assets first using the
 `rails assets:precompile` command. Once the assets are precompiled, you should be able to run the server without any issues.

**Comment by 20014119-002** [comment]
Thank you! @VaibhavUpreti.
Could you elaborate, how to run `bin/dev` ?

**Comment by VaibhavUpreti** [comment]
Just running `bin/dev`  instead of `rails server` in the root of the repo.

![bin](https://user-images.githubusercontent.com/85568177/232020410-465b56b8-b16c-4c24-9a2e-0886ab225c31.jpg)

**Comment by 20014119-002** [comment]
On Windows, when i run the `bin/dev`,  windows dialog box pops up asking how do you want to open this file

![Screenshot_1](https://user-images.githubusercontent.com/119746507/232032210-43862fe5-7c42-4f58-94a3-0cb4b125999b.png)

**Comment by 20014119-002** [comment]
Hitting `rails assets:precompile` generates following errors and `yarn build` also runs with errors.

[assets precompile error.txt](https://github.com/CircuitVerse/CircuitVerse/files/11232297/assets.precompile.error.txt)

**Comment by VaibhavUpreti** [comment]
1. `bin/dev` runs a bash script so it work on windows unless you are using WSL.
2. Regarding the error try running
```bash
gem install wdn
```
make sure yarn is properly configured with node version >=14 and all packages are installed. 

Detailed setup instructions are here [SETUP.md](https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md), still if gives any error feel free to reach out via [Slack](https://circuitverse.org/slack)

**Comment by 20014119-002** [comment]
1. So, the missing assets was due to using the `rails server` instead of `bin/dev`.
2. The `bin/dev` is a bash script that can only be executed in Linux or in Windows with WSL.
3. On windows, the versions of dependencies must be exactly the same as they are suggested by the [`SETUP.MD`](https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md), otherwise errors will be encountered while executing `yarn install` and `bundle install`.
4. While executing `bundle install`, if **pgadmin 1.4.5** and **redcarpet** cant be installed, make sure **MSYS2** and all the **postgresql libraries** are all properly installed.
5. Make sure your system has Ruby version 3.0.3 and Bundler gem version 2.4.1

PS. Deploying CircuitVerse locally is alot easier on any Linux distro than Windows because Linux provides Ruby package managers, Native Redis service, Easier libraries installation etc
