### ISSUE TITLE
Save Online Project Bug

### ISSUE THREAD

**Issue by theredcap** [CircuitVerse/CircuitVerse#374]
**Describe the bug**
The site automatically saves the new project although we press cancel button while the alert asks us whether we want to save the project or not
**To Reproduce**
1. Go to [Simulator](https://circuitverse.org/simulator) 
2. Draw any circuit(not necessary) click on Project/Save Online.
3. Press cancel. 
Although we press cancel we are redirected to a new page, and our project is saved.
**Expected behavior**
I don't know whether this is expected behavior or not. But the users should have a way to cancel this so that they will not have unnecessary circuits in their name.

**Desktop (please complete the following information):**
Chrome

**Are you working on this issue? (Yes/No)**
No

**Comment by shubhankarsharma00** [comment]
I'm on the bug though I'll like to know if it is really necessary to ask for the name of the project with the help of the prompt during online save, because we ask for it in the next page anyway.

**Comment by ankitkataria** [comment]
@shubhankarsharma00 We initially create the project using the name and add data to it in `simulator_controller#create` and then redirect the user to the actual project edit page, where we can add other parameters like description etc. The name is required to initially create the project and add the simulator data which won't be available on the edit page. 

There a few replacements for the current flow that I can think of - 

1. After showing the name prompt(if the name isn't already set) we can have another prompt asking the user if he/she wants to continue working on the project or finish it by adding a description etc. (or)
2. On clicking the save option, we can open a create page in a modal and send all the project params at once to carry out the create (preferably as `projects_controller#create`)

In the first one, handling the interim project state might be a hassle. After fixing this issue, we can discuss if the current flow needs to be removed or not. :wink:

**Comment by shubhankarsharma00** [comment]
@ankitkataria the suggestions are actually really good but I think rather then adding new create page or another prompt we can solve this bug easily: from what I could gather even if we leave the field empty there is a default name for every project so
- I think one way can be that we don't prompt the user for the name on the simulator edit page and create the project with a default name(`Untitled`) and change it on the project edit page.

**Comment by ankitkataria** [comment]
> I think one way can be that we don't prompt the user for the name on the simulator edit page and create the project with a default name(Untitled) and change it on the project edit page.

This sounds great!

> or we just somehow fix the prompt to return when there is null input because we'll have to do it for offline save anyway. 

Let's first start by fixing this bug, we can look into a different flow once this issue is tackled.

**Comment by shubhankarsharma00** [comment]
sorry, I am not able to work on this I was busy with some internship work please feel free to approach this issue, anyone.

**Comment by Rana-Elkhouly** [comment]
I'm working on this issue.

**Comment by shubhankarsharma00** [comment]
@tachyons can we reopen this.
