### ISSUE TITLE
🐞 Bug

### ISSUE THREAD

**Issue by Bharadwajshivam28** [CircuitVerse/CircuitVerse#3747]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the footer section where there is icon of Facebook, Twitter and Linkedin I can see that the icons are flowing out of box. We have to align them properly in the box... And i think there is no need of box also because box it will look more good but if we have to keep the box then we have to align icons properly as they are flowing out of box..

### Steps To Reproduce

1. Go to - https://circuitverse.org/
2.  Come down at the footer section/area
3.  We can See that the social media  icons are not aligned properly in the box we have to align them properly or we can remove the box which can be also a good idea

### Expected Behavior

Icons should be in center or if they are at side then also they have to be in the box or we can remove the box

### Screenshots

![Screenshot from 2023-05-08 00-53-30](https://user-images.githubusercontent.com/108119109/236698764-5b4e1f73-dc60-42eb-be5c-f4e7e8001c31.png)

### Device Information [optional]

```markdown
- OS: Linux (POP OS)
- Browser: Firefox
- version:
```

### Are you working on this issue?

Yes

**Comment by Bharadwajshivam28** [comment]
@tachyons Please assign to me so i can work on it

**Comment by Arnabdaz** [comment]
Issue is already open at [#3642](https://github.com/CircuitVerse/CircuitVerse/issues/3642)

**Comment by Bharadwajshivam28** [comment]
@Arnabdaz can i work on it??

**Comment by Bharadwajshivam28** [comment]
I will close this one and work and fix that one

**Comment by Bharadwajshivam28** [comment]
I have not noticed

**Comment by Bharadwajshivam28** [comment]
yes no one as the last comment was in march

**Comment by Bharadwajshivam28** [comment]
could you assign me that issue so i will close this one

**Comment by Arnabdaz** [comment]
Sorry I don't have the perms to assign issues yet you need to wait for Admins. You can ping them in the other thread and ask to be assigned

**Comment by Arnabdaz** [comment]
> okay like can you drop admins slack id

You can ping on GitHub or just join our slack channel at https://join.slack.com/t/circuitverse-team/shared_invite/zt-1v0jav9si-Y8teVum5sovXMQWKkL2l0Q
