### ISSUE TITLE
Redo option

### ISSUE THREAD

**Issue by harsha-iiiv** [CircuitVerse/CircuitVerse#376]
**Currently, there is no redo option for the Simulator.

**Are you working on this? (Yes/No)**
No

**Comment by theredcap** [comment]
@harsha-iiiv Ctrl-Z works fine in the simulator.

**Comment by harsha-iiiv** [comment]
But Ctrl + y, Redo option is not functioning.

**Comment by Shivansh2407** [comment]
Can I work on this issue @harsha-iiiv and @theredcap ?

**Comment by harsha-iiiv** [comment]
Yes, go-ahead with W PR

**Comment by Palaksharma23** [comment]
Hii,
Is anyone working on this issue?
Please assign me this issue and please help me out with some code pointers/references from where I can start digging into it.

**Comment by Palaksharma23** [comment]
Currently working on it ............

**Comment by nitin10s** [comment]
Sure Palak

cc @abstrekt @satu0king

**Comment by Palaksharma23** [comment]
@abstrekt that pr is closed so can i work on this issue .

**Comment by Palaksharma23** [comment]
@abstrekt if you want you can continue your work on your pull request, i checked it and you have done all correct changes just you have made changes in public file which is not in use now.
You can do these changes in simulator folder and can again make a pull request , but please confirm me if you are working on this or not.
Thank you

**Comment by nitin10s** [comment]
@Palaksharma23 you can open a PR for the same.

**Comment by pulkit-30** [comment]
Hey @nitin10s,
I was trying to implement this feature and successfully implemented the feature.
Opening pr for the requested feature.
