### ISSUE TITLE
Step-by-step guide for simulator

### ISSUE THREAD

**Issue by harsha-iiiv** [CircuitVerse/CircuitVerse#377]
It would be a good feature if we add step by step guide for simulator like a website tour.

**Additional context**
 
![guide](https://user-images.githubusercontent.com/31560965/56867750-bb864e00-6a06-11e9-85e8-abc8f2c09486.gif)

**Are you working on this? (Yes/No)**
Yes

**Comment by harsha-iiiv** [comment]
Please tell me your opinion on this feature @satu0king.

**Comment by satu0king** [comment]
Sorry, I missed this somehow. Yeah it is a great feature. How did you achieve this?

**Comment by harsha-iiiv** [comment]
Yes @satu0king

**Comment by satu0king** [comment]
@harsha-iiiv go ahead with w PR

**Comment by Shivansh2407** [comment]
Can I work with this @satu0king and @harsha-iiiv ?
