### ISSUE TITLE
Export Truth Tables

### ISSUE THREAD

**Issue by ogierm** [CircuitVerse/CircuitVerse#381]
I'm using CircuitVerse for lots uni stuff and truth tables would be useful for testing if my circuit behaves as expected, minimising etc..

When editing the circuit (where the whole thing is composed into one node and I can set the width and height) there could be an option to pop out the truth table. Additionally you should be able to have it rendered into the export image / SVG aswell

**Are you working on this? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
@Parikshit-Hooda can I work on this ?

**Comment by abstrekt** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/895#issuecomment-600802519
if PR is merged, this issue can be closed @satu0king ?

**Comment by satu0king** [comment]
I think this is implemented. @abstrekt
