### ISSUE TITLE
Improve Unit Test Coverage

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#3817]
Improve Unit Test Coverage

- [x] Models #3835
- [x] Helper #3836
- [x] Controllers #3852
- [x] Jobs #3853

**Comment by tanmoysrt** [comment]
@smritigarg @vedant-jain03  The listed PRs in this issue are ready for review!

**Comment by NextThread** [comment]
hey, can I work on this issue
