### ISSUE TITLE
Twitter logo not updated

### ISSUE THREAD

**Issue by HectorShaw** [CircuitVerse/CircuitVerse#3920]
### Is your feature request related to a problem? Please describe

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this. 

### Describe the solution you'd like

Wont change anything in the code as such would replace the  twitter-logo.png with a new file . No code will be touched

### Are you working on this?

Yes

**Comment by vikaskumar2703** [comment]
i d like to work on this issue unless @HectorShaw u aint created this issue to assign it to urself

**Comment by HectorShaw** [comment]
Was supposed to but go on i have the logo attached here facing some issues with my current laptop so did'nt end up working it need to be 400 x 400 so be careful 


![twitter-logo](https://github.com/CircuitVerse/CircuitVerse/assets/96543344/3c0a8c02-3334-4ae0-ae71-ac3b19b9043e)

**Comment by 8rxn** [comment]
Hey, Are you still working on this @vikaskumar2703 ? 

I would like to update this if you haven't.

**Comment by sanket-1305** [comment]
I would like to work on this if no one else is working!

**Comment by IAmRiteshKoushik** [comment]
@HectorShaw Has this issue been resolved or is work still left to do on this issue ?

**Comment by HectorShaw** [comment]
I guess the issue should have been resolved but didnt have response from maintainers so closing it for now.
