### ISSUE TITLE
🐞 Bug : Inappropiate  behaviour of zoom in and zoom out buttons

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3946]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Describe the bug

The zoom in and zoom out buttons are not working ideally as they need to work!!!!!!!

### Steps To Reproduce

1. click on  getting started
2. there click on documentation 
3. open any documentation 
4. use  zoom in and zoom out buttons .They are not working properly

### Expected Behavior

Instaed of moving the circuit left right they should zoom if zoom in is pressed

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/138685168/8f1da869-01a6-43bc-abb2-e8e288a30fd7

### Device Information [optional]

```markdown
- OS:window 11
- Browser:chrome
- version:
```

### Are you working on this issue?

Yes

**Comment by vikaskumar2703** [comment]
@harshsharma-11 This issue should be raised in the circuit verse docs repo

**Comment by harshsharma-11** [comment]
is this is in wrong repository so i am closing it
