### ISSUE TITLE
[TYPO]: there shoul be ',' use between "sure" and "you"

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3964]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

there is typo in delete assignment pop-up 

Reference of this issue
![Screenshot (215)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/d91e0f85-941a-4dd6-84eb-e3541b5f60b0)

### Steps To Reproduce

1.click on dropdown near your profile name seen in the navbar
2.then click on my groups
3. then after making groups
4.after creating assignments
5.when you click delete button this popup in above ss appears

### Expected Behavior

there should be comma between sure and want

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
@sal2701 @satu0king
 @Shivansh2407 @ShreyaPrasad1209 @shubhankarsharma00 @Shweta0002 @tachyons 
 please review this ,i want to make my first coontribution to circuitverse.
 please assign  this to me

**Comment by karthxk07** [comment]
Hi, I have already updated what needs to bee done. I hope this might solve this issue

**Comment by harshsharma-11** [comment]
@karthxk07 bro without assigning the issue you can't make pr,this is the policy i hope you know .If you don't then before contribution first read the contribution guide

**Comment by karthxk07** [comment]
@harshsharma-11  sorry, I didn't knew about it. What should I do about it now?

**Comment by harshsharma-11** [comment]
@karthxk07 only thing you can do is ,you can close your pr

**Comment by karthxk07** [comment]
@harshsharma-11 there are hundred other issues opened, you can probably try to get them assigned to you.

**Comment by harshsharma-11** [comment]
> @harshsharma-11 there are hundred other issues opened, you can probably try to get them assigned to you.

mate @karthxk07 i am the opener of issue and you should also look at the top in "are you working" there i mark yes ,so i will be the first person to be the assignee of  the issue .So if you want to solve issue ,first read contributing guidelines and not waste other's time and hardwork .Then you are good to go
