### ISSUE TITLE
[typo]:"email " istead of "emai id"  in  hindi and english 

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3976]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when you are adding mentors for groups then there is typo

### Steps To Reproduce

n

### Expected Behavior

h

### Screenshots

![Screenshot (238)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/18ffbf69-6a81-4d9f-9eff-da489655b3c7)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by manas95826** [comment]
I want to work on this!

**Comment by harshsharma-11** [comment]
@manas95826  bro i has already made  a Pull Request for this ,look for other bugs
