### ISSUE TITLE
[typo]:"my circuits" instead of "circuits"

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when you open someone's profile you can see their "My Circuits" section in his profile how???

### Steps To Reproduce

1.search any user in search option of navbar
2.open the user's profile 
3.you able to see "My Circuits" instead of just "circuits"

### Expected Behavior

instead of "MY CIRCUITS" it should be "CIRCUITS"

### Screenshots

![Screenshot (243)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/32339c33-2bf1-44e1-8cac-e0807c433c7d)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Arnabdaz** [comment]
why do you think it should be circuits instead of my circuits ?

**Comment by harshsharma-11** [comment]
> why do you think it should be circuits instead of my circuits ?

sir if you open another's profile why their circuits named as "my circuits" and in our profile too it is "my circuits".So to show  another user circuit it is better to named their circuits  as "Their circuits" or "Circuits".

**Comment by harshsharma-11** [comment]
cc @tachyons @Arnabdaz

**Comment by harshsharma-11** [comment]
cc @Arnabdaz @tachyons
