### ISSUE TITLE
Improve Assignment Restricted Element Reporting

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#398]
1) Show restricted elements banner only if present
![image](https://user-images.githubusercontent.com/2092958/60487354-55939c80-9cbd-11e9-9a4c-ec89fa97e131.png)
2) Show restricted elements across all scopes in assignment preview (when mentor sees)
3) Improve restricted element detection
4) Show warning message when circuit is saved

**Comment by ankitkataria** [comment]
I'll start working into this. 😄

**Comment by satu0king** [comment]
Oh, I was going to assign this to myself xD

**Comment by ankitkataria** [comment]
We can divide work on this one too. Which ones would you want to pick?

**Comment by shubhankarsharma00** [comment]
Leaving some added information:
- [ ] To show Restricted Elements div only when applicable:
Just add an if statement  
`         <%if @assignment.restricted_circuit_elements != "None"%>
`
https://github.com/CircuitVerse/CircuitVerse/blob/2898a70401ae1d7521a9e8c51347ec9710a74bdf/app/views/assignments/show.html.erb#L38-L40
