### ISSUE TITLE
[typo]: instead of "detail" it should be "details"

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in the about section there written "detail" instead of "details"

### Steps To Reproduce

1.go to about section by clicking about in navbar
2.scroll down a little and you find it

### Expected Behavior

it should be "details"

### Screenshots

![Screenshot (250)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/8b1c94e1-95b2-4654-8cb3-241c81286603)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Sujal942** [comment]
I would like to correct it can you please assign me
