### ISSUE TITLE
🐞 Bug: "fullscreen" should be replaced by "exit fullscreen"

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3987]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when you are viewing some circuits when you click "fullscreen" now circuit appears in fullscreen but to get back you can click the button "fullsctreen" but it should be "exit fullscreen"

### Steps To Reproduce

1.in homepage scroll down
2.click on featured examples
3.now you can see the issue

### Expected Behavior

it should have "exit fullscreen" when we are in fullscreen mode

### Screenshots

![Screenshot (252)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/4eccb32b-8373-415d-9405-ffe17c279c31)

https://github.com/CircuitVerse/CircuitVerse/assets/138685168/52adf7ad-6d5f-41fa-a902-9e7e5bf89dfd

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
cc @vedant-jain03 @tachyons @VaibhavUpreti please review this issue and let me know so that i can work on it

**Comment by ShivangRawat30** [comment]
I would like to work on this issue.
