### ISSUE TITLE
🐞 Bug:the istudio in footer has no active link

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#3995]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the istudio in footer has inactive link

### Steps To Reproduce

1.scroll down the homepage
2.click istudio in footer
3.you will see able to see the error

### Expected Behavior

it should have an active link

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/138685168/435f1a25-8b46-42f2-9557-6edf0fd70805

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
please @vedant-jain03 @tachyons @Arnabdaz @VaibhavUpreti please review and guide me how to make it active .I will be happy to work on it

**Comment by harshsharma-11** [comment]
@tachyons please provide link to connect to istudio

**Comment by vedant-jain03** [comment]
> @tachyons please provide link to connect to istudio

as discussed , we need to remove it

**Comment by harshsharma-11** [comment]
@vedant-jain03  we have to remove istudio from footer or just make its link inactive

**Comment by riteshsinghh-coder** [comment]
@vedant-jain03 @tachyons @Arnabdaz @VaibhavUpreti please review solved the issue #4004
