### ISSUE TITLE
Countries and Educational institutions - User Model

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#4]
User Model to store country and educational institution information. This is necessary for analysis. 

Should they be a foreign key to another table or just stored as string? 
Foreign key - Probably more difficult to implement 

[Jquery Autocomplete](http://jqueryui.com/autocomplete/) might help.

**Comment by garry329** [comment]
I would like to work on this issue @satu0king.Will that be okay?

**Comment by satu0king** [comment]
Yes, @tachyons any advice on how to proceed with this feature?

**Comment by tachyons** [comment]
Storing countries and colleges as separate tables seems an overkill to me. There are gems available to implement country select https://github.com/stefanpenner/country_select

**Comment by satu0king** [comment]
What about universities?

**Comment by tachyons** [comment]
It is almost impossible to get all university details. I would suggest just use a string field

**Comment by garry329** [comment]
Okay, so for country i will be making another table and use it as foreign key in user model.For institution , i will be adding a new string field to user model.Does this sound ok?

**Comment by garry329** [comment]
So, i have opened the which resolves this issue. i have used the country_select as suggested by @tachyons.I have also refactored and formatted some code in the logix controller and view templates.Please tell me if anything more needs to be done.
