### ISSUE TITLE
ctrl+c stops working randomly

### ISSUE THREAD

**Issue by HypheX** [CircuitVerse/CircuitVerse#40]
Sometimes I use the copy/paste functions heavily. Occasionally, it stops working randomly. No idea what causes this, but the only fix is to save and refresh the page.

**Comment by satu0king** [comment]
That is unexpected. It is difficult to debug these sort of issues without more information. Next time this happens, do the following. 

1. Paste whatever is there in the clipboard into a comment here. 
2. Open chrome developer tools (cmd+option+I) in mac and (ctr+shift+I) in windows/Linux. take a screenshot of the error messages or logs.

**Comment by HypheX** [comment]
Okay, I will.
It is funny though, I kept getting this issue every 5 minutes...
Now I does not pop up at all, damn...

**Comment by HypheX** [comment]
Glitch finally happened: clipboard:

{"layout":{"width":100,"height":40,"title_x":50,"title_y":13},"allNodes":[{"x":10,"y":0,"type":1,"bitWidth":1,"label":"","connections":[]}],"id":88379942558,"name":"BCD-sub","Input":[{"x":80,"y":130,"objectType":"Input","label":"","direction":"RIGHT","labelDirection":"LEFT","propagationDelay":0,"customData":{"nodes":{"output1":0},"values":{"state":0},"constructorParamaters":["RIGHT",1,{"x":0,"y":20,"id":"IXpvZjZ2mZ4IF2R6R5HL"}]}}],"nodes":[],"scopes":[],"logixClipBoardData":true}

**Comment by HypheX** [comment]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data[Learn More] logix.js:56:65
paste
https://circuitverse.org/js/logix.js:56:65
startListeners/<
https://circuitverse.org/js/listeners.js:267:9

**Comment by HypheX** [comment]
I just found the cause of the glitch... if you copy twice in a row too fast, it breaks.
1)Select a part
2)Hold ctrl
3)Double tap C quickly

**Comment by satu0king** [comment]
> I just found the cause of the glitch... if you copy twice in a row too fast, it breaks.
> 1)Select a part
> 2)Hold ctrl
> 3)Double tap C quickly
> 4)Paste --as soon as you paste, the code breaks.

When you do C twice, the first time it copies the selected elements, but once copied, the selected elements are no longer selected (this cannot be fixed). So the second time it copies nothing .... so it can paste nothing. This is expected behavior. However, you reported that after it fails once, the copy paste breaks, this is not expected behavior. For me, once it breaks, if I select again and copy it works .. 
Could you share details on which browser you are using.

**Comment by HypheX** [comment]
I am using Firefox Version 63.0.1 (64-bit)

**Comment by blane1257** [comment]
I'm using Chrome and it happens for me occasionally too.

perhaps this could be fixed by introducing a cool-down after the first copy.

**Comment by satu0king** [comment]
I am having an idea to fix the issue by not copying anything if nothing is selected. This should fix it .. will try later today.

**Comment by satu0king** [comment]
@blane1257 @HypheX, I made a change, could you report if you face the issue again. (Clear the cache to get the latest version)

**Comment by HypheX** [comment]
I confirm, the issue has stopped. AWESOME, THANK YOU!!!

**Comment by satu0king** [comment]
Cheers!

**Comment by HypheX** [comment]
![image](https://user-images.githubusercontent.com/29693543/48584806-ff1d4d80-e8e7-11e8-9de7-30d8373d0f61.png)
It happened again @satu0king
