### ISSUE TITLE
🐞 Bug  Request to Update Twitter Icon to X 

### ISSUE THREAD

**Issue by lalitkumawat1m** [CircuitVerse/CircuitVerse#4019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Twitter logo is updated recently and hasnt been updated on the site. I didnt find any issue related to this.

### Steps To Reproduce

Scroll to the footer section and see twitter logo

### Expected Behavior

Twitter logo should be changed to X

### Device Information [optional]

```markdown
- OS: windows
- Browser:chrome
- version:
```

### Additional context

I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Are you working on this issue?

Yes

**Comment by riteshsinghh-coder** [comment]
<img width="854" alt="Screenshot 2023-09-10 012951" src="https://github.com/CircuitVerse/CircuitVerse/assets/93989204/85ca43bf-3902-4615-ad73-2807b4bde7e5">
 Fixed-#4019

**Comment by riteshsinghh-coder** [comment]
@tachyons please review
