### ISSUE TITLE
Feature :Github link should be there in the footer with other social meadial links

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4028]
### Is your feature request related to a problem? Please describe

there should be provided github link of CircuitVerse in the footer with other social media links google,facebook ,twitter so that it will be easy for user to find github repo 
![Screenshot (269)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/20c9a1de-d71a-434b-8387-ababb0353f5f)
.
.
.
like this 
![Screenshot (263)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/f95f8433-c2e7-4fcc-8a46-f527331f6c52)

### Describe the solution you'd like

for this we should also provide git hub repo link in footer like social media links 

### Are you working on this?

Yes

**Comment by harshsharma-11** [comment]
@VaibhavUpreti @vedant-jain03 @tachyons please review and let me know what your views about this.I think it would be better
to user who looks up for github repo in website

**Comment by tachyons** [comment]
Good idea, go ahead

**Comment by shivang17d** [comment]
Hey, Can I work on this issue ?

**Comment by harshsharma-11** [comment]
> Hey, Can I work on this issue ?

already made a pr bro
