### ISSUE TITLE
🐞 Bug:social media icons are not align properly

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4029]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (270)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/72d3dba5-5a6d-4830-9ad5-35f26b2d5e2c)

### Steps To Reproduce

scroll down to footer and you will find this

### Expected Behavior

there should be proper alignment of these icons

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
@VaibhavUpreti @vedant-jain03 @tachyons please review .I want to work on it

**Comment by Malavi1** [comment]
The issue raised already 
#3642
