### ISSUE TITLE
🐞 Bug:notifications not properly fitted in container

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the notifications are not properly fitted inside the notification container

### Steps To Reproduce

1.go to notification section by clicking the bell
2.see your notification 

### Expected Behavior

properly fitting of notification inside the container

### Screenshots

.
.
.
![Screenshot (279)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/e65ca36b-5853-4a4a-84e8-16f4c5c5e5e8)

should be like this......
.
.
.
![1](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/f589c6ba-6fc8-4027-b94f-5d8131162191)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
@tachyons @VaibhavUpreti @vedant-jain03 please review and if valid please assign ,i want to work on this

**Comment by harshsharma-11** [comment]
@tachyons @VaibhavUpreti @vedant-jain03 please review

**Comment by harshsharma-11** [comment]
@Arnabdaz  @VaibhavUpreti please review

**Comment by salmoneatenbybear** [comment]
Fixed in #4244
