### ISSUE TITLE
Feature :youtube link of circuitVerse

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4047]
### Is your feature request related to a problem? Please describe

youtube link of circuitVerse
like here in image below
![Screenshot (282)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/654b3341-e37c-4f44-8418-44540ce39542)

### Describe the solution you'd like

there can be CircuitVerse youtube link as well in the footer along with linkedin,instagram .It will be better for users as youtube has some tutorial also where user can take help and brush up their concepts 

### Are you working on this?

Yes

**Comment by harshsharma-11** [comment]
@tachyons @Arnabdaz

**Comment by tachyons** [comment]
Go ahead

**Comment by harshsharma-11** [comment]
> Go ahead

thanks a lot

**Comment by harshsharma-11** [comment]
> Go ahead

thanks ,i am glad to work on it

**Comment by harshsharma-11** [comment]
cc @vedant-jain03 please check the pr
