### ISSUE TITLE
[UI-Bug] 4 options under help section not properly aligned

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4074]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Under Navbar, on small screen , when clicking on help section. the 4 options (Tutorial, User Manual, Learn Digital Logic, Discussion Forum) are not correctly align.

### Steps To Reproduce

1. Go to Simulator.
2. Convert your screen to small size device.
3. Click on navbar.
4. click on Help.
5. see the 4 option are not correctly align.

### Expected Behavior

(Tutorial, User Manual, Learn Digital Logic, Discussion Forum) Under Help should be correctly align.

### Actual Behaviour
![CV-UI-fix-bug-before-image](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/198043e8-3038-4523-befe-690b1753b067)

### Expected Behaviour
![CV-UI-fix-bug-after-image](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/ebb6466a-258d-49ab-9db4-02a2286c626c)

### Are you working on this issue?

No

**Comment by HemanthKR07** [comment]
Hey @shauryag2002 , I can fix this ! 
Can you assign this to me.

**Comment by Ayush-865** [comment]
Please Assign me this issue . I'm starting with my OpenSource Journey with CircuitVerse but can surely solve this issue

**Comment by mohitkadwe19** [comment]
Hello @shauryag2002 , it would be great if we can add media query for table and Desktop view . I have fixed the issue in my local , if you assign this task to me ,I can the changes push and create PR for same.

**Comment by vedant-jain03** [comment]
@shauryag2002 @mohitkadwe19  thanks for the suggetions but if you carefully see the other menu-item behaviour, we use 3 items grid system means in a single row, we are displaying 3 items and it is persistent throughout all the menu-items.

Might be a good approach here would be:
- To implement a grid or flex to make styles more stable as right now we are using `px`

**Comment by Ayush-865** [comment]
@vedant-jain03 I can implement grid system and would eliminate use of px . I want to work on this issue
