### ISSUE TITLE
Scroll to Comment Box

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4075]
### Is your feature request related to a problem? Please describe

When we open a user's circuit page , If we want to comment on it then we have to scroll to the end for post a comment it .
And that is a pain because if a post has too many comment we have to scroll to much

### Describe the solution you'd like

Place a down arrow besides the comment headline so when user clicks it . It will scroll smoothly to the end and the comment area will be accessable.
### Screenshot of the solution:
![CV-Issue-scroll-image](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/8981703a-7f56-4279-b6fd-1c74ce17ffba)

### Are you working on this?

No

**Comment by HemanthKR07** [comment]
Hi @shauryag2002 , can we place the 'Add comment' block on top of all comments ? Or I can even add the arrow button too, Can I work on this ?

**Comment by Arnabdaz** [comment]
I would recommend rather working on #3678

**Comment by HemanthKR07** [comment]
I will try to fix this !

**Comment by yash1378** [comment]
@Arnabdaz   what i am thinking that instead of placing an arrow to scroll , can i place the add comment button  over all the comments so i would not have to even scroll to comment ? can you assign this issue to me ?

**Comment by connectnitesh** [comment]
hey @Arnabdaz & @vedant-jain03  I would like to work on this issue, can u please just assign it to me?
