### ISSUE TITLE
[🐞 Bug]: On hovering on icons of Follow us on: in the footer the some part of tooltip is going behind copyright text

### ISSUE THREAD

**Issue by priyanshuxoxo** [CircuitVerse/CircuitVerse#4093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

on hovering on icons of follow us on: in the footer section some part of tooltip is going behind the copyright text 

### Steps To Reproduce

Step 1->Go to CircuitVerse.Org
Step 2->Scroll down to Footer section
Step 3->Hover on the icon of  Follow us on:

### Expected Behavior

The tooltip should not go behind the copyright text rather there should be space between copyright text and tooltip .

Solution 1-> we can add z-index so that the tooltip don't underlap with copyright as well as each other

### Screenshots

![Screenshot 2023-09-29 153335](https://github.com/CircuitVerse/CircuitVerse/assets/114825004/a273a06e-8fc7-49eb-adc1-0aa5a28faea0)

### Device Information [optional]

```markdown
- OS:Windows
- Browser:Brave
- version:v 1.58.131
```

### Are you working on this issue?

Yes

**Comment by hrshkshri** [comment]
Hey, I see the problem here.
Giving a margin to the bottom would do the job.
I would like to raise the PR.

**Comment by priyanshuxoxo** [comment]
@VaibhavUpreti Can u please review this?

**Comment by priyanshuxoxo** [comment]
@vedant-jain03 @tanmoysrt  can you please review this issue?

**Comment by tanmoysrt** [comment]
The bug has been verified !

**Comment by tanmoysrt** [comment]
@priyanshuxoxo are you working on this?

**Comment by priyanshuxoxo** [comment]
yep

**Comment by priyanshuxoxo** [comment]
@vedant-jain03 @tanmoysrt can you please add hacktoberfest label ? so that it can be accepted in Hacktoberfest 2023.
