### ISSUE TITLE
Tunnel "clickbox" is offset.

### ISSUE THREAD

**Issue by HypheX** [CircuitVerse/CircuitVerse#41]
The "clickbox" of the Tunnel is offset to the side:
![offset-cb](https://user-images.githubusercontent.com/29693543/48026038-33cc2080-e102-11e8-925a-2314ebef6f51.gif)

Furthermore, deleting a Tunnel leaves a green dot behind.

**Comment by HypheX** [comment]
I am currently using the Tunnel very heavily, and I constantly have to deal with this clickbox issue, editing wires next to the output is impossible unless I move the tunnel away first.

**Comment by satu0king** [comment]
@HypheX  I just fixed it. Can you check it once? You may need to clear your cache to see the update (Ctr+Shift+R). There was another bug regarding deletion of Tunnel. I fixed that too.

**Comment by HypheX** [comment]
Yes! THANK YOU! It is fixed 👍
