### ISSUE TITLE
bug: show `not entered` if educational institute is blank in profile

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4104]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When the user doesn't provide any educational institute during his profile creation/updation, in the profile, it's showing nothing like you can see below in the image.

![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/ce5ad067-6742-4e38-993b-fbaa87c57790)

### Steps To Reproduce

1. Open main website [[circuitverse.org](https://circuitverse.org/)]
2. Login yourself
3. Go to your profile
4. Go to `Edit Details` page
5. Update profile with blank `Educational institute`
6. Check your profile
7. It will not show `Not Entered` anymore

### Expected Behavior

It should show `Not Entered` in the educational institute's value if the user hasn't provided one. It is the same as the `Country` detail.
Checkout the attached image for a reference

### Are you working on this issue?

No

**Comment by niladrix719** [comment]
can I work on this?

**Comment by YashGupt29** [comment]
assign me this issue

**Comment by Snehil-Shah** [comment]
Unable to reproduce this issue

![image](https://github.com/CircuitVerse/CircuitVerse/assets/130062020/3799d6dc-7d86-48ef-a4f6-d17ff42f028a)

Works as expected!

**Comment by harsitagarwalla187** [comment]
Can i work on this?

The produced issue: 
<img src="https://github.com/CircuitVerse/CircuitVerse/assets/84774840/2751fb06-3cdc-40ac-bde2-78135d3f63f5" width="400" height="200">

**Comment by rajatmohan22** [comment]
Hello! I've proposed a solution for this issue. I think there are 2 things that can be done.

1. Remove the "Educational Institution" field if it's not entered. This may be confusing for users who weren't prompted to fill it during initial signup. And the user would not know of it until and unless he clicks the "edit" button.

2. Fill the field with 'Not Entered' by default. This reminds the users to edit the form and enter their details.

I've submitted a PR for this. Please have a look: #4118

**Comment by niladrix719** [comment]
hi @rajatmohan22 I am already working on this
