### ISSUE TITLE
align `edit details` button with parent

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4105]
### Is your feature request related to a problem? Please describe

The `edit details` button under the `Dashboard` or `Profile` page is not properly aligned w.r.t the parent component. 

![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/2b5a7613-1c5c-441d-a5d6-bbc5944920b6)

### Describe the solution you'd like

The button may have some padding around. Removing that can solve the issue.

### Are you working on this?

No

**Comment by YashGupt29** [comment]
assign me this issue i will try my best

**Comment by harsitagarwalla187** [comment]
Can you please assign it to me?

Before:
![image](https://github.com/CircuitVerse/CircuitVerse/assets/84774840/b4341fd9-d43b-4459-8506-e9ce2652a4f7)


After: 
![image](https://github.com/CircuitVerse/CircuitVerse/assets/84774840/942f3ad5-43c6-478f-b28e-d1194baac528)

**Comment by saltykheera** [comment]
![image](https://github.com/CircuitVerse/CircuitVerse/assets/142778969/78c3c9a7-c239-485d-a9fd-046b257211c8)

**Comment by saltykheera** [comment]
sry my mistake i dont know what pending triage meant

**Comment by uraj323** [comment]
sir please assign this issue to me

**Comment by tanmoysrt** [comment]
Hi @YashGupt29, can you raise a new PR ?
Actually, the `primary-button` class has been used in many place, so the removal of margin from the class has created some design issue in the website. 

So make the `primary-button` class  as before and may create a new class or use bootstrap class to remove the margin.

**Comment by shauryag2002** [comment]
Hi @vedant-jain03 , Can I work on this issue?
## Screenshot of solution:
![CV-issue-button-marginLeft0](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/69a986b7-daeb-463d-87e0-cd22483a88bc)

**Comment by unnat-gupta** [comment]
Hi! I would like to work on this issue.
Please let me know if I can do so.
