### ISSUE TITLE
improve responsiveness of profile page

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

<img src="https://github.com/CircuitVerse/CircuitVerse/assets/57363826/a4a5c097-c330-4a2d-9247-04ab26220318" width="200px" />

As you can see in the image, The My Circuits | Favourite Circuits | Collaborated Circuits and the Search bar are collapsing together and making it not responsive in the device width.

### Steps To Reproduce

1. Go to the main website [[circuitverse.org](https://circuitverse.org/)]
2. Log in yourself
3. Open your profile in mobile

### Expected Behavior

We need to make it a bit more responsive

In desktop mode, the layout will be
```
-----------------------------------------------------------------------------------------------
| My Circuits | Favourite Circuits | Collaborated Circuits | <-----------------> | Search Bar | 
-----------------------------------------------------------------------------------------------
```

In mobile mode, the layout will be like (based on the device  width)
```
------------------------------------------------------------
| My Circuits | Favourite Circuits | Collaborated Circuits | 
------------------------------------------------------------
|                      Search Bar                          | 
------------------------------------------------------------
```

Or

```
------------------------------------------------------------
|          My Circuits       |      Favourite Circuits     |
------------------------------------------------------------
|   Collaborated Circuits    | 
------------------------------------------------------------
|                      Search Bar                          | 
------------------------------------------------------------
```

Make sure the text of each button come in single line

### Are you working on this issue?

No

**Comment by niladrix719** [comment]
I think I can work on this

**Comment by tanmoysrt** [comment]
please wait a bit until the `pending triage` label removed

**Comment by hrshkshri** [comment]
Hey @tanmoysrt, I understand your concern.
Correct me if I am wrong, but I made some changes feel free to share your thoughts.

**Before**

![Screenshot 2023-10-04 at 2 09 48 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/240fcfe9-8ff8-4125-be24-34eefebb9030)

**After**

![Screenshot 2023-10-04 at 2 07 48 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/643b8350-378c-4708-a696-021d6e0d45cb)

`OR`


![Screenshot 2023-10-04 at 1 52 03 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/1ff95a79-8861-4b5d-8ec6-d3c48812fe4b)


`NOTE` I'll make these button text inline with proper padding after `pending triage`.

![Screenshot 2023-10-04 at 2 15 53 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/17d78b9a-8d9d-4b40-8826-2762f212d7e9)

Meanwhile, would you assign me this issue?

**Comment by tanmoysrt** [comment]
> Hey @tanmoysrt, I understand your concern.
> Correct me if I am wrong, but I made some changes feel free to share your thoughts.
> 
> **Before**
> 
> ![Screenshot 2023-10-04 at 2 09 48 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/240fcfe9-8ff8-4125-be24-34eefebb9030)
> 
> **After**
> 
> ![Screenshot 2023-10-04 at 2 07 48 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/643b8350-378c-4708-a696-021d6e0d45cb)
> 
> `OR`
> 
> 
> ![Screenshot 2023-10-04 at 1 52 03 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/1ff95a79-8861-4b5d-8ec6-d3c48812fe4b)
> 
> 
> `NOTE` I'll make these button text inline with proper padding after `pending triage`.
> 
> ![Screenshot 2023-10-04 at 2 15 53 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/17d78b9a-8d9d-4b40-8826-2762f212d7e9)
> 
> Meanwhile, would you assign me this issue? 
> 
> 
> 

We can make the search bar full width

cc @vedant-jain03 @VaibhavUpreti

**Comment by hrshkshri** [comment]
> > Hey @tanmoysrt, I understand your concern.
> > Correct me if I am wrong, but I made some changes feel free to share your thoughts.
> > **Before**
> > ![Screenshot 2023-10-04 at 2 09 48 PM](https://user-images.githubusercontent.com/108923011/272514163-240fcfe9-8ff8-4125-be24-34eefebb9030.png)
> > **After**
> > ![Screenshot 2023-10-04 at 2 07 48 PM](https://user-images.githubusercontent.com/108923011/272514362-643b8350-378c-4708-a696-021d6e0d45cb.png)
> > `OR`
> > ![Screenshot 2023-10-04 at 1 52 03 PM](https://user-images.githubusercontent.com/108923011/272514512-1ff95a79-8861-4b5d-8ec6-d3c48812fe4b.png)
> > `NOTE` I'll make these button text inline with proper padding after `pending triage`.
> > ![Screenshot 2023-10-04 at 2 15 53 PM](https://user-images.githubusercontent.com/108923011/272515964-17d78b9a-8d9d-4b40-8826-2762f212d7e9.png)
> > Meanwhile, would you assign me this issue?
> 
> We can make the search bar full width
> 
> cc @vedant-jain03 @VaibhavUpreti

Yeah for sure we can give search bar a full width

**Comment by NishantBansal2003** [comment]
Can I work on this issue if no one is working on it? Thanks!

**Comment by shreyansh1410** [comment]
Hey is this issue up for grab, I would love to make my first contribution to CircuitVerse @tanmoysrt ?

**Comment by tanmoysrt** [comment]
> Hey is this issue up for grab, I would love to make my first contribution to CircuitVerse @tanmoysrt ?

This issue has been solved ! You can look another issue
