### ISSUE TITLE
improve responsiveness of projects list page 

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Checkout the video first

https://github.com/CircuitVerse/CircuitVerse/assets/57363826/7851bb4d-831a-48fc-a734-17afcdc6555e

The navbar and search bar exceed the device-width. It's not a good experience for end-user

### Steps To Reproduce

1. Visit this page [circuitverse.org/search?resource=Projects&q=jk&button=Submit](https://circuitverse.org/search?resource=Projects&q=jk&button=Submit) from mobile screen
2. Check the responsiveness issue

### Expected Behavior
The components should not exceed device width and page should not overflow and have any kind of scroll in x-axis

### Are you working on this issue?

No

**Comment by himeshparashar** [comment]
I can look after this please assign it to me

**Comment by tanmoysrt** [comment]
please wait a bit until the `pending triage` label removed

**Comment by vedant-jain03** [comment]
@himeshparashar I have assigned you another issue, kindly complete that to get assigned to another, thankyou!

**Comment by coldrohak** [comment]
@tanmoysrt I would like to work on this issue, can you assign it to me?

**Comment by tanmoysrt** [comment]
> @tanmoysrt I would like to work on this issue, can you assign it to me?

sure !

**Comment by shauryag2002** [comment]
Can I work on this?

**Comment by tachyons** [comment]
Yes

**Comment by shauryag2002** [comment]
@tachyons Could you please assign this issue so that I can access it directly in my issues tab?

**Comment by Priyanshu-su30** [comment]
@tanmoysrt Please assign me this task I wish to work on this.
