### ISSUE TITLE
improve responsiveness of  `view` button in projects list

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4109]
### Is your feature request related to a problem? Please describe

See the image below first.

<img src="https://github.com/CircuitVerse/CircuitVerse/assets/57363826/9d0336db-56b0-4b21-80b0-fb49dd46002d" width="200px" />

The view button is the same as the desktop mode, which doesn't look nice in the mobile version.

### Describe the solution you'd like

In the desktop mode, keep it as it is.
For mobile mode, make the text `View Project` and make the button full width.

### Are you working on this?

No

**Comment by Malavi1** [comment]
Can I work?

**Comment by himeshparashar** [comment]
I can contribute to this issue please assign it to me

**Comment by tanmoysrt** [comment]
please wait a bit until the `pending triage` label removed

**Comment by himeshparashar** [comment]
@tanmoysrt I have created a PR regarding this issue https://github.com/CircuitVerse/CircuitVerse/pull/4125

**Comment by himeshparashar** [comment]
@tanmoysrt please can you review these changes and suggest some improvements.

**Comment by tanmoysrt** [comment]
> @tanmoysrt please can you review these changes and suggest some improvements.

sure!

**Comment by Deveshch2712** [comment]
@tanmoysrt Where can I find the code related to this issue? I'd like to contribute. Thanks!

**Comment by tanmoysrt** [comment]
> @tanmoysrt Where can I find the code related to this issue? I'd like to contribute. Thanks!

This issue is actually resolved by #4125. Anyhow this issue does not closed automatically. 
@Deveshch2712 please take a look at another issues or raise a issue on some problem .
