### ISSUE TITLE
improve responsiveness of landing page

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4110]
### Is your feature request related to a problem? Please describe

The landing page of CircuitVerse in the mobile version is not responsive design.

Check out the attached image. The buttons are not responsive.

<img src="https://github.com/CircuitVerse/CircuitVerse/assets/57363826/6f8c6dfe-42ad-48f4-a92d-90a4c0299aa4" width="250px" />

### Describe the solution you'd like

Here is a preferred design for this page. However, the design is open for feedback as well.

|  Old design | New Design |
|------------|-------------|
| <img src="https://github.com/CircuitVerse/CircuitVerse/assets/57363826/6f8c6dfe-42ad-48f4-a92d-90a4c0299aa4" width="250px" /> | <img src="https://github.com/CircuitVerse/CircuitVerse/assets/57363826/7a3e498c-9014-40f8-b820-c5cb70ab5b43" width="250px" /> |

### Are you working on this?

No

**Comment by Malavi1** [comment]
Can I work on the issue?

**Comment by himeshparashar** [comment]
Please assign this issue to me as I have good skill of responsive design

**Comment by hrshkshri** [comment]
Hey @tanmoysrt I did check this issue you are talking about...
changing the home simulator button to a `max-width` property to `inherit` would do the job for this particular button

![Screenshot 2023-10-03 at 4 34 36 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/970e4c02-41e6-43d2-b4e3-c3e759920c84)
![Screenshot 2023-10-03 at 4 36 44 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/56c9bcb3-51f1-4c7c-9221-dc7cc54ef73c)


Similarly, the other two button issues can be solved by this.
I am working on this issue meanwhile would assign me this...?

**Comment by tanmoysrt** [comment]
please wait a bit until the `pending triage` label removed

**Comment by hrshkshri** [comment]
@tanmoysrt Yeah sure.

**Comment by uraj323** [comment]
can i work on this issue ? assign this to me

**Comment by debnath003** [comment]
can I work on this? please assign me

**Comment by Karan-Palan** [comment]
Is this issue open to work on?

**Comment by pratik2172003** [comment]
if this issue  is open to work then i will like to contribute on it
