### ISSUE TITLE
🐞 Bug: Notification Page Style broken in mobile view & Large Screen(footer)

### ISSUE THREAD

**Issue by VaibhavUpreti** [CircuitVerse/CircuitVerse#4132]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Notification Page is not responsive in mobile view.
 
![nf](https://github.com/CircuitVerse/CircuitVerse/assets/85568177/714655fa-3bb0-40ec-b307-f351b281a7c2)

Footer in notification has extra white space below it.

![1234](https://github.com/CircuitVerse/CircuitVerse/assets/85568177/df3f946e-17fd-4b26-8d7e-97095c8dd6ed)

### Steps To Reproduce

1. Sign in to your circuitverse account.
2. Open notification dropdown, click -> See all
3. Observe bug on this notification for mobile view and footer.

### Expected Behavior

Page must be responsive for all devices.

### Are you working on this issue?

No

**Comment by niladrix719** [comment]
can I work on this

**Comment by uraj323** [comment]
please assign this issue to me

**Comment by hrshkshri** [comment]
Hey @VaibhavUpreti, I had a look, does this work ...?

**before**

![Screenshot 2023-10-07 at 8 43 45 AM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/bf5849d8-1800-42b3-80aa-33c01a90af37)

**After**

![Screenshot 2023-10-07 at 8 43 21 AM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/0cce7695-9028-431f-b518-d54e8c728d61)

May I work on this, assign me this one.

**Comment by harshsharma-11** [comment]
I am working on this , as there is no assignee

**Comment by vedant-jain03** [comment]
@niladrix719 @harshsharma-11 @hrshkshri I have seen that your work is under review. as there are new contributors we can help each other. Assigning it to @Vijaykv5 as asked first and new contributor to CV. @uraj323 you can checkout other issue

----

We are working on raising new issues every week, so don't worry you will get every chance!

**Comment by niladrix719** [comment]
@vedant-jain03 sure we should encourage new contributors. @Vijaykv5 if you need any help feel comfortable to ask. Go ahead with the issue

**Comment by Vijaykv5** [comment]
Yeah sure 👍🏼 
Thank you @niladrix719 and @vedant-jain03 for the support :)

**Comment by Vijaykv5** [comment]
Added a PR, Please check @vedant-jain03

**Comment by Vijaykv5** [comment]
Could you help me fix this issue in local development.

I've followed the steps exactly like in setup in readme and was installing using docker
how can I the see the live locally?

<img width="1013" alt="Screenshot 2023-10-07 at 4 47 32 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/94985341/3a254cc9-2a23-4290-adb9-0890ae3d4679">

@vedant-jain03 @niladrix719

**Comment by niladrix719** [comment]
@Vijaykv5 just go to http://localhost:3000

**Comment by niladrix719** [comment]
@Vijaykv5 you can also join CV [slack](https://circuitverse.org/slack) if you need any further help.

**Comment by Vijaykv5** [comment]
As per the #4145  Its working fine right also responsive in all devices.

**Comment by Vijaykv5** [comment]
Please any one can work on it. Thanks :)

**Comment by niladrix719** [comment]
@tanmoysrt can i take on

**Comment by shauryag2002** [comment]
Hi @vedant-jain03 @VaibhavUpreti , Can i work on this issue?
### Solution :
![CV-issue-noti-width](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/a7308076-ebae-4ec0-a644-98808a9d64a7)

**Comment by tanmoysrt** [comment]
> Hi @vedant-jain03 @VaibhavUpreti @tanmoysrt , Can i work on this issue?
> 
> ### Solution :
> ![CV-issue-noti-width](https://user-images.githubusercontent.com/77102885/280532912-a7308076-ebae-4ec0-a644-98808a9d64a7.png)

Go ahead, while raising the PR add preview screenshots with mobile, tab and desktop version with some notifications
