### ISSUE TITLE
Undo button in the context menu is not working

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#4135]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The undo button in the context menu is not working.

### Steps To Reproduce

1. Go to Simulator
2. Right-click on the canvas
3. Check the undo Button

### Expected Behavior

It should work like the undo button in the quick panel.

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/89515816/a6356b4f-a53d-4c07-ad0b-5bc5d7b7e3c3)

### Device Information [optional]

```markdown
- OS: Windows 10
- Browser: Chrome
```

### Are you working on this issue?

No

**Comment by coldrohak** [comment]
Can you assign this to me?

**Comment by niladrix719** [comment]
can I work on this

**Comment by siddoinghisjob** [comment]
Hey @Prerna-0202 can I work on it?

**Comment by uraj323** [comment]
please assign this to me @Prerna-0202

**Comment by ShashwatPS** [comment]
Can i work on this issue ? It's been 3 days since the last contributor commented.

**Comment by tanmoysrt** [comment]
Hi @coldrohak are you working on this?
I can't see any draft PR till now

**Comment by akshat-kaushik** [comment]
hello @tanmoysrt,
can u pls review my PR. I worked on it as its been 5 days since the last contributor commented.

**Comment by akshat-kaushik** [comment]
hello @Prerna-0202,
can u pls review my PR. I worked on it as its been 5 days since the last contributor commented.

**Comment by coldrohak** [comment]
> Hi @coldrohak are you working on this?
> I can't see any draft PR till now

Really sorry @tanmoysrt , I am caught up with some competitions work
