### ISSUE TITLE
Timing Diagram- Decrease height and Increase height buttons are not working

### ISSUE THREAD

**Issue by Prerna-0202** [CircuitVerse/CircuitVerse#4136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Decrease height and Increase height buttons are not working in Timing Diagram Panel.

### Steps To Reproduce

1. Go to the Timing Diagram panel
2. Expand it 
3. Click on the Decrease and Increase height buttons. 

### Expected Behavior

1. The Increase height button should increase the height of the panel.
2. The Decrease height button should decrease the height of the panel.

Just like, the Increase size and Decrease size button works.

### Screenshots

<img width="424" alt="image" src="https://github.com/CircuitVerse/CircuitVerse/assets/89515816/430bf835-e2d2-42ee-85f3-e8588c8b3508">

### Device Information [optional]

```markdown
- OS: Windows 10
- Browser: Chrome
```

### Are you working on this issue?

No

**Comment by SahityaGupta25** [comment]
I think I can help you in this

**Comment by DhairyaMajmudar** [comment]
@vedant-jain03 pls. assign this issue to me. I have gone through the code where bug is raised. And also working on an approach to remove the bug.

**Comment by uraj323** [comment]
please assign this to me

**Comment by SahityaGupta25** [comment]
@Prerna-0202 Thanks for Assigning me . As I am new to open-source can you help me where is the code?

**Comment by niladrix719** [comment]
@SahityaGupta25 app/views/simulator/edit.html.erb

**Comment by niladrix719** [comment]
@SahityaGupta25 and if you are looking for the Timing Diagram, you can go to the [simulator](https://circuitverse.org/simulator) and expand the Timing Diagram inside the canvas

**Comment by SahityaGupta25** [comment]
@niladrix719 Thanks a lot buddy........

**Comment by Jayendra-Welekar** [comment]
Hey any update over my pull request??

**Comment by MayurDas24** [comment]
Hi! I’d like to work on fixing this issue and will submit a pull request soon
