### ISSUE TITLE
Bug: when a user's name is short, it aligns horizontally with the profile picture in the search results

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4142]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I've noticed a bug where, in the search results, if a user's name is short, their name aligns horizontally with the profile picture. I believe this alignment should be corrected to ensure a better user experience.

### Steps To Reproduce

1. go to https://circuitverse.org.
2. Use the search bar to look for users.
3. Observe users with short names in the search results.

### Expected Behavior

regardless of the length of a user's name, the alignment of their name and the profile picture should always be visually consistent and correctly formatted.

### Screenshots

![Screenshot 2023-10-07 at 11 53 27 AM](https://github.com/CircuitVerse/CircuitVerse/assets/91966855/eddf1de4-add7-4ef4-8bfd-686c074b1a09)

### Device Information [optional]

```markdown
- OS: MacOs Sonoma
- Browser: Safari
- version: 16.5
```

### Are you working on this issue?

Yes

**Comment by vedant-jain03** [comment]
Verified the bug go ahead @niladrix719

**Comment by siddoinghisjob** [comment]
@niladrix719 Can I work on this issue please?

**Comment by niladrix719** [comment]
I am already working on this @siddoinghisjob

**Comment by DhairyaMajmudar** [comment]
@vedant-jain03 pls. assign this issue to me. I am figuring out the approach to solve this issue. I would be so nice of you if this issue is assigned to me .

**Comment by niladrix719** [comment]
@DhairyaMajmudar hi I am working on it already
