### ISSUE TITLE
🐞 Bug:footer irresponsive

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

footer is irresponsive in profile section of searched user
![Screenshot (319)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/6529e449-2d66-4664-b9c0-d384ca3fb799)

### Steps To Reproduce

..

### Expected Behavior

..

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by niladrix719** [comment]
I think this can be fixed in this #4132

**Comment by harshsharma-11** [comment]
@niladrix719 it doesn't as here misbehaviour is due to search box which is causing this problem and in 4132 hte issue is due to fix size given to notification box

**Comment by harshsharma-11** [comment]
@VaibhavUpreti @vedant-jain03

**Comment by tanmoysrt** [comment]
Hi @harshsharma-11
The main issue behind the unresponsive behaviour of the footer is the tabs and search bar of projects in the profile screen
This behaviour has been addressed to this #4106 

If you feel the same, close this issue, please.

**Comment by harshsharma-11** [comment]
ya ....
