### ISSUE TITLE
🐞 Bug:email box is not responsive

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4146]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the email container is not responsive at all
![Screenshot (321)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/ff1c1ecf-a01d-4ca8-8b2b-95c308b5206a)

### Steps To Reproduce

.

### Expected Behavior

.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
@VaibhavUpreti @vedant-jain03  please review the issue and assign this issue to me

**Comment by ansh343** [comment]
i am interested in working on this, can you assign this to me?

**Comment by ansh343** [comment]
i am interested in working on this, can you assign this to me?

**Comment by DhairyaMajmudar** [comment]
@VaibhavUpreti @vedant-jain03 @tanmoysrt  please assign this issue to me. I have located the code from where the bug can be fixed. And also figuring out the approach to solve this issue.

**Comment by tanmoysrt** [comment]
Verified the bug, @harshsharma-11 you have been assigned

**Comment by harshsharma-11** [comment]
i am not able to find where the email box is ,please help!!!!!!!

**Comment by tanmoysrt** [comment]
> i am not able to find where the email box is ,please help!!!!!!!

Check these two references - https://github.com/CircuitVerse/CircuitVerse/blob/bd9d6113c124ab230945bd5c6175a074a3c15ee5/app/views/groups/_add_mentor_modal.html.erb#L29

https://github.com/CircuitVerse/CircuitVerse/blob/bd9d6113c124ab230945bd5c6175a074a3c15ee5/app/javascript/controllers/groups_controller.js#L32

**Comment by harshsharma-11** [comment]
thanks @tanmoysrt for your help

**Comment by shauryag2002** [comment]
@tanmoysrt Can i work on this issue?
## Video of solution:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/5bb8f47a-0fbf-4587-87e9-2d02971e103e

**Comment by Prerna-0202** [comment]
> @tanmoysrt @Prerna-0202 Can i work on this issue?
> 
> ## Video of solution:
>  CV-issue-box-width.mp4

@shauryag2002 yes

**Comment by shauryag2002** [comment]
@Prerna-0202 you please assign this issue so that I can access it directly in my issues tab?
