### ISSUE TITLE
🐞 Bug:in small screen the user name and dropdown is not visible properly

### ISSUE THREAD

**Issue by harshsharma-11** [CircuitVerse/CircuitVerse#4147]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in the small screen in the simulator the  name and corresponding dropdown is not visible properly

### Steps To Reproduce

.

### Expected Behavior

.

### Screenshots

.
![Screenshot (323)](https://github.com/CircuitVerse/CircuitVerse/assets/138685168/e7ff563a-2a17-49e7-88d2-2e3bb8be6e14)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by harshsharma-11** [comment]
@vedant-jain03 @VaibhavUpreti please review the issue

**Comment by tanmoysrt** [comment]
Hi @harshsharma-11 
There is already a recent open issue #4114, for the same problem. 
Checkout #4114, If you feel the same, close the issue.
