### ISSUE TITLE
🐞 Bug : Alignment issues in the navbar of circuitverse Blog page

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/CircuitVerse#4152]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the responsive view the the navbar is not showing the expected alignment .

### Steps To Reproduce

- Visit Blog Page of circuit verse website 
- Open the responsive view ( width < 400 )

### Expected Behavior

Logo and the hamburger menu must be aligned in a row instead of a column 

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/7c5acb2a-6bb5-4527-af60-f806c26dd07b)

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser: Firefox
- version:
```

### Are you working on this issue?

Yes

**Comment by DhairyaMajmudar** [comment]
@VaibhavUpreti @vedant-jain03 @tanmoysrt  please review this issue and assign to me.

**Comment by tanmoysrt** [comment]
Raise the issue in blog repo here https://github.com/Circuitverse/blog

**Comment by DhairyaMajmudar** [comment]
> Raise the issue in blog repo here https://github.com/Circuitverse/blog
sorry I was not knowing that there a different repo for this website

**Comment by tanmoysrt** [comment]
> > Raise the issue in blog repo here https://github.com/Circuitverse/blog
> > sorry I was not knowing that there a different repo for this website

No problem, open the issue in  https://github.com/Circuitverse/blog repo. That will be fine
