### ISSUE TITLE
Feature : changing the Logo of Twitter with its new logo X

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/CircuitVerse#4153]
### Is your feature request related to a problem? Please describe

Changing the old logo of twitter ( bird ) to its new logo ( X ) in the footer section of the blog page 

### Describe the solution you'd like

I would like to solve this issue by replacing the old logo ( Bird ) with the new logo ( X ) of the twitter

### Additional context

**ScreenShot**
![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/690200e2-66b9-4deb-a23d-affd39e72378)

### Are you working on this?

Yes

**Comment by DhairyaMajmudar** [comment]
@VaibhavUpreti @vedant-jain03 @tanmoysrt  please review this issue and assign it to me .

**Comment by tanmoysrt** [comment]
@DhairyaMajmudar ig it's on the blog website? 

If yes, please raise the issue in blog's repository
Check here https://github.com/Circuitverse/blog

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar ig it's on the blog website?
> 
> If yes, please raise the issue in blog's repository Check here https://github.com/Circuitverse/blog

Yes , its on a different website

**Comment by tanmoysrt** [comment]
> > @DhairyaMajmudar ig it's on the blog website?
> > If yes, please raise the issue in blog's repository Check here https://github.com/Circuitverse/blog
> 
> Yes , its on a different website

Open this issue in this repo https://github.com/Circuitverse/blog
