### ISSUE TITLE
Integrate lookbook for view components

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#4167]
Refer: https://github.com/ViewComponent/lookbook

**Comment by YashGupt29** [comment]
can u elaborate more on this issue

**Comment by disha1202** [comment]
Hi @YashGupt29 
There are a few [view components](https://viewcomponent.org/) defined in the application. But we don't have any place to preview those components. You'll have to integrate https://github.com/ViewComponent/lookbook to achieve this.

**Comment by YashGupt29** [comment]
Ok I understood this issue I will try assign me this issue!

**Comment by shakthi2003-ice** [comment]
Hi @disha1202
Where should we integrate the lookbook in the application code?

**Comment by niladrix719** [comment]
@shakthi2003-ice we have to install it

**Comment by DhairyaMajmudar** [comment]
@niladrix719 @disha1202 Is there any documentation available from which we can refer how to integrate lookbook components

**Comment by niladrix719** [comment]
@DhairyaMajmudar https://lookbook.build/guide/installation

**Comment by niladrix719** [comment]
@YashGupt29 are you working on this?

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar https://lookbook.build/guide/installation

Thank you @niladrix719 for the docs. I went through them and understood the approach to implement the feature. can you pls. assign this issue to me.

**Comment by niladrix719** [comment]
if nobody is working on this you can go for it

**Comment by DhairyaMajmudar** [comment]
> if nobody is working on this you can go for it

Thank You 🙏

**Comment by shakthi2003-ice** [comment]
@DhairyaMajmudar  Extremely sorry but I am working on this issue

**Comment by DhairyaMajmudar** [comment]
> @DhairyaMajmudar Extremely sorry but I am working on this issue

@shakthi2003-ice can you pls. look for any other issue since I have almost completed the implementation.

**Comment by shakthi2003-ice** [comment]
> @shakthi2003-ice we have to install it

    @DhairyaMajmudar i am so sorry but i have been working for the past 2 days. Due to some installation issues I couldn't complete it early.

**Comment by DhairyaMajmudar** [comment]
> > @shakthi2003-ice we have to install it
> 
> ```
> @DhairyaMajmudar i am so sorry but i have been working for the past 2 days. Due to some installation issues I couldn't complete it early. 
> ```

Oh! Okayji no worries 🙂 
@niladrix719 can you pls. assign me an another issue in which I can contribute.

**Comment by shakthi2003-ice** [comment]
@niladrix719 hii
I have installed the lookbook but it is showing this error![IMG20231014132450.jpg](https://github.com/CircuitVerse/CircuitVerse/assets/132034882/2a8e789e-ddba-4906-8825-e7c5a6d69b32)

**Comment by niladrix719** [comment]
@shakthi2003-ice check for errors in routes.rb, you can also join our slack channel if you need more help

**Comment by shakthi2003-ice** [comment]
@disha1202 I have made the pull request can you please assign me this issue for the PR to get merged

**Comment by Karan-Palan** [comment]
If this issue is still open ,  I would like to work on it!

**Comment by rose2221** [comment]
is this issue still open?

**Comment by THARMATT** [comment]
Is this issue still open? I would like to work on it.
