### ISSUE TITLE
[🐞 Bug]: Under the footer section the social media icons->follow us on has rectangular box  which makes the icons unimpressive.

### ISSUE THREAD

**Issue by priyanshuxoxo** [CircuitVerse/CircuitVerse#4176]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Under the footer section, the social media icons->follow us on  has a black rectangular box shadow which make icons unimpressive also the footer section.

### Steps To Reproduce

Step 1: Go to  circuitverse.org.
Step 2: Scroll down to footer section.
Step 3: Under footer section the social media icons of follow us on has a rectangular black box( zoom on the icons little bit to get proper view).

### Expected Behavior

Solution: The icons of follow us on under the footer section should have no box shadow which will give the icons more impressive look as well as footer section.

### Screenshots

![Screenshot 2023-10-13 003911](https://github.com/CircuitVerse/CircuitVerse/assets/114825004/242dd12f-d729-4f32-9675-602f6d183128)

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser: Brave
- version:1.58.137
```

### Are you working on this issue?

Yes

**Comment by aditya123473892** [comment]
yes this issue exist can u assign me to work on this issue

**Comment by tanmoysrt** [comment]
The issue has been verified, @priyanshuxoxo you can work on this!

**Comment by priyanshuxoxo** [comment]
@tanmoysrt @vedant-jain03 can you please add hacktoberfest label ? so that it can be accepted in Hacktoberfest 2023.

**Comment by Malavi1** [comment]
this issue raised so many times and there are PRs under the review  #2825 #2590 #2570 #4133 #4156 #3689

**Comment by tanmoysrt** [comment]
If we make the box shadow color transparent, then ?

**Comment by Malavi1** [comment]
Yeah cool idea,
