### ISSUE TITLE
🐞 Bug: Sign In Button going out of view on resizing. 

### ISSUE THREAD

**Issue by theslowdeveloper** [CircuitVerse/CircuitVerse#4182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot from 2023-10-14 21-03-14](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/50af7626-5796-4481-925f-6d9b4f57c834)
![Screenshot from 2023-10-14 21-03-20](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/1ac676bf-d148-4445-a6bf-8854d7cc1605)

### Steps To Reproduce

1. Go To Circuitverse.org
2. Go to Simulator
3. Resize the window

### Expected Behavior

The Sign In Button should not go out of view 

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by shakthi2003-ice** [comment]
Can you assign me this issue?

**Comment by DhairyaMajmudar** [comment]
@Prerna-0202 ma'am pls. assign this issue to me .

**Comment by tanmoysrt** [comment]
This seem to be a duplicate issue of #4114.
