### ISSUE TITLE
Feature - Convert Subscribe/Unsubscribe link to button

### ISSUE THREAD

**Issue by theslowdeveloper** [CircuitVerse/CircuitVerse#4191]
### Is your feature request related to a problem? Please describe

The UI for Subscribe link doesn't match and look good 
![Screenshot from 2023-10-16 22-28-29](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/c8da7b98-954d-4cd5-9b43-3867ac8828d8)

### Describe the solution you'd like

I think this would look much better
![Screenshot from 2023-10-16 22-28-16](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/83b5c5b8-70c0-449a-a1b1-cc546315d775)

### Are you working on this?

Yes

**Comment by ishsarin** [comment]
Hi, if this issue is open, I'd like to contribute

**Comment by theslowdeveloper** [comment]
@tanmoysrt @vedant-jain03 can u review this ?

**Comment by tanmoysrt** [comment]
@theslowdeveloper you can work on this !
