### ISSUE TITLE
🐞 Bug Height of a Notification is not correct

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4199]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Height of Notification is not correct.

### Steps To Reproduce

1. Go to CircuitVerse.org
2. Click on notification's icon
3. See the error of incorrect height of notification.

### Expected Behavior

Height of Notification should be correct.

## Before:
![CV-fix-issue-noti-height-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/d40c7d8d-5851-42e1-b457-1b59458b9b48)

## After:

![CV-fix-issue-noti-height-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/fb69783e-54de-4009-9f7a-14d408bb1ee8)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by parthksingh1** [comment]
@shauryag2002 @vedant-jain03 please assign me this issue
