### ISSUE TITLE
7 Segment Decimal Point is hard to see

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#42]
The decimal point on the 7-Segment display is too close to the rest of the number and not defined enough, it is hard to see and easy to miss. Making it more separated from the other segments should fix this.

**Comment by satu0king** [comment]
![image](https://user-images.githubusercontent.com/2092958/48084570-17250b00-e21e-11e8-8afb-c14bfeda2587.png)
@blane1257 does this look alright?

**Comment by blane1257** [comment]
that looks much better, but i'd have to see it next to another display with some numbers on them and the decimal point on

**Comment by blane1257** [comment]
Alright, I will when I get the chance. Thanks for being so quick!

**Comment by satu0king** [comment]
I am closing this for now.
