### ISSUE TITLE
⭐️ Feature: Add a Model for the delete button in comments

### ISSUE THREAD

**Issue by theslowdeveloper** [CircuitVerse/CircuitVerse#4200]
### Is your feature request related to a problem? Please describe

Currently, when we click the delete button on a comment, it should shows a javascript confirm() box, we should upgrade it to a model instead.
![Screenshot from 2023-10-19 18-25-28](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/7c22563b-8406-4762-9860-c6f0a06a7004)

### Describe the solution you'd like

We should make the button click show a model just like the delete button on project.
![Screenshot from 2023-10-19 18-36-19](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/65450462-ce87-4750-8158-3631e761814d)

### Describe alternatives you've considered

We can also remove the confirm() box altogether and delete the comment without asking for confirmation. 

### Are you working on this?

Yes

**Comment by tenick** [comment]
Is this being worked on? I'm interested in contributing to this project

**Comment by Fareed95** [comment]
iam interested to resolve this isssue can you please assign to me this issue
