### ISSUE TITLE
🐞 Bug: Project utility button(edit, delete, embed) are not aligned properly 

### ISSUE THREAD

**Issue by theslowdeveloper** [CircuitVerse/CircuitVerse#4202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As you can see these buttons are not aligned vertically 
![Screenshot from 2023-10-19 20-20-06](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/1b2c8c8d-4fec-45d5-bb6b-fbb148e0ea65)

### Steps To Reproduce

1. Go To Circuitverse.org
2. Go to Simulator
3. Save Project Online
4. Go to Project
5. See the buttons are not aligned vertically 

### Expected Behavior

![Screenshot from 2023-10-19 20-19-31](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/8020e351-b957-4daa-999e-18fb738c5781)

The Buttons can be aligned vertically by adding the projects-primary-button
![image](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/3c1d698b-6c6f-4580-a162-c70610145b7f)
I think this class was primarily made to align the primary button but we can also use this class to align the secondary button as well, I also think we should change its name to something like projects-button-content-center 

### Device Information [optional]

```markdown
- OS: Linux Mint 21.2 x86_64
- Browser: Brave 
- version: 1.59.117
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
Hi @theslowdeveloper 
Issue verified and you can work on this!
Just want to say, while changing the CSS parameters, please check if the class has been used in any other place and make sure it's not effecting other parts of the project

**Comment by theslowdeveloper** [comment]
I don't think it is being used anywhere else, should i change the class name or add it as it is @tanmoysrt,
