### ISSUE TITLE
Navigating threads with search option

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4203]
### Is your feature request related to a problem? Please describe

navigating threads with search option is not available right now

![Screenshot 2023-10-19 at 11 57 09 PM](https://github.com/CircuitVerse/CircuitVerse/assets/91966855/4177a305-f433-4423-a7d6-e9102d5c73ba)

### Describe the solution you'd like

Having search functionality to search for threads just like other search functionalities

**Benefits:**

**1. users can conveniently search for keywords they are encountering.**

**2. improved accessibility of threads, ensuring that relevant discussions are readily available and easy to find.**

### Are you working on this?

Yes

**Comment by tanmoysrt** [comment]
Hi @niladrix719 , 
CircuitVerse uses `simple_discussion` for this community forum
I think you should check out this repository https://github.com/CircuitVerse/simple_discussion and raise the issue there.

**Comment by niladrix719** [comment]
sure
