### ISSUE TITLE
🐞 Bug : Placeholder is missing in login and signup page

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Login and Signup page , Placeholder is missing.

### Steps To Reproduce

1. Go to CircuitVerse.org
2. Click on Log in button 
3. See there is no place holder in input tags.

### Expected Behavior

Add placeholders for clear input identification in Login and Signup page.

## Before:
![CV-fix-issue-placeholder-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/aaa238c7-4704-4dfb-a727-ba3d3c8ed2c5)

## After:
![CV-fix-issue-placeholder-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/ae20399d-b0ca-495b-a151-40915be77f62)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by balkishan69** [comment]
hey @shauryag2002 , hope u are doing good, can u please assign me this issue so that i can contribute to it...

**Comment by parthksingh1** [comment]
@shauryag2002 @vedant-jain03 @tanmoysrt please assign me this issue

**Comment by shauryag2002** [comment]
@tanmoysrt I have no problem with assigning this issue to another contributor. Please feel free to do so.

**Comment by tanmoysrt** [comment]
> @tanmoysrt I have no problem with assigning this issue to another contributor. Please feel free to do so.

Thanks!

**Comment by tanmoysrt** [comment]
Hi @balkishan69 , you have been assigned this issue, you can start working on the issue and raise PR

**Comment by tanmoysrt** [comment]
As there is no PR activity for 1 month, unassigning @balkishan69

**Comment by jaydip1235** [comment]
Hi, Can I get this assigned ?

**Comment by tanmoysrt** [comment]
> Hi, Can I get this assigned ?

sure !
