### ISSUE TITLE
🐞 Bug :  Need Tooltip for Title and Fix Text Overflow in Simulator

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Need tooltip for _Big titles (Project Name)_  and the title are wrapping inside the width of projectName .
## ScreenShot of Problem:

![CV-fix-issue-tooltip-before-photo](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/52e40160-317d-4ff3-9933-f20da175490f)

### Steps To Reproduce

1. Go to circuitverse.org
2. Click on Simulator
3. Enter Some big name in Project:  section

See the error of Overflowing text
And Need Tooltip for Seeing Big project name.

### Expected Behavior

Fix the Project name by text-overflow and add tooltip

## Before:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/6c64df0f-5274-4262-bfc4-4ba3a8234f63

## After:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/e4adabff-e165-45df-a191-12b242c9aed9

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by test1883** [comment]
@shauryag2002 heyy, can I work on this?

**Comment by tanmoysrt** [comment]
Hi @shauryag2002 
This issue has been verified and you can raise the PR for this
