### ISSUE TITLE
🐞 Bug : Wrong alignment of tooltip

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4209]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Alignment of tooltip is left side instead of center.
## Video of Bug:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/baf2d473-0e43-4dbc-9ec4-f1d1418d154b

### Steps To Reproduce

1. Go to [https://circuitverse.org/](https://circuitverse.org/) .
2. After Signup, click on dashboard under your username.
3. hover on any circuit name , You created or forked.
_See the bug that tool tip is in left ._

### Expected Behavior

The Tooltip should be in center as Circuit name is also center.
## Video of Solution:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/b64e7a89-2ab5-4efd-9aa5-5422614fc8e5

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
Hi @shauryag2002 issue verified and assigned to you
