### ISSUE TITLE
label duplication when dragging the next element after labelling an element

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we label an element and try dragging another element just after that, the label gets duplicated onto the new element.

### Steps To Reproduce

1. go to https://circuitverse.org/simulator
2. drag any element and label it
3. drag another element just after that
4. see error

### Expected Behavior

The label should not be duplicated, as it represents an individual element.

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/768b2e7d-d008-4638-8785-bb730727c01c

### Device Information [optional]

```markdown
- OS: MacOs
- Browser: Safari
- version: 17.1
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
@niladrix719 
The issue has been verified!
