### ISSUE TITLE
bug: the alignment of some element labels is not correct

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I have checked all the elements with all directions of labels but only these 4 elements seems to have not proper alignment:

1. Variable LED
2. Digital LED
3. RBG LED
4. Priority Encoder

![Screenshot 2023-11-14 at 9 44 53 PM](https://github.com/CircuitVerse/CircuitVerse/assets/91966855/01eca20f-3121-4c87-b26c-2bc623a97007)

### Steps To Reproduce

1. go to https://circuitverse.org/simulator
2. drag any element within these 4
3. add labels and check for all direction
4. see error

### Expected Behavior

The labels should be proper and visible in any direction

### Device Information [optional]

```markdown
- OS: MacOs
- Browser: Safari
- version: 17.1
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
@Prerna-0202 @Arnabdaz can you review this issue pls .

**Comment by tanmoysrt** [comment]
@niladrix719 as the `pending triage` has been removed, I have assigned you and you can raise the PR now.
