### ISSUE TITLE
🐞 Bug : Fix alignment of user's circuit navbar

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4224]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Incorrect alignment of users-circuit-navbar which causes overflow of elements in small screens.
### Screenshot of bug :
![CV-fix-issue-revamp-user-circuit-navbar-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/86aaa3c9-b57b-4d74-a148-09aff496f235)

### Steps To Reproduce

1. Go to [https://circuitverse.org/](https://circuitverse.org/) .
2. Open your dashboard .
3. Navigate to small screen
_**See the incorrect alignment of `users-circuit-navbar`**_

### Expected Behavior

Users navbar should be correctly align .
### Screenshot of solution :
![CV-fix-issue-revamp-user-circuit-navbar-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/66ccf5ff-f33a-49c5-824d-74ddef19211e)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by nisha-laur** [comment]
Hi, if this issue is still open . I would like to work on this . If you could assign this to me .

**Comment by DhairyaMajmudar** [comment]
@tanmoysrt @vedant-jain03 I would like to work on this issue pls. assign this to me.

**Comment by tanmoysrt** [comment]
Hi @shauryag2002 this issue was recently raised and fixed already. Ref PR #4121 
For that reason, closing this issue.
