### ISSUE TITLE
⭐️ Feature : Implement Copy Link button at "Embed Your Circuit" section

### ISSUE THREAD

**Issue by Keshav-0907** [CircuitVerse/CircuitVerse#4225]
### Is your feature request related to a problem? Please describe

Adding the copy link functionality for a better user experience. 

<img width="1440" alt="Screenshot 2023-10-26 at 10 00 17 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/91189139/af2a71be-e5a3-4f8a-ae18-fc6166270428">

### Describe the solution you'd like

- A copy button that will copy the link to user's clipboard
- A "Copied" Success message 

Here is a very basic figma mockup of the solution 
![Frame 1171275816](https://github.com/CircuitVerse/CircuitVerse/assets/91189139/66403439-d0de-4db1-b94e-29e5527fa6e4)

### Are you working on this?

Yes

**Comment by Keshav-0907** [comment]
@tachyons @Arnabdaz

**Comment by DhruvGupta3377** [comment]
Hello!
Can i work on this issue?

**Comment by Fareed95** [comment]
Is this issue is still open.... if then please give me a chance to resolve it

**Comment by tanmoysrt** [comment]
Hi @Keshav-0907 
The main goal of the modal is to generate the `iframe` codes for embedding, it's not for sharing the circuit URL. So I don't think it's good UX to have another action button in the modal
