### ISSUE TITLE
⭐️ Feature : Add Color Picker for border color

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4227]
### Is your feature request related to a problem? Please describe

It is hard to first pick a good color and place it in input box.

### Describe the solution you'd like

Easier option is to provide a color picker to navigate between colors and choose a great color.
### Video of Solution :
https://github.com/CircuitVerse/CircuitVerse/assets/77102885/15e1fadc-7b85-4b2d-acf4-dc3083427bee

### Are you working on this?

Yes

**Comment by Simer13** [comment]
hello can i work on this issue ?

**Comment by tanmoysrt** [comment]
Hi @shauryag2002 , the issue seems to be valid, and solution looks good. You can raise the PR
