### ISSUE TITLE
🐞 Bug : Pagination Width overflow 

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4234]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Pagination (page numbers) is causing website unresponsiveness.
### Video of bug:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/0136c7cc-d245-49c8-8295-7c962ee73e74

### Steps To Reproduce

1. Go to [https://circuitverse.org/](https://circuitverse.org/) .
2. Search any circuit name. (ex- [Link](https://circuitverse.org/search?button=Submit&page=1&q=jk&resource=Projects) ) .
3. Convert website to small screen.
4. Navigate to bottom.
_**The pagination menu is overflowing, causing the website to become distorted.**_

### Expected Behavior

Pagination class should add `overflow-x: auto;` .
### Video of Solution: 

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/ea43418e-1ed7-4ddf-af80-7f05978a8169

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by rajesh604** [comment]
Hi @shauryag2002 are you working on this issue. If not can you assign this issue to me

**Comment by shauryag2002** [comment]
Hi @rajesh604 , I am waiting for `pending triage` , Then I will start working on this issue.

**Comment by rajesh604** [comment]
I have actually completed the task

**Comment by tanmoysrt** [comment]
> I have actually completed the task

Understood that. But we assign as per FIFO. But it's  also not recommended to raise the PR without getting assigned to one issue. That's why, you may haven't found any linked PR for this issue, have confused a little bit.

Search another issue or raise a issue to get assigned to that.

**Comment by shauryag2002** [comment]
#4131 addresses this issue, closing as completed.
