### ISSUE TITLE
🐞 Bug: improve error handling for project name and circuit name to improve user experience

### ISSUE THREAD

**Issue by senbo1** [CircuitVerse/CircuitVerse#4235]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

A user can add very long title with no boundries(in the example below I pasted a wikipedia article) in input fields and saving the project leads to a 500 server error.
Simulator
![Screenshot from 2023-10-31 19-50-02](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/68c783e4-41d8-475e-a6fc-5f9afdfc3a59)

Form 
![Screenshot from 2023-10-31 20-05-44](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/52663dd5-24b9-466d-89e2-2148fcdb3f6e)

Error
In Production
![Screenshot from 2023-10-31 19-48-38](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/bfde059d-f7a1-474b-9542-2cda53ab7831)
An ambiguous error is thrown

Local Development
![Screenshot from 2023-10-31 20-06-55](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/e9a5c270-bfbc-4479-bb1d-add9124c589f)

### Steps To Reproduce

1. Go to circuitverse.org
2. Open up Simulator
3. Add a very long title
4. Save Project
5. Fill other fields as well with long titles 

### Expected Behavior

We should provide error above or below the input to let user know that they have exceeded the maximum limit!

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Chirag-Nanda** [comment]
Can I work on this issue?

**Comment by tanmoysrt** [comment]
The issue has been verified !
@theslowdeveloper you can start working.

Try to enforce this on both client and server side.
On client side , try to use maxlength attribute -> ref https://www.w3schools.com/tags/att_input_maxlength.asp
On server side, you can raise error above a specific length.

**Comment by theslowdeveloper** [comment]
@tanmoysrt Thank you!, I will start on the working on the issues one by one.

**Comment by shauryag2002** [comment]
Hi @theslowdeveloper, if you're not actively working on this issue, I'd like to contribute. 
@tanmoysrt @vedant-jain03 @Prerna-0202, can I take over this issue?
#### Video without `maxlength="50"` :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/baaa8223-46fa-4789-b32f-a4c54569df85
#### Video with `maxlength="50"` :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/2741d94e-e08f-4a14-a58f-7abbe2fa96be

**Comment by theslowdeveloper** [comment]
sorry but I was busy working on other issues and as well as college exam and now I am free to work on this issue, besides max length, I think we also need show some message displaying the limit is reached, as well as protect the api route better. I would very much want to work on this.

**Comment by tanmoysrt** [comment]
Rollback the limitation of size from bacekdn, as it can cause issues to LMS integration / pre-exisiting project
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/48e19802-f58d-446a-9a83-4f6ef68f50a1)
