### ISSUE TITLE
Feature: disable signup

### ISSUE THREAD

**Issue by TobiasKappe** [CircuitVerse/CircuitVerse#4236]
### Is your feature request related to a problem? Please describe

I am trying to deploy CircuitVerse within my university for a course. The local IT people would prefer that we limit account creation to comply with our security policy.

### Describe the solution you'd like

It would be nice if there was some way for the administrator of a CircuitVerse instance to disable signup, i.e., to prevent new users from registering an account. This could happen either via setting or a switch on the admin panel.

### Describe alternatives you've considered

I considered integrating with my university's SAML provider, and still intend to do this in the long run. Going by the interaction I had on Slack, however, that still requires a different change on your end. For now, disabling registration is enough for me.

### Are you working on this?

No

**Comment by Chirag-Nanda** [comment]
Can I work on this issue @TobiasKappe ?

**Comment by niladrix719** [comment]
@tachyons Within the /config folder, we can introduce `config.allow_user_signup = true`. This configuration setting will be utilized during the sign-up process to enable or restrict user registration as necessary. Additionally, we will incorporate a toggle button in the user admin dashboard, allowing administrators to modify this setting, i can work on this, do you have any alternative approaches in mind? What do you think?

**Comment by tachyons** [comment]
@niladrix719 But it will difficult to toggle. We can use feature flag using flipper https://github.com/flippercloud/flipper. We already have toggle for project comments, recaptcha, LTI etc. We can add toggle for user_signup too

**Comment by niladrix719** [comment]
@tachyons ok i can implement it that way, should i go for it

**Comment by tachyons** [comment]
Hi @Chirag-Nanda Sorry, assigning this issue to @niladrix719 as issue require some understanding about the GitLab code base, not a good candidate for first issue to work on. Thanks for your willingness to help.

**Comment by Chirag-Nanda** [comment]
No problem. I will try to understand the codebase first, hope to find some suitable features I can add on or issues I can solve
