### ISSUE TITLE
🐞 Bug : Alignment of Remember me and forget password is incorrect in login page.

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4237]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Alignment of Remember me and forget password is incorrect in login page.

### Steps To Reproduce

1. Go to [Sign in page](https://circuitverse.org/users/sign_in) .
_**See the error that Alignment of Remember me and forget password is incorrect**_

### Expected Behavior

Remember me and forget password should be in same line.

### Actual Behaviour :
![CV-fix-issue-login-alignment-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/f9719780-75ef-4100-89e6-29483da15418)

### Expected Behaviour :

![CV-fix-issue-login-alignment-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/408203b4-170b-4dc1-9f22-3163ed6fef3a)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Chirag-Nanda** [comment]
Can I work on this issue?

**Comment by parthksingh1** [comment]
@shauryag2002 @vedant-jain03 @tanmoysrt please assign me this issue

**Comment by rajesh604** [comment]
Hello I have created the pull request to it please check it

**Comment by rajesh604** [comment]
my pull request https://github.com/CircuitVerse/CircuitVerse/pull/4240

**Comment by rajesh604** [comment]
The changes I have made

https://github.com/CircuitVerse/CircuitVerse/assets/77529419/a0038411-bc63-471b-bcee-a8e5c919b779

**Comment by rajesh604** [comment]
@shauryag2002  I have solved the issue and created a pull can you look at it

**Comment by rajesh604** [comment]
@tanmoysrt but I have already solved the issue

**Comment by tanmoysrt** [comment]
> @tanmoysrt but I have already solved the issue

Normally we assign based on FIFO. The issue author has already marked that he is working on the issue. 
btw if @shauryag2002 like to pass it, then I can assign another one

**Comment by rajesh604** [comment]
okay
