### ISSUE TITLE
Commentator mails failing

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#424]
Mails are created when a user comments on a subscribed mail thread. However the mails are failing due to this error. 

```
NoMethodError: undefined method `project_url' for #<ActionDispatch::Routing::RoutesProxy:0x00000000059d7268>
```

**To Reproduce**
1. Create a project
2. Add a comment (this will subscribe user1)
3. Sign in as another user (user2)
4. Create another comment on the same project (user1 should get email)
5. Run sidekiq in the background 

**Expected behavior**
An email is received

**Additional context**
`project_url` method doesn't exist. Instead `user_project_url` exists. A fix would be to define `project_url` in terms of `user_project_url`. 

**Are you working on this issue? (Yes/No)**
No

**Comment by ankitkataria** [comment]
Looked into this for quite some time. 

#### Probable solution
`./app/config/commontator.rb`
```ruby
config.comment_url_proc = ->(comment, app_routes) {
    if comment.thread.commontable.class.name == "Project"
      project = comment.thread.commontable
      author = project.author
      return "/users/#{author.id}/projects/#{project.id}#comment_#{comment.id}_div"
    else
      return app_routes.polymorphic_url(comment.thread.commontable, anchor: "comment_#{comment.id}_div")
    end
  }
```

Reference: https://github.com/lml/commontator/issues/119

Then inside rails console
```ruby
Commontator.comment_url(Commontator::Comment.find(183), ActionDispatch::Routing::PolymorphicRoutes)

"/users/6874/projects/19246#comment_183_div"
```

But, initial testing still showed the same error in sidekiq
Looking more into this. 

More references:
- [Polymorphic routes](https://apidock.com/rails/ActionDispatch/Routing/PolymorphicRoutes)

**Comment by satu0king** [comment]
@ankitkataria sidekiq runs independently of the rails server. So you will have to kill and restart the sidekiq process to test.
