### ISSUE TITLE
Feature: Next and Previous Buttons can also be configured to redirect to the recent circuit section

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4248]
### Is your feature request related to a problem? Please describe

Currently, the Next and Previous buttons redirect to the header section, which is inconvenient for navigation, unlike the other page number buttons that appear to function correctly.

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/54c1ca49-3fb8-4f27-a21b-e84f0b29ec82

### Describe the solution you'd like

I would like the Next and Previous buttons to be configured to redirect to the most recent circuit section, similar to how the other page number buttons currently function.

### Are you working on this?

Yes

**Comment by rajesh604** [comment]
hi @niladrix719 @tanmoysrt can you assign me this issue

**Comment by tanmoysrt** [comment]
Hi @niladrix719 
Issue verified , go ahead :+1:
