### ISSUE TITLE
Enhancing User Experience: Auto-Focusing on the Search Bar with Dynamic Placeholder Text Based on User's Selection

### ISSUE THREAD

**Issue by rajesh604** [CircuitVerse/CircuitVerse#4249]
### Is your feature request related to a problem? Please describe

On the Circuitverse homepage, there's a search icon that, when clicked, reveals a search bar with options to select users and projects. However, I've noticed that the focus doesn't automatically shift to the search bar when it's revealed, and the placeholder text doesn't accurately describe what should be input. I'd like to suggest making improvements to address these issues.

https://github.com/CircuitVerse/CircuitVerse/assets/77529419/3480f474-e23d-421f-9744-6c324f3ccd03

### Describe the solution you'd like

When i click on search icon my focus or text cursor should be in the search bar and if i select user option the placeholder should show "search for users here" and similarly for the projects.

### Are you working on this?

Yes

**Comment by shauryag2002** [comment]
Hi @rajesh604, I believe #4023 addresses this issue.

**Comment by rajesh604** [comment]
okay

**Comment by tanmoysrt** [comment]
As it's a duplicate  issue of #4023, closing this issue.

But @rajesh604 , you can raise a issue maybe on this -
When `users` option is selected, show `Search user by name`  in the placeholder
When `projects` option selected, show `Search project by name or description` in placeholder

You can give a better suggestion for placeholder text as well.
