### ISSUE TITLE
Admin: Send Custom Mail Preview to Self 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#425]
When admin creates a mail and would like to send it, it would be nicer if we could test send a mail to admin first. This is necessary because sometimes mails turn out unexpected and doesn't match the preview mail shown. 

**Describe the solution you'd like**
Along with **edit** and **send**, a **send to self** option is desirable. 
page: `http://localhost:3000/custom_mails/1` 
![image](https://user-images.githubusercontent.com/2092958/62422279-73458e80-b6cd-11e9-9243-2e8341e45ef1.png)

**Are you working on this? (Yes/No)**
No

**Comment by shubhankarsharma00** [comment]
I think adding a button Send to self 
https://github.com/CircuitVerse/CircuitVerse/blob/2898a70401ae1d7521a9e8c51347ec9710a74bdf/app/views/custom_mails/show.html.erb#L5
and adding a simple user_mailer to self can do the trick
