### ISSUE TITLE
Enhancing User Experience by Equalizing Button Sizes

### ISSUE THREAD

**Issue by rajesh604** [CircuitVerse/CircuitVerse#4250]
### Is your feature request related to a problem? Please describe

I have that both the for teachers and for contributors button in home page is not of same size due to which when the screen is small the buttons does not look good.

![Screenshot 2023-11-04 170431](https://github.com/CircuitVerse/CircuitVerse/assets/77529419/ddfef239-9eaf-4d18-97a3-313fa84221fd)

### Describe the solution you'd like

I want to make both the buttons of same size and add responsiveness to them

### Are you working on this?

Yes

**Comment by rajesh604** [comment]
should i continue to work on this issue can you please respond ?

**Comment by niladrix719** [comment]
Hi @rajesh604 , it would be best to wait for the maintainers to review it first. After they have reviewed it, they will assign you to this issue, and then you can start working on it and link a pull request to it

**Comment by rajesh604** [comment]
okay

**Comment by maheshkakad9** [comment]
should i work on this issue?

**Comment by tanmoysrt** [comment]
Hi @rajesh604, thanks for opening the issue
This seems to be a duplicate issue of #4110
And there is already approved PR for that

So, closing this PR

btw I have mentioned an issue here, #4249, you can raise one on that
