### ISSUE TITLE
🐞 Bug: Alignment of Navigation bar is incorrect in login page.

### ISSUE THREAD

**Issue by Rahulr2101** [CircuitVerse/CircuitVerse#4252]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The navigation bar alignment on the login page for the Galaxy Fold device appears to be distorted or misaligned.

### Steps To Reproduce

1. Go to [login page](https://circuitverse.org/users/sign_in)

### Actual Behavior: 

![current](https://github.com/CircuitVerse/CircuitVerse/assets/117565630/d35bd8c9-7c6c-4628-997f-02aa0cae9e1e)

### Expected Behavior: 

![Execpted](https://github.com/CircuitVerse/CircuitVerse/assets/117565630/a652654f-7082-4613-94fd-55044113c8cf)

### Device Information [optional]

```markdown
- OS: Android
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

**Comment by Ansh101112** [comment]
working on this issue will submit a PR asap.

**Comment by tanmoysrt** [comment]
Issue verified.
Go ahead @Rahulr2101

**Comment by SamsShow** [comment]
@tanmoysrt it's been a week with no PR on this issue. I would like to work on it

**Comment by tanmoysrt** [comment]
@Rahulr2101 can you provide a update please

**Comment by tanmoysrt** [comment]
@SamsShow you have been assigned the issue !
Go ahead

**Comment by SamsShow** [comment]
> @SamsShow you have been assigned the issue ! Go ahead

Please review the PR
