### ISSUE TITLE
🐞 Bug : Alignment of Comment and Subscribe Button is not correct

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4255]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Alignment of Comment and Subscribe Button in comment section is not correct  .

### Steps To Reproduce

1. Go to [https://circuitverse.org/](https://circuitverse.org/) .
2. Then , go to any circuit view page .
3. Scroll to comment section.
**_See the bug that Comment section heading and Subscribe button is not align correctly._**

### Expected Behavior

The comment section heading and subscribe button should be in same line.

### Bug :
![CV-fix-issue-align-comment-subscribe-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/3130f85c-c68d-4b45-a74b-d686c5477305)

### Solution :
![CV-fix-issue-align-comment-subscribe-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/0da11c99-9468-4284-947e-917aa9f06d2d)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by maheshkakad9** [comment]
can i work on this issue?

**Comment by SamsShow** [comment]
I would like to work on this issue

**Comment by tanmoysrt** [comment]
Issue verified
Go ahead @shauryag2002
