### ISSUE TITLE
🐞 Bug: The "Add member" button remains disabled even after entering an email address

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4256]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we enter an email address and select it, the "Add member" button remains disabled. It only becomes enabled after we refocus on the input field.

### Steps To Reproduce

1. go to https://circuitverse.org
2. go to my groups and view any group
3. Try to add a member
4. enter and select a email address
5. you will see that the "Add member" button is still diabled

### Expected Behavior

The "Add member" button should enable upon entering a email address in the input field

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/81b3de0c-22ef-4c58-888d-bc5d84932468

### Device Information [optional]

```markdown
- OS: MacOs
- Browser: Safari
- version: 17.1
```

### Are you working on this issue?

Yes

**Comment by ansh343** [comment]
I would like to work on this issue . Can you assign it to me ?

**Comment by Ansh101112** [comment]
Will submit the PR asap.

**Comment by niladrix719** [comment]
hi @Ansh101112 no its fine i will do it once its approved

**Comment by tanmoysrt** [comment]
Issue verified.
@niladrix719, you can raise the PR
