### ISSUE TITLE
🐞 Bug : Width of Notification overflows in small screens

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4260]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Width of Notification overflows in small screens .
### Video of Bug :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/e57d1b6f-bd8d-47ec-885a-31fcdab2f550

### Steps To Reproduce

1. Go to [https://circuitverse.org/](https://circuitverse.org/) .
2. After Login , Click on Notification icon.
3. Convert website view to small screen.
**_See the bug that Notification is overflowing_**

### Expected Behavior

The width of the notification should not overflow.
### Video of Solution :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/b9188492-ddf9-4a7d-b3f8-a7b82f3f9a80

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Sejal1411** [comment]
I would like to work on this issue. Pls assign!

**Comment by tanmoysrt** [comment]
Issue verified 
@shauryag2002 go ahead
