### ISSUE TITLE
🐞 Bug: input fields UI breaks when an error alert is shown

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 input fields UI breaks when an error alert is shown

### Steps To Reproduce

1. go to https://circuitverse.org/users/sign_up
2. click signup with blank input fields
3. see error

### Expected Behavior

Input fields should remain visually and functionally intact when an error alert is displayed, ensuring a smooth user experience.

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/56660dbd-2d78-429b-bae4-6c541f92c01c

### Device Information [optional]

```markdown
- OS: MacOs
- Browser: Safari
- version: 17.1
```

### Are you working on this issue?

Yes

**Comment by Chadokar** [comment]
Hi, I want to solve this issue. Can you please assign it to me?

**Comment by tanmoysrt** [comment]
Issue verified :+1:

**Comment by tanmoysrt** [comment]
@ niladrix719 you have been assigned couple of issues; can I assign this to another contributor for the first contribution?

**Comment by tanmoysrt** [comment]
@ niladrix719 you have been assigned couple of issues; if you don't mind can I assign this to another contributor for the first contribution?

**Comment by niladrix719** [comment]
@tanmoysrt sure

**Comment by tanmoysrt** [comment]
@Chadokar go ahead

**Comment by Chadokar** [comment]
thanks @tanmoysrt

**Comment by SwetanshuSingh** [comment]
@tanmoysrt I would love to work on this issue, If it is still open.

**Comment by niladrix719** [comment]
@Chadokar are you still working on it?

**Comment by shauryag2002** [comment]
Hi @tanmoysrt @Prerna-0202 @vedant-jain03 , Can i work on this issue?
### Video of Solution :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/b0b13b90-46b9-4a1a-9220-cdcbad302f45

**Comment by jaydip1235** [comment]
https://github.com/CircuitVerse/CircuitVerse/assets/65560026/598351f4-f79c-4e74-ac20-8b3dd9eab29f

**Comment by tanmoysrt** [comment]
@Chadokar, as there is no response, you have been unassigned
As a first-time contributor, @jaydip1235, you have been assigned the issue. You can raise the PR
