### ISSUE TITLE
Pagination Misalignment &  Responsiveness

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

User search pagination misalignment & it was not responsive 

### Steps To Reproduce

click on search
select users
scroll down to the pagination

### Expected Behavior

fix alignment & responsiveness

### Screenshots

![Screenshot 2023-11-10 124133](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/b0c982f4-ab42-4951-9bbe-e5eca2ffcd0f)

![Screenshot 2023-11-10 131024](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/17c15141-10c5-43f4-baee-4272c08ddb12)

### Device Information [optional]

```markdown
- OS:Windows
- Browser: firefox
- version:119.0.1
```

### Are you working on this issue?

Yes

**Comment by shauryag2002** [comment]
Hi @Malavi1 , I believe #4234 addresses this issue .

**Comment by Malavi1** [comment]
Yeah @shauryag2002  I overlooked IG!
So, While fixing the issue consider centring the pagination in the laptop screen size meanwhile it also fixes.

**Comment by Uddancode** [comment]
Hey, I would like to work on this issue, pls assign this issue @Malavi1
