### ISSUE TITLE
⭐️Feature : Dynamic Placeholder of Search

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4272]
### Is your feature request related to a problem? Please describe

This feature enhances user experience by dynamically updating the search input placeholder based on user selections.
 It aims to provide more context-sensitive and intuitive search suggestions, improving the overall usability of the search functionality.

### Video of Solution :
https://github.com/CircuitVerse/CircuitVerse/assets/77102885/711754d8-ca61-475e-a807-1b8dfa269b40

### Describe alternatives you've considered

NA

### Additional context

NA

### Are you working on this?

Yes

**Comment by tanmoysrt** [comment]
@shauryag2002 Go ahead !
