### ISSUE TITLE
Blog page search bar styling

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4275]
### Currently the blog page search bar is empty with no styling.

![Screenshot 2023-11-14 200408](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/c8ad85ad-4104-4ede-b0c1-c7fce3110869)

### Styling the search bar as the one we have in the main page increases the UX & flow would be good

![Screenshot 2023-11-14 202129](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/fb4991b6-075e-4010-9f6e-1946f7f7b9a3)

### Are you working on this?

Yes

**Comment by yogeshsshekhawat** [comment]
@Malavi1   yes i thing so it should be style

**Comment by Shubham071122** [comment]
Hey, @Malavi1 is this issue still open .  i wana  work on this.

**Comment by tanmoysrt** [comment]
@Malavi1 open this issue in this repo > https://github.com/CircuitVerse/blog
Closing this issue here!
