### ISSUE TITLE
Remove Display of Collaborator Emails

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#428]
Example: https://circuitverse.org/users/2484/projects/11615

![image](https://user-images.githubusercontent.com/2092958/62945204-f1a3de00-bdfb-11e9-96dd-d76cd56300ec.png)

Please display collaborator email only if the current user is the owner of the project otherwise only show name.

**Comment by Sahaj8** [comment]
Can I work on this issue??

**Comment by satu0king** [comment]
Sure @Sahaj8 go ahead!

**Comment by ankitkataria** [comment]
Fixed with #430
