### ISSUE TITLE
make registration-block alert texts i18n compatible

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4280]
### Is your feature request related to a problem? Please describe

registration-block alert texts are not currently i18n compatible
![Screenshot 2023-11-15 at 4 39 22 PM](https://github.com/CircuitVerse/CircuitVerse/assets/91966855/b52f1bc2-fe05-4d64-b8bc-e95e8c332103)

### Describe the solution you'd like

We need to translate registration block alert texts into all available languages
ref PR - https://github.com/CircuitVerse/CircuitVerse/pull/4124

### Are you working on this?

No

**Comment by Malavi1** [comment]
Can I work on this?

**Comment by niladrix719** [comment]
@Malavi1 sure

**Comment by Malavi1** [comment]
Hey @niladrix719 I am understanding the issue in different ways could you please reframe the issue again what are you supposed to change in that way I will understand IG!!

**Comment by niladrix719** [comment]
"Sign up is Currently disabled" this text is not being translated to all languages, which was a follow up issue for this: https://github.com/CircuitVerse/CircuitVerse/pull/4257#discussion_r1393805118
