### ISSUE TITLE
🐞 Bug : Overflow Issue with Group Name Heading on Large Names

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4281]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Group name Heading overflows device screen when huge names enter

### Video of Bug :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/216895fc-9b26-4560-8506-079503eff1b4

### Steps To Reproduce

1. Go to "My Groups" after log in.
2. Enter a Huge name .
_**See the error that group name is exceeding the screens width**_

### Expected Behavior

There should be a `width: 100%` and `overflow: hidden` .
And There should be tooltip for full name visibility.
### Video of Solution :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/3307b486-5e07-48fa-b24e-17068de7da58

### Screenshots

NA

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

NA

### Are you working on this issue?

Yes

**Comment by Jayendra-Welekar** [comment]
@shauryag2002 can i get assigned to this issue

**Comment by tanmoysrt** [comment]
@shauryag2002 
Issue verified and assigned!
