### ISSUE TITLE
🐞 Bug : Edit profile details error not displaying.

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When symbols are entered in the name, it's considered invalid. Submitting results in page refresh without updating details.
### Video of Bug :

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/2ccc66b4-7beb-40e7-bc0d-6e3e1d19e3d3

### Steps To Reproduce

1. Go to [https://circuitverse.org/](https://circuitverse.org/) .
2. After log in , Go to dashboard and then Edit Details
3. Enter Symbols to name like **#@!**
4. Save the Details
_**See the Page refreshes but the error not displayed.**_

### Expected Behavior

It should display the errors .
### Video of Solution :
https://github.com/CircuitVerse/CircuitVerse/assets/77102885/ee6baaf2-fbf5-49b7-b355-c03198affb13

### Screenshots

NA

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

NA

### Are you working on this issue?

Yes

**Comment by nithinkatta** [comment]
I would like to contribute to this issue. Please assign me

**Comment by tanmoysrt** [comment]
@shauryag2002 Issue verified!
Go ahead :+1:
