### ISSUE TITLE
🐞 Bug : Error message CSS not applied in Edit Project.

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The CSS of the error message is not applied in Edit Project.

### Screenshot of Bug :

![CV-fix-issue-error-message-css-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/39ac0209-fa18-4ef9-b5ec-60ced282279a)

### Steps To Reproduce

1. Go to [https://circuitverse.org/simulator](https://circuitverse.org/simulator) and save the project.
2. In Edit Project page, clear the project name input .
3. Click Update Project button .
**_See the error: Error message lacks CSS._**

### Expected Behavior

The error message should have CSS applied.

### Screenshot of Solution :

![CV-fix-issue-error-message-css-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/2989c66d-0cd2-447d-bcc7-352d864b84d7)

### Screenshots

NA

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
@shauryag2002 Issue Verified & Assigned !
Make sure to keep the notification content properly centered vertically.
In the solution, their was more padding at bottom than top of the error message
