### ISSUE TITLE
🐞 Bug : Sign Up form is not proper when the input field/s is/are invalid/blank

### ISSUE THREAD

**Issue by jaydip1235** [CircuitVerse/CircuitVerse#4292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Sign Up form UI is not proper when the form is attempted to submit without one or more input fields

### Steps To Reproduce

1. Go to 'https://circuitverse.netlify.app'
2. Click on Log in in the Navbar
3. Click on Sign up
4. Click on Sign Up button without entering one or more fields

### Expected Behavior

<img width="1727" alt="Screenshot 2023-11-20 at 10 42 51 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/65560026/0df17808-304c-43ed-8052-610a48696016">

### Screenshots

<img width="1531" alt="Screenshot 2023-11-20 at 3 54 07 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/65560026/e3e79787-2391-46af-9a14-c429e12527ca">

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by niladrix719** [comment]
its a duplicate #4261

**Comment by tanmoysrt** [comment]
As you have been assigned to #4261, closing this issue
