### ISSUE TITLE
🐞 Bug: Search bar overlaps with user-detail-container

### ISSUE THREAD

**Issue by hrshkshri** [CircuitVerse/CircuitVerse#4297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we try to search on the dashboard, the search bar overlaps with the user details container...
Adding a video for the same.

https://github.com/CircuitVerse/CircuitVerse/assets/108923011/db4ca82a-63c7-4209-8aa9-4eacfa36af97

### Steps To Reproduce

1. Go to the user Dashboard.
2. try searching 
3. see the issue

### Expected Behavior

There should be proper space between the search bar and the user container
![Screenshot 2023-11-21 at 3 19 01 PM](https://github.com/CircuitVerse/CircuitVerse/assets/108923011/3aeac88f-6ea5-410a-b3a6-8bdacaf39cca)

### Device Information [optional]

```markdown
- OS: MacOS
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

**Comment by hrshkshri** [comment]
Please justify if this is the intended behaviour of the search bar because the same persists with the home page too.

**Comment by Jayendra-Welekar** [comment]
i would like to work on this issue

**Comment by tanmoysrt** [comment]
> @hrshkshri I have already solved this issue in #4312 , You can checkout the PR for reference.

The changes will  not work, we need to make sure there is no extra padding while the search bar is not there, and we can't change the padding of each page. We need to manage somehow it in navbar section or in the search bar's own container

**Comment by hrshkshri** [comment]
> @hrshkshri Whatever is there on the video, it's the current expecting behaviour. But we can modify that like - if we expand that portion it should add a padding, so that the content doesn't get hidden,
> 
> Currently, the search container is a container with `position:fixed`, so if you can modify the behaviour it will be a better design.

Hey @tanmoysrt 
The issue is because of `position:fixed` giving `position: fixed` is doing the job fine.


https://github.com/CircuitVerse/CircuitVerse/assets/108923011/997887a4-eac5-4f85-9d3d-3d8588428215

**Comment by tanmoysrt** [comment]
> > @hrshkshri Whatever is there on the video, it's the current expecting behaviour. But we can modify that like - if we expand that portion it should add a padding, so that the content doesn't get hidden,
> > Currently, the search container is a container with `position:fixed`, so if you can modify the behaviour it will be a better design.
> 
> Hey @tanmoysrt The issue is because of `position:fixed` giving `position: fixed` is doing the job fine.
> 
>  Screen.Recording.2023-12-09.at.3.53.33.PM.mov

Looks fine ! Raise the PR. Will review once the CI fix
