### ISSUE TITLE
Not redirecting to home page from blog

### ISSUE THREAD

**Issue by nithinkatta** [CircuitVerse/CircuitVerse#4302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After entering into the blog page when we click on the circuitverse logo, its not redirecting to the home page of circuitverse

### Steps To Reproduce

1) Click on https://circuitverse.org/
2) Click on blog
3) Click on Circuitverse logo on left top corner

### Expected Behavior

The page should redirect to the home page

### Screenshots

![Screenshot 2023-11-22 114744](https://github.com/CircuitVerse/CircuitVerse/assets/88046362/02599294-1759-42ec-b88b-7c759d6c1801)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by SUNIDHI-JAIN125** [comment]
Hey @nithinkatta!!
In my opinion this is not an issue because when you click on Blog then it is directed to a new tab. [https://blog.circuitverse.org/](url). So we don't need to redirect to the main organisation again, we need to close the tab.

Any other opinion?

**Comment by chiragmalik2612** [comment]
i got it, asssign this issue to me , i want to work on it.

**Comment by nithinkatta** [comment]
Hey @SUNIDHI-JAIN125!!
Yes, It is directed to new tab, but it looks good if it renders to the home page in the same new tab while clicking on the logo

**Comment by niladrix719** [comment]
@nithinkatta but if you notice thats a different website, clicking on the logo should not have a different website link

**Comment by tanmoysrt** [comment]
It's not an issue, it's a standard practice to redirect to the root of the website by clicking main logo.|

On any page `https://blog.circuitverse.org/<anything>`, if we click the main logo, that should redirect to https://blog.circuitverse.org/ .
