### ISSUE TITLE
🐞 Bug : Text overflow in the comment section

### ISSUE THREAD

**Issue by Keshav-0907** [CircuitVerse/CircuitVerse#4308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

https://github.com/CircuitVerse/CircuitVerse/assets/91189139/8d607c9c-4a35-47af-8c91-3079799f6098

The long words/Links are making disturbing the overall styling of that page 

### Steps To Reproduce

( In Mobile View )

1. Go to https://circuitverse.org/
2. Scroll Down to "Featured Examples"
3. Click on a Featured Example
4. Scroll Down to Comments

### Expected Behavior

The expected behavior is that, comments are displayed within a set character limit, preventing overflow, and offers users the choice to view the full comment when desired.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by royaals** [comment]
can i work on this issue?

**Comment by Keshav-0907** [comment]
@royaals 
I am already working on this :)

**Comment by royaals** [comment]
ok

**Comment by Arnabdaz** [comment]
duplicate issue of #3586

**Comment by tanmoysrt** [comment]
Closing this issue as duplicate pf #3586
