### ISSUE TITLE
🐞 Bug: search bar overlapping with introduction heading.

### ISSUE THREAD

**Issue by chiragmalik2612** [CircuitVerse/CircuitVerse#4309]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when we search , the search bar open and overlap or hide the introduction heading.
![Screenshot (511)](https://github.com/CircuitVerse/CircuitVerse/assets/150550493/b9cbd7c8-647e-42cc-81e3-3adcc84277bf)
![Screenshot (512)](https://github.com/CircuitVerse/CircuitVerse/assets/150550493/91116617-6b7c-441e-926a-64a0e42e9410)

1. Go to :  https://circuitverse.org/
2. click on search icon.

### Expected Behavior

the search bar should be open without overlapping/ hiding the content.

### Screenshots
![Screenshot (514)](https://github.com/CircuitVerse/CircuitVerse/assets/150550493/6f239b9a-c024-4403-b311-17afb0d50e98)

### Are you working on this issue?

Yes

**Comment by chiragmalik2612** [comment]
here is the solution or expected behavior.

https://github.com/CircuitVerse/CircuitVerse/assets/150550493/e8f73645-ec1d-4471-a304-fbc0392f1bd1

**Comment by chiragmalik2612** [comment]
@hrshkshri , i,ve also noticed the same problem and tried to solve it 
but don't know how to fix it from everywhere like it's working only on intro page 
i've tried this by edit html,css from inspect.
if you've done it can you please help me out.

**Comment by balagowda** [comment]
@chiragmalik2612 where else u found the issue? in /teachers and /contribute page??

**Comment by chiragmalik2612** [comment]
> @chiragmalik2612 where else u found the issue? in /teachers and /contribute page??

it is shown above , you can refer screenshots.

**Comment by balagowda** [comment]
In screenshots  u mentioned only about homepage @chiragmalik2612

**Comment by upsaurav12** [comment]
Respected Sir/Mam, 
I want to contribute in this repository but i am facing some problems while setup like i am not to understand how can i access the application from the browser(chrome) i have tried both by docker and by manually but i am facing same issue

**Comment by Jayendra-Welekar** [comment]
The same issue is posted in #4297 .

**Comment by balagowda** [comment]
@upsaurav12 place post ur installation issue in slack[https://circuitverse.org/slack](url) to get support

**Comment by chiragmalik2612** [comment]
> In screenshots u mentioned only about homepage @chiragmalik2612 , but it's also same issue in /about, /teachers, /contribute pages ???

@balagowda yess, this issue is everywhere...search bar overlap with other items.

**Comment by Jeevan-Neupane** [comment]
Assign me this issue please

**Comment by tanmoysrt** [comment]
As it's duplicate issue of #4297 , closing this issue.
