### ISSUE TITLE
🐞 Bug: Clicking 'Update Project' button displays 404 Not Found screen

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After clearing the name input and pressing 'Update Project,' an error message appears. And after that we again press "Update Project" button then 404 not found screen shows up.
### Video of Bug:

https://github.com/CircuitVerse/CircuitVerse/assets/77102885/374e7920-a85b-4f19-936b-33ea169ec228

### Steps To Reproduce

1. Go to [https://circuitverse.org/simulator](https://circuitverse.org/simulator) (After login)
2. Save the Project .
3. In Edit Project page , clear the Name input field .
4. Press "Update Project" button.(A error message will appear)
5. Then press again "Update Project" button.
_**See the error that 404 not found screen appears**_

### Expected Behavior

After pressing 'Update Project,' it should display an error message instead of going to the 404 Not Found screen.

### Screenshots

NA

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

NA

### Are you working on this issue?

Yes

**Comment by 1Shlok-singh** [comment]
please assign me this issue

**Comment by duckling69** [comment]
Hey @tanmoysrt can i work on this issue

**Comment by imsidkg** [comment]
Hello @tanmoysrt can you please confirm if @shauryag2002 is still working on it?

**Comment by shauryag2002** [comment]
Hey @tanmoysrt , need your help! So, when I hit 'Update Project' with an empty project name, it just kicks me back to the same URL without the '/edit' part. Any ideas on how to make it stay there when an error pops up?

**Comment by fillingtothemomo** [comment]
Hello, if this issue is not being worked upon by anyone, I would like to take this up.

**Comment by niladrix719** [comment]
Hi @shauryag2002 I am working on this as it's been more than a month now
