### ISSUE TITLE
🐞 Bug : Incorrect Email input field width in Add Collaborator modal

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4330]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Width of Email input box field is not correct in Add Collaborator modal.
### Screenshot of Bug :

![CV-fix-issue-incorrect-add-collaborator-before](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/f15b772a-f593-402b-b315-0655739d4415)

### Steps To Reproduce

1. Go to [https://circuitverse.org/simulator](https://circuitverse.org/simulator) , Then Create a circuit .
2. Open the page of your circuit .
3. Click the + Add a Collaborator .
**_See the error that Email input box's width is not correct._**

### Expected Behavior

The width of Email input box's should be long enough as `Add a Collaborator` modal.
### Screenshot of Solution :
![CV-fix-issue-incorrect-add-collaborator-after](https://github.com/CircuitVerse/CircuitVerse/assets/77102885/2d68e60e-355d-49b1-9364-b2b5c90195de)

### Screenshots

NA

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

NA

### Are you working on this issue?

Yes

**Comment by EshaanAgg** [comment]
I want to work on this issue! Can I please be assigned the same?

**Comment by tanmoysrt** [comment]
Issue verified
Go ahead @shauryag2002 

Just ensure, for the changes the select2 inputs of groups management pages don't get affected
