### ISSUE TITLE
Feature: Modify Highlight Color of Text  

### ISSUE THREAD

**Issue by senbo1** [CircuitVerse/CircuitVerse#4332]
### Is your feature request related to a problem? Please describe

Currently, the highlight color of selected text on the website remains the default.
![Screenshot from 2023-12-01 20-48-12](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/365636cd-3a60-4690-8245-6ba2bb65a70f)

### Describe the solution you'd like

To align with the design scheme, we should change the background color to primary-green of CircuitVerse and text color to white.
![Screenshot from 2023-12-01 20-47-05](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/ed09b810-53a9-4756-b1e7-ee65d3c4bce4)

### Are you working on this?

Yes

**Comment by Uddancode** [comment]
Hey, I would like to work on this issue, pls assign this issue @theslowdeveloper.

**Comment by hackwhiz-8** [comment]
i can do this

**Comment by tanmoysrt** [comment]
@senbo1 You have been assigned !
