### ISSUE TITLE
Invalid AuthenticityToken Error in Github Codespaces

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4334]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

After launching the project in CodeSpaces , While registering or logging in with a user , it's providing the below mentioned error.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/40eb59ff-51c2-4a8e-a564-e4d79e77ed53)

### Steps To Reproduce

1. Open the project in CodeSpace [[Follow Guide](https://github.com/CircuitVerse/CircuitVerse/blob/master/installation_docs/remote_development.md#github-codespaces)]
2. Register a user by visiting this route `http://localhost:3000/users/sign_up`
3. You will see the error

### Expected Behavior

It should not provide any error.

### Additional context

This error only comes when Github Codespaces run in Browser, and If you can open Codespaces in local VS Code, you will not face this issue.

### Are you working on this issue?

No

**Comment by niladrix719** [comment]
would like to work on this

**Comment by 1Shlok-singh** [comment]
Greetings, 

I express my interest in contributing to the issue and I would like to work on this issue

**Comment by tanmoysrt** [comment]
> would like to work on this

Go ahead. Might be some CSRF related issue.
So you may disable that while using Github Codespaces, You can check the configuration file in the repo, there is a specific environment variable to detect Github Codespace Environment.
