### ISSUE TITLE
🐞 Bug

### ISSUE THREAD

**Issue by sohail9972** [CircuitVerse/CircuitVerse#4347]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Search bar and Context Menu are not sticky at Header while scrolling down the side Navigation bar

### Steps To Reproduce

Go to :https://circuitverse.org/
Click on to Getting started drop down to Navigate to Documentation Tab 
Now Scroll Side Nav Bar and Observe the Search Field and Context Menu.

Uploading chrome_5raBC2WVse.mp4…

### Expected Behavior

Search bar and Context Menu Need to be Sticky to header

### Screenshots

<img width="960" alt="Screenshot_241" src="https://github.com/CircuitVerse/CircuitVerse/assets/68369706/15f71260-c5e2-4080-a8f1-489c95b87b20">

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by sohail9972** [comment]
Uploading chrome_5raBC2WVse.mp4…

**Comment by deepak05kr18** [comment]
I guess that is the functionality given to it

**Comment by tanmoysrt** [comment]
I think it's a functionality implemented in the theme
If you feel it can be made better, raise issue in this repo - https://github.com/CircuitVerse/CircuitVerseDocs

Check the codebase first to know, whether the changes possible

**Comment by tanmoysrt** [comment]
@sohail9972 

I think it's a functionality implemented in the theme
If you feel it can be made better, raise issue in this repo - https://github.com/CircuitVerse/CircuitVerseDocs

Check the codebase first to know, whether the changes possible
