### ISSUE TITLE
blog page (img) is not responsive🐞 Bug

### ISSUE THREAD

**Issue by yogeshsshekhawat** [CircuitVerse/CircuitVerse#4365]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the blog page image is not responsive for 
995 *736 resolution

### Steps To Reproduce

1. go to web site (circuitverse)
2. now do to the blog page 
3. check the resposive nature of the page
![erro1](https://github.com/CircuitVerse/CircuitVerse/assets/149690978/1466438a-0e28-4b4c-9471-c4c47a93c1f7)

### Expected Behavior

it should be like
![fix](https://github.com/CircuitVerse/CircuitVerse/assets/149690978/7cdb3e1d-df1f-467e-bbc2-e32b858bc1b2)

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
You should raise the issue in this repo https://github.com/CircuitVerse/Blog

**Comment by yogeshsshekhawat** [comment]
thankyou for telling me
