### ISSUE TITLE
 Non-responsive Notification Box 🐞 Bug 

### ISSUE THREAD

**Issue by deepak05kr18** [CircuitVerse/CircuitVerse#4370]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Upon clicking the bell icon in the website's navigation bar, the expected behavior is for a notification box to appear. While the notification box does appear as intended, it is observed that the box is not responsive in nature. This lack of responsiveness could potentially impact user experience, especially on devices with smaller screens or when viewed on various resolutions.

### Steps To Reproduce

1. Navigate to the CircuitVerse website.
2. Click on the bell icon in the navigation bar.
3. Observe the behavior of the notification box in terms of responsiveness.

### Expected Behavior

The notification box should adapt to different screen sizes and resolutions, ensuring a seamless and user-friendly experience.

### Screenshots

![WhatsApp Image 2023-12-12 at 11 58 31 AM](https://github.com/CircuitVerse/CircuitVerse/assets/122279122/c3f18933-50b0-4392-b26a-b3fec6789a00)

Expected behavior
<img width="359" alt="Screenshot 2023-12-12 115702" src="https://github.com/CircuitVerse/CircuitVerse/assets/122279122/b2cad427-ff87-4dfc-b1d1-9f9c845023ed">

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Google Chrome
- version: 120.0.6099.62
```

### Are you working on this issue?

Yes

**Comment by shauryag2002** [comment]
Hi @deepak05kr18 , This issue is being addressed in #4260
