### ISSUE TITLE
🐞 Bug: A color bug when click on "Learn logic design"

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When i click on Learn logic design sometime a dark theme mode rendered for a second Sometimes it doesnot

### Steps To Reproduce

Go to https://circuitverse.org/
Click on "Learn logic Design"
See the error

### Expected Behavior

it should be rendered properly whenever clicked

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/116784047/5839a055-7499-4f18-8519-1a74d062d57b

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Additional context

You can check may this is from my side

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
Hi @upsaurav12 
It seems to be the blue colour coming while transitioning to `dark` mode while loading.
Although the `docs` is dependent on jsdoc with `better-docs` template

Although, raise the issue in this repo - https://github.com/CircuitVerse/Interactive-Book
& close this one !

**Comment by upsaurav12** [comment]
@tanmoysrt yes but  it's already raised in that repo and it is only arrises when we click in interactive-book page so should i open a saparate issue ?? https://github.com/CircuitVerse/Interactive-Book     #575

**Comment by tanmoysrt** [comment]
> @tanmoysrt yes but it's already raised in that repo and it is only arrises when we click in interactive-book page so should i open a saparate issue ?? https://github.com/CircuitVerse/Interactive-Book #575

It's not same issue. Anyway as the issue closed, you can open !

**Comment by upsaurav12** [comment]
@tanmoysrt got it
