### ISSUE TITLE
 Issue with User Profile "My Circuits" Section Overflow

### ISSUE THREAD

**Issue by deepak05kr18** [CircuitVerse/CircuitVerse#4372]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When searching for a user and navigating to their profile page, the "My Circuits" section appears to have an overflow issue. The text "public" exceeds the boundaries of the box, affecting the visual presentation of the user's circuits.

### Steps To Reproduce

1. Perform a search for a user on the CircuitVerse website.
2. Navigate to the user's profile.
3. Observe the "My Circuits" section to see that the text "public" exceeds the box boundaries.

### Expected Behavior

The "My Circuits" section should display the text "public" within the box boundaries, ensuring a visually pleasing and well-formatted presentation.

### Screenshots

<img width="959" alt="problem" src="https://github.com/CircuitVerse/CircuitVerse/assets/122279122/b74ec1f2-44c0-4838-baec-a000a9ab4e66">

It should be like
<img width="960" alt="Screenshot 2023-12-12 230856" src="https://github.com/CircuitVerse/CircuitVerse/assets/122279122/8874c775-48c9-49b9-9704-2d68a4dcd252">

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Google Chrome
- version: 120.0.6099.71
```

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
i guess it is addressing the issue #4303 if i am not wrong
