### ISSUE TITLE
⭐️Feature: Make Side bar : `position: sticky;`

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4380]
### Is your feature request related to a problem? Please describe

It is hard to access side bar , If you scroll down.
### Video of current functionality :
https://github.com/CircuitVerse/simple_discussion/assets/77102885/6c26b3ed-4651-433a-9811-1e60c5befc26

### Describe the solution you'd like

Make sidebar `position: sticky;` for easy accessibility and improved appearance.

### Video of Solution :

https://github.com/CircuitVerse/simple_discussion/assets/77102885/fd4fddd3-2105-42d4-9c96-5ff08d8f152b

### Describe alternatives you've considered

NA

### Additional context

NA

### Are you working on this?

Yes

**Comment by aarishshahmohsin** [comment]
Can I be assigned this issue?

**Comment by yogeshsshekhawat** [comment]
could you please assign me this issue

**Comment by 0PrashantYadav0** [comment]
i would like to work on it so please assign this to me

**Comment by tanmoysrt** [comment]
Issue verified !
Go ahead @shauryag2002
