### ISSUE TITLE
Inconsistent Capitalization in Comment Placeholder

### ISSUE THREAD

**Issue by deepak05kr18** [CircuitVerse/CircuitVerse#4387]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The placeholder text for adding a comment is currently set as "Add A Comment." in forums. This follows title case, which is more formal and appropriate for titles but not consistent with sentence case within the context of a sentence or paragraph. To align with standard sentence case conventions, it should be changed to "Add a comment..." This adjustment would enhance the overall readability and adherence to style guidelines.

### Steps To Reproduce

1.Visit the CircuitVerse website.
2. Navigate to the footer section.
3. Click on the "Forum" options.
4. Click on Ask a Question button.

### Expected Behavior

The placeholder text should follow sentence case, such as "Add a comment..."

### Screenshots

<img width="946" alt="Screenshot 2023-12-17 003634" src="https://github.com/CircuitVerse/CircuitVerse/assets/122279122/9fbd719e-0393-42b9-9ecf-5c2870ae6bf4">

It should be like
<img width="960" alt="checked" src="https://github.com/CircuitVerse/CircuitVerse/assets/122279122/24cf65fb-edfd-4516-bdce-5ca2551d97ad">

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Google Chrome
- version: 120.0.6099.72
```

### Are you working on this issue?

Yes

**Comment by Madankumara** [comment]
Hey @deepak05kr18 please assign me the issue.

**Comment by Madankumara** [comment]
Hey @deepak05kr18 i would like to work on the issue.

**Comment by tanmoysrt** [comment]
@deepak05kr18 Go ahead !
