### ISSUE TITLE
🐞 Bug: The outline of Search-bar is not visible in dashboard

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the dashboard after login the Search bar below the user's details the outline is not visible 

### Steps To Reproduce

1. Go to https://circuitverse.org/users/211241
2. Scroll down and see the search-bar container
3. see the error

### Expected Behavior

![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/908ae024-0331-4b15-8ab6-b3bc45e9f3cd)

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/d8b1d630-e4b1-4732-b3aa-096333e537f0)

### Device Information [optional]

```markdown
- OS: Windows 
- Browser: Chrome
- version: 120.0.6099.109
```

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
please assign this issue to me

**Comment by tanmoysrt** [comment]
Currently, the search input has been updated. Ref #4381
So the mentioned issue does not exist anymore.
In the main website the issue maybe there as we do manual deployment.
