### ISSUE TITLE
Incorrect spelling of placeholder in last section of Contact Us form -"You"

### ISSUE THREAD

**Issue by Madankumara** [CircuitVerse/CircuitVerse#4396]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Describe the bug

The placeholder text for writing Message in last section of contact us form is "Type You Message Here".
where "You" should be changed to "Your".
It should be "Type Your Message Here".

### Steps To Reproduce

1.Visit the CircuitVerse website.
2. Navigate to the Blog Page.
3. Click on the "Contact" button top right corner .
4. scroll down to contact us form

### Expected Behavior

The placeholder text inside the last section of form should be corrected to "Type Your Message Here"

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/147712713/ba69e2bc-9669-4eec-ac1d-47e4b3542016)

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Google Chrome
- version: 120.0.6099.72
```

### Are you working on this issue?

Yes

**Comment by deepak05kr18** [comment]
https://github.com/CircuitVerse/Blog/issues/170   check this
