### ISSUE TITLE
"Download Image" feature is slightly broken

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#44]
When downloading an image of my display (I have not tested it on any other circuits yet) it seems to h\get the layers mixed up.
![test](https://user-images.githubusercontent.com/34515731/48231746-21bedc00-e3a7-11e8-8ea9-a939588d5436.png)
![screenshot 2018-11-08 17 34 18](https://user-images.githubusercontent.com/34515731/48231755-27b4bd00-e3a7-11e8-818d-e339e84dfffe.png)

The image on the bottom is how it's supposed to look, the top image is how it looks when using the Download Image tool

**Comment by satu0king** [comment]
This circuit looks amazing! Yeah, the render order was wrong, I corrected it, could you confirm and post a picture of the same.
