### ISSUE TITLE
the tag name is not visible 🐞 Bug

### ISSUE THREAD

**Issue by yogeshsshekhawat** [CircuitVerse/CircuitVerse#4400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

the tag name is not visible 🐞 Bug

### Steps To Reproduce

1. go to the web site 
2. scroll down to Featured Examples
3. now click on any project 
4. and then go to the Comments section and click on anyone user profile
5. the tag name is not visible
![Screenshot 2023-12-19 213402](https://github.com/CircuitVerse/CircuitVerse/assets/149690978/c24ab121-7342-4406-809d-1cf55d05611c)

### Expected Behavior

it should be like 
![Screenshot 2023-12-19 213535](https://github.com/CircuitVerse/CircuitVerse/assets/149690978/e6147a00-df23-414b-b9f5-cfc5d4201a3c)

### Are you working on this issue?

Yes

**Comment by yogeshsshekhawat** [comment]
can you please assign me this issue

**Comment by tanmoysrt** [comment]
@yogeshsshekhawat thanks for raising the issue.

But, This issue has been fixed by #4338 
After the next deployment, the issue will be resolved in live website as well.
