### ISSUE TITLE
🐞 Bug : UI for Edit Layout is Distorted/Un-even in Simulator

### ISSUE THREAD

**Issue by Vivek-Lahole** [CircuitVerse/CircuitVerse#4402]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

**Edit Layout** tab of Simulator has **un-even/distorted UI** Components 

1. The height attribute is misplaced in the edit layout tab.
2. The reset all nodes icon is misplaced in the edit layout tab

### Steps To Reproduce

1. Go to Simulator 
2. In layout tab , click edit Layout 
3. Top part of edit layout tab

### Expected Behavior

1. The height attribute should be correctly placed below the width attribute.
2. The reset all nodes icon should be sideways to **Reset All Nodes text**.

### Screenshots

**Current UI** of Edit-Layout:

![image](https://github.com/CircuitVerse/CircuitVerse/assets/82323706/704a0bb5-00b0-4cc1-a525-10416cae9737)

### Device Information [optional]

```markdown
- OS:Windows
- Browser:Chrome
- version:Chrome Version [120.0.6099.110]
```

### Are you working on this issue?

Yes

**Comment by Vivek-Lahole** [comment]
@tanmoysrt Can you  please **assign** me this issue !

**Comment by tanmoysrt** [comment]
@Vivek-Lahole I am not able to reproduce the issue. I am testing on Chrome latest 120.*
In which browser you are testing on and the version of browser ?

**Comment by Vivek-Lahole** [comment]
> @Vivek-Lahole I am not able to reproduce the issue. I am testing on Chrome latest 120.* In which browser you are testing on and the version of browser ?

I am  using Google Chrome
![image](https://github.com/CircuitVerse/CircuitVerse/assets/82323706/c074bff0-de36-4c19-b560-f27d1742ed1a)

When you navigate to Simulator and click on Edit Layout in layout tab , in this manner this issue can be reproduced.

**Comment by tanmoysrt** [comment]
> > @Vivek-Lahole I am not able to reproduce the issue. I am testing on Chrome latest 120.* In which browser you are testing on and the version of browser ?
> 
> I am using Google Chrome ![image](https://private-user-images.githubusercontent.com/82323706/291786223-c074bff0-de36-4c19-b560-f27d1742ed1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwNTAwMjUsIm5iZiI6MTcwMzA0OTcyNSwicGF0aCI6Ii84MjMyMzcwNi8yOTE3ODYyMjMtYzA3NGJmZjAtZGUzNi00YzE5LWI1NjAtZjI3ZDE3NDJlZDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIwVDA1MjIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMzNiMzUyZDZjMWI4N2ZjZTI0NjM1ZTg4NWQ1YTM5Yjc0NzliMjFjYzQ2MDU2ODg5ZDJiYjJlNzg2MzhmMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wLeM2DRANikHHH3cp_nAaYLupLekClWqAfSEzmBnM7w)
> 
> When you navigate to Simulator and click on Edit Layout in layout tab , in this manner this issue can be reproduced.

Here is mine
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/ac8e41b9-f3a2-4bb2-9736-76ba4fee3585)

Can you share screen size of your system ?

**Comment by tanmoysrt** [comment]
Try also on incognito to check whether the issue exists

**Comment by Vivek-Lahole** [comment]
> Try also on incognito to check whether the issue exists

I  check on Incognito mode as well but  the issue is still there
![image](https://github.com/CircuitVerse/CircuitVerse/assets/82323706/ee2ae473-782c-4d34-b804-31cbce976ec6)

Here are my screen resolution Information
![image](https://github.com/CircuitVerse/CircuitVerse/assets/82323706/21e81ad9-8850-4107-9e6b-1c2f5a5db7d0)

**Comment by upsaurav12** [comment]
Me also not able to reproduce this issue

**Comment by Vivek-Lahole** [comment]
Something that was related to my system settings and Google Chrome environment—not a bug—is resolved!
