### ISSUE TITLE
NAN dates on iMac

### ISSUE THREAD

**Issue by sfeister** [CircuitVerse/CircuitVerse#441]
**Describe the bug**
NAN in default date window when creating new assignment in iMac in Safari browser

**To Reproduce**
1. **On our iMacs**, go to 'Create New Assignment' or Edit Assignment.
2. Observe the date field is now filled with NANs.

**Expected behavior**
Of course, that it would have a date!

**Desktop (please complete the following information):**
 - OS: macOS [version? Can look up later]
 - Browser Safari
 - Version ? [Can look up later]

**Are you working on this issue? (Yes/No)**
No

**Comment by phyzicist** [comment]
This doesn't happen in Firefox on Windows 10.

**Comment by phyzicist** [comment]
My proposed solution: Use server time, rather than local computer time, to pre-populate the date text box?

**Comment by VaibhavUpreti** [comment]
Not able to reproduce bug on macos Monterey 12.4 -using safari.
