### ISSUE TITLE
Test Bench missing in Tutorial Guide

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4410]
### Is your feature request related to a problem? Please describe

In the tutorial guide, all panels tour is covered except the test bench,

### Describe the solution you'd like

We need to Add a **test bench** to the tutorial guide 

### Are you working on this?

Yes

**Comment by Malavi1** [comment]
@Prerna-0202 Cloud you please review the issue?

**Comment by Arnabdaz** [comment]
cc @tachyons
