### ISSUE TITLE
Feature: Whiteboard for the Navigation bar 

### ISSUE THREAD

**Issue by Simer13** [CircuitVerse/CircuitVerse#4413]
### Is your feature request related to a problem? Please describe

The navigation bar overlaps with the website. It is better to keep the nav bar looks separate from website.

### Describe the solution you'd like

Build a whiteboard for the navigation bar. It will improve its quality and appearance. 

### Are you working on this?

Yes

**Comment by RahulRudra81** [comment]
I want to work on this issue . Can you please assign it to me

**Comment by tanmoysrt** [comment]
@Simer13 you have been assigned !
