### ISSUE TITLE
Enhancement: Improved User Profile Presentation in Navbar (Feature)

### ISSUE THREAD

**Issue by nisha-laur** [CircuitVerse/CircuitVerse#4422]
### Is your feature request related to a problem? Please describe

The current User Profile Navbar Dropdown Menu displays the user's name in a small space, causing the name to be partially cut off and making the overall presentation less visually appealing.

### Describe the solution you'd like

I propose replacing the user's name in the Navbar Profile Dropdown Menu with a small profile image. This change will not only provide a more aesthetically pleasing appearance but also ensure that the user's profile is presented in a clear and concise manner.
![Group 3](https://github.com/CircuitVerse/CircuitVerse/assets/104618576/e3fb1c2f-0acf-4ffe-85d2-e229ea7a53a5)

### Describe alternatives you've considered

Alternative solutions may include adjusting the font size or layout to accommodate the user's name better. However, replacing the name with a profile image is a more modern and user-friendly approach.
[Figma Link](https://www.figma.com/file/tUWRBvEZBbm9AtvqRB7ZAP/Dashboard-profile-icon?type=design&node-id=1%3A2&mode=design&t=VmnnrnAXueYDU815-1)

### Additional context

Adding a profile image to the Navbar Profile Dropdown Menu will enhance the overall user experience by creating a visually appealing and easily recognizable representation of the user. This change aligns with current design trends and ensures that the user's profile is presented in a more elegant and user-friendly manner.

### Are you working on this?

Yes

**Comment by gkm0001** [comment]
I think you should "YOU" because having two avatars or changing font size negatively impacts the overall design or user experience, simplifying the approach with a single, inclusive term like "You" can be a good alternative.

**Comment by nisha-laur** [comment]
@tanmoysrt  @vedant-jain03 What do you think ?

**Comment by tanmoysrt** [comment]
@nisha-laur I feel the current design looks much cleaner than placing a avatar.

**Comment by nisha-laur** [comment]
Alright @tanmoysrt  , Will close this issue then.
