### ISSUE TITLE
Re-order tabs of Circuits

### ISSUE THREAD

**Issue by phyzicist** [CircuitVerse/CircuitVerse#443]
**Is your feature request related to a problem? Please describe.**
It's not a huge problem, but typically my students have a preferred order of circuits -- e.g. such that a new sub-circuit sits next to the circuit that uses it.

**Describe the solution you'd like**
Like in modern web browsers, it would be great if you could click and drag on Circuit tabs to re-order.

**Describe alternatives you've considered**
A less preferred solution would be to allow re-ordering of tabs with some sort of numeric priority indication.

My current workaround is to Shift-Drag to copy/paste the entire contents of circuits to re-order tabs. Doing that workaround is tedious and not usually worth the effort.

**Screenshots**
Circuit tabs:
<img width="189" alt="Tabs" src="https://user-images.githubusercontent.com/7269185/65298109-1851e480-db1f-11e9-9387-f86b0c86584f.PNG">

**Are you working on this? (Yes/No)**
No

**Comment by NavonilDas** [comment]
Good Idea 👍 . I will be working on it.

**Comment by Palaksharma23** [comment]
I would love to work on this issue : )

**Comment by Palaksharma23** [comment]
This issue is already solved. I guess @tachyons we can close this one : )
