### ISSUE TITLE
🐞 Bug: Project page and projects buttons stick to each other.

### ISSUE THREAD

**Issue by nikhilhuirem** [CircuitVerse/CircuitVerse#4437]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the 

In bigger screen size the project page and the project buttons stick to each other.

### Screenshot of the bug
<img width="1440" alt="Screenshot 2023-12-26 at 10 24 34 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/73533729/de538a3c-dde1-48f1-9591-f18d0987ad8f">

### Steps To Reproduce

1. Go to your profile drop-down and click the dashboard section.
2. Under your profile details you will find the projects buttons and project list.
3. Both are sticking to each other on a bigger screen.

### Expected Behavior

Project buttons and project lists must have a gap between them.

### Screenshot of expected behavior
<img width="1440" alt="Screenshot 2023-12-26 at 10 24 17 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/73533729/2e0181a4-bce3-4287-94e9-48f9cc66fd5c">

### Device Information [optional]

```markdown
- OS: macOS 14.2
- Browser: Chrome
- version: 120.0.6099.129
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
@nikhilhuirem go ahead !
