### ISSUE TITLE
Include font size property for text tool

### ISSUE THREAD

**Issue by phyzicist** [CircuitVerse/CircuitVerse#444]
**Is your feature request related to a problem? Please describe.**
When I'm designing circuits to show students, I often want to add large text as a title.

**Describe the solution you'd like**
I'd like the text tool to have a font size property.

**Describe alternatives you've considered**
I just use the default font size, sometimes all-caps.

**Are you working on this? (Yes/No)**
No

**Comment by Parikshit-Hooda** [comment]
Should also take into account overflow and other render issues that might happen as fontsize changes

**Comment by M06631** [comment]
Hi please assign this issue to me am working on it

**Comment by M06631** [comment]
@phyzicist  @satu0king 
I add this feature it looks like:
![Text size](https://media.giphy.com/media/XygiJjMl06AhhEPGxW/giphy.gif)
I'll make a PR to master I think?
