### ISSUE TITLE
🐞 Bug: Getting started dropdown icon is not working

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4450]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Getting started dropdown icon is not working(i.e. it is changing direction of arrow on dropdown)
![Screenshot 2023-12-29 060736](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/c108abca-4631-4061-9190-c555253543f2)
![Screenshot 2023-12-29 060750](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/2adb0c21-2320-4bc2-9d8f-d447b0387cfb)

### Steps To Reproduce

1. Go to main page 
2. click on Getting started button 
3. its dropdown icon is not working(i.e. it is changing direction of arrow on dropdown)

### Expected Behavior

IN DROP DOWN IT SHOULD POINT DOWNWARDDS LIKE THIS:
![Screenshot 2023-12-29 061353](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/ffcbf4d3-d65f-4957-94c9-30f74467595b)
![Screenshot 2023-12-29 061411](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/03a85d77-538f-4167-868f-9f58cc7f0ada)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
@priyanshagra go ahead !

**Comment by riteshsinghh-coder** [comment]
@tanmoysrt kindly check

**Comment by priyanshagra** [comment]
sir please review my pr(https://github.com/priyanshagra/CircuitVerse/commit/f97fab21c55d91ddc1ebce139439c95f338f9fe8) of this issue i created
