### ISSUE TITLE
🐞 Bug: Panels can be dragged outside the viewport on mobile devices

### ISSUE THREAD

**Issue by NamitBhutani** [CircuitVerse/CircuitVerse#4451]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In mobile devices (Responsive mode in dev tool) whenever a draggable panel is completely dragged outside the screen (viewport) there is no way to drag it back.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/26519624/6283ffc2-46c7-4f61-8aaf-a50834019db2)

### Steps To Reproduce

1. Open dev tools and choose any mobile device.
2. Try dragging the panels outside the viewport.

### Expected Behavior

The panels should not be allowed to go past the viewport as is in big screen devices.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by NamitBhutani** [comment]
Please assign me this issue.

**Comment by tanmoysrt** [comment]
cc @Arnabdaz @Prerna-0202

**Comment by DhairyaMajmudar** [comment]
I have checked this issue in chrome and Firefox and its as said by @Arnabdaz, so can be closed.
