### ISSUE TITLE
🐞 Bug (Simulator 500 error)

### ISSUE THREAD

**Issue by zzz-creator** [CircuitVerse/CircuitVerse#4468]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm recieving a 500 error.

### Steps To Reproduce

1. Click on simulator icon

### Expected Behavior

Open the simulator.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by DhairyaMajmudar** [comment]
@zzz-creator can you pls. explain the issue more. Like which kind of bugs you are facing?

**Comment by Mayank77maruti** [comment]
Hey @DhairyaMajmudar , I am new to open source can you please tell how can I contribute to this amazing repository.

**Comment by DhairyaMajmudar** [comment]
> Hey @DhairyaMajmudar , I am new to open source can you please tell how can I contribute to this amazing repository.

Hi @Mayank77maruti thanks for showing your interest. You can start contributing by solving good first issues also you can join the slack community to connect with other contributors and mentors.

**Comment by tanmoysrt** [comment]
It was a production issue and fixed !
If anyone facing the issue anymore, open the issue.
