### ISSUE TITLE
Profile Picture size inconsitency

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4473]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

As we didn't define the particular dimension for the user profile, the picture should look like it is producing inconsistency while uploading different dimensions of the image. 

` <%= image_tag user_profile_picture(@profile.profile_picture), alt: "project.name", class: "center-row search-usersearch-image" %>`

https://github.com/CircuitVerse/CircuitVerse/assets/112646623/1deff9c7-cd0c-4519-9539-53b43a3b0bbe

### Steps To Reproduce

->login
->upload the image
->again upload image(with different dimensions)
->see error Upload

### Expected Behavior

It would be more ordered and clean if we define the fixed dimensions Irrespective of the size of the image the user uploading

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by niladrix719** [comment]
will work on this if approved @Malavi1

**Comment by tanmoysrt** [comment]
> will work on this if approved @Malavi1

You can work on this
