### ISSUE TITLE
🐞 Bug: Incorrect Label hover for Group Name

### ISSUE THREAD

**Issue by niladrix719** [CircuitVerse/CircuitVerse#4477]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The label is shown on hover on the parent div instead of the group name element

### Steps To Reproduce

1. go to https://circuitverse.org
2. go to you groups
3. hover on the group name and around it
4. see error

### Expected Behavior

The label should be shown only when the element group name is hovered

### Screenshots

https://github.com/CircuitVerse/CircuitVerse/assets/91966855/6d3341ef-61f0-4f8e-91db-065269c32197

### Device Information [optional]

```markdown
- OS: MacOs
- Browser: Safari
- version:
```

### Are you working on this issue?

Yes

**Comment by niladrix719** [comment]
@syntax-bot yeah why not, you can take it once approved

**Comment by dev-tashvi** [comment]
so the 
▶ one thing I found is you are putting the "Edit name" container in h1 which should be outside of h1, 

▶ the second thing is you  are putting full width to GroupName and PrimaryMentor, If you want that whenever the user hovers over the name then the tooltip should show, for that I think you should use "width:fit-content" to both, 

▶ third thing is replace the bootstrap class of the div which contains name and edit name, etc with this class "d-flex flex-column align-items-center col-xs col-sm col-md col-lg" 

and all set 😀

**Comment by tanmoysrt** [comment]
> > @syntax-bot yeah why not, you can take it once approved
> 
> Thanks

Hi @syntax-bot , you can work on this
