### ISSUE TITLE
 File missing : [application.js file missing ] while installing the circuitverse setup in local pc

### ISSUE THREAD

**Issue by igennova** [CircuitVerse/CircuitVerse#4490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

While setting up the circuitverse in local pc for contributing i faced this issue that
there is one file missing in app/assets/javascript the file name is application.js so that file should be there if that file will not be there
new contributors will face problem to setup circuit verse in their local environment

### Steps To Reproduce

1 Clone the github repo
2 run docker command

### Expected Behavior

The site will not run in the local environment if we do not have application .js

### Screenshots

![Screenshot (224)](https://github.com/CircuitVerse/CircuitVerse/assets/91773416/fd011b36-caf8-4350-8400-2524562ebf03)

### Device Information [optional]

```markdown
- OS:Windows 11
- Browser:Chrome
- version:120.0.6099.130 (Official Build) (64-bit)
```

### Are you working on this issue?

Yes

**Comment by igennova** [comment]
plzz assign this issue to me

**Comment by tachyons** [comment]
See the https://github.com/CircuitVerse/CircuitVerse/blob/master/installation_docs/troubleshooting_guide.md
