### ISSUE TITLE
can't log in on Interactive book🐞 Bug

### ISSUE THREAD

**Issue by oiabhishekk** [CircuitVerse/CircuitVerse#4495]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

can't properly login  on Interactive Book  

https://github.com/CircuitVerse/CircuitVerse/assets/137642480/c4281baa-f8bc-4d83-a145-c3b832ecee9d

### Steps To Reproduce

go to : https://learn.circuitverse.org/about.html

### Expected Behavior

A user should be able to login  so that he can comment.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
cc @tachyons

**Comment by tachyons** [comment]
This seems to be an issue with disquis platform. Seems to be working now.
