### ISSUE TITLE
🐞 Bug:In mobile view, Navbar's taskbar menu when opens it's baground page is visible (i.e. it should opaque till it opened)

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4497]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 In mobile view ,when navbar's taskbar menu opens but we can still able to use background this  is a bad experience .
Its background should opaque
![Screenshot 2024-01-03 032311](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/722a8ccd-aaf9-47f2-bf65-a4783aba5374)

### Steps To Reproduce

1. Go to mobile view
2. open navbar taskbar menu
3. its background is scrollable &usable

### Expected Behavior

it's background should be hidden
https://github.com/CircuitVerse/CircuitVerse/assets/127022024/fddb70a5-7f41-44aa-a8c1-acd864d1518f

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by priyanshagra** [comment]
@tanmoysrt please assigin this issue to me

**Comment by tanmoysrt** [comment]
There is already PR to make it sticky instead of overlapping the content #4188 
As this is not any sidebar by design, the opaque background on opening this may not required.
