### ISSUE TITLE
🐞 Bug:In mobile view, Navbar's taskbar menu when opens it's opening button should change to cross for closing that menu

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In mobile view navbar's taskbar menu when opens it's opening buttoon sholud change to cross for closing that menu for better user experience
![Screenshot 2024-01-03 033801](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/cd5dffa5-f47a-44cf-98b5-4ec0cb4ac8da)

### Steps To Reproduce

1. Go to mobile view
2. open navbar taskbar menu
3. its closing button should be changed to cross instead of usual opening button of three lines

### Expected Behavior

its closing button should be changed to cross instead of usual opening button of three lines

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by riteshsinghh-coder** [comment]
please assign this issue to me

**Comment by priyanshagra** [comment]
@tanmoysrt please assigin this issue to me
