### ISSUE TITLE
Feature UX: Hamburger menu is converted to the cross icon while menu is opened  

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/CircuitVerse#4499]
### Is your feature request related to a problem? Please describe

In the mobile responsive view when the navbar is dropped down the hamburger menu can be converted into the cross icon 

### Describe the solution you'd like

Replacing the hamburger menu with the cross icon when the menu is opened. 

### Describe alternatives you've considered

![image](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/4a11e177-7f5f-4c19-9dfe-7cb9b35f3d86)

### Additional context

- [x]  Add feature to the main website 
- [x] Add feature to the legacy simulator 
### Are you working on this?

Yes

**Comment by DhairyaMajmudar** [comment]
@tanmoysrt pls. assign this issue to me : )

**Comment by harith-hacky03** [comment]
I am ready to fix it . Hope it helps .

**Comment by tanmoysrt** [comment]
> @tanmoysrt pls. assign this issue to me : )

Sure !

**Comment by priyanshagra** [comment]
This is the cheating i raise the same issue before you
@tanmoysrt please see my issue just before it and please remove this issue

**Comment by tanmoysrt** [comment]
> This is the cheating i raise the same issue #4498 before you @tanmoysrt please see my issue just before it and please remove this issue

He have discussed the issue on 1st january on slack #ux group, I don't think it's correct to close this.

**Comment by priyanshagra** [comment]
but sir i had raise this issue before him about 8hrs earlier if he has disscused he should raise this
 issue before me
