### ISSUE TITLE
Group Invite Link "Copy to Clipboard" option 

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4511]
### Is your feature request related to a problem? Please describe

After creating the group we have 2 options to add the numbers
*  entering their emails
*  Invitation link
**My feature request is related to 2nd option where the user needs to copy the invitation link through keys/mouse**

![Screenshot from 2024-01-04 04-35-09](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/9f4c27c9-26e3-42b1-a671-a1b71fd2d536)

### Describe the solution you'd like

In addition to that, we can let the user copy the invitation link just by **clicking a button/icon.**

[Screencast from 01-04-2024 04:40:10 AM.webm](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/d080f1bd-8033-4061-b34d-9cf14366b7f0)

### Are you working on this?

Yes

**Comment by Harsh1s** [comment]
Could you assign this issue to me? Would love to work on this.

**Comment by tanmoysrt** [comment]
@Malavi1 It will be better to have a UI like github for placing the `copy` icon button inside a container.

like the below image.
![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/9d306ea6-3307-443d-81d1-ca713aa75e98)

**Comment by Malavi1** [comment]
Yep, that was more refined.
We will go with that

**Comment by Decoder-25** [comment]
anyone working on this issue? @Malavi1

**Comment by Malavi1** [comment]
Yep, me

**Comment by tanmoysrt** [comment]
> Yep, me. 
> @tanmoysrt can I work?! 

Yeah sure
