### ISSUE TITLE
🐞 Bug incubated form text breaking into lines

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In footer section the "incubated form" text is breaking into to lines when width is below 305px

### Steps To Reproduce

1. Go to 'https://circuitverse.org/'
2. Scroll down and see the incubated-from text above the Zense logo
3. reduce the width size

### Expected Behavior

It should not break in to lines

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/0ca83c7d-e829-427c-b2e7-dc6f67165bae)

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Chrome
- version: 120
```

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
Please review this issue and assign this issue to me

**Comment by DhairyaMajmudar** [comment]
@upsaurav12 if you don't mind shall I take this up. If @tanmoysrt approves this issue.
Thank you : )

**Comment by upsaurav12** [comment]
yep go ahead

**Comment by DhairyaMajmudar** [comment]
Thanks 🤝🏻

**Comment by DeekshaMalviya** [comment]
Hey,
Can I work on this issue  ??
