### ISSUE TITLE
🐞 Bug: Username is Not Aligned correctly on Simulator Screen

### ISSUE THREAD

**Issue by nikhilkalburgi** [CircuitVerse/CircuitVerse#4534]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The Username is not aligned vertically to center

### Steps To Reproduce

1. Go to 'Simulator'

### Expected Behavior

The username should align vertically to the center and should have some gap with down arrow

### Screenshots

![Screenshot 2024-01-07 180039](https://github.com/CircuitVerse/CircuitVerse/assets/70331875/e7638997-e6e2-45a7-960a-c4bce69b4f0a)

### Device Information [optional]

```markdown
- OS:Windows
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
Closing as duplicate of #4519
