### ISSUE TITLE
FAQ in footer 

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4539]
### Is your feature request related to a problem? Please describe

Adding the **FAQ** section in the footer will help users get a basic idea regarding CV and how they can use it. Those all are the most asked questions as well as common ones and bringing that here adds value.

![Screenshot from 2024-01-08 12-19-11](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/451e7937-1029-436f-89fe-798b3208e2c8)

### Describe the solution you'd like

As we have an **FAQ** section ready to use(In the User Manual) it is just a matter of adding a tag and hyperlink in the footer accordingly.

![Screenshot from 2024-01-08 12-11-15](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/978e7f60-37b7-48b7-b95b-8fc1e2970fe3)

### Describe alternatives you've considered

Instead of using a user manual FAQ for navigation, we can even build a dedicated FAQ by considering the forum section question or brainstorming the questions 

### Are you working on this?

Yes

**Comment by whitewolf2000ani** [comment]
Can I work on this feature request .

**Comment by GaganMeshram123** [comment]
@igennova please can you assign these issue to me I want to work on these issue

**Comment by GaganMeshram123** [comment]
@Malavi1 please can you assign these issue to me I want to work on these issue

**Comment by pankaj-2503** [comment]
I would like to work on this issue by adding html component in footer to add hyperlink of faq

**Comment by Malavi1** [comment]
@tanmoysrt if this issue verified. 
I would like to pass this to @igennova

**Comment by tanmoysrt** [comment]
> @tanmoysrt if this issue verified. I would like to pass this to @igennova

Thanks
Hi @igennova you can work on your first issue.

**Comment by igennova** [comment]
> > @tanmoysrt if this issue verified. I would like to pass this to @igennova
> 
> Thanks Hi @igennova you can work on your first issue.

Thanks @tanmoysrt for giving me this

**Comment by arpy8** [comment]
can you assign this task to me? @tanmoysrt

**Comment by igennova** [comment]
i have submitted the pr 
please review it @tanmoysrt
