### ISSUE TITLE
Google Code-In 2019 application

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerse#454]
Google Code-in 2019 is accepting applications from 10 october.
Link : https://codein.withgoogle.com/

We should apply!

**Comment by Parikshit-Hooda** [comment]
@satu0king Its time!

**Comment by Parikshit-Hooda** [comment]
Also, this time, I would like to mentor some of the participants.

**Comment by ankitkataria** [comment]
Hey, we've started the discussion for application of GCI on #gci19 channel on slack, do consider joining for further updates! :grin:

**Comment by Parikshit-Hooda** [comment]
ok, got it!
