### ISSUE TITLE
🐞 Bug - Mentor Adding Themselves Again After Creating Group

### ISSUE THREAD

**Issue by priyam-03** [CircuitVerse/CircuitVerse#4541]
### Describe the bug

The current system allows the mentor to add themselves again to a group after creating it. This behavior is not preferable and needs attention.

### Steps To Reproduce

1. Create a new group.
2. Assign yourself as the mentor during the creation process.
3. Attempt to add yourself again to the group.

### Expected Behavior

Mentors should not be able to add themselves again to a group they are already mentoring.

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/104610119/e17e556b-9fb4-43c5-bc46-5cba29e55959)
creator: priyam.saha2003@gmail.com
added mentor: pritam.saha2003@gmail.com
(same mail coming twice as mentor)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by priyam-03** [comment]
@tanmoysrt  if the issue is valid I am interested to solve it.

**Comment by tanmoysrt** [comment]
> @tanmoysrt if the issue is valid I am interested to solve it.

Issue verified. You can prevent to add primary mentor as mentor again
