### ISSUE TITLE
In terms of service and In privacy policy there is no padding or margin at top of heading🐞 Bug

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4550]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In terms of service and In privacy policy  there is no padding or margin at top of heading ,this is a bad user exxperience
![Screenshot 2024-01-09 085827](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/734ef3dd-761a-4d15-8c1e-db15dcb37854)
![Screenshot 2024-01-09 090420](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/3b071677-c08c-40bd-b2f4-a09ecb2858c8)

### Steps To Reproduce

1. Go to home page
2. Go to about section
3. Go to terms of condition section
4. Go to privacy policy

### Expected Behavior

there should be padding or margin at the top

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by priyanshagra** [comment]
@nitin10s @tanmoysrt please assign this issue to me

**Comment by pankaj-2503** [comment]
I would raise a pr by fixing this in just few hours.

**Comment by tanmoysrt** [comment]
@priyanshagra you can work on this.
Merge this issue to this one https://github.com/CircuitVerse/CircuitVerse/issues/4551 and close #4551

**Comment by priyanshagra** [comment]
This is the primary issue. Closing #4551 and merging its contents.
