### ISSUE TITLE
In Privacy Policy there is no padding or margin at top of heading🐞 Bug

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4551]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Privacy Policy there is no padding or margin at top of heading,,this is a bad user exxperience
![Screenshot 2024-01-09 090420](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/3b071677-c08c-40bd-b2f4-a09ecb2858c8)

### Steps To Reproduce

1. Go to home page
2. Go to about section
3. Go to Privacy Policy section

### Expected Behavior

there should be padding or margin at the top

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by priyanshagra** [comment]
@nitin10s @tanmoysrt please review my issue

**Comment by SudipMukhejee** [comment]
please assign me in this issue

**Comment by pankaj-2503** [comment]
Yeah i would add a margin top in the privacy section , i would raise a pr in just few hours

**Comment by priyanshagra** [comment]
merging its contents to #4550
