### ISSUE TITLE
Padding or margin is not provided at the bottom of buttons in user dashboard🐞 Bug

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4556]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Padding or margin is not provided at the bottom of buttons in user dashboard ,this is very unprofessional
![Screenshot 2024-01-10 060623](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/7237566c-6ceb-4144-b3cc-68216f5ef528)

### Steps To Reproduce

1. Go to home page
2. Sign in
3. open dashboard

### Expected Behavior

there should be margin and padding at the top

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by priyanshagra** [comment]
@tachyons @tanmoysrt please assign this issue to me

**Comment by tanmoysrt** [comment]
Already fixed by #4455
