### ISSUE TITLE
bug: when block_registration flag enabled it's showing new user text

### ISSUE THREAD

**Issue by tanmoysrt** [CircuitVerse/CircuitVerse#4557]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When `block_registration` enabled from flipper to disable new user registration across website, it's removing sign up button but `New User ?` text left in place. Check screenshot.

![image](https://github.com/CircuitVerse/CircuitVerse/assets/57363826/fa93210c-1455-4277-ad0e-ab7b3eeddcdf)
The `New User?` text should not be there as well.

### Steps To Reproduce

1. Open circuitverse locally
2. Login with admin user
   ```
   username - admin@circuitverse.org
   password - password
   ```
3. Visit `localhost:3000/flipper`
4. Fully enable `block_registration` flag
5. Now, open `localhost:3000` in incognito or wherever you haven't logged in
6. Go to user registration page

### Expected Behavior

The `New User?` text should not be there when registration blocked.

### Are you working on this issue?

No

**Comment by Malavi1** [comment]
can I take the issue!?

**Comment by tanmoysrt** [comment]
> can I take the issue!?

Sure !
