### ISSUE TITLE
No border radius is given for boxes (many for search)🐞 Bug

### ISSUE THREAD

**Issue by priyanshagra** [CircuitVerse/CircuitVerse#4560]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No border radius is given for boxes (many for search) .This is quite a bad user experience practise
![Screenshot 2024-01-10 164719](https://github.com/CircuitVerse/CircuitVerse/assets/127022024/c5a09d41-dabf-42e1-9232-eec1ebd65719)

### Steps To Reproduce

1. Go to home page
2. click on search button

### Expected Behavior

for better user experience there should be some border radius

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by priyanshagra** [comment]
@tanmoysrt please assign this issue to me

**Comment by AyushRakwal** [comment]
i would like to work on this issue ,  if assigned @priyanshagra @tanmoysrt ?

**Comment by pankaj-2503** [comment]
Hey @tanmoysrt  i propose these changes 
![image](https://github.com/CircuitVerse/CircuitVerse/assets/90036864/5df5f8d4-8ca2-4d8e-98ce-1bad68e8aa66)

**Comment by pankaj-2503** [comment]
Hey , @tanmoysrt  i have linked the PR with proposed changes please review this . Thanks.

**Comment by priyanshagra** [comment]
@nitin10s please approve this
