### ISSUE TITLE
Adding back-to-top button 

### ISSUE THREAD

**Issue by antriksh-9** [CircuitVerse/CircuitVerse#4564]
### Is your feature request related to a problem? Please describe

On CV website a back-to-top button isn't present which is a common website feature. 
Helps in moving the through the website smoothly.

### Describe the solution you'd like

I will add the back-to-top button which will appear as soon as website gets scrolled.

### Are you working on this?

Yes

**Comment by antriksh-9** [comment]
Hey @tanmoysrt @Arnabdaz @Prerna-0202 can I proceed?

**Comment by tanmoysrt** [comment]
Duplicate issue of #4510
