### ISSUE TITLE
🐞 Bug: Overflow in medium and small screens.  

### ISSUE THREAD

**Issue by DhairyaMajmudar** [CircuitVerse/CircuitVerse#4575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the forum section of Circuitverse overflow is observed in the medium and small screen sizes. 

### Steps To Reproduce

1. [Visit](https://circuitverse.org/forum)
2. Open developer tools 
3. Open the responsive mode for medium-sized/small-sized devices
4. overflow is observed 

### Expected Behavior

There should be no overflow in the  modes. 

### Screenshots

[Screencast from 2024-01-11 18-35-20.webm](https://github.com/CircuitVerse/CircuitVerse/assets/124715224/3de411df-c50b-4b1a-a7ed-eb8cdc08c121)

### Device Info
```markdown

- OS: Debian Linux
- Browser: FireFox
- version: Latest
```

### Additional context

N/A

### Are you working on this issue?

Yes

**Comment by DhairyaMajmudar** [comment]
@tachyons @tanmoysrt This issue was observed in the forum section pls. review and assign.  
Thank You : )

**Comment by tanmoysrt** [comment]
This issue may be fixed if this issue got fixed #4554. This can be added to the existing issue itself as overflow is part of responsiveness.

**Comment by DhairyaMajmudar** [comment]
> This issue may be fixed if this issue got fixed #4554. This can be added to the existing issue itself as overflow is part of responsiveness.

Sure I will commit the changes in the existing PR and will mention this issue in the PR description.

**Comment by tanmoysrt** [comment]
> > This issue may be fixed if this issue got fixed #4554. This can be added to the existing issue itself as overflow is part of responsiveness.
> 
> Sure I will commit the changes in the existing PR and will mention this issue in the PR description.

Add the description in #4554 issue, else it will tough to track both issue.
