### ISSUE TITLE
Test bench buttons improvement 

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4577]
### Is your feature request related to a problem? Please describe

As shown in the below 3 buttons(**import from CSV, export as CSV, new group**) left and right side are very close to the borders

![Screenshot from 2024-01-11 21-42-12](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/587bd685-afed-42f6-86dc-3af96b7cf2b0)

### Describe the solution you'd like

we have adjust the styling accordingly to make it more clean

![Screenshot from 2024-01-11 21-54-47](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/5fbad67d-5678-4fff-80a9-402c7f50b022)

### Are you working on this?

No

**Comment by AyushRakwal** [comment]
can  i work on this issue @Malavi1  @tanmoysrt  ?

**Comment by tanmoysrt** [comment]
> can i work on this issue @Malavi1 @tanmoysrt ?

Sure, you can work on.
