### ISSUE TITLE
Feature : Adding hover effect to the subscribe and Unsubscribe buttons 

### ISSUE THREAD

**Issue by Madhu-mac** [CircuitVerse/CircuitVerse#4589]
### Is your feature request related to a problem? Please describe

https://github.com/CircuitVerse/CircuitVerse/assets/99901964/ed67df76-e9bb-4333-8763-b82f7cf0532e
<h4>Unsubscribe Button</h4>

![Screenshot_20240113_145516](https://github.com/CircuitVerse/CircuitVerse/assets/99901964/cf538e66-a8c5-4cbd-83af-b7b59e09461f)

### Describe the solution you'd like

Styling subscribe and Unsubscribe buttons with the hover effect same as remaining buttons in the website

### Are you working on this?

Yes

**Comment by Madhu-mac** [comment]
@tanmoysrt @gr455 Verify this issue and please assign it to me!!

**Comment by tanmoysrt** [comment]
This issue has been fixed already. The producttion website hasn't updated.

**Comment by Madhu-mac** [comment]
@tanmoysrt Thanks for letting me know
