### ISSUE TITLE
🐞 Bug: Bad UI of footer in mozilla firefox browser for some width 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4597]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In Mozilla Firefox browser the UI of footer is not responsive as in google chrome browser 
Like incubated from breaks into two lines 

### Steps To Reproduce

1. Open your Mozilla Firefox browser 
2. Go to 'https://circuitverse.org/'
3. scroll to footer section
4. reduce the width and see the error

### Expected Behavior

In Google chrome browser it is working fine

https://github.com/CircuitVerse/CircuitVerse/assets/116784047/473b1292-5b44-4f81-bb84-90c11e3406cf

### Screenshots

**In Mozilla Firefox Browser :-**
![Screenshot from 2024-01-14 12-13-01](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/7a2d03e8-408d-4d24-9450-3b086173215d)
![Screenshot from 2024-01-14 12-13-10](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/c5f29d73-bae1-428b-bf12-de93130e2fcb)

### Device Information [optional]

```markdown
- OS: Linux Mint(Victoria)
- Browser: Mozilla 
- version: 118
```

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
Once verified pls assign this issue to me

**Comment by tanmoysrt** [comment]
Hi @upsaurav12 you can work on this, while raising the PR attach before and after screenshots

**Comment by upsaurav12** [comment]
hey @tanmoysrt the changes are 
***Chrome***
``before``
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/c5a361ed-f779-4c9e-bb03-a1cbc4ef286b)
``after``
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/577cf30a-7eb2-405f-a65f-b7e122e5f301)

***Mozilla***
``before``
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/a43c54ca-51e0-4214-ad71-507be1fa2457)

``after``
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/0238dad9-6cb8-4a50-99e1-fdf51a76e559)


These issue were because some properties of are not supported in mozilla unlikely in chrome like(text-wrap: nowrap)
also there was useless width for ``sponsor-logo-container`` so i changed the bootstrap code for this

**Comment by upsaurav12** [comment]
Hey apologies for inconvinience this issue was because of my side when i updated(again and reset the setting) the firefox then fontsize were reset as issue was resolved

**Comment by tanmoysrt** [comment]
> Hey apologies for inconvinience this issue was because of my side when i updated(again and reset the setting) the firefox then fontsize were reset as issue was resolved

If you feel the issue is not there on the platform, you can close the raised PR and this issue

**Comment by upsaurav12** [comment]
ok but i have seen than there is extra space in container of sponsor-logo(zense) we can utilise that space for other two container
??

**Comment by tanmoysrt** [comment]
> ok but i have seen than there is extra space in container of sponsor-logo(zense) we can utilise that space for other two container
> ??

As previously there was two image, and now only one, it's not looking good. 

That can be improved. You can open a new issue for that.

**Comment by upsaurav12** [comment]
i am sorry which image are u talking about

**Comment by tanmoysrt** [comment]
> i am sorry which image are u talking about

I mean at the side of sponsor logo, there was another one previously, that has been removed few months ago.

**Comment by upsaurav12** [comment]
there was an issue related to this #4563 should i open

**Comment by tanmoysrt** [comment]
> there was an issue related to this #4563 should i open

Ok then we don't need to open a new issue

**Comment by upsaurav12** [comment]
closed the issue
