### ISSUE TITLE
Paragraph style missing in contribution page

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the contribution page everything is center except paragraph(**justified**)

![Screenshot from 2024-01-15 11-45-58](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/687eeea9-cbdb-462a-9c3a-2ca3018d2113)

### Steps To Reproduce

footer->contribute->see bug

### Expected Behavior

We have to make it center 

![Screenshot from 2024-01-15 11-57-05](https://github.com/CircuitVerse/CircuitVerse/assets/112646623/b6e4d384-0cf8-41b4-9d21-ae48c2d39eb6)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by DhairyaMajmudar** [comment]
@Malavi1 shall I take this up if @tanmoysrt approves this.

**Comment by tanmoysrt** [comment]
I think we can keep this to assign to first time contributors, as it's a `good first issue`

> @Malavi1 shall I take this up if @tanmoysrt approves this.

**Comment by ManeetChhabra** [comment]
hello @Malavi1 can i work on this issue?

**Comment by upsaurav12** [comment]
Hey @Malavi1 can i work on this issue??

**Comment by tanmoysrt** [comment]
> hello @tanmoysrt @Malavi1 can i work on this issue?

Sure you can work on.

**Comment by Malavi1** [comment]
Hi, @foad-khan 
Before making PR do follow the contribution guidelines. It's not good practice to make PR without assign
https://github.com/CircuitVerse/CircuitVerse/blob/master/CONTRIBUTING.md
Even if you raise PR definitively mentors won't consider. You did the same thing with this issue IG #4539
cc: @tanmoysrt

**Comment by foad-khan** [comment]
Hello @Malavi1
I am new in open source and very enthusiast about it, I was not much aware of guidelines, very sorry for this next onwards I will surely remember it 
Thank you  🙏

**Comment by Malavi1** [comment]
That's fine @foad-khan 👍
It's all about learning

**Comment by foad-khan** [comment]
Sure! @Malavi1
Please assign me some issue on which I can work on.

**Comment by pankaj-2503** [comment]
hey @tanmoysrt  can you assign me some good first issue so that i became comfortable with CircuitVerse code base and to gain motivation to work forward in my open source journey.

**Comment by Sahil-K123** [comment]
hii @tanmoysrt ,is this issue still open ?

**Comment by upsaurav12** [comment]
> hii @tanmoysrt ,is this issue still open ?

no this issue is already assigned to @ManeetChhabra
