### ISSUE TITLE
Update UI to Bootstrap 5

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#4602]
We are currently using Bootstrap 4. We should update it to latest bootstrap version 5.

**Comment by priyanshagra** [comment]
please assigm me sir

**Comment by upsaurav12** [comment]
> We are currently using Bootstrap 4. We should update it to latest bootstrap version 5.

@tachyons can we make multiple PR'S for this ??

**Comment by DhairyaMajmudar** [comment]
@tachyons @tanmoysrt shall I take this up?

**Comment by Uddancode** [comment]
Hey, @tachyons. Can I take up this issue if it is available for working in it?

**Comment by DhairyaMajmudar** [comment]
Hi @Uddancode can you pls. look for an another issue since I am working on it 

Thank You : )

**Comment by salmoneatenbybear** [comment]
Please assign me this issue @tachyons

**Comment by salmoneatenbybear** [comment]
Thank you @tachyons, will start working !

**Comment by priyanshagra** [comment]
sir i am working on it

**Comment by salmoneatenbybear** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/5109

@tachyons 

pls take a look and please guide me ahead if you find time, thanks a lot !

**Comment by salmoneatenbybear** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/5117

@tachyons @tanmoysrt please take a look
