### ISSUE TITLE
Doc. updation with "pending triage" label 

### ISSUE THREAD

**Issue by Malavi1** [CircuitVerse/CircuitVerse#4606]
`pending triage` is one of the common labels that every issue get, but most of the contributors not getting what exactly the meaning of this so it's good to update the contribution label guidelines with this.

`pending triage` labeled issues are not verified by maintainers

**Comment by tanmoysrt** [comment]
> @Malavi1 can i work on this? My approach will be;
> 
> > updating "pending triage" in - CONTRIBUTING.md file

You can work on this !
