### ISSUE TITLE
🐞 Bug: Code Redundancy in comments thread view.

### ISSUE THREAD

**Issue by senbo1** [CircuitVerse/CircuitVerse#4616]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot from 2024-01-17 02-48-38](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/3815073c-27e9-41c8-a40b-9d17cbf784be)
Previously the position of add comment button was decided by the order in which comments were sorted 
:l (latest comment first)
but now it is placed always at the top but the code was not removed.

### Steps To Reproduce

1. Go to app/views/commentator/threads/_show.html.erb
2. Examine Line No. 74

### Expected Behavior

![Screenshot from 2024-01-17 02-56-48](https://github.com/CircuitVerse/CircuitVerse/assets/102225113/a1ea4ae3-d6fa-494d-bd2c-d0ccf2e08779)
We can remove the conditions since add comment button will always be on top.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by pankaj-2503** [comment]
Hey @tanmoysrt  i would like to work on this can you please assign this to me.

**Comment by tanmoysrt** [comment]
Hi @senbo1 you can work on the issue
