### ISSUE TITLE
Feature : Same background color on hover on teachers and contributors buttons

### ISSUE THREAD

**Issue by pankaj-2503** [CircuitVerse/CircuitVerse#4622]
### Is your feature request related to a problem? Please describe

As if we click on simulator button , the background color sets to light greenish which is applied in website everywhere . But for teachers and contributors buttons have different background color which needs to be same as light greenish which is applied to whole website for better color combination

### Describe the solution you'd like

Before:
![image](https://github.com/CircuitVerse/CircuitVerse/assets/90036864/4ed4b82e-1bbc-475e-bf37-bf1cc69aef25)
After hover:
![image](https://github.com/CircuitVerse/CircuitVerse/assets/90036864/a820bb33-a39d-4a72-a4dc-d454d34b5117)

---
My feature request:
![image](https://github.com/CircuitVerse/CircuitVerse/assets/90036864/0210648b-f91d-4d65-84a8-287ed14bb676)

### Are you working on this?

Yes

**Comment by pankaj-2503** [comment]
Hey @tanmoysrt if you agree with this feature request can you assign this to me so that i can work on this.

**Comment by AyushRakwal** [comment]
can i do this if not done yet @tanmoysrt ?

**Comment by yogeshsshekhawat** [comment]
please assign me this issue

**Comment by tanmoysrt** [comment]
> Hey @tanmoysrt @DhairyaMajmudar , if you agree with this feature request can you assign this to me so that i can work on this.

Sure, on hover you can change it to same primary colour.
