### ISSUE TITLE
Capitalisation error on word "ToolTip" when we hover on Gates in Simulator

### ISSUE THREAD

**Issue by assetlover** [CircuitVerse/CircuitVerse#4630]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When we hover on the gates  icon in simulator a toast (ToolTip) appears on the bottom right corner where the capitalisation error is 
present somewhere it is "Tooltip" and somewhere "ToolTip"

### Steps To Reproduce

1.Go to simulator.
2.Hover on gates.
3. See the toast (Tip) that appears on bottom right of the screen

### Expected Behavior

It should say "ToolTip" in all the toasts.

### Screenshots

![2_image](https://github.com/CircuitVerse/CircuitVerse/assets/109067056/05672b1d-df81-4540-a6c4-3254d50d779d)
![image](https://github.com/CircuitVerse/CircuitVerse/assets/109067056/cd2695eb-f5c5-4b95-bc44-2c31c0ce9b6c)

### Device Information [optional]

```markdown
- OS:Ubuntu 20.04
- Browser:chrome
- version:22
```

### Are you working on this issue?

Yes

**Comment by assetlover** [comment]
@tanmoysrt  it is a small fix pls assign me it would be my first open-source contribution

**Comment by AyushRakwal** [comment]
can i work upon this issue ? @tanmoysrt

**Comment by tanmoysrt** [comment]
Hi @assetlover I didn't get the issue. Can you explain a bit, what is `currently` and what is `expected` ?

**Comment by assetlover** [comment]
> Hi @assetlover I didn't get the issue. Can you explain a bit, what is `currently` and what is `expected` ?

A small toast appears when we hover on gates in simulator somewhere it is written *Tooltip* (small t in tip word) and somewhere it is *ToolTip*(captial T in tip word) it's is a typo basically

**Comment by tanmoysrt** [comment]
> > Hi @assetlover I didn't get the issue. Can you explain a bit, what is `currently` and what is `expected` ?
> 
> A small toast appears when we hover on gates in simulator somewhere it is written _Tooltip_ (small t in tip word) and somewhere it is _ToolTip_(captial T in tip word) it's is a typo basically

oh ok fine you can work on that.
