### ISSUE TITLE
🐞 Bug : Search functions not working properly in 'circuit elements' 

### ISSUE THREAD

**Issue by Simer13** [CircuitVerse/CircuitVerse#4633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot (267)](https://github.com/CircuitVerse/CircuitVerse/assets/113010708/719807df-1b58-4ce7-b9be-b55d71eee106)

The search functionality is not working properly in the simulator's 'circuit elements' bar.

### Steps To Reproduce

1. Go to "https://circuitverse.org/"
2. Click on the 'Simulator' button
3. Search for your desired element in the 'circuit element' division.

### Expected Behavior

It should be displaying the searched elements by the user. 

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by deepak05kr18** [comment]
If the mentors approve this can I work on this .

**Comment by upsaurav12** [comment]
i dont understand what exactly the issue is ??

**Comment by Simer13** [comment]
@upsaurav12 If we search for 'gates' in the circuit elements search bar, it should display All the gates present over there rather than showing 'element not found'.

**Comment by b-harsh** [comment]
@Simer13 @upsaurav12 @deepak05kr18 when we search for "Gate"  we are getting the available gates why do we have to search for the "Gates"   
Correct me if I am wrong .


![Screenshot (48)](https://github.com/CircuitVerse/CircuitVerse/assets/122884578/59c1e6f1-9002-4cbc-831d-58ecf6b00647)

**Comment by Simer13** [comment]
Then I will close this issue as it seems I didn't check it properly. Sorry for the trouble.
