### ISSUE TITLE
Code Optimization Proposal for Enhanced Readability

### ISSUE THREAD

**Issue by deepak05kr18** [CircuitVerse/CircuitVerse#4636]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I noticed a minor inefficiency in the create action of the GroupMembersController. Currently, the Utils.mail_notice method is called twice for the notice, which can be simplified for improved readability and maintainability. I suggest modifying the code as follows:   
```
notice = Utils.mail_notice(group_member_params[:emails], group_member_emails, newly_added)

respond_to do |format|
  format.html { redirect_to group_path(@group), notice: notice }
end
```
This change streamlines the code without altering its functionality. Your consideration is appreciated.

### Steps To Reproduce

In the file CircuitVerse/app/controllers/group_members_controller.rb

### Expected Behavior

The suggested code modification aims to enhance the readability of the create action in the GroupMembersController without altering its existing functionality. After implementing this change, the notice displayed upon redirecting to group_path(@group) should remain consistent with the current behavior, while the code structure becomes more streamlined.

### Screenshots

![Screenshot (30)](https://github.com/CircuitVerse/CircuitVerse/assets/122279122/4f92b745-36cc-4c34-9433-ef84307a6e88)

### Device Information [optional]

```markdown
- OS: Windows
- Browser: Google Chrome
- version: 120.0.6099.225
```

### Are you working on this issue?

Yes

**Comment by deepak05kr18** [comment]
@tachyons @tanmoysrt  please review

**Comment by tanmoysrt** [comment]
Hi @deepak05kr18 go ahead !
