### ISSUE TITLE
Fix linting issues in specs

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#465]
**Describe the bug**
Some of the specs were added before rubocop was added for linting. As a result some of them were written without linting checks. These linting errors needs to be fixed. Check [rubocop](https://github.com/rubocop-hq/rubocop) to see how linting works. 

Linting fixes are required in following directories inside `./spec`
- [controllers](https://github.com/CircuitVerse/CircuitVerse/tree/master/spec/controllers)
- [models](https://github.com/CircuitVerse/CircuitVerse/tree/master/spec/models)
- [factories](https://github.com/CircuitVerse/CircuitVerse/tree/master/spec/factories)

**Separate PRs for fixing linting issues of a group of files are expected**. Let us know which files you are working on by commenting below.

**To Reproduce**
Run `bundle exec rubocop ./spec/`

**Expected behavior**
Should show no offences

**Are you working on this issue? (Yes/No)**
No

**Comment by YashKumarVerma** [comment]
@tachyons, there are linting issues in other files as well, (as of now, the count is at 44k). Will PR addressing those be welcomed?

**Comment by ciphereck** [comment]
@ankitkataria I ran **bundle exec rubocop ./spec/** again, and it's still showing 12 offenses in the latest master branch. Can we reopen this issue?

**Comment by ciphereck** [comment]
@ankitkataria @tachyons  I ran bundle exec rubocop ./spec/ again, and it's still showing 12 offenses in the latest master branch. Can we reopen this issue?
