### ISSUE TITLE
🐞 Bug blank statement is there

### ISSUE THREAD

**Issue by yogeshsshekhawat** [CircuitVerse/CircuitVerse#4653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

blank statement is there

### Steps To Reproduce

Go to 'circuitverse'
Click on '[Learn Logic Design]'
now select [Guidelines] 
Scroll down to Workflow
See error ( the d option is black)
![Screenshot 2023-12-23 103530](https://github.com/CircuitVerse/CircuitVerse/assets/149690978/c719062b-a49f-411c-adca-79e71f81ef27)

### Expected Behavior

![Screenshot 2023-12-23 103612](https://github.com/CircuitVerse/CircuitVerse/assets/149690978/cd00c525-164f-4d5c-ab34-24a6164bed82)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Pradipram** [comment]
@yogeshsshekhawat, Are you still working on this? I am going to work on this.

**Comment by Pradipram** [comment]
This issue is not from this repository. So you can raise this issue on [this](https://github.com/CircuitVerse/Interactive-Book/pulls) repository .

**Comment by yogeshsshekhawat** [comment]
@tanmoysrt please assign me this issue

**Comment by tanmoysrt** [comment]
Raise the issue in this repo https://github.com/CircuitVerse/Interactive-Book
