### ISSUE TITLE
In show password icon there should be cursor pointer

### ISSUE THREAD

**Issue by subhamkumarr** [CircuitVerse/CircuitVerse#4658]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Error view:
https://www.loom.com/share/ebeb4e69a5ec461baefbffe28b784b66?sid=0c0bd295-3e38-4223-8a2d-a57a2defadaf

### Steps To Reproduce

Go to this [https://circuitverse.org/users/sign_in](url) & this [https://circuitverse.org/users/sign_up](url) 

### Expected Behavior

On Password, the show icon cursor should be the pointer.

### Are you working on this issue?

No

**Comment by Pradipram** [comment]
@subhamkumarr Can I work on this?

**Comment by subhamkumarr** [comment]
@Pradipram Yes if you want you can work.

**Comment by igennova** [comment]
Please Assign me

**Comment by Pradipram** [comment]
@igennova There is open PR linked to this issue, so can't work on this issue so look for other issue.

**Comment by tanmoysrt** [comment]
> @subhamkumarr Can I work on this?

You have been assigned !

**Comment by Pradipram** [comment]
@tanmoysrt, I have raised this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/4660). Please have a look into this.
