### ISSUE TITLE
Redesign circuit preloader

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#466]
**Is your feature request related to a problem? Please describe.**
Currently, we have a diamond-shaped preloader for circuits. It would be more appealing to change it to an animation of the logo found [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/public/img/favicon.ico). Suggestions are welcome. 

Current preloader - 
![image](https://user-images.githubusercontent.com/22021150/67668256-982c6380-f995-11e9-83bf-95d5c4f4be59.png)

**Are you working on this? (Yes/No)**
No.

**Comment by fluctix** [comment]
Do you mean something like this 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/40538506/68084752-f78be700-fe5f-11e9-93d4-aecfb5ef0e9c.gif)

**Comment by Shivansh2407** [comment]
Can I work on this issue sir?

**Comment by Potential17** [comment]
Hey,I would Like to contribute for this issue.

**Comment by ciphereck** [comment]
@Potential17 yeah sure. and Let us know your updates please on this thread.
