### ISSUE TITLE
🐞 Bug : Navbar misalligned on Contact Us and Blog (Mobile View)

### ISSUE THREAD

**Issue by lakshaycode22** [CircuitVerse/CircuitVerse#4669]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The toggle menu button appears below the logo in mobile view for Contact Us and Blog pages

### Steps To Reproduce

1. Go to Blog
2. Open the website on mobile or in mobile view on your browser.

### Expected Behavior

The toggle menu button should be at the right side of the screen in alignment with the logo

### Screenshots

<img width="313" alt="Screenshot 2024-01-30 at 9 15 48 PM" src="https://github.com/CircuitVerse/CircuitVerse/assets/87278876/c0aaee2b-345c-4796-905b-a8d1a4d11cdd">

### Device Information [optional]

```markdown
- OS: Mac M1
- Browser: Chrome
- version:
```

### Are you working on this issue?

Yes

**Comment by debghs** [comment]
I would like to work on this.

**Comment by lakshaycode22** [comment]
hi @DhairyaMajmudar, thanks for informing me. Can you please mention the PR?

**Comment by tanmoysrt** [comment]
Hi @lakshaycode22 Thanks for raisng the issue.

- First of all, you should open the issue in respective repo. For Blog, you should open issue in this repo https://github.com/CircuitVerse/Blog/pull/189
- Secondly, before raising issue, please try to go through the issues to check if anyone previously has raised that.

**Comment by lakshaycode22** [comment]
@tanmoysrt, thank you for bringing this to my attention. This was my first time creating an issue, and I initially searched for a similar one in this repository. 
I wasn't aware that there was a separate repository for the blog. I apologize for any inconvenience caused.

**Comment by tanmoysrt** [comment]
> * econdly, before raising issue, please try to go through the issues to check if anyone previously has raised that.

That's fine ! Keep contributing :rocket:
