### ISSUE TITLE
Code auto completion document link not working in setup.md page🐞 Bug

### ISSUE THREAD

**Issue by Gaurav122000** [CircuitVerse/CircuitVerse#4677]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

 Upon clicking the link to access the code auto-completion document, a 404 page not found error is displayed. This is because of the LSP-SETUP.MD path is not present in the master branch of CircuitVerse.

https://github.com/CircuitVerse/CircuitVerse/assets/100744516/ab8c2d6f-988c-4374-b052-97eea86d5464

### Steps To Reproduce

1. Go to the bottom of the CircuitVerse code page (https://github.com/CircuitVerse/CircuitVerse). 
2. Click on the SETUP.md page
3. Then scroll down a little, and you will see a Tool Setup heading
4.  from the tool setup click on the the code auto-completion link. (you see a 404)

### Expected Behavior

![issue](https://github.com/CircuitVerse/CircuitVerse/assets/100744516/3f64299c-79f6-4b91-94d2-b72f8a6329ba)

### Device Information [optional]

```markdown
- OS: git codespace
- Browser: Edge
- version:
```

### Are you working on this issue?

Yes

**Comment by Gaurav122000** [comment]
hi @tanmoysrt sorry for asking late, but I corrected the link can you please check? :)

**Comment by tanmoysrt** [comment]
> hi @tanmoysrt sorry for asking late, but I corrected the link can you please check? :)

sure !
