### ISSUE TITLE
🐞 Bug: Height of elements is not consistent 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Height of ``navbar-searchbar-select`` is not same as other containers or buttons

### Steps To Reproduce

1. Go to https://circuitverse.org
2. open active navbar
3. see the select container

### Expected Behavior

Should be same as other containers

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/89f04672-8427-4e9a-89cc-8f70f1bb8cc8)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
> @tanmoysrt once verified assing me 
> 

ig the height is taking full height of container. It depends on the input heights. 
So I think it's fine. Current state is looking good. 
If we try to make it like other primary buttons it may not looks good.

**Comment by upsaurav12** [comment]
no i am talking about to make height of select container looks like in input container 
like this

**Comment by tanmoysrt** [comment]
> no i am talking about to make height of select container looks like in input container like this ![image](https://private-user-images.githubusercontent.com/116784047/302076627-a233d991-17e9-4078-a693-0ff15bc73a2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcwMjExODksIm5iZiI6MTcwNzAyMDg4OSwicGF0aCI6Ii8xMTY3ODQwNDcvMzAyMDc2NjI3LWEyMzNkOTkxLTE3ZTktNDA3OC1hNjkzLTBmZjE1YmM3M2EyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNFQwNDI4MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjU3YzAyYjU4ZDQwMGM2YWJiNjFlYWJkMWE1NmE5YTIwYjU4ZGE5M2EwYTZmODFkMWQ0ZGVjYWU0MjAyOWFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-mqxox3DnQxSB4voMATVUI_6W4LPww9XFWCwR6PxC-U)

Ok ! You can start working on that issue.

**Comment by SATYAM1000** [comment]
i would like to work on this issue @tanmoysrt

**Comment by upsaurav12** [comment]
> i would like to work on this issue @tanmoysrt

hey @SATYAM1000 this issue was assigned to me and also raised the PR 
so try other issues that are relatively older
