### ISSUE TITLE
Feature : The input bar of contact us page is taking too much length to type message

### ISSUE THREAD

**Issue by pankaj-2503** [CircuitVerse/CircuitVerse#4683]
### Is your feature request related to a problem? Please describe

**Here is the Problem**
---
![image](https://github.com/CircuitVerse/CircuitVerse/assets/90036864/b73df89e-e7d6-41e8-ad10-869228ac8bdd)

### Describe the solution you'd like

The input box should have give spacing just below previous line with not too much spacing. As for a short message it get's filled easily.

### Are you working on this?

Yes

**Comment by pankaj-2503** [comment]
@tanmoysrt  review this issue if it is verified then I can start working on this issue to solve it as soon as possible.

**Comment by tanmoysrt** [comment]
It's part of this theme https://github.com/gethugothemes/northendlab-light-hugo
So probably the issue is in the theme itself, you need to fix there, you can't push the changes.

Although Blog is on a different repo, so from next time raise related issue there https://github.com/CircuitVerse/blog

**Comment by pankaj-2503** [comment]
okay i understand I am not proposing feature request for theme i was just
testing the contact us form .
