### ISSUE TITLE
🐞 Bug:  No gap between the navbar and the title text `Terms of Service.`

### ISSUE THREAD

**Issue by subhamkumarr** [CircuitVerse/CircuitVerse#4694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no gap between the navbar and the title text `Terms of Service.` In Term of Service page.

### Steps To Reproduce

1. Go to the 'About page'.
2. Click on 'Term of Service'.

### Expected Behavior

There should be a gap between the navbar and the title text `Terms of Service.` In Term of Service page.

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/99977240/8383a1e2-dbad-43e3-be46-4c10112bd172)

### Are you working on this issue?

No

**Comment by Pradipram** [comment]
@subhamkumarr, @tanmoysrt Can I work on this issue?

**Comment by subhamkumarr** [comment]
@Pradipram Yes, you can take it.

**Comment by Malavi1** [comment]
Hi, @subhamkumarr , @Pradipram  this issue raised previously #4550
Also while making PR follow the contribution guidelines without maintainers approval if your raise the PR your work will be vain attemt.

cc: @tanmoysrt

**Comment by subhamkumarr** [comment]
@Malavi1 Are you not facing that issue even though this PR https://github.com/CircuitVerse/CircuitVerse/issues/4550 got merged?

**Comment by Pradipram** [comment]
@Malavi1 [#4550](https://github.com/CircuitVerse/CircuitVerse/issues/4550) is closed, but the issue still exists. And since the issue is closed, that way, @subhamkumarr cannot find that this issue already exists.

**Comment by tanmoysrt** [comment]
> @Malavi1 [#4550](https://github.com/CircuitVerse/CircuitVerse/issues/4550) is closed, but the issue still exists. And since the issue is closed, that way, @subhamkumarr cannot find that this issue already exists.

You should check locally. The production website is not always up-to-date.

**Comment by tanmoysrt** [comment]
> @tanmoysrt, I can see the same issue locally also.

I will check, If issue persists, I will re-open

**Comment by subhamkumarr** [comment]
> > @tanmoysrt, I can see the same issue locally also.
> 
> I will check, If issue persists, I will re-open

Sorry, I have checked locally the issue was already resolved.
