### ISSUE TITLE
Circular profile picture instead of rectangular

### ISSUE THREAD

**Issue by Pradipram** [CircuitVerse/CircuitVerse#4697]
#### In the Profile dashboard, the profile pictures are currently displayed in a rectangular shape, and changing them to a circular shape would enhance the overall user experience.
![Screenshot (17)](https://github.com/CircuitVerse/CircuitVerse/assets/101059602/85d8807f-6d67-480e-b224-42c92ee02486)

### Describe the solution you'd like

Change the rectangular profile size to a circular shape like this.

### Are you working on this?

No

**Comment by subhamkumarr** [comment]
@Pradipram @tanmoysrt I would like to work on this issue. Please assign it to me.

**Comment by upsaurav12** [comment]
@subhamkumarr @Pradipram it is advisable for a contributor to wait until the approval from the maintainer because the authenticity of the issue raised is to be checked by the maintainers 
thank you

**Comment by Kiran-pande-30** [comment]
Yeah, a Circular Display Picture will be better, We can Also Add "Digital Characters of the Electrical component" for the display Picture, Something Like Discord, uses.

**Comment by Pradipram** [comment]
@Kiran-pande-30, can you share some images to learn more about your features?

**Comment by Kiran-pande-30** [comment]
@Pradipram, Something Like This, but I think it will be better if we implemented this after we introduce the chatbox. 
![Speaker_Avater](https://github.com/CircuitVerse/CircuitVerse/assets/105718863/39e9ac72-dbeb-4b5f-8c1c-0c0b1b6ca178)

**Comment by tanmoysrt** [comment]
Hi @subhamkumarr 
You have been assigned !
Instead of making it round, just add some border radius.

**Comment by subhamkumarr** [comment]
@tanmoysrt You mean instead of making it circular, I need just to give a `border-radius` a little rounded square?
