### ISSUE TITLE
Trying to use clipboard in menubar results in chaos.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#470]
**Describe the bug**
When you try to paste stuff in menubar's text input fields you accidentally end up pasting it on the simulator.  
**To Reproduce**

**Expected behavior**
Should paste stuff in the input text field and not in the menubar.

**Screenshots**
![8](https://user-images.githubusercontent.com/32474302/67860012-ed59a800-fb42-11e9-955d-c6c9fbb1f774.gif)

**Additional context**
The copy-pasting isn't working even if we don't have any simulator element in the clipboard.

**Are you working on this issue? (Yes/No)**
No

**Comment by shubhankarsharma00** [comment]
As you can see in the screenshot I tried pasting some text in the input text filed but  ended up pasting the recent simulator element onto the simulator just below the field.

**Comment by ShubhamChaudharyy** [comment]
I would like to work on this Bug!

**Comment by shubhankarsharma00** [comment]
@Shivansh2407 are you still working on this?

**Comment by Shivansh2407** [comment]
Yes @shubhankarsharma00 I am working on it. I will be creating two different Listeners for canvas and elements area.

**Comment by shubhankarsharma00** [comment]
@nitin10s can you reopen this?

**Comment by mahmodHammad** [comment]
I have a ready solution for that,
@nitin10s can I make a PR?

**Comment by shubhankarsharma00** [comment]
@mahmodHammad I think you should go ahead with the PR as you have already shared screen recording of you working solution on slack and it was working as intended.

**Comment by mahmodHammad** [comment]
@shubhankarsharma00 
I'm using a different implementation for copy, paste, and cut to make this works.
so I would prefer to discuss that with @satu0king  before opening the PR  
i was fixed at #1313 but it included much work that will be done during GSOC so I closed it for now

**Comment by mahmodHammad** [comment]
if @satu0king  agree i will extract the implementation from #1313  to a separate PR
