### ISSUE TITLE
🐞 Bug: No gap between the navbar and the title text `Privacy`  in Privacy Policy page. 

### ISSUE THREAD

**Issue by subhamkumarr** [CircuitVerse/CircuitVerse#4703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There is no gap between the navbar and the title text `Privacy`. On the Privacy Policy page.

### Steps To Reproduce

1. Go to the 'About page'.
2. Click on 'Privacy Policy'.

### Expected Behavior

There should be a gap between the navbar and the title text  `Privacy.` On the Privacy Policy page.

### Screenshots
![image](https://github.com/CircuitVerse/CircuitVerse/assets/99977240/dbf335bb-b8e2-4b5f-8324-7888c1918dd5)

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
i think this issue can be done with the issue #4694 
cc @tanmoysrt

**Comment by tanmoysrt** [comment]
Already done via #4550
