### ISSUE TITLE
🐞 Bug : Clickable Under-lined Words Needs to be Change to a Button

### ISSUE THREAD

**Issue by Kiran-pande-30** [CircuitVerse/CircuitVerse#4706]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On the Website there are many instances where the words are just underlined.
![Screenshot 2024-02-05 202307](https://github.com/CircuitVerse/CircuitVerse/assets/105718863/d2bf55f4-c923-40cc-9495-437a09dadeed)
![Screenshot 2024-02-05 202553](https://github.com/CircuitVerse/CircuitVerse/assets/105718863/b8b9455f-6074-4784-b8ec-a5553e119b67)

### Steps To Reproduce

1. Go to the Home Page
2. And See "Learn Logic Design".

### Expected Behavior

There Should be a clickable Button

### Device Information [optional]

```markdown
- OS: Windows 11
- Browser: Chrome
```

### Are you working on this issue?

Yes

**Comment by tanmoysrt** [comment]
Hi @nitin10s , WDYT, should we moved the text buttons to Outlined button ?

**Comment by tanmoysrt** [comment]
> @tanmoysrt can you assign this issue to me?

If @Kiran-pande-30 like to pass the issue, then I can.

**Comment by Shahbaz898414** [comment]
> > @tanmoysrt can you assign this issue to me?
> 
> If @Kiran-pande-30 like to pass the issue, then I can.

@Kiran-pande-30 are interested to pass me?

**Comment by tanmoysrt** [comment]
Usually, we assign people in FIFO as people have commented. Now if the issue creator has marked `Are you working on this issue?` as `Yes`, then he wiill be assigned. If we like to pass then next person will be assigned.

After assigning, if we find out more than 3~4 weeks of inactivity, then we can reassign to next person

**Comment by Kiran-pande-30** [comment]
@tanmoysrt I am interested in resolving the issue
Sorry, @Shahbaz898414 i will be working on the issue.

**Comment by Kiran-pande-30** [comment]
@tanmoysrt I have not been assigned the issue yet.

**Comment by upsaurav12** [comment]
@Kiran-pande-30 for ``Learn Logic Design`` there is already merged PR
 https://github.com/CircuitVerse/CircuitVerse/pull/4472
 But you can work on other

**Comment by Kiran-pande-30** [comment]
That's good to know, about the merge PR, Thanks @upsaurav12

**Comment by upsaurav12** [comment]
> That's good to know, about the merge PR, Thanks @upsaurav12

yes but you can still work for other pic or may more you find the similar issues

**Comment by Kiran-pande-30** [comment]
> lar yeah, but #4472 is closed and this issue as not been assigned to me yet.

**Comment by tanmoysrt** [comment]
Hi @Kiran-pande-30 , you can replace `back` button with outlined buttons

**Comment by Kiran-pande-30** [comment]
@tanmoysrt I have surfed through the application and I don't think there are any issues now.
