### ISSUE TITLE
Can't resize menubar after it is collapsed.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#471]
**Describe the bug**
We can't resize the menubar once it is resized to a size where it almost collapses.
**Screenshots**
![9](https://user-images.githubusercontent.com/32474302/67861205-aae59a80-fb45-11e9-879e-553c40fc6afc.gif)

**Additional context**
I would like to point out that it resets when the page is reloaded.
I think when people see their circuit's simulation they would want to collapse the sidebar.
**Are you working on this issue? (Yes/No)**
No

**Comment by shubhankarsharma00** [comment]
Can be closed by #827

**Comment by satu0king** [comment]
Resolved
