### ISSUE TITLE
🐞 Bug: Scrolling to wrong positon when clicking on feature

### ISSUE THREAD

**Issue by Pradipram** [CircuitVerse/CircuitVerse#4710]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

On clicking on the feature button, It is not scrolling to the feature section; instead, it is scrolling to the below part of features.
[Screencast from 09-02-24 10:05:03 PM IST.webm](https://github.com/CircuitVerse/CircuitVerse/assets/101059602/dac85908-51e2-4e50-bb83-6a41813cdd45)

### Steps To Reproduce

1. Go to 'https://circuitverse.org/'
2. Click on the feature present in the navbar
3. see the error 

### Expected Behavior

On clicking the feature, It should scroll down to the feature section, showing the correct heading. properly

### before
[Screencast from 09-02-24 10:05:03 PM IST.webm](https://github.com/CircuitVerse/CircuitVerse/assets/101059602/0e09683f-216a-4280-8085-a032f47fb8dd)

### after
[Screencast from 09-02-24 10:13:01 PM IST.webm](https://github.com/CircuitVerse/CircuitVerse/assets/101059602/8015d568-ef71-4413-88ed-e17feba9e280)

### Device Information [optional]

```markdown
- OS: Ubuntu 22.04
- Browser: Chrome
- version: Version 121.0.6167.139 (Official Build) (64-bit)
```

### Are you working on this issue?

Yes

**Comment by APS-1926** [comment]
can i work on this issue

**Comment by Pradipram** [comment]
@APS-1926, I have raised a [PR](https://github.com/CircuitVerse/CircuitVerse/pull/4711), which is still open, so please look for other raised issues.

**Comment by APS-1926** [comment]
Sure

**Comment by upsaurav12** [comment]
> @APS-1926, I have raised a [PR](https://github.com/CircuitVerse/CircuitVerse/pull/4711), which is still open, so please look for other raised issues.

hey @Pradipram you need to get assigned by the maintainers so pls dont raise without getting assigned

**Comment by Pradipram** [comment]
@tanmoysrt @tachyons, Please assign me this issue.
