### ISSUE TITLE
🐞 Bug: only space cant be the name of the assignment 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

while creating new assgnment when the user enter only space bar then it should show an error like this 
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/b00039a3-f435-412f-a942-37a0177f75c1)
similar when making a new group name

### Steps To Reproduce

1. Go to circuitvere website 
2. create a new group 
3. and try to name space as a group name 

### Expected Behavior

![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/37e4fc26-de48-45c1-a7df-9ed6c041192e)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
@tanmoysrt pls review this and assign me

**Comment by tanmoysrt** [comment]
> @tanmoysrt pls review this and assign me

Your `issue` and `expected behaviour` image is exactly same. I didn't get the issue

**Comment by upsaurav12** [comment]
the image is of ``when a user creating a new group`` and second is ``when the user is creating a new assignment`` 
when the user creating a new assignment and when the user enter `` `` space only then it should show error like the 1st image that i provided
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/5b93b999-27a7-4de9-9be4-eb52fc2d6671)

``result is this``
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/69da2d9a-642f-483a-b0e4-5cbe3a769518)

**Comment by tanmoysrt** [comment]
> the image is of `when a user creating a new group` and second is `when the user is creating a new assignment` when the user creating a new assignment and when the user enter ` ` space only then it should show error like the 1st image that i provided ![image](https://private-user-images.githubusercontent.com/116784047/303851400-5b93b999-27a7-4de9-9be4-eb52fc2d6671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODMzMDEsIm5iZiI6MTcwNzU4MzAwMSwicGF0aCI6Ii8xMTY3ODQwNDcvMzAzODUxNDAwLTViOTNiOTk5LTI3YTctNGRlOS05YmU0LWViNTJmYzJkNjY3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxNjM2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYzdmM2MxNmY4NzliMmZiMGQwZGQ1MzI3ZGM0MzhlZTgyNzRlZjI5MWEwMDg2OTk0ZmY2MTNjYmI2NzJhNmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cUSfUoAlDNXWZbdHvICKKMHJj5zo0JoCAqdjUy5Bac4)
> 
> `result is this` ![image](https://private-user-images.githubusercontent.com/116784047/303851432-69da2d9a-642f-483a-b0e4-5cbe3a769518.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1ODMzMDEsIm5iZiI6MTcwNzU4MzAwMSwicGF0aCI6Ii8xMTY3ODQwNDcvMzAzODUxNDMyLTY5ZGEyZDlhLTY0MmYtNDgzYS1iMGU0LTVjYmUzYTc2OTUxOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMFQxNjM2NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmRjN2ZiMDlkMzM1MDk1NjVmMzYwMTU1MDU5OTZhODIwNTY3NmYzZjJjYTUyMDZmZWNkOWM1ZjA1ZmE3NDdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.4pZJBzq7cQ9L-9L4zJrFDs34GeJar9NSqbgnEHYfNE4)

Got it, you can work on this.
