### ISSUE TITLE
🐞 Bug: Disappearing of CLOSE Button in mobile and tab view

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4715]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

IN assignment page ``close`` button is not present in ``mobile and tab``
**mobile view**
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/159937da-ea15-4e11-8649-6dbf33babc46)

**desktop view**
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/371d886a-e23e-4b9e-94fb-c74678046af9)

### Steps To Reproduce

1. Create a group 
2. create a new assignment 
3. and see the assignment page 
4. and now inspect the page in mobilke view

### Expected Behavior

``close button`` should be there as in desktop view

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by DhairyaMajmudar** [comment]
@upsaurav12 shall I take this up if @tanmoysrt approves this ?

**Comment by upsaurav12** [comment]
yeah sure

**Comment by subhamkumarr** [comment]
Can i work on this issue? @upsaurav12

**Comment by upsaurav12** [comment]
> Can i work on this issue? @upsaurav12

i am interested to giving this issue to @DhairyaMajmudar as he asked me first so

**Comment by subhamkumarr** [comment]
if @DhairyaMajmudar approve can i take this issue?

**Comment by upsaurav12** [comment]
> if @DhairyaMajmudar approve can i take this issue?

ask @DhairyaMajmudar

**Comment by DhairyaMajmudar** [comment]
I think I should take this up, @subhamkumarr can you pls. look for an another issue : )

**Comment by tanmoysrt** [comment]
> I think I should take this up, @subhamkumarr can you pls. look for an another issue : )

You can work on the issue

**Comment by SATYAM1000** [comment]
can i work on this issue ?

**Comment by DhairyaMajmudar** [comment]
Hi @SATYAM1000 thanks for showing interest, but this issue is already solved by mentioned PR, pls. look for another issue. : )

**Comment by SATYAM1000** [comment]
Hey, how to know that the issue is open or closed?

**Comment by DhairyaMajmudar** [comment]
You can check top left icon , if is green then issue is open or if it is red / violet then issue is completed.
