### ISSUE TITLE
🐞 Bug: un-updated image in the teacher section

### ISSUE THREAD

**Issue by subhamkumarr** [CircuitVerse/CircuitVerse#4720]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug
The image in the teacher section 'Post assignment' is this: `close button`  is missing.

![image](https://github.com/CircuitVerse/CircuitVerse/assets/99977240/02c16731-eb23-4122-aa3b-f9b7a614ab12)

### But there should be this image with `Close button`: in the `Post Assignment`  section
![image](https://github.com/CircuitVerse/CircuitVerse/assets/99977240/71240b34-1d41-41de-b33e-ed9a02792700)

### Steps To Reproduce

1. Go to the 'Teacher' section
2. Scroll down to `Post Assignment`
3. See the image error

### Expected Behavior

There should be an updated image.

### Are you working on this issue?

Yes

**Comment by subhamkumarr** [comment]
@tanmoysrt Please assign this issue to me.

**Comment by tanmoysrt** [comment]
@subhamkumarr Go ahead

**Comment by SATYAM1000** [comment]
I would like to work on this issue @tanmoysrt

**Comment by subhamkumarr** [comment]
@SATYAM1000 I'm working on this issue, and it's already assigned.
You can look in other open issues.
