### ISSUE TITLE
🐞 Bug: No use of  `close button` 

### ISSUE THREAD

**Issue by subhamkumarr** [CircuitVerse/CircuitVerse#4722]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There should be no `Close Button` as it has no use. It is behaviour is the same as the `View Button` behavior.

## Error view:

https://github.com/CircuitVerse/CircuitVerse/assets/99977240/45122197-6d8a-4917-801a-0060a063873b

### Steps To Reproduce

1. Go to `Add Group`
2. Add `Assignment`
3. Check the behavior of `View` & `Close`
4. No use to close button

### Expected Behavior

There should be no `Close` button as it is behaving exactly the same as the `View` button.

### Are you working on this issue?

Yes

**Comment by subhamkumarr** [comment]
@tachyons Can I work on this issue?

**Comment by upsaurav12** [comment]
i dont think it is an issue it is use to close whenever the user wants to close the issue

**Comment by subhamkumarr** [comment]
@upsaurav12 I have tested it has no use

**Comment by tanmoysrt** [comment]
Hi @subhamkumarr , if it's not working, that doesn't mean that `close` button is useless. Maybe it's not working as expected. ig it's there to close the assignment. 
You should raise issue to fix that, not to remove that.

**Comment by subhamkumarr** [comment]
@tanmoysrt Can I update this issue and make this a feature? and make close button functional?

**Comment by upsaurav12** [comment]
> Hi @subhamkumarr , if it's not working, that doesn't mean that `close` button is useless. Maybe it's not working as expected. ig it's there to close the assignment. You should raise issue to fix that, not to remove that.

from my side it is absolutely working no need to remove this cc @tanmoysrt

**Comment by tachyons** [comment]
https://docs.circuitverse.org/#/chapter2/2cvforeducators?id=add-assignments you can find more about assignments here
