### ISSUE TITLE
🐞 Bug: put no of notification over the bell-icon 

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4724]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

in mobile view, the number of notifications should be over the bell-icon same as the desktop view 
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/8ebf18d7-bf22-43d4-bc82-c58df22f571c)

### Steps To Reproduce

1. Go to Circuitverse 
2. check the bello icon in nav-bar 
3. check this in mobile view or smaller width 

### Expected Behavior

![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/0e35e9a8-f534-4063-8b32-76e1cc8897a8)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by upsaurav12** [comment]
i am working on this issue

**Comment by tanmoysrt** [comment]
Will be fixed by #4705
