### ISSUE TITLE
Add a view for viewing all custom emails sent

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#473]
**Is your feature request related to a problem? Please describe.**
Custom email functionality for admins was added in #423. Check out #419 for detailed feature description. Currently, there is no way to view all the custom emails that have been sent so far. 

**Describe the solution you'd like**
Create another view only visible to the admins where they can view all the custom emails that have been sent, with relevant information such as who the email is composed by, has it been sent or not etc.

**Are you working on this? (Yes/No)**
No

**Comment by shipcy** [comment]
I want to take this issue. Can I?
