### ISSUE TITLE
🐞 Bug: Users have to re-enter their password

### ISSUE THREAD

**Issue by antriksh-9** [CircuitVerse/CircuitVerse#4739]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When a user tries to login to CircuitVerse website and fill all the details (email and password) but fails to verify re-CAPTCHA then reCAPTCHA verification process encounters a failure, and despite the absence of any password error, users are still required to re-enter their passwords.

The problem: 

https://github.com/CircuitVerse/CircuitVerse/assets/132576984/43fb5862-fde3-4c7d-9c2f-ecdcb2aebfd8

### Steps To Reproduce

1. Go to the CircuitVerse login page.
2. Fill the details (email and password).
3. Skip the re-CAPTCHA verification process and try to login.
4. Click on login button and see the bug.

### Expected Behavior

Users need not to re-enter their password when the re-CAPTCHA verification fails. 
Only re-CAPTCHA verification process should be done again.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by antriksh-9** [comment]
Hey @tanmoysrt @Arnabdaz I would like to work on this issue.

**Comment by adarsh7raj** [comment]
Hey when i log in to the circuit verse website i do not see any issue of re entering the password instead i see this :re captcha failed.

https://github.com/CircuitVerse/CircuitVerse/assets/130682848/1afa7317-adb3-45cc-a0a5-20ad651cacad

**Comment by tanmoysrt** [comment]
Hi @antriksh-9 , this is a standard practice.

After you submit the form with username, password, re-captcha info, it goes to server and it verifies usually all  the data. If it fails anyhow, no web service should return the submitted info to that page.

Now, you can check the e-mail pre-filled for user convenience, as it's doesn't come under secrets in  your browser. For password, it shouldn't send back the info to browser.

**Comment by tanmoysrt** [comment]
> Hey when i log in to the circuit verse website i do not see any issue of re entering the password instead i see this :re captcha failed.
> 
>  Untitled.video.-.Made.with.Clipchamp.mp4

That's autofill by your browser. The server had not sent back the password to that form.

**Comment by antriksh-9** [comment]
Okay thanks, for clarifying.
