### ISSUE TITLE
Search Bar needs improvement

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#474]
**Is your feature request related to a problem? Please describe.**

The search bar on <a href="https://docs.circuitverse.org/">docs page</a> needs to be differentiated from the rest of the sidebar, maybe adding a search button and input box with a search icon may help and also, fix that cross button, it is too small and also it needs to differentiated from rest of the text, so maybe making it red will help.

**Additional context**

![search](https://user-images.githubusercontent.com/42115530/67972026-e199de80-fc33-11e9-972b-9addf1f8d418.PNG)

**Comment by ShreyaPrasad1209** [comment]
This issue is meant for CircuitVerse Docs and is already opened at https://github.com/CircuitVerse/CircuitVerseDocs/issues/143
