### ISSUE TITLE
🐞 Bug : Footer alignment and icon format inconsistencies on large devices.

### ISSUE THREAD

**Issue by Pawank06** [CircuitVerse/CircuitVerse#4764]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

   • Footer items are aligned to the left instead of being distributed across both sides.
   • The copyright section text is not centered, and there's a need for a divided line separating it from the upper section.
   • Icons in the footer appear messy and should be replaced with SVG format for better scalability and clarity.

   ![image](https://github.com/CircuitVerse/CircuitVerse/assets/117660893/3cf0cc5c-ccf6-48b8-a89c-a1ba49538660)

### Steps To Reproduce

   1. Access the website on a large device.
   2. Scroll down to the footer section.
   3. Observe the alignment of footer elements and the presentation of icons.
   4. Additionally, use the Pesticide Chrome/Firefox extension to inspect the alignment more accurately.

### Expected Behavior

    1. Footer items should be evenly distributed across both sides for better balance.
    2. The copyright text should be centered and visually separated from the upper section by a divided line.
    3.  Icons should be replaced with SVG format to improve clarity and scalability.

### Device Information [optional]

```markdown
- OS: Ubuntu
- Browser: Firefox
- version: 22.04
```

### Additional context

There is already an issue despite previous attempts to address it, as well as the need for a comprehensive solution rather than focusing solely on individual elements.

### Are you working on this issue?

Yes

**Comment by RajiaRani** [comment]
hello, @Pawank06 , i know that how to fix this issues, we change  need to change the style properties...i will resolve this issues, please can you assign me this issue...thankyou

**Comment by Pawank06** [comment]
> hello, @Pawank06 , i know that how to fix this issues, we need to change the style properties...i will resolve this issues, please can you assign me this issue...thankyou

Hey, It's great that you want to work on this issue, but I'm sorry to say that I have already solved this bug on my local machine. I'm currently awaiting the community member's review of the issue.

**Comment by Asrani-Aman** [comment]
same issue have been created already #4563 
(https://github.com/CircuitVerse/CircuitVerse/issues/4563#issue-2074861126)

**Comment by Pawank06** [comment]
> same issue have been created already #4563 ([#4563 (comment)](https://github.com/CircuitVerse/CircuitVerse/issues/4563#issue-2074861126))

Are you working on it?

**Comment by Asrani-Aman** [comment]
Yes
