### ISSUE TITLE
🐞 Bug : next button present on last page 

### ISSUE THREAD

**Issue by Ashish12-tripathi** [CircuitVerse/CircuitVerse#4768]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Issue: On the CircuitVerse website  https://circuitverse.org/?page=71117#recent, in the Recent Circuits section, the "Next" button is present even on the last page. However, since it serves no function on the last page, its presence might confuse users.

.

### Steps To Reproduce

.

### Expected Behavior

 Remove the "Next" button when users are on the last page of the Recent Circuits section to provide a clearer and more intuitive user experience

### Screenshots

![Screenshot 2024-02-25 232306](https://github.com/CircuitVerse/CircuitVerse/assets/156857802/bb9d4a1f-67d7-4550-84e4-fb738564ace5)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by Ashish12-tripathi** [comment]
@tanmoysrt Can you please review this  issue ?

**Comment by tanmoysrt** [comment]
Hi @Ashish12-tripathi don't remove buttons. It's already disable that my the style for disabled button doesn't differentiate for active button. You can update the style of `Prev` and `Next` button if disabled.

**Comment by tanmoysrt** [comment]
It will be solved in this issue #4754.

**Comment by Ashish12-tripathi** [comment]
> Hi @Ashish12-tripathi don't remove buttons. It's already disable that my the style for disabled button doesn't differentiate for active button. You can update the style of `Prev` and `Next` button if disabled.

okay got it...
