### ISSUE TITLE
Import saved circuit from local desktop option

### ISSUE THREAD

**Issue by Shweta0002** [CircuitVerse/CircuitVerse#477]
Problem:
There is a option available for saving circuits as png , jpeg etc and exporting circuits , But what if i want to reopen my circuit on Circuit Verse which i already saved on my local desktop and want to edit it. 

Requirement
Create a option for **importing** already saved circuits in local PC , for editing purpose.

 One can upload the file saved with the extension for circuits and then reopen it and edit it .
![CircuitVerse](https://user-images.githubusercontent.com/40588060/67981746-50ccfe00-fc47-11e9-94b4-a3669525ea5e.png)

I am starting working over this . If anyone can suggest more, feel free to contact.

**Comment by kushthedude** [comment]
@Shweta0002 Nice suggestion, it would definitely come handy
