### ISSUE TITLE
🐞 Bug: Typo error in Documentation of Contributing in circuitverse primary repository

### ISSUE THREAD

**Issue by upsaurav12** [CircuitVerse/CircuitVerse#4772]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In this pic you can see the typo error of Communtiy it should be as "Community"
![image](https://github.com/CircuitVerse/CircuitVerse/assets/116784047/e1b1c66f-be74-48f8-8f54-342c9e44b8b4)

### Steps To Reproduce

1. Go to primary circuitverse repo
2. GO to Contribtiing.md
3. 

### Expected Behavior

there should no typo error 

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by upsaurav12** [comment]
@tanmoysrt can review this issue

**Comment by tanmoysrt** [comment]
Hi @upsaurav12 you can work on this. Also add `pending triage` label and it's meaning in the labels list

**Comment by upsaurav12** [comment]
hi @tanmoysrt ``pending triage`` is already there in issue labels
