### ISSUE TITLE
Change of Readme to clearly explain gitpod usage

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#478]
**Is your feature request related to a problem? Please describe.**
While going through the development environment, I found Set up in cloud section not placed at the right position and not clearly stated.

**Describe the solution you'd like**
The readme could be updated with the following steps to be clear and precise.
1) Setup in cloud can be done using gitpod.
2) Click on the gitpod toggle.
3) Wait for it to load, once done it will open in the same tab of your browser.

The above points can be added and the whole section should be moved directly under the Docker section to give better clarity.

**Comment by ankitkataria** [comment]
Fixed in #618
