### ISSUE TITLE
Feature : Splitter not present in Misc Circuits 

### ISSUE THREAD

**Issue by Simer13** [CircuitVerse/CircuitVerse#4780]
### Is your feature request related to a problem? Please describe

![Screenshot (311)](https://github.com/CircuitVerse/CircuitVerse/assets/113010708/451e999e-43ac-4cc1-abea-b53c26d0f236)

![Screenshot (310)](https://github.com/CircuitVerse/CircuitVerse/assets/113010708/05f81851-853d-426d-af8e-524969e4ada5)

### Describe the solution you'd like

The 'splitter' is mentioned in the docs of circuitverse but if you checkk out the 'misc' in the 'circuit elements' it is not present over there. It is better to remove any extra unnecessary documentation that might confuse user's when they need particular circuits.  

### Are you working on this?

Yes

**Comment by Simer13** [comment]
@tanmoysrt can you please review this ?

**Comment by yashmangal112** [comment]
@Simer13 please assign this issue to me.

**Comment by tanmoysrt** [comment]
cc @Arnabdaz @Prerna-0202

**Comment by Simer13** [comment]
@yashmangal112 Sorry but I cannot assign as I am also a contributor here like you.

**Comment by sethbassetti** [comment]
Scroll up in the misc tab and you'll find the splitter

**Comment by Arnabdaz** [comment]
closing as splitter is already there in the misc section
