### ISSUE TITLE
Feature : Redirect to simulator signout page instead of circuitverse.org

### ISSUE THREAD

**Issue by pankaj-2503** [CircuitVerse/CircuitVerse#4785]
### Is your feature request related to a problem? Please describe

When user is signed in and using simulator then after signing out it redirects to https://circuitverse.org/  , rather it should be on same page when you are giving simulator access for free.

### Describe the solution you'd like

If it's free to use then  it should redirects to same page of simulator with sign out message rather redirecting to circuitverse.org.

### Are you working on this?

Yes

**Comment by tanmoysrt** [comment]
It's the expected behaviour to redirect to homepage once logged out. The user maybe working on a private circuit, we shouldn't redirect ti simulator.

**Comment by pankaj-2503** [comment]
I understood this
