### ISSUE TITLE
Words missing in the tagline

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#479]
**Is your feature request related to a problem? Please describe.**
Under 'teachers' and 'Create Groups', the statement makes no relevance. It has missing words.

**Describe the solution you'd like**
It can be changed to the following:
Teachers can create groups and **add** their students to them!

**Additional context**
![Capture](https://user-images.githubusercontent.com/42520146/68004877-1e4bf100-fc99-11e9-8b17-3b34d889b452.PNG)

**Comment by CodeSarthak** [comment]
Hi, 

How does this look?
![groups-text-missing](https://user-images.githubusercontent.com/24937677/68023666-dabfaa00-fccd-11e9-8473-2c8ace6b1feb.png)

**Comment by sakshi1499** [comment]
It looks great. :)
