### ISSUE TITLE
🐞 Bug: CircuitVerse Forum returns 404 Error

### ISSUE THREAD

**Issue by ForgottenMachines** [CircuitVerse/CircuitVerse#4791]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The CircuitVerse discussion forum returns a 404 error.   https://circuitverse.org/forum

Even when trying to access from the main menu -> Help -> Forum, it still gives the 404 error.  Hopefully the Forum is still out there somewhere.  

### Steps To Reproduce

1. CircuitVerse Main Menu
2. Help
3. Forum

### Expected Behavior

It's supposed to go to the Forum, but it doesn't, so something is cearly wrong with the Forum, or the URL given for the Forum.

### Screenshots

![image](https://github.com/CircuitVerse/CircuitVerse/assets/79030181/50fe3662-7824-4442-af80-4034f46e160b)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

No

**Comment by tanmoysrt** [comment]
Forum disabled temporarily for spamming issues and lack of moderation control.
