### ISSUE TITLE
Feature : Allowing users to copy and paste a section or whole circuit within one or multiple projects

### ISSUE THREAD

**Issue by Abhinav1148** [CircuitVerse/CircuitVerse#4798]
### Is your feature request related to a problem? Please describe

When you are working on big circuits you might need to make a sub circuit multiple time. And currently CircuitVerse simulator allows to copy only one element at a time, which reduces the efficiency of the user and increases the circuit building time.

### Describe the solution you'd like

Some circuit simulation software like LT Spice provide this feature, and we can recreate that to enhance the user experience. We can also add a feature that allows a user to copy a circuit and use it in other currently open projects as well. The video depicting the idea of the feature is attached below :

https://github.com/CircuitVerse/CircuitVerse/assets/120770920/46c3fdce-1937-452b-892d-ed50c460a6e3

### Are you working on this?

Yes

**Comment by Abhinav1148** [comment]
@tanmoysrt please review this issue

**Comment by tanmoysrt** [comment]
This is already implemented.
Keep pressing `Shift` and select a portion of circuit and then you can copy paste that.
