### ISSUE TITLE
Alignment issue on home page

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#482]
**Is your feature request related to a problem? Please describe.**
Padding is required in the read more section. It looks unaligned. 

**Describe the solution you'd like**
Padding of 20px or so can be added to make it appear better.

**Additional context**
Screenshot of the same has been attached.

![alignment](https://user-images.githubusercontent.com/42520146/68005748-40933e00-fc9c-11e9-8e24-9d18b1bf1ea8.PNG)

**Comment by junron** [comment]
We can use [flexbox](https://jsfiddle.net/2467mgn5/2/) for this, instead of hardcoding paddings, which may not work well if the text length changes later.

**Comment by sakshi1499** [comment]
Definitely, That'll be a better option :)

**Comment by Ananthavijay** [comment]
@tachyons this can be closed, old UI.
