### ISSUE TITLE
Invalid email ids also accepted in group

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#483]
**Is your feature request related to a problem? Please describe.**
While making a group and adding members to it, I added invalid email id namely sakshi@test but no filter stopped it and I received acceptance alert.

**Describe the solution you'd like**
Email id attribute should be added in the html page input tag.

**Additional context**
Find below the screenshot of the alert I received.

![invalidalert](https://user-images.githubusercontent.com/42520146/68007217-e5b01580-fca0-11e9-8e44-87d73c3c92d2.PNG)

**Comment by Shivansh2407** [comment]
I guess This has been fixed in PR #891

**Comment by Ananthavijay** [comment]
@tachyons This can be closed
