### ISSUE TITLE
Bootstrap missing in button

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#484]
**Is your feature request related to a problem? Please describe.**
Bootstrap is missing in create assignment button.

**Describe the solution you'd like**
Bootstrap is not added in the button.

**Additional context**
While some buttons look like below, the create assignment button lacks bootstrap.

![Bootstrap](https://user-images.githubusercontent.com/42520146/68007431-9d452780-fca1-11e9-9a54-3a709b80be18.PNG)
![withboot](https://user-images.githubusercontent.com/42520146/68007456-b1892480-fca1-11e9-8faa-76ac2b215291.PNG)

**Comment by Ananthavijay** [comment]
@tachyons This can be closed.
