### ISSUE TITLE
Different countdown times for assignment

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#485]
**Is your feature request related to a problem? Please describe.**
The countdown time for the same assignment varies once opened.

**Describe the solution you'd like**
The countdown should be synced.

**Additional context**

![error](https://user-images.githubusercontent.com/42520146/68007645-37a56b00-fca2-11e9-8806-444256d556b6.PNG)
![error1](https://user-images.githubusercontent.com/42520146/68007647-383e0180-fca2-11e9-8802-1cf7510b399f.PNG)

**Comment by Shivansh2407** [comment]
Can you please let me know how to proceed with this @sakshi1499 ?

**Comment by aayush-05** [comment]
This isn't a bug I guess. The time remaining acts as a countdown, and the remaining time will change as the time passes by @tachyons @nitin10s

**Comment by nitin10s** [comment]
The first time remaining is the actual time remaining [fixed].
The second time remaining is the countdown [varying]. Right?

**Comment by aayush-05** [comment]
Yes @nitin10s , the first one mentions that certain date, so that is fixed. And the second one is just a timer on how much time is left, so it is bound to change as time passes.

**Comment by nitin10s** [comment]
So the first one should be renamed to Deadline rather than Time Remaining. Time remaining can be confusing.

**Comment by aayush-05** [comment]
Didn't get you, the first one is already named Deadline.
![image](https://user-images.githubusercontent.com/47032027/81496160-2aada800-92d3-11ea-912e-9576cb42fa95.png)
![image](https://user-images.githubusercontent.com/47032027/81496161-2da89880-92d3-11ea-8dc0-9c9ab7004075.png)
Maybe we can add the time remaining around parenthesis to make it more clear ?

**Comment by aayush-05** [comment]
This must get fixed by #1629
