### ISSUE TITLE
Remove JQuery dependency

### ISSUE THREAD

**Issue by aryanndwi123** [CircuitVerse/CircuitVerse#4859]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Remove jQuery and use native DOM methods in it.

### Steps To Reproduce

1. Go to Main repository (CircuitVerse).

### Expected Behavior

The main repository's codebase still relies on jQuery, which should be replaced with native DOM JavaScript since jQuery is no longer used in the CircuitVerse.

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tachyons** [comment]
No need to remove jquery from the legacy simulator
