### ISSUE TITLE
Add alert for all options

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#486]
**Is your feature request related to a problem? Please describe.**
Alert pops up when any element in the input or output option in simulator is hovered but this does not happen in the rest of the options. Those alerts should also be added to maintain symmetry.

**Describe the solution you'd like**
Alert should be added when hovered over options other than input and output.

**Comment by ankitkataria** [comment]
@sakshi1499 is it possible to add a little bit more information and screenshots for this?

**Comment by sakshi1499** [comment]
Yes. Sure, attaching.

**Comment by sakshi1499** [comment]
![image](https://user-images.githubusercontent.com/42520146/68532976-17cd1180-034a-11ea-8b6e-19553739a86a.png)
![image](https://user-images.githubusercontent.com/42520146/68532986-2b787800-034a-11ea-9667-6b8608d09d0f.png)

**Comment by ankitkataria** [comment]
Great, thanks! :slightly_smiling_face:

**Comment by Shivansh2407** [comment]
I would like to add this feature but I do not have the message/text that should be shown on alert. Please let me know soon @ankitkataria and @sakshi1499 .

**Comment by sakshi1499** [comment]
Which text/message are you unsure of? @Shivansh2407 If you are unsure of all the messages that are missing, I'll recommend you to review simulator tools on google. In the screenshot above, the selected gate is AND gate. So the alert should show 'AND gate selected' or something similar.

**Comment by Shivansh2407** [comment]
Ok cool. But I am asking that like if I hover on Ground element then it shows 
> Ground: all bits are Low 
So should I keep something similar or Just the element name and selected . All can I open up a PR for this ?
