### ISSUE TITLE
No invite received after being added to the group

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#487]
**Is your feature request related to a problem? Please describe.**
Invite was to be sent to the people who are not already on CircuitVerse to connect to a project according to the alert, but none was received(not even in spam).

**Describe the solution you'd like**
Emails can be sent to the users using sendgrid api.

**Comment by ankitkataria** [comment]
Does this issue arise in prod?

**Comment by sakshi1499** [comment]
This issue arises only in the developer environment, in gitpod which requires smtp service to be registered and applied and that needs to be worked on. Otherwise,the invite mail goes in spam.

**Comment by ankitkataria** [comment]
Email services, in my opinion, are not necessarily required in the development environment. Almost everything related to emails can be achieved indirectly without configuring SMTP. But it'll be nice to have some documentation on how to configure it if ever required. How does this sound?

**Comment by sakshi1499** [comment]
Great good idea to go. :)

**Comment by tachyons** [comment]
There which does mail handling for dev environment without configuring SMTP
Eg https://github.com/ryanb/letter_opener

**Comment by sakshi1499** [comment]
This seems like a good option, here the emails will get sent back to us only right?

**Comment by tachyons** [comment]
Already done
