### ISSUE TITLE
Color setting for 7-segment displays

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#49]
The 7-segment and hex displays are lacking a color setting, which would be great to have. The variable LED is also lacking a color setting.

**Comment by satu0king** [comment]
This can be done

**Comment by blane1257** [comment]
Thanks

**Comment by HypheX** [comment]
I will attempt to do this...

**Comment by satu0king** [comment]
Great! It is very easy to do. Just add an attribute called color in all of them. Then add mutable properties and write the appropriate function for changeColor. In fact, you can copy everything from DigitalLed. Ensure the default colors are the one that is used now. 

Checkout DigitalLed in `public/js/module.js`.

**Comment by HypheX** [comment]
Oh, thank you, I was reading through every script, trying to find the properties 😛.

**Comment by satu0king** [comment]
There is an open PR with a few minor issues, we will have this feature soon.

**Comment by blane1257** [comment]
Ah, okay

**Comment by shipcy** [comment]
I want to take this issue

**Comment by sgpritam** [comment]
Can i work on this issue

**Comment by Shivansh2407** [comment]
Can I take up this issue @blane1257 , @satu0king ??

**Comment by ShubhankarKG** [comment]
Hey, is the PR still up ? Has the issue been solved @satu0king ? Else, I can contribute on this one.

**Comment by ArshdeepSahni** [comment]
can i take this issue to work on?

**Comment by tushar912** [comment]
is this issue still open?

**Comment by Roshan13046** [comment]
I would like to work upon this.
Is the issue open?

**Comment by ShrutiKhatri826** [comment]
May I work on this?

**Comment by srishty-07** [comment]
Can I work on this issue, is it still open

**Comment by AswinCG2002** [comment]
Is the issue till there? Can i work on this?

**Comment by dhiru9599** [comment]
I want to work on this issue.is it still open?

**Comment by satu0king** [comment]
Yes, this issue is still open. Please send in a PR. Thanks!

**Comment by srishty-07** [comment]
> Yes, this issue is still open. Please send in a PR. Thanks!

I would like to work on this issue could you please tell how to proceed , like what necessary changes are  to be made.

**Comment by gr455** [comment]
> I would like to work on this issue could you please tell how to proceed?

You can go ahead and work on it. You will have to add a color property in modules/MODULENAME.js, change the customDraw() function to use that color. Finally you will have to add the color property in MODULENAME.mutableProperties so that the option shows up on the dialog box on the simulator.

Refer to @\satu0king's comments and the closed PR for reference

**Comment by Palaksharma23** [comment]
@shlokjjw are you working on this issue ? 
i would love to take up this issue .

**Comment by nitin10s** [comment]
@Palaksharma23 you can take up the issue.

**Comment by pulkit-30** [comment]
Hey @satu0king @gr455 @nitin10s, I tried to add this feature, Please have a look at #2741 and provide me with appropriate feedback so that I can continue working on this.
