### ISSUE TITLE
Bootstrap missing in Project's drop down buttons 

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#491]
**Is your feature request related to a problem? Please describe.**
Drop down from the Project tab seems plain. 

**Describe the solution you'd like**
Apply Bootstrap and make the drop down buttons light gray with text becoming black on hover. 

**Additional context**
![2019-11-01 (2)](https://user-images.githubusercontent.com/43600306/68013152-31b78600-fcb2-11e9-8b1b-9f7147f66dc3.png)

**Comment by Shivansh2407** [comment]
I would like to work on this . Please can you guide me on this @ankitkataria .
