### ISSUE TITLE
Navbar unresponsive

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#492]
**Describe the bug**
Navbar becomes unresponsive at 1261x760 px.

**Expected behavior**
Navbar should maintain its dimensions even when size of the screen changes. 

**How to correct**
Use media query and verify the size using inspection as shown in screenshot.

**Screenshots**
![2019-11-01 (3)](https://user-images.githubusercontent.com/43600306/68013857-0897f500-fcb4-11e9-9eb1-51f0b4c8599d.png)

**Comment by Shivansh2407** [comment]
Can you please guide me how to proceed with this issue @ShreyaPrasad1209 ?
