### ISSUE TITLE
Separate project and search button

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#493]
**Is your feature request related to a problem? Please describe.**
There's no gap between project button and search bar.

**Describe the solution you'd like**
Shift the project button towards left and apply Bootstrap on it. Prefer light greyish color scheme.

**Additional context**
![2019-11-01 (2)](https://user-images.githubusercontent.com/43600306/68014247-fd919480-fcb4-11e9-9b7c-afaa26f2ff8d.png)

**Comment by ankitkataria** [comment]
Related to #491
