### ISSUE TITLE
Page index unresponsive

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#494]
**Describe the bug**
Page Index unresponsive after 767x760px.

**How to correct it**
Use media query and verify responsiveness using inspection.

**Expected behavior**
"Previous" and "Next" buttons should maintain its width.

**Screenshots**

![2019-11-01 (5)](https://user-images.githubusercontent.com/43600306/68015040-316db980-fcb7-11e9-9ce5-86a0278f7e97.png)

**Comment by junron** [comment]
Simple solution: Remove the space between the arrow and the text. This causes the browser to render the text as one 'word' so it stays on the same line

**Comment by myfrom** [comment]
I'll work on this as part of GCI task

**Comment by ShreyaPrasad1209** [comment]
@myfrom you can claim the task given on GCI dashboard, there's no need to comment here unless you wanna work on an issue that's not present in the task list.

**Comment by myfrom** [comment]
Oh, ok. I wasn't sure if the tasks disappear once you claim them and didn't want to get a few people working on the same thing 😅

**Comment by ShreyaPrasad1209** [comment]
Don't worry, we can still modify the number of instances. Just ping us on the Slack channel in case you're unable to claim an unfinished task.

**Comment by myfrom** [comment]
Is putting the pagination in a grid a valid solution? (would fix some styles, like align that better etc)
![image](https://user-images.githubusercontent.com/19410489/70073409-24672180-15f9-11ea-84e6-f969f476e367.png)

I think only other options would be to:
- make the pagination horizontally scrollable or
- decrease the number of pages shown on all screen sizes

**Comment by ShreyaPrasad1209** [comment]
Pagination is usually grid like in nature. But one can use other designs as well. Go with the first option. You can explore other ways to create an aesthetic pagination. I'll mark this issue under design.
