### ISSUE TITLE
Feature : Integration of UI-Based Language Contribution

### ISSUE THREAD

**Issue by Asrani-Aman** [CircuitVerse/CircuitVerse#4951]
### Is your feature request related to a problem? Please describe

 if any user wants to contribute to CircuitVerse's language support, then he/she must be familiar with git and CircuitVerse’s code base, otherwise they are unable to contribute in CircuitVerse’s language support.

### Describe the solution you'd like

So there is a need of adding more translations and a method in which users,who are unfamiliar with Git and Coding can contribute CircuitVerse’s Language support.This integration will enhance language support capabilities for CircuitVerse.

![Image](https://github.com/CircuitVerse/CircuitVerse/assets/96644946/424e3d96-4336-44d9-97f1-cbbb7d08817e)

### Are you working on this?

Yes

**Comment by blizet** [comment]
I would like to help, could you please provide a little elaboration related to the same or maybe provide a detailed flowchart of the working.
