### ISSUE TITLE
Email Verification at the time of User Registration:

### ISSUE THREAD

**Issue by Asrani-Aman** [CircuitVerse/CircuitVerse#4957]

**Comment by Prateek-Fst** [comment]
Hey @Asrani-Aman can you provide more information about this issue, I would like to work upon it

**Comment by Asrani-Aman** [comment]
Hello @Prateek-Fst,

Hope you are doing well,
Actually this issue is the part of my GSOC project, and I Have almost implemented this task,

You can find other issues and also create yours if you find a bug or want to introduce a feature and start working once verified by mentors(in the Slack Channel)

Thank you!

**Comment by Asrani-Aman** [comment]
Hello @Prateek-Fst,

 If you want are curious to know ,You can see the below flow that will explain How I implemented Email Verification functionality ?
