### ISSUE TITLE
🐞 Bug :: Image does not showing 

### ISSUE THREAD

**Issue by Santoshpatel112** [CircuitVerse/CircuitVerse#4996]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

##Image does not shown in feature section 
<img width="950" alt="feature1" src="https://github.com/CircuitVerse/CircuitVerse/assets/134463761/21cbdadd-d022-4bbf-9a84-b42abfedec4f">

### Steps To Reproduce

# step to reproduce the behavior
1. go to (https://circuitverse.org/featured_circuits)
2. Scroll down see in middle img 

### Expected Behavior

<img width="950" alt="feature1" src="https://github.com/CircuitVerse/CircuitVerse/assets/134463761/419d3139-433c-4947-bc56-5b24ae7cbee9">

### Screenshots

<img width="950" alt="feature1" src="https://github.com/CircuitVerse/CircuitVerse/assets/134463761/e7298660-4362-4fdc-a607-e70a96ad67eb">
<img width="949" alt="feature2" src="https://github.com/CircuitVerse/CircuitVerse/assets/134463761/660498d8-0e37-4071-9f5e-910ee7f8cd30">

### Device Information [optional]

```markdown
window 11
Browser(Chrome,Microsoft edge)
```

### Additional context

please asign me but i need some pic that fit for that .

### Are you working on this issue?

Yes

**Comment by tachyons** [comment]
This is due to data issue in image migration, not a product issue
