### ISSUE TITLE
Separate backend/front end code 

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#5]
Currently backend and front end code is tightly coupled. Developers who want to work on the simulator will not want to install and setup the backend code and dependencies. Therefore it is desirable to separate the two.

**Comment by Parikshit-Hooda** [comment]
@satu0king Can we put it under GCI 'hard' ?

**Comment by ankitkataria** [comment]
I don't think that'll be a good idea, there's still a lot of work required to achieve that.

**Comment by Parikshit-Hooda** [comment]
Yes, I get it now. This was perhaps posted/refered before your advice on the slack.
