### ISSUE TITLE
Alert should disappear when reloaded

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#503]
**Is your feature request related to a problem? Please describe.**
The alert fails to disappear when reloaded.

**Describe the solution you'd like**
Alert popped up earlier should get removed on its own when the page is refreshed.

**Additional context**
Look at the screenshot attached.
![alert](https://user-images.githubusercontent.com/42520146/68021561-bb258300-fcc7-11e9-85b4-9dae1119eb41.PNG)

**Comment by tachyons** [comment]
This is the intended behaviour in rails flash messages

**Comment by sakshi1499** [comment]
Okay :)
