### ISSUE TITLE
Should display messages properly

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#504]
**Is your feature request related to a problem? Please describe.**
When a user clicks on the send me instructions toggle in the forgot password page, the text displayed on screen should show texts like "Enter an email" or "Email can't be blank" instead of " 1 error prohibited this user from being saved: email can't be blank"

The text that is being displayed doesn't seem appropriate and individual pointer.
Font and size can also be improvised. 
**Additional context**
The screenshot has been attached below
![improve](https://user-images.githubusercontent.com/42520146/68021956-e197ee00-fcc8-11e9-8d58-36e1f958cefc.PNG)

**Comment by tachyons** [comment]
This is the default ui from the library we use (devise). Do you have better design suggestions to improve user experience on this page?

**Comment by sakshi1499** [comment]
Yes definitely. Because the email can't be blank is generated directly from the library, we can change the text stating 1 error line, user is the person using it, why should it be in the third person and not second person?

**Comment by sakshi1499** [comment]
User experiences are majorly personalized and this makes it look generic, I hope you understand what I am conveying. Its not very eye pleasing to look at the same once it has loaded.
If you could direct me to the file, I'll look for how we can make it better.

**Comment by tachyons** [comment]
Yes, I that is why I used the term user experience. 

This is the relavent file from the codebase https://github.com/CircuitVerse/CircuitVerse/blob/master/app/views/users/passwords/new.html.erb

**Comment by sakshi1499** [comment]
Yes, I'll look at it. Where is this file rendering?

**Comment by tachyons** [comment]
From this gem https://github.com/plataformatec/devise

**Comment by sakshi1499** [comment]
I read that, I found an article similar to our situation, give it a read please?
https://stackoverflow.com/questions/20530682/modify-devise-reset-password-error-text

**Comment by shubhankarsharma00** [comment]
> https://stackoverflow.com/questions/20530682/modify-devise-reset-password-error-text
Hey @sakshi1499 to display custom message that might be good way.
Also this can be useful if we want to display flash messages: https://stackoverflow.com/a/5560355/9581628

**Comment by sakshi1499** [comment]
<% if flash.count > 0 %>
  <div id="error_explanation">
    <h2>Errors prevented you from logging in</h2>
      <ul>
        <% flash.each do |name, msg| %>
        <li>
          <%= content_tag :div, msg, id: "flash_#{name}" %>
        </li>
       <% end %>
     </ul>
   </div>
<% end %>
I really like this answer, I think this should work.

**Comment by Shivansh2407** [comment]
Can I work on this issue?

**Comment by Shivansh2407** [comment]
@tachyons should we display custom messages instead of the default ones ? Would like to work on this 👍
