### ISSUE TITLE
Invalid emails being allowed in 'add collaborator'

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#505]
**Is your feature request related to a problem? Please describe.**
I tried to add invalid email and it showed it was valid.
Email that I added was test@rosy
**Describe the solution you'd like**
Invalid emails should get removed.

**Additional context**
Screenshot attached.
![invalid](https://user-images.githubusercontent.com/42520146/68023657-c9769d80-fccd-11e9-9b14-e2c3a357ef1f.PNG)

**Comment by Shivansh2407** [comment]
Can I please work on this issue?

**Comment by Shivansh2407** [comment]
Can I work on this @tachyons and @sakshi1499 ?

**Comment by sakshi1499** [comment]
As all the PRs have been closed without merging, you can work on this. Ref the last PR, some comments have been made for improvement. Include those. @Shivansh2407

**Comment by Shivansh2407** [comment]
Ok Cool @sakshi1499
