### ISSUE TITLE
Bootstrap Missing in Post comment and cancel button

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#507]
**Is your feature request related to a problem? Please describe.**
Bootstrap missing in post and cancel buttons in the add comment section.

**Describe the solution you'd like**
Bootstrap can be added to make it look better and in sync with other buttons.

**Additional context**
Screenshot attached.

![comment](https://user-images.githubusercontent.com/42520146/68033211-42352400-fce5-11e9-94bc-1c1a5433a013.PNG)

**Comment by Arun-42** [comment]
@sakshi1499  Where in particular is this section?
