### ISSUE TITLE
Comment should delete after being deleted.

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#508]
**Is your feature request related to a problem? Please describe.**
As a user, its not likely that I would want my deleted comment to be marked as "comment deleted".

**Describe the solution you'd like**
It should actually be deleted or removed for better user experience.

**Additional context**
Screenshot Attached.
![delete](https://user-images.githubusercontent.com/42520146/68033682-31d17900-fce6-11e9-842e-b1ae58a46a19.PNG)

**Comment by shubhankarsharma00** [comment]
We can change the code below to reload the whole show partial.
https://github.com/CircuitVerse/CircuitVerse/blob/535b3c269b003aaa523492563af7be156a053b4d/app/views/commontator/comments/delete.js.erb#L1-L15
like 
`$("#comment_<%= @comment.id.to_s%>_div").html("<%= j(render partial: 'show', locals: { comment: @comment,user: @user }) %>");
`
and then add an if statement here
https://github.com/CircuitVerse/CircuitVerse/blob/535b3c269b003aaa523492563af7be156a053b4d/app/views/commontator/comments/_show.html.erb#L11-L12 
Note: This will remove the undelete button too maybe add a flash message to undo delete.

**Comment by sakshi1499** [comment]
I think it should work but I just have to contribute in raising issues for now and leave it for GCI participants. Right?

**Comment by shubhankarsharma00** [comment]
@sakshi1499 yeah, I guess..... I was just leaving an explanation to make it easier for first-timers.
