### ISSUE TITLE
Bootstrap missing in edit project

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#509]
**Is your feature request related to a problem? Please describe.**
Bootstrap missing in update
![update](https://user-images.githubusercontent.com/42520146/68034757-562e5500-fce8-11e9-9e7a-26777928aca9.PNG)
 project in simulator.

**Describe the solution you'd like**
The above button should have bootstrap.

**Additional context**
Screenshot has been attached.

**Comment by MrBartusek** [comment]
Duplicate with less info of #712
