### ISSUE TITLE
Yarn fails during setup

### ISSUE THREAD

**Issue by solsword** [CircuitVerse/CircuitVerse#5093]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I'm following along with the setup instructions and I've gotten to the point where it says to run "yarn". This step fails with multiple error messages (see attached). The first error message is an HTTP 404 when trying to download node-canvas, and indeed, the node_modules/canvas/build/config.gypi file contains a "node_napi_label" value of "node-v127", but there is no file at the full URL:

https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v127-linux-glibc-x64.tar.gz

v120 seems to be the latest version available on [the releases page](https://github.com/Automattic/node-canvas/releases/) under v2.11.2, so I'm not sure why we're trying to select v127 and failing to download it. On the other hand, I can't even be confident that this is the root cause of the larger build failure, since I'm not a yarn expert at all. Editing the config file to replace v127 with v120 doesn't help; that config file says it's generated by gyp and shouldn't be edited. It's possible that something entirely different in the output I'm seeing is the cause.

The complicated part of this issue is that I'm on WSL. I'm following the Linux install instructions since there aren't right now dedicated WSL instructions, but all the steps have worked up to this point. My system is running Arch Linux under WSL2, on an x86_64 CPU. I'm on a fork on commit  98788e00c3093aa7b86a1c9541f36c7e38dace75, but I haven't yet made any changes to the code (trying to get the build process working first!

I did see a mention of asking about setup issues in slack, but the slack link is dead (and was last updated in 2023).

[yarnout.txt](https://github.com/user-attachments/files/17235566/yarnout.txt)

### Steps To Reproduce

Follow the [Linux setup guide](https://github.com/CircuitVerse/CircuitVerse/blob/master/installation_docs/manual/linux.md) through step #3: run 'yarn'.

### Expected Behavior

Yarn should succeed in installing stuff.

### Device Information [optional]

```markdown
- OS: WSL2 on Windows, running Arch Linux (64-bit)
- Browser: Not relevant, but Firefox
- version: commit 98788e00c3093aa7b86a1c9541f36c7e38dace75 (latest as of 2024-10-2)
```

### Are you working on this issue?

No

**Comment by salmoneatenbybear** [comment]
Hi! @solsword seems like the issue stems from an incompatible Node.js version. The error you're seeing is because node-canvas is trying to use a version of Node.js that doesn't have the appropriate pre-built binaries available. Here's what you can try:

1. Install Node.js 16.x (as it's the version recommended for this setup):

```
curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
sudo apt install -y nodejs
```

Install the necessary build tools for node-canvas:

```
sudo apt-get install build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
yarn add canvas
```

Once you've done that, delete your node_modules folder and yarn.lock file, and try running yarn again.

**Comment by solsword** [comment]
Thanks for the help! That's something I should have checked on...

After upgrading nodejs, I was able to proceed a bit further. The database commands failed due to permissions, and it's hacky and possibly going to be an issue later, but proceeding with sudo (after doing a sudo gem install, which gem warned me about but I'm not using Ruby for anything else on this system) lets me actually run the app, which is good. I had to delete the node_modules folder in cv-frontend-vue after getting repeated ENOTEMPTY errors for renaming folders there, but that actually let the thing run and respond to a request on localhost:3000. Unfortunately, I'm now getting an error in the browser about a missing asset (obviously, possibly due to my hacking around a few steps).

My new error looks like this, but I'll try to poke around a bit more before actually asking for help with this. I'm just posting this response now in case I don't get to that soon and others trying to get it up and running on WSL find what I'm doing useful or run into the same sorts of errors.

```
Sprockets::Rails::Helper::AssetNotFound in Circuitverse#index

Showing /home/pmwh/teaching/240/src/CircuitVerse/app/views/layouts/application.html.erb where line #18 raised:

The asset "application.js" is not present in the asset pipeline.

Extracted source (around line #18):

16
17
18
19
20
21
              

	


    <%= javascript_include_tag "application_sprockets", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload", defer: true %>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <%= render partial: "layouts/google_analytics" if Rails.env.production? %>

Rails.root: /home/pmwh/teaching/240/src/CircuitVerse
Application Trace | Framework Trace | Full Trace
app/views/layouts/application.html.erb:18
app/controllers/application_controller.rb:34:in `switch_locale'
Request

Parameters:

None
```

**Comment by Krapanshu-Tyagi** [comment]
I was able to solve this error.

**Comment by Krapanshu-Tyagi** [comment]
This app was previously a Rails 6 but as you upgraded to Rails 7, the application.html.erb was no longer recognizing my application.js file. I just made a minor change and now it is working fine. I will create a pull request to solve this issue.

**Comment by Krapanshu-Tyagi** [comment]
Hey! For some reason, I am unable to commit my code to git. So all you have to do is change the **"application"** part in the below code with **" /assets/application.js"**
![image](https://github.com/user-attachments/assets/2f3af8c9-899a-45e1-a75e-47d6994666c6)

**Comment by Krapanshu-Tyagi** [comment]
Then it should work

**Comment by tachyons** [comment]
It is documented [here](https://github.com/CircuitVerse/CircuitVerse/blob/master/installation_docs/troubleshooting_guide.md)
