### ISSUE TITLE
Cloudflare 522: Connection Timed Out on circuitverse.org

### ISSUE THREAD

**Issue by salmoneatenbybear** [CircuitVerse/CircuitVerse#5095]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

There seems to be a persistent issue with accessing circuitverse.org. When trying to access the site, the page displays a Cloudflare error with code 522, indicating that Cloudflare was able to reach the server but the server did not respond in time.

### Steps To Reproduce

1. Go to https://circuitverse.org
2. Wait for the page to load
3. See the error message "Connection Timed Out, Error 522"

### Expected Behavior

The CircuitVerse website should load without any issues.

### Screenshots

![image](https://github.com/user-attachments/assets/87e675b4-2141-4642-95c0-6f1f038a48e7)

### Device Information [optional]

```markdown
- OS:24.04.1 LTS (Noble Numbat)
- Browser: CHROME
- version: 129.0.6668.70 (Official Build) (64-bit)
```

### Additional context

The issue has been persistent for a while. It may be worth investigating the server's resource allocation or any potential server-side problems causing the timeout.

I also tried using a mobile device to access the website, same error. 

### Are you working on this issue?

No

**Comment by salmoneatenbybear** [comment]
@tachyons @tanmoysrt 

I thought it wouldn't hurt to notify...

**Comment by tanmoysrt** [comment]
Hi @salmoneatenbybear 
Circuitverse was down. It's up now.
Anyone there is a  page to track uptime status https://uptime.circuitverse.org/

**Comment by tachyons** [comment]
This was due to server resource constraints and we had to restart our server.
