### ISSUE TITLE
[chore]: Adopt vet for Automated OSS Package vetting to Prevent Risky OSS Dependencies

### ISSUE THREAD

**Issue by abhisek** [CircuitVerse/CircuitVerse#5106]
### Is your feature request related to a problem? Please describe

Not a problem. Proposing a free and open source tool integration to improve the security of CircuitVerse code base.

### Describe the solution you'd like

Team

I am the creator and maintainer of [vet](https://github.com/safedep/vet), tool to automate vetting of open source dependencies in PR using custom policies (as code). I wanted to check if you are willing to adopt `vet` to setup a policy driven security guardrail against risky OSS packages being added to `CircuitVerse` as dependencies.

Example PR vetted by `vet`: 

https://github.com/safedep/vet/pull/239#issuecomment-2331412400

Example policy using which the vetting was done:

https://github.com/safedep/vet/blob/main/.github/vet/policy.yml

If there is interest, I am happy to contribute a PR to integrate `vet` as a GitHub Action to scan dependency changes during PR in `CircuitVerse` as per your customised policies. 

### How does this help?

To reduce the risk of vulnerable or malicious `rubygems` or `npm` packages being added to `CircuitVerse` as dependencies. Also to assist code reviewers to make a faster decision on PRs from the community that add new dependencies.

### Describe alternatives you've considered

You can also use GitHub Dependency Review for similar use-cases. But `vet` is purpose built for developers with high flexibility of risk definition and customization using policy as code.

### Are you working on this?

Yes

**Comment by tachyons** [comment]
We are open to experiment with this tool, but we will remove this tool if it doesn't provide enough value in our workflow.

**Comment by abhisek** [comment]
Thanks @tachyons I will get a PR raised against this issue to integrate `vet` as a GitHub Action.

**Comment by abhisek** [comment]
@tachyons @smritigarg I raised a PR to integrate `vet` with `CircuitVerse`. 

I am happy to volunteer and contribute to `CircuitVerse` in reviewing PRs with potential security issues identified by `vet` or any other tool that you may have in CI. I don't want to dump `vet` on you. If there are failures or other issues related to `vet`, I can look at it as a CircuitVerse contributor.

I see there are a bunch of older gems with known vulnerabilities. I am happy to contribute updates as well but that will take a while because there may be breaking changes in newer version of the gem which requires some code refactoring.
