### ISSUE TITLE
Feature : Login/Signup by Github Authentication.

### ISSUE THREAD

**Issue by gitsofaryan** [CircuitVerse/CircuitVerse#5108]
### Is your feature request related to a problem? Please describe

Currently, users may find it inconvenient to create a new account or remember their passwords for different platforms. Offering GitHub authentication will allow users to quickly sign in or sign up with their GitHub account, simplifying the login process and enhancing user experience. This feature will also reduce friction for developers who frequently use GitHub, encouraging them to engage with Circuitverse more easily.

### Describe the solution you'd like

CircuitVerse should integrate GitHub OAuth with Vue.js to allow users to log in or sign up using their GitHub credentials. Here’s how it would work:

Users click a "Login with GitHub" or "Sign up with GitHub" button.
They are redirected to GitHub’s authorization page, where they grant permission for the app to access their profile.
After successful authentication, the app retrieves basic user information (e.g., email, GitHub ID) and either logs the user in or creates a new account if they are signing up for the first time.
The user is then redirected back to the application and logged in automatically.
This feature will be implemented using the OAuth flow in Vue.js. The process should be secure, responsive, and seamless, with proper error handling in place

### **Manual Signup/Login with Email and Password:** 
While this is a traditional option, it introduces friction and isn't as convenient as social login, particularly for the developer community.

### **Other Social Logins (Google, Facebook):** 
Although Google authentication is another viable option, GitHub is more appropriate for CircuitVerse’s target audience, which includes developers and engineers.

### **API Key Authentication:** 
This could be an alternative for some user types, but it doesn't address the ease-of-use and quick access GitHub OAuth provides.

### Additional context

Technology Stack: Since CircuitVerse uses Vue.js, this feature will involve integrating Vue with GitHub’s OAuth API, managing the authentication process using Vue components and backend support to securely handle access tokens.

### Are you working on this?

Yes

**Comment by gitsofaryan** [comment]
@subhamkumarr @tanmoysrt 
Please review this. I encounter redirection to signup page while login/signing-up via github.

**Comment by tachyons** [comment]
Have you tried using Circuitverse? We have big login with GitHub button in out sign in page !

**Comment by gitsofaryan** [comment]
https://github.com/user-attachments/assets/de33dafe-cc88-4ebc-a959-33123a331cba

so is that a bug?
