### ISSUE TITLE
Facebook sign up not working

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#511]
**Describe the bug**
Server error occuring when trying to sign up through Facebook

**Expected behavior**
Should sign up successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/43600306/68069603-49f9d480-fd88-11e9-8c46-36da82a8a44c.png)
On refreshing the above page,
![image](https://user-images.githubusercontent.com/43600306/68069608-5bdb7780-fd88-11e9-80d7-cd945f9bf8b9.png)
 even when given all the permissions.

**Comment by CodeSarthak** [comment]
Hi @ShreyaPrasad1209 , I just tried to sign up through Facebook and I was successful. 

Are you already signed in to Facebook before trying to sign up? Maybe, that is the difference. I was already signed in to my Facebbok (i.e. from www.facebook.com not from Circuit Verse)

**Comment by Parikshit-Hooda** [comment]
Perhaps try clearing browser storage and reattempt. Let me know if this is fixed.

**Comment by ShreyaPrasad1209** [comment]
I was already logged in to my Facebook when I signed up here. This issue persists today too.

**Comment by sakshi1499** [comment]
I was able to login too through facebook.

**Comment by CodeSarthak** [comment]
@ShreyaPrasad1209 Perhaps you could share your system specifications and the browser you are using.

**Comment by Ananthavijay** [comment]
@ShreyaPrasad1209 this can be done only after creating Google, Fb, Github app. Check this [wiki](https://github.com/CircuitVerse/CircuitVerse/wiki/Create-Apps) for more info. @tachyons This can be closed.

**Comment by Ananthavijay** [comment]
My bad, didn't read the issue properly

**Comment by ciphereck** [comment]
Can close this, since just a misunderstanding while onboarding @tachyons @nitin10s

**Comment by tachyons** [comment]
No this issue need to be fixed as issue happened in production, not local environment

**Comment by yash15601** [comment]
@tachyons   can i work on this

**Comment by yash15601** [comment]
@tachyons   thiers some issue with facebook app id
here's my screenshot 
![image](https://user-images.githubusercontent.com/49101492/76195974-64006380-620f-11ea-8679-b48722dd0209.png)

**Comment by Ananthavijay** [comment]
@yash15601 This is in circuitverse.org not in the development environment. To use the social media login u should check [this](https://github.com/CircuitVerse/CircuitVerse/blob/master/SETUP.md#configuring-third-party-services) .

**Comment by Shivansh2407** [comment]
Can I work on this @tachyons ?

**Comment by nitin10s** [comment]
@yash15601 is working on it. Right?

**Comment by yash15601** [comment]
Yes @nitin10s
