### ISSUE TITLE
Feature : Circuit Automation using AI Integration: Build Faster with a Prompt

### ISSUE THREAD

**Issue by gitsofaryan** [CircuitVerse/CircuitVerse#5111]
### Is your feature request related to a problem? Please describe

Designing complex circuits manually can be time-consuming and prone to human error. Students and engineers may struggle with selecting the right components, connecting them accurately, and achieving the desired functionality. This slows down the learning process and increases the difficulty of prototyping, especially for beginners. The absence of automation in circuit creation results in inefficiency, limiting experimentation and innovation.

### Describe the solution you'd like

I would like to implement AI-powered Circuit Automation, where users can simply provide a text prompt describing the type of circuit they want to create, and the system automatically generates the basic structure of the circuit. The AI would intelligently select the right components, configure the connections, and generate a circuit based on the user's description. For example, if a user inputs "Create a basic RC low-pass filter," the AI will generate a functioning circuit with the necessary resistor and capacitor in the correct configuration.

**Key Features:**

- Users enter natural language descriptions, and the system builds circuits accordingly.
- AI suggestions for optimizing circuit design and improving efficiency.
- Real-time editing after the circuit is generated, with the ability to tweak components as needed.

### Describe alternatives you've considered

- Manual Circuit Design: Users can continue designing circuits manually, which provides complete control but can be slow and tedious, especially for large or complex circuits.
- Circuit Templates: Pre-built templates for common circuit types, which can help users get started but may not be flexible enough for custom designs.

### Additional context

Technology Integration: This feature will require integrating an AI model capable of understanding circuit-related prompts and transforming them into logical circuit designs. We can explore using natural language processing (NLP) models in conjunction with circuit design databases.

### Are you working on this?

No

**Comment by gitsofaryan** [comment]
@vedant-jain03 @subhamkumarr @tanmoysrt
Please review this.

**Comment by tachyons** [comment]
This requires training a model with our circuit data structure, it will being additional complexity and infrastructure expenses. But if you want to build as a third party integration using circuitverse API, then feel free to do that.

**Comment by vedant-jain03** [comment]
@gitsofaryan thanks for the initiative though
