### ISSUE TITLE
[🐞 Bug]Missing of alternative LOG IN platforms

### ISSUE THREAD

**Issue by cr-arya-2024** [CircuitVerse/CircuitVerse#5139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Missing of alternative LOG IN platforms in Log in page

### Steps To Reproduce

1.Go to  LogIn page
2.scroll down towards footer section
3.update the twitter log

### Expected Behavior

Adding more options for login like Disqus,X(Twiiter),MicroSoft,,Apple 

### Screenshots

![Screenshot (9)](https://github.com/user-attachments/assets/39ba8826-be94-4238-b1cc-2175270128ef)

### Device Information [optional]

```markdown
- OS:
- Browser:
- version:
```

### Are you working on this issue?

Yes

**Comment by tachyons** [comment]
Not a bug
