### ISSUE TITLE
Designing Finite State and Algorithmic State Machines

### ISSUE THREAD

**Issue by eKuG** [CircuitVerse/CircuitVerse#515]
The algorithmic state machine (ASM) method is a method for designing finite state machines. It is used to represent diagrams of digital integrated circuits. The ASM diagram is like a state diagram but less formal and thus easier to understand.

FSM includes Mealy and Moore machines. Requesting to implement in the Circuitverse website.

**Comment by yash15601** [comment]
@eKuG  can you explain this theroy of computation in more detail like taking input in melay machine and verifying it ??

**Comment by eKuG** [comment]
As far as I remember, This issue was merely regarding DE rather than ToC

**Comment by yash15601** [comment]
@eKuG  i dont know about DE
