### ISSUE TITLE
Feature : Password strength 

### ISSUE THREAD

**Issue by Priyanshu1035** [CircuitVerse/CircuitVerse#5153]
### Is your feature request related to a problem? Please describe

During SignUp , check for the Strength of the Password .

### Describe the solution you'd like

To enhance password security, I want a strong pattern that balances complexity and usability.

### Are you working on this?

Yes

**Comment by kanishka-coder0809** [comment]
hey @Priyanshu1035  My name is Kanishka and I know how to deal with this issue can you please assign me with this.

**Comment by kartik-212004** [comment]
I'm interested in working on this issue and would appreciate being assigned to it.
