### ISSUE TITLE
Signing up name should not contain number

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#516]
**Describe the bug**
I made an account on circuitverse with my name being sakshi1

**To Reproduce**
1. Go to Sign Up page
2. Add your name as Any Alphabet and number
3. No alert of a wrong name will pop up.

**Expected behavior**
Alert showing invalid name should pop up.

**Screenshots**
Screenshot has been attached.

![name](https://user-images.githubusercontent.com/42520146/68180947-a4c74200-ffbb-11e9-9c81-1d8bee6e0239.PNG)

**Comment by ankitkataria** [comment]
What are possible drawbacks to using numbers?

**Comment by sakshi1499** [comment]
As such I'll say no drawback, but it just seems inappropriate. Like whenever you refer them in email, because of the generated message, every time their name won't be an actual name. One other thing could be that they might be making a typo, no one really writes their names including numbers.

Otherwise not really a drawback, more like enhancement.

**Comment by tachyons** [comment]
Given the complexity of names across the global It is better not to add validation for name other than sanitizing for security reasons
