### ISSUE TITLE
Add Translation Option for Non-English Comments to English

### ISSUE THREAD

**Issue by Stitipragyanbarik** [CircuitVerse/CircuitVerse#5168]
### Is your feature request related to a problem? Please describe

To improve accessibility for users from different linguistic backgrounds, it would be useful to add a translation feature to comments. If a comment is written in any language other than English, it should automatically translate to English when users click a "Translate" button. For comments already written in English, no translation is necessary.

### Describe the solution you'd like

1-Add a "Translate" button under each comment.
2-If the comment is written in a language other than English, use an API (e.g., Google Translate) to automatically translate it to English.
3-If the comment is already in English, no translation is performed.
4-Allow users to toggle between the original language and the translated English version, if needed.
5-Provide an option to enable/disable this feature in user settings, so users can choose to see comments in their preferred language.

### Are you working on this?

No

**Comment by Stitipragyanbarik** [comment]
@tanmoysrt  , @nitin10s  sir please review it

**Comment by andycandy** [comment]
Hi! This is an excellent idea, and I would love to get started on implementing it as soon as possible. Let me know if it's okay for me to take this up and start working on it. Looking forward to your response!

**Comment by Sarvesh2783** [comment]
Hi, I am also interested and  currently working on adding the translation option!!

**Comment by salmoneatenbybear** [comment]
The translation feature is not planned as of now as mentioned by @tachyons in #5168
