### ISSUE TITLE
Easily accessible grading option shold be added.

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#517]
**Is your feature request related to a problem? Please describe.**
I made two accounts, one for teacher and one for student and I posted an assignment and completed that through the student account. I added that it should be a graded assignment but no buttons or options were added to grade the assignment directly.
**Describe the solution you'd like**
To enhance the user experience a button containing the grading option should be added and the grade should be made visible to the student.

**Comment by ankitkataria** [comment]
Grading options are only visible once the deadline for the assignment is over. A note on the assignment page somewhere will be helpful.

**Comment by sakshi1499** [comment]
I added this issue thinking that some teachers like to start grading like first come first but that would not work in the case when students can update their assignment until the submission date. Is that what happens? Yes note on assignment page would actually help.

**Comment by ankitkataria** [comment]
Yup, students are allowed to edit the project until the submission deadline.
