### ISSUE TITLE
Unable to login using the admin credentials mentioned.

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#518]
**Is your feature request related to a problem? Please describe.**
I am unable to login through the login credentials mentioned on the readme.md file of CircuitVerse.

**Describe the solution you'd like**
Make these credentials work or create a new account and hence update the readme.

**Additional context**
Screenshots have been attached.
![readme](https://user-images.githubusercontent.com/42520146/68181636-1e602f80-ffbe-11e9-9267-b165d6550e49.PNG)
![invalid](https://user-images.githubusercontent.com/42520146/68181711-52d3eb80-ffbe-11e9-8bb6-fdee89391ccb.PNG)

**Comment by ankitkataria** [comment]
Doing `bundle exec rake db:seed` is necessary to seed the database with the admin credentials. It would be great add a note regarding this in the README.

**Comment by sakshi1499** [comment]
Yes, okay.

**Comment by sakshi1499** [comment]
Should I add a note for the same in readme? It would be easier for beginners.

**Comment by tachyons** [comment]
@sakshi1499 go ahead
