### ISSUE TITLE
Feature : The profile picture on the dashboard is not fully visible

### ISSUE THREAD

**Issue by sahiladit** [CircuitVerse/CircuitVerse#5182]
### Is your feature request related to a problem? Please describe

No

<img width="1440" alt="Screenshot 2024-12-03 at 12 12 33 PM" src="https://github.com/user-attachments/assets/43a44fb7-6256-460f-af75-d10cb216ba6e">

### Describe the solution you'd like

The profile picture should be fully visible.The picture should be circular.

### Are you working on this?

Yes

**Comment by andycandy** [comment]
I already fixed that, check pull request #5171. It fixes profile picture appearance all across the website
