### ISSUE TITLE
Implement cursor based pagination for recent circuits

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#5195]
Recent circuits view on home page currently using OFFSET pagination , which is not perfomant when paginating millions of records. We need to change that to Cursor based pagination. 

Gem to use: https://github.com/healthie/activerecord_cursor_paginate
Explanation about the techniques: https://www.citusdata.com/blog/2016/03/30/five-ways-to-paginate/

**Comment by salmoneatenbybear** [comment]
would love to work on this.

**Comment by salmoneatenbybear** [comment]
Thankyou @tachyons for assignment
