### ISSUE TITLE
🐞 Bug Close icon does not function correctly 

### ISSUE THREAD

**Issue by sahiladit** [CircuitVerse/CircuitVerse#5205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

When tried to open menu in mobile/small-screen the close(cross) icon does not close the menu, only the icon changes to hamburger menu.

### Steps To Reproduce

1.Open site in mobile view
2.Open menu
3.Click on the cross icon

### Expected Behavior

The cross icon does not close the menu but changes itself to hamburger manu icon.

### Screenshots

https://github.com/user-attachments/assets/80df831b-f7f1-4ab6-ad1d-f4093d4d3f39

### Device Information [optional]

```markdown
- OS:MacOS
- Browser:Chrome
- version:
```

### Are you working on this issue?

Yes

**Comment by salmoneatenbybear** [comment]
Yes this is addressed in #5203
