### ISSUE TITLE
Setup using Ruby on Rails on Windows without the use of Docker

### ISSUE THREAD

**Issue by eKuG** [CircuitVerse/CircuitVerse#521]
**Is your feature request related to a problem? Please describe.**
I always use Windows as my primary Operating system due to ease of use and so does people around the world. Ruby on Rails, on windows is a very tedious task to properly install.

**Describe the solution you'd like**
With the incoming of WSL and windows terminal, I would like to request using the same for the implementation of Circuitverse directory on WIndows.

**Describe alternatives you've considered**
Solutions like Docker and DigitalOcean are always the way to go for ease and because people would not like to change OS's on the fly. I would like to eradicate the middle piece of software in use.

**Are you working on this?
Personally Yes, but would like to help and guide those who are working besides me.

**Comment by JoshHeng** [comment]
@eKuG I installed Ruby using the GUI installer and then followed the instructions in the CircuitVerse README and that worked fine for me. I'm running Windows 10 Home without Docker, and all I have to do to start the server is to navigate to the CircuitVerse directory and enter `rails s -b 127.0.0.1 -p 8080` in command prompt (as said in the README).

**Comment by eKuG** [comment]
That's why this is just a documentation task

**Comment by JoshHeng** [comment]
> That's why this is just a documentation task

Isn't it already documented though, on the README? If anything needs to be added, it's literally to install Ruby using the installer on their website

**Comment by nrs1729** [comment]
I claimed the task on GCI and wrote up how I installed ruby/rails on WSL - is this what was intended?

**Comment by falguniraina** [comment]
can i work on this??

**Comment by Shivansh2407** [comment]
Hey @eKuG I have recently gone through the process of setting up Ruby on rails without the use Docker on my local machine. Can I give this a try?

**Comment by eKuG** [comment]
I think this task is over!
