### ISSUE TITLE
Make the Setup Instructions beginner friendly

### ISSUE THREAD

**Issue by Anjalizi** [CircuitVerse/CircuitVerse#525]
**Describe the bug**
The instructions to be followed aren't clear and will present newbies to RoR with a lot of problems. A detailed step with a code snippet should be provided.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Chrome

**Additional context**
For instance, instead of "Install ruby using RVM, use ruby-2.5.1", the instruction should be like - 
Install rvm from rvm.io
Using rvm: `rvm install 2.5.1` followed by `rvm use 2.5.1`

More such issues of documentation should be catered to.

**Comment by ankitkataria** [comment]
A better approach would be to add setup scripts for Windows and Linux environments. Something on the lines of [this](https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/setup/deb-setup.sh). This would make the instructions as easy as running a bash script.

**Comment by Anjalizi** [comment]
Sure, I'll look into it but the setup instructions [here](https://github.com/publiclab/plots2#standard-installation) are also very user friendly and easy to comprehend. Do have a look.
