### ISSUE TITLE
New Group Page Styling

### ISSUE THREAD

**Issue by Tanish0019** [CircuitVerse/CircuitVerse#527]
**Is your feature request related to a problem? Please describe.**
Log in. 
Go to https://circuitverse.org/groups/new
This section looks very out of place with no styles applied. Moreover, a one-liner description of how making groups are useful can be helpful for new users.

**Describe the solution you'd like**
Use of simple bootstrap classes to style it so it goes with the rest of the website.

**Describe alternatives you've considered**

**Additional context**
![Screen Shot 2019-11-05 at 9 52 31 PM](https://user-images.githubusercontent.com/30210495/68225752-ecc78280-0016-11ea-88b4-ea4e2fa8f03b.png)

**Are you working on this? (Yes/No)**
Yes

**Comment by CodeSarthak** [comment]
Hi  @Tanish0019 , I see that you are already working on this, but if you need any help, do let me know :)

**Comment by nrs1729** [comment]
Hi, just to say I claimed the task on GCI and am working on it.

**Comment by Ananthavijay** [comment]
@tachyons This can also be closed, fixed by new UI
