### ISSUE TITLE
Unwanted div at the bottom of the page

### ISSUE THREAD

**Issue by rajat2502** [CircuitVerse/CircuitVerse#528]
**Describe the bug**
There is an empty space from the pagination links which is not required and actually looking bad in the mobile view of the website. That extra space is due to an empty *div* of a height of 250 pixels. That div ( of class name *container* ) is not required as it is not looking good in the Mobile view. 
 
**To Reproduce**
1. Go to https://circuitverse.org/
2. Scroll down to the end of the website
3. See the extra space which is not required.

**Expected behavior**
The unwanted div should either be removed and its display should be set to none in the Mobile view of the website.

**Screenshots**
![Screenshot from 2019-11-05 21-49-18](https://user-images.githubusercontent.com/42200276/68225853-12548c00-0017-11ea-8146-b9204335223a.png)

**Desktop:**
 - OS: Ubuntu
 - Browser: Google Chrome
 - Version 77.0.3865.120 

**Are you working on this issue? (Yes/No)** No, this issue is for GCI students.

**Comment by Shivansh2407** [comment]
Please review this @rajat2502 and let me know if any changes.

**Comment by MrBartusek** [comment]
Footer has been changed in new UI should be closed
