### ISSUE TITLE
Club Financial Contributors under readme.md

### ISSUE THREAD

**Issue by CodeSarthak** [CircuitVerse/CircuitVerse#529]
Under the Financial Contributors section of the readme file in the main repository, contributing for individuals and organisations is listed separated but they point to the same webpage.

Contribution for individual/organisation can be clubbed under 1 heading itself. 

![issue](https://user-images.githubusercontent.com/24937677/68227557-f1416a80-0019-11ea-81be-d8521a8a9349.png)

Working on it? - Yes.

**Comment by Shivansh2407** [comment]
Can I work on it @CodeSarthak ?
