### ISSUE TITLE
Extremely odd dragging behavior.

### ISSUE THREAD

**Issue by HypheX** [CircuitVerse/CircuitVerse#53]
![what-drag](https://user-images.githubusercontent.com/29693543/48607388-69f97380-e93e-11e8-8495-d9d144aa9b1c.gif)
Notice, there is a dot that is moving twice as fast as the rest of the selected parts.
![image](https://user-images.githubusercontent.com/29693543/48607464-885f6f00-e93e-11e8-8198-c2be568febd8.png)
![image](https://user-images.githubusercontent.com/29693543/48607552-a62cd400-e93e-11e8-842a-38c2f74dd222.png)
This has happened before a few times, I have not been able to reproduce it. The error logs might help though.

**Comment by satu0king** [comment]
This should not be happening. Something really wrong must have happened. Either the node got detached from the parent, then something really bad happened somewhere. Or the node got selected by mistake, then we can rectify it by putting a constraint somewhere. Have to look into it.

**Comment by satu0king** [comment]
@HypheX have you been able to reproduce this issue?

**Comment by ankur54** [comment]
So, if I am correct, the issue is of the green wire rotating abnormally, right?
