### ISSUE TITLE
Show uploaded image preview in profile edit section

### ISSUE THREAD

**Issue by Tanish0019** [CircuitVerse/CircuitVerse#530]
**Is your feature request related to a problem? Please describe.**
Log in and go to profile edit section. When a new photo is uploaded a preview of the uploaded photo is not shown.

**Describe the solution you'd like**
Show a preview of the uploaded photo to improve user experience.

**Additional context**
![Screen Shot 2019-11-05 at 10 19 30 PM](https://user-images.githubusercontent.com/30210495/68228667-da9c1300-001b-11ea-96cc-c273efd83c64.png)

**Comment by Shivansh2407** [comment]
@Tanish0019 Please review the PR 👍
