### ISSUE TITLE
Contact Email link doesn't work

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#531]
**Describe the bug**
The contact email link on the About Us page doesn't respond.

**To Reproduce**
1. Go to 'About' page
2. Click on 'support@circuitverse.org'
3. See error

**Expected behavior**
The link should redirect the browser window to Gmail or any other email client.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68243651-f1049780-0038-11ea-8f0d-d3759777d0e8.png)

**Comment by ankitkataria** [comment]
What error are you facing @aayush-05 ?

**Comment by aayush-05** [comment]
The link doesn't redirect to the website of the email client when it is not installed on the system. But I guess it is the standard for the "mailto:" attribute. I even had a conversation with Satvik regarding this.

![image](https://user-images.githubusercontent.com/47032027/68533869-f53ff600-0353-11ea-8120-1788e4aee519.png)

Should I close this issue for now @ankitkataria ?

**Comment by ankitkataria** [comment]
Yup. :grin:
