### ISSUE TITLE
Example Div elements' size mismatched

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#532]
**Describe the bug**
The size of the elements in given Examples on the Homepage gets mismatched to each other when the browser window is resized.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Scroll down to 'Featured Examples'
3. Resize the browser window

**Expected behavior**
All the elements showcased should have equal dimensions irrespective of the Heading contents. This can be done using equal and same CSS properties for each and setting a limit to the characters of topic shown.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68244516-fcf15900-003a-11ea-8839-c37b876ba1f5.png)

**Comment by Shivansh2407** [comment]
Hey @aayush-05 I would like to work on this .

**Comment by Shivansh2407** [comment]
We can solve this issue by add CSS media queries for different zooming levels I guess?
What say @aayush-05 ?

**Comment by aayush-05** [comment]
Yes that can be done. But solving this now won't be beneficial, because anyways we are revamping the UI.

**Comment by Shivansh2407** [comment]
This Needs to be reopened. The issue has not been fixed yet @tachyons . See error in the screenshot below.
![Capture](https://user-images.githubusercontent.com/42182955/76165287-c6a81f80-617b-11ea-9c7f-e45c78e869cc.PNG)

**Comment by aayush-05** [comment]
Any possible solution for this @Shivansh2407 ? This is happening due to the different aspect ratios of the images, so setting a max-height won't help as then the remaining text would overflow.

**Comment by Shivansh2407** [comment]
> Any possible solution for this @Shivansh2407 ? This is happening due to the different aspect ratios of the images, so setting a max-height won't help as then the remaining text would overflow.

I am trying to fix this . If I get any better solution I will open up a PR.

**Comment by yash15601** [comment]
@Shivansh2407  @aayush-05  try placing the view button in center  after the text and add new div of class container to text ? i think this will work

**Comment by Shivansh2407** [comment]
> @Shivansh2407 @aayush-05 try placing the view button in center after the text and add new div of class container to text ? i think this will work

@aayush-05 and @yash15601 the Image thing is fixed now, But the Name is of different Length so I am thinking to add ... at the end of the Long names to avoid this type of situation. Because if anyone adds or updates the Names in future then also this fix can work

**Comment by yash15601** [comment]
@Shivansh2407  good idea this the possible way we can prevent the length of text being long @aayush-05 your views on this

**Comment by aayush-05** [comment]
Feels right @Shivansh2407 , send a screenshot and get it verified by @nitin10s for confirmation

**Comment by Shivansh2407** [comment]
![150zoom](https://user-images.githubusercontent.com/42182955/76166250-3b328c80-6183-11ea-8792-6ad20322212a.PNG)
@nitin10s and @tachyons I will be doing something like this . This is a screenshot for 150% zoom , I will be adding ... to long names so that whenever the user zooms in or views it on mobile deices then they do not face this issue. Please let me know your views on this.

**Comment by yash15601** [comment]
LGTM🙂

**Comment by aayush-05** [comment]
@Shivansh2407 are you still working on this ?

**Comment by aayush-05** [comment]
@tachyons @nitin10s can we reopen this issue

**Comment by Shivansh2407** [comment]
I think @abstrekt has worked on this . See #1347

**Comment by abstrekt** [comment]
my pr was for different UI components I guess, if no one's assigned for this issue, I can work on it, @aayush-05

**Comment by aayush-05** [comment]
Got it @abstrekt . Once you push those cards to rails partial do the same with these one too, because these two are majorly the type of cards we are using. Then we can just import them wherever required and it would help maintain consistency across screens

**Comment by abstrekt** [comment]
> Got it @abstrekt . Once you push those cards to rails partial do the same with these one too, because these two are majorly the type of cards we are using. Then we can just import them wherever required and it would help maintain consistency across screens

ok I'm on it

**Comment by aayush-05** [comment]
@tachyons @nitin10s this can be closed.
