### ISSUE TITLE
Logo image missing from Navbar

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#533]
**( Under GCI )**

**Describe the bug**
The CircuitVerse Logo on the Navigation Bar disappears when the browser window is resized to 1016*676 px

**To Reproduce**
1. Go to 'circuitverse.org'
2. Resize the browser window to 1016*676 px
3. See error

**Expected behavior**
The Logo div element should have fixed width irrespective of the current dimensions of the browser window. This can be done by fixing a min width value for the logo image div element.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68244968-03cc9b80-003c-11ea-8ace-c8d233967f01.png)

**Comment by sourabhb77** [comment]
add following css =>
navbar-brand img {
     max-width =100%
}

**Comment by aayush-05** [comment]
Hey @sourabhb77 
I am not a contributor to this project; so can't give you the rights to merge your commits with the code base.
You can make a pr for this issue and get it reviewed by @ankitkataria or @satu0king

**Comment by sharmaaditya570191** [comment]
Hi @ankitkataria and @satu0king  . I would like to take this up.

**Comment by shipcy** [comment]
I wanna take this.

**Comment by aayush-05** [comment]
@shipcy I think this task is under GCI now, so you can take it from the GCI website only

**Comment by shipcy** [comment]
@aayush-05 But there are no such mentions here that it is a GCI task.

**Comment by aayush-05** [comment]
@shipcy sorry about that. I have made the changes now.

**Comment by Shivansh2407** [comment]
@aayush-05 can I work on this now as GCI is Over I guess?

**Comment by aayush-05** [comment]
Saying it again but UI revamp is supposed to solve all of the minor UI bugs. You can help us in with that, join the ux channel on slack

**Comment by Shivansh2407** [comment]
Ok cool @aayush-05 .
