### ISSUE TITLE
Can only authors reply to comments?

### ISSUE THREAD

**Issue by anshh** [CircuitVerse/CircuitVerse#535]
**Is your feature request related to a problem? Please describe.**
I observed in https://circuitverse.org/users/3/projects/248 and https://circuitverse.org/users/3/projects/249 too that a user cannot reply to comments by another user

**Describe the solution you'd like**
I'd like for this platform to be made more user-friendly and supportive of the doubts raised by our fellow engineers so that any user can reply to a comment as long as it doesn't violate community guidelines.

![image](https://user-images.githubusercontent.com/32905727/68250890-dc64d700-0019-11ea-8164-123d3074e12f.png)

Yes I'd like to work on this with others

**Comment by ShreyaPrasad1209** [comment]
I'm able to comment successfully. 
![image](https://user-images.githubusercontent.com/43600306/68400119-815bed00-019d-11ea-97b0-a150fadb0877.png)

**Comment by anshh** [comment]
> I'm able to comment successfully.
> ![image](https://user-images.githubusercontent.com/43600306/68400119-815bed00-019d-11ea-97b0-a150fadb0877.png)

I asked about replreplying to the comments which are already there not make a new comment.

**Comment by ankitkataria** [comment]
We use [commontator](https://github.com/lml/commontator) gem for handling comments. Although there is no documentation for nested replies, there seems to be some recent commits regarding the same. figuring out how to enable this would be really interesting.
