### ISSUE TITLE
No loading screen in simulator

### ISSUE THREAD

**Issue by anshh** [CircuitVerse/CircuitVerse#537]
**Is your feature request related to a problem? Please describe.**
While loading https://circuitverse.org/simulator I observed that it took it's fair share of time. While loading this we can show a cool loader which may slow the loading further by second or two but is great from psychological point of view.

**Describe the solution you'd like**
Add a loading animation
**Describe alternatives you've considered**
We can also show the data that it has already fetched but that won't be much helpful here I think so
Yes I can easily add a loader

**Comment by aayush-05** [comment]
Similar to #466

**Comment by aayush-05** [comment]
Can be closed @tachyons
