### ISSUE TITLE
google and fb signin not working - gitpod

### ISSUE THREAD

**Issue by Parikshit-Hooda** [CircuitVerse/CircuitVerse#538]
**Describe the bug**
Google signin in Gitpod not working

**To Reproduce**
1. Run gitpod on browser.
2. In launch window, go to signin.
3. Click on google sign-in.

**Expected behavior**
Successful signin

**Screenshots**

**Desktop (please complete the following information):**
 - Gitpod

**Additional context**
![googlesigningitpod](https://user-images.githubusercontent.com/25405707/68256564-90845300-0056-11ea-833c-a78d6f72a528.gif)

**Are you working on this issue? (Yes/No)**
No.

**Comment by Parikshit-Hooda** [comment]
gitpod bash : 
`Started GET "/users/auth/google_oauth2" for 10.140.0.21 at 2019-11-05 23:54:28 +0000
Cannot render console from 10.140.0.21! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
I, [2019-11-05T23:54:28.666565 #25702]  INFO -- omniauth: (google_oauth2) Request phase initiated.`

**Comment by tachyons** [comment]
We will have to add documentation for how to configure fb and Google integration in gitpod and localhost
