### ISSUE TITLE
Forbid Combinational Analysis for teachers

### ISSUE THREAD

**Issue by blane1257** [CircuitVerse/CircuitVerse#54]
There should be an option for teachers to forbid combinational analysis for assignments, as it seems many students use it.

**Comment by HypheX** [comment]
Completely agree!


Fierro Salinas Luis Alberto-3C

**Comment by satu0king** [comment]
Haha true, my professor got me to disable it for his course. I completely disabled it for him. 
It is actually a feature in the to-do list.

**Comment by fpintos** [comment]
I'm not sure disabling the feature would actually prevent students from using it.

One can always open the simulator (disconnected from an assignment), build the circuit with the tool and simply cut-and-paste it (or visually copy it) back into a project where the feature was disabled. In a more extreme case, one can produce the circuit in a completely different program and then copy the resulting circuit back into CircuitVerse.

I'm not a professional teacher but it sounds like it would be more productive to teach students how and why the tool works and once they understand it, let them play with it and use it when necessary. I suppose that if a student can't build these circuits by hand he/she won't do well building more advanced circuits too.

**Comment by satu0king** [comment]
@fpintos, yes you are right students will find ways to overcome this. The initial plan was to give an option to disable cross-project copy/paste. Hence allowing only copy paste within the assignment. This will also ensure people cannot copy/paste from other public projects too. 

>I 'm not a professional teacher but it sounds like it would be more productive to teach students how and why the tool works and once they understand it

Yes, that is correct. In my university, except the first assignment, all further assignments allowed the use of combinational analysis (even encouraged it).
