### ISSUE TITLE
Fix Navbar in Mobile view

### ISSUE THREAD

**Issue by rajat2502** [CircuitVerse/CircuitVerse#540]
**Describe the bug**
The Navbar is not responsive as it is not working properly in the Mobile view of the website. The navbar toggler is not completely visible in the mobile view and that's why it is hard to click on a small screen.

**To Reproduce**
1. Go to https://circuitverse.org/'
2. Change the view to iPhone 6/7/8
3. Notice the Navbar and its toggler

**Expected behavior**
The Navbar should be responsive and should be properly visible in the desktop as well as its desktop view.

**Screenshots**
![Screenshot from 2019-11-06 07-45-10](https://user-images.githubusercontent.com/42200276/68262755-368d8880-006a-11ea-999d-dd955680b543.png)

**Desktop (please complete the following information):**
 - OS: Linux (Ubuntu)
 - Browser: Google Chrome
 - Version 77.0.3865.120

**Additional Issue**
The navbar is not uniform in all the pages. 
![Screenshot from 2019-11-06 08-00-55](https://user-images.githubusercontent.com/42200276/68263263-946ea000-006b-11ea-9957-8089c81d1494.png)
![Screenshot from 2019-11-06 07-45-10](https://user-images.githubusercontent.com/42200276/68263277-9afd1780-006b-11ea-8752-aa324c949b93.png)

**Are you working on this issue? (Yes/No)** No, this issue is for GCI students.

**Comment by ankitkataria** [comment]
Related to #492

**Comment by dkapur17** [comment]
I would like to work on this issue if that's alright.

Cheers!

**Comment by dkapur17** [comment]
I have noticed that the code in the repository is for the new UI that is being planned for the website. As such, there is no way for me to edit the source code of the currently hosted site. So do I drop this issue? Thanks.

**Comment by aayush-05** [comment]
This issue would be automatically solved when the New UI gets shifted to the production branch, so no need to solve it now.
This can be closed @tachyons
