### ISSUE TITLE
Title correction

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/CircuitVerse#541]
**Describe the bug**
In circuit element there is one section is decoder&plexer it should be decoder& multiplexer
Because plexer itself have no meaning in digital circuit

**Screenshot**
![Screenshot_20191106-125844~2](https://user-images.githubusercontent.com/46513305/68277713-c5fc6100-0095-11ea-8e94-c16f9dcab558.png)

**Are you working on this issue? (Yes/No)**no but will try

**Comment by satu0king** [comment]
Well plexers is short of multiplexer and demultiplexer :P , we need to come up with a new name as we have encoders as well.

**Comment by dev9414** [comment]
What about deplexer

**Comment by dev9414** [comment]
Can't we make separate section like encoder/decoder And
multiplexer/demultiplexer
