### ISSUE TITLE
Sign up constraints

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/CircuitVerse#543]
**Describe the bug**
In signup section Tobe specific name field should contain only alphabet not any types of symbol/number
PS:it is act as username section because it can contain alphanumeric and symbol

**To Reproduce**
1. Go to 'signup'
2. Click on 'name'
3. Enter 'any alphanumeric symbol'

**Expected behavior**
When we enter any symbol or number it should pop out with saying "only alphabet can be used in name field"

**Desktop (please complete the following information):**

**Are you working on this issue? (Yes/No)**
No this is for GCI Students

**Comment by satu0king** [comment]
Hey, 
The user should be free to use handles. For example dev9414 if he wants to be pseudo-anonymous. I don't see if there is an issue with this.
