### ISSUE TITLE
Criteria for title

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/CircuitVerse#545]
**Is your feature request related to a problem? Please describe.**
I seen in  recent circuit section that some of circuit titled randomly.

**Describe the solution you'd like**
We should define some criteria for circuit nomenclature in recent section

![Screenshot_20191106-190657~2](https://user-images.githubusercontent.com/46513305/68303208-64ee8080-00c9-11ea-8f5c-33fde5e6d585.png)

**Are you working on this? (Yes/No)**
No, this is for GCI Students

**Comment by satu0king** [comment]
Hey @dev9414 , 
These recent circuits are actual recent circuits by users. We cannot and should not put a constraint on the language they can use!

**Comment by dev9414** [comment]
Ok got it
