### ISSUE TITLE
Template is not dynamic mobile view

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/CircuitVerse#546]
**Describe the bug**
In mobile view of this page there blank column type part is there

**To Reproduce**
1. Go to 'circuitverse.org' in mobile
3. Scroll right side to '....'

**Expected behavior**
Page should look like same as desktop view

**Screenshots**
![Screenshot_20191106-191858](https://user-images.githubusercontent.com/46513305/68303965-e5fa4780-00ca-11ea-9c47-38f305d2ec5b.png)

**Are you working on this issue? (Yes/No)**
No, this is for GCI STUDENTS

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
This issue is already opened at #540
