### ISSUE TITLE
Error message color should be in red.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#548]
**Is your feature request related to a problem? Please describe.**
The error message displayed is in the same colour as the rest of the components present of the screen.
![Screenshot from 2019-11-06 20-13-14](https://user-images.githubusercontent.com/28510494/68308129-55c00080-00d2-11ea-8e57-ce0afd46f11e.png)

**Describe the solution you'd like**
The error displayed when a form is submitted should be red in colour. It will make the UI better and would be more noticeable for a user. 

**Additional context**

**Are you working on this? (Yes/No)**

**Comment by MrBartusek** [comment]
@plxity  this is fixed in new ui can be closed
![image](https://user-images.githubusercontent.com/23432278/71687744-daf82680-2d9e-11ea-8684-064a074fa3a8.png)

**Comment by ciphereck** [comment]
@tachyons @nitin10s this can be closed since this issue is fixed in new UI as mentioned by MrBartusek
