### ISSUE TITLE
Add "eye button" in password field to view it.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#549]
**Is your feature request related to a problem? Please describe.**
As of now, there is no option to view your password. Like most of the website usually have an eye icon for viewing the password.

**Describe the solution you'd like**
Adding an option to view the password entered in the input field.

**Describe alternatives you've considered**

**Are you working on this? (Yes/No)**

**Comment by M06631** [comment]
first you need to use font-awesome css to show eye icon
second you need pure javascript or jQuery to change the 'password' type of html input to 'text' type and vice versa....
here is a live example..
https://codepen.io/Sohail05/pen/yOpeBm
wish you find it usefull :)

**Comment by plxity** [comment]
@M06631 Thanks for the response. Actually I have already figured out the way to solve it :)

**Comment by M06631** [comment]
Please assign issue to me :)

**Comment by plxity** [comment]
@satu0king Can you please assign this to him? Thank you :)

**Comment by M06631** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/660

Review this PR

**Comment by aayush-05** [comment]
This can be closed @tachyons

**Comment by tachyons** [comment]
Fixed
