### ISSUE TITLE
Keyboard shortcut changes

### ISSUE THREAD

**Issue by HypheX** [CircuitVerse/CircuitVerse#55]
I suggest the following changes: 

1. Pressing L should prompt the user to change the label.    (It currently deletes it)
2. Pressing D should prompt the user to change the delay.

It would be great to see those changes!

**Comment by satu0king** [comment]
Definitely will do

**Comment by sanctophagus** [comment]
@satu0king I'll be taking this up, ok?

**Comment by armudgal** [comment]
@sanctophagus Please go forward

**Comment by sanctophagus** [comment]
Presently, `D` is used for changing direction, so won't be able to use it for delay. How should I proceed?

**Comment by sanctophagus** [comment]
Due to bug mentioned in issue #121 , I am facing problem implementing keyboard shortcut for changing label.
An alternative would be to prompt to change the Label, something like
![Label_Alternative](https://user-images.githubusercontent.com/31550423/54153185-f5a28d00-4464-11e9-996a-f150033f13e4.png)
@armudgal  @satu0king How should I proceed?

**Comment by satu0king** [comment]
Not very sure, the keyboard shortcuts will vary user to user and so has to be configurable. Currently, WASD is used to rotate the element as someone requested it but not everyone wants to use it.

**Comment by sanctophagus** [comment]
@satu0king, can you please elaborate, what exactly you want, in the final feature?

**Comment by Shivansh2407** [comment]
Is this still open ?

**Comment by abstrekt** [comment]
can be closed, as it will be addressed as part of the GSOC project,
@nitin10s

**Comment by nitin10s** [comment]
Let's leave such issues that "will" be addressed until they are addressed properly.

**Comment by abstrekt** [comment]
> Let's leave such issues that "will" be addressed until they are addressed properly. 

yes, that would be better
