### ISSUE TITLE
Add padding in mobile view.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#550]
**Describe the bug**
Padding should be present between the buttons.
![Screenshot from 2019-11-06 20-35-43](https://user-images.githubusercontent.com/28510494/68309868-1a730100-00d5-11ea-8092-9cdf74c7ef50.png)

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to signup option in mobile view.

**Expected behaviour**
There should be proper padding between the buttons to make the UI better

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chrome]

**Comment by namantechlabs** [comment]
Where can I find the respective CSS file for the login page?
