### ISSUE TITLE
Fix search field in mobile view

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#551]
**Describe the bug**
A dropdown adjacent to the search field is not proper in the mobile view.
![Screenshot from 2019-11-06 20-46-11](https://user-images.githubusercontent.com/28510494/68310783-96ba1400-00d6-11ea-9bfc-43d99c815dc6.png)

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to the navigation bar in the mobile view

**Expected behaviour**
The dropdown should be visible properly in mobile view.

.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Comment by myfrom** [comment]
Can't reproduce neither on my phone, nor in Chrome DevTools,
browsers: Edge Dev 80, Chrome Dev 80, Chrome Stable 78


![circuitverse org_](https://user-images.githubusercontent.com/19410489/69986776-5798aa80-153e-11ea-86f7-421ce7c8ea42.png)

**Comment by fluctix** [comment]
I also cannot reproduce this on my phone.
