### ISSUE TITLE
Current page highlight on navbar

### ISSUE THREAD

**Issue by Tanish0019** [CircuitVerse/CircuitVerse#553]
**Is your feature request related to a problem? Please describe.**
The page you're on is not highlighted on the navbar.

**Describe the solution you'd like**
When you go to any page that page's button in the navbar should be highlighted.

**Additional context**
![Screen Shot 2019-11-06 at 10 05 47 PM](https://user-images.githubusercontent.com/30210495/68317825-c91d3e80-00e1-11ea-95dd-50436e5759d8.png)

**Comment by Shivansh2407** [comment]
I would like to work on this.
