### ISSUE TITLE
Unequal width and length of Input Fields

### ISSUE THREAD

**Issue by Anjalizi** [CircuitVerse/CircuitVerse#555]
**To Reproduce**
Can be found on http://localhost:8080/groups/1/assignments/new

**Screenshots**
![Issue](https://user-images.githubusercontent.com/26696144/68319725-c6701880-00e4-11ea-815b-30e6088fcd2c.png)

Also, unequal width of input fields for "Name", "Grading Scale" and "Deadline"

**Comment by aayush-05** [comment]
A similar issue had been created earlier; you can close this one.

**Comment by Anjalizi** [comment]
Is it fine now @aayush-05 ?

**Comment by aayush-05** [comment]
Yes @Anjalizi . Keep contributing :)
