### ISSUE TITLE
"New Assignment" page should be Fit to Screen 

### ISSUE THREAD

**Issue by Anjalizi** [CircuitVerse/CircuitVerse#556]
**To Reproduce**
Go to http://localhost:8080/groups/1/assignments/new

**Screenshots**
![issue2](https://user-images.githubusercontent.com/26696144/68320240-98d79f00-00e5-11ea-8fc1-8b0487a65c50.png)

This created an issue of misalignment of the footer.

**Comment by MrBartusek** [comment]
![image](https://user-images.githubusercontent.com/23432278/71688317-f0ba1b80-2d9f-11ea-8974-da311c03e4fc.png)
works fine on chromium, maybe it has been fixed
