### ISSUE TITLE
The website is not properly responsive in mobile view. 

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#557]
**Is your feature request related to a problem? Please describe.**

The homepage is not properly responsive in the mobile view. The navbar breadcrumb is not completely visible when the webpage first loads and also, there is an overflow in the x-direction. Moreover, please make the pagination bar provided at the bottom of the page responsive.

**Describe the solution you'd like**

Add media queries or add bootstrap classes to make it more responsive and add an overflow-x hidden property in the body of the page.

**Additional context**

![Screenshot_20191106-115813](https://user-images.githubusercontent.com/42115530/68320923-d7218e00-00e6-11ea-986d-6b16538bfcaa.png)
![Screenshot_20191106-120407](https://user-images.githubusercontent.com/42115530/68320937-db4dab80-00e6-11ea-8de7-e4c5ce9e9e22.png)

**Are you working on this? (Yes/No)**
No. This is for GCI 2019.

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
Already opened at #540

**Comment by PragatiVerma18** [comment]
There is an overflow in the x-direction. Moreover, the next and previous buttons at the bottom of the pagination bar at the bottom of the page are barely visible. This needs to be made responsive. These points are not pointed at #540 and need to be fixed as well.

**Comment by ShreyaPrasad1209** [comment]
Pagination bar issue is opened at #494 . Overflow in x-direction is understood, not needed to be stated explicitly.

**Comment by ankitkataria** [comment]
Closing this in favour of #540 and #494
