### ISSUE TITLE
Overview iframe element and Deadline not rightly aligned

### ISSUE THREAD

**Issue by Anjalizi** [CircuitVerse/CircuitVerse#558]
**To Reproduce**
Navigate to http://localhost:8080/groups/1/assignments/1

**Screenshots**
![issue3](https://user-images.githubusercontent.com/26696144/68320927-d7ba2480-00e6-11ea-8d29-60ade9fc556c.png)

P.S. The box isn't a textbox since not clickable.

**Comment by aayush-05** [comment]
The box is actually an iframe element to show the thumbnail/overview of the assignment.
![image](https://user-images.githubusercontent.com/47032027/68420405-4b7d2f80-01c2-11ea-9e9d-e324f0e4a4ba.png)
 But it is not working properly, you can change the title of the issue for better understandability.

**Comment by sakshi1499** [comment]
@Anjalizi @aayush-05 This is not an empty box. This is the part where the students who have submitted their assignments can be seen.
![pic](https://user-images.githubusercontent.com/42520146/68473586-647cf380-0249-11ea-9229-477c9f690e1a.PNG)

**Comment by ankitkataria** [comment]
Though the box serves it's purpose, having a better UI on this page can help. When there are no submissions a `No submissions yet` notice would be nice, instead of the empty circuit display box.

**Comment by aayush-05** [comment]
@nitin10s we have to design the assignments page too.
