### ISSUE TITLE
Member invitation not being received even after MULTIPLE invites

### ISSUE THREAD

**Issue by Anjalizi** [CircuitVerse/CircuitVerse#559]
**To Reproduce**
Navigate to http://localhost:8080/groups/1

**Screenshots**
![issue4](https://user-images.githubusercontent.com/26696144/68322323-3f716f00-00e9-11ea-9259-8a9dd14fcd37.png)

P.S. The system should keep track of the invites being sent and shouldn't allow sending multiple invites

**Comment by ankitkataria** [comment]
> P.S. The system should keep track of the invites being sent and shouldn't allow sending multiple invites

[This](https://github.com/CircuitVerse/CircuitVerse/blob/master/app/models/group_member.rb#L6) should ensure that emails are only sent when new group members are created. 

> Navigate to http://localhost:8080/groups/1

Emails cannot be sent locally until SMTP has been configured.
