### ISSUE TITLE
"Bug" with bits and integer limits

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#56]
So I was putting together a group of 16 bit full adders to make a 64 bit full adders. This was forked from another project of course. I was testing it out, and then the simulation began to act strangely. Somehow, it believed that the binary values were negatives (and appended a negative sign onto the inputs). I also wasn't able to change any further values past a certain point. My guess as to the source of this issue is that the simulation literally had overflow errors (my real computer, not the simulated one), and so believed the numbers I was inputting were negative. I assume this is also due to bit's being grouped together as a single number, instead of their individual boolean values. This isn't exactly a problem, and I don't expect it to be solved immediately (unless you're aware of an easy solution). This situation is already completely out of proportion and likely to never occur in any legitimate circumstance, but it does show a limitation in the CurcuitVerse simulation.

You can see for yourselves in this project: https://circuitverse.org/users/1577/projects/4038

**Comment by HypheX** [comment]
I ran across this problem while working on my BCD calculator. It appears like the maximum bidwidth usable is 32 bits. 

Any component with a higher bitwidth is prone to throw errors, or output nonsense. I ended up using 2x 32 bit wires for my 64 bit output.

**Comment by HypheX** [comment]
> 
> 
> Me and blane have tried doing huge RAM's before, but even if we used
> 
> It would be lovely to see a bit width property and a separate "address bit width" property, allowing for the customization of the RAM's size to its full extent.
> 
> However, one has to keep in mind that the maximum bit width possible is 32, possibly due to limitations with the browsers only allowing integers up to 2^32-1.
> A fix for this is storing the states of multi-bit wires as arrays and not as integers, as it is currently done.
> 
> An even better fix would be to use 1 integer for every 32 bits in a wire, allowing for virtually unlimited bit widths without changing the code that much.

**Comment by ankur54** [comment]
Hi. Are there any suggestions on how to tackle this problem? I think this problem is tremendously trivial, as such errors also occur in programming languages like C/C++ etc. If anyone has any idea regarding this issue, I would like to work on.

**Comment by satu0king** [comment]
> Hi. Are there any suggestions on how to tackle this problem? I think this problem is tremendously trivial, as such errors also occur in programming languages like C/C++ etc. If anyone has any idea regarding this issue, I would like to work on.

It is easy to tackle if we are to implement or designing something from scratch. We have a whole system that relies on the regular integer of javascript, we cannot just change it easily.

**Comment by ankur54** [comment]
So, what is the resolved output that you want?
