### ISSUE TITLE
Navbar toggle button is not working in smaller viewports.

### ISSUE THREAD

**Issue by JoshuaPoddoku** [CircuitVerse/CircuitVerse#562]
**Describe the bug**
The navigation bar toggle button is not placed well in smaller viewports.

**To Reproduce**
1. Inspect the home page
2. Switch to the available viewport (411 x 731) Pixel 2.
3. Check all the devices and see the difference.
3. Observe the toggle button coming out of the actual position. i.

**Expected behavior**
The button should be responsive enough to avoid unwanted padding (space) below.

**Screenshots**

![Screenshot (6)](https://user-images.githubusercontent.com/31725457/68331423-f88c7500-00fa-11ea-8b22-eb49681ff748.png)
Toggle button in the navbar not visible for the Pixel 2 device.

![Screenshot (7)](https://user-images.githubusercontent.com/31725457/68331477-08a45480-00fb-11ea-9157-9568bb88c90b.png)
The button is visible after dragging the page towards the right which is not right!

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Chrome
 - Version: 77.0.3865.120

**Additional context**
It is the same for all view-ports so the styling can be changed based on device-size so that the site gets accessible to all.

**Are you working on this issue? (Yes/No)**
Yes, I would like to contribute

**Comment by aayush-05** [comment]
**Duplicate Issue** 
Same issued opened at #540 

You can close this one.

**Comment by JoshuaPoddoku** [comment]
I'm sorry. And thanks for letting me know. Please check other issues also.
:)
