### ISSUE TITLE
Unusual error message on Deleting Circuit

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#566]
**Describe the bug**
The Delete Circuit button in the simulator raises an error to have atleast two circuit windows open , if you want to delete the current circuit. While rather it should just delete the current circuit window.

**To Reproduce**
1. Open Simulator
2. Click on 'Delete Circuit'
3. See error

**Expected behavior**
The Delete Button does so that it can switch to the other circuit window when the first one is deleted; but a better option can be to redirect back to the home page when the single circuit is deleted.
**(Edit : Make the simulator redirect to open a new fresh window inside the simulator)**
**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68358355-46769c80-013e-11ea-97b2-6b14a318d87f.png)

**Comment by satu0king** [comment]
@MrBartusek @aayush-05, while this is one way of looking at it, I don't think the end user actually wants this. When the user says delete circuit, it is not delete simulator. Moreover, this doesn't allow the user to save the circuit. Instead what would be interesting is, when the single circuit is deleted, it would help if the circuit was replaced with a new empty circuit (starting fresh).
