### ISSUE TITLE
Download as Image feature for someone else's circuits

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#568]
**Is your feature request related to a problem? Please describe.**
Currently, we have the ability to download our own circuits as Images via the simulator window. In order to download someone else circuits, we are first required to fork that project, then open it up the simulator window and then download it

**Describe the solution you'd like**
But it would great, if the user have this option on the Project Info page; so as to be able to download someone else project straight away without forking it and creating unnecessary copies for it.
A 'Download as Image' button along the Fork button would be good.

![image](https://user-images.githubusercontent.com/47032027/68359425-d538e880-0141-11ea-99ae-b2b359cd8979.png)

**Comment by ShreyaPrasad1209** [comment]
Forking lets you know who's using your circuits.

**Comment by aayush-05** [comment]
I didn't know that; on which page does it show that.
Further, the feature suggested to not only let fork someone else's circuit but make them download as images as well.
Because the user might not have the functionality to embed the circuits necessarily, say maybe in a word document.
