### ISSUE TITLE
Subcircuit saving and loading + additional subcircuit improvements

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#57]
- [ ] Saving subcircuits for use in other projects

This has probably (definitely) been suggested before, but I have some ideas for some extra improvements to sub curcuits, and a way of distributing them to other people, or at least between projects. The idea is that you can save subcircuits to a tab in the "circuit elements" tab, which will allow you to utilise that subcircuit elsewhere. This will link the subcircuit to the original project whence it came from, so changes to the subcircuit in that project will be reflected elsewhere. This will also make using subcircuits far easier to use, since they can be dragged from the "circuit elements" tab, instead of using the popup which is rather annoying.

- [ ] Custom subcircuit textures

Another feature would be to add custom textures to subcircuits, by uploading your own image to be used on your subcircuit. This would make subcircuits incredibly customisable, and a great addition to projects. The downside to this is that subcircuits would have to be managed much more thouroughly, as they would also have image data stored too. It's also possible to see people "trolling" via the use of these customizable images on their subcircuits. It's an idea all the same, even for a future date.

**Comment by satu0king** [comment]
> The idea is that you can save subcircuits to a tab in the "circuit elements" tab, which will allow you to utilise that subcircuit elsewhere.

I like this idea. This definitely is a must have feature. For now, you could simply copy relevant portions of any circuit and paste it in your new circuit, Everything gets copied correctly.

> This will link the subcircuit to the original project whence it came from, so changes to the subcircuit in that project will be reflected elsewhere.

This is a bit ambitious, what is more achievable is simply duplicate the current version of the subcircuit. In case it is updated, it has to be duplicated again.

**Comment by ankur54** [comment]
Hi. I am interested in this project of reusing subcircuits. I would definetely like to contribute to it. Currently I know JavaScript, C++, HTML, CSS and also have some experience in python. Could you please help me in how to proceed?
