### ISSUE TITLE
Purpose of rectangle on bottom right of simulator unclear

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#570]
**Is your feature request related to a problem? Please describe.**
This rectangle doesn't seem to serve any purpose. Moreover, it's taking up space in the simulator.

**Describe the solution you'd like**
If it has a purpose then make it functional else remove it.
**Additional context**
![image](https://user-images.githubusercontent.com/43600306/68396353-730ad280-0197-11ea-8cba-d9274d976f85.png)

**Are you working on this? (Yes/No)**
For GCI participants

**Comment by aayush-05** [comment]
@ShreyaPrasad1209 isn't that box showing the overview of the positions of the elements present on the simulator window.
![image](https://user-images.githubusercontent.com/47032027/68400444-119a3200-019e-11ea-9424-c49e18ec4a5a.png)

**Comment by ShreyaPrasad1209** [comment]
It didn't in mine. I guess we have to add more than two elements to show an overview.

**Comment by shubhankarsharma00** [comment]
@ShreyaPrasad1209, Should we close this issue?

**Comment by ShreyaPrasad1209** [comment]
Yep I think so
