### ISSUE TITLE
Improve dropdown in the navbar.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#571]
**Is your feature request related to a problem? Please describe.**
As of now, the dropdown is the usual one.
![Screenshot from 2019-11-07 23-11-48](https://user-images.githubusercontent.com/28510494/68413512-69dc2e80-01b4-11ea-9897-df8af3676441.png)

**Describe the solution you'd like**
We can style the dropdown to make the UI/UX better.

**Are you working on this? (Yes/No)**
For GCI participant

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
This issue is already open at #491
