### ISSUE TITLE
Footer design suggestion

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#572]
**Is your feature request related to a problem? Please describe.**
Made a few changes to the footer. Will change font style after initial changes are approved

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/43600306/68417814-1f12e480-01bd-11ea-85fa-f3615b62ffb7.png)

**Describe alternatives you've considered**
Add shadow effect on hover maybe?

**Are you working on this? (Yes/No)**
For GCI students under good first issue.

**Comment by aayush-05** [comment]
I think rather than Black; dark grey colour similar to the navbar would make it look more good and uniform.

**Comment by ShreyaPrasad1209** [comment]
Actually I was thinking of changing navbar's colour to black

**Comment by aayush-05** [comment]
Oh, okay. Then that's a different story.

**Comment by aayush-05** [comment]
Footer has been redesigned, now this can be closed @tachyons
