### ISSUE TITLE
Add flexbox to div enclosing circuit boxes

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#575]
**Describe the bug**
Currently the image and header of boxes are separate( as shown by border) which makes shadow effect cover only the image part. Also, this makes it difficult to apply any common styling to the box. 

**Expected behavior**
Enclose image and header under a common div so that any changes made to the box will apply to the whole box. Eg: Shadow effect on hover.
**Solution**
Use flex-box property as it aligns every box perfectly and helps in responsiveness too.

**Screenshots**
![image](https://user-images.githubusercontent.com/43600306/68478659-66997f00-0256-11ea-917b-b580daa5c9a6.png)

**Are you working on this issue? (Yes/No)**
For GCI students under medium issue.

**Comment by ankitkataria** [comment]
The image and header are enclosed inside a div. The box-shadow can be given to the outside div.
![image](https://user-images.githubusercontent.com/22021150/68532112-adaf6f00-033f-11ea-9266-81e70b2bac34.png)

Though the circuits section is already pretty responsive, rewriting it using flexbox might be a good beginner task. Is it possible to edit the issue for the same?

**Comment by ShreyaPrasad1209** [comment]
Sure

**Comment by Shivansh2407** [comment]
Can I work on this?

**Comment by ShreyaPrasad1209** [comment]
Sure

**Comment by Shivansh2407** [comment]
Can You please explain me what needs to be done here @ShreyaPrasad1209 ?
Like we should add display : flex ; in the css or anything extra?

**Comment by Shivansh2407** [comment]
@ShreyaPrasad1209 any updates? 
Like we should add display : flex ; in the css or anything else?
