### ISSUE TITLE
Add tooltip in the upvote and downvote buttons.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#576]
**Is your feature request related to a problem? Please describe.**
Adding a tooltip in the upvote and downvote will make the UI/UX better.
![Screenshot from 2019-11-08 19-03-12](https://user-images.githubusercontent.com/28510494/68480367-a2364800-025a-11ea-920b-678f3a934950.png)

**Describe the solution you'd like**
Add tooltip property to the buttons.

**Are you working on this? (Yes/No)**
For GCI

**Comment by nitin10s** [comment]
Upvotes and Downvotes are pretty common features you must have seen/used on various platforms. There isn't much need for tooltips for common actions.

**Comment by salomon03** [comment]
Happy new year to all can i have the source code

**Comment by MrBartusek** [comment]
@salomon03 you can access source code[ here](https://github.com/CircuitVerse/CircuitVerse), and this is an issue page, not good place to ask questions like that instead please ask on [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE)

**Comment by Shivansh2407** [comment]
Can I work on this ?
