### ISSUE TITLE
Change font color as existing color macthes with the background.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#579]
**Describe the bug**
Currently, the text colour is the same as the background colour, so seems like no text is present is the `div`

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to any project.
2) Scroll down
3) Click on "new comment" & enter a comment.
4) Click on edit comment.

**Expected behaviour**
Text colour should be similar to color of the rest of the text present on the screen.

**Screenshots**
![Screenshot from 2019-11-08 20-50-57](https://user-images.githubusercontent.com/28510494/68487980-19bfa380-026a-11ea-9bfa-7dbfea764984.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chrome

**Are you working on this issue? (Yes/No)**
For GCI

**Comment by ankitkataria** [comment]
I could not replicate this issue in prod. The empty div there seems to be there for mentions. 

![image](https://user-images.githubusercontent.com/22021150/68531935-e77f7600-033d-11ea-93bc-5807a3fd6de5.png)

![image](https://user-images.githubusercontent.com/22021150/68532005-991ea700-033e-11ea-9541-452cc80aee69.png)

**Comment by plxity** [comment]
@ankitkataria This issue is present in prod as well. Open any project and click on edit comment, edit your comment and then inspect the element mentioned above. You will notice the div present.

**Comment by ankitkataria** [comment]
I did and posted a screenshot of the same, it seems to be empty for me. :thinking:

**Comment by plxity** [comment]
![Screenshot from 2019-11-09 22-45-59](https://user-images.githubusercontent.com/28510494/68532397-beadaf80-0342-11ea-9339-c465d36e8a94.png)
Check out this once.
