### ISSUE TITLE
Add tool tip feature

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerse#580]
**Is your feature request related to a problem? Please describe.**
Currently, when viewing a example project there's a option to fork and embed project but there is no information about what does it means.

**Describe the solution you'd like**
Add hover on text for fork and embed. If no so a short description can be added below and a detailed information about this what does it means can be added to the documentation.

**Additional context**
![Screenshot from 2019-11-08 23-04-43](https://user-images.githubusercontent.com/44617923/68498550-1d105a80-027d-11ea-82c9-952e5b6c2c7b.png)

**Are you working on this? (Yes/No)**
No, this task is for GCI students.

**Comment by aayush-05** [comment]
I guess you are talking about tooltip feature. You can change the issue heading for better understandability.

**Comment by deepak2431** [comment]
@aayush-05 Thanks for the review. Sure, I will do that.
