### ISSUE TITLE
Add counter on Web Page

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerse#581]
**Is your feature request related to a problem? Please describe.**
Currently, there is no information about total page visit.

**Describe the solution you'd like**
Add a counter on web page to track the total page visits.

**Are you working on this? (Yes/No)**
No, this task is for GCI students under medium.

**Comment by plxity** [comment]
@deepak2431 This is not a necessary feature I guess. It is of no use.

**Comment by deepak2431** [comment]
@plxity Thanks for the review. I will close this issue.
