### ISSUE TITLE
Diminishing Circuitverse logo 

### ISSUE THREAD

**Issue by eKuG** [CircuitVerse/CircuitVerse#582]
![2019-11-09](https://user-images.githubusercontent.com/33174166/68503385-b3964900-0288-11ea-898a-8209bbb1b515.png)
The website becomes unresponsive below 1100x800 pixels and the logo seems to dissapear.
Use Media Query

**Comment by eKuG** [comment]
https://circuitverse.org/

**Comment by aayush-05** [comment]
**Duplicate Issue**
Issue already raised under #533

You can close this one.
