### ISSUE TITLE
Improper padding in the heading

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#583]
**Describe the bug**
The heading "CircuitVerse Features" don't have proper padding when the page is opened in the mobile view. The navbar overlaps on the title heading.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Click on 'Features'
3. See error

**Expected behavior**
The heading should have proper padding relative to the other elements on the page. Since the desktop site works well; using media queries to add additional heading would be preferable.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68507571-4091d000-0292-11ea-864e-ad1748c10cb3.png)
![image](https://user-images.githubusercontent.com/47032027/68507584-4b4c6500-0292-11ea-9117-aba10e096a50.png)

**Additional context**
The same problem exists on 'circuitverse.org/contribute' and 'circuitverse.org/teachers'

**Comment by samarpan1738** [comment]
where is the CSS file for this (https://circuitverse.org/features) page?
