### ISSUE TITLE
Unresponsive footer under mobile view

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#584]
**Describe the bug**
The footer of the website becomes unresponsive in mobile view. It does not reduces its size according to the device size and streches on to multiple lines.

**To Reproduce**
1. Go to 'circuitverse.org'
2. Reduce the window to 574*676 or less
3. Scroll down to bottom

**Expected behavior**
The footer div should reduce the elements' size inside it according to the device width.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68508384-47214700-0294-11ea-869e-532133b34a34.png)

**Comment by plxity** [comment]
@aayush-05 Footer looks absolutely fine.

**Comment by aayush-05** [comment]
Footers are never meant to be multilined. Even though we are mentioning the sponsors here they should remain in a single line as in the desktop version.

![image](https://user-images.githubusercontent.com/47032027/68511002-eea17800-029a-11ea-8d8c-e5784389c3e1.png)

The only instance they can be multilined is when we feature them inside the website content segment.

**Comment by plxity** [comment]
@aayush-05 There is nothing like footers are never meant to be multilined. Check website you may get to know. Anyway let the maintainers decide if it is an appropriate issue.
