### ISSUE TITLE
Improper size of controls in circuit preview

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#585]
**Describe the bug**
The circuit preview of the simulator in the Project Info page on mobile view becomes unresponse. The control panel in the preview almost blocks the circuit preview.

**To Reproduce**
1. Go to 'circuitverse.org/examples'
2. Open up any featured example
3. Reduce the browser window to 480*676 or less

**Expected behavior**
The control panel in the preview should be responsive. It should decrease its size accordingly with all the elements of the page.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68509538-29a1ac80-0297-11ea-890f-1a4fc9a1ebec.png)

**Comment by Parikshit-Hooda** [comment]
Hi. I don't think the simulator is meant to go that far low in terms of screen size.

**Comment by aayush-05** [comment]
Okay
