### ISSUE TITLE
Login window link for better user experience

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#586]
**Is your feature request related to a problem? Please describe.**
Since the user cannot comment without logging in, the website shows a statement to log in before being able to comment. But it doesn't provide a link to the login screen; on the mobile devices it can be hard to find the login button since it gets hidden under the navbar dropdown.

![image](https://user-images.githubusercontent.com/47032027/68509840-f4e22500-0297-11ea-9555-95b99e8f4e5b.png)

**Describe the solution you'd like**
A better option would be provide a hyperlink directly in the statement below the comments to directly redirect the user to the login window.

**Comment by wwe123456789** [comment]
https://github.com/login

**Comment by MrBartusek** [comment]
blocked by #767

**Comment by Shivansh2407** [comment]
Can I work on this ?

**Comment by aayush-05** [comment]
See the comment above, this can be done only before solving #767 . I guess the UI revamp will solve both of these issues.
