### ISSUE TITLE
Unresponsive View Count element

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#587]
**Describe the bug**
The element showing the stars and the view count on the project info page is irresponsive. Its size remains same even when the browser window is reduced.

**To Reproduce**
1. Go to 'circuitverse.org/examples'
2. Open up any featured example
3. Reduce the browser window to 480*676 or less

**Expected behavior**
The view count element should be made responsive and its size should remain inside the outer div irrespective of the browser window size.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68510799-78047a80-029a-11ea-91f8-ea8625ef9ba6.png)

**Comment by ShreyaPrasad1209** [comment]
**Duplicate Issue**
Hi, this issue is meant for Interactive Book and is open at https://github.com/CircuitVerse/Interactive-Book/issues/19

**Comment by aayush-05** [comment]
Okay
