### ISSUE TITLE
Improve profile page

### ISSUE THREAD

**Issue by deepak2431** [CircuitVerse/CircuitVerse#589]
**Is your feature request related to a problem? Please describe.**
Since the platform if for different category of users. There is not any information about the type of the user whether he/she is a student or teacher. Their is not much information about the users educational details. As if a user is a school student in which class he is, if he is a UG student his branch details and if he is a teacher his highest qualifications.

**Describe the solution you'd like**
1. Add user type to the sign up page as (Student/Teacher).
2. Ask the users too fill up more information about their educational details as
a) If a user is a school student ask him to fill out his class and school name.
b) If a user is a college student ask them to fill out his year of study and branch details.
c) If a user is a teacher ask him to add his highest qualification.

**Are you working on this? (Yes/No)**
No, this task for GCI students under difficult.

**Comment by NumberC** [comment]
@deepak2431 I got the form setup. How would you like the student and teacher data represented in the database?
