### ISSUE TITLE
Small size and overflowing text of circuit elements in Simulator.

### ISSUE THREAD

**Issue by samarpan1738** [CircuitVerse/CircuitVerse#590]
**Describe the bug**
The circuit elements are very small sized and text is overflowing in some of them too.Without zooming its pretty hard to read.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'simulator'
3. See the circuit elements on the right.

**Expected behavior**
The circuit elements must be big enough to be visible clearly and text overflow must be fixed too

**Screenshots**
![IMG_20191109_145054](https://user-images.githubusercontent.com/30201846/68526336-b3d22b00-0300-11ea-9e0f-e104a9d303a8.png)
![IMG_20191109_145126](https://user-images.githubusercontent.com/30201846/68526337-b765b200-0300-11ea-9091-870efeffdf34.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
 - Browser: Brave
 - Version : 0.70.123 

**Are you working on this issue? (Yes/No)**
Yes

**Comment by yash15601** [comment]
can i work on this??

**Comment by KaustubhDamania** [comment]
Is this issue still open? I'd like to work on it.

**Comment by yash15601** [comment]
@KaustubhDamania  both the issues are solved i think @Shivansh2407 and i have made pr

**Comment by KaustubhDamania** [comment]
Okay, just saw your PR. I think <a href="https://getbootstrap.com/docs/4.3/components/tooltips/">Tooltips</a> would be more useful in this case.

**Comment by Shivansh2407** [comment]
Each element has a defined tooltip @KaustubhDamania .

**Comment by KaustubhDamania** [comment]
@Shivansh2407 I meant the tooltip mentioned below, on hovering on each element, a tooltip would be visible mentioning the name of the element.

![cropped](https://user-images.githubusercontent.com/33577657/77081104-275b1600-6a20-11ea-9eca-4d775093195b.png)

**Comment by Shivansh2407** [comment]
Yes this can be done @KaustubhDamania. Other way of implementing it can be, we can fade the element on hover and then on a light blue faded bg we can show the element name. This way we get more space and also bigger text. I would like to know the views of @satu0king and @nitin10s on this.

**Comment by KaustubhDamania** [comment]
The result will look like this (I haven't styled it yet)

![cropped1](https://user-images.githubusercontent.com/33577657/77082487-22976180-6a22-11ea-8bd9-170d0811b232.png)

@Shivansh2407 @nitin10s

**Comment by yash15601** [comment]
Looks good  will be visible to all  this can overcome the issues of small size element name

**Comment by nitin10s** [comment]
Nope, the text doesn't look associated with the element due to lack of proximity.

**Comment by KaustubhDamania** [comment]
@nitin10s I can make it look like the screenshot I sent earlier, the latest screenshot wasn't styled

**Comment by nitin10s** [comment]
That would be great

**Comment by KaustubhDamania** [comment]
Cool, then I'll start working on this and submit a PR ASAP! @nitin10s
