### ISSUE TITLE
Circuit description should have a word limit.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#591]
**Is your feature request related to a problem? Please describe.**

If the circuit description is too large, then the page has lots of white space below the circuit and lots of text crushed in the other corner. Also, it worsens the responsiveness scenario in the mobile view.

**Describe the solution you'd like**

The circuit description can be given a certain limit such that one can describe the main points and not end up writing a very large explanation. And in case, an explanation is felt necessary, there can be an option to include an explanation and must be shown below the circuit such that the page looks organized. 

**Additional context**

Refer to <a href="https://circuitverse.org/users/3464/projects/16521#"> https://circuitverse.org/users/3464/projects/16521#</a>

![phone view](https://user-images.githubusercontent.com/42115530/68531152-4987ad80-0335-11ea-8bb0-9374d604c636.PNG)

![white](https://user-images.githubusercontent.com/42115530/68531169-720fa780-0335-11ea-8975-c5f3c038313a.PNG)

**Are you working on this? (Yes/No)**
No, it's for GCI 2019.

**Comment by nitin10s** [comment]
Rather than limiting length, we can put a limit on the number of characters shown followed by a "Read More" option. Read more option can maybe redirect them to the doc or better a popup opens displaying the full description and other main details.

**Comment by shubhankarsharma00** [comment]
One more option can be having the word limit for description and giving an option to upload a separate markdown file that can have an in-depth explanation of the whole circuit (like a report for a project). This alternative is easier to implement though I personally believe having a separate page would be very cool.

**Comment by nitin10s** [comment]
The point you are mentioning is great when the majority of the users who upload their circuits want to give an in-depth explanation. By observing the current users, we see such users are way too less. So redirecting the users to a new complete page will just add more friction in their journey. IMO
