### ISSUE TITLE
An unusual alert message asking for bitwidth pops up on the window on opening some circuits.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#593]
**Describe the bug**

An unusual alert message asking for bitwidth pops up on the window on opening some circuits.

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'https://circuitverse.org/users/7229/projects/34327'

**Expected behaviour**

There should be some other method of taking input rather than asking for it immediately as the page loads because the person opening may not know at first what is the project about.

**Screenshots**

![unusual message on opening circuit](https://user-images.githubusercontent.com/42115530/68532652-287b8880-0346-11ea-93c6-40c2a9871db5.PNG)

**Are you working on this issue? (Yes/No)**
No, for GCI 2019.

**Comment by aayush-05** [comment]
Hey !
This isn't a bug, but an input required for the logic gates to work properly. Bit width suggest the length of the number in binary form to be calculated.

![image](https://user-images.githubusercontent.com/47032027/68533669-a4c79900-0351-11ea-9c21-e2e0755b32aa.png)

**Comment by PragatiVerma18** [comment]
But asking for value in an alert message like this doesn't look welcoming to beginners, maybe have some default and then allow the user to modify it because if someone is just looking at examples it doesn't clarify what is bit width or why is it required. It's just a suggestion.

**Comment by aayush-05** [comment]
There is actually a bit-width column in the simulator window with default value of 1.

![image](https://user-images.githubusercontent.com/47032027/68534689-486a7680-035d-11ea-8a76-d0f0d05cb3bb.png)

The problem might be with that specific example. But anyways I think a tooltip/description would be good to have in the alert.
