### ISSUE TITLE
No option to remove uploaded photo in profile section.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#595]
**Is your feature request related to a problem? Please describe.**
There should be a feature to remove uploaded photo in profile section.

**Describe the solution you'd like**
Implement a function to remove the existing photo from profile section.

**Are you working on this? (Yes/No)**
For GCI 2019

**Comment by Shivansh2407** [comment]
Is this issue open to work or has it been implemented @nitin10s? If opened I would like to work on this 👍
