### ISSUE TITLE
Make change in sign up,login ,reset 

### ISSUE THREAD

**Issue by dev9414** [CircuitVerse/CircuitVerse#596]
Describe the feature you'd like
 Certain verification is implemented there. We need to make those changes in the website accordingly.

Additional context
List of probable changes:

Require user passwords to have at least 8 characters and at least one special character, one number and text characters
Add Recaptcha for second log-in attempts
Add Recaptcha for password resets (forgot password)
Username less than or equal to 51 characters.
Add Recaptcha for SignUp
Recaptcha needs to be validated both on frontend and backend
Would you like to work on the issue?
No, this is for GCI STUDENTS

**Comment by aayush-05** [comment]
I guess you have already made an issue regarding the Recaptcha thing #573

**Comment by dev9414** [comment]
Agreed,but I have added some more enhancement in this

**Comment by ShreyaPrasad1209** [comment]
You can edit #573 and close this one

**Comment by dev9414** [comment]
I just closed #573
