### ISSUE TITLE
Option to make private to public should be available 

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#597]
**Is your feature request related to a problem? Please describe.**
Once a project has been made public it cannot be made private. This should be always available.

**Describe the solution you'd like**
Toggle to turn public to private should be available.

**Additional context**
![public](https://user-images.githubusercontent.com/42520146/68533320-10f3ce00-034d-11ea-98db-07a52ada103f.PNG)
![public1](https://user-images.githubusercontent.com/42520146/68533322-14875500-034d-11ea-94b7-e9b2fc9dec5a.PNG)

**Comment by ankitkataria** [comment]
This is available, explore the project edit page.

**Comment by sakshi1499** [comment]
Oh yes alright! :)

**Comment by sakshi1499** [comment]
I was suggesting it to be handy. For someone in view my circuits page, they'll have to go all the way to clicking more and then edit and then save the whole thing. If there is a toggle button or a drop down button that they can access directly by clicking private button, it'll be much easier.

**Comment by ankitkataria** [comment]
How do you propose the selection of `Limited Access` project visibility then?

**Comment by sakshi1499** [comment]
What I am actually suggesting is that if the same features are available to a person in edit why make the person go though all those steps if the button indicating public is available to them on that page only. It is like increasing the steps for a task that can be very handy. Limited Access Option should also be included like Public and Private, because they can anyway achieve that two steps later.

**Comment by ankitkataria** [comment]
In my opinion, have a toggle button for public and private would hide the presence of the limited access feature. Opening this for more input. :v:

**Comment by satu0king** [comment]
We can just have a drop down then. The user can know that its possible to change this and easily.
