### ISSUE TITLE
Should not save group with empty name.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#598]
**Describe the bug**
As of now, you can create a group with an empty name. The group name should not be empty.

**To Reproduce**
Steps to reproduce the behaviour:
1) Go to 'My Groups' 
2) Click on 'New Groups'
3) Click on 'Create Group'

**Expected behaviour**
There should be a check before creating a group whether the name field is empty or not.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chtome

**Are you working on this issue? (Yes/No)**
For GCI 2019

**Comment by aayush-05** [comment]
Hey !
Even the Assignment and the Project name can be saved empty; you can add them in the isse too.
![image](https://user-images.githubusercontent.com/47032027/68534365-c593ec80-0359-11ea-8cfe-b9971bba9d20.png)

![image](https://user-images.githubusercontent.com/47032027/68534375-e9efc900-0359-11ea-9281-5e99a0e171a6.png)
