### ISSUE TITLE
Broken Drop down in Simulator

### ISSUE THREAD

**Issue by aayush-05** [CircuitVerse/CircuitVerse#599]
**Describe the bug**
The drop down menus in the navbar on the simulator window appears when the cursor is hovered on a particular section. But it does not go back when the pointer is removed from the section heading.

**To Reproduce**
1. Go to 'https://circuitverse.org/simulator'
2. Hover on any section heading
3. Remove the pointer from the heading

**Expected behavior**
The drop down for the sections should go back to its original state after the pointer has been removed fromo the section heading.

**Screenshots**
![image](https://user-images.githubusercontent.com/47032027/68534470-e446b300-035a-11ea-9d48-15496c2c3ead.png)
_(The pointer/cursor had been removed from the Tools heading at this point.)_

**Comment by ac030540** [comment]
@aayush-05, I would like to fix this issue. So can I work on it?

**Comment by aayush-05** [comment]
Hey @ac030540 !
I am not a contributer to this project as of now.
You can ask @satu0king or @ankitkataria , if they can assign this issue to you.

**Comment by ac030540** [comment]
> Hey @ac030540 !
> I am not a contributer to this project as of now.
> You can ask @satu0king or @ankitkataria , if they can assign this issue to you.

Okay. Thanks.

**Comment by ac030540** [comment]
@satu0king , I would like to fix this issue. So can I work on it?

**Comment by ac030540** [comment]
> @satu0king , I would like to fix this issue. So can I work on it?

@ankitkataria ?

**Comment by ankitkataria** [comment]
Personally I prefer the way it is right now. It's pretty similar to the Google Docs menubar. @satu0king what do you think?

**Comment by aayush-05** [comment]
Then we can make it more uniform like the Google Docs menubar, like since the menu closes back only when the heading is clicked upon. It should open only on clicking of the heading, not when hovered.
