### ISSUE TITLE
Featured Circuits/ Editor Picks

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#6]
[Desmos](https://www.desmos.com/)
Refer to the way Desmos shows featured works for more details. 

Currently featured circuits is hardcoded temporarily. Will need a nice way for admins to selectively feature circuits. 

- [ ] Create Model FeaturedProjects - primary attribute - project_id
- [ ] Send email to the featured project's author 
- [ ] Monthly/ Weekly send email to everyone about past month's/week's featured works 
- [ ] Ensure FeaturedProjects cannot be made private or limited access
- [ ] Provide a way for people to submit their work to be featured

**Comment by garry329** [comment]
Is there any work left to be done on this @satu0king ?

**Comment by satu0king** [comment]
> Is there any work left to be done on this @satu0king ?

There has been no work done on this! The featured circuits you see on the home page are hardcoded.

**Comment by garry329** [comment]
Ok, cool then i will start working on this one.
