### ISSUE TITLE
Gmail login not working

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#600]
**Describe the bug**
Unable to login via Google when CircuitVerse runs on Gitpod

**To Reproduce**
1. Go to README.md
2. Click on Gitpod
3. Give permission to expose all end points
4. Go to Sign In
5. Log in with Google 

**Expected behavior**
Should log in successfully as it's an old account 

**Screenshots**
![2019-11-10 (7)](https://user-images.githubusercontent.com/43600306/68547796-c2f1cf80-040b-11ea-9d3c-b3e183c5d9c3.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

**Are you working on this issue? (Yes/No)**
For GCI students under difficult

**Comment by satu0king** [comment]
It is not expected to work as Oauth is generally used in production only. We can make it work but this would cause us to leak private keys into docker configuration.
