### ISSUE TITLE
The cross button in simulator closes the properties panel but there is no way to reverse it.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#601]
**Describe the bug**
The cross button in simulator closes the properties panel but there is no way to reverse it except reloading the page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'https://circuitverse.org/simulator/edit/36189'
2. Click on 'x' in the upper rightmost corner
3. See error

**Expected behavior**

There should be tooltips that tell what the buttons will do and also, either there should be an undo button or some option that enables to get back the editing options being right there on the webpage rather than reloading or going back again.

**Screenshots**

Before clicking on the cross button:

![before](https://user-images.githubusercontent.com/42115530/68547807-f2084100-040b-11ea-9197-d41e8e43bc82.PNG)

After clicking on the cross button:

![after](https://user-images.githubusercontent.com/42115530/68547872-e0736900-040c-11ea-99f9-2bfd8186c4af.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 78.0.3904.97 (Official Build) (64-bit)

**Additional context**

It is very confusing to know what the buttons do without proper text and the cross button is not apt for symbolizing that the editing options will be gone, it symbolizes more like deleting the circuit, so if possible remove the x symbol and add some other symbol.

**Are you working on this issue? (Yes/No)**
No, For GCI 2019.

**Comment by aayush-05** [comment]
Hey!
You can actually get the properties panel easily by clicking anywhere in the simulator workspace.

**Comment by PragatiVerma18** [comment]
Yeah, but that's not clear at first sight. So, maybe a tooltip for the cross button can help. It is very confusing to know what the buttons do without proper text.

**Comment by aayush-05** [comment]
Yes, a tooltip or a description in the documents would be fine.

**Comment by Shivansh2407** [comment]
Where can I find the Code for the Button panel present on the simulator page?

**Comment by Ananthavijay** [comment]
@tachyons I think this can be closed
