### ISSUE TITLE
There should be a Generate Truth Table From Circuit feature.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#604]
**Is your feature request related to a problem? Please describe.**

There should be a Generate Truth Table From Circuit feature. This would help in better understanding of the circuit. 

**Are you working on this? (Yes/No)**
No.

**Comment by nrs1729** [comment]
Would this be added as in the tools menu?

**Comment by PragatiVerma18** [comment]
Yeah, that would be good!

**Comment by gkan30** [comment]
Greetings!
I would like to work on this.
Can you assign this issue to me?
