### ISSUE TITLE
Add bottom to top button in all the pages.

### ISSUE THREAD

**Issue by plxity** [CircuitVerse/CircuitVerse#606]
**Is your feature request related to a problem? Please describe.**
A bottom to top button should be present in all pages to scroll to the top.

**Describe the solution you'd like**
Implement a simple button at the right bottom side of the page. As a user scrolls more a 50px it should be visible on the screen.

**Are you working on this? (Yes/No)**
For GCI 2019

**Comment by nitin10s** [comment]
The back to top button is preferred only when the pages are longer than 4-5 screens.
If you observe, our platform doesn't have more than 2-3 screens on a page.

The button would be an overkill and is not necessary in my opinion.

**Comment by aayush-05** [comment]
This button would be useful on the user's own circuits page. The length of that page isn't specified and solely depends upon the number of circuits the user has.
