### ISSUE TITLE
Fork individual subcircuits from other peoples projects into your own projects

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#62]
A handy feature would be the ability to fork individual subcurcuits into your own projects, and use them in your projects. This would mean you could take a bunch of individual parts from other projects to use in another project.

**Comment by HypheX** [comment]
Actually, this is already possible!
You can straight up copy-paste subcircuits from other people's projects.

**Comment by satu0king** [comment]
As @HypheX said, it is already possible with copy/paste. Providing additional functionality to make it work differently will overcomplicate matters.
