### ISSUE TITLE
Update bundler version to 2.0 

### ISSUE THREAD

**Issue by ankitkataria** [CircuitVerse/CircuitVerse#620]
**Is your feature request related to a problem? Please describe.**
Currently, bundler version 1.17 is being used. Updating it to 2.0 is required. 

**Describe the solution you'd like**
Refer [this](https://bundler.io/guides/bundler_2_upgrade.html) guide for steps to update to bundler v2.

**Are you working on this? (Yes/No)**
No

**Comment by tachyons** [comment]
Fixed in #621
