### ISSUE TITLE
Add windows CI using appveyor

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#625]
We are using circle CI to run specs, circle CI do no have support for windows builds, having a windows CI will ensure windows compatibility of the application, 

Reference: https://www.appveyor.com/docs/lang/ruby/

**Comment by fluctix** [comment]
I want to work on this

**Comment by tachyons** [comment]
Github actions is very slow since they don't have cache support yet

**Comment by fluctix** [comment]
Okay , I would start work on appveyor integration soon.

**Comment by fluctix** [comment]
@tachyons I cannot currently work on this issue

**Comment by fluctix** [comment]
@tachyons I made a pr later , can you review it

**Comment by fluctix** [comment]
This can now be closed through #637

**Comment by tachyons** [comment]
Fixed in #637
