### ISSUE TITLE
Links Redirection to Contribute Page

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#628]
**Is your feature request related to a problem? Please describe.**
Cards on Contribute Page are static and as a first time user, a developer directly goes to the contribute page. It should be made dynamic and should redirect to the links of specified options. 

**Describe the solution you'd like**
The page should have linking(anchor tags).

**Comment by JoshHeng** [comment]
Hi, I've claimed this task on Google Code In

So just to confirm, the [contribute](https://circuitverse.org/contribute) page should contain hyperlinks within the lists on each card?

By the looks of it most links will be either Github, Patreon, PayPal or the home page, and some items (e.g. `Introduce the platform to your buddie`) won't have any links at all. Is this right?

Thanks

**Comment by JoshHeng** [comment]
Hi,
I've just added various linked icons to the list items. Is this what you need?

<img width="876" alt="contribute-page-screenshot" src="https://user-images.githubusercontent.com/34946235/69999588-e7dfeb00-1550-11ea-9cd3-5e58a6c484b2.png">

**Comment by JoshHeng** [comment]
See PR https://github.com/CircuitVerse/CircuitVerse/pull/667

**Comment by sakshi1499** [comment]
@JoshHeng This is what we wanted in the link redirection. I think the fist sub topic of fan can redirect to the simulator. Do we want icons in every sub topic or should we go without them and just with the hyperlinks? @satu0king @ankitkataria

**Comment by JoshHeng** [comment]
Also @sakshi1499 Patreon seems to have changed their branding so we might have to change the logo on the bottom left

**Comment by sakshi1499** [comment]
Right! I just noticed. Well I think that should be in a separate issue. I'll raise another issue about it and post it as a task. You can claim it if you want. 👍

**Comment by JoshHeng** [comment]
I've updated the simulator links. Should I change anything else?
<img width="922" alt="firefox_8MMR5EuIlr" src="https://user-images.githubusercontent.com/34946235/70172302-52676700-16c8-11ea-93ea-836d9d91268d.png">

**Comment by JoshHeng** [comment]
If everything is fine please merge pull request https://github.com/CircuitVerse/CircuitVerse/pull/667

**Comment by Parikshit-Hooda** [comment]
Perhaps make the icons a bit smaller, look cluttery to me. @sakshi1499 Opinions? Also, do note that the link redirects should lead to new tabs.

**Comment by JoshHeng** [comment]
@Parikshit-Hooda Links already redirect to new tabs and icons are already slightly smaller, but I can make them smaller again if needed

**Comment by sakshi1499** [comment]
@Parikshit-Hooda I had already pointed it out earlier, I wasn't really envisioning icons earlier. It'll be great if they are a smaller than this. Right now it kind of looks too crowded.
