### ISSUE TITLE
Remove right margin when then page in mobile view

### ISSUE THREAD

**Issue by sgpritam** [CircuitVerse/CircuitVerse#629]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
![Capture3](https://user-images.githubusercontent.com/41269164/69025447-07253700-09ed-11ea-8fc2-edc91db65ff3.PNG)

**Are you working on this issue? (Yes/No)**

**Comment by sgpritam** [comment]
> Add any other context about the problem here.

Remove extra margin when then page in mobile view

**Comment by aayush-05** [comment]
**Duplicate Issue**
Similar issue opened at #540
