### ISSUE TITLE
logo not properly seen or not readable

### ISSUE THREAD

**Issue by sgpritam** [CircuitVerse/CircuitVerse#630]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
when page in approximate pixel between 1150 to 1010
![1](https://user-images.githubusercontent.com/41269164/69025777-5ddf4080-09ee-11ea-9008-919f0cecd843.PNG)

**Are you working on this issue? (Yes/No)**

**Comment by aayush-05** [comment]
**Duplicate Issue**
Issue already opened at #533
