### ISSUE TITLE
Searchbar design

### ISSUE THREAD

**Issue by sgpritam** [CircuitVerse/CircuitVerse#634]
Requested Feature:-
When page view(i.e. desktop to mobile) changes then `search` changes as `search logo` and size of search box is decreases

**Comment by JoshHeng** [comment]
Please be more specific and maybe add screenshots/mockups to demonstrate what you mean

**Comment by sgpritam** [comment]
@JoshHeng When I bring the page from desktop mode to mobile mode, the search bar is switched to be converted into search bar logo.

**Comment by JoshHeng** [comment]
I still don't understand, please could you answer each point:

* What is the problem?
* What are possible solutions?
* Do you want to work on this?

Can you also attach screenshots of what you mean - both on the desktop and mobile mode.

If English isn't your first language, maybe use a service like Google Translate or (maybe) respond in your native language and hopefully someone else will be able to understand.

Thanks!

**Comment by sgpritam** [comment]
@JoshHeng 
Problem:-
I want that as the size of the web page is small then the search bar will be converted to Search Bar Logo.
Image
https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcQIKedXMaQ5oIy3Xznycv14ieFh_EfsJGqGwIkYoTI2xMBL7fKl
