### ISSUE TITLE
Add user account logo

### ISSUE THREAD

**Issue by sgpritam** [CircuitVerse/CircuitVerse#635]
Requested feature:-
When page view(i.e. desktop to mobile) changes then `sign in` changes as `user logo`

**Comment by JoshHeng** [comment]
Please be more specific and maybe add screenshots/mockups to demonstrate what you mean

**Comment by sgpritam** [comment]
@JoshHeng When I bring the page from desktop mode to mobile mode, the sign in is switched to be converted into sign in logo.

**Comment by JoshHeng** [comment]
I still don't understand, please could you answer each point:

* What is the problem?
* What are possible solutions?
* Do you want to work on this?

Can you also attach screenshots of what you mean - both on the desktop and mobile mode.

If English isn't your first language, maybe use a service like Google Translate or (maybe) respond in your native language and hopefully someone else will be able to understand.

Thanks!

**Comment by JoshHeng** [comment]
I still don't understand, please could you answer each point:

* What is the problem?
* What are possible solutions?
* Do you want to work on this?

Can you also attach screenshots of what you mean - both on the desktop and mobile mode.

If English isn't your first language, maybe use a service like Google Translate or (maybe) respond in your native language and hopefully someone else will be able to understand.

Thanks!
