### ISSUE TITLE
Back button should bring back to the same page.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#641]
**Describe the bug**

The back button at <a href="https://circuitverse.org/users/13353/projects/39261">Projects</a> page redirects to the <a href="https://circuitverse.org/users/13353">Users</a> page whereas it should bring back the user to the same page where they came from.

**To Reproduce**
1. Go to 'https://circuitverse.org/users/13353/projects/39261'
2. Click on 'Back'
3. See error

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 78.0.3904.108

**Additional context**

The link for the author's name already takes the user to the author's profile page, so need for the back button to take there. If possible, an option of view more can be added, saying something like, view more from this author.

**Are you working on this issue? (Yes/No)**
No. For GCI 2019.

**Comment by tachyons** [comment]
This seems an expected behavior, cc @satu0king

**Comment by Shivansh2407** [comment]
Is it fixed?
