### ISSUE TITLE
If there are no favourites, show a message rather than showing a blank page.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#643]
**Describe the bug**

If there are no favourites added by a user, show a message rather than showing a blank page or either open the favourites page and there show a message saying there are no favourites selected by the user yet and give an option to view more projects by that author.

**To Reproduce**
1. Go to 'https://circuitverse.org/users/13353'
2. Click on 'View Favourites'
3. See error

**Expected behaviour**

An empty page doesn't look good. In the first place, it gives an impression of what is wrong with the page. So, better write that there re no favourites yet.

**Screenshots**

![1](https://user-images.githubusercontent.com/42115530/69483266-21c33a00-0e4b-11ea-80f3-7690e0d1e124.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 78.0.3904.108

**Are you working on this issue? (Yes/No)**
No. For GCI 2019.

**Comment by sal2701** [comment]
@PragatiVerma18  There is an empty screen in projects section as well. We can add a message for Favourites as well as Projects. Also the message should be different for the account owner and a viewer. The owner should preferably receive a motivational message :smile: and a link to the simulator. What do you think?

**Comment by PragatiVerma18** [comment]
Nice idea @sal2701!!! 😀 That would be great considering user experience. Even when there are favorites there should be a link to view more projects from the same author or a link to simulator to create some of their own. Just the proper linking of pages can work wonders for user experience here.
