### ISSUE TITLE
Add a rotate clockwise or counterclockwise option for circuit elements.

### ISSUE THREAD

**Issue by PragatiVerma18** [CircuitVerse/CircuitVerse#644]
**Is your feature request related to a problem? Please describe.**
Adding rotate clockwise or counterclockwise options for circuit elements can be a great utility with respect to the user experience and interactiveness as that would help them align the circuit elements in a better and easier way.

**Are you working on this? (Yes/No)**
No.

**Comment by aayush-05** [comment]
There's actually a Direction column in the controller for the simulator that basically does the same.
![image](https://user-images.githubusercontent.com/47032027/69560017-0aae5480-0fd1-11ea-81bd-a811a1c3fb2a.png)

**Comment by sal2701** [comment]
@aayush-05 True! Also, one can use the arrow keys to orient the elements with the arrow direction corresponding to the output node.

**Comment by aayush-05** [comment]
Invalid issue @tachyons

**Comment by Shivansh2407** [comment]
> Invalid issue @tachyons

Also as mentioned by @sal2701 about the arrow keys to rotate the elements , We have an option in CV where after dragging the element we can rotate it using W-A-S-D keys.
So I think this issue is already implemented. Let me know your views @aayush-05 and @tachyons .
