### ISSUE TITLE
Change mouse to pointer on hover

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#650]
Mouse should change to pointer form when hovered on post comment/cancel button.

![image](https://user-images.githubusercontent.com/43600306/68069357-503a8180-fd85-11e9-8292-49025bd88747.png)

**Comment by Shivansh2407** [comment]
Can I please work on this ? Please let me know how to proceed with this?

**Comment by falguniraina** [comment]
can i work on this?please till me about the link in which i can find the source code??

**Comment by ShreyaPrasad1209** [comment]
You can use hover property in css. For finding the source code, use inspect element.

**Comment by falguniraina** [comment]
@ShreyaPrasad1209 ma'am i am unable to find post comment/cancel button !!Help me to find this so that i can start with this issue

**Comment by Ananthavijay** [comment]
@falguniraina Right now, there is an issue with comment section. Refer to this [issue](https://github.com/CircuitVerse/CircuitVerse/issues/767)
