### ISSUE TITLE
Change font size and family in comments section

### ISSUE THREAD

**Issue by ShreyaPrasad1209** [CircuitVerse/CircuitVerse#651]
**Problem**
 No CSS on fonts in comment section. Font size also small.

**Changes proposed**
Try this out. 
```
font-family: 'Ubuntu', sans-serif;
  font-size: 1.1rem;
```
**Alternative changes**
Maybe use Poppins or some other font style.

**Screenshot**
![image](https://user-images.githubusercontent.com/43600306/68069415-e66ea780-fd85-11e9-9770-275f33394608.png)

**Comment by CodeSarthak** [comment]
Where are the HTML and CSS files for the same? @ShreyaPrasad1209 @satu0king

**Comment by ShreyaPrasad1209** [comment]
@CodeSarthak use inspection, name of the file will be shown.

**Comment by KaranKS** [comment]
is it still assigned to anyone? I want to fix this.

**Comment by falguniraina** [comment]
can i please work on this??
