### ISSUE TITLE
Set appropriate titles to all pages

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#653]
**Describe the bug**
All pages except for pages in the main navigation bar have the same title and we need to add appropriate titles to each page. Also there are some discrepancies in the titles like "CircuitVerse - Digital Circuit Simulator online" and "CircuitVerse - Digital Circuit Simulator". These need to be rectified.

**To Reproduce**
1. Go to different pages such as groups, assignments, etc all have the same title.

**Are you working on this issue? (Yes/No)**
Nope. For GCI 2019

**Comment by Shivansh2407** [comment]
Please list out all the pages so that I can change and fix them.

**Comment by sal2701** [comment]
Hey! You need to go through all the pages and see the titles and see if they match. I haven't made a list.

**Comment by Shivansh2407** [comment]
Ok Cool . Will fix this soon.

**Comment by Ananthavijay** [comment]
I am working on this.
