### ISSUE TITLE
Change Project Name by clicking name on top of page.

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#655]
**Is your feature request related to a problem? Please describe.**
If I want to change name of project while creating a circuit I have to go to the box at the bottom left, which is visible only in the default setup of page which we can access by deselecting any element, etc.

**Describe the solution you'd like**
I suggest that double clicking the title at the top of the page should make it possible to change the name of the Project. This feature can also be added to the names of circuits.

**Describe alternatives you've considered**
Alternative can be to just add a button beside the title which will enable "Edit Mode" and we'll be able to edit all names like Project, Circuit, etc.

**Are you working on this? (Yes/No)**
Nope. For GCI 2019

**Comment by Shivansh2407** [comment]
Can I work on this issue @sal2701 ?

**Comment by sal2701** [comment]
Yes sure!

**Comment by Shivansh2407** [comment]
@sal2701 I have fixed one part of the issue . Please review it and let me know what do you think on this ?
