### ISSUE TITLE
Dark mode is pretty messed up.

### ISSUE THREAD

**Issue by nitin10s** [CircuitVerse/CircuitVerse#657]
**Describe the bug**
Both the dark modes on https://docs.circuitverse.org/#/ and https://learn.circuitverse.org/ don't work properly at all.

**To Reproduce**
In the documentation, turn on dark mode and click on another link. We see the toggle comes back at its off position and works in a completely opposite way

In the learning platform, turn on dark mode and click on another link. We see the dark mode gets turned off.

**Expected behavior**
In the documentation, the toggle should stay in its previous position on changing links
In the learning platform, the dark mode should not get off on changing links

**Are you working on this issue? (Yes/No)**
No, probably for GCI students

**Comment by nrs1729** [comment]
For Interactive Book I used session storage to remember whether dark mode is enabled, is that alright?

**Comment by aayush-05** [comment]
Issue fixed in https://github.com/CircuitVerse/Interactive-Book/pull/124 
The problems with Circuitverse Docs would be more helpful to be added as an issue in that repo.
