### ISSUE TITLE
Add "Login with GitHub" feature

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#658]
**Is your feature request related to a problem? Please describe.**
Nowadays, logging into websites with your GitHub account has become common and convenient. So adding this feature will help in improving Login procedure and User Experience.

**Describe the solution you'd like**
Add **Login with GitHub** option.

**Additional context**
[Connect your app to GitHub](https://auth0.com/docs/connections/social/github)

**Are you working on this? (Yes/No)**
Nope. For GCI 2019

**Comment by Ananthavijay** [comment]
@sal2701 Could u make this a GCI task?
