### ISSUE TITLE
Popup if Don't Cares present in Combinational Analysis Table

### ISSUE THREAD

**Issue by sal2701** [CircuitVerse/CircuitVerse#659]
**Is your feature request related to a problem? Please describe.**
While using the Combinational Analysis feature, we've to fill up a table of inputs which can be a lot sometimes. And if we forget to change even a single "x" we don't get a circuit. So the whole work of filling in the table goes to waste due to s small mistake.

**Describe the solution you'd like**
A popup which would show that "x" still exist. Should work till there are no "x" left in the table.

**Are you working on this? (Yes/No)**
Nope. For GCI 2019

**Comment by Shivansh2407** [comment]
Would like to take up this task . Can you please tell me which file to look for ?

**Comment by Shivansh2407** [comment]
@sal2701 sir please could guide me on this issue ?

**Comment by sal2701** [comment]
Hey @Shivansh2407 sorry for the late reply but I am working on this issue. While using combinational analysis we might sometimes forget to enter a value. And the tool doesn't output a circuit if even a signal input is "x". We need to show a popup to indicate this to the user.

**Comment by Shivansh2407** [comment]
Actually I also started working on this issue . I understand the issue completely .

**Comment by satu0king** [comment]
This is issue is actually incorrect, 

Try this 
![image](https://user-images.githubusercontent.com/2092958/77294613-9b403b80-6d0a-11ea-855c-96933ae1b4f0.png)

**Comment by satu0king** [comment]
We still need to resolve this degenerate case as well, as the user cannot be expected to know this.

**Comment by sal2701** [comment]
@satu0king Yeah, but I feel we need to have a standard, like it won't work if there are any "X" left. If we follow it, output for the table 1 above can be obtained using a 1 input "C" and single output rather than 3 inputs. What do you feel?
