### ISSUE TITLE
Move privacy page to separate controller

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#662]
Move privacy page from logix controller to own controller

**Comment by Shivansh2407** [comment]
Can you please explain the term own controller . I would like to fix this issue please

**Comment by tachyons** [comment]
@Shivansh2407 Can you go through this tutorial, https://www.youtube.com/watch?v=wbZ6yrVxScM This will give an idea about MVC architecture in Rails, also feel free to ask any doubts in our slack channel
