### ISSUE TITLE
Move authorisation methods from User model

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#663]
Move check edit_access, check_view_access, and check_direct view access to pundit authorization layer

**Comment by junron** [comment]
I want to take this task, but I'm not quite sure what I should do. Should I be moving the `check_edit_access` methods in the `project.rb` model to the project policy?

**Comment by fluctix** [comment]
I want to work on this issue

**Comment by junron** [comment]
@tachyons Is there a task for this issue? I can't seem to find it in the GCI dashboard

**Comment by fluctix** [comment]
I don't think it has yet been published

**Comment by tachyons** [comment]
It is published now

**Comment by NumberC** [comment]
I just claimed this task on GCI. Has someone been trying this or has done it already?

**Comment by nrs1729** [comment]
Is someone still working on it? The task is unclaimed.
