### ISSUE TITLE
Preview mail in development environment

### ISSUE THREAD

**Issue by tachyons** [CircuitVerse/CircuitVerse#664]
Setting up SMTP in development environment is a difficult to task and not necessary, letter opener gem makes testing mails in dev environment easy 
https://github.com/ryanb/letter_opener

**Comment by fluctix** [comment]
Can I work on this ?(or wait for.it to.be published in the gci dashboard)

**Comment by junron** [comment]
I find that [MainCatcher](https://mailcatcher.me/) is better for this, especially in remote environments like docker where there is no browser.

**Comment by tachyons** [comment]
https://codein.withgoogle.com/dashboard/tasks/5538448790781952/

**Comment by codingfreak98** [comment]
Has this issue been solved?
I would like to work on it if anyone else isn't working on it at the moment

**Comment by junron** [comment]
Go ahead! 👍

**Comment by Ananthavijay** [comment]
@codingfreak98 This is a beginner's task in GCI. If you are a GCI student and have not completed 2 beginner's task then go ahead!

**Comment by Shivansh2407** [comment]
I would like to work on this @tachyons  Sir. Please let me know what needs to be done here.

**Comment by tachyons** [comment]
Just integrate letter opener or mail catcher as suggested in above comments

**Comment by Shivansh2407** [comment]
Ok @tachyons Working on it 👍

**Comment by Shivansh2407** [comment]
@tachyons I have integrated mailcatcher as suggested successfully 👍  . Can I go ahead and open up a PR for this ?
![Capture](https://user-images.githubusercontent.com/42182955/74404800-86da6a80-4e51-11ea-8b36-0e4ebc81473b.PNG)

**Comment by tachyons** [comment]
Yes

**Comment by Shivansh2407** [comment]
Ok @tachyons Sir 👍
