### ISSUE TITLE
Patreon has changed its logo

### ISSUE THREAD

**Issue by sakshi1499** [CircuitVerse/CircuitVerse#669]
**Describe the bug**
Patreon has changed its branding logo and the Contribute page has Patreon's previous logo. 

**To Reproduce**
1. Go to https://circuitverse.org/
2. Click on Contribute
3. Scroll down to the bottom
4. Patreon logo is outdated.

**Expected behavior**
The old logo should be replaced by the new one.

**Screenshots**
![old](https://user-images.githubusercontent.com/42520146/70003795-44abc780-158a-11ea-82ee-fa1151e4b77b.PNG)
![New](https://user-images.githubusercontent.com/42520146/70003801-4c6b6c00-158a-11ea-8d75-0e086b0c1a5c.PNG)

**Are you working on this issue? (Yes/No)**
No it is for the GCI'19 participants.

**Comment by JoshHeng** [comment]
Hi I'll work on this too (but I can't currently claim it on GCI because the other task is still open, I'll claim it later)

**Comment by sakshi1499** [comment]
Okay no issue :) @JoshHeng

**Comment by JoshHeng** [comment]
Also fixed in https://github.com/CircuitVerse/CircuitVerse/pull/667

**Comment by JoshHeng** [comment]
Issue fixed in branch stories/new_ux. Can close
