### ISSUE TITLE
"Counter" component

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#67]
See this project for an example: https://circuitverse.org/users/1577/projects/4036

Essentially, the counter would take in a clock signal, and output a signal which is incremented by 1 every time it receives a clock pulse.

**Comment by HypheX** [comment]
Actually, there is already a neat way to do this, which is what I implemented on my WIP computer.
![image](https://user-images.githubusercontent.com/29693543/49387574-648e7e00-f6df-11e8-85c3-a021757b0434.png)

However, I don't see why there shouldn't a counter component.

**Comment by sarthak77** [comment]
Hey, I would like to take up this issue

**Comment by shubhscoder** [comment]
@sarthak77 I think this is actually a big issue. Would you mind if we both can work on this?

**Comment by shubhscoder** [comment]
I will try to subdivide this issue into multiple smaller sub issues , we can take work on them!

**Comment by sarthak77** [comment]
ok thats fine
Please let me know my part

**Comment by armudgal** [comment]
@sarthak77 and @shubhcoder, there is already a PR opened to fix the issue and is under the process of being reviewed. Please look through other issues on which you can work.
