### ISSUE TITLE
[GCI] Find and Fix Typos

### ISSUE THREAD

**Issue by RYBPLAYER** [CircuitVerse/CircuitVerse#673]
Task for GCI 2019
Student: Ryan Y. B.
Mentor: Sakshi Munjal

I found a few issues with the documentation on the Getting Started page on CircuitVerse.org, and I sorted them out based on what page of the documentation they are from. I tried to focus on the end parts of the documentation because I felt it explained a lot of the key features that are unique to CircuitVerse. I purposely skipped the circuit elements and basic tutorials sections as I felt they were sufficiently clear. 

**ANNOTATION ELEMENTS PAGE:**

**Documentation:** "Also, you can add details in your circuit, to help further convey the logic, highlight specific points, or explain the flow of circuit, using the Text feature."
**Fix:** _Using the text feature,_ you can also add details in your circuit to _help convey_ the logic behind it, highlight specific points, or explain the flow of circuit.

**Documentation:** "Also, you can change it's direction either by using the arrow keys on your keyboard or using the properties menu."
**Fix:** You can also change _its_ direction either by using the arrow keys on your keyboard or using the properties menu.

**Documentation:** "If you ever feel the need to highlight or mark a specific portion of your circuit, you can use Rectangle, by navigating through Misc -> Rectangle and just drag & drop it to the required place."
**Fix:** If you ever feel the need to highlight or mark a specific portion of your circuit, you can use the _the_ Rectangle by navigating through Misc -> Rectangle. Just drag and drop it to the required place.

**GROUPS PAGE:**

**Documentation:** "One of the Versatile Feature of CircuitVerse assists Teachers in Managing Class Assignments."
**Fix:** One of the versatile _features_ of CircuitVerse _is that_ assists Teachers in _managing_ Class Assignments.

**Documentation:** "View the Given Assignment with live deadline counter."
**Fix:** View the _given assignment(s)_ alongside _a_ live deadline counter.

**Documentation:** "Then, Click on New Group Button to create a New Group."
**Fix:** Then, click on _the_ New Group _button_ to create a _new group._

**Documentation:** "Fill Up all the necessary Details like: Assignment name, Set the Deadline (both Time and Date)"
**Fix:** Fill up all the necessary details _such as_ _the assignment_ name, _the assignment Deadline (Both time and date)_

**TEST BENCH PAGE:**

**Documentation:** "Test Bench are used to simulate your designs. These are generally used for automated testing of your circuits."
**Fix:** _The test bench is_ used to simulate your designs. _It is generally used to automate the testing of you circuits._

**Documentation:** "In order to do so change that simply click on the box where inp1 is written and you will now be able to change the label for your input. Also, note the color of your input box is purple while that of output will be light green."
**Fix:** In order to do so_,_ simply click on the box where inp1 is written and you will now be able to change the label for your input. _Also note that input boxes are purple while output boxes are light green._

**Documentation:** "Whenever you run your test bench the TB_out always displays output in 2 columns as seen in the figure below."
**Fix:** Whenever you run your test bench_,_ the TB_out will display the output _in two columns_ as seen in the figure below.

**Documentation:** "When the actual output is written in red, it means the output produced by the circuit is not equal to the expected value. Thus there might be some errors in your design. But Sometimes, as in this example, though the input values 1,1 in AND gate produces an output of 1, it is shown wrong."
**Fix:** _When the actual output is written in red, the output produced by the circuit is not equal to the expected value. This means that there may be some errors with your design. However, sometimes, as seen in this example, though the input values are 1,1 and the AND gate produces an output of 1, it is displayed wrong._

**Comment by sakshi1499** [comment]
You have to make a PR and not an issue. I have explained step by step on the GCI dashboard. Go through it okay? @RYBPLAYER

**Comment by sakshi1499** [comment]
@RYBPLAYER Please close/delete this issue. It had to be in a Pull Request only

**Comment by AyanChoudhary** [comment]
Can I take this up, if this is not complete?
