### ISSUE TITLE
Deleting a project, then going to another project's page displays a delete message.

### ISSUE THREAD

**Issue by HypheX** [CircuitVerse/CircuitVerse#68]
So, I deleted a project I created on accident, then went to my calculator's project page, only to be greeted by this message:
![image](https://user-images.githubusercontent.com/29693543/49389122-cac8d000-f6e2-11e8-962f-d7ca0fe0016a.png)

I thought I had accidentally deleted my BCD calculator.

**Comment by satu0king** [comment]
This is an annoying UI bug. I will fix it.

**Comment by satu0king** [comment]
can you see if the issue is resolved
