### ISSUE TITLE
"CircuitVerse" forums

### ISSUE THREAD

**Issue by jbox144** [CircuitVerse/CircuitVerse#69]
I'm kind of surprised CircuitVerse lacks a dedicated forum of some kind. Hopefully something like that could be implemented for people to use. It would definitely be necessary if CircuitVerse aims to grow its community further.

**Comment by blane1257** [comment]
These are both great ideas! (more so the forum, as it is highly needed)

**Comment by satu0king** [comment]
https://discourse.circuitverse.org/
Check this out, sign up and test if everything works fine,

**Comment by blane1257** [comment]
I wouldn't mind being a moderator.

**Comment by satu0king** [comment]
It is going to be a while before we launch this as I am having an issue with setting up email for the forum. Also currently we are using Yandex email as our email provider (for free). It currently works well but we need to upgrade to a better (paid) email provider. However, the project currently does not have the financial support to do so.

**Comment by satu0king** [comment]
We should launch the forum soon, any thoughts on how to go about this?

**Comment by woswos** [comment]
I have a lifetime enterprise web hosting deal which I bought years ago. I paid once and I don't pay anything else. It has 4gb ram and almost unlimited bandwidth. I am using it for my personal websites only. 

Let me try to install a copy of circuit verse on it. If it works, I wouldn't mind sharing my hosting to host CircuitVerse. So far I never had problems with my hosting in terms of down times, etc.

Please let me know if you are interested in.

<img width="402" alt="Screen Shot 2019-04-06 at 12 35 46 PM" src="https://user-images.githubusercontent.com/10498874/55667063-8ef86f80-5868-11e9-8a3b-f16066fce3dd.png">
<img width="402" alt="Screen Shot 2019-04-06 at 12 35 57 PM" src="https://user-images.githubusercontent.com/10498874/55667064-94ee5080-5868-11e9-91d5-ad748104a53c.png">
