### ISSUE TITLE
Add a 'Create Project' button to the projects page

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/CircuitVerse#710]
**Is your feature request related to a problem? Please describe.**
There should be a clearly labelled button to create a project on the projects page itself

**Describe the solution you'd like**
Show a 'Create Project' in the project navigation bar, like so:
<img width="824" alt="firefox_DIw4vii5iP" src="https://user-images.githubusercontent.com/34946235/70377880-9c8f5900-1911-11ea-86a7-c5e29b8185bb.png">

**Describe alternatives you've considered**
The user could just click on 'Simulator' but it is easier and makes more sense if there is a 'Create Project' button as well

**Are you working on this? (Yes/No)**
No

**Comment by yash15601** [comment]
can i work on this

**Comment by yash15601** [comment]
can u plzz tell on clicking create project in which page we should redirect?

**Comment by falguniraina** [comment]
can i work on this??

**Comment by yash15601** [comment]
@falguniraina  I already  made a pr u can check🙂

**Comment by satu0king** [comment]
This has been closed due to comments here - https://github.com/CircuitVerse/CircuitVerse/pull/887
