### ISSUE TITLE
Show 'no projects' or 'no public projects' if a user has no projects

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/CircuitVerse#711]
**Is your feature request related to a problem? Please describe.**
If a user doesn't have any projects their projects page looks empty and like something isn't loading
<img width="848" alt="firefox_TMKc1CsUwo" src="https://user-images.githubusercontent.com/34946235/70377919-14f61a00-1912-11ea-8365-6d72998f5ba1.png">

**Describe the solution you'd like**
If the user has no public projects, the website should say something along the lines of 'This user has no public projects'.

**Are you working on this? (Yes/No)**
No

**Comment by MrBartusek** [comment]
I think that might be closed cause [this page will be redone](https://xd.adobe.com/spec/7453ce8f-6d79-4969-4a1a-d0162c42c53d-0262/screen/8eb46bd1-d2bb-4f71-b5f0-d18b8e887157/Profile-Self-1) in new UI same as #710

**Comment by Ananthavijay** [comment]
@tachyons This can be closed since this has been fixed already
