### ISSUE TITLE
Make the project information editing page look nicer

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/CircuitVerse#712]
The project information editing page doesn't look very well styled and like it was rushed
<img width="904" alt="firefox_2dp4nIVvgc" src="https://user-images.githubusercontent.com/34946235/70377929-4373f500-1912-11ea-8ac8-7a197a07926a.png">

**Describe the solution you'd like**
- The 'Update Project' button should have a bootstrap class,
- There should be less of a space between the 'Description' label and WYSIWYG editor
- The scrollbars on the WYSIWYG editor should only be shown if needed
- There should be more padding in the top two input fields
- The blue colour in the WYSIWYG editor should be changed to something that follows the overall colours of the website. It looks a bit out of place

**Are you working on this? (Yes/No)**
No

**Comment by kshitijandmojo** [comment]
Hi!
I would like to solve this issue, but an not able to understand which files are involved, coukd you please help me with them?

**Comment by sakshi1499** [comment]
Bootstrap issue is already being dealt with in issue #509

**Comment by MrBartusek** [comment]
@sakshi1499 that issue is more about buttons
@kshitijandmojo you need to add form classes from bootstrap in `app\views\projects\_form.html.erb`
basically same rules as #778

**Comment by sakshi1499** [comment]
@MrBartusek Yes I very well know that. Its not worth mentioning in twice, when it has already been dealt with in another PR. This is what creates duplicates.

**Comment by MrBartusek** [comment]
@sakshi1499 #778 is only about assignment but here is needed to do something like this but on a different page, not a duplicate

**Comment by sakshi1499** [comment]
@MrBartusek I was talking about #509, please see my above comment again. Thanks

**Comment by MrBartusek** [comment]
@sakshi1499 oh yeah sorry, in that case #509 should be closed case it don't describe whole problem

**Comment by MrBartusek** [comment]
There was no update from @kshitijandmojo for more than 2 weeks so I will for on that
