### ISSUE TITLE
Change the URLs for the profile details and a user projects

### ISSUE THREAD

**Issue by JoshHeng** [CircuitVerse/CircuitVerse#713]
It would make more sense if the profile information of a user was found at https://circuitverse.org/users/00000/ and the projects found at https://circuitverse.org/users/00000/projects

Currently the projects are found at https://circuitverse.org/users/00000/ and profile at https://circuitverse.org/users/00000/profile

**Are you working on this? (Yes/No)**
No

**Comment by MrBartusek** [comment]
I will work on that

**Comment by Shivansh2407** [comment]
Can i take up this task?

**Comment by Shivansh2407** [comment]
Please Can you help me with how to proceed @JoshHeng ?

**Comment by MrBartusek** [comment]
@Shivansh2407 if you want to ask how to do this issue a better place would be [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE), btw: you don't need to ask if you can take issue, just say that you are working on it

**Comment by JoshHeng** [comment]
> 
> 
> Please Can you help me with how to proceed @JoshHeng ?

What problems are you having? If you're new to CircuitVerse, read the README to get started!
