### ISSUE TITLE
Getting Started Videos Corrupted

### ISSUE THREAD

**Issue by kshitijandmojo** [CircuitVerse/CircuitVerse#742]
On the website The Videos in getting started section are not able to play cuz they are being described as corrupted

**To Reproduce**
  Open Firefox Web browser
 Go to 'https://docs.circuitverse.org/#/getting_started'

**Expected behavior**
Videos must be ready to be played as like in other sections of the page

**Screenshots**
Attached below

**Are you working on this issue? (Yes/No)**
No

**Comment by MrBartusek** [comment]
![image](https://user-images.githubusercontent.com/23432278/71672973-b2106b00-2d77-11ea-8e63-813a9f6b6ba7.png)
works fine in my case, try update or reinstall browser
