### ISSUE TITLE
language filter for descriptions.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#761]
**Is your feature request related to a problem? Please describe.**
As the pics shared in this issue : https://github.com/CircuitVerse/CircuitVerse/issues/561
 many users on the platform use profanity which shoud be restricted.

**Describe the solution you'd like**
I want to restrict the use of profanity in at least descriptions.

**Describe alternatives you've considered**
We can use https://github.com/chrisvfritz/language_filter

**Additional context**
Ultimately It's my opinion and is totally up for discussion. Please let me know your thoughts on whether the description needs a profanity filter.
**Are you working on this? (Yes/No)**
GCI

**Comment by tachyons** [comment]
Agree with having a profanity filter for public projects, comments etc

**Comment by junron** [comment]
I think this should be a task
