### ISSUE TITLE
Navbar not working in new ux

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#765]
**Describe the bug**
On any page navbar buttons have `#` in href, `Learn` button is always active
Only `Login` and `Notifications` works properly
Page logo should work as an index button but it not

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any page with navbar
2. See error

**Expected behaviour**
Clicking buttons should change page and the selected page should be marked as active

**Screenshots**
![image](https://user-images.githubusercontent.com/23432278/71355793-6a702f00-2580-11ea-99c0-b972daa846d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
[Beginner GCI Task](codein.withgoogle.com/tasks/5710665268854784)

**Comment by junron** [comment]
Yep currently only Login works iirc

**Comment by MrBartusek** [comment]
@junron edited
