### ISSUE TITLE
No comments section in projects

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#767]
**Describe the bug**
The comments section on projects don't show 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to any project page
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/23432278/71357269-61359100-2585-11ea-9326-1bb9227d7ac9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No, That issue should be fixed by someone who will be redesigning project page, for more info ask on 
[UX channel](https://circuitverse-team.slack.com/archives/CQ17325A5) on [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE)

**Comment by aayush-05** [comment]
Can you mention some of the projects (from the public ones or either make yours public) where you have faced this issue. I can find the comment section on all the project pages I checked.

**Comment by MrBartusek** [comment]
@aayush-05 on production it is working fine, it has been broken on new ux (master)
