### ISSUE TITLE
Sign-in/Login page layout

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#769]
**Describe the bug**
Login and sing-in page needs layout changes

1. ~~Remember me checkbox is not styled at all~~ (fixed in #1259)
2. Social login buttons look odd when they are aligned that way if we want to stick to circles the best way to fix that will be something like that:

![image](https://user-images.githubusercontent.com/23432278/77224763-1a960980-6b69-11ea-8447-cb48ce3ffaa8.png)

3. Elements are not aligned with each other

![Bez tytułu](https://user-images.githubusercontent.com/23432278/77224728-cdb23300-6b68-11ea-9891-d4a12bda79f8.png)

4. Show password icon (eye) should be inside a textbox

5. Main action buttons (Log-in/Sign-in) are definitely too small and don't stand out when they should be the main button on the page they look very "little"

6. The whole section below text boxes looks like an overloaded mess. The big part in that issue also points `2` but, the important issue is that `New User? Sign up` and `Forgot password? Reset your Password` are basically the same font size and shape like normal page elements or titles when those elements are rarely used by end-user. They should be grey and don't stand out that much

7. I described login page mostly here but the sign-in page has exactly same problems

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by nitin10s** [comment]
1) Yes true I didn't make it during design therefore it was copied as it is from previous design.
2) There is a reason the button is left aligned. This might help you. https://www.interaction-design.org/literature/topics/fitts-law
3) There are no hard and fast rules for button styling. It should follow just some few basic guidelines: It must appear clickable and should clearly depict what'll happen on clicking. So, no need.
4) Yes there are aligment issues in the developed version. Correction is needed. You might refer to the XD prototype I've made.
5) Forgot password has similar styling and size like New User? Sign up and Login with elements. So that doesn't really stand out.
6) Yes it should be inside.

**Comment by AnupNair08** [comment]
I would like to work on this issue and come up with a solution covering all the suggested changes
Thanks

**Comment by AyanChoudhary** [comment]
Can I work on this, I already have experience with work like this and am quite good with it.

**Comment by MrBartusek** [comment]
Yes, go ahead @AyanChoudhary

**Comment by angrycharas** [comment]
I am a UI/UX designer and can make a better Log-in/Sign-in page.
I am planning to make a Figma file with the design of the new Log-in page, before starting to code.
Can I take this issue? (The PR linked to this issue is inactive for a long period of time.)

**Comment by AyanChoudhary** [comment]
It's already completed and has a pr linked to it.

**Comment by MrBartusek** [comment]
@angrycharas Nitin is coordinating UX remake, We already have [prortotype](https://xd.adobe.com/spec/7453ce8f-6d79-4969-4a1a-d0162c42c53d-0262/). If you would like to work on new UX please ask on #UX on Slack

**Comment by HarshalGoyal** [comment]
Hi i am Harshal Goyal 
I am an undergraduate student and i am willing to participate in gsoc 2020

**Comment by HarshalGoyal** [comment]
Can you please help me out by guiding me about project

**Comment by MrBartusek** [comment]
Hello @HarshalGoyal The best place for asking such things is our [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE)

**Comment by MrBartusek** [comment]
Still relevant

![image](https://user-images.githubusercontent.com/23432278/76141125-a421e380-6061-11ea-81c9-c248640ed9a6.png)

**Comment by nitin10s** [comment]
What is still relevant? Also, we'll be styling all checkbox uniformly soon.

**Comment by MrBartusek** [comment]
@nitin10s 
> Login in with a forgot password is not aligned with other elements
>Show password icon (eye) should be inside a textbox

**Comment by abstrekt** [comment]
I can work on the login-page for whatever seems off if all the claimers aren't working on it anymore, It's the second page all user's sees while visiting, I did a styling of the checkbox  #1259  (awaiting reviews)
@MrBartusek @nitin10s

**Comment by MrBartusek** [comment]
@nitin10s @abstrekt I completely re-elaborate the whole issue, now it should be cleaner

**Comment by abstrekt** [comment]
Removing some padding & margin will fix point 3
![Firefox_Screenshot_2020-03-21T11-07-37 257Z](https://user-images.githubusercontent.com/42478217/77225116-4d082c80-6b92-11ea-9d57-ec44e582e85c.png)

**Comment by abstrekt** [comment]
CV uses fontawesome, so we can use their social icons, should look good for point 2.
![Firefox_Screenshot_2020-03-21T11-13-00 879Z](https://user-images.githubusercontent.com/42478217/77225208-1da5ef80-6b93-11ea-8bc8-c28354de27c3.png)
![Firefox_Screenshot_2020-03-21T11-13-54 694Z](https://user-images.githubusercontent.com/42478217/77225218-2c8ca200-6b93-11ea-8932-82b315e2b993.png)
![Firefox_Screenshot_2020-03-21T11-14-25 082Z](https://user-images.githubusercontent.com/42478217/77225229-40d09f00-6b93-11ea-9859-d7dff4544cf4.png)

**Comment by abstrekt** [comment]
maybe for 4
![Firefox_Screenshot_2020-03-21T11-22-17 442Z](https://user-images.githubusercontent.com/42478217/77225366-65794680-6b94-11ea-83d7-bc2cc8239d94.png)

**Comment by abstrekt** [comment]
Shall I start working on it now? @nitin10s @MrBartusek

**Comment by nitin10s** [comment]
We've tweaked the input boxes actually, I'll send the new design soon.

**Comment by abstrekt** [comment]
was it Sign-in/Sign-up page layout ..

**Comment by MrBartusek** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/853#issuecomment-633228560
