### ISSUE TITLE
Old logo on index

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#771]
**Describe the bug**
CirciutVerse logo changed but the logo on index page is still old
If there is a black version of the new logo it should be replaced but if not it should be changed to normal text

**Screenshots**
![image](https://user-images.githubusercontent.com/23432278/71359392-8c6fae80-258c-11ea-8da8-f7517683def8.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No, might be GCI Task

**Comment by NumberC** [comment]
I don't think this is an issue. The logo changed, but CircuitVerse spelled out like that is a design choice that makes it look better and more unique. That image highlights the organization's name, even though it may not be the logo.

**Comment by nitin10s** [comment]
Actually, we currently don't have a logo as such. We'll be finalizing a new logo after GCI (It was a task for students)

**Comment by MrBartusek** [comment]
the index will be different in new UX so closing
