### ISSUE TITLE
CircuitVerse Doesn't Work on Mobile Devices

### ISSUE THREAD

**Issue by NumberC** [CircuitVerse/CircuitVerse#784]
**Describe the bug**
On mobile devices, you can't use the simulator!

**To Reproduce**
1. Go to CircuitVerse on a mobile device
2. Go to the simulator
3. Try to use it
4. You'll have a hard time using it

OR

1. Go to CircuitVerse on your browser
2. Inspect Element
3. Change Size to be similar to that of a mobile device
4. Go to the simulator
5. Try to use it
6. You'll have a hard time using the simulator

**Expected behavior**
I expect that using the simulator on any device should be easy and effortless. However, so much as trying to drag an input onto the circuit is frustrating and incredibly difficult.

**Screenshots**
I can't really provide screenshots.

**Desktop (please complete the following information):**
 - OS: Android (But this issue should be across all mobile devices)
 - Browser: Chrome
 - Version: 79.0

**Additional context**
No additional context.

**Are you working on this issue? (Yes/No)**
No.

**Comment by JoshHeng** [comment]
I suggest just disabling the simulator on mobile and displaying a message to use a desktop. Adding mobile compatability would be a huge job without much of a target audience, and a mobile screen is too small and quite unoptimised for this task

**Comment by MrBartusek** [comment]
On our [Slack](https://circuitverse-team.slack.com/archives/CJTJJ6XN0/p1578044638130300) we disused and like a @JoshHeng said there is no point of making simulator mobile-friendly, I will work on blocking it to mobile users

**Comment by JoshHeng** [comment]
@MrBartusek Note that the circuit previewing should still work (which is done through an iframe)

**Comment by satu0king** [comment]
@MrBartusek Instead of just disabling the simulator in previews, instead maybe show the circuit image that is saved.

**Comment by MrBartusek** [comment]
@satu0king this page triggers only when `edit.html.erb` is requested, did it broke something?

**Comment by JoshHeng** [comment]
@satu0king Does the circuit preview need to be interactive? Because then the image method wouldn’t work (or we could do one image per combination of inputs)

**Comment by satu0king** [comment]
> @satu0king this page triggers only when `edit.html.erb` is requested, did it broke something?

Oh my bad

**Comment by JoshHeng** [comment]
A better option could maybe be to show the user the interactive/embedded version of the circuit on mobile devices, which doesn't have the controls.
(For example showing this https://circuitverse.org/simulator/embed/42961 with a message at the top saying the circuit is only editable if a larger screen or computer is used)

**Comment by MrBartusek** [comment]
@JoshHeng `edit.html.erb` ([the file where detection is triggered](https://github.com/CircuitVerse/CircuitVerse/pull/806/files#diff-fac33a1fb6ffd5158a20f99fb570ac31)) is renderd only when user request:
`/simulator` which is rendering `SimulatorController#new`
`/simulator/edit/:id` which is rendering `SimulatorController#edit`
So user is blocked only when he click `Edit` or `Launch Simulator` on the project page (which have a preview build-in) or when he creates completely empty project so I don't see any sense in this change

![image](https://user-images.githubusercontent.com/23432278/71783183-63670900-2fe3-11ea-95e2-74231a20f140.png)

**Comment by NumberC** [comment]
What about instead of redirecting them to another page, you just forbid them from clicking on any of the circuits (Inputs, Outputs, Gates, etc.)?

**Comment by MrBartusek** [comment]
@NumberC The whole simulator on small screens is broken so I don't think there is any sense of doing that. For this moment we don't have plans to support simulator as slack poll says

![image](https://user-images.githubusercontent.com/23432278/71783286-ea68b100-2fe4-11ea-9359-c609a703c195.png)

**Comment by NumberC** [comment]
Currently, is the embeded view working? I thought it wasn't working.

**Comment by MrBartusek** [comment]
@NumberC all photos made on chrome dev tools phone emulator
Simulator - **Blocked**
![simulator](https://user-images.githubusercontent.com/23432278/71783352-e5f0c800-2fe5-11ea-8536-fc59e4a19bc8.png)

Embed - **Working**
![embed](https://user-images.githubusercontent.com/23432278/71783356-ef7a3000-2fe5-11ea-9797-2141d0a33bc9.png)

Project View - **Working but, not related UI issues**
![project view](https://user-images.githubusercontent.com/23432278/71783362-002aa600-2fe6-11ea-9c21-33a3f70af3b2.png)

**Comment by NumberC** [comment]
Oh, ok. Sorry, disregard my suggestion. I thought the project view wasn't working due to a change

**Comment by MrBartusek** [comment]
No problem

**Comment by JoshHeng** [comment]
I would change the buttons to:
`Go back` to `View Circuit` 
`Continue anyway` to `Go back`

`View Circuit` should go to the full screen, read-only embed page that I mentioned earlier. If you want, you can make another route (something like /simulator/view) which calls the same controller and does exactly the same thing.

Completely remove the ability to bypass the message as there is no need to give users access. So remove the cookies and all that code as it is unneeded and gives more things for the user's computer and server to do (such as requesting a completely new library from that CDN).

**Comment by MrBartusek** [comment]
@JoshHeng I moved it to [Slack](https://circuitverse-team.slack.com/archives/CJTJJ6XN0/p1578246347159700)

**Comment by ciphereck** [comment]
Should not close this issue. Once someone removes conflict in #810 by rebasing, then merging will automatically close this issue.

**Comment by MrBartusek** [comment]
> Should not close this issue. Once someone removes conflict in #810 by rebasing, then merging will automatically close this issue.

@JoshHeng
