### ISSUE TITLE
Dockerize code

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#8]
Dockerize the code to be run in development so developers can quickly get started.

**Comment by satu0king** [comment]
Go ahead! Thank you @manuelcarrizo 

1. Install the dependencies
2. Create the database(start another container)
3. Migrate the database
4. Start redis-server(not needed if it works without that)
5. Start the sidekiq server(Not needed if you don't do the previous step)
6. Load public and app folder as a volume, this will ensure all images are saved persistently and that the developers don't need to rebuild the container for every change. 

The primary goal of dockerizing is to allow front end developers to only focus on JavaScript instead of Rails.

**Comment by manuelcarrizo** [comment]
It worked without redis and sidekiq, please test it and let me know if I should add them too

**Comment by satu0king** [comment]
![image](https://user-images.githubusercontent.com/2092958/47250961-17b15980-d449-11e8-9ae6-80412576cde6.png)
Thats great!
It started the server perfectly. However redis is required for sending mails. It would be great if you could configure redis too. If not, it is not a big deal, that can be another issue, as the simulator can still be used without user signing in. 
Thanks a lot!
