### ISSUE TITLE
No option to Sign out

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#801]
**Describe the bug**
There is no option for :
- signout
- view my circuits,my profile 
in new UI
**To Reproduce**
1. Go to homepage 
2. See error

**Expected behavior**
There should be a dropdown containing these.

**Additional context**

**Are you working on this issue? (Yes/No)**
Yes

**Comment by ShreyaPrasad1209** [comment]
Sign out option is relevant only when the user is signed in that's why it is not present separately.
![2020-01-04 (2)](https://user-images.githubusercontent.com/43600306/71768161-bb493580-2f39-11ea-8df1-beaa04b0fab3.png)

**Comment by Ananthavijay** [comment]
@ShreyaPrasad1209 this is old ui. I am talking about the new one
