### ISSUE TITLE
In the simulator,project name merges with 'help' when the screen size is reduced

### ISSUE THREAD

**Issue by mohit-003** [CircuitVerse/CircuitVerse#807]
**Describe the bug**
In the simulator ,the name of the project merges with 'help' when screen is shrunk ,which makes it difficult to access 'help'.  

**To Reproduce**
1. Go to [Simulator](https://circuitverse.org/simulator)
2. Reduce the screen size , and look at the top bar.

**Expected behavior**
The project name should not merge with help.

**Screenshots**
![image](https://user-images.githubusercontent.com/58560983/71766726-f42cde80-2f28-11ea-92aa-02e3b6702580.png)

**Are you working on this issue?**
No

**Comment by aayush-05** [comment]
Looks like a good GCI task @tachyons

**Comment by Shivansh2407** [comment]
Can I work on this issue Please?

**Comment by AyanChoudhary** [comment]
Can I work on this issue? This looks like a good task which I can complete quickly.
