### ISSUE TITLE
Add search bar in simulator

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#809]
As a new user of CircuitVerse, I don't know in which categories all components are so it will be helpful to add a small search bar

**Additional context**
![image](https://user-images.githubusercontent.com/23432278/71786390-3cbcc880-300b-11ea-9582-e6553247f26f.png)
something like this but make it look as a search bar
![image](https://user-images.githubusercontent.com/23432278/71786450-ab018b00-300b-11ea-8bda-0c6f6a81a36f.png)

_This issue is a part of my [Usability Test](https://drive.google.com/open?id=1igwLx2tc1dAU_75qY2F4u7ZnHf2crcp-)_
**Are you working on this? (Yes/No)**
No

**Comment by MrBartusek** [comment]
still valid

**Comment by MrBartusek** [comment]
@tachyons can it be re-opened?

**Comment by kalyani489** [comment]
Can I work on this?
Can it be re-opened again?

**Comment by MrBartusek** [comment]
> Can I work on this?
> Can it be re-opened again?

I am not currently active in cv and I think there is simulator rework happening currently, please ask on slack

**Comment by kalyani489** [comment]
Yes ok, no problem

**Comment by satu0king** [comment]
Implemented in new UI
