### ISSUE TITLE
When having a lot of subcircuits the top and bottom of "insert subcircuit" dialog will span out of view.

### ISSUE THREAD

**Issue by alvarudras** [CircuitVerse/CircuitVerse#815]
When having a lot of subcircuits the top and bottom of "insert subcircuit" dialog will span out of view. This means you cannot close the dialog from "x" or select the subcircuits that are not visible. One fix would be to set maximum height to window and then "overflow: auto" style, that would cause scrollbar to appear when you have more subcircuits that will fit on that dialog.

**Comment by aayush-05** [comment]
Can you please attach a screenshot for this as well ?

**Comment by alvarudras** [comment]
sure :)
![screenshot](https://user-images.githubusercontent.com/2356565/72114434-29cc3000-334c-11ea-832c-388d86447cfc.PNG)

**Comment by Shivansh2407** [comment]
Hey can you please suggest a way in which this can be solved. I am trying to add overflow-y: scroll but it is not working /disabled . Please let me know a better method. Would like to fix this .
