### ISSUE TITLE
A custom context menu for the elements in side-bar.

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#817]
**Is your feature request related to a problem? Please describe.**
Right now we display little info about the tool we hover on but I purpose an option to view more information about the tool from the context menu.   

**Describe the solution you'd like**
A custom context menu with an option of more info that redirects to the docs page.
 
**Are you working on this? (Yes/No)**
GCI

**Comment by jha11aditya** [comment]
I added a onclick function on CircuitVerse Tip button in properties menu which redirects to the specific
help page of the circuit element in Pull Request No.  #843
