### ISSUE TITLE
Allow users to change values in ROM when in view mode.

### ISSUE THREAD

**Issue by superstewie** [CircuitVerse/CircuitVerse#82]
It is not possible to change the values stored in a ROM when in view mode. This applies to both ones own circuits and when viewing others circuits. I believe that allowing the ROM component to be edited when in view mode will add significant functionality to many circuits, especially in situations where it would be beneficial to allow users an easy method of entering data or instructions. Well, atleast until we get a RAM component, provided that the contents of a RAM component can be edited when in view mode.

Additionally, while discovering this I also discovered that, when in fullscreen view mode, pressing any key takes you out of full screen mode. This may be as intended, but it would be mighty annoying if ROM editing were enabled.

**Comment by superstewie** [comment]
> It is possible to edit the ROM in view mode. Please check the same. However, the below issue persists in view mode.

I see now. I don't know why I couldn't get it to work the other day. I guess PEBKAC was the likely culprit.

**Comment by satu0king** [comment]
The issue is not with ROM but with full screen. For some reason, the keyboard does not work properly in full screen. I am not sure there will be a fix.
