### ISSUE TITLE
Scroll up to Zoom in and Scroll down to Zoom out

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#828]
**Describe the bug**
In the simulator when you scroll up it should zoom in but it is happening the opposite.

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Scroll Up

**Expected behavior**
When you scroll up, it should zoom in and not zoom out

**Screenshots**

**Are you working on this issue? (Yes/No)**
No

**Comment by yash15601** [comment]
yes

**Comment by yash15601** [comment]
i am working

**Comment by yash15601** [comment]
@Ananthavijay  when we press ctrl +scroll mousewheel up its working perfect

**Comment by Ananthavijay** [comment]
But it would great if it works with just scroll

**Comment by yash15601** [comment]
ok

**Comment by shubhankarsharma00** [comment]
I always thought of this as a feature rather than a bug normal scroll up zooms in and ctrl + scroll zooms out(i.e. inverts the scroll) some might prefer inverted zoom so as long as both zooms are available I don't think we need a fix for this. What do you think @tachyons @ankitkataria?

**Comment by Ananthavijay** [comment]
@shubhankarsharma00 then we should let the user know to use control+scroll to scroll instead of just scroll

**Comment by Ananthavijay** [comment]
@shubhankarsharma00 There is no doc for controls, like the selection of many components is done by shift+mouse button.

**Comment by Shivansh2407** [comment]
Can I please work on this issue @Ananthavijay ?

**Comment by Shivansh2407** [comment]
Please review the PR @Ananthavijay .

**Comment by satu0king** [comment]
So many people have sent PRs inverting this feature again and again over time. There is no solution, each OS does something differently, each browser does something differently, mouse and keypad do something differently. Unless someone comes up with a real solution, we are not going to merge simple inversions
