### ISSUE TITLE
Demultiplexer "remembers" output of non-selected outputs

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#83]
According to the documentation (and expected behavior), the demultiplexer is supposed to return zero for the non-selected outputs and forward the input to the currently selected output.

However, I'm seeing that the multiplexer "remembers" the value of each output.
To reproduce, go to https://docs.circuitverse.org/#/decodersandplexers?id=demultiplexer and do this:
- make T=1 while S=0; O1 is 1 as expected but O2 is X (expected is zero)
- now make S=1. O2 becomes 1, but O1 remains 1 (expected is zero, according to table above the circuit).

**Comment by satu0king** [comment]
Thank you for reporting this bug

**Comment by satu0king** [comment]
Can you confirm if the issue is fixed.

**Comment by fpintos** [comment]
Fixed indeed. Thanks.
