### ISSUE TITLE
Add support for re-ordering subcircuits

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#84]
I would like to be able to re-order subcircuits.

Right now it is possible to move an unused subcircuit to the end of the list by copying its elements and pasting to a new subcircuit. But if the subcircuit is already in use this doesn't work unless you manually remove all usages and add them back after the move.

Expected usage would be to be able to click on the subcircuit title and drag it around, similar to tabs in the browser.

**Comment by satu0king** [comment]
This is an important requirement which would need significant changes to the code. Right now we do not store the order in which the circuits are to be displayed.

**Comment by Shivansh2407** [comment]
Can you please explain the issue clearly . I would like to fix this issue.
