### ISSUE TITLE
Clear circuit function should have popup asking if you're sure

### ISSUE THREAD

**Issue by CEa-TIde** [CircuitVerse/CircuitVerse#848]
The clear function clears the circuit without asking if you're sure. This way a misclick can almost be fatal to your progress.

**Additional context**
I have almost lost a whole computer circuit to this, so please add this. The only ways to recover the circuit are to luckily have a recent offline save or go to your circuits and reopen the project.

**Are you working on this? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
Can You specify which all files need this Change? I would love to work on this @CEa-TIde .

**Comment by CEa-TIde** [comment]
Unfortunately I am not familiar with the code base and cannot tell you which files need to be changed. I've tried to look for it, but cannot find any files related to the clear function. My guess would be that is in the same file as the save (offline/online) feature and other from the same list.

@Shivansh2407

**Comment by jha11aditya** [comment]
Oh sorry I didn't see there was already a pull request, there was none about 2 hrs ago.

**Comment by Shivansh2407** [comment]
@jha11aditya I was Working on the issue as you could see my comment above. Please first claim the issue and then work to avoid this type of situations.

**Comment by jha11aditya** [comment]
Yes, ok.
