### ISSUE TITLE
Project Properties does not update when moving from one subcircuit to another

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#85]
The "Circuit" name in the "Project Properties" div in the editor does not update as you move from one subcircuit to another.

Repro:
- Create a project with two or three subcircuits
- Click on the subcircuits name at the top of the editor to move from one to another.
Actual:
- Notice the circuit name in the "Project Properties" does not update as you move from circuit to circuit.
Expected:
- Project Properties to show name of currently selected subcircuit.

Mitigations:
- If you happen to click in a blank space in the editor, then the name of the selected circuit shows up in the Project Properties.
- Edit Layout and Delete buttons seem to act on the selected subcircuit as expected, even when the name shown in the Project Properties is incorrect.

**Comment by superstewie** [comment]
Additionally, if you click in the "Circuit" panel, as if you were going to type something there, and then click on blank space, it changes the name of the current circuit to the name of the previous circuit.

**Comment by satu0king** [comment]
Please check if the issue is fixed.
