### ISSUE TITLE
Blank Circuit Name Breaks Bar Height

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#851]
![image](https://user-images.githubusercontent.com/23432278/73392216-a746e880-42d9-11ea-8bf9-e21f602f804a.png)

When names of all project circuits are empty the circuit selection bar changes width to 5.9px. The best solution will be to don't allow for blank names
_This issue is a part of my [Usability Test](https://drive.google.com/open?id=1igwLx2tc1dAU_75qY2F4u7ZnHf2crcp-)_

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
I would like to work on this issue @MrBartusek

**Comment by MrBartusek** [comment]
@Shivansh2407 sure, go ahed

**Comment by Shivansh2407** [comment]
Can you guide me a bit on where to proceed this issue?? (If possible please specify the file)

**Comment by MrBartusek** [comment]
@Shivansh2407 no idea, ask on [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE)

**Comment by Shivansh2407** [comment]
![1](https://user-images.githubusercontent.com/42182955/73765331-66981500-479a-11ea-97a3-292dd3fc35ab.PNG)
@MrBartusek Which Break are you referring to ? I have created a project without giving the title but I see no break in Bar Height.
Please let me know soon.

**Comment by MrBartusek** [comment]
@Shivansh2407 

![ezgif-2-9e05678c2f6b](https://user-images.githubusercontent.com/23432278/73766129-e069d780-4775-11ea-934b-c6e18576244b.gif)

**Comment by Shivansh2407** [comment]
Ok Cool . Looking forward to fix this issue .
