### ISSUE TITLE
Unwanted pop-up when editing element's label in simulator

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#852]
![ezgif-2-9609bca3a01e](https://user-images.githubusercontent.com/23432278/73393348-c9416a80-42db-11ea-940c-50a445617644.gif)

While testing simulator I came across popup that showed while editing diode label that prompted to insert label but inserting it and accepting pop-up didn't changed the label
_This issue is a part of my [Usability Test](https://drive.google.com/open?id=1igwLx2tc1dAU_75qY2F4u7ZnHf2crcp)_
**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
Which file has that issue @MrBartusek Sir?

**Comment by MrBartusek** [comment]
@Shivansh2407 no idea, ask on [Slack](https://join.slack.com/t/circuitverse-team/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE)

**Comment by Shivansh2407** [comment]
@MrBartusek I would like to work on this but first please change/update the example screenshot (It is not visible).

**Comment by Shivansh2407** [comment]
Working on it.

**Comment by Shivansh2407** [comment]
@MrBartusek Should I remove the Label prompt or should I link the Prompt with Label Updation. According to me Removing the prompt is much better because we can change the Label from the Sidebar.
