### ISSUE TITLE
Update ERD 

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#857]
**Describe the bug**
The ERD here: https://github.com/CircuitVerse/CircuitVerse/blob/master/erd.pdf is outdated.

**Are you working on this issue? (Yes/No)**
It can be a first-time issue.

**Comment by Shivansh2407** [comment]
What Can we update in here? I would like to work on this issue

**Comment by shubhankarsharma00** [comment]
Many new tables like notifications taggings have to be added.

**Comment by Shivansh2407** [comment]
Can you please explain more on this so that I can Update this.

**Comment by tachyons** [comment]
It is difficult to maintain such a file, we can just remove that file instead

**Comment by Shivansh2407** [comment]
Should I open a PR for that ?

**Comment by YashKumarVerma** [comment]
> It is difficult to maintain such a file, we can just remove that file instead

I think we must not completely remove the file, instead, we can use some other method to share database details.

**Comment by shubhankarsharma00** [comment]
> Something like https://erdplus.com/ would be helpful.

This still takes effort. I agree with @tachyons we should remove the file.

**Comment by Shivansh2407** [comment]
So @shubhankarsharma00 and @tachyons should I open a PR for the same?

**Comment by shubhankarsharma00** [comment]
The issue is still an open discussion but go ahead open the PR.
