### ISSUE TITLE
Unexpected sticky selection

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#86]
This is a weird one since I haven't figured out a consistent repro yet:
- _Sometimes_ the set of selected elements in the editor gets stuck and I seem unable to deselect them. I can click around in other elements without using shift and this causes the elements to be added to the selection.

Normally I double-click (or triple-click) in a blank part of the editor and that seems to be enough to deselect all elements but when this bug happens I seem unable to deselect them. I've seen this happening with me and my son's computers as I was teaching him. _Great tool for teaching kids, by the way, thanks for it!_

Anyway, when this happens, the only way I get back to a working state is by inserting a new element. This seems to clear the selection and then I can delete this newly added element.

I'll update this if I manage to figure out the repro.

**Comment by satu0king** [comment]
> Normally I double-click

Yes, double click is what is to be done to deselect. 

I think this is only possible because the shift listener was missed somehow. If this happens just try hitting shift again and see what happens.

**Comment by fpintos** [comment]
No luck with pressing shift again.

**Comment by satu0king** [comment]
Strange, we will need to be able to reproduce the issue to debug this.

**Comment by Parikshit-Hooda** [comment]
@fpintos Is there any progress on this issue?
