### ISSUE TITLE
The description of a project does not respect rich text formatting

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#87]
When the site shows the description of a project it does not respect rich text used when we edit such description.

Repro:
- Create a new project and use rich text when editing its description (in https://circuitverse.org/users/{id}/projects/{id}/edit)
- View the project (https://circuitverse.org/users/{id}/projects/{id}) and notice that the rich text is lost.

Expected:
- For rich text to be displayed.
- Alternatively, for the description to support markdown and for this markdown to be interpreted when viewing the project's description.

**Comment by satu0king** [comment]
Could you check if the issue is rectified.

**Comment by fpintos** [comment]
Indeed it is fixed. Thanks!
