### ISSUE TITLE
Make navbar logo and button responsive

### ISSUE THREAD

**Issue by kartik918** [CircuitVerse/CircuitVerse#871]
**Describe the bug**

Current Navbar is unresponsive and the nav button also covers part of the screen on smaller devices.

**To Reproduce**
1. Go to any page on https://circuitverse.org/
2. Switch to responsive mode on browser if not on a smaller screen.

**Expected behavior**
Navbar fits right on  smaller screens with logo on the left and nav button to the right.

**Desktop:**
 - OS: Windows
 - Browser: Firefox

**Are you working on this issue? (Yes/No)**
Yes if you could direct me to the files involved for the header I have a fix I believe could work.

**Comment by Shivansh2407** [comment]
Can I work on this?

**Comment by kartik918** [comment]
I've worked on a fix already , thanks though
