### ISSUE TITLE
Sign-in with Google account always goes thru sign-up process

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#88]
I signed-up to CircuitVerse using Google account and sign-on process showed up as expected.

However, when I need to sign-in again, the Google button in the https://circuitverse.org/users/sign_in page goes thru the whole sign-up process again. This happens every time I need to sign-in.

Expected: after completing the Google sign-on process once I should be able to sign-in without seeing all the sign-on pages again.

**Comment by satu0king** [comment]
Interesting, the library does all the API calls. Not sure we can do much about it.

**Comment by fpintos** [comment]
Perfect!
