### ISSUE TITLE
New Circuit and Sub Circuit Bugs

### ISSUE THREAD

**Issue by Shivansh2407** [CircuitVerse/CircuitVerse#899]
**Describe the bug**
There are some bugs present in the New Circuit and Insert SubCircuit Feature that need to be fixed to make the UI more user friendly.
1. Whenever we enter a long name , then if we try to insert it as a subcircuit , it will flow out from the existing div.
2. Including #815 . When many subcircuits are involved then the Insert Subcircuit overflows vertically. Then user has to refresh in order to get back. 

**To Reproduce**
1. Go to 'https://circuitverse.org/'
2. Click on 'New Circuit +' or  'Insert SubCircuit'
3. See error

**Expected behavior**
1. Overflowing in the Insert Subcircuit must be removed .
2. All subcircuits must be shown in the pop-up.

**Screenshots**
1.
 ![1](https://user-images.githubusercontent.com/42182955/74504958-e69d4800-4f1b-11ea-9d22-c950c6994529.PNG)
2.
 ![2](https://user-images.githubusercontent.com/42182955/74504961-e7ce7500-4f1b-11ea-85a8-bb5e4dc5fd0b.PNG)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome]

**Are you working on this issue? (Yes/No)**
Yes

**Comment by yash15601** [comment]
Hey  @Shivansh2407  ,

3. When we Click on Insert subcircuit then if we have three circuits then only two of them show up in the Pop-up

So this is not an issue, when you create a new circuit you switch to it directly.
Thus when you try to insert a new circuit it wont show the circuit itself. Try switching to `Main` circuit and then open the `Insert SubCircuit` dialog and it'll show you the circuit you created. 
The simulators tries to avoid adding the circuit to itself as sub circuit to avoid the whole loop problem and thus this isn't a bug.

Take a look at this:

![Screenshot (47)_LI](https://user-images.githubusercontent.com/49101492/74835066-a3d7d780-5342-11ea-88c2-d536949fea70.jpg)

![Screenshot (49)_LI](https://user-images.githubusercontent.com/49101492/74835253-f0bbae00-5342-11ea-9e4d-a5279df2b679.jpg)

![Screenshot (48)_LI](https://user-images.githubusercontent.com/49101492/74835159-c4a02d00-5342-11ea-8a7a-c4dfa56598c5.jpg)

**Comment by Shivansh2407** [comment]
> Hey @Shivansh2407 ,
> 
> 1. When we Click on Insert subcircuit then if we have three circuits then only two of them show up in the Pop-up
> 
> So this is not an issue, when you create a new circuit you switch to it directly.
> Thus when you try to insert a new circuit it wont show the circuit itself. Try switching to `Main` circuit and then open the `Insert SubCircuit` dialog and it'll show you the circuit you created.
> The simulators tries to avoid adding the circuit to itself as sub circuit to avoid the whole loop problem and thus this isn't a bug.
> 
> Take a look at this:
> 
> ![Screenshot (47)_LI](https://user-images.githubusercontent.com/49101492/74835066-a3d7d780-5342-11ea-88c2-d536949fea70.jpg)
> 
> ![Screenshot (49)_LI](https://user-images.githubusercontent.com/49101492/74835253-f0bbae00-5342-11ea-9e4d-a5279df2b679.jpg)
> 
> ![Screenshot (48)_LI](https://user-images.githubusercontent.com/49101492/74835159-c4a02d00-5342-11ea-8a7a-c4dfa56598c5.jpg)

Cool, I thought it differently that it must be adding all the given subcircuits to Main Only . Thanks for pointing this out . Will take care of it.

**Comment by yash15601** [comment]
Hey @Shivansh2407  Are you still working in this PR because I have already fix this if you dont have problem can i make PR again

**Comment by Shivansh2407** [comment]
Actually I was working on some more Subcircuit bugs simultaneously , so if you want go ahead and make a PR.

**Comment by yash15601** [comment]
Thanks , will make PR tonight

**Comment by Shivansh2407** [comment]
Cool But make sure to fix the Bugs mentioned here. I will then open a separate issue for other subcircuit bugs. All the best 👍

**Comment by Shivansh2407** [comment]
@tachyons the first part of the issue is not fixed yet and I have asked @yash15601 to fix it in the PR he made. I think till then the issue must remain open.

**Comment by tachyons** [comment]
Make separate issues for bugs, otherwise it will be difficult to keep track of

**Comment by Shivansh2407** [comment]
Ok @tachyons 👍
