### ISSUE TITLE
Implement Subscriptions for comments

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#91]
https://github.com/lml/commontator

Check the documentation and add the functionality of subscriptions to comments.

**Comment by Swapnilr1** [comment]
I would like to work on this.

**Comment by hjhimanshu01** [comment]
Hey @satu0king , May I work on this enhancement?

**Comment by hjhimanshu01** [comment]
@armudgal may I work on this issue if it isn't taken?

**Comment by armudgal** [comment]
Please go forward @hjhimanshu01

**Comment by Amansingla97** [comment]
@hjhimanshu01 are you still working on it ? I would like to work on this

**Comment by hjhimanshu01** [comment]
@Amansingla97 , Thanks Aman , would reach you out if I'm stuck somewhere , for now it's going well.

**Comment by hjhimanshu01** [comment]
@Amansingla97 , I think it might take time to implement this and I'm currently having semester exams , go ahead and take this issue . Thanks !

**Comment by armudgal** [comment]
Hi @Amansingla97, will you be working on it?

**Comment by Sadat97** [comment]
if no one is working on it, i have used this gem recently in a school project and i would like to help

**Comment by Amansingla97** [comment]
@armudgal yes i am on it

**Comment by Amansingla97** [comment]
@armudgal @satu0king  Although I have enabled the subscription for the comments but the subscription mailer is not working. What I think is that ,the commontator uses mailgun as a mailer and in the the source code of it ,they have not mentioned any public key. Kindly correct me if I am wrong. I too have raised a issue in their repo as well :)

**Comment by satu0king** [comment]
Not very aware on how this gem works internally. I am sure if they have a default configuration of mailgun, there should be a way to change it. Also can you check and see if other emails are being sent? Emails will be sent only if redis-server is running. So maybe you can start a redis-server and check.

**Comment by Amansingla97** [comment]
@satu0king @armudgal where are the mailing variables defined ?
<img width="713" alt="screenshot 2019-03-07 at 9 21 24 pm" src="https://user-images.githubusercontent.com/20012612/53969539-fc589980-411e-11e9-8e94-5b3bcaf77ea3.png">
I was not able to find the environment file

**Comment by armudgal** [comment]
If we included the env file here, it would kill the purpose of having it in the first place.
https://www.honeybadger.io/blog/ruby-guide-environment-variables/ go through this.

You need to setup your own `smtp settings`.
