### ISSUE TITLE
Insert subcircuit button still visible even if there are no subcircuits

### ISSUE THREAD

**Issue by Nitish145** [CircuitVerse/CircuitVerse#914]
**Describe the bug**
A clear and concise description of what the bug is: When there are no SubCircuits there shouldn't be a button to _Add SubCircuit_ as it may be confusing to first time users.

Similiar behaviour is observed when trying to open offline projects. 

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Click on Circuit -> Insert Subcircuit
3. See error

**Expected behavior**
If there are no subcircuits or offline projects, no button indicating _Insert SubCircuit_ or _Open Project_ should be visible respectively. 

**Screenshots**
![Screenshot from 2020-02-19 19-56-48](https://user-images.githubusercontent.com/45434030/74855290-8157b580-5366-11ea-9f04-bcd3c299619f.png)
![Screenshot from 2020-02-19 19-47-27](https://user-images.githubusercontent.com/45434030/74855313-87e62d00-5366-11ea-8d7b-053af4375169.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 18.04

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Shivansh2407** [comment]
As far as this issue is concerned , the button is not clickable so that will not create a confusion but disabling it will be good.

**Comment by Nitish145** [comment]
Yes! button is non clickable but when i first time used simulator i was a bit confused what this button is for if there are no offline projects :)
