### ISSUE TITLE
ask user before redirecting to login page

### ISSUE THREAD

**Issue by Nitish145** [CircuitVerse/CircuitVerse#923]
**Describe the bug**
When a not logged in user tries to save a project, an alert is shown and the user is redirected to the login page. User is not presented with a choice of not being redirected to login page..

**To Reproduce**
1. Go to https://circuitverse.org/simulator
2. Click on Circuit -> New Circuit
3. Save the project
4. See error (if not logged in).

**Expected behavior**
A Prompt asking user if he/she wishes to be redirected to login page and if user chooses NO/CANCEL he/she is not redirected

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version 80.0.3987.116

**Additional context**

**Are you working on this issue? (Yes/No)**
No

**Comment by arpancodes** [comment]
I am working on it

**Comment by arpancodes** [comment]
@tachyons

**Comment by arpancodes** [comment]
Just fixed the issue. Please review @tachyons
