### ISSUE TITLE
Label of input button not shown in Firefox

### ISSUE THREAD

**Issue by criticic** [CircuitVerse/CircuitVerse#924]
**Describe the bug**
#### Mozilla Firefox
![Screenshot_2020-02-22_17-08-03](https://user-images.githubusercontent.com/40538506/75091696-5d7ab680-5596-11ea-821a-8a398a23c196.png)
#### Chromium
![Screenshot_2020-02-22_17-08-28](https://user-images.githubusercontent.com/40538506/75091697-5f447a00-5596-11ea-9972-3f91feff929e.png)

**To Reproduce**
1. Go to Firefox and open the simulator

**Expected behavior**
Chromium & Firefox should have same result. 

**Desktop (please complete the following information):**
 - OS: [e.g. iOS ] ARCH Linux
 - Browser [e.g. chrome, safari] Mozilla Firefox
 - Version [e.g. 22] 72.0.2

**Additional context**
A whole lot of errors appear on Firefox :
![Screenshot_2020-02-22_17-17-33](https://user-images.githubusercontent.com/40538506/75091799-56a07380-5597-11ea-80f6-6d22b3fd2553.png)

**Are you working on this issue? (Yes/No)**
Yes

**Comment by thiefie** [comment]
@satu0king

**Comment by sal2701** [comment]
@thiefie I can see the label. It is working fine for me. I am using Firefox 72.0.2 on Ubuntu with i3wm.

Screenshot:
![cv1](https://user-images.githubusercontent.com/42511766/75092940-092a0380-55a3-11ea-9e8e-d117ee0e32fb.png)

**Comment by yash15601** [comment]
@sal2701  update your forked repo
 follow this link :
https://gist.github.com/CristinaSolana/1885435
