### ISSUE TITLE
Tooltip slightly upward in circuit elements when we hover 

### ISSUE THREAD

**Issue by yash15601** [CircuitVerse/CircuitVerse#926]
**Describe the bug**
When we hover on Circuit Elements in the simulator the Tooltip slightly shifted upward from the bottom 

**To Reproduce**
1. Go to 'Simulator'
2. Hover on 'Circuit Elements'

**Expected behavior**
The ToolTop should be at the bottom of Circuit Elements

**Screenshots**
![Screenshot (58)_LI](https://user-images.githubusercontent.com/49101492/75095031-d38f1580-55b6-11ea-8ace-99d269b5d023.jpg)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. chrome]
 - Version [e.g. 80.0.]

**Are you working on this issue? (Yes/No)**
YES

**Comment by Shivansh2407** [comment]
@yash15601 this is the case with localhost I guess. On the website it is working absolutely fine 👍

**Comment by yash15601** [comment]
@Shivansh2407  i think the problem is with new ui

**Comment by Shivansh2407** [comment]
I think you must try cloning the repo again. That might fix this .

**Comment by yash15601** [comment]
Actually, I am noticing this from past few days and my repo is updated

**Comment by yash15601** [comment]
@Shivansh2407 can you provide me your screenshot is it working or not

**Comment by yash15601** [comment]
@nitin10s  views please

**Comment by nitin10s** [comment]
As @Shivansh2407 said, it works fine on the website, so lets put a hold on this PR.

**Comment by nitin10s** [comment]
As @Shivansh2407 said, it works fine on the website, so lets put a hold on this issue.
