### ISSUE TITLE
Issue with README.md 

### ISSUE THREAD

**Issue by ShubhankarKG** [CircuitVerse/CircuitVerse#927]
**Describe the bug**
There's a small typography error in the file __README.md__ .

**To Reproduce**
1. Go to __README.md__ .
2. Scroll down to line 84.
4. The Back Tick symbol (`) used to define code blocks has imperfect opening and closing set of back ticks

**Expected behavior**
Code block form for the line :
`gitpod url/users/auth/(google or facebook or github)/callback`

**Screenshots**
![Screenshot from 2020-02-22 21-34-28](https://user-images.githubusercontent.com/50791000/75095539-a729c800-55bb-11ea-9f77-2606daa4d700.png)

**Desktop (Doesn't really matter as per se):**
 - OS: Ubuntu 18.04 LTS
 - Browser :- Chrome

**Are you working on this issue? (Yes/No)**
Yes

Tagging @tachyons

**Comment by Ananthavijay** [comment]
I think this is being done in this [PR](https://github.com/CircuitVerse/CircuitVerse/pull/835)

**Comment by ShubhankarKG** [comment]
I have fixed the same. Please review @tachyons

**Comment by Ananthavijay** [comment]
@tachyons This can be closed.
