### ISSUE TITLE
20 And Counting most BRAIN MELTING bugs I ran into while making the 16-Bit Computer

### ISSUE THREAD

**Issue by DevL0rd** [CircuitVerse/CircuitVerse#935]
Here is a link to the computer I mentioned in the title.
https://circuitverse.org/users/17603/projects/54486

I love circuit verse and hope alot of these annoying issues get fixed. thanks everyone who works so hard on this, But withouth further ado... let me release my frustration this software has fueled me with.

While building this I ran into very many frustrating issues I would like to list here.
I really hope they are fixed in the future.

1. When typing a value that is out of range for any gate or anything for that matter, you are not told that. In fact select something else and selecting it again it will show it is reset. The arrows prevent leaving the range but.. still

2. If you do 0 for bitwidth on anything you will be unable to change any of its properties. you have to delete it and replace it.

3. OW MY EYES: DARK THEME PLEASE

4. REMOVE THE ADRESS BIT LIMIT ON THE EEPROMS.
If i'm going to make something crazy i want the freedom. i had to spend hours making something to extend their memory address range. and end the end the one i made wasn't persistent it would clear on move or copy etc. PLEASE fix this. i want to leave programed roms for my computer but can't because of this.

5. Related to that, EEPROMS do not persist inside of subchips. which really sucks when i'm trying to get around the already sucky limited address space of eeproms. please frikin fix that.

6. Deselect everything when clicking away from it. JESUS I HAVE DELETED OR MESSED UP SO MANY THINGS BECAUSE OF THIS. sorry. alot of rage from this.... sometimes the f-ups are ireeversable because everynow and then undo fails and saves stop working. very rare, but it happens.

7. The camera will start zooming and panning at weird speeds and directions when scrolling to zoom until i hit a key , usually i hit shift and it fixes it for a few secs.

8. when editing somethings label, everynow and then backspace will delete the thing i'm editing.

9. When pasting deselect the old stuff.

10. When copying don't deselect everythin after. PLEASE. when copying large things it lags and if i have to move it after... just dear god.

11. The size of the flags monitoring thing is always wrong in crome at the bottom. its in a small box with scrollbars and its hard to see whats going on. and idk how to control it. there are no docs on that.

12. When in IE and edge you can zoom in anywhere on the page messing up the layout.
However in chrome you can zoom only if the left toolbar is focused.

13. The screen is very buggy. I have a 80 column 10 row screen and sometimes after a very short period, not when the screen is filled or columns are filled, can't tell why, but suddenly everything but text dissapears while the ascii screen is visible, and when it is not everything re-appears. Also when the ascii screen is on screen in this state the mouse up event doesn't work making me forever drag until it is off screen.

14. Undo sometimes takes 2 or 3 times hitting it for it to work, but sometimes it doesn't even work at all making it severly frustrating when i mess something up.

15. Recovering unsaved work is a absolute joke. I have lost progress so many times due to these bugs, but worst of all recovering a save rarely works. And if you load something up before recovering it, you can forget about seeing it again. you need more slots for recovery.

***NEWEST BUGS***
16. Sometimes after saving the simulation just completely craps out and won't step forward, even though everything is still controllable.

17. Splitters dissapear halfway off screen alot of the time.

18. Saving randomly dies and stops working. And when this happens so does offline save. Saving results in endless saving icon and not ever being able to recover the work done in that time. this has happened to me more than 5 times.

19. Sometimes when returning to the site I am signed out after loading my own project. and after a refresh i need to sign in.

20. When you have alot of chips the insert chip menu goes off the top and bottom of page and doesn't allow scrolling. You have to zoom the page to get to the off screen chips.

Extras:

Middle click to delete would be amazing.

Add a eep rom edit menu where we can manually paste in data for the whole rom. then i can make really long programs.

The delay option on everything does not work at all. But maybe it doesn't do what.. well it says.

The world clock controls all clocks while for the longest time i thought each clock had a seperate speed.

**Comment by DevL0rd** [comment]
Added 4 more bugs to the list. I'll keep adding to this one when they come up..

Undo sometimes takes 2 or 3 times hitting it for it to work, but sometimes it doesn't even work at all making it severly frustrating when i mess something up.

Recovering unsaved work is a absolute joke. I have lost progress so many times due to these bugs, but worst of all recovering a save rarely works. And if you load something up before recovering it, you can forget about seeing it again. you need more slots for recovery.

When in IE and edge you can zoom in anywhere on the page messing up the layout.
However in chrome you can zoom only if the left toolbar is focused.

The screen is very buggy. I have a 80 column 10 row screen and sometimes after a very short period, not when the screen is filled or columns are filled, can't tell why, but suddenly everything but text dissapears while the ascii screen is visible, and when it is not everything re-appears. Also when the ascii screen is on screen in this state the mouse up event doesn't work making me forever drag until it is off screen.

**Comment by DevL0rd** [comment]
Ok 4 more new bugs to add to the list.

16. Sometimes after saving the simulation just completely craps out and won't step forward, even though everything is still controllable.

17. Splitters dissapear halfway off screen alot of the time.

18. Saving randomly dies and stops working. And when this happens so does offline save. Saving results in endless saving icon and not ever being able to recover the work done in that time. this has happened to me more than 5 times.

19. Sometimes when returning to the site I am signed out after loading my own project. and after a refresh i need to sign in.

**Comment by DevL0rd** [comment]
oh forgot
20. When you have alot of chips the insert chip menu goes off the top and bottom of page and doesn't allow scrolling. You have to zoom the page to get to the off screen chips.

**Comment by yash15601** [comment]
20. Is already  their  as issue  and I almost  fixed that so no need to mention  this issue you can at this pr 
https://github.com/CircuitVerse/CircuitVerse/pull/938

**Comment by satu0king** [comment]
@DevL0rd, thanks for using CV and patiently facing our bugs! Please consider joining our slack channel and helping us identify and fix these issues.

**Comment by satu0king** [comment]
> When pasting deselect the old stuff.

Double click anywhere to deselect for now.

**Comment by satu0king** [comment]
> The world clock controls all clocks while for the longest time i thought each clock had a seperate speed.

Yes, The user interface is not very clear on this.

**Comment by satu0king** [comment]
15, 16, 18 and 19 seem related to me. @DevL0rd could you paste what you see in your browser console when this happens? Its very hard to debug these issues and any help would be great. @tachyons do you have any ideas as to why the server might reject a save request?

**Comment by tachyons** [comment]
No idea, may because payload was too big and server closed connection 🤔 . Need to check in detail

**Comment by DevL0rd** [comment]
@satu0king will do. I'll keep this open. They are intermittent issues but hwen they happen i'll be sure to open my developer console. I am running chrome ATM. I'll post more details like chrome version, etc when I upload the next time it happens.

Can you help me with joining the slack channel? The sooner we can track down the cause of these bugs the better XD I'd love to have a little less frustration building my computer. I dream of it one day running a crappy tetris lolol

**Comment by Ananthavijay** [comment]
Click this [link](https://circuitverse-team.slack.com/join/shared_invite/enQtNjc4MzcyNDE5OTA3LTdjYTM5NjFiZWZlZGI2MmU1MmYzYzczNmZlZDg5MjYxYmQ4ODRjMjQxM2UyMWI5ODUzODQzMDU2ZDEzNjI4NmE) to join circuitverse in slack

**Comment by DevL0rd** [comment]
@Ananthavijay Thanks!

**Comment by YizhePKU** [comment]
> When editing somethings label, every now and then backspace will delete the thing i'm editing.

I can relate to this. Sometimes when I am editing the label, it seems that the keyboard input is not completely captured. For example, when I tries to enter 'Q' in the label it pops up the "edit bit width" window, though the input 'Q' is actually appended to the label as well. In case of backspace, it just deletes the circuit altogether. But I cannot find a way to consistently reproduce the BUG. Sometime it works and sometimes it just breaks.

**Comment by Shivansh2407** [comment]
> > When editing somethings label, every now and then backspace will delete the thing i'm editing.
> 
> I can relate to this. Sometimes when I am editing the label, it seems that the keyboard input is not completely captured. For example, when I tries to enter 'Q' in the label it pops up the "edit bit width" window, though the input 'Q' is actually appended to the label as well. In case of backspace, it just deletes the circuit altogether. But I cannot find a way to consistently reproduce the bug. Sometime it works and sometimes it just breaks.

The Backspace Feature has been enabled in #952 .

**Comment by YizhePKU** [comment]
@Shivansh2407 This is a different, unrelated bug. When I press Backspace when editing a label in the properties panel, sometimes it deletes the circuit instead.

**Comment by YizhePKU** [comment]
@DevL0rd Please take a look at #971. Would that solve (part of) your problem? Any feedback is welcome :)

**Comment by DevL0rd** [comment]
> @DevL0rd Please take a look at #971. Would that solve (part of) your problem? Any feedback is welcome :)

Absolutely it does!

**Comment by DevL0rd** [comment]
> @Shivansh2407 This is a different, unrelated bug. When I press Backspace when editing a label in the properties panel, sometimes it deletes the circuit instead.

For this one it only happens when the mouse isn't hovering over the toolbar. The simulator thinks the canvas is focused because of the mouse being over it. When in reality it should wait for the label input to be unfocused.

**Comment by DevL0rd** [comment]
> > > When editing somethings label, every now and then backspace will delete the thing i'm editing.
> > 
> > 
> > I can relate to this. Sometimes when I am editing the label, it seems that the keyboard input is not completely captured. For example, when I tries to enter 'Q' in the label it pops up the "edit bit width" window, though the input 'Q' is actually appended to the label as well. In case of backspace, it just deletes the circuit altogether. But I cannot find a way to consistently reproduce the bug. Sometime it works and sometimes it just breaks.
> 
> The Backspace Feature has been enabled in #952 .

This is unrelated to the removal of objects while editing label properties I THINK, not 100%.
I believe it has to do with not checking weather the label input is not focused before focusing the simulator.
