### ISSUE TITLE
NavBar issues on mobile site

### ISSUE THREAD

**Issue by dkapur17** [CircuitVerse/CircuitVerse#936]
**Bug Description**

The NavBar has some issues while viewing in the mobile device. Firstly, on the landing page, due to the pagination container, the NavBar overflows off the screen and one must swipe to the right to be able to access the hamburger.

Also on the other pages, the hamburger may appear below the Nav-Brand item based on the screen size of the viewing device. This is probably because of the padding in the Nav-Bar.

**To Reproduce**

1. Go to [circuitverse.org](circuitverse.org) on a mobile device.
2. See the error.

**Expected behavior**

The NavBar should not overflow and the Nav-Brand and hamburger should be on opposite ends of the screen for all pages.

**Screenshots**

Screenshot of the landing page, showing the NavBar overflow.

![NavBar Issue 1](https://user-images.githubusercontent.com/37783178/75135027-317e4300-5706-11ea-87a6-16d85a5373c3.png)

Screenshot of the NavBar on any other page when viewed in mobile view.

![NavBar Issue 2](https://user-images.githubusercontent.com/37783178/75134856-938a7880-5705-11ea-8455-ce9b8cded154.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Google Chrome]
 - Version [79.0.3945.130]

**Additional context**
This bug has been brought up in Issue #540 , but has not been handled. I'm new to Open Source so I was unsure whether to continue on that thread or to start a new one.

**Are you working on this issue? (Yes/No)**
I would like to fix this bug.

Cheers.

**Comment by shubhankarsharma00** [comment]
@dkapur17 it's always better to open a PR on existing issues. It's been bought up  If you can solve that issue I think it would be best if you go ahead with a PR for that issue and close this one.in #540 . If you can solve that issue I think it would be best if you go ahead with a PR for that issue and close this one. :v:

**Comment by dkapur17** [comment]
Sure @shubhankarsharma00 . Thanks for the response!
