### ISSUE TITLE
Middle Click to delete a circuit element

### ISSUE THREAD

**Issue by shubhankarsharma00** [CircuitVerse/CircuitVerse#937]
**Is your feature request related to a problem? Please describe.**
feature requested in https://github.com/CircuitVerse/CircuitVerse/issues/935#issue-569672715 

**Describe the solution you'd like**
Middle Click to delete a circuit element

**Describe alternatives you've considered**
Some might feel `Del` is enough but middle click to delete is a nice feature to have.

**Additional context**

**Are you working on this? (Yes/No)**
I can (but comment below if you want to claim).

**Comment by Shivansh2407** [comment]
I would like to work on this @shubhankarsharma00  :+1:

**Comment by DevL0rd** [comment]
Thanks I'd really love it. I'm growing the bug list as i work on my 16 bit computer. Man it is really frustrating with the issues right now but I love it so much I'm goign to stick with it. Thanks for the work guys.

**Comment by DevL0rd** [comment]
@Shivansh2407 Hey your working in the simulators control events. can you point me to this part of the code so i can start contributing and fixing these issues? I have not look at the code base once but it woul be a good place to start and work my way deeper.

**Comment by DevL0rd** [comment]
And i'm immediately redesigning this editor and making a dark theme and adding some more in depth graphics settings. lol

**Comment by Shivansh2407** [comment]
> @Shivansh2407 Hey your working in the simulators control events. can you point me to this part of the code so i can start contributing and fixing these issues? I have not look at the code base once but it woul be a good place to start and work my way deeper.

Yes @DevL0rd I am working to fix this issue . Will open up a PR soon .

**Comment by satu0king** [comment]
Middle click to delete sounds interesting but most users wouldn't expect it. I am not sure about this change.

**Comment by shubhankarsharma00** [comment]
Hmm, I agree that it won't be intuitive to users who don't use middle click to close browser windows and someone might delete their circuit by mistake. I guess we should add this feature later, once we can manage simulator shortcuts so a user can toggle between the option according to his preference.
