### ISSUE TITLE
Overlapping of circuit elements.

### ISSUE THREAD

**Issue by swarali15** [CircuitVerse/CircuitVerse#951]
**Is your feature request related to a problem? Please describe.**
When circuit elements are placed one on the top of the other ,the newly added element should align itself with respect to other such that there is no overlapping.
**Describe the solution you'd like**
If the newly added circuit element overlaps the previously added element ,the newly added circuit should get aligned with proper spacing.

**Describe alternatives you've considered**

Screenshot:
![image](https://user-images.githubusercontent.com/51054329/75306771-06176780-5870-11ea-9d45-b4d5f70a052e.png)

**Are you working on this? (Yes/No)** Yes

**Comment by KaustubhDamania** [comment]
Is this issue still open? I'd like to work on it.

**Comment by swarali15** [comment]
> Is this issue still open? I'd like to work on it.
Yes the issue is open...But I am working on it...
