### ISSUE TITLE
Stepper does not work in Preview/Embed mode

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#96]
Steppers do not seem to be responding to keyboard events in the preview window, even thou they appear selected when you click on them.

Repro:
- Navigate to a project that uses steppers, ex: https://circuitverse.org/users/1935/projects/5524
- In the preview pane, click one of the steppers (in this case, one of the two squares inside the pixel art box)
  - Stepper becomes yellow, indicating it is selected.
- Press up/down

Expected:
- For steppers to change value, as it happens in design mode.

Actual:
- No response from stepper.

**Comment by satu0king** [comment]
This should be easy to fix, by adding the listeners in embedListeners.js

**Comment by Ankitanvesh** [comment]
Hello @satu0king can I take up this issue

**Comment by Ankitanvesh** [comment]
I have had a look at the issue. I wanted to know if it is needed to have the values of the steppers changed by using +,- keys as it happens in design mode or is it needed to have their values changed using up,down keys.

**Comment by fpintos** [comment]
The request in this case is to have the stepper work consistently in both cases. I think it is a good idea to support the arrow keys and -/+ keys as well in both cases.

**Comment by devu1999** [comment]
is this issue still open ?

**Comment by Ankitanvesh** [comment]
I m already working on it.

**Comment by armudgal** [comment]
Hi @devu1999, @Ankitanvesh is working on it :)

**Comment by shubhankarsharma00** [comment]
@armudgal I already sent a pr 2 days ago fixing it

**Comment by armudgal** [comment]
@shubhankarsharma00 Aah, didn't see that, but again please inform us before starting to work on any issue. I have mentioned this before but it becomes really difficult for us to allocate issues that way. 

@Ankitanvesh please talk to @shubhankarsharma00 and figure this out. Thanks

**Comment by Ankitanvesh** [comment]
@shubhankarsharma00 is trying to fix the original issue. Although I have been working on the issue plus the suggestion to add the arrowkeys for updating values of the steppers. I will leave it to @shubhankarsharma00 to fix the issue while I work on adding the arrowkey feature. Is it fine to continue that way @armudga.l

**Comment by armudgal** [comment]
Sure, just wait for the other PR to get merged so that there are no conflicts :)
