### ISSUE TITLE
Multi-Lingual Support

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#963]
Recently I made a [poll on slack](https://circuitverse-team.slack.com/archives/CJTJJ6XN0/p1581680032055200) asking if Multi-Lingual support is needed, The poll result was `3.1/5` which means that the community is mostly neutral with slight support to implementing this feature

![image](https://user-images.githubusercontent.com/23432278/75447892-80c4ad80-596a-11ea-82f9-e8f0ca24089b.png)

I won't write info about the implementation here cause there is the tone of info in these docs:

**Additional Informations**
[Research for Multi-Lingual Support](https://docs.google.com/document/d/1yj-9z6mQG_O5VrDbk3m1MlNtwu9_3MOUxqdp4F-9UAM/edit?usp=sharing) by @MrBartusek 
[Multiple Language Support](https://drive.google.com/open?id=1udBfHa-oTLOaiZmYwBw8hjdtg9_b6lxc) by @JoshHeng

**Are you working on this? (Yes/No)**
No

**Comment by harshgujrati** [comment]
Can i work on this @nitin10s  @tachyons

**Comment by nitin10s** [comment]
Sure
