### ISSUE TITLE
Keep connection point fixed when changing bit width of input and output elements

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#97]
When you change the bit width of an input or output element its position is adjusted so that the middle of the element stays the same.

This causes a disruption in the circuit layout when the connection point is to the right or the left of the element and usually requires one to go and move the element back into a better position. It can even happen that the connection point ends up on top of another line, in which case when we move it back we end up with an undesired connection.

My suggestion would be to anchor the connection point when changing the bitwidth, not the middle of the element. This way, increasing the bitwidth of an element whose connection is on the right will make it grow to the left and vice-versa; this way there will be no change in where the element is connected and therefore no chance of introducing an undesired connection.

**Comment by satu0king** [comment]
Yes, that is a good idea, this can be done. 

Steps to do it

1. In changeBitWidth() function in Input/Output element, calculate the positions of new and old position
1. Move the circuit element by that much

**Comment by fpintos** [comment]
I'm fixing this one.
