### ISSUE TITLE
Outline not working properly in `/user/:id`

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#972]
**Describe the bug**
Outline on the user page is not rounded (but it should) and have wired white strip

**Screenshots**

![image](https://user-images.githubusercontent.com/23432278/75571670-f196c300-5a59-11ea-9267-82c208ef1fb1.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
I would like to work on this 👍

**Comment by abstrekt** [comment]
I'd love to work on it!

**Comment by MrBartusek** [comment]
@abstrekt 
@Shivansh2407 Is working on it

**Comment by abstrekt** [comment]
ok, I'll look for something else
