### ISSUE TITLE
Footer not sticking to the bottom of the page of small pages

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#973]
### This issue is partially fixed, please read the whole thread

---

**Describe the bug**
The footer should always be on the bottom of the page 

**Screenshots**

![image](https://user-images.githubusercontent.com/23432278/75571895-62d67600-5a5a-11ea-9575-0e9fecc637d2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by abstrekt** [comment]
I'd like to work on this issue :)

**Comment by abstrekt** [comment]
I am unable to reproduce this issue.. the footer seemed to be at the bottom when i ran it in my system

**Comment by abstrekt** [comment]
is the issue solved?

**Comment by MrBartusek** [comment]
@abstrekt I don't think so, check favourite projects

**Comment by abstrekt** [comment]
* Footer was in its right place, seemed off in place due to empty content
* Checked adding favourties, footer stay at bottom
## Screenshot
![issue footer](https://user-images.githubusercontent.com/42478217/75764441-dbdc1300-5d63-11ea-9a89-ae64b9115603.png)

please review @MrBartusek , Shall add a few more pixels to it?

**Comment by abstrekt** [comment]
## screenshot latest commit
![footer fix](https://user-images.githubusercontent.com/42478217/75775931-ff5d8880-5d78-11ea-86a6-b5cc20f1a55e.png)

**Comment by abstrekt** [comment]
This issue was solved, forgot to add fixes, you can close this issue.

**Comment by MrBartusek** [comment]
@abstrekt
Found same issue on `/notifications`
![image](https://user-images.githubusercontent.com/23432278/76141007-a899cc80-6060-11ea-9579-b83b051d7cdc.png)

**Comment by MrBartusek** [comment]
@tachyons can you re-open?

**Comment by abstrekt** [comment]
> @abstrekt
> Found same issue on `/notifications`
> ![image](https://user-images.githubusercontent.com/23432278/76141007-a899cc80-6060-11ea-9579-b83b051d7cdc.png)

I'll recheck all pages today.
