### ISSUE TITLE
Images stretched out on `/teachers`

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#974]
**Describe the bug**
For an example, first image is stretched from `115px` to `150px`

**Screenshots**

![image](https://user-images.githubusercontent.com/23432278/75572451-193a5b00-5a5b-11ea-9a5f-9a2dca3e52ae.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by Ananthavijay** [comment]
@MrBartusek This is not a valid issue, these images will be replaced once the pages are complete

**Comment by MrBartusek** [comment]
@Ananthavijay page is completed only those images are out of place but still, they should be changed asap if we plan to launch new UI in 2 days

**Comment by Ananthavijay** [comment]
> @MrBartusek I think these images will be replaced once the pages are complete

I meant the other pages. The images are of old UI

**Comment by Ananthavijay** [comment]
@MrBartusek see this [comment](https://github.com/CircuitVerse/CircuitVerse/pull/933#pullrequestreview-363630386)

**Comment by MrBartusek** [comment]
@Ananthavijay Ok, but still, will keep issue as a reminder that we need to do it before launch

**Comment by abstrekt** [comment]
This issue was solved, forgot to added fixes, you can close this issue.

**Comment by Ananthavijay** [comment]
@tachyons This issue can be closed.
