### ISSUE TITLE
Footer links redirect to `circuitverse.org` instead to the relative page

### ISSUE THREAD

**Issue by MrBartusek** [CircuitVerse/CircuitVerse#975]
**Describe the bug**

`About` link should redirect to `/about` but for now it is redirecting to `circuitverse.org/about`

**Links that should be changed to a relative:**  
- Simulator
- Examples
- Login
- Contribute
- Teachers
- About
- Social Media

**Links that should be kept cause they redirect to subdomain:** 
- Learn
- Documentation

**Is fix needed?** [Yes](https://github.com/CircuitVerse/CircuitVerse/pull/783#issuecomment-570438697).

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Vivaldi (chromium)

**Are you working on this issue? (Yes/No)**
No

**Comment by Shivansh2407** [comment]
Can you please explain more on this @MrBartusek ?

**Comment by MrBartusek** [comment]
@Shivansh2407 
![image](https://user-images.githubusercontent.com/23432278/75573919-20169d00-5a5e-11ea-82fc-4556dc4ef9e5.png)
It shouldn't redirect to the main page when running on localhost rather it should redirect to the local copy

**Comment by Ananthavijay** [comment]
@Shivansh2407 Are u working on this or can I open a PR?

**Comment by Shivansh2407** [comment]
> @Shivansh2407 Are u working on this or can I open a PR?

@Ananthavijay actually I am busy with my exams so go ahead and make a PR.
