### ISSUE TITLE
Update Deadline Bugs

### ISSUE THREAD

**Issue by Miftahunajat** [CircuitVerse/CircuitVerse#978]
**Describe the bug**
When the teacher changes the deadline of an assignment to the time before the current time at the moment then we get redirected to the next page and the edit button still hasn't changed to 'Reopen'. Must be refreshed first

**To Reproduce**
1. Go to 'circuitverse.org'
2. Login
3. Open your groups
2. Click on 'Edit' in the one of the group
3. Change the deadline to earlier than now
4. Click on 'Update Assignment' (it still show edit)
5. Click on 'Edit'
6. See the error

**Expected behavior**
The button in update assignment changed to be Reopen, no need to refresh

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.1 Cinnamont 64-bit
 - Browser Chrome
 - Version 73

**Additional context**
-

**Are you working on this issue? (Yes/No)**
Yes

**Comment by Miftahunajat** [comment]
I think this Issue can be closed because of choosing a date before earlier than now. In the new display of Circuitverse no longer be activated

**Comment by Ananthavijay** [comment]
@tachyons This can be closed.
