### ISSUE TITLE
Automatic inference of bitwidths

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#98]
Would it be possible for element to automatically infer the bitwidth of their inputs?
Perhaps the bitwidth value could have an "auto" value.

For some elements this should be simple:

- An Output element would simply pick up the bitwidth of the line it is connected to.
- Gates would automatically infer the bitwidth if all input lines are the same width and error out otherwise.
- Similar for the data input/output of decoders/multiplexers/flip-flops and others.
  - Maybe the same inference could be applied to the control signal, although this could cause trouble since a change in control signal size ends up changing the layout of decoders/multiplexers.
 - Input elements obviously need to specify their bitwidth since they themselves have no input.
  - That being said, suppose an input could be set to automatic as well; in this case an input exposed by a sub-circuit would inherit the bitwidth from the parent circuit.

This would allow us to create circuits that are more generic and reusable, since each instance could take a different set of bitwidth values.

**Comment by satu0king** [comment]
Haha, you mean template circuit elements like template functions in C++ or Java. Thanks! that is in Interesting idea. Implementing this would require some major planning and testing. I will mark this is a future feature.

**Comment by fpintos** [comment]
I have a simple fix for the OUTPUT element, which makes it inherit the bitWidth of its input signal automatically. I'll try to generalize before sending the PR.

**Comment by fpintos** [comment]
@satu0king , the solution I have seems to work generically, so we can implement inference in different components with different rules for each.

Here is the proposal:
- Elements will optionally implement a `onBitWidthError` callback. This callback will receive an offending node (which will be one of its children) and the expected bitWidth, which will be determined by the external node connected to the offending node.
- When a node is resolving itself (in `Node.prototype.resolve`) it currently looks at its connections and when it detects a bitWidth mismatch we show the error; with the fix, we will first detect the bitWidth mismatch between the current node and its connection and then invoke the parent of the offending node, effectively giving the element a chance to correct itself.
- In any case, after the callback returns we go thru the logic as-is today, so if the component has corrected itself things just work and if not, we show the error as usual.

In terms of code, the core change is simple - we call this inside the for-loop in `Node.prototype.resolve`:
```js
        let node = this.connections[i];
        // If we detect a bitWidth mismatch, give the parent element a chance to correct itself.
        if (node.bitWidth != this.bitWidth && node.parent.onBitWidthError) {
            node.parent.onBitWidthError(node, this.bitWidth);
        }
        if (node.value != this.value) { ... // as usual
```

Then, each component that can correct itself implements `onBitWidthError`. For example, `Output` can simply do this:
```js
Output.prototype.onBitWidthError = function(node, expectedBitWidth) {
    this.newBitWidth(expectedBitWidth);
}
```

I'm looking to see which other components will benefit from this; for example, the gates could correct themselves if there's only one connected input or if all inputs have the same bitWidth (different from the gate bitWidth itself).

**Comment by satu0king** [comment]
This seems to be a suitable approach. We can handle each case separately and only support a few of the elements initially.

**Comment by ankur54** [comment]
The idea seems really interesting to me. Can I work on this issue? GSOC '19
