### ISSUE TITLE
No of Views can be easily increased by requesting page in a loop by curl or something else

### ISSUE THREAD

**Issue by ciphereck** [CircuitVerse/CircuitVerse#982]
**Describe the bug**
I request to get this page in the browser https://circuitverse.org/users/18390/projects/56841 and saw no of views increase by one. But then I added a for loop in a shell script to make a curl request again and again, and it's increasing no of views. 
Suppose a person creates a project, he/she can easily increase their number of views using multiple iterations of making that request from command line or javascript.

**To Reproduce**
1. Go to 'Terminal
2. write command: "for ((i=0; i<=10;i++)); do curl https://circuitverse.org/users/18390/projects/56841; done"
3. Check that the number of views got increased by same amount by visiting https://circuitverse.org/users/18390/projects/56841

**Expected behavior**
A user must not be able to increase its number of views like this, not at least this easily.

**Screenshots**
I did the same to increase the number of views of a project from 25 to 296.
![1](https://user-images.githubusercontent.com/24265219/75621023-924dc580-5bb5-11ea-9c8d-69d4b91f882f.png)
![2](https://user-images.githubusercontent.com/24265219/75621024-9679e300-5bb5-11ea-87de-76848be00038.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome
 - Version Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**
If we use a number of views to find trending projects, it's going to create a lot of problems there.

**Are you working on this issue? (Yes/No)**, 
Maybe, depending on the expertise needed.

**Comment by KaustubhDamania** [comment]
Maybe this issue can be fixed by incrementing the views count only if the session id encountered is new :thinking:

**Comment by tachyons** [comment]
https://github.com/CircuitVerse/CircuitVerse/pull/414

**Comment by pranavmodx** [comment]
I would like try this issue. If someone could give me a head start on the section of code handling user views count, it would be great.

**Comment by ciphereck** [comment]
Hi @pranavmodx 
Sorry for the late reply. Check #414 PR, it contains some work, maybe you can take it from there.

**Comment by Ananthavijay** [comment]
@tachyons this can be closed.

**Comment by ciphereck** [comment]
@Ananthavijay yeah sure. Now it can after Or #1346
