### ISSUE TITLE
Buffer remembers previous output when input is X

### ISSUE THREAD

**Issue by fpintos** [CircuitVerse/CircuitVerse#99]
I might be wrong on this one...

When I think of "Buffer" I think of an element that simply outputs its input as-is.

But the one in CircuitVerse has a memory - if the input becomes X the Buffer will output the last non-X input it received. By combining a TriState with a Buffer we effectively create a memory cell similar to a D-Latch.

Is that intentional?

Maybe it is, since the Buffer has a Reset input; it just seems odd...

**Comment by satu0king** [comment]
Yeah, it is intentional. Probably the name is incorrect. The idea is that it remembers the last input, hence it buffers the data. 

> By combining a TriState with a Buffer we effectively create a memory cell similar to a D-Latch.

It was implemented partially for this use because, at the time, feedback loops were not supported. 

Maybe we should deprecate this element.
