### ISSUE TITLE
Update CircuitVerse logo in the Readme file

### ISSUE THREAD

**Issue by Ananthavijay** [CircuitVerse/CircuitVerse#994]
**Describe the bug**
The logo in the readme file is the old one.

**To Reproduce**
1. Go to 'readme.md'
2. See error

**Expected behavior**
The old logo should be replaced with the new one

**Are you working on this issue? (Yes/No)**
No

**Comment by abstrekt** [comment]
I will work on it!

**Comment by shubhankarsharma00** [comment]
@abstrekt the logo is available #ux channel in slack.

**Comment by AsaoluElijah** [comment]
Hi @abstrekt are you still working on this?
